### ISSUE TITLE
Icons are not displayed when using with kivy-ios

### ISSUE THREAD

**Issue by olek5andr** [kivymd/KivyMD#1006]
The app starts and runs but all the icons are not being displayed.
I'm installing kivymd using toolchain like this:

'toolchain pip install https://github.com/kivymd/KivyMD/archive/master.zip'

(Please note: 'toolchain pip install kivymd' has the same issue)

I'm using

kivy-ios = master
kivy = b5ec51ed2315a9a890f264b0df6d23c8e6341d42 (that's the recipe available in the toolchain)
sdl2_ttf = 2.0.14  (that's the recipe available in the toolchain)

Thanks in advance!

**Comment by valkorlive** [comment]
I just replaced version in

**venv/lib/python3.8/site-packages/kivy_ios/recipes/sdl2_ttf/__init__.py**

`version = "2.0.14"`

to

`version = "2.0.15"`

And rebuild sdl2_ttf:
```
toolchain clean sdl2_ttf
toolchain build sdl2_ttf
```

**Comment by HeaTTheatR** [comment]
@valkorlive 
What is the result? It works? Are the icons displayed?

**Comment by valkorlive** [comment]
> @valkorlive
> What is the result? It works? Are the icons displayed?

Yes, it helped me, the icons displayed.

**Comment by HeaTTheatR** [comment]
@valkorlive Thanks for report!
