### ISSUE TITLE
refresh layout orientation issue

### ISSUE THREAD

**Issue by surbhicis** [kivymd/KivyMD#101]
on my phone the refresh isn't triggered by swiping top to bottom but right to left as I am using kivymd repo of this repository

**Comment by HeaTTheatR** [comment]
Show me how you do it

**Comment by surbhicis** [comment]
https://streamable.com/u48i7 check this please

**Comment by ArtemSBulgakov** [comment]
@surbhicis Does the same behavior happen in kitchen_sink? Say your phone model and OS version

**Comment by surbhicis** [comment]
Does the same behavior happen in kitchen_sink :: Incase of Desktop app it is working and for android I didnt check yet for kitchen sink build.

Model:: Moto e5 plus 
OS version :: 8.0.0

Check this as well :: https://ibb.co/N1DH3GF

**Comment by HeaTTheatR** [comment]
@surbhicis I will create a virtual machine with your device and test this behavior

**Comment by surbhicis** [comment]
thanks :)

**Comment by PeterSurda** [comment]
Same problem on Moto G4 Play (harpia), microg lineageos 14.1 (Android 7.1.2)

**Comment by surbhicis** [comment]
@HeaTTheatR  if you want we can also provide you an apk so that you will notice issue better way?

**Comment by HeaTTheatR** [comment]
@surbhicis Send me a package...

**Comment by surbhicis** [comment]
@HeaTTheatR 

Please find the link for download apk package

https://drive.cisinlive.com/index.php/s/UeTer5FtNNxVWMc

Password :  j9X6PkcG

**Comment by HeaTTheatR** [comment]
RefreshLayout only works with lists!

**Comment by surbhicis** [comment]
@HeaTTheatR I am using MDList so what an issue in this?
check this please #########

https://pastebin.com/sR0QgNDx

**Comment by HeaTTheatR** [comment]
@surbhicis https://github.com/HeaTTheatR/KivyMD/wiki/Components-Refresh-Layout
