### ISSUE TITLE
MDRaisedButton  critical clock 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1011]
### Description of the Bug
When i am adding code below this problem showing .
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute

### Code and Logs

```python
BoxLayout:
			size_hint_y: None
			height: '35dp'
			spacing:'5dp'
			MDRaisedButton:
				size_hint: (1, 1)
				text:'PREVIOUS'
				on_release:
					#root.parent.transition.direction = 'right'
					#root.parent.current=root.parent.previous()
			MDRaisedButton:
				size_hint: (1, 1)
				text:'CLEAR'
				#on_release:root.clear_cbox()
			MDRaisedButton:
				size_hint: (1, 1)
				text:'SAVE & NEXT'
				on_release:
					#root.lock_cbox()
					#root.parent.transition.direction = 'left'
					#root.parent.current=root.parent.next()
			MDRaisedButton:
				size_hint: (1, 1)
				text:'NEXT'
				on_release:
					#root.parent.transition.direction = 'left'
					#root.parent.current=root.parent.next()
			
		
```

### Versions

* OS: kubuntu 18.04
* Python: 3.6.9
* Kivy: 2.0.0
* KivyMD:0.104.2   git-bc7d1f5,

**Comment by Sahil-pixel** [comment]
this error not showing after removing .
size_hint:(1,1) in MDRaisedButton

**Comment by bskora** [comment]
Can confirm that this actually breaks any button with a size_hint as (1, 1). Have not tried in BoxLayout, but the same issue occurs with GridLayout. There is a current workaround that I found. If you set the size_hint via .py file before the screen, this error does not occur.

**Versions**
>OS: Windows 10
>Python: 3.9.4
>Kivy: 2.0.0
>KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
This code works correctly. Please create a new issue that reproduces the behavior you are talking about.

**Comment by Amyantis** [comment]
Same issue here: removing `size_hint` from `MDRaisedButton` does remove the warnings.

**Comment by Amyantis** [comment]
I think the warning shows if:

1. The button is added to a screen that is not currently displayed.
2. The button is a child of a BoxLayout with padding>0.

Here is a reproducible example:
```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen


class ScreenA(MDScreen):
    pass


class ScreenB(MDScreen):
    pass


KV = """
<ScreenA>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        MDLabel:
            text: "Hello world A!"
        MDRaisedButton:
            text: "Go world B"
            size_hint_x: 1.0
            on_press: app.root.ids.screen_manager.current = "ScreenB"
            
<ScreenB>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        MDLabel:
            text: "Hello world B!"
        MDRaisedButton:
            text: "Go world A"
            size_hint_x: 1.0
            on_press: app.root.ids.screen_manager.current = "ScreenA"
            
Screen:
    ScreenManager:
        id: screen_manager
        ScreenA:
            name: "ScreenA"
        ScreenB:
            name: "ScreenB"
"""


class MyMDApp(MDApp):
    def build(self):
        return Builder.load_string(KV)


if __name__ == "__main__":
    MyMDApp().run()
```


My config:
1. Ubuntu 20.04.3
2. Python 3.8.10
3. kivy 2.0.0
4. kivymd 0.104.2
