### ISSUE TITLE
App crashes when start in phone

### ISSUE THREAD

**Issue by kostochki238** [kivymd/KivyMD#1012]
Files: https://github.com/kostochki238/my_arduino_app
Phone: ZTE Blade A7 2020
Python: 3.9.2

**Comment by HeaTTheatR** [comment]
@kostochki238 When creating a issue, follow the prompts that are written in the form of creating a new issue - https://github.com/kivymd/KivyMD/issues/new?assignees=&labels=&template=bug_report.md&title=
