### ISSUE TITLE
`ListItem` click bug

### ISSUE THREAD

**Issue by Neizvestnyj** [kivymd/KivyMD#1013]
When you click on a list item (`OneLineListItem` and the like), you may get a completely different item than the one you click on, or even several.

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.list import OneLineListItem

KV = '''
ScrollView:

    MDList:
        id: container
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for i in range(20):
            self.root.ids.container.add_widget(
                OneLineListItem(text=f"Single-line item {i}")
            )

Test().run()
```

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Your code example does not show any problems. Add logs, videos, console output, etc.

**Comment by Neizvestnyj** [comment]
This error occurred on a `Raspberry pi` without a virtual environment, I think this is the case
