### ISSUE TITLE
Bug with the color of the disabled button

### ISSUE THREAD

**Issue by Neizvestnyj** [kivymd/KivyMD#1028]
When changing the theme from light to dark, the color of the disabled button turns black. If you restart the application and set a dark theme during initialization, and then change it to a light one, the button color will be white.

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'Disabled button'
        disabled: True
        
    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
'''


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        return Builder.load_string(KV)

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'


Test().run()
```

https://user-images.githubusercontent.com/40869738/124393674-40b2cf00-dd04-11eb-99ca-31de0bbe2c08.mp4

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I'm not really sure what practical value the example you gave is??

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj I'm not really sure what practical value the example you gave is??

I added video

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I don't see the point in the code example you attached ...

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj I don't see the point in the code example you attached ...

the color of the disabled button is different: gray, white, black

**Comment by HeaTTheatR** [comment]
@Neizvestnyj The code you showed as an example cannot be applied in practice. This example is simply useless.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj The code you showed as an example cannot be applied in practice. This example is simply useless.

This example is made so as not to manually restart the application. In fact, this is enough.

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'Disabled button'
        disabled: True
        
    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'


Test().run()
```

**Comment by HeaTTheatR** [comment]
@Neizvestnyj This is not enough for me. I don't see any practical use for your example code...

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj This is not enough for me. I don't see any practical use for your example code...

I just change the theme of the application, and for some reason the color of the blocked button changes with it

**Comment by Neizvestnyj** [comment]
https://user-images.githubusercontent.com/40869738/124396128-7e1d5980-dd10-11eb-908e-f9cb27f7ca4c.mp4

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I don't see any errors in the last video. The color of the button in the `disabled` state depends on the type of theme: light theme or dark

**Comment by Neizvestnyj** [comment]
> I don't see any errors in the last video. The color of the button in the `disabled` state depends on the type of theme: light theme or dark

But why it can be like: black-dark theme, white-light theme, or gray-at startup. Something's wrong

**Comment by Neizvestnyj** [comment]
https://user-images.githubusercontent.com/40869738/124397620-a198d200-dd19-11eb-83fc-c59ba4148401.mp4

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'text'
        disabled: True
        
    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
        
    MDRoundFlatIconButton:
        text: 'Restart'
        pos_hint: {"center_x": .5, "center_y": .3}
        on_release: app.restart()
'''


def run_app(theme=None):
    Test(theme).run()


class Test(MDApp):
    def __init__(self, theme=None, **kwargs):
        super().__init__(**kwargs)
        if theme:
            self.theme_cls.theme_style = theme

    def build(self):
        return Builder.load_string(KV)

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'

    def restart(self):
        self.stop()
        run_app(self.theme_cls.theme_style)


run_app('Light')
```


Your code example is completely useless for practical purposes.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj
> 
> ```python
> from kivy.lang import Builder
> 
> from kivymd.app import MDApp
> 
> KV = '''
> Screen:
>     MDRoundFlatIconButton:
>         pos_hint: {"center_x": .5, "center_y": .5}
>         text: 'text'
>         disabled: True
>         
>     MDRoundFlatIconButton:
>         text: 'Change theme'
>         pos_hint: {"center_x": .5, "center_y": .4}
>         on_release: app.change_theme()
>         
>     MDRoundFlatIconButton:
>         text: 'Restart'
>         pos_hint: {"center_x": .5, "center_y": .3}
>         on_release: app.restart()
> '''
> 
> 
> def run_app(theme=None):
>     Test(theme).run()
> 
> 
> class Test(MDApp):
>     def __init__(self, theme=None, **kwargs):
>         super().__init__(**kwargs)
>         if theme:
>             self.theme_cls.theme_style = theme
> 
>     def build(self):
>         return Builder.load_string(KV)
> 
>     def change_theme(self):
>         if self.theme_cls.theme_style == 'Light':
>             self.theme_cls.theme_style = 'Dark'
>         else:
>             self.theme_cls.theme_style = 'Light'
> 
>     def restart(self):
>         self.stop()
>         run_app(self.theme_cls.theme_style)
> 
> 
> run_app('Light')
> ```
> 
> Your code example is completely useless for practical purposes.

I sent you another one and made a video

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I don’t understand what you want to tell me.

**Comment by Neizvestnyj** [comment]
Colors of the locked button - 3! And sometimes text missing. [See](https://github.com/kivymd/KivyMD/issues/1028#issuecomment-873650384)

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Show me some example code that reproduces this behavior.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj Show me some example code that reproduces this behavior.

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'Disabled button'
        disabled: True
        
    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
'''


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        return Builder.load_string(KV)

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'


Test().run()
```

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 

https://github.com/kivymd/KivyMD/issues/1028#issuecomment-873643368

https://user-images.githubusercontent.com/16930280/124398701-c42de980-dd1f-11eb-9439-f0e65d809e28.mov

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj
> 
> [#1028 (comment)](https://github.com/kivymd/KivyMD/issues/1028#issuecomment-873643368)
> 
>  2021-07-04.23.29.28.mov

Try this. You will see that the background of the button has turned white and the text has disappeared

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'Disabled button'
        disabled: True
        
    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
'''


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = 'Light'
        return Builder.load_string(KV)

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'


Test().run()
```

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I have tried running exactly this example code.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj I have tried running exactly this example code.

Here the basic theme is light, and there it is dark, that's the difference.

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I do not understand what you are talking about.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj I do not understand what you are talking about.

Just run the last example and you will see everything.  Or watch this [video](https://github.com/kivymd/KivyMD/issues/1028#issuecomment-873650384)

**Comment by HeaTTheatR** [comment]
@Neizvestnyj The topic is closed.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj The topic is closed.

The main thing is that you see this bug. If I have time I will fix it

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I don't see any errors.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj I don't see any errors.

Have you watched my video?  The text at the end is clearly missing.  If the basic theme is light, then the color of the locked button is gray, when in a running application we switch to dark, its color changes to black.  If the basic theme is dark, then the color of the (locked) button is gray, if inside the application we change the theme to a light one, then the background becomes light. How illogical. There should then be no intermediate gray

**Comment by HeaTTheatR** [comment]
@Neizvestnyj 

 I don't see any errors.

https://user-images.githubusercontent.com/16930280/124399272-f725ac80-dd22-11eb-85e0-b2864d54d4dc.mov

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj
> 
> I don't see any errors.
> 
>  2021-07-04.23.52.19.mov

As for me, it's just strange that, depending on the starting base theme, when switching to another, two backgrounds change (gray - black, gray-white), why not (white-black), as for me it is illogical

**Comment by SpecDaTurtle** [comment]
@Neizvestnyj @HeaTTheatR 
When the app is first started up in light mode the text is set to blue

When the app is first started up in dark mode the text is set to white.

If the disabled button's default colour is grey in dark mode it will be made lighter if the theme is switched light. 

If the disabled button's default color is grey in light mode then it will be made darker if the theme is switched to dark.

The two above statements make obvious sense.

Things to note here:
When started with light mode, text cannot be white so the text takes on the theme primary color( in this case its blue).
when started with dark mode, text can be white so that is what the text color is set to.

With that said, the text color never changes during the course of the running program unless done explicitly!
(it will only change during reset in this program)

This can be considered a bug if you want, however light and dark modes should be set along side the other theme color settings to achieve a clean look :)

The fix is simple. Set your text color of buttons to your theme primary_color to maintain their color.  See example below:
Note* Run this and mess with it as much as you want and try to break it in runtime. I Dare You ;)
```Python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:
    MDRoundFlatIconButton:
        id: button
        pos_hint: {"center_x": .5, "center_y": .6}
        text: 'text'
        disabled: True
        text_color: app.theme_cls.primary_color
    
    MDRoundFlatIconButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: 'text'
        text_color: app.theme_cls.primary_color
        on_release: app.enable_disable()

    MDRoundFlatIconButton:
        text: 'Change theme'
        pos_hint: {"center_x": .5, "center_y": .4}
        on_release: app.change_theme()
        text_color: app.theme_cls.primary_color

    MDRoundFlatIconButton:
        text: 'Restart'
        pos_hint: {"center_x": .5, "center_y": .3}
        on_release: app.restart()
        text_color: app.theme_cls.primary_color
'''


def run_app(theme=None):
    Test(theme).run()


class Test(MDApp):
    def __init__(self, theme=None, **kwargs):
        super().__init__(**kwargs)
        self.theme_cls.primary_palette = "Blue"
        self.theme_cls.accent_palette = "Gray"
        self.screen = Builder.load_string(KV)
        if theme:
            self.theme_cls.theme_style = theme

    def build(self):
        return self.screen

    def change_theme(self):
        if self.theme_cls.theme_style == 'Light':
            self.theme_cls.theme_style = 'Dark'
        else:
            self.theme_cls.theme_style = 'Light'

    def restart(self):
        self.stop()
        run_app(self.theme_cls.theme_style)

    def enable_disable(self):
        button = self.screen.ids.button

        if button.disabled:
            button.disabled = False
        else:
            button.disabled = True


run_app('Light')


```
or let them alternate by modifying your python code to set their colors based on the active theme.

Side Note:
If we are talking about disabled buttons... Lets put it this way, they are supposed to not be noticeable and so they match the theme color. which is the way material design expects it to be. So on that note you cant really call it a bug lol.

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj @HeaTTheatR
> When the app is first started up in light mode the text is set to blue
> 
> When the app is first started up in dark mode the text is set to white.
> 
> If the disabled button's default colour is grey in dark mode it will be made lighter if the theme is switched light.
> 
> If the disabled button's default color is grey in light mode then it will be made darker if the theme is switched to dark.
> 
> The two above statements make obvious sense.
> 
> Things to note here:
> When started with light mode, text cannot be white so the text takes on the theme primary color( in this case its blue).
> when started with dark mode, text can be white so that is what the text color is set to.
> 
> With that said, the text color never changes during the course of the running program unless done explicitly!
> (it will only change during reset in this program)
> 
> This can be considered a bug if you want, however light and dark modes should be set along side the other theme color settings to achieve a clean look :)
> 
> The fix is simple. Set your text color of buttons to your theme primary_color to maintain their color. See example below:
> Note* Run this and mess with it as much as you want and try to break it in runtime. I Dare You ;)
> 
> ```python
> from kivy.lang import Builder
> 
> from kivymd.app import MDApp
> 
> KV = "'
> Screen:
>  MDRoundFlatIconButton:
>  id: button
>  pos_hint: {"center_x": .5, "center_y": .6}
>  text: 'text'
>  disabled: True
>  text_color: app.theme_cls.primary_color
>     
>  MDRoundFlatIconButton:
>  pos_hint: {"center_x": .5, "center_y": .5}
>  text: 'text'
>  text_color: app.theme_cls.primary_color
>  on_release: app.enable_disable()
> 
>  MDRoundFlatIconButton:
>  text: 'Change theme'
>  pos_hint: {"center_x": .5, "center_y": .4}
>  on_release: app.change_theme()
>  text_color: app.theme_cls.primary_color
> 
>  MDRoundFlatIconButton:
>  text: 'Restart'
>  pos_hint: {"center_x": .5, "center_y": .3}
>  on_release: app.restart()
>  text_color: app.theme_cls.primary_color
> "'
> 
> 
> def run_app(theme=None): Test(theme).run() class Test(MDApp): def __init__(self, theme=None, **kwargs): super().__init__(**kwargs) self.theme_cls.primary_palette = "Blue"
>         self.theme_cls.accent_palette = "Gray"
>         self.screen = Builder.load_string(KV) if theme: self.theme_cls.theme_style = theme
> 
>     def build(self): return self.screen
> 
>     def change_theme(self): if self.theme_cls.theme_style == 'Light': self.theme_cls.theme_style = 'Dark'
>         else: self.theme_cls.theme_style = 'Light'
> 
>     def restart(self): self.stop() run_app(self.theme_cls.theme_style) def enable_disable(self): button = self.screen.ids.button
> 
>         if button.disabled: button.disabled = False
>         else: button.disabled = True
> 
> 
> run_app('Light') 
> ```
> 
> or let them alternate by modifying your python code to set their colors based on the active theme.
> 
> Side Note:
> If we are talking about disabled buttons... Lets put it this way, they are supposed to not be noticeable and so they match the theme color. which is the way material design expects it to be. So on that note you cant really call it a bug lol.

Yuri  said that is a bug) We discussed this in the discord and decided that the topic is closed, and the bug will be fixed later.

https://user-images.githubusercontent.com/40869738/128185754-68e0158e-cf29-4ece-b8f6-90d9bf9d425e.mp4

**Comment by SpecDaTurtle** [comment]
@Neizvestnyj @HeaTTheatR since its a bug then I'm going to assume the button should stay gray? Not a difficult change. Can you confirm what the behaviour should be? Stay gray? Or some other behaviour?

**Comment by Neizvestnyj** [comment]
> @Neizvestnyj @HeaTTheatR since its a bug then I'm going to assume the button should stay gray? Not a difficult change. Can you confirm what the behaviour should be? Stay gray? Or some other behaviour?

As in the MD specification.

**Comment by Noor-Kalibbala** [comment]
Actually i have the same problem while using the development version of kivymd, When u change the theme from dark to white, the text in label widgets becomes invisible, they remain white/gray.

**Comment by HeaTTheatR** [comment]
@Noor-Kalibbala Thanks for report We will fix this shortly.
