### ISSUE TITLE
Kivymd not working in APK and kivy launcher

### ISSUE THREAD

**Issue by Aathithiya** [kivymd/KivyMD#1036]
Kivy MD not working after converting as APK and in kivy launcjer

**Comment by HeaTTheatR** [comment]
@Aathithiya The question is completely incomprehensible.

**Comment by Ahmed212237** [comment]
I have tried the process of converting kivymd and I have successfully made the apk file, but when I upload the apk file to my phone, It just blink a white empty screen for once then exit the app, why does this happen to kivymd?

**Comment by HeaTTheatR** [comment]
@Aathithiya `adb logcat | grep python`
