### ISSUE TITLE
kivymd.utils.cropimage function excluded in pypi kivymd version

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivymd/KivyMD#1048]
when u try to call crop_round_image function in kivymd pypi version, no modulenotfound error is thrown.
`` 
from kivymd.utils.cropimage import crop_round_image
``
it seems this function was not shipped in kivymd.utils class for kivymd version in pypi

**Comment by mp-007** [comment]
cropimage.py file was deleted/removed in kivymd 0.104.2
