### ISSUE TITLE
Spinner can't be added directly from the python code

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#105]
#### Description of the Bug

I tried to solve with a pull request, but my approach wasn't good enough. Before trying to pull another one, I prefer to set this as an Issue.

Whenever you try to add the MDSpinner as a class (self.add_widget(MDSpinner()), you get an IndexError back (see log).

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.spinner import MDSpinner

kv = """
<Testing>:
        orientation: "vertical"
        size_hint: 0.5, 0.5
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
"""
class Testing(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        s = MDSpinner()
        self.add_widget(s)

class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)
        return Testing()


if __name__ == '__main__':
    MainApp().run()
```
Log

``` kivy.lang.builder.BuilderException: Parser: File "<inline>", line 11:
 ...
       9:        Color:
      10:            rgba: self.color
 >>   11:            a: self._alpha
      12:        SmoothLine:
      13:            circle: self.center_x, self.center_y, self.width / 2,            self._angle_start, self._angle_end
 ...
 IndexError: list index out of range
```

In addition to my other approaches, I tried removing the line ``` >>   11:            a: self._alpha``` and it worked, so I think this is another solution I propose, but I don't really know if removing that line will cause any problem to the rest of the code.

I'd really like to help solving this issue, so if you need something, here I am.

### Versions

* OS: not depending on OS
* Python: latest
* Kivy: latest
* KivyMD: latest

**Comment by ArtemSBulgakov** [comment]
See the last commit
https://github.com/HeaTTheatR/KivyMD/commit/49bd42a6a697c831437dae322d7e7b969b5dac09

**Comment by ghost** [comment]
> See the last commit
> [49bd42a](https://github.com/HeaTTheatR/KivyMD/commit/49bd42a6a697c831437dae322d7e7b969b5dac09)

I'm glad one of the approaches worked. Thanks!
