### ISSUE TITLE
Kivymd problem with using Xcode to make iOS app

### ISSUE THREAD

**Issue by joshuam22045** [kivymd/KivyMD#1051]
### Description of the Bug

I am using kivymd to make and publish and ios app and so I created my app in pycharm and everything flawlessly in pycharm, but when I imported my files to xcode and installed kivy-ios I got the error no module "kivymd" and the only way I could fix it was by dragging the kivymd folder from the site packages folder in the venv folder from pycharm, then I got no module 'PIL' so I did the same thing with the PIL folder(and in its version.py folder it says pillow 8.3.1), but then now my app builds in xcode but when I try to run it get the errors shown in the screen shots and I don't understand why. I know it has something to do with the PIL folder but I don't what exactly and I don't know how to fix it. Additionally, the reason I had to fix the module errors by manually dragging the folders in to my app folder was because when I tried using toolchain and pip commands it seemed to work, but still gave the ModuleError when it ran in xcode. I have looked everywhere and cannot find an answer. Additionally, I have seen some people suggest a buildozer.spec file and putting them as requirements but I couldn't figure out how to make it work on mac, so if that is a solution I would need more explanation.

### Code and Logs

I can't post it because the app for my code is close to 7,000 lines long. 

### Screenshots

![Screen Shot 2021-07-24 at 10 06 03 PM](![Screen Shot 2021-07-24 at 10 06 03 PM](https://user-images.githubusercontent.com/71143352/126888560-ccd8f324-ca99-42c1-badb-6449c6e72e7b.png)

### Versions

* OS: macOS Big Sur 11.5
* Python: 3.9.6
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@joshuam22045 https://github.com/kivy/kivy-ios/issues/320

**Comment by joshuam22045** [comment]
The Link you commented didn't work for me as it gives me a syntax error when I put the workaround at the top of my code in pycharm. Additionally, my problem is not that I can't access the kivmd or PIL folders, it is that there is something in the PIL folder that is making it so that where ever I put it, whether that be in my App folder from pycharm or the kivy-ios/dist/root/python3/lib/python3.9 folder it still gives me the error "ImportError: dynamic module does not define module export function (PyInit_imaging)" everytime it runs in xcode but then runs perfectly in pycharm.
