### ISSUE TITLE
Persisting problem with kivymd and PIL running succesfully in Xcode

### ISSUE THREAD

**Issue by joshuam22045** [kivymd/KivyMD#1055]
The Link you commented didn't work for me as it gives me a syntax error when I put the workaround at the top of my code in pycharm. Additionally, my problem is not that I can't access the kivmd or PIL folders, it is that there is something in the PIL folder that is making it so that where ever I put it, whether that be in my App folder from pycharm or the kivy-ios/dist/root/python3/lib/python3.9 folder it still gives me the error "ImportError: dynamic module does not define module export function (PyInit_imaging)" everytime it runs in xcode but then runs perfectly in pycharm.

_Originally posted by @joshuam22045 in https://github.com/kivymd/KivyMD/issues/1051#issuecomment-886999667_

**Comment by HeaTTheatR** [comment]
https://github.com/kivy/kivy-ios/issues/644#issuecomment-996143345
