### ISSUE TITLE
MDDropdownMenu : TypeError: object.__init__() takes exactly one argument

### ISSUE THREAD

**Issue by radiolondra** [kivymd/KivyMD#1057]
### Description of the Bug

I had a perfectly working project with KivyMD version 0.104.1 installed. It was working perfectly, until I updated KivyMD to the latest version (1.00dev from 'pip install https://github.com/kivymd/KivyMD/archive/master.zip').
Now it's not working anymore. It gives 
`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`
when the app is starting, trying to create a couple of `MDDropdownMenu `(see code below).

### Code and Logs

```
class MediaRow(BoxLayout):
   
    # ----------------------------------------------ctor
    def __init__(self, **kwargs):
        super(MediaRow, self).__init__(**kwargs)
        self.video = None
        ....
        ....
        self.audio_items = ["mp3", "m4a", "flac", "wav", "wma", "aac", "aiff"]
        self.video_items = ["mp4", "mov", "webm", "avi", "mkv"]
        self.audio_menu_items = [
            {
                "text": f"{item}",
                "viewclass": "OneLineListItem",
                "height": dp(56),                
            } for item in self.audio_items
        ]

        self.video_menu_items = [
            {
                "text": f"{item}",
                "viewclass": "OneLineListItem",
                "height": dp(56),                
            } for item in self.video_items
        ]

        self.audio_menu = MDDropdownMenu(           
            caller=self.ids.audio_button,
            items=self.audio_menu_items,
            callback=self.audio_menu_callback,
            width_mult=4,
        ) <<<<<<<<<<<<<<<<--------------------------- the error is thrown here!

        self.video_menu = MDDropdownMenu(            
            caller=self.ids.video_button,
            items=self.video_menu_items,
            callback=self.video_menu_callback,
            width_mult=4,
        )

```
What is wrong in this code?

### Versions

* OS: Windows 10 x64
* Python: 3.7.3
* Kivy: 2.0.0
* KivyMD: latest

**Comment by HeaTTheatR** [comment]
@radiolondra https://kivymd.readthedocs.io/en/latest/components/menu/#usage

**Comment by radiolondra** [comment]
@HeaTTheatR

I already read. ther's nothing new there

**Comment by HeaTTheatR** [comment]
@radiolondra Seriously?

**Comment by mp-007** [comment]
@radiolondra Your callback should be inside self.audio_menu_items and self.video_menu_items has it's specified in the doc. Your code is maybe good for kivymd 0.104.1 but not 0.104.2.

**Comment by HeaTTheatR** [comment]
@marcets A person should see for himself the differences in the code of 20 lines ...

**Comment by radiolondra** [comment]
gotcha. So something like:
`"on_release": lambda x=f"{item}": self.video_menu_callback(x),`
in the items builder instead of
`callback=self.video_menu_callback`
in the MDDropdownmenu contructor.
OK,thanks

**Comment by radiolondra** [comment]
@HeaTTheatR 

> A person should see for himself the differences in the code of 20 lines ...

A serious maintainer should always preserve backward compatibility. We don't have to "**pray it will keep working**" every time we update. Also the same "serious maintainer" should write all the difference for every updated function, instead to update just some examples. What have we to do? Make a diff of the old with all the new examples?
Anyway, thank you @marcet

**Comment by HeaTTheatR** [comment]
@radiolondra 
I owe nothing to anyone! This is the first thing! And secondly, open your eyes and carefully read the README file:

![Снимок экрана 2021-07-27 в 21 13 44](https://user-images.githubusercontent.com/16930280/127206430-9779c5af-7e07-4c54-88c1-d93f0e753ce0.png)

So leave your claims to yourself!

**Comment by radiolondra** [comment]
ok, my apologies

**Comment by HeaTTheatR** [comment]
@radiolondra :v:
