### ISSUE TITLE
Question: the MDDropDownMenu shadow

### ISSUE THREAD

**Issue by radiolondra** [kivymd/KivyMD#1059]
Just a question, not a bug report.
Is it possible to remove the shadow behind the MDDropDownMenu in some way?
I read the code but it seems ther's no option/parameter to set/remove the shadow

![shadow](https://user-images.githubusercontent.com/20070559/127739611-bdda9a9e-3894-4149-8625-9a5080c71b98.png)

### Versions

* OS: Windows 10 x64
* Python: 3.7.3
* Kivy: 2.0.0
* KivyMD: 1.0dev

**Comment by HeaTTheatR** [comment]
@radiolondra 
```python
instance_menu.ids.card.elevation = 0
```
