### ISSUE TITLE
Lag in navigation drawer ui

### ISSUE THREAD

**Issue by sina76n** [kivymd/KivyMD#106]
Hi. im trying to implement navigation drawer im my project but im experiencing UI lag in toggling the navigation... even in simplest example code written in documentations however it's fine on desktop . any idea how to make this better ?

### Code 

```python
from kivy.app import App
from kivy.lang import Builder

from kivymd.navigationdrawer import NavigationDrawerIconButton
from kivymd.theming import ThemeManager
from kivymd.toast import toast

main_kv = """
#:import MDSeparator kivymd.cards.MDSeparator
#:import MDToolbar kivymd.toolbar.MDToolbar
#:import NavigationLayout kivymd.navigationdrawer.NavigationLayout
#:import MDNavigationDrawer kivymd.navigationdrawer.MDNavigationDrawer
#:import NavigationDrawerSubheader kivymd.navigationdrawer.NavigationDrawerSubheader

<ContentNavigationDrawer@MDNavigationDrawer>:
    drawer_logo: ''

    NavigationDrawerSubheader:
        text: "Menu:"


NavigationLayout:
    id: nav_layout

    ContentNavigationDrawer:
        id: nav_drawer

    BoxLayout:
        orientation: 'vertical'

        MDToolbar:
            id: toolbar
            title: 'KivyMD Kitchen Sink'
            md_bg_color: app.theme_cls.primary_color
            background_palette: 'Primary'
            background_hue: '500'
            elevation: 10
            left_action_items:
                [['dots-vertical', lambda x: app.root.toggle_nav_drawer()]]

        Widget:
"""


class Example(App):
    theme_cls = ThemeManager()
    theme_cls.primary_palette = 'Teal'
    title = "Navigation Drawer"
    main_widget = None

    def build(self):
        self.main_widget = Builder.load_string(main_kv)
        return self.main_widget

    def callback(self, instance, value):
        toast("Pressed item menu %d" % value)

    def on_start(self):
        for i in range(15):
            self.main_widget.ids.nav_drawer.add_widget(
                NavigationDrawerIconButton(
                    icon='checkbox-blank-circle', text="Item menu %d" % i,
                    on_release=lambda x, y=i: self.callback(x, y)))


Example().run()
```

**Comment by HeaTTheatR** [comment]
Record the video of this example on your device...

**Comment by sina76n** [comment]
http://www.mediafire.com/file/5je9kt0kvk47jzx/SVID_20190907_130921_1.mp4/file

**Comment by sina76n** [comment]
Actually its not annoying but not quite good for a stunning app

**Comment by HeaTTheatR** [comment]
@sina76n And where are the lags ???

**Comment by sina76n** [comment]
Well... In comparison with other android apps of course :) they have smooth and impressive animations. I'm just curious about the reason

**Comment by HeaTTheatR** [comment]
@sina76n I did not see any lags! If you are not comfortable with the type of animation, change it yourself. If you do not know how, ask the appropriate question.

![Снимок экрана 2019-09-07 в 12 06 04](https://user-images.githubusercontent.com/16930280/64472498-0dcf3c80-d168-11e9-907d-a84228054fe5.png)

**Comment by mkc2019** [comment]
In case anyone comes across this post, this is not a kivymd issue. The lag is due to a bug in kivy 1.11.1 related to p4a and sdl2. Please take a look at the following discussion:
[Link to GitHub Discussion](https://github.com/kivy/python-for-android/issues/2002)
