### ISSUE TITLE
Persian

### ISSUE THREAD

**Issue by Khamisijeff** [kivymd/KivyMD#1073]
### Description of the Feature

Dear sirs 
Please support Persian in your powerful framework 😀

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@Khamisijeff This issue has nothing to do with the KivyMD library.

**Comment by Khamisijeff** [comment]
Hi there and thanks for your answer but in kivymd and kivy if i want to ask for Persian text in textinput widget it will displays the letters left to right and divided. What i want is totally different, right to left without dividing.
