### ISSUE TITLE
change the position of MDFloatingActionButtonSpeedDial

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1074]
###
It will be great if there is any way to change the position of MDFloatingActionButtonSpeedDial

**Comment by MrinmoyHaloi** [comment]
yeah it would it be great. but its usually seen in bottom right. But it would be useful for some people

**Comment by LazzaAU** [comment]
oh so it's not moveable ?. I just updated from 1.0.2 to 1.1.1 and my speeddial button moved to the left bottom and the stack opens on the right bottom and the stack buttons don't call the callback anymore.
Anyway, thought i was doing something wrong by not being able to shift the main button back to the right bottom corner, now i know it's simply my kivymd1.1.1 thats broken so i'll stop looking :) cheers

![speeddialButton](https://user-images.githubusercontent.com/31381872/204117320-d4cd7367-6fbf-46af-b02d-7fa04bbd680a.gif)

**Comment by MajdMsallati** [comment]
I have the same problem with the MDFloatingActionButtonSpeedDial from version 1.1.1 showing on the bottom left and the stack buttons on the bottom right. please try to fix it asap because my app is based on the latest version of kivymd and I can't use an older version.

**Comment by LazzaAU** [comment]
Switching phone to landscape then back to portrait fixes it. But that's obviously not a professional solution :)

**Comment by PartORG** [comment]
Hi, I have the same problem with MDFloatingActionButtonSpeedDial.
It is rendered on the left bottom side(((

Would be nice to have a fix for it.

**Comment by HeaTTheatR** [comment]
Widgets to be removed in version `1.3.0`:

`MDFloatingActionButtonSpeedDial
MDBackdrop
MDBanner`
