### ISSUE TITLE
Responsive MDDialog height

### ISSUE THREAD

**Issue by FrankS1990** [kivymd/KivyMD#1075]
### Description of the Feature

I always have struggles with setting the height of MDDialog popups because they are not responsive.
It is in a way possible with type=custom but most time i dont need a custom dialog.
Even with the custom dialog it is no fun working with the dialog height.

The size_hint parameter only affects the width even with both parameter set.
The widht of the dialog resizes perfect if i change Window size.
The height does not resize with the window AND the initial height does not work correctly sometimes the height is ok other times it is lager than the window.

Attached Screenshots are both with the following code just different Window sizes.

It would be great to have the height responsive even in the not custom dialogues.

### Code and Logs

```
    def openCategoryDialog(self):

        inputList = [{"id":"EMPTY", "text":"Leer"},{"id":"SOFTWARE", "text":"App / Software"},{"id":"WEB", "text":"Website"},{"id":"GAMES", "text":"Games"},{"id":"MAIL", "text":"Mail"},{"id":"MUSIC", "text":"Musik"},{"id":"MOVIE", "text":"Film"},{"id":"LAN", "text":"Netzwerk"},{"id":"DASHBOARD", "text":"Dashboard"}]
        listItems = [ OneLineAvatarIconListItem(id=entry["id"], text=entry["text"], on_release=self.categorySelected) for entry in inputList ]

        self.dialog = MDDialog( 
            title = "Kategorie wählen",
            type = "confirmation",
            size_hint = (.8, .7),
            items = listItems,
            buttons = [ MDFlatButton( text="Abbrechen", on_release=self.closeCategoryDialog ) ]
        )
        self.dialog.open()

    def closeCategoryDialog(self, *args):
        self.dialog.dismiss( force=True )

    def categorySelected(self, item):
        print( item.id )
        print( item.text )
        self.dialog.dismiss( force=True )
```

### Screenshots

![image](https://user-images.githubusercontent.com/62507401/131087046-c77d9075-3741-41c8-8db5-c8d0bb28d144.png)

![image](https://user-images.githubusercontent.com/62507401/131087100-3ad4a7f5-13e1-4a40-b279-af6606203510.png)

### Versions

* OS: Windows 10
* Python: 3.7.1
* Kivy: 2.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@FrankS1990 You cannot change the height of the dialog box.

**Comment by FrankS1990** [comment]
Thank you for the quick response.

Ok but isn´t at least the height bigger than the Window an issue that should be addressed?
Or am i doing something wrong?

**Comment by HeaTTheatR** [comment]
@FrankS1990 The height of the dialog is equal to the height of the content of the root widget inside the dialog.

**Comment by HeaTTheatR** [comment]
@FrankS1990 https://kivymd.readthedocs.io/en/latest/components/dialog/#kivymd.uix.dialog.dialog.MDDialog.content_cls

**Comment by FrankS1990** [comment]
Okay thanks i´ll just use custom then.

But i still dont get it, i got multiple heights with equal content just different window size so it clearly does someting with the Window height. As i work with it it just feels wrong to me.

Doesn´t matter i use custom now, thanks again for your help. :)
