### ISSUE TITLE
MDSlider with factional values

### ISSUE THREAD

**Issue by vitoller** [kivymd/KivyMD#1076]
### Description of the Bug

Currently the value hint in the MDSlider does not support fractional values. 
I would like to use 0.5 steps.

For me it worked by removing the **int()** in slider.kv line 89.
```
MDLabel:
      text: str((slider.value))
```

But this might not be the right solution due to rounding errors.

### Code and Logs

```python

kv = """
MDSlider:
    id: difficulty
    step: 0.5
    max: 5
"""
```

### Versions

* OS: ubuntu
* Python: 3.9.5
* Kivy: head
* KivyMD: head

**Comment by maleksware** [comment]
Possible fix for this is to add `round()` istead of `int()` and specify a parameter for rounding precision.

**Comment by SpecDaTurtle** [comment]
Why not increase the max steps? Complicated solution for no benefit?

Logically speaking you can double the steps to 10, then step 1 give you the same result as 5 steps and stepping 0.5

Am I missing anything here?

**Comment by maleksware** [comment]
This is a temporary fix.

The bug certainly should be either fixed or changed by adding error raising when user sets a fraction as a parameter.
