### ISSUE TITLE
Please update the old document about navigation drawer

### ISSUE THREAD

**Issue by 0rbianta** [kivymd/KivyMD#1078]
### Description of the Bug

[Navigation Drawer](https://kivymd.readthedocs.io/en/0.104.0/components/navigation-drawer/) document contains "NavigationLayout" which is named as "MDNavigationLayout" on new update(s).

Edit on GitHub option also not working too

**Comment by HeaTTheatR** [comment]
![Снимок экрана 2021-09-08 в 21 48 21](https://user-images.githubusercontent.com/16930280/132567610-2ccea5b7-5f80-4430-b263-7caf5bf92940.png)

![Снимок экрана 2021-09-08 в 21 48 50](https://user-images.githubusercontent.com/16930280/132567635-564c8787-00a3-4208-bdae-317d7d143f58.png)
