### ISSUE TITLE
I have an issue with MDFloatLayout in kivymd. I have added a MDFloatLayout to appear as loading background for my app but the problem is when I click the buttons behind the MDFloatLayout are still working. I don't want MDFloatLayout to allow to click the buttons behind it. Can anyone please help me solve this problem

### ISSUE THREAD

**Issue by CodeWithVallabh** [kivymd/KivyMD#1082]
I have an issue with MDFloatLayout in kivymd. I have added a MDFloatLayout to appear as loading background for my app but the problem is when I click the buttons behind the MDFloatLayout are still working. I don't want MDFloatLayout to allow to click the buttons behind it. Can anyone please help me solve this problem. 
Thanks in advance :)

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1010#issuecomment-919160357
