### ISSUE TITLE
Time Picker Recursion Error

### ISSUE THREAD

**Issue by coder5459** [kivymd/KivyMD#1083]
### Description of the Bug

When Using the Time picker on KIvyMD specifically the typing out the time, when trying to backspace both zeroes on the minutes a recursion error appears with the following text:"RecursionError: maximum recursion depth exceeded while getting the repr of an object" Any suggestions on why? Used Template for time picker from KivyMD website

### Code and Logs

`from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.picker import MDTimePicker

KV = '''
FloatLayout:

    MDRaisedButton:
        text: "Open time picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_time_picker()
'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def show_time_picker(self):
        '''Open time picker dialog.'''

        time_dialog = MDTimePicker()
        time_dialog.open()

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
Related issue - https://github.com/kivymd/KivyMD/issues/973
