### ISSUE TITLE
Uncorrect behavior of the MDSwitch

### ISSUE THREAD

**Issue by Cedric-G-dev** [kivymd/KivyMD#1090]
Hello,
I believe I found a mistake of coding inside the MDSwitch.
If I understand the code well, the active property is related to the 'thumb' meanwhile the state property is related to the MDSwitch.
Or it seems like the thumb is not 'well' positionned inside the switch, thus not allowing a perfect control of this widget.

The following code allows the demonstration of the issue.

```
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
MDFloatLayout:

    MDSwitch:
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_state: app.test_state(self)
        on_active: app.test_active(self)  
'''

class Test(MDApp):
    def build(self):
        screen = Builder.load_string(KV)
        return screen

    def test_state(self,instance):
        print(instance.state)

    def test_active(self,instance):
        print(instance.active)

Test().run()



```
![image](https://user-images.githubusercontent.com/85155937/134712569-d69b43cf-e9c6-4c0f-932e-d12a69089b77.png)

According to my tests this issue can be resolved updating the code of the following function in 'uix/selectioncontrol.py' (Line 526):
The _thumb_pos value on active should be 'self.width - dp(24)' .
```
    def _update_thumb_pos(self, *args, animation=True):
        if self.active:
            _thumb_pos = (self.width - dp(14), self.height / 2 - dp(12))
        else:
            _thumb_pos = (0, self.height / 2 - dp(12))
        Animation.cancel_all(self, "_thumb_pos")
        if animation:
            Animation(_thumb_pos=_thumb_pos, duration=0.2, t="out_quad").start(
                self
            )
        else:
            self._thumb_pos = _thumb_pos
 
```

The following diagram details the x position of the MDSwitch, Thumb and also the RoundedRectangle (considering root.widget_style != 'ios').
It is shown that when the thumb is active, there is a 10dp length outside the MDswitch
![image](https://user-images.githubusercontent.com/85155937/134766863-40127802-0c80-4bcd-9caf-e7f896da204d.png)

I would also propose to change the RoundedRectangle size/position so that it is centered in the MDSwitch.

New to Kivy-KivyMD I hope I understood the code well enough so my explaination is True and clear.

**Comment by HeaTTheatR** [comment]
@Cedric-G-dev I have not found any bugs in the MDSwitch behavior that you are talking about here.

**Comment by Cedric-G-dev** [comment]
@HeaTTheatR 
The last action does not trigger the 'test_state' function.

https://user-images.githubusercontent.com/85155937/135058760-9e968b2e-de07-491d-a112-5e636341816a.mp4

**Comment by HeaTTheatR** [comment]
@Cedric-G-dev I do not understand what the problem is?

**Comment by Cedric-G-dev** [comment]
@HeaTTheatR 
The issue that I am facing is that I need to know when the MDSwitch is clicked (with the 'state' information).
In the video, at 3s, the thumb is clicked on the center -> output in the console
'down
False
normal'
In the video, at 10s, the thumb is clicked on the right-> output in the console
'False'
--> The switch does not send back the information that it has been clicked.

**Comment by HeaTTheatR** [comment]
@Cedric-G-dev MDSwitch has two states: True - active state and False - inactive state.
