### ISSUE TITLE
TimePicker crash upon execution

### ISSUE THREAD

**Issue by FELOPZDDEFPOTEC** [kivymd/KivyMD#1091]
### Description of the Bug

The TimePicker widget seems to just automatically crash the entire program when you try to populate/use it (the widget). The app builds, with the button to open the time picker, but as soon as I click the button, the whole thing crashes. Also, "kivymd.uix.picker" for some reason needs to be changed to "kivymd.uix.pickers", else the app won't even fully build before crashing, and the traceback reads that there is no module named "kivymd.uix.picker"

### Code and Logs

```
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.pickers import MDTimePicker

KV = '''
FloatLayout:

    MDRaisedButton:
        text: "Open time picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_time_picker()
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def show_time_picker(self):
        '''Open time picker dialog.'''

        time_dialog = MDTimePicker()
        time_dialog.open()


Test().run()


```

Last bit of the traceback:

```
File "D:\kivygui\virt\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 139:
 ...
     137:        num_type: "minute"
     138:        pos: dp(120), 0
 >>  139:        text_color: root.text_color
     140:        disabled: root.disabled
     141:        on_text: root.dispatch("on_time_input")
 ...
 KeyError: '_current_hint_text_color'
   File "D:\kivygui\virt\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "kivy\_event.pyx", line 725, in kivy._event.EventDispatcher.__proxy_setter

```

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 2.0
* KivyMD: 1.0.0.dev0

**Comment by sollarp** [comment]
I could not regenerate your issue. The only thing I modified in is the " kivymd.uix.picker import MDTimePicker" . Your code was pointing to the different file. I have tested this code on my Ubuntu 20.04  and my Samsung phone all fine. If I can further assist let me know. You have to make sure you are using the latest version of Kivy and KivyMD.
Name: kivymd
Version: 0.104.2
Name: Kivy
Version: 2.0.0


        from kivy.lang import Builder
        
        from kivymd.app import MDApp
        from kivymd.uix.picker import MDTimePicker
        
        KV = '''
        FloatLayout:
        
            MDRaisedButton:
                text: "Open time picker"
                pos_hint: {'center_x': .5, 'center_y': .5}
                on_release: app.show_time_picker()
        '''
        
        
        class Test(MDApp):
            def build(self):
                return Builder.load_string(KV)
        
            def show_time_picker(self):
                '''Open time picker dialog.'''
        
                time_dialog = MDTimePicker()
                time_dialog.open()
        
        
        Test().run()

**Comment by HeaTTheatR** [comment]
@sollarp Thanks for your analysis!

**Comment by FELOPZDDEFPOTEC** [comment]
Looks like it is a problem with the dev build. Uninstalling the dev build and installing using 

`pip install kivymd`

seems to have resolved the issue, though this is how I had first installed when I had the issue originally. The dev install was an attempt to see if that would fix it, but seems like now the dev build is the only one with the issue.

**Comment by HeaTTheatR** [comment]
Fix un master branch.
