### ISSUE TITLE
Translate DatePicker

### ISSUE THREAD

**Issue by CoutinhoElias** [kivymd/KivyMD#1098]
### Description of the Feature

Does anyone here use KivyMD's DatePicker?
I would like to translate to my language.
Is there any way?

**Comment by sollarp** [comment]
Always a way. 
Add the following to your "picker.py" file 

      import locale
      # this sets the date time formats to pt_PT, there are many other options for currency, numbers etc. 
      # You might need to install language package  "sudo apt-get install language-pack-pt-base" pt means Portuguese 
      locale.setlocale(locale.LC_TIME, 'pt_PT.utf8')

Also find class BaseDialogPicker and modify the string property of the title.

       title = StringProperty("Selecione a data")


Find this code block in Kivy

          DatePickerIconTooltipButton:
            id: triangle
            owner: root
            icon: "menu-down"
            ripple_scale: .5
            theme_text_color: "Custom"
            #### Change hint_text ######
            hint_text: "Escolha o ano"
            on_release:
                root.transformation_to_dialog_select_year() \
                if not root._select_year_dialog_open else \
                root.transformation_from_dialog_select_year()
            pos:
                (label_month_selector.width + dp(14), root.height - dp(123) - self.height) \
                if root.theme_cls.device_orientation == "portrait" \
                else (dp(180) + label_month_selector.width, label_title.y - dp(14))
            text_color:
                app.theme_cls.text_color \
                if not root.text_color else root.text_color
            md_bg_color_disabled: 0, 0, 0, 0




https://user-images.githubusercontent.com/74240451/136863529-24ed9099-24fb-4c50-b95a-bcf949bf1d31.mp4

 Any issue let me know. Happy coding

**Comment by CoutinhoElias** [comment]
sollarp, thanks for helping but I don't know where to find BaseDialogPicker, I searched and didn't find it.

I didn't even find the DatePickerIconTooltipButton:

Can you explain me?

**Comment by sollarp** [comment]
Path to picker.py file
kivymd/uix/picker.py
if you can't find it than you can trace it back like import that class to your file like this:
     
     from kivymd.uix.picker import BaseDialogPicker

hope this makes it easier to find.

**Comment by CoutinhoElias** [comment]
Yes, got it!
Your help was essential. Thanks!

**Comment by tmimi-fakhreddine** [comment]
Hello, 
How can I use it in android please ?
apparently locale.setlocale(locale.LC_TIME, 'pt_PT.utf8') is not supported by android and  locale.setlocale(locale.LC_ALL, '')
 keep the translation in English even if the device lang is different. Thank you.

**Comment by sollarp** [comment]
@symbian001 
Hi , 
This is just an example to change the language that is why PR has not been issued. Unfortunately this is the disadvantage of using any cross-platform. If you can't build it with Builtdozer than try to find another python library it might be supported. If you desperate to get it working you have to hard code the language into the core code.

**Comment by tmimi-fakhreddine** [comment]
Hi @sollarp ,
Yes finally I have to work on core code because 'locale' is not supported on android. 
Thanks for your answer.
