### ISSUE TITLE
text color not change

### ISSUE THREAD

**Issue by kaomao1234** [kivymd/KivyMD#1099]
### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    MDTextField:
                size_hint_y:None
                id:password_field
                password:True
                text_color:root.black
                line_color_focus:root.copper_rust
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/76930515/136683076-9864e3ca-4426-4b83-9fde-213046d42ef6.png)
### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@kaomao1234 https://kivymd.readthedocs.io/en/latest/components/textfield/#kivymd.uix.textfield.textfield.MDTextField.text_color_focus

**Comment by kaomao1234** [comment]
and MDRoundFlatIconButton too.

**Comment by HeaTTheatR** [comment]
@kaomao1234 https://kivymd.readthedocs.io/en/latest/components/button/#mdrectangleflatbutton

**Comment by kaomao1234** [comment]
yeah but i doesn't change
```python
  self.back_arrow = MDRoundFlatIconButton(
            icon='arrow-expand-left',
            size_hint=(.1, .1),
            pos_hint={'x': 0, 'y': .9},
            text='back',
            theme_text_color="Custom",
            line_color=self.copper_rust,
            icon_color=self.white,
            text_color= self.white,
        )
```
![image](https://user-images.githubusercontent.com/76930515/136688193-c207e958-b5a0-4dea-916a-338a83790026.png)

**Comment by HeaTTheatR** [comment]
@kaomao1234 
![Снимок экрана 2021-10-10 в 11 26 41](https://user-images.githubusercontent.com/16930280/136688422-b4fc0bb3-aa76-4108-9b62-22df824ce85a.png)

Until the release of the KivyMD library version 1.0.0 has been released, use `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by HeaTTheatR** [comment]
@kaomao1234 
![Снимок экрана 2021-10-10 в 11 28 45](https://user-images.githubusercontent.com/16930280/136688483-6f689a48-0fd8-4133-8673-45aa4d9ac1c5.png)

**Comment by kaomao1234** [comment]
i reinstall but it still

**Comment by HeaTTheatR** [comment]
@kaomao1234 
No. You are using version 0.104.2.

**Comment by HeaTTheatR** [comment]
@kaomao1234 

![000](https://user-images.githubusercontent.com/16930280/136702993-06b75a4e-437e-49ca-b2e7-7683350149d1.gif)

**Comment by kaomao1234** [comment]
> @kaomao1234 
> ![Снимок экрана 2021-10-10 в 11 26 41](https://user-images.githubusercontent.com/16930280/136688422-b4fc0bb3-aa76-4108-9b62-22df824ce85a.png)
> 
> Until the release of the KivyMD library version 1.0.0 has been released, use `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

I were used but it still
