### ISSUE TITLE
MDThemePicker displaying Style tab improperly on Android devices

### ISSUE THREAD

**Issue by YarosMallorca** [kivymd/KivyMD#1100]
### Description of the Bug

MDThemePicker displaying Style tab improperly on Android but on Windows it works like expected with same code!

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.picker import MDThemePicker


class MainApp(MDApp):
    def build(self):
        theme_dialog = MDThemePicker()
        theme_dialog.open()


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![Screenshot_20211013-135305_Universal Converter](https://user-images.githubusercontent.com/54041533/137190607-f2839bf1-f652-4376-af77-a9beb838c12b.jpg)

### Versions

* OS: Android 11, Windows 10
* Python: 3.8
* Kivy: 2.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
Fix in master branch.

**Comment by YarosMallorca** [comment]
Master branch doesn't compile for android, at least yesterday it didn't. Will recompile with buildozer tomorrow and try!
Thanks!

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Compiling a Kivy application has nothing to do with the KivyMD library.

**Comment by YarosMallorca** [comment]
I know, but after compiling I got an error that said more or less something like this: `No module named kivymd.uix.picker`
So I recompiled with the 0.104.4 and it did compile successfully

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
![Снимок экрана 2021-10-13 в 21 45 21](https://user-images.githubusercontent.com/16930280/137194605-220564cd-74e0-4a58-9939-41e001493239.png)

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
![Uploading Снимок экрана 2021-10-13 в 21.45.21.png…]()

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
![Снимок экрана 2021-10-13 в 21 45 21](https://user-images.githubusercontent.com/16930280/137198895-1d66c9c2-0e51-4972-8f74-832162f05037.png)

**Comment by YarosMallorca** [comment]
@HeaTTheatR Tried to compile again with the master branch (as you showed in the images) and did buildozer android clean but I still have the issue!

Here is the exception:
![image](https://user-images.githubusercontent.com/54041533/137933250-5bf1f762-3d36-405f-9930-e0c3a89568a7.png)

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder I can assume that you are not using the master version of the KivyMD library.

**Comment by YarosMallorca** [comment]
Is this correct? @HeaTTheatR

![image](https://user-images.githubusercontent.com/54041533/137934634-03b6b4ad-1e95-4144-9819-a63c30e4d2cd.png)

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder It does not matter! Show the version of the library in the log from `adb`

**Comment by YarosMallorca** [comment]
How to access that?

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder `adb logcat | grep python`

**Comment by YarosMallorca** [comment]
It just says: Waiting for devices!

I also have the ADB Log Viewer with Find option, is that useful somehow? Does it print it in the logs of my app somewhere?

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder https://stackoverflow.com/questions/59384085/how-to-debug-a-kivy-kivymd-app-for-android

**Comment by YarosMallorca** [comment]
@HeaTTheatR Can't figure out how to do this but I have the logs. Why would it be a different version if I compiled using the link?

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Show the log of the `adb logcat | grep python` command .

**Comment by YarosMallorca** [comment]
Okay I will, let me clean and recompile first

**Comment by YarosMallorca** [comment]
@HeaTTheatR There is an issue!
I installed the master on windows by using: `pip install https://github.com/kivymd/KivyMD/archive/master.zip`
And I get this error:

```
[INFO   ] [Logger      ] Record log in C:\Users\siuba\.kivy\logs\kivy_21-10-22_0.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\siuba\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\siuba\AppData\Local\Programs\Python\Python39\python.exe"
[INFO   ] [KivyMD      ] 1.0.0.dev0, git-Unknown, 2021-10-22 (installed at "C:\Users\siuba\AppData\Local\Programs\Python\Python39\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 461.92'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1050 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "C:\Users\siuba\Documents\GitHub\Universal-Converter\main.py", line 24, in <module>
     from kivymd.uix.picker import MDThemePicker
 ModuleNotFoundError: No module named 'kivymd.uix.picker'
```

Could you please test it? It seems that I can't import **MDThemePicker** by using from `kivymd.uix.picker import MDThemePicker`

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder There is no class named MDThemePicker in KivyMD.

**Comment by YarosMallorca** [comment]
Then how is it named now? 
The code worked with 0.104.2!

**Comment by YarosMallorca** [comment]
@HeaTTheatR 
Heck, even in the docs it is:
![image](https://user-images.githubusercontent.com/54041533/138449701-a92fed06-71b1-478f-8189-195dbaec3f79.png)

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
![Снимок экрана 2021-10-22 в 14 59 41](https://user-images.githubusercontent.com/16930280/138450216-35ae640d-5913-426f-a03c-b4daac76cee8.png)

We only support the master branch of the KivyMD library

**Comment by YarosMallorca** [comment]
Can't find pickers

![image](https://user-images.githubusercontent.com/54041533/138450478-751e7a0d-c9b7-4aa7-a55d-a03a75bd0dd7.png)

**Comment by YarosMallorca** [comment]
Oh well @HeaTTheatR Figured out that they are different sections of the docs, but where is ThemePicker??

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder https://kivymd.readthedocs.io/en/latest/components/colorpicker/

**Comment by YarosMallorca** [comment]
@HeaTTheatR That is COLOR PICKER not Theme Picker!!!
You said you fixed it but your fix is just removing it???

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder I do not understand the essence of your question...

**Comment by YarosMallorca** [comment]
@HeaTTheatR  Could you please re-introduce it? Because I need it working like it was before with the SAME CODE!
We made the app, compiled it for android, seen the issue, reported it, you said you fixed it in master, tried to compile with master, it doesn't work and now the project is delayed by much because you removed the widget as a fix?

You need to learn about something called backward compatibility, it should work in theory with new builds!

**Comment by YarosMallorca** [comment]
I agree that the Color Picker is nice, for other things, but Theme Picker is another thing and should work as expected, as it was before.

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
The `MDThemePicker` widget has been removed so it is no longer useful. You can change the application theme with one line of code. Therefore, a more modern `ColorPicker` widget was created. And until a stable version of the `KivyMD` library with version `1.0.0` is released, we do not support backward compatibility and do not support older versions of the library. This is stated in the documentation.

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder We don't need any special widget to change the app theme from dark to light.

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
![Снимок экрана 2021-10-22 в 15 28 05](https://user-images.githubusercontent.com/16930280/138453601-a4de9fb2-df84-4ad8-94ea-eb7261fe81a5.png)
