### ISSUE TITLE
left icon color not changing in MDTextFieldRound

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1104]
### Description of the Bug

left icon color not changing in MDTextFieldRound

### Code and Logs
```python
 MDTextFieldRound:
                icon_left_color:[1,1,0,1]
                cursor_color:[1,1,1,1]
                hint_text_color:[1,1,1,1]
                foreground_color:[1,1,1,1]
                icon_left: "magnify"
                hint_text: "Search"
                #fill_color:[0.25,0,1,1]
                normal_color:[0.5,0.0,0.7,1]
                
                line_color:[0,0,0,0]
```

### Versions

* OS: kubuntu 18.04
* Python: 3.6.9
* Kivy: 2.0.0
* KivyMD: 1.0.0.dev0, git-Unknown, 2021-08-21

**Comment by sollarp** [comment]
Can you confirm this is what you are looking for terms of the behaviour  of this?

          from kivymd.app import MDApp
          from kivy.lang import Builder
          
          
          KV = """
          #: import gch kivy.utils.get_color_from_hex
          
          
          AnchorLayout:
	          canvas:
		          Color:
			          rgba: gch("#5D1049")
		          Rectangle:
			          size: self.size
			          pos: self.pos
	          MDTextFieldRound:
		          hint_text: "Select dates"
		          icon_left: "calendar"
		          icon_left_color: [1, 0, .5, 1]
		          size_hint: (.7, .07)
		          color_active: gch("#720D5D")
		          normal_color: gch("#720D5D")
		          line_color: (0, 0, 0, 0)
		          foreground_color: gch("#C79EBE")
		          hint_text_color: (1, 0, 0, 1) # not works
          """
          
          
          class Example(MDApp):
	          def build(self):
		          return Builder.load_string(KV)
          
          
          Example().run()
          


https://user-images.githubusercontent.com/74240451/138166674-7f4c353c-0b27-4cbe-942e-930c3b897a95.mp4




I will do a pull request later on if this is ok.

**Comment by HeaTTheatR** [comment]
@sollarp I see that this code solves the problem, but unfortunately it does not solve the cause of this problem :(

**Comment by sollarp** [comment]
> @HeaTTheatR  I see that this code solves the problem, but unfortunately it does not solve the cause of this problem :(

Sorry I did not mention this is just a code I was using. It doesn't  solve the problem. I found a bug in  textfield.py MDTextFieldRound class




         def on_focus(self, instance, value):

                  if value:
                      self.icon_left_color = (
                          self._icon_left_color_copy or self.theme_cls.text_color
                      )
                      self.icon_right_color = (
                          self._icon_right_color_copy or self.theme_cls.text_color
                      )
                  else:
                      self.icon_left_color = self.theme_cls.primary_color
                      self.icon_right_color = self.theme_cls.primary_color
          
Just need to do a pull request...

**Comment by HeaTTheatR** [comment]
@sollarp If your changes fix this error you can suggest your PR.

**Comment by HeaTTheatR** [comment]
@Sahil-pixel https://kivymd.readthedocs.io/en/latest/components/textfield/#round-mode
