### ISSUE TITLE
Header Menu not working with MDToolbar

### ISSUE THREAD

**Issue by J-Arnold** [kivymd/KivyMD#1108]
### Description of the Bug

Hi,
I try to combine the Header Menu with the Menu with MDToolbar example but the header part is not in the correct position.

### Code and Logs

```python
from kivy.lang import Builder
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.snackbar import Snackbar
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
<MenuHeader>
    orientation: "vertical"
    adaptive_size: True
    padding: "4dp"

    MDBoxLayout:
        spacing: "120dp"
        adaptive_size: True

        MDIconButton:
            icon: "gesture-tap-button"
            pos_hint: {"center_y": .5}

        MDLabel:
            text: "Actions"
            adaptive_size: True
            pos_hint: {"center_y": .5}
            
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "MDToolbar"
        left_action_items: [["menu", lambda x: app.callback(x)]]
        right_action_items: [["dots-vertical", lambda x: app.callback(x)]]

    MDLabel:
        text: "Content"
        halign: "center"
'''

class MenuHeader(MDBoxLayout):
    '''An instance of the class that will be added to the menu header.'''

class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [
            {
                "viewclass": "OneLineListItem",
                "text": f"Item {i}",
                "height": dp(56),
                "on_release": lambda x=f"Item {i}": self.menu_callback(x),
             } for i in range(5)
        ]
        self.menu = MDDropdownMenu(
            header_cls=MenuHeader(),
            items=menu_items,
            width_mult=4,
        )
        
    def build(self):
        return self.screen

    def callback(self, button):
        self.menu.caller = button
        self.menu.open()

    def menu_callback(self, text_item):
        self.menu.dismiss()
        Snackbar(text=text_item).open()

Test().run()
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/16463717/138245317-3fd17d2e-0946-4d03-a478-24fb4ab5b282.png)

### Versions

* OS: Win 10
* Python: Python 3.8.8
* Kivy: 2.0.0
* KivyMD: 0.104.2, git-bc7d1f5, 2021-06-06

**Comment by HeaTTheatR** [comment]
@J-Arnold 
You could use the "position" parameter:

```python
        self.menu = MDDropdownMenu(
           ...
            position="bottom",
        )
```

But since this parameter was not added very well, I encountered the following error:
![Снимок экрана 2021-10-21 в 12 09 10](https://user-images.githubusercontent.com/16930280/138247641-b2f56060-b8f1-4607-945b-4f31e7ec29e4.png)

So I'll add the label "Bug" to come back to this later.

**Comment by sollarp** [comment]
Looks like MDDropDown menu takes the window y axis instead of the MDtoolbar right icon y position.

Found a temporary solution dropping DropDown menu to the icon.

Modifying menu.py file MDDropdownMenu class.
Subtract 50 from  the self.caller.center_y.  

        def set_menu_properties(self, interval=0):
                """Sets the size and position for the menu window."""
                if self.caller:
                    self.ids.md_menu.data = self.items
                    # We need to pick a starting point, see how big we need to be,
                    # and where to grow to.
                    self._start_coords = self.caller.to_window(
                        self.caller.center_x, self.caller.center_y - 50
                    ) 

![dropdownmenu](https://user-images.githubusercontent.com/74240451/138614836-1621d317-a5e8-4eb3-a80a-77e3f0231c98.png)

I will try to find a solution to call in the right icon  position.

**Comment by sollarp** [comment]
Hi  @HeaTTheatR ,

Are you interested to have the following effect available for the drop down menu?

Current behave.

Opening the right drop down menu moves when window gets resized but left.

https://user-images.githubusercontent.com/74240451/139051321-4129e720-1105-4123-8348-756fdbeddaf6.mp4


After added my code both of them behaving the same way.

https://user-images.githubusercontent.com/74240451/139051574-2f741e08-6c03-48b7-93da-437dd08b9c9f.mp4

About original issue:

I'm a bit struggling to make this code look better mentioned above.
I do not like just giving a random value "50" to the code. If the icon position gets changed this wouldn't work.
I was thinking to get the action icon y position somehow if there is such a thing or get the MDTool bar height would do.

     self._start_coords = self.caller.to_window(
                    self.caller.center_x, self.caller.center_y - 50
                ) 

Thanks in advance

**Comment by HeaTTheatR** [comment]
@sollarp Yes, the menu shift effect looks great!

**Comment by sollarp** [comment]
> @sollarp Yes, the menu shift effect looks great!

I will work on the MDToolBar bottom code as well test it and let you know.

**Comment by HeaTTheatR** [comment]
@sollarp OK!
