### ISSUE TITLE
adding persian and arabic support just with font_name arg

### ISSUE THREAD

**Issue by amir0241** [kivymd/KivyMD#1117]
### Description of the Feature

hi , i have a suggestion for you 
after many hours of working with kivymd i found a solution for supporting persian and arabic 

so please add font_name arg in everywhere of your lib this can help us to change the default font to support persian and arabic even on toolbar, textfield and etc

**Comment by HeaTTheatR** [comment]
@amir0241 Arabic language support should be implemented at the application level, and not at the KivyMD library level.

**Comment by amir0241** [comment]
i know that but writing arabic is not supported much even when we use arabic reshaper and shows just some square thing instead but i tested when i change font_name to something like arial arabic  text shows very well

**Comment by HeaTTheatR** [comment]
@amir0241 https://github.com/mpcabd/python-arabic-reshaper
