### ISSUE TITLE
First Tab in MDTabs has wrong text color when set tab_hint_x

### ISSUE THREAD

**Issue by BeardyBarber** [kivymd/KivyMD#1118]
### Description of the Bug
Setting together `text_color_active` and `tab_hint_x` and running app renders text of first (active) tab with default text color not set with `text_color_active` property.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.floatlayout import MDFloatLayout

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
        tab_hint_x: True
        text_color_active: [0,0,0,1]
        Tab:
            title: "My tab1"
        Tab:
            title: "My tab2"
'''

class Tab(MDFloatLayout, MDTabsBase):
    pass


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)

Example().run()
```

### Screenshots

Result:
https://ibb.co/p21zP3D

Expected result:
https://ibb.co/4jT7yH7

### Versions

* OS: Linux Mint 20.1
* Python: 3.8.10
* Kivy: 2.0.0
* KivyMD: 1.0.0.dev0, git-Unknown, 2021-10-26

**Comment by HeaTTheatR** [comment]
@BeardyBarber I cannot confirm this. Use only the most recent version of the KivyMD library branch master.

**Comment by HeaTTheatR** [comment]
@BeardyBarber 

https://user-images.githubusercontent.com/16930280/140408664-8eb16900-178b-4176-8b05-e57fa99cdc5a.mov

**Comment by BeardyBarber** [comment]
@HeaTTheatR Still exists after update.

https://webmshare.com/bxxQB

**Comment by HeaTTheatR** [comment]
@BeardyBarber So most likely you are using a completely different version of the KivyMD library

**Comment by sollarp** [comment]
I have just cloned the master repo and see the same issue.

https://user-images.githubusercontent.com/74240451/140424250-4daa81ff-7455-404d-b3bd-1c50ad6c6e61.mp4

**Comment by HeaTTheatR** [comment]
@BeardyBarber 
![Снимок экрана 2021-11-05 в 00 45 19](https://user-images.githubusercontent.com/16930280/140424711-d769c8fc-6f4d-43a8-9ec3-748b78f388f0.png)

**Comment by BeardyBarber** [comment]
The issue is not present after KIVY update to 2.1.0.dev0.
