### ISSUE TITLE
white page while fetching values from dropdown

### ISSUE THREAD

**Issue by deepak1703raj** [kivymd/KivyMD#1120]
### Description of the Feature

white page while fetching values from dropdown

### Code and Logs
     from kivy.lang import Builder
     from itertools import chain
     from kivymd.app import MDApp
     from kivymd.uix.menu import MDDropdownMenu

     KV = '''
     Screen:

             MDRaisedButton:
                       id: button
                       text: "Open dropdown"
                       pos_hint: {"center_x": .5, "center_y": .5}
                        on_release: app.menu.open()
                          '''

         class Test(MDApp):
                   def __init__(self, **kwargs):
                            super().__init__(**kwargs)
                           self.screen = Builder.load_string(KV)
                           self.item_count = 5
                           menu_items = [{"text": f"Item {i}"} for i in range(self.item_count)]
                           self.menu = MDDropdownMenu(
                           caller=self.screen.ids.button,
                            items=menu_items,
                           width_mult=4,
                         )
                           self.menu.bind(on_release=self.menu_callback)

           def add_item(self):
                    self.item_count += 1
                    new_item = {'text': f'Item{self.item_count}'}
                   self.menu.items = [item for item in chain(self.menu.items, [new_item])] 
    
             def menu_callback(self, instance_menu, instance_menu_item):
                      print(instance_menu, instance_menu_item)

           def build(self):
                 return self.screen

          Test().run()

### Screenshots

Add images to explain us this feature. Paste urls here.

![image](https://user-images.githubusercontent.com/54531725/140656350-25be4161-e945-43b1-abd1-4d80345f35a3.png)

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/menu/#usage
