### ISSUE TITLE
MDRectangleFlatButton Bug

### ISSUE THREAD

**Issue by amir0241** [kivymd/KivyMD#1121]
i've found a bug in kivymd dev 1.0.0

MDRectangleFlatButton text color does not change to white with rgba  color 1,1,1,1 you can test it yourself

**Comment by sollarp** [comment]
Can you be kind and share the minimum code to reproduce this issue please. This would save time. Thank you

**Comment by yari-iran** [comment]
Hi Amir
I am Saeed. I am from Iran but live in canada.
Are you from Iran?

**Comment by gbm001** [comment]
There have been considerable changes to the Button classes and the way colours in them are controlled, so in the absence of a minimal example this bug can probably be closed?
