### ISSUE TITLE
Dropdown is not disappearing after selecting data

### ISSUE THREAD

**Issue by deepak1703raj** [kivymd/KivyMD#1122]
### Description of the Feature

After selecting data from dropdown it is not disappearing automatically

### Code and Logs

     from kivymd.app import MDApp
     from kivymd.uix.menu import MDDropdownMenu
     from kivy.lang import Builder
     from kivy.clock import Clock
     from kivymd.uix.screen import Screen
     from kivy.properties import ObjectProperty
     from kivy.uix.screenmanager import Screen, ScreenManager
     from kivymd.uix.datatables import MDDataTable
     from kivy.metrics import dp
     from kivy.uix.anchorlayout import AnchorLayout

     KV = """

    ScreenManager:   
       BuildApp:
            
    <BuildApp>:

     MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.menu.open()

    MDRaisedButton:
        id: button1
        text: "PRESS "
        pos_hint: {"center_x": .5, "center_y": .7}
        on_release: root.menu.open()
            
       """

     class BuildApp(Screen):
    
           def __init__(self, **kwargs):
              super().__init__(**kwargs)
             Clock.schedule_once(self._late_init)

         def _late_init(self, interval):
             #menu_items = [{"text": f"Item {i}"} for i in range(5)]
             d = ['Snapshot','Settings','History','Logout','Exit']
             menu_items = [
            {
                "text": i,
                "viewclass": "OneLineListItem",
                "on_release": lambda x=f"Item {i}": self.menu_callback(x),
            } for i in d
        ]
        self.menu = MDDropdownMenu(
            caller=self.ids.button,
            items=menu_items,
            width_mult=4,
        )

        dd = ['sSnapshot','Settings','History','Logout','Exit','LL']
        menu_items1 = [
            {
                "text": i,
                "viewclass": "OneLineListItem",
                "on_release": lambda x=f"Item {i}": self.menu_callback(x),
            } for i in d
        ]
        
        self.menu = MDDropdownMenu(
            caller=self.ids.button1,
            items=menu_items,
            width_mult=4,
        )
        #self.menu.bind(on_release=self.menu_callback)

      def menu_callback(self, instance_menu):
        print(instance_menu)

      def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Clock.schedule_once(self._late_init1)

      def _late_init1(self, interval):
        #menu_items = [{"text": f"Item {i}"} for i in range(5)]
        dd = ['Snapshot','Settings','History','LL']
        menu_items1 = [
            {
                "text": i,
                "viewclass": "OneLineListItem",
                "on_release": lambda x=f"Item {i}": self.menu_callback1(x),
            } for i in dd
        ]
        self.menu = MDDropdownMenu(
            caller=self.ids.button1,
            items=menu_items1,
            width_mult=4,
        )
        #self.menu.bind(on_release=self.menu_callback)

      def menu_callback1(self, instance_menu1):
        print(instance_menu1)
       
       sm = ScreenManager()

      class MainApp(MDApp):
    
       def build(self):
    	  self.root = Builder.load_string(KV)
    	  sm.add_widget(BuildApp(name='BuildApp'))
    	return sm
    
       MainApp().run()

### Screenshots

![image](https://user-images.githubusercontent.com/54531725/140889765-dc7bbaf8-b8a0-46f1-aaa6-6e2503cd6ed7.png)

![image](https://user-images.githubusercontent.com/54531725/140890072-c2b917e4-b451-4aa6-b5af-7174fb9ef72e.png)

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by deepak1703raj** [comment]
@HeaTTheatR, can you guide me. 

Dropdown is not disappearing automatically after selecting.

**Comment by HeaTTheatR** [comment]
@deepak1703raj Please edit your code.
