### ISSUE TITLE
ColorPicker not available ?

### ISSUE THREAD

**Issue by Bounty57** [kivymd/KivyMD#1124]
### Description of the Bug

I tried to call MDColorPicker but it seems to be nowhere, not in kivymd.uix.pickers and not in kivymd.uix.picker.
Is it no longer available ?

### Code and Logs

    from kivymd.uix.pickers import MDColorPicker
    ModuleNotFoundError: No module named 'kivymd.uix.pickers'

and

    from kivymd.uix.picker import MDColorPicker
    ImportError: cannot import name 'MDColorPicker' from 'kivymd.uix.picker'

### Versions

* OS: Windows 10
* Python: 3.8
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/colorpicker/

**Comment by Bounty57** [comment]
I tried the import from your documentation but it doesn't work... There is no "kivymd.uix.pickers". I just can find MDDatePicker, MDTimePicker and MDThemePicker in "kivymd.uix.picker" but no MDColorPicker.

**Comment by HeaTTheatR** [comment]
@Bounty57 
![Снимок экрана 2021-11-11 в 02 22 56](https://user-images.githubusercontent.com/16930280/141209537-6370a86e-e01a-4b76-a889-5fad90c99b70.png)

**Comment by Bounty57** [comment]
Ok thank you
