### ISSUE TITLE
MDTextField line_color_normal attribute update issue

### ISSUE THREAD

**Issue by Cedric-G-dev** [kivymd/KivyMD#1125]
### Description of the Bug
Hello,
I noticed a strange behavior when I tried to update the line_color_normal attribute of the MDTextField widget.

With the following code, pressing the 'update' button changes the line_color_normal attribute (expected behavior); but then when I enter/exit the textfield, the line_color_normal attribute is reset to its initial color.

### Code and Logs

```
from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.properties import ColorProperty

KV = '''
#:import images_path kivymd.images_path
Screen:
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'update'
            on_press: app.button(self)
        BoxLayout:
            padding: '20dp'
            MDTextField:
                id: input
                icon_right: 'email'
                hint_text: 'test'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

'''

class Test(MDApp):
    mycolor = ColorProperty([1, 0, 0, 1])

    def build(self):
        return Builder.load_string(KV)

    def button(self, instance):
        instance.parent.children[0].children[0].line_color_normal = self.mycolor

Test().run()
```

### Versions
Python: 3.8.11
Kivy: v2.0.0
KivyMD: 1.0.0.dev0, git-c9e8a26, 2021-11-11

**Comment by HeaTTheatR** [comment]
@Cedric-G-dev 
```python
        instance_fielf.line_color_normal = color
        instance_fielf._cache_colors["line_color_normal"] = color
```

**Comment by Cedric-G-dev** [comment]
@HeaTTheatR , Thank you, adding the following line does the trick.

Meanwhile, I can not propose a solution to change the file textfield.py yet.
