### ISSUE TITLE
Widgets on Back layer is clickable even when the front layer is there

### ISSUE THREAD

**Issue by xie186** [kivymd/KivyMD#1128]
### Description of the Bug

I adapted KickenSink demo codes. I found that even when the front layer is there, the widgets on the back layer is still clickable. 
Please see the first gif for details. As you can see, when the front layer is there, if I click a position overlap with back layer's widgets, it will change the style. 

Please see the second gif for an example in Kitchen Sink. Similar issue is encountered. 

Could you please help me solve this issue? Thank you. 

### Code and Logs

```
git clone https://github.com/xie186/KivyScanpy.git
cd KivyScanpy
git checkout 3b6cf8deb1fa0b323e6a01efb239d23c33859d60
cd KivyScanpy
pip install -r requirments.txt
python main.py
```

### Screenshots

![kivy_backdrop](https://user-images.githubusercontent.com/20909751/142350688-4d86890c-0e81-4665-a308-9444ab09a306.gif)

![kivy_backdrop_kitckensink](https://user-images.githubusercontent.com/20909751/142351235-b03ffb27-6ead-4ee5-b7c5-b28506612bc3.gif)

### Versions

* OS:  Windows 10
* Python:  3.7.8 
* Kivy: Kivy==2.0.0
* KivyMD: kivymd==0.104.2

Packages required can be obtained at `KivyScanpy/requirments.txt`.

**Comment by HeaTTheatR** [comment]
@xie186 This is fixed in the master branch of the KivyMD library.

**Comment by xie186** [comment]
I'll try it. Thanks for the quick response. I really appreciate it.

**Comment by xie186** [comment]
```
pip install https://github.com/kivymd/KivyMD/archive/master.zip
```
I used the command line above to install KivyMD. 

I was told:
```
Installing collected packages: kivymd
  Attempting uninstall: kivymd
    Found existing installation: kivymd 0.104.2
    Uninstalling kivymd-0.104.2:
      Successfully uninstalled kivymd-0.104.2
Successfully installed kivymd-1.0.0.dev0

```
But new issue came up. The back layer wouldn't hide after I checked "Light". Please see the gif below for details. I also tried Kitchen Sink. Same issue came up. 
![kivy_backdrop1](https://user-images.githubusercontent.com/20909751/142353103-d7c5a2a7-dc74-49cb-b56e-3aee3a93da7d.gif)

**Comment by HeaTTheatR** [comment]
@xie186 Yes, there is such a problem.
