### ISSUE TITLE
More work on MD buttons

### ISSUE THREAD

**Issue by gbm001** [kivymd/KivyMD#1144]
This is to keep track, and allow comment on, things I think either need fixing or I am planning on improving to do with KivyMD Buttons.

- If you use a multi-line label (which of course is not allowed by the MD spec, but that doesn't mean you can't) the label is not centered (easy fix - set halign='center', valign='center'/'middle' or whatever it is on the label).
- There may be some issues with square backgrounds behind FABs on Android (but not Linux) - I need to check this (might just be weirdness with my own app).
- Button sizes are not in accordance with the MD spec. The padding attribute is currently ignored (if symmetric) rather than added to the height/width. If the padding attribute is not symmetric then weirdness happens. The minimum height for buttons is currently set at 88 but the MD2 spec is 64dp (48dp in MD3). The button height is fixed in MD2 at 36dp (40dp in MD3); we should allow buttons to become larger than this when required but for text that fits this should be the button height. For all except text-only buttons, the padding should be 12dp to the icon (whether present or not), 4dp to the text label, and 16dp on the far side (16dp, 8dp and 24dp, respectively, for MD3). Text buttons should only have 8dp either side (12dp in MD3, with 8dp between icon and text if both present).
- Right-to-left text should have the icon at the right-hand end of an icon & text button.
- MD3 buttons are not supported (except FABs).

There are fundamentally two kinds of (MD2) buttons currently supported:
- 'Normal' buttons: These can be simple text buttons, or can be outlined, or can be filled, can have elevation behaviour, and can be rounded rectangles or just rectangles.
- 'Icon' buttons: Circular buttons with an icon at the centre; can be a FloatingActionButton if it has elevation behaviour.

In both MD2 and MD3, Floating Action Buttons can have text as well as an icon ('extended' FABs). This leaves the plain icon button as the _only_ button that doesn't take potentially both text and an icon. Consequently, it would probably be easier to roll the Icon properties into BaseButton since they could be used in almost every MD button, and always include (at least for the 'rectangular' buttons) both an icon and a text label. If the button had no icon (for a 'rectangular' button), the label would just be zero-width which (except for text-only buttons) gets the correct padding.
Consequently, I propose making these changes, fixing the label size/padding issues and minimum width/heights for the existing classes, then creating an 'MDButton' class which can be set to MD2 or MD3 and covers all rectangular button options via a 'button_type' parameter (which sets defaults for line color/width, background color/width etc). Then MDIconButton and MDFloatingActionButton would then remain as separate classes.

**Comment by HeaTTheatR** [comment]
In my opinion, this is a more appropriate place for this topic - https://github.com/kivymd/KivyMD/discussions
