### ISSUE TITLE
MDCard V3 throws error even when using example in docs

### ISSUE THREAD

**Issue by ENJ1** [kivymd/KivyMD#1151]
### Description of the Bug

When using MDCard V3 in Kivy v2.0.0 with Python 3.8.9 on macOS Monterey, the error `TypeError: object.__init__() takes exactly one argument (the instance to initialize)` is thrown, even when using the sample code provided in the docs. No other information is provided by the error, probably because the exception is handled and thrown up the application loops until it hits the main loop and the app crashes.

### Code and Logs

```python
from kivy.lang import Builder
from kivy.properties import StringProperty
from kivy.utils import get_color_from_hex

from kivymd.app import MDApp
from kivymd.uix.behaviors import RoundedRectangularElevationBehavior
from kivymd.uix.card import MDCard

KV = '''
#:import get_color_from_hex kivy.utils.get_color_from_hex


<MD3Card>
    padding: 16
    size_hint: None, None
    size: "200dp", "100dp"

    MDRelativeLayout:
        size_hint: None, None
        size: root.size

        MDIconButton:
            icon: "dots-vertical"
            pos:
                root.width - (self.width + root.padding[0] + dp(4)),                     root.height - (self.height + root.padding[0] + dp(4))

        MDLabel:
            id: label
            text: root.text
            adaptive_size: True
            color: .2, .2, .2, .8


MDScreen:

    MDBoxLayout:
        id: box
        adaptive_size: True
        spacing: "56dp"
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class MD3Card(MDCard, RoundedRectangularElevationBehavior):
    '''Implements a material design v3 card.'''

    text = StringProperty()


class TestCard(MDApp):
    def build(self):
        self.theme_cls.material_style = "M3"
        return Builder.load_string(KV)

    def on_start(self):
        styles = {
            "elevated": "#f6eeee", "filled": "#f4dedc", "outlined": "#f8f5f4"
        }
        for style in styles.keys():
            self.root.ids.box.add_widget(
                MD3Card(
                    line_color=(0.2, 0.2, 0.2, 0.8),
                    style=style,
                    text=style.capitalize(),
                    md_bg_color=get_color_from_hex(styles[style]),
                )
            )


TestCard().run()
```

(The sample code from docs)

### Versions

* OS: macOS Monterey 
* Python: 3.8.9
* Kivy: 2.0.0
* KivyMD: 0.104.2, git-bc7d1f5, 2021-06-06

### Quick Note

As I said above, application crashes on launch. If it helps, this is using the pygame backend because I would get an error saying that Kivy was unable to open a window without it. Thank you!

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch - https://kivymd.readthedocs.io/en/latest/components/card/#kivymd.uix.card.card.MDCard.style
https://kivymd.readthedocs.io/en/latest/themes/theming/#kivymd.theming.ThemeManager.material_style

`versionadded 1.0.0`

**Comment by ENJ1** [comment]
Edit: Using Kivy from pip fixed it. Thank you!
