### ISSUE TITLE
MDDataTable - Single Item Issue

### ISSUE THREAD

**Issue by espeoceka** [kivymd/KivyMD#1154]
### Description of the Bug

Hi, im trying example code for datatable, everything works fine until only one item is left on list.

Columns are not being filled with data:

### Code and Logs

table = MDDataTable(
            size_hint=(0.9, 0.6),
            column_data=[
                ("Column 1", dp(20)),
                ("Column 2", dp(30)),
                ("Column 3", dp(50)),
                ("Column 4", dp(30)),
                ("Column 5", dp(30)),
                ("Column 6", dp(30)),
                ("Column 7", dp(30)),
            ],
            row_data=[
                # The number of elements must match the length
                # of the `column_data` list.
                (
                    "1",
                    ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                    "Astrid: NE shared managed",
                    "Medium",
                    "Triaged",
                    "0:33",
                    "Chase Nguyen",
                ),
                
            ])

** Is there any workaround this issue...?

### Versions

* OS:  Windows
* Python: 3.9
* Kivy: Kivy==2.0.0
* KivyMD:  kivymd==0.104.2

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.

**Comment by espeoceka** [comment]
So i checked this with master branch and this problem is still there....

for example 

column_data=[
                ("First Name", dp(30)),
                ("Last Name", dp(30)),
                ("Email Address", dp(30)),
                ("Phone Number", dp(30))
            ],
            row_data=[
                ("John", "Elder", "john@codemy.com", "(123) 456-7891"),
            ]

![image](https://user-images.githubusercontent.com/47976946/148195412-1f9bac97-1497-4040-92e0-9601f42c8aa2.png)

**Comment by HeaTTheatR** [comment]
@espeoceka Use Kivy from master branch.
