### ISSUE TITLE
Option to change the shadow color of widgets

### ISSUE THREAD

**Issue by AdarshRevankar** [kivymd/KivyMD#1155]
**Requirement**

While using the **MDCard**, wanted to have a specific shadow color to the card, but after trying multiple options, I found that it is not possible at this point in time with kivymd to change the shadow color ! Please do provide me some help, to get this effect for the MDCard

<img width="917" alt="example" src="https://user-images.githubusercontent.com/48080453/148058235-9ae2acf4-d4e9-4185-87ae-7d0dc4136b65.png">

**Comment by HeaTTheatR** [comment]
Fix in master branch.
