### ISSUE TITLE
MDRectangleFlatButton Line_Color Bug

### ISSUE THREAD

**Issue by bskora** [kivymd/KivyMD#1157]
### Description of the Bug

When a MDRectangleFlat button is disabled and then activated, the line_color loses functionality. So even after enabling it, you cannot set the line_color to what you want, it wont update.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
       MDRectangleFlatButton:
            id: okaction
            font_style: "Button"
            theme_text_color: "Custom"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            line_color: C("FFFFFF")
            text_color: C("FFFFFF")
            text: "End Turn"
            disabled: True
"""

self.ids.okaction.disabled = False

```

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: 1.0.0.dev0 Master

**Comment by bskora** [comment]
I am still having this issue. The button I'm working with is always disabled by default. When it becomes enabled, it still appears as disabled. Only the text color changes. The line will not change color, even if you set it to after it becomes enabled. 

Disabled Button
![disabled button](https://user-images.githubusercontent.com/809979/149043448-4d055e9e-9485-49ef-a318-a77dcbc1694d.png)
Button was just enabled after being disabled
![not disabled button](https://user-images.githubusercontent.com/809979/149042889-0fd23647-133a-457f-b389-d34c21c71b11.png)

This one is an example of a button that has never been disabled at any point.
![neverdisabled](https://user-images.githubusercontent.com/809979/149043585-8209d1d8-4cf7-488b-8c9a-809a27d219f5.png)

**Comment by HeaTTheatR** [comment]
@Trenix Update the KivyMD library from the master branch.

**Comment by bskora** [comment]
> @Trenix Update the KivyMD library from the master branch.

I'm almost certain that I have. Is it working on your end?

```from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.screen import MDScreen

KV = """
#:import C kivy.utils.get_color_from_hex

ScreenManager:
    MainInfo:

<MainInfo>:
    name: "maininfo"
    spacing: "8dp"
    md_bg_color: C('#000000')
    
    MDBoxLayout:

        MDRectangleFlatButton:
            id: okaction
            font_style: "Button"
            theme_text_color: "Custom"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            line_color: C("FFFFFF")
            text_color: C("FFFFFF")
            text: "End Turn"
            disabled: True
            on_release:
                self.disabled = False
                
        MDRectangleFlatButton:
            font_style: "Button"
            theme_text_color: "Custom"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            line_color: C("FFFFFF")
            text_color: C("FFFFFF")
            text: "End Turn"
            on_release:
                root.fix()
"""


class MainInfo(MDScreen):
    def fix(self):
        self.ids.okaction.disabled = False


class MainApp(MDApp):
    def build(self):
        screen = Builder.load_string(KV)
        return screen


MainApp().run()

``

**Comment by HeaTTheatR** [comment]
@Trenix I don't understand the meaning of your example code...

**Comment by bskora** [comment]
So there are two buttons. On button activates the other button which was originally disabled. When enabled, the line_color for the button that got enabled, remains as the disabled_color. It cannot be changed. Once a button is disabled and then enabled, the line color cannot be changed, it remains as the disabled_color.

**Comment by HeaTTheatR** [comment]
@Trenix Your code example does not demonstrate this...

**Comment by bskora** [comment]
Can you take a picture on your end of what is the result? I'm certain I have the latest commit.

**Comment by HeaTTheatR** [comment]
@Trenix 
![Снимок экрана 2022-01-12 в 20 00 38](https://user-images.githubusercontent.com/16930280/149186706-ee7e813a-b9fe-4803-957b-cd7d60d36ef5.png)

**Comment by bskora** [comment]
I did a clean reinstall of kivymd master and it fixed it. Thanks!
