### ISSUE TITLE
KivyMD Text Input Field not accepting all android keyboards (like handwriting, regional language ) and not displaying multi language Unicode text.

### ISSUE THREAD

**Issue by nidhin84** [kivymd/KivyMD#1162]
### Description of the Bug

I am tying to build an an Android App that needs all language unicode text input in a single text input field. I am not able to type my regional language in it.  I am not able to switch google handwriting keyboard. When switching to handwriting keyboard, I am getting ordinary keyboard itself! I tried with kitchen sink  app, but showing same issue. I am stuck with my development. Please help me. Its urgent.

* OS: ubuntu 18.04
* Python: 3
* Kivy: 2.0.0
* KivyMD: https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by HeaTTheatR** [comment]
@nidhin84 This question is not related to `KivyMD` library. The `MDTextField` widget uses the `Kivy` `TextInput` widget, so contact Kivy support.

**Comment by nidhin84** [comment]
ok. thank you.
