### ISSUE TITLE
DataTable properties

### ISSUE THREAD

**Issue by Kanfit** [kivymd/KivyMD#1172]
### Description of the Bug

Elevation property is missing and causes TypeError.

### Code and Logs
TypeError: Properties ['elevation'] passed to __init__ may not be existing property names. Valid properties are ['_anim_alpha'...

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
Fix in master branch.
