### ISSUE TITLE
NavigationRail Bugs

### ISSUE THREAD

**Issue by bskora** [kivymd/KivyMD#1175]
### Description of the Bug

Icons on the rail are not centered and there doesn't seem to be a way of make them centered. Text is clipped if it's too long. Seems like after 10 characters the text will wrap which is very low. The opened rail does not utilize all the space when it's opened. If you spam opening and closing the rail, it will extend so much that it will never return to it's original position. The hover feature also bugs up, the first time you put your cursor over the icon it usually doesn't hover until you do it a second time.

In this code I did not include use_resizeable = True and use_title = True. By adding it, this creates a cog at the top right of the resized rail. However I tried everything within the documentation to call an event once the cog is pressed and nothing seems to work. Another issue I found is that when a MDNavigationRailItem is disabled, by pressing another non-disabled MDNavigationRailItem, the faded disabled icon no longer becomes faded as if it's disabled.

Some feature suggestions:
- Being able to hide and unhide the rail via a toolbar button.
- Being able to use Icon badges.
- Having a second rail appear next to the current one, when an icon is pressed.
- Tooltip functionality.

### Code and Logs

```
from kivy.lang import Builder
from kivymd.uix.screen import MDScreen
from kivymd.app import MDApp

KV = '''
#:import C kivy.utils.get_color_from_hex

ScreenManager:
    MainScreen:
    

<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title: "Name of Page"
            left_action_items: [["menu", lambda x: root.rail_open()]]

        MDBoxLayout:
            MDNavigationRail:
                radius: ["0dp"]
                id: rail
                use_resizeable: True

                MDNavigationRailItem:
                    size_hint_x: None
                    width: dp(800)
                    icon: "human-handsdown"
                    text: "Inventory"

                MDNavigationRailItem:
                    icon: "hiking"
                    text: "Discover"

                MDNavigationRailItem:
                    icon: "pine-tree"
                    text: "Gather"
'''

class MainScreen(MDScreen):

    def rail_open(self):
        if self.ids.rail.rail_state == "open":
            self.ids.rail.rail_state = "close"
        else:
            self.ids.rail.rail_state = "open"

class MainApp(MDApp):
    def build(self):
        screen = Builder.load_string(KV)
        return screen


if __name__ == "__main__":
    MainApp().run()
```

### Versions

* OS: Windows 10
* Python: 3.9.4
* Kivy: 2.0.0
* KivyMD: master

**Comment by HeaTTheatR** [comment]
Deprecated - https://github.com/kivymd/KivyMD/commit/c683f53e8eb565dc6510814c5e4382b78ce1e216
