### ISSUE TITLE
MDTextButton unexpected behaviour at runtime

### ISSUE THREAD

**Issue by ApuCoder** [kivymd/KivyMD#1176]
### Description of the Bug

Prior to this version (0.104.2) `MDTextButton` behaved usually. But in this version its height changes when different `text` is being set. Shouldn't that be all in one line ?

### Possible reason

I think that this unusual (if so) behaviour (behavior) is due to the incorporation of new attr. `adaptive_height` etc. in `MDLabel`. I guess that there may be some issues in `MDLabel` too.

### Possible solution

I additionally set the `text_size` attr. as, `text_size: None, self.height`. With this change that worked as expected.

### Code and Logs

```python
from kivy.lang.builder import Builder
from kivy.clock import Clock
from kivymd.app import MDApp


class Main(MDApp):
    def build(self):
        Clock.schedule_once(lambda *x : setattr(self.root.ids.txt_btn, "text", "This is the default Sample Text Button"), 3.0)
        return Builder.load_string("""

Screen:

	MDTextButton:
		id: txt_btn
		text: "Sample Text Button"
#		text_size: None, self.height
		color: app.theme_cls.primary_color
		pos_hint: {"center_x" : 0.5, "center_y" : 0.65}

""")


Main().run()

```

### Screenshots

https://user-images.githubusercontent.com/98318102/152496224-66543037-83eb-431b-9ea3-73b1cea2276e.mp4

### Versions

* OS: Android
* Python: 3.9.7
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@ApuCoder We do not support versions of the KivyMD library below 1.0.0

**Comment by sulaimanmichealolowosale** [comment]
Hello, I tried creating a text button that will hold any length of text. The width and height will adapt to the length of the text it holds.

`

        MDTextButton:

            text:"KivyMD is a collection of Material Design compliant widgets for use with Kivy, a framework for cross-platform, 
            touch-enabled graphica"

            pos_hint:{"center_x":.5, "center_y":.34}

            size_hint:None, None
            # size_hint_y: None
            text_size: None, None
            md_bg_color: [0,0,0,1]
            width: self.texture_size[0] + dp(5)
            height: self.texture_size[1]
            color: 1 , 0 , 0 , 1
`



I've tried everything but still, it's not working. Instead, I keep getting this error `[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute. Remaining events: `


I hope to get help here. Thank you.
