### ISSUE TITLE
MDSelectionList items are overlapping

### ISSUE THREAD

**Issue by USER4247** [kivymd/KivyMD#1182]
I have been trying making a selectable list with custom widgets as its contents . Whenever I use MDList , everything works perfectly but whenever I use MDSelectionList , if widgets are longer in length , widgets overlap each other . I have posted this issue on reddit with a video demonstrating the issue . Also there is another question , how can I pass texture_size[0] in python code , as whenever I add a widget , the widget gets squashed , you can understand better in the video 
here is the post.

https://www.reddit.com/r/kivy/comments/spaha1/mdselectionlist_messing_up_the_contents_of_list/

Thank you for your time.

**Comment by HeaTTheatR** [comment]
@USER4247 Attach a minimal code example that reproduces this behavior.

**Comment by USER4247** [comment]
> @USER4247 Attach a minimal code example that reproduces this behavior.

here is the code sample in my repository

https://github.com/USER4247/Demo

**Comment by USER4247** [comment]
So what am I doing wrong ? . It works perfectly if I use MDList

**Comment by HeaTTheatR** [comment]
@USER4247 https://github.com/kivymd/KivyMD/issues/1182#issuecomment-1035931624

**Comment by USER4247** [comment]
Well , any luck?? . I made a repo because there were some files required for execution and it would have been a headache if I provided em in text here .
Is there something I am doing wrong ?

**Comment by HeaTTheatR** [comment]
@USER4247 

If you would like to get an answer to your question quickly, please follow the following small terms:

If you get an error in your code, please describe your question in one message and attach MINIMUM CODE .

MINIMUM CODE is:

Code in which there are no unnecessary imports, classes, functions, widgets that are not related to the reproduction of the error.

KV string should be in the code, not in a separate file, for example:

```python
[imports]

KV = """
    ...
"""

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

If your code exceeds the allowed number of characters in one message, then this is not the MINIMUM CODE. Your code should run in three clicks: Copy/Paste/Run.
If this is not possible in three clicks, this is NOT the MINIMUM CODE.

**Comment by USER4247** [comment]
I am trying to paste my code in the comment but it's pasting it like this

`[imports]

KV = """
    ...
"""

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()'

My code is about 113 lines long and there is only 1 .py file which has all the essentials to run code .
I am using <> to add code . 
I am new to GitHub so please spare me if I did something wrong.

**Comment by USER4247** [comment]
Here is the code 
```
from kivymd.app import MDApp 
from kivy.core.window import Window
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.uix.scrollview import ScrollView
from kivymd.uix.list import *
from kivymd.uix.label import MDLabel
from kivy.uix.widget import Widget
from kivy.lang.builder import Builder
from kivymd.uix.button import *
from kivymd.uix.textfield import MDTextField
from kivy.animation import Animation
Window.size=(320,600)
kv = '''
MDBoxLayout:
    orientation: "vertical"
    MDBoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        padding: [0, 0, 10, 0]
    ScrollView:
        MDSelectionList: #-----------------> here if its changed to MDList , everything works fine
            id: msglist 
    MDBoxLayout:
        padding: [10, ]
        spacing: 5
        size_hint_y:None
        height: 80
        MDTextField:
            id: text
            multiline:True
        MDIconButton:
            icon: "send" 
            on_press: app.send_message(text.text)

<ChatBubble@Widget>:
    id: chtbld
    md_bg_color: [0, 0, 0, 0]
    size_hint_y: None
    height: 60
    adaptive_height: True
    padding: [10, 0, 10, 0]
    orientation: 'vertical'
    MDBoxLayout:
        id: box
        height:msg_content.height
        size_hint: None, None
        md_bg_color: app.theme_cls.bg_darkest 
        MDRelativeLayout:
            id: boxT
            MDLabel:
                id: msg_content
                text: root.msg
                font_size:15
                height: self.texture_size[1]
                width: msg_content.texture_size[0]
                text_size:  [None, None]
                size_hint_y: None
                halign: 'left'
                color: app.theme_cls.opposite_bg_normal
            MDBoxLayout:
                spacing: 3
            MDFlatButton:
                #width: 200
                width: msg_content.texture_size[0]
                height:msg_content.texture_size[1]
                size_hint: None, None
                radius: [10, 10, (1, -5), 10] if self.pos_hint == {'right': 1} else [10, 10, 10, (1, -5)]
                md_bg_color: app.theme_cls.bg_darkest
'''
class ChatBubble(MDBoxLayout):
    msg = StringProperty()
    time = StringProperty()
class ChatApp(MDApp):
    def build(self):
        GUI=Builder.load_string(kv)        
        return GUI
    def send_message(self,message):
        self.msg = ChatBubble()
        self.root.ids["text"].text = ""
        self.msg.ids["msg_content"].text = message
        p = message
        if len(p) <= 5:
            width = 70
        elif 10 < len(p) <=15:
            width = 120
        elif len(p)>25:
            width = 220
        self.root.ids["msglist"].add_widget(self.msg)        
    def set_selection_mode(self, instance_selection_list, mode):
        pass
    def selected(self,instance_selection_list,instance_selection_item):
        pass
    def unselected(self,instance_selection_list,instance_selection_item):
        pass
if __name__ == "__main__":
    ChatApp().run()
```
If you change MDSelectionList to MDList , widgets will not overlap

Try it out by writing in something into txtfield and then writing 
1
2
3
4
5
6
Widgets will overlap but overlapping doesn't occur in MDList

**Comment by USER4247** [comment]
So , what's the problem here ??

**Comment by HeaTTheatR** [comment]
@USER4247 No, I haven't looked at this problem in detail yet...

**Comment by HeaTTheatR** [comment]
@USER4247 The above code cannot be tested because it is full of bugs. In addition, this is not a minimal example and it does not demonstrate absolutely anything. Edit your code example.

**Comment by USER4247** [comment]
I have removed the unwanted lines in code . Only important part is above the <ChatBubble@Widget> . Rest of the code is just adding the text input in selectionlist . Anything the user writes is shown inside custom wiget aka <ChatBubble@Widget> . The problem is with spacing in SelectionList inside ScrollView . Widgets containing user text overlap each other's space . But spacing is fine in case of MDList . Changing SelectionList to MDList auto-spaces everything and widgets dont overlap. Try writing anything then writing  a long list . The list will overlap the previous widgets only in case of SelectionList.

**Comment by HeaTTheatR** [comment]
@USER4247 At least 50 lines of code in your example are redundant and have nothing to do with reproducing the error.

**Comment by USER4247** [comment]
Sir , I am still leaning to code . I have tried my best to make a small example of problem that I am facing with SelectionList. Please view the reddit link that I have provided , it explains the problem with a video .

**Comment by HeaTTheatR** [comment]
@USER4247 You must attach a minimal code example here.

**Comment by USER4247** [comment]
this time I have shorten the code as well as there is an example pre-loaded in the code. Code is about 70 lines.
```
from kivymd.app import MDApp 
from kivy.core.window import Window
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.uix.scrollview import ScrollView
from kivymd.uix.list import *
from kivymd.uix.label import MDLabel
from kivy.uix.widget import Widget
from kivy.lang.builder import Builder
from kivymd.uix.button import *
from kivymd.uix.textfield import MDTextField
Window.size=(500,500)
kv = '''
MDBoxLayout:
    orientation: "vertical"
    MDBoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        padding: [0, 0, 10, 0]
    ScrollView:
        MDSelectionList: #-----------------> here if its changed to MDList , everything works fine
            id: msglist 
            size_hint_y:None
    MDBoxLayout:
        padding: [10, ]
        spacing: 5
        size_hint_y:None
        height: 80
        MDTextField:
            id: text
            multiline:True
        MDIconButton:
            icon: "send" 
            on_press: app.push_text(text.text)

<Custom_Box@Widget>:
    MDBoxLayout:
        height:msg_content.height
        size_hint: None, None
        md_bg_color: app.theme_cls.bg_darkest 
        MDRelativeLayout:
            MDLabel:
                id: msg_content
                text: root.msg
                font_size:15
                height: self.texture_size[1]
                width: self.texture_size[0]
                text_size:  [None, None]
                size_hint_y: None
                halign: 'left'
                color: app.theme_cls.opposite_bg_normal
'''
class Custom_Box(Widget):
    msg = StringProperty()
class SelectionListTest(MDApp):
    def build(self):
        GUI=Builder.load_string(kv)        
        return GUI
    def on_start(self):
        example = ['this is example message',"a"*70,'2nd message overlaps first message','following problem does not occur in MDList']
        for data in example:
            self.msg = Custom_Box()
            self.msg.ids["msg_content"].text = data
            self.root.ids["msglist"].add_widget(self.msg)
    def push_text(self,text):
        self.msg = Custom_Box()
        self.root.ids["text"].text = ""
        self.msg.ids["msg_content"].text = text
        self.root.ids["msglist"].add_widget(self.msg)    
if __name__ == "__main__":
    SelectionListTest().run()


```

**Comment by USER4247** [comment]
With all due respect sir , is the problem explained properly ? , if not , I will rewrite the code.

**Comment by USER4247** [comment]
is my problem clear now ?
