### ISSUE TITLE
After changing the text of the MDFillRoundFlatIconButton, it wraps

### ISSUE THREAD

**Issue by Axentiev** [kivymd/KivyMD#1184]
Text wraps after changing in MDFillRoundFlatIconButton (screenshot below)

How fix it?

### Screenshots

![Screenshot_2022-02-13-21-18-56-550_org kivymd learning_english](https://user-images.githubusercontent.com/76518901/153762732-14318366-5384-4a87-acea-d214eb5c91f1.jpg)

### Versions

* OS: Linux Mint
* Python: 3.9.4
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@Axentiev We do not support version 0.104.2.
