### ISSUE TITLE
Strange red dots display on App upon right clicks

### ISSUE THREAD

**Issue by amiracam** [kivymd/KivyMD#1185]
### Description of the Bug

if one does a right click , a red dot gets displaced on the screen and per every other subsequent right click.
It feels like some sort of development artifact used to assist in collision detection, so perhaps my app is in some sort of "dev" mode ? 
or the app has measles :)

Just load the example here:

https://kivymd.readthedocs.io/en/latest/components/selection/index.html
the example has not been modified in any way.
and after running do right clicks on the app

### Screenshots

![image](https://user-images.githubusercontent.com/508408/154728422-91dbab74-9ff2-4cdf-a942-141592a0e9bd.png)

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: latest
* KivyMD: latest

**Comment by HeaTTheatR** [comment]
https://stackoverflow.com/questions/12692851/why-does-right-clicking-create-an-orange-dot-in-the-center-of-the-circle

**Comment by amiracam** [comment]
thank you
