### ISSUE TITLE
MDLabel error

### ISSUE THREAD

**Issue by qizheng-1998** [kivymd/KivyMD#1189]
Getting following error "ValueError: MDLabel.text_color has an invalid format (got [1, 1, 1, 1])" when using the kivymd from the master. No issue with older version of kivymd .

    MDNavigationDrawer:

        MDNavigationDrawerItem:
            id:mainpg
            icon: 'home'
            text: "Home"
            on_release: app.main_widget.ids.scr_mngr.current = 'mainpg'

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/navigationdrawer/#standard-content-for-the-navigation-bar
