### ISSUE TITLE
Problem with colors...

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#119]
#### Description of the Bug

I used the following code for a sample app with one simple MDTextField
when I run the app, the hint text is somehow blacky and if I click to focus on textfield and move out of it to make the hint text back to it's position again it became greenish, dark green in fact, is there any problem with my code?

Edited: it seems that the problem is with the Dark style, when I use the Dark style, everything is somehow Darky and colors are not shows correctly

### Code and Logs

```python
    theme_cls.primary_palette = 'Green'
    theme_cls.accent_palette = 'Amber'
    theme_cls.theme_style = 'Dark'
```

### Versions

* OS: Windows 10 x64
* Python: 3.7
* Kivy: latest
* KivyMD: latest

**Comment by ArtemSBulgakov** [comment]
I have tested it with Kitchen Sink demo. It is really a bug.

Before doing anything:
![image](https://user-images.githubusercontent.com/44732506/67160925-444ec880-f35e-11e9-8680-6acfcc401eab.png)

After clicking:
![image](https://user-images.githubusercontent.com/44732506/67160932-4b75d680-f35e-11e9-9bf9-c41194a4001f.png)

After losing focus:
![image](https://user-images.githubusercontent.com/44732506/67160935-50d32100-f35e-11e9-9dba-c8de7f506137.png)

**Comment by dezashibi** [comment]
This is also another problem with the Dark mode, as you see, 2 same logo, same color and meaningless

![image](https://user-images.githubusercontent.com/11794726/67160990-1fa91f80-f363-11e9-8ffb-4faf661a107c.png)

**Comment by sagarhm** [comment]
> I have tested it with Kitchen Sink demo. It is really a bug.
> 
> Before doing anything:
> ![image](https://user-images.githubusercontent.com/44732506/67160925-444ec880-f35e-11e9-8680-6acfcc401eab.png)
> 
> After clicking:
> ![image](https://user-images.githubusercontent.com/44732506/67160932-4b75d680-f35e-11e9-9bf9-c41194a4001f.png)
> 
> After losing focus:
> ![image](https://user-images.githubusercontent.com/44732506/67160935-50d32100-f35e-11e9-9dba-c8de7f506137.png)

plzz can help me how make the 2nd text fild shape type in kivymd

**Comment by HeaTTheatR** [comment]
@sagarhm You are using the old version from PyPi. Update KivyMD library from master branch.
