### ISSUE TITLE
MDTabsLabel

### ISSUE THREAD

**Issue by qizheng-1998** [kivymd/KivyMD#1191]
### Description of the Bug

Your text

Description of the Bug

Getting the following error with kivymd from the master

File "kivy/properties.pyx", line 498, in kivy.properties.Property.set
03-04 11:39:02.932 17686 17939 I python : File "kivy/properties.pyx", line 527, in kivy.properties.Property.set
03-04 11:39:02.934 17686 17939 I python : File "kivy/properties.pyx", line 2020, in kivy.properties.ColorProperty.convert
03-04 11:39:02.937 17686 17939 I python : ValueError: MDTabsLabel.text_color_normal has an invalid format (got [1, 1, 1, 1])
Code and Logs

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
                    MDLabel:
                        id: welcome_label
                        text: "WELCOME"
                        font_size: 40
                        halign: 'center'
                        size_hint_y: None
                        height: self.texture_size[1]
                        padding_y: 15
                        theme_text_color: "Custom"
                        text_color: 1, 1, 1, 1
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Versions

* OS: linux
* Python: 3.7.6
* Kivy: 2.0.0
* KivyMD: 1.0.0.dev0

**Comment by HeaTTheatR** [comment]
@QiZheng-stellarnet What does your code have to do with the MDTabsLabel class?
