### ISSUE TITLE
MDIconButton (MDToolTip) bounding box overlap, scaling icons

### ISSUE THREAD

**Issue by OJtheDJ** [kivymd/KivyMD#1196]
### Description of the Bug

The clickable bounding box of the MDIconButton is too big, especially for small icons close together. This can cause the overlap of icon's bounding boxes, while the icons itself do not overlap, which in turn results in not knowing which button will be clicked. Overlapping bounding boxes result in funny MDTooltip behaviour, too. Tooltip is only shown when entering the bounding box with the mouse cursor from a horizontal position.
In a previous version of kivymd (a long time ago) the bounding box was only as big as the icon itself, if I remember correctly. The MDIconButton was scaled with the "size" parameter back then.

Side Issue:
I don't know if the following is intended: not releasing the left mouse button after clicking and then leaving the boundary box lets the ripple effect circle stay visible.

Possible Fix:
This will make the bounding box fit the icon's size:

in button.py -> class MDIconButton(BaseRoundButton, BasePressedButton): -> def set_size(self, interval):

self.width = (
            # "48dp" if not self.user_font_size else dp(self.user_font_size + 23)
            "48dp" if not self.user_font_size else dp(self.user_font_size)
        )
        self.height = (
            # "48dp" if not self.user_font_size else dp(self.user_font_size + 23)
            "48dp" if not self.user_font_size else dp(self.user_font_size)
        )

Suggestion:
If someone desires this behaviour, maybe an additional parameter could be added to specify how far the bounding box should go over the edges of the icon

MDIconButton documentation:
"icon_size" parameter is not available in button.py
"user_font_size " can be bare integer or string ('...sp' or '...dp')

Min working example below

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.metrics import dp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.button import MDIconButton
from kivymd.uix.tooltip import MDTooltip

root_kv = """
MyClass:
    orientation: 'vertical'
    padding: '300dp'
"""

class MDTooltipMDIconButton(MDIconButton, MDTooltip):
    pass

class MyClass(MDBoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.app = MainApp.get_running_app()
        self.create_widgets()

    def create_widgets(self, *args):
        layout_1 = MDBoxLayout(size_hint_y=None, height='28dp', spacing='12dp')
        iconbutton_del_1 = MDTooltipMDIconButton(user_font_size = 24, icon='delete-forever-outline', tooltip_text='Tooltip_1', pos_hint={'center_y': 0.5, 'x': 0})
        layout_2 = MDBoxLayout(size_hint_y=None, height='28dp', spacing='12dp')
        iconbutton_del_2 = MDTooltipMDIconButton(user_font_size = '24sp', icon='delete-forever-outline', tooltip_text='Tooltip_2', pos_hint={'center_y': 0.5, 'x': 0})
        layout_1.add_widget((iconbutton_del_1))
        layout_2.add_widget((iconbutton_del_2))
        self.add_widget(layout_1)
        self.add_widget(layout_2)

class MainApp(MDApp):
    def __init__(self, **kwargs):
        self.title = "My Material Application"
        super().__init__(**kwargs)

    def build(self):
        # self.theme_cls.theme_style = 'Light'
        # self.theme_cls.primary_palette = "Orange"
        # self.theme_cls.accent_palette = 'LightGreen'
        self.root = Builder.load_string(root_kv)


if __name__ == "__main__":
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

![BB_overlap_MDIconButton](https://user-images.githubusercontent.com/99122639/158054750-cef52190-2961-4856-8f2d-532f7e333b24.PNG)

### Versions

* OS: Win10 Prof
* Python: 3.7
* Kivy: 2.1.0
* KivyMD: commit 8dc5c9b from 12 Mar 2022

**Comment by HeaTTheatR** [comment]
The MDIconButton class is fully compliant with material design.
