### ISSUE TITLE
Widget not viewed properly when disabled

### ISSUE THREAD

**Issue by hoba87** [kivymd/KivyMD#1197]
### Description of the Bug

When widgets are disabled, some of them are not view properly, e.g. the helper text of MDTextView is not shown or the text of MDDropDownItem is not shown. I have not tested all, but at least for the given examples this seems to be the case.

### Versions

* OS: Win10
* Python: 3.9
* Kivy: 2.1
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
We do not support version 0.104.2. Use the master version of the KivyMD library

**Comment by hoba87** [comment]
For master version the bug for MDDropDownItem is still present.

**Comment by HeaTTheatR** [comment]
@hoba87 Create a new issue according to the template.
