### ISSUE TITLE
MDTextField unwanted unfocus

### ISSUE THREAD

**Issue by hoba87** [kivymd/KivyMD#1199]
### Description of the Bug

MDTextField unfocusses when deleting everything by backspace.

### Versions

* OS: Win 10
* Python: 3.9.10
* Kivy: 2.1
* KivyMD: 1.0.0.dev0

**Comment by hoba87** [comment]
@HeaTTheatR perhaps you should read your "Code of Conduct" again

**Comment by HeaTTheatR** [comment]
@hoba87 You should learn good manners! Don't post here anymore!

**Comment by hoba87** [comment]
> @hoba87 You should learn good manners! Don't post here anymore!

@HeaTTheatR No comment. A buggy project which is not interested in bug reports, instead insulting contributors? Don't worry, I will not waste my time with that.

**Comment by HeaTTheatR** [comment]
@hoba87
The project is not interested in users like you! I pointed out to you that your code example is redundant and misleading those who will investigate the problem. Instead of fixing your code, you called my comments useless. So go to hell with your opinion!

**Comment by hoba87** [comment]
@HeaTTheatR yeah, instead of being grateful for help, swearing around because my bug report was not perfect. It was a trivial bug report, with some example code just copied from the project. Nothing what should overwhelm a "core developer".

**Comment by HeaTTheatR** [comment]
@hoba87
You responded with an insult to a constructive remark! So go to school and learn good manners. I have no desire to communicate with a troll like you! Adios!

**Comment by hoba87** [comment]
@HeaTTheatR distorting facts. No more words.

**Comment by HeaTTheatR** [comment]
@hoba87
![Снимок экрана 2022-03-17 в 14 55 19](https://user-images.githubusercontent.com/16930280/158803470-2028fd66-3c02-41f2-8c03-de8a31ad5370.png)
![Снимок экрана 2022-03-17 в 14 55 33](https://user-images.githubusercontent.com/16930280/158803489-65ff304f-3fe5-430e-adea-b34fe78ed6aa.png)

If you consider the remark of the core developer to be absolutely unnecessary comments, then I can only tell you one thing:

**Listen, get the hell out of here! This is not made for you and not for people like you. Don't go littering the comments - no one needs you here! You were not invited here. You are not welcome here! Get out of here. And never come back! Is it clear?**

**Comment by hoba87** [comment]
@HeaTTheatR Thank you for proving.
