### ISSUE TITLE
kivyMd recipe

### ISSUE THREAD

**Issue by selobu** [kivymd/KivyMD#12]
It would be nice if you could write a recipe to be used by p4a, so if you use python3 it still continue working.

[Python 4 android recipes](https://github.com/kivy/python-for-android/tree/59f6a6bb359a2b97e5ff50652dc999a5b449cab8/pythonforandroid/recipes)

**Comment by HeaTTheatR** [comment]
requirements = kivy==master,git+https://github.com/HeaTTheatR/KivyMD.git
