### ISSUE TITLE
Can ScrollView support widget creation while scrolling down ?

### ISSUE THREAD

**Issue by USER4247** [kivymd/KivyMD#1201]
I just have a question , can i create widgets as i am scrolling up or down in scrollview ? I tried using RecycleView , but its not suited for mu use case....
I did read documentation and there are events like on_scroll_down etc. Can i use those events to create widgets in ScrollView while Scrolling to a specific distance ?

**Comment by HeaTTheatR** [comment]
@USER4247 Your question is not related to the KivyMD library.
