### ISSUE TITLE
make MDFileManager suport multiselect please

### ISSUE THREAD

**Issue by chineselzh** [kivymd/KivyMD#1204]
### Description of the Feature

can MDFileManager suport multiselect?thank's!

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@chineselzh 
```python
file_manager = MDFileManager(selector="multi")  # 1.0.0-dev
```

**Comment by chineselzh** [comment]
@HeaTTheatR thank you!
