### ISSUE TITLE
JetBrains kvMD auto-completion

### ISSUE THREAD

**Issue by noembryo** [kivymd/KivyMD#121]
Not an issue, just a heads up.

I was using this [settings file](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fkivy%2Fkivy%2Fwiki%2FSetting-Up-Kivy-with-various-popular-IDE%27s&sa=D&sntz=1&usg=AFQjCNGLFjDEEKAjUhFgV3nSBamSGWcLvg) that offered auto-completion and syntax highlighting for years, and I kept on adding new keywords as I found them.

After seeing kivyMD, I uploaded this [newer version](https://github.com/noembryo/KV4Jetbrains) (updated, a little restructured and with kivyMD support).

I hope you find it useful.
Also, feel free to inform me about missing keywords I should add, so that I can update it.

**Comment by HeaTTheatR** [comment]
Cool! I will add your settings file to the KivyMD repository.

**Comment by noembryo** [comment]
Keep in mind that I will keep on updating it.. ;o)
