### ISSUE TITLE
Change font style for MDNavigationRail

### ISSUE THREAD

**Issue by j4ggr** [kivymd/KivyMD#1211]
### Idea

It would be nice if you could change the font styles of the MDNavigationRailItems globally at MDNavigationRail. 
So that the defined font styles "Subtitle1", "Caption", "Body2" etc. can be used. 

### Code sample

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
MDScreen:
    MDBoxLayout:
        orientation: "horizontal"
        
        MDNavigationRail:
            font_style: "Body2"
            
            MDNavigationRailItem:
                icon: "language-python"
                text: "Text"
    
        MDLabel:
            font_style: "Body2"
            text: "Text\\nfont style: Body2"
        
        MDLabel:
            font_style: "Body1"
            text: "Text\\nfont style: Body1"
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
Currently the "font_style" property of the MDNavigationRail has no effect on the text of the MDNavigationRailItem. The idea is that with the above code the font of the item would be the same as the label in the middle and not like the label on the right :

![kivymd_font_style](https://user-images.githubusercontent.com/43211511/159245144-1e81df2a-000b-465d-90c3-147fe82adb89.png)

### Versions

* OS:  Windows 10
* Python: 3.9.7
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@j4ggr We do not support version `0.104.2`. In addition, in version `1.0.0`, the `MDNavigationRail` widget has completely changed its `API`. In the next few days, these changes will be added to the `master` branch.
