### ISSUE TITLE
Deprecation Warning triggered when using title property of MDTabs

### ISSUE THREAD

**Issue by epitavy** [kivymd/KivyMD#1217]
### Description of the Bug
When using MDTabs, a **DeprecationWarning** is raised because the code uses the StringProperty `text` of MDTabsBase. However, nowhere in the user code the `text` property is used. The only property used is the `title` property.

### Code and Logs
Juste run the following code and see the Deprecated in the logs about the StringProperty `text`, while there is no use of it in the code.

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.floatlayout import MDFloatLayout

KV = '''
MDBoxLayout:
    orientation: "vertical"


    MDTabs:
        Tab:
            title: "Tab 1"
        Tab:
            title: "Tab 2"
        Tab:
            title: "Tab 3"

<Tab>
    MDLabel:
        text: root.title
        halign: "center"
'''


class Tab(MDFloatLayout, MDTabsBase):
    pass


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

TestApp().run()
```

### Output
 ```
.
.
.
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] Deprecated property "<StringProperty name=text>" of object "<__main__.Tab object at 0x7f734d0bac80>" has been set, it will be removed in a future version
[INFO   ] [Base        ] Start application main loop
```

### Versions

* OS: Ubuntu 20.04
* Python: 3.8.10
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
These are internal class properties that are marked as deprecated. This will be removed with a new release of the library.

**Comment by HeaTTheatR** [comment]
And we do not support any version of the library other than the master version.

**Comment by epitavy** [comment]
Why these internal properties are used if they are declared as deprecated ?
The warning suggests thatthe user code is actually using the deprecated property. IMO no warning should be raised as the user code do not rely directly on deprecated properties.
