### ISSUE TITLE
MDDataTable selected data of the first page even when pressing rows on the next pages.

### ISSUE THREAD

**Issue by honghuzi** [kivymd/KivyMD#1223]
### repeate process

1. set use_pagination=True, and create a MDDataTable with more rows than rows_num. for example rows_num = 5
2. start the app, switch to the second or later pages, press any row, for example the 3rd row for page 3, namely, the 13th row for the total dataframe
3. the 3rd row not the 13th row was selected.

### Code and Logs

```python
        re_df = pd.DataFrame([[i, i] for i in range(20)], columns=['a', 'b'])
        data_tables = MDDataTable(
            use_pagination=True,
            rows_num=5,
            size_hint=(1, 0.8),
            column_data=[
                (f"[size=20][color=#65275d]{c}[/color][/size]", dp(35))
                for c in re_df.columns
            ],
            row_data=[tuple(r) for r in re_df.values],
        )
        data_tables.bind(
            on_row_press=self.show_result()
        )
```

### Versions

* OS: Windows10
* Python: 3.9.0
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@honghuzi KivyMD version 0.104.2 is deprecated and not supported. Use the master branch of the library.

**Comment by honghuzi** [comment]
> @honghuzi KivyMD version 0.104.2 is deprecated and not supported. Use the master branch of the library.

updated to the master branch, but the bug remains.
