### ISSUE TITLE
MDDatePicker bug in date input dialog

### ISSUE THREAD

**Issue by arol005** [kivymd/KivyMD#1225]
### Description of the Bug

Hi! I found a bug in MDDatePicker. 
When you are in the date input dialog, when you click on the OK button, not the selected date is transmitted, but today. 

And if, after input the date, you switch to the date selection, two dates become selected - the previous one and the one that you entered in the dialog.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.pickers import MDDatePicker

KV = '''
MDFloatLayout:

    MDToolbar:
        title: "MDDatePicker"
        pos_hint: {"top": 1}
        elevation: 10

    MDRaisedButton:
        text: "Open date picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_date_picker()
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_save(self, instance, value, date_range):
        print(instance, value, date_range)

    def on_cancel(self, instance, value):
        '''Events called when the "CANCEL" dialog box button is clicked.'''

    def show_date_picker(self):
        date_dialog = MDDatePicker()
        date_dialog.bind(on_save=self.on_save, on_cancel=self.on_cancel)
        date_dialog.open()


Test().run()
```

### Screenshots

https://drive.google.com/file/d/1nxhIOS8WbEcxQbD9bFTtt3odLhaiQUrY/view?usp=sharing
https://drive.google.com/file/d/1hv7BwNU6TXrONJXhl6I2SJhsChoPy30J/view?usp=sharing

### Versions

* OS: Win10
* Python: 3.10
* Kivy: 2.1.0
* KivyMD: 1.0.0.dev0

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1169
