### ISSUE TITLE
MDDatePiker wrong AM/PM selector

### ISSUE THREAD

**Issue by arol005** [kivymd/KivyMD#1226]
### Description of the Bug

When you pass the date value through the set_time method, the selector is always AM. In the test, the time was 14:20, and the selector was still on AM.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.pickers import MDTimePicker

KV = '''
MDFloatLayout:

    MDToolbar:
        title: "MDTimePicker"
        pos_hint: {"top": 1}
        elevation: 10

    MDLabel:
        id: time_label
        text: "Some Stuff!!!"
        pos_hint: {'center_x': .95, 'center_y': .7}
 
    MDRaisedButton:
        text: "Open time picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_time_picker()
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_save(self, instance, value, date_range):
        '''
        Events called when the "OK" dialog box button is clicked.

        :type instance: <kivymd.uix.picker.MDDatePicker object>;

        :param value: selected date;
        :type value: <class 'datetime.date'>;

        :param date_range: list of 'datetime.date' objects in the selected range;
        :type date_range: <class 'list'>;
        '''

        print(instance, value, date_range)

    def on_cancel(self, instance, value):
        '''Events called when the "CANCEL" dialog box button is clicked.'''

    def show_time_picker(self):
        from datetime import datetime

        # Define default time
        default_time = datetime.strptime("14:20:00", '%H:%M:%S').time()

        time_dialog = MDTimePicker()
        # Set default Time
        time_dialog.set_time(default_time)
        time_dialog.bind(on_cancel=self.on_cancel, time=self.get_time)
        time_dialog.open()

    def get_time(self, instance, time):
        self.root.ids.time_label.text = str(time)


Test().run()

```

### Screenshots

![scr3](https://user-images.githubusercontent.com/103219826/163689349-17f35263-af4e-4d7d-9d25-51a515376b7b.JPG)

### Versions

* OS: Win10
* Python: 3.10
* Kivy: 2.1.0
* KivyMD: master

**Comment by arol005** [comment]
https://github.com/kivymd/KivyMD/blob/5a5db42ac8b526bc4bebdecf71b1ef33e8e4537b/kivymd/uix/pickers/timepicker/timepicker.py#L635
I tried to change to 
**self._am_pm_selector.selected = selected**
 and it worked

**Comment by bernhardkaindl** [comment]
@arol005 @HeaTTheatR: Submitted #1255 with the fix to add this line:
https://github.com/bernhardkaindl/KivyMD/blob/19a6ddd40637d91189809cf200132bca1eaf0813/kivymd/uix/pickers/timepicker/timepicker.py#L635
```py
self.am_pm = selected
```
I think this is correct because `self.am_pm` is used by `_get_data()` when converting the time data to a string:
https://github.com/kivymd/KivyMD/blob/5a5db42ac8b526bc4bebdecf71b1ef33e8e4537b/kivymd/uix/pickers/timepicker/timepicker.py#L641
