### ISSUE TITLE
Error in Date picker

### ISSUE THREAD

**Issue by ps2229** [kivymd/KivyMD#1232]
04-25 11:24:28.154  7869 15484 I python  :    File "/content/.buildozer/android/app/main.py", line 16, in <module>
04-25 11:24:28.154  7869 15484 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp5/armeabi-v7a/kivymd/uix/pickers/__init__.py", line 3, in <module>
04-25 11:24:28.154  7869 15484 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp5/armeabi-v7a/kivymd/uix/pickers/timepicker/__init__.py", line 1, in <module>
04-25 11:24:28.154  7869 15484 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp5/armeabi-v7a/kivymd/uix/pickers/timepicker/timepicker.py", line 253, in <module>
04-25 11:24:28.154  7869 15484 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp5/armeabi-v7a/kivymd/uix/pickers/timepicker/timepicker.py", line 278, in TimeInput
04-25 11:24:28.154  7869 15484 I python  :  TypeError: 'type' object is not subscriptable

 
Trying to import the MDdatepicker but again and again it is leading to errors in android device.Tried both //from kivymd.uix.pickers import MDDatePicker and //from kivymd.uix.picker import MDDatePicker both are leading to errors
### Versions

* OS: Android
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: https://github.com/kivymd/KivyMD/archive/master.zip used this in buildozer as well.

**Comment by dataserver** [comment]
Type hint used is from python 3.9. The default buildozer  python version is v3.8.5 


from \_\_future__ import annotations

**Comment by cristianmejiaarias** [comment]
I get the same issue, please help.

**Comment by ps2229** [comment]
I was able to solve the issue by creating a seperate kivymd folder which just datepicker files  and calling it seperately in python code, did work after this if you have any other issues you can ask me.

**Comment by cristianmejiaarias** [comment]
Thanks, it work for me.
