### ISSUE TITLE
[Enhancement]: Add ripple effect in Bottom navigation 

### ISSUE THREAD

**Issue by T-Dynamos** [kivymd/KivyMD#1240]
### Description of the Feature

https://user-images.githubusercontent.com/68729523/166693198-02e8fdcf-8b58-4b9b-8b19-91912dd574cd.mp4

We can see some ripple effect in Bottom Navigation

### Versions

* OS: Ubuntu 22.04
* Python: 3.8.9
* Kivy: 2.1.0
* KivyMD: master

**Comment by T-Dynamos** [comment]
Different animation in Play store

https://user-images.githubusercontent.com/68729523/169430123-96fd1e45-bd18-4298-9b1d-8066f73885c0.mp4

**Comment by HeaTTheatR** [comment]
@T-Dynamos No one uses sharp corners in design anymore.

**Comment by T-Dynamos** [comment]
> ### Description of the Feature
>  Screenrecorder-2022-05-03-09-40-50-342.mp4 
> We can see some ripple effect in Bottom Navigation
> 
> ### Versions
> * OS: Ubuntu 22.04
> * Python: 3.8.9
> * Kivy: 2.1.0
> * KivyMD: master



So , we are going to implement this?

**Comment by HeaTTheatR** [comment]
@T-Dynamos 
![Снимок экрана 2022-05-20 в 13 39 46](https://user-images.githubusercontent.com/16930280/169511224-b3cb715a-418c-4814-8c16-f83d3647ff8c.png)

**Comment by HeaTTheatR** [comment]
Added in 1.3.0 version
