### ISSUE TITLE
Some problems in the use of kivymd's mddatatable module

### ISSUE THREAD

**Issue by Jicming** [kivymd/KivyMD#1241]
### Description of the Bug

There was a problem when I used kivymd's mddatatable module. When my data is only a single line, only one column is displayed in the interface. I've read the source code, but I can't find where the problem happened。

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.screen import Screen
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp
from kivy.lang import Builder

kv_string = '''
BoxLayout:
    orientation: "vertical"
    BoxLayout:
        id:button_tab
        size_hint_y:None
        height: dp(30)

        MDFlatButton:
            text: "Hello <3"
            on_release:
                app.update_row_data()
    BoxLayout:
        id:body                    
'''
class DemoApp(MDApp):
    def build(self):
        screen = Screen()
        self.data_table = MDDataTable(pos_hint={'center_x': 0.5, 'center_y': 0.5},  #位置
                                 size_hint=(0.9, 0.6), #大小
                                 check=True,#是否显示复选口
                                 column_data=[      #添加列
                                     ("No.", dp(18)),  # dp 单元格宽度
                                     ("Food", dp(20)),
                                     ("Calories", dp(20))
                                 ],
                                 row_data=[   #添加行
                                     ("1", "Burger", "300"),
                                     # ("2", "Oats", "200"),
                                 ]
                                 )
        self.data_table.bind(on_row_press=self.on_row_press)
        self.data_table.bind(on_check_press=self.on_check_press)
        root = Builder.load_string(kv_string)
        root.ids.body.add_widget(self.data_table)
        screen.add_widget(root)
        return screen

    def on_row_press(self, instance_table, instance_row):
        print(instance_table, instance_row)


    def on_check_press(self, instance_table, current_row):
        print(instance_table, current_row)

DemoApp().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/21354647/167098100-bab6f5d4-538e-4bc0-8084-846931d259c4.png)

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@Jicming Use KivyMD library from master branch and Kivy >=2.1.0

**Comment by Jicming** [comment]
> @Jicming Use KivyMD library from master branch and Kivy >=2.1.0

Does kivymd have any requirements for the python version? I use Python 3.6.6

**Comment by HeaTTheatR** [comment]
@Jicming Why use Python 3.6.6 when there is already a Python version 3.10.2?

**Comment by Jicming** [comment]
> @Jicming Why use Python 3.6.6 when there is already a Python version 3.10.2?

Because I always feel that the older the version, the more stable it is, because there are many people using it. However, the latest version also exists, which only specifies the interpreter of Python to Python 3.6.6

**Comment by CapacitorDev** [comment]
> @Jicming Why use Python 3.6.6 when there is already a Python version 3.10.2?

some devices must run in the older python version for the compatible libs
