### ISSUE TITLE
MDDatePicker do not work in android 

### ISSUE THREAD

**Issue by cristianmejiaarias** [kivymd/KivyMD#1244]
### Description of the Bug

Your text

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@cristianmejiaarias Please follow the instructions (description, code, minimal example) when creating a new issue. Edit this issue, otherwise it will be closed.
