### ISSUE TITLE
MDTextField bug

### ISSUE THREAD

**Issue by GokalpA** [kivymd/KivyMD#1247]
### Description of the Bug

 When the text field(mode:rectangle)'s required value is set to True , clicking on it then clicking somewhere else makes the field red, indicating it's required without a problem. However, when you click on the text field again the hint text moves up as usual but the border of the text field does not adjust itself to make room for it. As a result, the hint text looks like the image below.

### Code and Logs
"""
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
Screen:
    MDTextField:
        mode: 'rectangle'
        hint_text: "Hint Text"
        helper_text: 'Helper Text'
        helper_text_mode: "on_focus"
        pos_hint: {"center_x":.5,"center_y":.7}
        size_hint_x: .5
        max_text_length: 5
        required: True
"""

class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)

MainApp().run()
"""

### Screenshots

![ss](https://user-images.githubusercontent.com/98057967/169291887-2f93bf0e-78d8-442f-80d6-d8f8b6ec71e8.png)

### Versions

* OS: ?
* Python: 3.10.2
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@GokalpA Version 0.104.2 is deprecated and not supported. Use KivyMD from the main branch.

**Comment by GokalpA** [comment]
Should i not install it using pip? (pip install kivymd)

**Comment by HeaTTheatR** [comment]
@GokalpA `pip install https://github.com/kivymd/KivyMD/archive/master.zip`
