### ISSUE TITLE
pyinstaller KivyMD 0.104.2 

### ISSUE THREAD

**Issue by cristianmejiaarias** [kivymd/KivyMD#1249]
when I'm running pyinstaller I get the following error

24078 WARNING: stderr:     for path_to_kv_file in Path(kivymd.uix_path).glob("**/*.kv"):
 AttributeError: module 'kivymd' has no attribute 'uix_path'
24078 WARNING: stderr: AttributeError: module 'kivymd' has no attribute 'uix_path'

### Versions

* OS: OSX 12.3.1
* Python: 3.9
* Kivy: 2.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@cristianmejiaarias Version `0.104.2` is deprecated and not supported. Use the master version of the `KivyMD` library - `pip install https://github.com/kivymd/KivyMD/archive/master.zip`
