### ISSUE TITLE
I cant install KivyMD, help please

### ISSUE THREAD

**Issue by marcelopilone** [kivymd/KivyMD#125]
#### 

when i try run the setup i see this error and kivy is installed, pyhons3 and 2 is installed, I do not know what else to do

### Console
(kivy_venv) marcelo@lala ~/KivyMD $ python3 ./setup.py install
  File "./setup.py", line 17
    raise ValueError(f"Unable to find version string in {version_file}.")
(kivy_venv) marcelo@lala ~/KivyMD $ python --version
Python 3.5.2
                                                                       ^
SyntaxError: invalid syntax

### Versions
* Python: 3.5
* Kivy: last
* KivyMD: last

Thanks

**Comment by ArtemSBulgakov** [comment]
@marcelopilone Try to install KivyMD via pip:
```bash
pip3 install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git@master
```

**Comment by HeaTTheatR** [comment]
@marcelopilone https://github.com/HeaTTheatR/KivyMD#how-to-install

**Comment by marcelopilone** [comment]
i run the command and i see this:
![Selección_011](https://user-images.githubusercontent.com/13138425/67340678-671ae180-f504-11e9-8bbd-b75c1ce941dd.png)
thanks

**Comment by HeaTTheatR** [comment]
```
python

>>> s = "123"
>>> print(f"{s}")
```

**Comment by marcelopilone** [comment]
thanks, how do i solve this?
![Selección_012](https://user-images.githubusercontent.com/13138425/67341021-2cfe0f80-f505-11e9-8014-a70f5036e4c8.png)

**Comment by HeaTTheatR** [comment]
Use `Python 3.6`

**Comment by HeaTTheatR** [comment]
`Python 3.5` does not support `f-strings`

**Comment by marcelopilone** [comment]
I'm going to try it and keep you up to date,If I solve it, I close the issue, thanks

**Comment by marcelopilone** [comment]
now i see this: 
![Selección_013](https://user-images.githubusercontent.com/13138425/67341837-09d45f80-f507-11e9-9759-4b332503ae9c.png)

**Comment by ArtemSBulgakov** [comment]
@marcelopilone Install Kivy

**Comment by ArtemSBulgakov** [comment]
@marcelopilone If Kivy already installed, do `pip3 install --upgrade setuptools`

**Comment by marcelopilone** [comment]
@Mountaino 
![Selección_014](https://user-images.githubusercontent.com/13138425/67341908-44d69300-f507-11e9-920b-6c4ea44ddbce.png)

**Comment by marcelopilone** [comment]
help with the last screen please
