### ISSUE TITLE
TypeError: 'type' object is not subscriptable in timepicker module

### ISSUE THREAD

**Issue by Adewole1** [kivymd/KivyMD#1250]
### Description of the Bug

After compiling my project for use on an android phone. I keep getting an error that, "TypeError: 'type' object is not subscriptable" from line 278, in TimeInput of timepicker module. It works fine on my PC, but after compiling with buildozer and installing on my android phone, the app crashes. I don't think its anything with the code because from the logcat it crashes on line 15, which is where I imported the TimePicker module. And also I'm using the module in more than one screen, so I don't know which part of my code to attach. Attached is a picture of the error from adb logcat, and also picture of one of the screens that I'm using the module while running on my PC. 

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""

class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
![Screenshot (165)](https://user-images.githubusercontent.com/63207113/169606220-cf63411b-7c68-40a7-8589-2f665a894844.png)
![Screenshot (166)](https://user-images.githubusercontent.com/63207113/169606256-86ae69fb-5d2a-492e-bf50-721275ce6857.png)
Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: windows 10 (WSL2 Ubuntu 20.04)
* Python: 3.9.0
* Kivy: 2.1.0
* KivyMD: 1.0.0.dev0

**Comment by HeaTTheatR** [comment]
@Adewole1 Make sure that the package for the mobile device uses the master branch of the KivyMD library.

**Comment by Adewole1** [comment]
Yes, that was what I specified in the buildozer spec file. But It's working now, I made 2 changes - I noticed that the hostpython version is not the same with the python3, so I specify the version to use. And then I made it one arch per build, rather than combining different archs to one build. I'll go back to check which one of them might be causing the error.

**Comment by T-Dynamos** [comment]
After the #1258 still the issue is there, @Adewole1 how you fixed it?
My error
```
2022-06-03 10:38:45.135 27559 27593 com.tdynamos.srapsapp I python : File "/home/tdynamos/SRAPS-App/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/srapsapp/armeabi-v7a/kivymd/uix/pickers/timepicker/timepicker.py", line 278, in TimeInput
2022-06-03 10:38:45.135 27559 27593 com.tdynamos.srapsapp I python : TypeError: 'type' object is not subscriptable
```

**Comment by Adewole1** [comment]
> After the #1258 still the issue is there, @Adewole1 how you fixed it? My error
> 
> ```
> 2022-06-03 10:38:45.135 27559 27593 com.tdynamos.srapsapp I python : File "/home/tdynamos/SRAPS-App/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/srapsapp/armeabi-v7a/kivymd/uix/pickers/timepicker/timepicker.py", line 278, in TimeInput
> 2022-06-03 10:38:45.135 27559 27593 com.tdynamos.srapsapp I python : TypeError: 'type' object is not subscriptable
> ```

I solved it by specifying the version of hostpython to use in my spec file. I found out the hostpython was downloading python 3.8 and changed it to 3.9 which was the python version I was using. Now, I don't know whether the error is due to the differences or something with that particular version.

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
