### ISSUE TITLE
KivyMD MDFileManager file extension filtering does not work when android.api = 30

### ISSUE THREAD

**Issue by janandaj** [kivymd/KivyMD#1252]
I'm building an android application using python kivy framework and I use kivyMD MDFileManager to filter JSON files.

`self.file_manager = MDFileManager(exit_manager=self.exit_manager,select_path=self.select_path)`

I use the extension property to filter JSON files
`ext = [".json", ".JSON"]`
`self.file_manager.ext = ext`
`self.file_manager.show(path)`

I use the buildozer spec to build the android APK and the api version is 27
`requirements = python3,kivy==2.1.0,numpy,kivymd==0.104.2`
`android.api = 27`
`android.ndk = 19c`

My application is working perfectly fine and I needed to upload the application to google play store. However the play store asks for api version 30 to upload new application. So I change the buildozer spec to support level 30.

`android.api = 30`
`android.ndk = 19c`

After that APK build was successful, installation was successful and application is running perfectly fine, However my file chooser no longer works and it just display empty when I select a folder which contains the JSON files. There are no any code changes and only change is in the `buildozer.spec` file where `android.api` is change from 27 to 30.

I used the kivymd master code branch as well but no success. 
`requirements = python3,kivy==2.1.0,opencv==4.5.5,numpy,https://github.com/kivymd/KivyMD/archive/master.zip`

Can someone please explain why MDFileManager is not working with android.api 30?
Is there any solution or workaround so I can upload my application to google play store? (need to build using api 30)

Thanks

**Comment by HeaTTheatR** [comment]
@janandaj Please edit your issue according to the current template.

**Comment by janandaj** [comment]
Please let me know what has to be done to comply with expected template. Is there any guideline? please share. Thank you.

**Comment by HeaTTheatR** [comment]
@janandaj 
![Снимок экрана 2022-05-23 в 13 41 56](https://user-images.githubusercontent.com/16930280/169802443-734c270c-45ce-4b2c-ae14-e9fc272c6b86.png)

**Comment by janandaj** [comment]
@HeaTTheatR, Thanks for the reply. I updated the issue. Can you please help me on this.

**Comment by HeaTTheatR** [comment]
@janandaj Please edit your issue according to the current template.

**Comment by Neizvestnyj** [comment]
You need this https://github.com/kivy/python-for-android/pull/2431/commits/30a28d5a71fcca4c369d3f9ae85539515d413a6e

**Comment by janandaj** [comment]
> You need this [kivy/python-for-android@30a28d5](https://github.com/kivy/python-for-android/commit/30a28d5a71fcca4c369d3f9ae85539515d413a6e)

@Neizvestnyj Thank you very much. I tried this approach. It works perfectly when API is 29. However it is also not working when the API is 30. Now google requests API to be 30 to upload new apps to play store. So this is not going to work.

**Comment by Neizvestnyj** [comment]
> > You need this [kivy/python-for-android@30a28d5](https://github.com/kivy/python-for-android/commit/30a28d5a71fcca4c369d3f9ae85539515d413a6e)
> 
> @Neizvestnyj Thank you very much. I tried this approach. It works perfectly when API is 29. However it is also not working when the API is 30. Now google requests API to be 30 to upload new apps to play store. So this is not going to work.

Use api 32
