### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Jicming** [kivymd/KivyMD#1256]
### Description of the Feature

Now kivymd can't speak Chinese, such as mdtextinput,mdlabel etc    When you input Chinese on a written app, it's garbled

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
This issue has nothing to do with the KivyMD library.

**Comment by Jicming** [comment]
Can you develop a function that supports Chinese

**Comment by Jicming** [comment]
Do I need to request Kivy project for Chinese support
