### ISSUE TITLE
Support drives in MDFileManager (e.g. on Windows)

### ISSUE THREAD

**Issue by pakal** [kivymd/KivyMD#1262]
For now, MDFileManager expects a single file tree, so unfortunately on Windows we cnnot access other drives like D:, F: etc.

It'd be awesome if, on such OSes, at the root of the MDFileManager tree, we could have a list of the disk drives available.

**Comment by kulothunganug** [comment]
Use `.show_disks()`.

This function has implemented in #1007 by @Neizvestnyj but it is not documented.

**Comment by Neizvestnyj** [comment]
> For now, MDFileManager expects a single file tree, so unfortunately on Windows we cnnot access other drives like D:, F: etc.
> 
> It'd be awesome if, on such OSes, at the root of the MDFileManager tree, we could have a list of the disk drives available.

[Read more carefully](https://kivymd.readthedocs.io/en/latest/components/filemanager/)
![image](https://user-images.githubusercontent.com/40869738/172146824-60946319-829d-40c9-8d02-299bb92be93a.png)

**Comment by pakal** [comment]
Thanks, I missed that, i'll have to test it on iOS specifically so it'll be the occasion to check
