### ISSUE TITLE
Some controls of KIVYMD do not support Chinese, but some controls support Chinese

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMD#1267]
There are two controls in the routine. After the font is introduced, one displays garbled characters and the other displays normally.

How can I support it correctly? Many thanks!
[test.zip](https://github.com/kivymd/KivyMD/files/8956496/test.zip)

**Comment by HeaTTheatR** [comment]
https://stackoverflow.com/questions/63462947/using-arabic-reshaper-and-bidi-algorithm-in-kivymd

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

The problem described in your post is exactly the same as mine, but I ended up with the same situation as the text and the same situation as his picture describes. The last part of the control successfully displayed Chinese garbled characters.
--------------------------------------
![This is an image](https://i.stack.imgur.com/yrSls.png)

Unfortunately, As you see in the image below, the font has changed only in Label and in MDToolbar title or also MDTextField (helper_text and hint_text), Again, it has not changed

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/textfield/#kivymd.uix.textfield.textfield.MDTextField.font_name_helper_text

**Comment by 471657** [comment]
@HeaTTheatR 
the problem still exists. MDLabel can be displayed normally, but 'MDBottomNavigationItem' is not.

![image](https://user-images.githubusercontent.com/43966525/175521008-baf488e1-b9cc-4150-8014-9a4091e57156.png)

**Comment by 471657** [comment]
@HeaTTheatR 

I think my question should change:

        MDBottomNavigationItem:
            name:'shield-home'
            text: '测试'

How to display Chinese normally in TEXT. MDLabel can be displayed normally

The PY file in the source code I uploaded above is used to globally specify Chinese fonts.

**Comment by ChinaGodzilla** [comment]
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.resources import resource_add_path
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            name:'shield-home'
            text: 'MDBottomNavigationItem-哈'

            icon:'shield-home'
            #YourContent:

    MDLabel:

        text:'MDLabel-哈'

    MDChip:
        text: 'MDLabel-哈'
''')


class Test(MDApp):
    def build(self):
        resource_add_path('./fonts')  # 全局申明载入字体
        LabelBase.register(DEFAULT_FONT, 'font.ttf')
        return Factory.ExampleBanner()


Test().run()

------------------------------------------
A Chinese character is displayed at the end of the three controls at the same time, and some controls display garbled characters.
------------------------------------------



![image](https://user-images.githubusercontent.com/43966525/175527383-635f6433-ef99-4566-9c48-21571446d9c3.png)

**Comment by HeaTTheatR** [comment]
@471657 https://stackoverflow.com/questions/63462947/using-arabic-reshaper-and-bidi-algorithm-in-kivymd

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  I read this solution when you replied for the first time, but at the end of the post, he is in the same situation as me, some controls display the language, and some controls display garbled characters

**Comment by HeaTTheatR** [comment]
@471657 Attach a minimal code example (50-100 lines) which reproduces this.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

from kivy.lang import Builder
from kivy.factory import Factory
from kivy.resources import resource_add_path
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivymd.app import MDApp

Builder.load_string('''
[ExampleBanner@Screen](mailto:ExampleBanner@Screen)

MDBottomNavigation:
    MDBottomNavigationItem:
        name:'shield-home'
        text: 'MDBottomNavigationItem-哈'

        icon:'shield-home'
        #YourContent:

MDLabel:

    text:'MDLabel-哈'

MDChip:
    text: 'MDLabel-哈'
''')

class Test(MDApp):
def build(self):
_add_path('/fonts') #resourceT申明载入字体
LabelBase.register(DEFAUL_FONT, 'font.ttf')
return Factory.ExampleBan


[font.zip](https://github.com/kivymd/KivyMD/files/8976391/font.zip)

**Comment by HeaTTheatR** [comment]
@471657 Please edit your code so that it can be read.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  Thanks for the help, I didn't quite understand what to edit the code.

Is there anything wrong with the code I posted?

**Comment by 471657** [comment]
@HeaTTheatR 

from kivy.lang import Builder
from kivy.factory import Factory
from kivy.resources import resource_add_path
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            text: '哈'

''')


class Test(MDApp):
    def build(self):
        resource_add_path('./fonts')  # 全局申明载入字体
        LabelBase.register(DEFAULT_FONT, 'font.ttf')
        return Factory.ExampleBanner()


Test().run()

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

from kivy.lang import Builder
from kivy.factory import Factory
from kivy.resources import resource_add_path
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            text: '哈'

''')


class Test(MDApp):
    def build(self):
        resource_add_path('./fonts')  # 全局申明载入字体
        LabelBase.register(DEFAULT_FONT, 'font.ttf')
        return Factory.ExampleBanner()


Test().run()

**Comment by HeaTTheatR** [comment]
@471657 Do you think it's possible to copy and run your code?

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 
[CODE.zip](https://github.com/kivymd/KivyMD/files/8977210/CODE.zip)

**Comment by HeaTTheatR** [comment]
@471657 No need to attach files. Write a minimal sample code that can be copied and run.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  



```
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.resources import resource_add_path
from kivy.core.text import LabelBase, DEFAULT_FONT
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            text: 'MDBottomNavigationItem-哈'

    MDLabel:

        text:'MDLabel-哈'

    MDChip:
        text: 'MDLabel-哈'
''')


class Test(MDApp):
    def build(self):
        resource_add_path('./fonts')  # 全局申明载入字体
        LabelBase.register(DEFAULT_FONT, 'font.ttf')
        return Factory.ExampleBanner()


Test().run()

```

[font.zip](https://github.com/kivymd/KivyMD/files/8976391/font.zip)

**Comment by ChinaGodzilla** [comment]
It should work, with the font attached. Sorry for wasting your time. I'm new to GITHUB and don't know the rules for posting code.

**Comment by HeaTTheatR** [comment]
@471657 
```python
import kivy.app
import kivy.uix.label
import arabic_reshaper
import bidi.algorithm

class TestApp(kivy.app.App):
 def build(self):
    
    bidi_text = bidi.algorithm.get_display(arabic_reshaper.reshape("میلاد"))
    return kivy.uix.label.Label(text=bidi_text, font_name="arial" , font_size="90sp") 

testApp = TestApp()
testApp.run()
```

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Using your example to test my garbled controls is also garbled

```
from kivymd.app import MDApp
from kivymd.uix.toolbar import MDToolbar

import arabic_reshaper
import bidi.algorithm


class TestApp(MDApp):
    def build(self):
        bidi_text = bidi.algorithm.get_display(arabic_reshaper.reshape("میلاد"))
        return MDToolbar(title=bidi_text)


testApp = TestApp()
testApp.run()

```

**Comment by HeaTTheatR** [comment]
@471657 First of all, it works. And secondly, it has nothing to do with the KivyMD library.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

deep problem i don't understand but i want to know how to solve it
This garbled problem.


![image](https://user-images.githubusercontent.com/43966525/175616260-3692454a-1d63-40d5-9afe-b5bf496a413f.png)

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

This issue blocked me from using the MD widget, thanks a lot.

**Comment by HeaTTheatR** [comment]
@471657 For each screenshot of the problem, there should be a minimum code that reproduces this problem.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

```
from kivymd.app import MDApp
from kivymd.uix.toolbar import MDToolbar

import arabic_reshaper
import bidi.algorithm


class TestApp(MDApp):
    def build(self):
        bidi_text = bidi.algorithm.get_display(arabic_reshaper.reshape("میلاد"))
        return MDToolbar(title=bidi_text)


testApp = TestApp()
testApp.run()
```
![image](https://user-images.githubusercontent.com/43966525/175640668-767c30aa-8be1-4f1d-87f4-2f81a1151d15.png)

**Comment by HeaTTheatR** [comment]
@471657 
```python
from kivymd.app import MDApp
from kivymd.uix.toolbar import MDToolbar

import arabic_reshaper
import bidi.algorithm


class TestApp(MDApp):
    def build(self):
        bidi_text = bidi.algorithm.get_display(arabic_reshaper.reshape("میلاد"))
        return MDToolbar(title=f"[font=DroidNaskh-Regular.ttf]{bidi_text}[/font]")


testApp = TestApp()
testApp.run()
```

**Comment by 471657** [comment]
@HeaTTheatR 

你解决了我的疑惑非常感谢！

**Comment by HeaTTheatR** [comment]
@471657 ???

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 
thank you very much, this solved my problem

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Hi, I found that executing the method you provided last night in the same widget produces different results and some controls are still gibberish.

![image](https://user-images.githubusercontent.com/43966525/175760045-f70ad5c0-ae88-4cf9-b6c9-c4cfdcb70aa0.png)


```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            #name:'shield-home'
            text:'[font=font.ttf]哈哈[/font]'     #same assignment method
            #icon:'shield-home'

    MDToolbar:
        title:'[font=font.ttf]哈哈[/font]'        #same assignment method
        pos_hint:{'x':.3,'y':.3}
''')


class Test(MDApp):
    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

[font.zip](https://github.com/kivymd/KivyMD/files/8976391/font.zip)

**Comment by HeaTTheatR** [comment]
@471657 https://github.com/kivymd/KivyMD/issues/1267#issuecomment-1165840595

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

I'm using the solution you provided in this chapter, the code below translates to the same framework.

```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp
import arabic_reshaper
import bidi.algorithm


Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            #name:'shield-home'
            text:f"[font=font.ttf]{app.res3}[/font]"     #same assignment method
            #icon:'shield-home'

    MDToolbar:
        title:f"[font=font.ttf]{app.res3}[/font]"       #same assignment method
        pos_hint:{'x':.3,'y':.3}
''')


class Test(MDApp):
    text3 = ('急啊急啊')
    reshaped_texts3 = arabic_reshaper.reshape(text3)
    res3 = bidi.algorithm.get_display(reshaped_texts3)

    def build(self):
        return Factory.ExampleBanner()


Test().run()

```

![image](https://user-images.githubusercontent.com/43966525/175760045-f70ad5c0-ae88-4cf9-b6c9-c4cfdcb70aa0.png)


[font.zip](https://github.com/kivymd/KivyMD/files/8976391/font.zip)

**Comment by HeaTTheatR** [comment]
@471657 Arabic and Chinese need a different font. This has nothing to do with the KivyMD library

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

I'm afraid not so. Arabic fonts are also garbled

![image](https://user-images.githubusercontent.com/43966525/175761750-dbdb5a26-a290-45bf-92a9-6f11098bfc6e.png)



```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp
import arabic_reshaper
import bidi.algorithm


Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            #name:'shield-home'
            text:f"[font=Arial.ttf]{app.res3}[/font]"     #same assignment method
            #icon:'shield-home'

    MDToolbar:
        title:f"[font=Arial.ttf]{app.res3}[/font]"       #same assignment method
        pos_hint:{'x':.3,'y':.3}
''')


class Test(MDApp):
    text3 = ('میلاد')
    reshaped_texts3 = arabic_reshaper.reshape(text3)
    res3 = bidi.algorithm.get_display(reshaped_texts3)

    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

[Arial.zip](https://github.com/kivymd/KivyMD/files/8984043/Arial.zip)

**Comment by HeaTTheatR** [comment]
@471657 https://kivymd.readthedocs.io/en/latest/components/bottomnavigation/#kivymd.uix.bottomnavigation.bottomnavigation.MDBottomNavigation.font_name

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

thank you for your reply. After using the method you provided, the garbled characters are still displayed. I just want to know how to display the letters in the routine normally in the widget without garbled characters.

![image](https://user-images.githubusercontent.com/43966525/175762945-7d0fa4ba-4f12-4a5b-8d77-c33d7383ff43.png)


```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp
import arabic_reshaper
import bidi.algorithm


Builder.load_string('''
<ExampleBanner@Screen>

    MDBottomNavigation:
        MDBottomNavigationItem:
            #name:'shield-home'
            font_name: "Arial.ttf"
            text:app.res3

''')


class Test(MDApp):
    text3 = ('میلاد')
    reshaped_texts3 = arabic_reshaper.reshape(text3)
    res3 = bidi.algorithm.get_display(reshaped_texts3)

    def build(self):
        return Factory.ExampleBanner()


Test().run()
```


[Arial.zip](https://github.com/kivymd/KivyMD/files/8984043/Arial.zip)

**Comment by HeaTTheatR** [comment]
@471657 
```
    MDBottomNavigation:
        font_name: "DroidNaskh-Regular.ttf"
```

Please be careful! I gave you a link to the documentation.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR The error is written under the MDBottomNavigationItem layout. My fault. solved thanks for your time

**Comment by yeyuchen198** [comment]
MDTextField setting font_name does not take effect, how to solve it?
