### ISSUE TITLE
Can't increase the font_size of MDLabel

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#1268]
I can't increase the font_size of `MDLabel`. I checked the kivymd source code of `MDLabel` and discovered that the `update_font_style` method is actually the cause

```python
    def update_font_style(self, instance_label, font_style: str) -> None:
        if self.check_font_styles() is True:
            font_info = self.theme_cls.font_styles[self.font_style]
            self.font_name = font_info[0]
            self.font_size = sp(font_info[1])
            if font_info[2] and self.can_capitalize:
                self._capitalizing = True
            else:
                self._capitalizing = False
```

the line that contains ` self.font_size = sp(font_info[1])` is the actual cause, whenever I comment it out the my the MDLabel font increases to the actual size I added in the `font_size` attribute

**Comment by HeaTTheatR** [comment]
@kengoon 
```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel


class MainApp(MDApp):
    def build(self):
        label = MDLabel(text="Hello, World", halign="center")
        label.font_size = "32sp"
        return label


MainApp().run()
```

**Comment by kengoon** [comment]
@HeaTTheatR using it on kv code does not work

**Comment by HeaTTheatR** [comment]
@kengoon 
```python
from kivy.lang import Builder
from kivymd.app import MDApp


class MainApp(MDApp):
    def build(self):
        return Builder.load_string(
"""
MDLabel:
    text: "Hello, World"
    halign: "center"
    font_size: "32sp"
"""
        )


MainApp().run()
```
![Снимок экрана 2022-06-24 в 11 30 30](https://user-images.githubusercontent.com/16930280/175496564-e3b95110-0041-4a10-b355-1bc4a4c4bc88.png)

**Comment by kengoon** [comment]
@HeaTTheatR

> @kengoon
> 
> ```python
> from kivymd.app import MDApp
> from kivymd.uix.label import MDLabel
> 
> 
> class MainApp(MDApp):
>     def build(self):
>         label = MDLabel(text="Hello, World", halign="center")
>         label.font_size = "32sp"
>         return label
> 
> 
> MainApp().run()
> ```

this method is working. I was doing something like this `MDLabel(font_size="100sp", text="hello")`. so since `update_font_style` is overriding the initial font_size being set by the user during the Object initialization, the user has to instantiate `MDLabel` first before setting the font_size.

**Comment by hi-one-gg** [comment]
@kengoon, @HeaTTheatR
It's not working.

**Comment by arxjei** [comment]
use Label as alternative instead of MDLabel

**Comment by HeaTTheatR** [comment]
```
MDLabel:
    theme_font_size: "Custom"
    font_size: "56sp"
```
