### ISSUE TITLE
TypeError: 'kivy.properties.AliasProperty' object is not iterable

### ISSUE THREAD

**Issue by marcelopilone** [kivymd/KivyMD#127]
#### Description of the Bug

 TypeError: 'kivy.properties.AliasProperty' object is not iterable
   File "/home/marcelo/kivy_venv/lib/python3.6/site-packages/kivy/lang/builder.py", line 921, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__

### Code and Logs

```python
import sys
from kivy.app import App
from kivymd.theming import ThemeManager

class MainApp(App):
	theme_cls = ThemeManager

MainApp().run()


kv = """
NavigationLayout:
	MDNavigationDrawer:
		NavigationDrawerIconButton:
			text: "pantalla 1"
			on_release: 
				screen_manager.current = "pantalla1"
		NavigationDrawerIconButton:
			text: "pantalla 2"
			on_release: 
				screen_manager.current = "pantalla2"

	ScreenManager:
		id: screen_manager
		Screen:
			name: "pantalla1"
			MDLabel: 
				text: "pantalla 1"
		Screen:
			name: "pantalla2"
			MDLabel: 
				text: "pantalla 1"
"""

```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Linux
* Python: 3.6
* Kivy: Last
* KivyMD: Last

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer
