### ISSUE TITLE
‘MDDataTable’ Running the .KV to create a widget reports an error

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMD#1270]
@HeaTTheatR

hello i see the py code creation process in the routine works then i declare the widget in the .kv file i get an error

![image](https://user-images.githubusercontent.com/43966525/175774419-fd6537d2-67fb-4bca-b71e-fcd37848f7f8.png)

```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>
    MDToolbar:
        title:'hello' 
        pos_hint:{'x':.3,'y':.3}
    
    
    
    MDDataTable:
        pos_hint:{"x": 0.5, "y": 0.5}
        size_hint:(0.9, 0.6)
        use_pagination:False
        column_data:[("No.", dp(30)),("Column 1", dp(40)),("Column 2", dp(40)),("Column 3", dp(40))]
        row_data:[("0", "1", "2", "3")]
        
''')


class Test(MDApp):
    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.

**Comment by 471657** [comment]
@HeaTTheatR 
Thanks for your time, this widget can't be created in kv file only by py code right?

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Hi, thanks for taking the time to answer, how to download the corresponding side branch version so that I can use it in .Kv to create 'MDDataTable'.

![image](https://user-images.githubusercontent.com/43966525/175800989-26e6262c-3a5f-4547-aef7-ff93e19b6da6.png)



-----------------------------------------------------------
![image](https://user-images.githubusercontent.com/43966525/175801647-37a48c42-affc-470f-97f2-5b2c9d517f24.png)



```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>
    MDToolbar:
        title:'hello' 
        pos_hint:{'x':.3,'y':.3}
    
    
    
    MDDataTable:
        pos_hint:{"x": 0.5, "y": 0.5}
        size_hint:(0.9, 0.6)
        
''')


class Test(MDApp):
    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

**Comment by HeaTTheatR** [comment]
@471657 Use KivyMD library from master branch.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Hi I don't know how to use the KivyMD library from the master branch.

I searched on github and couldn't find anything.


How to find branches of KIVYMD? I saw the installation method in the introduction.

pip install https://github.com/kivymd/KivyMD/archive/master.zip

But I can't find any branch project ，thanks！

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR

I have the developer version installed now, is this the kivymd branch you describe? ?
The result is the same error.
 
![image](https://user-images.githubusercontent.com/43966525/175811097-c4c46b8b-ee9f-434e-9687-6c701489b6d3.png)

```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>
    MDToolbar:
        title:'hello' 
        pos_hint:{'x':.3,'y':.3}
    
    
    
    MDDataTable:

        
''')


class Test(MDApp):
    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

![image](https://user-images.githubusercontent.com/43966525/175811173-7e64413d-dbf6-4de4-96d5-a9a58c3138ba.png)

**Comment by HeaTTheatR** [comment]
@471657 You are not using the master branch of the library.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thanks a lot for your reply, I would love to install a fork of the library. How to install

**Comment by HeaTTheatR** [comment]
@471657 `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Hello, I installed it through this command, please see the screenshot.

Successfully installed kivymd-1.0.0.dev0

![image](https://user-images.githubusercontent.com/43966525/175817241-f94c0af4-4784-4dbe-a8dc-adb7bcd941ed.png)

still running error

![image](https://user-images.githubusercontent.com/43966525/175817280-24c097f6-d52d-4419-94b9-5517ed2d5c44.png)

**Comment by HeaTTheatR** [comment]
@471657  You are not using the master branch of the library.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

as you describe

pip install https://github.com/kivymd/KivyMD/archive/master.zip

After installation my version is 'kivymd-1.0.0.dev0', you said the version is wrong, I really don't understand.

**Comment by HeaTTheatR** [comment]
@471657 Solve problems with your virtual environments.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

ok thanks i checked my environment

**Comment by 471657** [comment]
@HeaTTheatR 

I used CONDA to create a new PYTHON3.9 environment, and then only installed KIVY + pip install https://github.com/kivymd/KivyMD/archive/master.zip, the version is still 1.0.0.dev.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

I used CONDA to create a new PYTHON3.9 environment, and then only installed KIVY + pip install https://github.com/kivymd/KivyMD/archive/master.zip, the version is still 1.0.0.dev.

What do I do now.

Is there any other way to install the forked version you mentioned?

**Comment by HeaTTheatR** [comment]
@471657  Solve problems with your virtual environments.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR do you mean it could be caused by my CONDA virtual environment?

**Comment by HeaTTheatR** [comment]
@471657 I have no idea about your virtual environments.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  thank you for your reply. I immediately use another physical computer to install PYTHON test directly without using plug-ins such as CONDA
thank you for your reply. I immediately use another physical computer to install PYTHON test directly without using plug-ins such as CONDA

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  By the way, what should be the version number if the version of the install branch is correct.

**Comment by HeaTTheatR** [comment]
@471657 `1.0.0.dev0`

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  

My God, my conda newly installed PYTHON3.9, the current KIVYMD version is 1.0.0.dev0 .

![image](https://user-images.githubusercontent.com/43966525/175885729-09932e78-42f6-4c25-8fcf-33e1331024a8.png)

```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string('''
<ExampleBanner@Screen>
    MDToolbar:
        title:'hello' 
        pos_hint:{'x':.3,'y':.3}
    
    
    
    MDDataTable:


        
''')


class Test(MDApp):
    def build(self):
        return Factory.ExampleBanner()


Test().run()
```

![image](https://user-images.githubusercontent.com/43966525/175885847-50407750-ac2d-4f2f-802a-412759f74e00.png)

**Comment by HeaTTheatR** [comment]
@471657 You are not using the KivyMD library from master branch. It doesn't matter at all what you have in your pip list. Solve problems with your virtual environments.

**Comment by HeaTTheatR** [comment]
@471657 And read the documentation - https://kivymd.readthedocs.io/en/latest/components/datatables / Does the documentation say that the MDDataTable widget can be used in KV Language?

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  I just want to know if datatables can be created in KV files.

**Comment by HeaTTheatR** [comment]
@471657 No

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thanks for your reply, every routine I upload tries to create 'MDDataTable' in .kv file, I see your response is very positive, I always thought it was possible to create 'MDDataTable' in .kv. . . . .

**Comment by T-Dynamos** [comment]
```
pip3 uninstall kivymd
pip3 cache purge
pip3 install https://github.com/kivymd/KivyMD/archive/master.zip
```
Try this

**Comment by T-Dynamos** [comment]
His code will not work and raise a error saying 
```
ValueError: KivyMD: App object must be initialized before loading root widget. See https://github.com/kivymd/KivyMD/wiki/Modules-Material-App#exceptions
```

**Comment by ChinaGodzilla** [comment]
> His code will not work and raise a error saying 
> ```
> ValueError: KivyMD: App object must be initialized before loading root widget. See https://github.com/kivymd/KivyMD/wiki/Modules-Material-App#exceptions
> ```

thanks for your time!

**Comment by T-Dynamos** [comment]
After initialising the screen use `on_start` function and add `Clock. schedule_once(add_table,0.1)` , `add_table` will be a function that adds `MDDataTable`

**Comment by ChinaGodzilla** [comment]
> 初始化屏幕使用`on_start`函数并添加`Clock. schedule_once(add_table,0.1)`后，`add_table`将添加一个函数`MDDataTable`

@T-Dynamos  You're talking about creating a step in a .PY file, not a .KV file, right? See HeaTTheatR reply This widget cannot be created in a .kv file.
