### ISSUE TITLE
MDTextField

### ISSUE THREAD

**Issue by Prakash1124** [kivymd/KivyMD#1278]
I do not know if it is a bug or intended design/limitation.

![image](https://user-images.githubusercontent.com/108631726/177056344-5ae6054c-3916-4cd3-a70b-dc3c4ee4d916.png)

When I used MDTextField with size_hint_x as 1 the element spanned to whole width. Same as the button at the bottom.

But when I used MDTextField with mode='rectangle' and size_hint_x as 1 the element is overflowing.

This might create confusion to the designer as he will struggle with the perfect width, for everything to be inline.

The material design manual says that if we select 'outlined' textbox the width should remain same:
https://material.io/components/text-fields#input-types.

**Comment by HeaTTheatR** [comment]
@Prakash1124 Yes it looks like a bug.

**Comment by Prakash1124** [comment]
![image](https://user-images.githubusercontent.com/108631726/177057004-33a1f9d3-c984-4821-b8e0-efca14911a95.png)

@HeaTTheatR  this is the case with different MDTextField.
