### ISSUE TITLE
'MDList' - How to set the character spacing of TwoLineListItem?

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMD#1279]
As shown, a 2-line list is displayed in the routine. How to set character spacing between A and B? I think the default values are pretty close Thanks a lot!

```
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivymd.uix.list import OneLineListItem

KV = '''
Click:
    ScrollView:

        MDList:
            id: container
            TwoLineListItem:
                text:'[color=ff0000]a[/color]'
                secondary_text: "b"
                on_release:root.Click_button(self)

            
'''
class Click(Screen):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)  #申明继承

    def Click_button(self,button):
        print(button.text)




class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)




Test().run()
```

**Comment by HeaTTheatR** [comment]
@471657 
`instance_list_item.ids._text_container.spacing`

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Hi, based on your tip, I searched but still don't know what to do. Expand 2 lines of text spacing for 'TwoLineListItem'.

'spacing' can only adjust the distance between 2 lists in the KV file.

![image](https://user-images.githubusercontent.com/43966525/177153007-70114ba8-9dd4-4625-8d20-d25e08519168.png)

```
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivymd.uix.list import OneLineListItem

KV = '''
Click:
    ScrollView:

        MDList:
            id: container
            TwoLineListItem:
                text:'Hello [color=ff0000]a[/color]'
                secondary_text: "b"
                on_release:root.Click_button(self)

            
'''
class Click(Screen):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)  #申明继承

    def Click_button(self,button):
        print(button.text)




class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)




Test().run()
```

**Comment by HeaTTheatR** [comment]
@471657 I don't understand your questions. I clearly answered your first question.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Sorry, my first question was wrong. Excuse me, "TwoLineListItem", as shown in the figure below, how to adjust the value of the gap (arrow position) between the "helloA" and "B" texts. I wish the gap was bigger.

![image](https://user-images.githubusercontent.com/43966525/177153007-70114ba8-9dd4-4625-8d20-d25e08519168.png)

```
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivymd.uix.list import OneLineListItem

KV = '''
Click:
    ScrollView:

        MDList:
            id: container
            TwoLineListItem:
                text:'Hello [color=ff0000]a[/color]'
                secondary_text: "b"
                on_release:root.Click_button(self)

            
'''
class Click(Screen):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)  #申明继承

    def Click_button(self,button):
        print(button.text)




class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)




Test().run()
```

**Comment by HeaTTheatR** [comment]
@471657 I've already answered you. Be careful.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  

instance_list_item._text_container.spacing:9

I get an error when I reference this project in KV.

**Comment by HeaTTheatR** [comment]
@471657 

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    TwoLineListItem:
        text: "Two-line item"
        secondary_text: "This is a multi-line label where you can"
        on_size: self.ids._text_container.spacing = "4dp"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thanks for your answer. Sorry, I am a beginner in programming. I use KIVY & KIVYMD in China. There is almost no ecology here. Apart from the official documentation, there is almost no other information in Chinese, so almost every question I have is stupid.

**Comment by HeaTTheatR** [comment]
@471657 Welcome!

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thank you very much, you have 'self.ids._text_container.spacing' in the provided method

The IDS '_text_container' is not the ID defined in my program. Where do these IDs come from, as a novice, I can't understand it at all.

**Comment by HeaTTheatR** [comment]
@471657 https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/list/list.kv#L42

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thank you so much! ! !

It turned out to be the source code of the widget! ! !

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/list/list.kv

Hello, I found a strange phenomenon. I searched for 'OneLineListItem' , 'TwoLineListItem' , 'ThreeLineListItem ' in the source code of the list. There are no three layouts in the source code, but 'OneLineAvatarListItem' exists.

**Comment by HeaTTheatR** [comment]
@471657 
https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/list/list.py#L780
https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/list/list.py#L793

[...]

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR THANSK

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Chinese information is extremely scarce

![image](https://user-images.githubusercontent.com/43966525/177320180-a8c35b99-b5bd-43b8-b55e-546716e54aa9.png)


Shocked, with your guidance, I now understand viewing widget source code and then coding. There is one other incident that confuses me. Is there a compendium or list of KIVY events to learn about all KIVY events?

For example: "on_size", "on_release", etc.

**Comment by HeaTTheatR** [comment]
@471657 Almost all properties of Kivy widgets have on methods: `size` - `on_size`, `text` - `on_text` and so on...

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

Thanks for the reply Yes, I currently know through the KIVY docs that there are these main events, I mean is there such a collection? ?

Explained list of all common events, which will be very helpful for newbies.

I look at the official documentation of KIVY and it seems that they do not have a similar explanation.

**Comment by HeaTTheatR** [comment]
@471657 https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L298

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR  

THANKS！

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR 

I think if the 'KivyMDBuilder' developed by you can be released, it may cause an explosion of users in China.

If you can sell this product well in China, I believe this project can make countless money directly. PYTHON has a large number of users, but KIVY is really not popular in China, why is it because Chinese people prefer visual design, especially in the scene of PYTHON, most of the staff are non-professional programmers, they think that if pure code writes UI time cost is too long.

If your product is willing to expand in China, you can also cooperate with me. Although China is a country with weak copyright awareness, I also have a complete and legal Internet company in China, and I can also hire a professional legal team for copyright protection. The population market is the best in the world.
