### ISSUE TITLE
`opposite_colors` works incorrect on macos

### ISSUE THREAD

**Issue by Neizvestnyj** [kivymd/KivyMD#1281]
```py
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDIconButton:
        icon: "language-python"
        pos_hint: {"center_x": .5, "center_y": .5}
        opposite_colors: True
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```
![Screenshot 2022-07-08 at 15 49 18](https://user-images.githubusercontent.com/40869738/177995600-12983a10-7be3-4271-bef0-1c7339ca7398.png)

**Comment by HeaTTheatR** [comment]
@Neizvestnyj Everything works correctly on my computer.

**Comment by HeaTTheatR** [comment]
@Neizvestnyj I just noticed that the icon color when using `opposite_colors: True` is different from the current background color.

**Comment by HeaTTheatR** [comment]
The `opposite_color` property is used to contrast the label color: `opposite_color` sets the text color to the opposite of the default label color. Therefore, it is not correct to use the `opposite_color` property for labels on a white background. So I don't see any bug in this.
