### ISSUE TITLE
when pillow added in requriements, it happend issue

### ISSUE THREAD

**Issue by jbc0708** [kivymd/KivyMD#1282]
### Description of the Bug

in buildozer.spec, i add python3,kivy,https://github.com/kivymd/KivyMD/archive/maseter.zip in requirements.
and after buildozer run, it show me "No module Named 'PIL'" issue.
so i add pillow in requirements. and it show other issue.

 ----------------report--------------------------
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
# Search for Git (git)
#  -> found at /opt/homebrew/Cellar/git/2.37.0/bin/git
# Search for Cython (cython)
#  -> found at /Users/bcjung/Project/convert_android/env/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /Users/bcjung/Project/convert_android/.buildozer/android/platform/python-for-android
https://github.com/misl6/python-for-android.git
# Run 'git branch -vv'
# Cwd /Users/bcjung/Project/convert_android/.buildozer/android/platform/python-for-android
* fix/build-platform-on-m1 29d05325 [origin/fix/build-platform-on-m1] Uses pyjnius master
# Run '/Users/bcjung/Project/convert_android/env/bin/python3 -m pip install -q  \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0\' \'toml\''
# Cwd None
# Apache ANT found at /Users/bcjung/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/bcjung/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 23b
# Android NDK found at /Users/bcjung/.buildozer/android/platform/android-ndk-r24
# Read available permissions from api-versions.xml
# Run '/Users/bcjung/Project/convert_android/env/bin/python3 -m pythonforandroid.toolchain aab -h --color=always --storage-dir="/Users/bcjung/Project/convert_android/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug'
# Cwd /Users/bcjung/Project/convert_android/.buildozer/android/platform/python-for-android
# Check application requirements
# Compile platform
# Run '/Users/bcjung/Project/convert_android/env/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=hostpython3==3.9.9,python3==3.9.9,kivy,kivymd,pillow --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/bcjung/Project/convert_android/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug'
# Cwd /Users/bcjung/Project/convert_android/.buildozer/android/platform/python-for-android
Download failed: <urlopen error [Errno 60] Operation timed out>; retrying in 1 second(s)...Download failed: <urlopen error [Errno 60] Operation timed out>; retrying in 2 second(s)...Download failed: <urlopen error [Errno 60] Operation timed out>; retrying in 4 second(s)...Download failed: <urlopen error [Errno 60] Operation timed out>; retrying in 8 second(s)...# Command failed: /Users/bcjung/Project/convert_android/env/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=hostpython3==3.9.9,python3==3.9.9,kivy,kivymd,pillow --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/bcjung/Project/convert_android/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     __CFBundleIdentifier = 'com.apple.Terminal'
#     TMPDIR = '/var/folders/jy/yh6w1_113h76wx3bmnqcmhg80000gn/T/'
#     XPC_FLAGS = '0x0'
#     LaunchInstanceID = '2CD7A150-39B6-4276-90AB-870F1299DF7A'
#     TERM = 'xterm-256color'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.vwfvPCrIpp/Listeners'
#     SECURITYSESSIONID = '186b2'
#     XPC_SERVICE_NAME = '0'
#     TERM_PROGRAM = 'Apple_Terminal'
#     TERM_PROGRAM_VERSION = '445'
#     TERM_SESSION_ID = '5F8DA05B-617A-43CA-AAF7-98F80B405C6D'
#     SHELL = '/bin/zsh'
#     HOME = '/Users/bcjung'
#     LOGNAME = 'bcjung'
#     USER = 'bcjung'
#     PATH = '/Users/bcjung/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/bcjung/Project/convert_android/env/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
#     SHLVL = '1'
#     PWD = '/Users/bcjung/project/convert_android'
#     OLDPWD = '/Users/bcjung/project'
#     HOMEBREW_PREFIX = '/opt/homebrew'
#     HOMEBREW_CELLAR = '/opt/homebrew/Cellar'
#     HOMEBREW_REPOSITORY = '/opt/homebrew'
#     MANPATH = '/opt/homebrew/share/man::'
#     INFOPATH = '/opt/homebrew/share/info:'
#     VIRTUAL_ENV = '/Users/bcjung/Project/convert_android/env'
#     PS1 = '(env) %n@%m %1~ %# '
#     VIRTUAL_ENV_PROMPT = '(env) '
#     LANG = 'ko_KR.UTF-8'
#     _ = '/Users/bcjung/Project/convert_android/env/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x3:0x33'
#     PACKAGES_PATH = '/Users/bcjung/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/bcjung/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/bcjung/.buildozer/android/platform/android-ndk-r24'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

-------------------------------------------------

### Code and Logs
from kivymd.app import MDApp
from kivymd.uix.labe import MDLabel

class Main(MDApp):
    def build(self):
        return MDLabel(text="Hello")

Main().run()

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Ubuntu 20.04 Server, Monteray12.04(Apple M1)
* Python: 3.8(ubuntu) 3.9(M1, hostpython)
* Kivy: master
* KivyMD: https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KitchenSink/blob/main/buildozer.spec#L40

**Comment by jbc0708** [comment]
> https://github.com/kivymd/KitchenSink/blob/main/buildozer.spec#L40

it's my mistake. I fix kivy to kivy==2.1.0 and rebuild.. and success!!
Thank you. and I also watch your Youtube.
