### ISSUE TITLE
The problem of Kivy Python to display Persian and Arabic text

### ISSUE THREAD

**Issue by goldaaa** [kivymd/KivyMD#1289]
Hello, my good friend, I put my problem in the link and I can't fix it, please help me, thank you.

https://stackoverflow.com/questions/73002498/the-problem-of-kivy-python-to-display-persian-and-arabic-text

**Comment by goldaaa** [comment]
<p>
This is the image you see in the output of this code.
</p>
<img src="https://i.stack.imgur.com/0aBTc.png"/>


<p>what i want:</p>
<p>Using the image editing program, I moved the text to make it correct.</p>
<p>What I want to display properly, from top to bottom.</p>

<img src="https://i.stack.imgur.com/hef4g.png"/>

**Comment by HeaTTheatR** [comment]
@goldaaa 
I don't understand Arabic. In any case, your question has nothing to do with the KivyMD library.
Tip: Check the display of non-Arabic text.

**Comment by goldaaa** [comment]
Lib\site-packages\kivy\core\text\__init__.py line 760


    def refresh(self):
        '''Force re-rendering of the text'''
        self.resolve_font_name()

        # first pass, calculating width/height
        sz = self.render()
        self._size_texture = sz
        self._size = (sz[0], sz[1])


        # if no text are rendered, return nothing.
        width, height = self._size
        # print('width, height : ', width, height)
        if width <= 1 or height <= 1:
            self.texture = self.texture_1px
            return

        # create a delayed texture
        texture = self.texture
        if texture is None or \
                width != texture.width or \
                height != texture.height:
            texture = Texture.create(size=(width, height),
                                     mipmap=self.options['mipmap'],
                                     callback=self._texture_fill)
            texture.flip_vertical()
            texture.add_reload_observer(self._texture_refresh)
            self.texture = texture
        else:
            texture.ask_update(self._texture_fill)


This discussion is for guidance and help to solve problems
I spent a lot of time to find the problem. It seems that if it shows this part like a mirror, the problem will be solved.
Changes in texture.

**Comment by goldaaa** [comment]
If you have a good solution for this part, please send it so that I can reverse the text upwards like a mirror.

**Comment by goldaaa** [comment]
This problem has been completely fixed. We are waiting for the necessary changes.
https://github.com/kivy/kivy/issues/7977

**Comment by goldaaa** [comment]
برای کار با زبان فارسی از kivyir استفاده کنید.
Use Kivyir for Persian.

pip install kivyir --user

[Link GitHub](https://gitHub.com/goldaaa/kivyir)
