### ISSUE TITLE
pos_hint in MDBoxlayout

### ISSUE THREAD

**Issue by Prakash1124** [kivymd/KivyMD#1290]
I used a MDBoxLayout and after adding some textfields and a button , I placed it on screen.

Then when I am trying to center it in screen I used pos_hint. It is taking the center_x value and placing it at the center but center_y value is ignored and the box layout stays at the bottom.

Is this intended or there is some bug?

<Code>
<RegisterWindow>:
    name: 'Register'
    canvas.before:
        Color:
            rgba: app.theme_cls.primary_color
        Rectangle:
            pos:self.pos 
            size:self.size

    MDBoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.8
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        spacing: 20

![image](https://user-images.githubusercontent.com/108631726/179580512-9711b22d-9c55-416f-a891-0a41bc0af417.png)

**Comment by HeaTTheatR** [comment]
@Prakash1124 You need to remember that all the widgets in the KivyMD library are Kivy widgets. So first you need to study the behavior of the BoxLayout widget - https://kivy.org/doc/stable/api-kivy.uix.boxlayout.html

**Comment by Prakash1124** [comment]
I am sorry Yuri if I am bothering you but I tried this in kivy. Here the centre_x and centre_y worked. So my question stays as it is. I mean is it as per design or a bug?

Below are two snapshots:
1) pos_hint: {'center_x': 0.5,'center_y': 0.5}
2) pos_hint: {'center_x': 0.5,'center_y': 0.3}

![image](https://user-images.githubusercontent.com/108631726/179601455-f76ad528-30d1-4c16-b587-639d44da9645.png)

![image](https://user-images.githubusercontent.com/108631726/179601703-c27e2f55-c270-4f38-82a7-200c4f509e19.png)

**Comment by HeaTTheatR** [comment]
@Prakash1124 
```python
from kivy.app import App
from kivy.lang import Builder


KV = '''
BoxLayout:

    Button:
        size_hint: None, None
        size: 100, 100
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class Test(App):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```
![Снимок экрана 2022-07-18 в 23 08 00](https://user-images.githubusercontent.com/16930280/179608300-12fcc161-e0a7-439e-92fb-ce8d87b9e6e1.png)
