### ISSUE TITLE
I would like to ask what is the name of this widget.

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMD#1291]
I would like to ask what is the name of this widget that implements the loading animation.

![image](https://user-images.githubusercontent.com/43966525/179743205-20c5fdca-a2d0-4df1-8901-7a059a962319.png)

**Comment by HeaTTheatR** [comment]
@471657 https://github.com/kivymd/KitchenSink/blob/main/View/ManagerScreen/manager_screen.py#L177
