### ISSUE TITLE
TextField height

### ISSUE THREAD

**Issue by DaniS001** [kivymd/KivyMD#1294]
Is there a way to set the maximum height of a text field? It should be like a multiline textfield, but have a default height so that you can see multiple lines from the beginning and it doesn't grow with each new line.

https://i.stack.imgur.com/q84BH.gif

Something like this but with MDTextField for example in the rectangle mode.

**Comment by HeaTTheatR** [comment]
@DaniS001 You can and use the `TextInput` widget from `Kivy`.

**Comment by DaniS001** [comment]
Is it also possible to use themes like dark and light with it?

**Comment by HeaTTheatR** [comment]
@DaniS001 No.

**Comment by DaniS001** [comment]
Ok thanks.
