### ISSUE TITLE
How KIVYMD implements the effect of the selection widget in the video.

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMD#1296]
How KIVYMD implements the effect of the selection widget in the video.

https://user-images.githubusercontent.com/43966525/180457383-8c177765-a92d-4adc-a39b-a8632fa86451.mp4

**Comment by HeaTTheatR** [comment]
You can easily implement this yourself using the existing KivyMD widgets.

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR Just now I went through all the widgets and nothing seems to be related to this. It should only be built with basic widgets, right?

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/list/

**Comment by ChinaGodzilla** [comment]
@HeaTTheatR THANSK
