### ISSUE TITLE
  from uix.custom_button import AnimatedButton  ModuleNotFoundError: No module named 'uix'

### ISSUE THREAD

**Issue by IndrajeethY** [kivymd/KivyMD#1298]
i tried an example py file from ur source code actually dont remember file name 

here is my code `https://nekobin.com/paqiyubeba`

**Comment by HeaTTheatR** [comment]
@TAMILVIP007 Use KivyMD from master branch.

**Comment by IndrajeethY** [comment]
okie tqs
