### ISSUE TITLE
Cannot install on Lubuntu 18

### ISSUE THREAD

**Issue by alexeygridnev** [kivymd/KivyMD#13]
Cannot install the program. When I run:
sudo python3 /home/.../setup.py install

It throws:
Traceback (most recent call last):
  File "/home/aleksei/KivyMD-master/setup.py", line 7, in <module>
    ver_file_data = open(VERSION_FILE, "rt").read()
FileNotFoundError: [Errno 2] No such file or directory: 'kivymd/__init__.py'

When I changed "kivymd/__init__.py" to the full path in setup.py (line 7) and run setup.py again, it throws:

running install
running build
running build_py
error: package directory 'kivymd' does not exist

**Comment by HeaTTheatR** [comment]
> Cannot install the program. When I run:
> sudo python3 /home/.../setup.py install

Try **_sudo pip install git+https://github.com/HeaTTheatR/KivyMD_**

**Comment by alexeygridnev** [comment]
Thank you! Now it works!
