### ISSUE TITLE
Create console scripts

### ISSUE THREAD

**Issue by JulianOrteil** [kivymd/KivyMD#1306]
### Description of the Feature

Commands like ``python -m kivymd.tools.patterns.create_project`` are unwieldy and can be improved via console scripts. For example, the aforementioned command can be shorted to ``create_project`` via a console script.

**Comment by HeaTTheatR** [comment]
@JulianOrteil 
` python kivymd/tools/release/make_release.py release 1.0.1 1.1.0.dev0 ` - https://kivymd.readthedocs.io/en/1.0.0/api/kivymd/tools/release/make_release/

**Comment by HeaTTheatR** [comment]
@JulianOrteil 
`python -m kivymd.tools.patterns.add_view` - https://kivymd.readthedocs.io/en/1.0.0/api/kivymd/tools/patterns/add_view/

**Comment by JulianOrteil** [comment]
@HeaTTheatR Both modules are implemented as requested. PR is ready to merge unless you have others you'd like done.
