### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by evgenybf** [kivymd/KivyMD#131]
I understand that for now this library is to make "touch-enabled graphical applications" only, but are there any plans on supporting navigation with a keyboard, gamepad or remote control? There is a bunch of Android TV devices that don't have touch screen.

**Comment by ArtemSBulgakov** [comment]
@evgenybf KivyMD is a library of widgets for framework Kivy. Your question is not related to KivyMD. You can ask Kivy about this https://github.com/kivy/kivy
