### ISSUE TITLE
DataTable Issue

### ISSUE THREAD

**Issue by ps2229** [kivymd/KivyMD#1310]
Using MDDatatable along with Vkeyboard , whenever I do on_row_press the Vkeyboard opens up automatically without even calling it. Not able to understand as to why this is happening.
code  
self.screen = MDBoxLayout()
        self.data_tables = MDDataTable(
            pos_hint={'center_y': 0.33, 'left': .1},
            size_hint=(0.94, 1.33),
            background_color_selected_cell="#9CB4CC",
            background_color_header="#D44444",
            use_pagination=True,
            check=True,
            column_data=[
                ("[size=33][color=#f9fcf7]Batch ID[/color][/size]", dp(60)),
                ("[size=33][color=#f9fcf7]Name[/color][/size]", dp(90)), ],
            row_data = self.s_li1   
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
   
        self.data_tables.bind(on_check_press=self.on_check_press)
        self.screen.add_widget(self.data_tables)
        self.ids.card.add_widget(self.screen)

### Versions

* OS: rpi bullseye
* Python: 3.9.2
* Kivy: 2.1.0
* KivyMD: 1.1.0.dev0

**Comment by HeaTTheatR** [comment]
@ps2229 Attach a minimal code example.

**Comment by GromoZavr** [comment]
I am having exactly the same issue with MDDataTable and Vkeyboard. How to fix it?
