### ISSUE TITLE
Responsive directory structure incomplete when using kivymd.create_project

### ISSUE THREAD

**Issue by jphoubion** [kivymd/KivyMD#1311]
Hi!
When I use the following command to create a project with responsibe design, the directory structure is incomplete under view/FirstScreen/components/ :
`kivymd.create_project MVC /mnt/92AE1710AE16EC8B/dev_en_cours KivyTest python3.10 2.1.0 --use_hotreload yes --use_responsive FirstScreen`

I use the KivyMD library master version.

![kivymd](https://user-images.githubusercontent.com/25503721/184511501-e120e7dc-207c-4539-935b-ea90c7efc848.png)

Any idea?

Thanks for your help.

JP

**Comment by HeaTTheatR** [comment]
@jphoubion 
The names of the screens that inherit the responsive behavior and that you specify in the `--use_responsive` parameter must match the names of the screens that are specified in the `--name_screen` parameter.

Right command:

```
kivymd.create_project \\
    MVC \\
    /mnt/92AE1710AE16EC8B/dev_en_cours \\
    KivyTest python3.10 \\
    2.1.0 \\
    --use_hotreload yes \\
    --name_screen FirstScreen \\
    --use_responsive FirstScreen
```
