### ISSUE TITLE
MDScreenManager doc: check_tranistion.

### ISSUE THREAD

**Issue by cederom** [kivymd/KivyMD#1312]
### Description of the Feature

Newcomer request :-) In the documentation of `MDScreenManager` [1] please list possible value for `check_transition` property. This is in detail explained in Kivy docs and `transition` property does not propagate to `MDScreenManager` object from `ScreenManager` (i.e `NoTransition` set to `ScreenManager` works as intended but still there is an animation I cannot control in `MDScreenManager`). So far I will stick to `ScreenManager` :-)

By the way is there a single PDF documentation for KivyMD just as there is for Kivy? Based on the code itself? That would be awsome to have :-)

Thanks :-)

[1] https://kivymd.readthedocs.io/en/latest/components/screenmanager/#kivymd.uix.screenmanager.MDScreenManager.check_transition

### Versions

* OS: FreeBSD 13-STABLE.
* Python: 3.9.13.
* Kivy: 2.1.0.
* KivyMD: 1.0.2.

**Comment by HeaTTheatR** [comment]
@cederom Unfortunately, I don't quite understand the essence of your question...
