### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.uix.picker'

### ISSUE THREAD

**Issue by irenemaring** [kivymd/KivyMD#1313]
I have just installed kivymd and kivy libraries in my Windows with pip
pip install kivy
pip install kivy-deps.angle
pip install kivy-deps.glew
pip install kivy-deps.gstreamer
pip install kivy-deps.sdl2
pip install kivymd`

Everything works fine except for the Picker module:

Python 3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

`import kivymd.uix.picker `
         

> [INFO   ] [Logger      ] Record log in C:\Users\Usuario\.kivy\logs\kivy_22-08-15_13.txt
> [INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.3
> [INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
> [INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
> [INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
> [INFO   ] [Kivy        ] v2.1.0
> [INFO   ] [Kivy        ] Installed at "C:\Users\Usuario\miniconda3\envs\androidapp\lib\site-packages\kivy\__init__.py"
> [INFO   ] [Python      ] v3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
> [INFO   ] [Python      ] Interpreter at "C:\Users\Usuario\miniconda3\envs\androidapp\python.exe"
> [INFO   ] [Logger      ] Purge log fired. Processing...
> [INFO   ] [Logger      ] Purge finished!
> [INFO   ] [KivyMD      ] 1.0.2, git-38fe356, 2022-08-11 (installed at "C:\Users\Usuario\miniconda3\envs\androidapp\lib\site-packages\kivymd\__init__.py")
> [INFO   ] [Factory     ] 189 symbols loaded
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [Window      ] Provider: sdl2
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] GLEW initialization succeeded
> [INFO   ] [GL          ] Backend used <glew>
> [INFO   ] [GL          ] OpenGL version <b'4.0.0 - Build 10.18.10.4358'>
> [INFO   ] [GL          ] OpenGL vendor <b'Intel'>
> [INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4000'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 0
> [INFO   ] [GL          ] Shading version <b'4.00 - Build 10.18.10.4358'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <16>
> [INFO   ] [Window      ] auto add sdl2 input provider
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
>  Traceback (most recent call last):
>    File "<stdin>", line 1, in <module>
>  ModuleNotFoundError: No module named 'kivymd.uix.picker'

```
from importlib.metadata import version
version('kivymd')
```

> '1.0.2'

`version('kivy')`

> '2.1.0'

Thank you!

**Comment by HeaTTheatR** [comment]
@irenemaring `import kivymd.uix.pickers`
