### ISSUE TITLE
Datatable does not work with kivymd 1.1.0.dev0

### ISSUE THREAD

**Issue by Igor-san** [kivymd/KivyMD#1323]
Installed the version as:

git clone https://github.com/kivymd/KivyMD.git --depth 1
cd KivyMD
pip install .

Used the official example:
https://kivymd.readthedocs.io/en/1.0.2/components/datatables/?highlight=data_tables#

Got an error:

```
 File "D:\MyDocuments\Python\KIVY\KivyMd\lib\site-packages\kivy\lang\parser.py", line 199, in precompile
     self.co_value = compile(value, self.ctx.filename or '<string>', mode)
   File "<string>", line 177
 SyntaxError: f-string: expecting '}'

Process finished with exit code 1
```

Looks like the problem is here
https://github.com/kivymd/KivyMD/blob/4df275d525fc7bf0f804b4bf99cedcb5d25de661/kivymd/uix/datatables/datatables.kv#L177
and
https://github.com/kivymd/KivyMD/blob/4df275d525fc7bf0f804b4bf99cedcb5d25de661/kivymd/uix/datatables/datatables.kv#L196

Changed to (like in older versions):
`f"{root.table_data.rows_num if root.table_data.rows_num < len(root.table_data.row_data) else len(root.table_data.row_data)}"
`
and

`f"1-" \
f"{root.table_data.rows_num if root.table_data.rows_num > len(root.table_data.row_data) else len(root.table_data.row_data)} " \
f"of {len(root.table_data.row_data)}"
`

It seems to work

Versions
OS: Windows 10 Pro 64 bits
Python: Python 3.7.9
Kivy:  2.1.0
KivyMD: 1.1.0.dev0

**Comment by HeaTTheatR** [comment]
@Igor-san Attach a minimal code...

**Comment by Igor-san** [comment]
да просто демку можно взять https://kivymd.readthedocs.io/en/1.0.2/components/datatables/?highlight=data_tables#kivymd.uix.datatables.datatables.MDDataTable.column_data, но вот

```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.uix.anchorlayout import AnchorLayout


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            # name column, width column, sorting function column(optional)
            column_data=[
                ("No.", dp(30)),
                ("Status", dp(30)),
                ("Signal Name", dp(60)),
                ("Severity", dp(30)),
                ("Stage", dp(30)),
                ("Schedule", dp(30), lambda *args: print("Sorted using Schedule")),
                ("Team Lead", dp(30)),
            ],
        )
        layout.add_widget(self.data_tables)
        return layout


Example().run()
```

Думал проблемы с удалением отмеченных строк, когда отметки смещаются на неудаленные, в новой версии нет. Сорри за русский, с английским не особо дружу.
