### ISSUE TITLE
Calculate the DEFAULT_FONT static variable in label.py, in scalable pixel (sp)

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#1329]
`font_style` variable is not functional on Android due to the `DEFAULT_FONT` variable is just a mere number and not calculated in `sp`

**Comment by HeaTTheatR** [comment]
@kengoon The font_style property works correctly on Android. At least I have not seen any errors in the operation of this property.

**Comment by kengoon** [comment]
@HeaTTheatR there are no errors but the font_size remains small when I set the font_style to H1

**Comment by kengoon** [comment]
@HeaTTheatR the text `Login` still remains the same after changing the font_style to H1


![Screenshot_20220901-094323.png](https://user-images.githubusercontent.com/42192162/187872003-bbb03ad2-a6ff-41f2-8f87-edc43689587d.png)
