### ISSUE TITLE
Inappropiate render of some widgets

### ISSUE THREAD

**Issue by zhugeo** [kivymd/KivyMD#133]
#### Description of the Bug

Inappropiate work of some widgets when fullscreen mode is on

### Code and Logs

https://github.com/HeaTTheatR/KivyMD/tree/master/demos/kitchen_sink

### Screenshots

![image](https://user-images.githubusercontent.com/48350334/68082102-dca27e00-fe31-11e9-96e4-9182c2f74846.png)
![image](https://user-images.githubusercontent.com/48350334/68082184-ea0c3800-fe32-11e9-9f67-caddc64f2f04.png)
![image](https://user-images.githubusercontent.com/48350334/68082191-fdb79e80-fe32-11e9-9f26-1a89f2f87025.png)

### Versions

* OS: Windows 10
* Python: 3.6
* Kivy: 1.11.1
* KivyMD: 0.102.0

**Comment by HeaTTheatR** [comment]
![555](https://user-images.githubusercontent.com/16930280/68106710-8bf35980-fef3-11e9-866c-eaa936c7ac1b.gif)

**Comment by ArtemSBulgakov** [comment]
Windows 10 64 bit, screen 1920x1080
![issue-133](https://user-images.githubusercontent.com/44732506/68107114-c7425800-fef4-11e9-8421-342e07e528c1.gif)

**Comment by HeaTTheatR** [comment]
@Mountaino Apparently, this is only on Windows, because the problem does not reproduce on my computer.

**Comment by wasimafser** [comment]
@ArtemSBulgakov , @HeaTTheatR this can be closed right ?

**Comment by HeaTTheatR** [comment]
@wasimafser Yes. `useranimationcard.py` is still in the library, but it will be removed

**Comment by HeaTTheatR** [comment]
The `useranimationcard.py` module has been removed.
