### ISSUE TITLE
TouchBehaviour is not supported in KV language

### ISSUE THREAD

**Issue by bergus** [kivymd/KivyMD#1335]
I tried to use `TouchBehaviour` in a `.kv` file but it didn't work.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
<TouchLabel@TouchBehavior+MDLabel>

Screen:
    TouchLabel:
        text: "tap me some time!"
        on_long_touch: root.menu.open()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)

if __name__ == '__main__':
    MainApp().run()
```

Errors:
```text
kivy.factory.FactoryException: Unknown class <TouchBehavior>
```
```text
AttributeError: long_touch, …/kivy/lang/builder.py, line 729, in _apply_rule
``` 

### Versions

* OS: Raspbian GNU/Linux 10
* Python: 3.7
* Kivy: 2.1.0
* KivyMD: 1.0.2

### Details

Comparing the definition of `TouchBehaviour` with e.g. `HoverBehavior`, the former is missing:
* `register('TouchBehavior', module='kivymd.uix.behaviors.touch_behavior')` in *factory_registers.py*
* `self.register_event_type("on_long_touch"), self.register_event_type("on_double_tap"), self.register_event_type("on_triple_tap")` in the constructor
* calling `self.dispatch("on_long_touch")` instead of `self.on_long_touch(…)` etc

#823 is probably a duplicate, being caused by this deeper problem.

**Comment by HeaTTheatR** [comment]
@bergus Just import the class name in KV file.

**Comment by bergus** [comment]
No, that is not the solution - after doing `#:import TouchBehavior kivymd.uix.behaviors.touch_behavior.TouchBehavior`, one still gets an exception because those events are not proper events.
Also, why wouldn't KivyMD register the class by itself, like it does with all the other classes?

**Comment by bergus** [comment]
Would you accept a PR for this?
