### ISSUE TITLE
Does KivyMD require python 3.10 now?

### ISSUE THREAD

**Issue by PeterSurda** [kivymd/KivyMD#1339]
In a commit introduced yesterday,

https://github.com/kivymd/KivyMD/blob/6d596bd406284876e2b3df507cb8017bc1eb4df3/kivymd/uix/behaviors/elevation.py#L779

The syntax used to define a union requires python 3.10. Is that intentional? I don't mind either way, just if now python 3.10 is required it should be reflected in `setup.py`. Alternatively, you can use a syntax compatible with older versions, e.g.:

```
from typing import Union

    def on_opacity(self, instance, value: Union[int, float]) -> None:
```

**Comment by PeterSurda** [comment]
Thanks.

**Comment by PeterSurda** [comment]
Works now again in python 3.8.

**Comment by HeaTTheatR** [comment]
> Thanks.

Thank you for pointing out the bugs. This way they are fixed faster :)
