### ISSUE TITLE
Ability to add custom tooltip in the MDDataTable Column.

### ISSUE THREAD

**Issue by TobiasHT5** [kivymd/KivyMD#1340]
While working with MDDataTables of recent, I found it important to be able to add extra information to the column field about what the column contains. So my suggestion is if it's possible to add a fourth parameter in the column_data tuple that accepts this information. Mostly probably it would look better if it were the 3rd argument and then the 4th being the sorting function. Something like this.
`(column_name, column_size, column_tooltip, column_sort_function)`

**Comment by HeaTTheatR** [comment]
@ht-thomas I don't quite understand what you mean...

**Comment by TobiasHT5** [comment]
Let me see if I can explain a little better.

```python
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp

class Main (MDApp):
    def build (self):
        return MDDataTable(column_data = [("Name",dp(30),sort_function)])
```
Here, MDDataTable automatically creates a tooltip from the name provide for the column. So when someone hovers the mouse over the column "Name" shall be displayed in the tooltip automatically. What if we could give room for some to add some detail to the tooltip so that when some hovers over the Name column, instead of the tooltip just having "Name", someone could provide a string such as "Name of employee", so that when someone hovers over the Name column, that information is displayed in the tooltip.
So it could be something like

```python
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp

class Main (MDApp):
    def build (self):
        return MDDataTable(column_data = [("Name",dp(30), "Name of employee",sort_function)])
```

I don't know if I'm clearer now.

**Comment by TobiasHT5** [comment]
Just as how one is able to add custom tooltip information to the MDToolAppBar

**Comment by TobiasHT5** [comment]
Can I work on a PR for this?

**Comment by JimScope** [comment]
You could also have a flag in the tuple to disable the tooltip, since passing a value that evaluates to false as an empty string will return the text of the column.

**Comment by JimScope** [comment]
You could also have a flag in the tuple to disable the tooltip, since passing a value that evaluates to false as an empty string will return the text of the column.
