### ISSUE TITLE
KivyMD does not support RTL  & do not support many languages

### ISSUE THREAD

**Issue by SaeidJavadi** [kivymd/KivyMD#1341]
### KivyMD does not support RTL

Thanks for your great library

But there are several big problems
Roboto fonts do not support many languages, such as Chinese Persian Arabic and ...
And your library does not support RTL (only LTR supports) In the event that must be a capability in your components to adjust RTL or LTR (as a parameter)
For example in MDTopAppBar cannot be adjusted RTL to display text and this is a problem, and many more of the methods
Please check and solve these elementary problems
![KivyMD](https://user-images.githubusercontent.com/53658372/188933576-e4b6728f-6a71-47c6-bb6e-f831eb0922c8.PNG)

Thank you for not simply rejecting these problems

### Versions
* OS: windows 10
* Python: 3.10.5
* Kivy: 2.1.0
* KivyMD: 1.1.0.dev0

**Comment by HeaTTheatR** [comment]
@SaeidJavadi Everything about custom fonts does not apply to the KivyMD library. This is a question for the Kivy framework.

**Comment by SaeidJavadi** [comment]
@HeaTTheatR   
Yes, it's true, but how can we lead option to the right? And put the MDTopAppBar menu on the right? To set when ([anchor](https://kivymd.readthedocs.io/en/latest/components/navigationdrawer/#kivymd.uix.navigationdrawer.navigationdrawer.MDNavigationDrawer.anchor))
```
anchor: "right"
```
it needs to have the three-line menu on the right
How to do this?
I think this is related to the Kivymd library
![KivyMD1](https://user-images.githubusercontent.com/53658372/189218410-5dc9a034-77a1-4ec8-af5a-70d9f3599d86.png)

and how can we start the title appbar text from the right?

**Comment by HeaTTheatR** [comment]
@SaeidJavadi https://kivymd.readthedocs.io/en/latest/components/toolbar/#kivymd.uix.toolbar.toolbar.MDTopAppBar.right_action_items
