### ISSUE TITLE
 kivy.factory.FactoryException: Unknown class <MDToolbar>

### ISSUE THREAD

**Issue by Monica-Xiao** [kivymd/KivyMD#1346]
After I move everything from the firebaseLoginScreen folder to the folder where the main.kv and main.py are. Then I had another error named:  kivy.factory.FactoryException: Unknown class <MDToolbar>
I am not sure is it due to the version of kivy or not.  But when I searched the MDToolbar API at kivymd's documents, the API <MDToolbar> does not exit. So I replaced it with <MDTopAppBar> and everything goes fine now.
I post this issue just in case that anyone else may have this problem with me.
Please let me know if I am wrong, thank you

**Comment by HeaTTheatR** [comment]
@Monica-Xiao Use `MDTopAppBar` unstead - https://kivymd.readthedocs.io/en/latest/components/toolbar/
