### ISSUE TITLE
MDCard has no auto update for mg_bg_color

### ISSUE THREAD

**Issue by Kak0ytachel** [kivymd/KivyMD#1348]
### Description of the Bug

Already inited MDCards in kivymd 1.0.2 do not change their mg_bg_color after changing app.theme_cls.theme_style as they used to in kivymd 0.104.2. This feature is not mentioned in changelog, so i think it's a bug which needs to be fixed
### Code and Logs

```python
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivy.lang import Builder
kv = """
ScreenManager:
    Screen1:
    Screen2:
    Screen3:

<Screen1>
    name: 'Screen1'
    
    MDBoxLayout:
        Button:
            text: 'light'
            on_release:
                app.theme_cls.theme_style = 'Light'
        Button:
            text: 'dark'
            on_release:
                app.theme_cls.theme_style = 'Dark'
        Button:
            text: 'Screen2'
            on_release:
                app.root.current = 'Screen2'
        Button:
            text: 'Screen3'
            on_release:
                app.root.current = 'Screen3'

<Screen2>
    name: 'Screen2'
    padding: 50

    MDCard:
        on_release:
            app.root.current = 'Screen1'
            text: 'back'

<Screen3>
    name: 'Screen2'
    padding: 50

    MDCard:
        on_release:
            app.root.current = 'Screen1'
            text: 'back'   
"""


class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Versions

* OS:  win10
* Python: 3.9.1
* Kivy: 2.1.0
* KivyMD: 1.0.2

**Comment by HeaTTheatR** [comment]
@Kak0ytachel Unfortunately, your example contains bugs. Please attach a code that works...

**Comment by Kak0ytachel** [comment]
Oh, I'm sorry, I forgot to update the code, here you go @HeaTTheatR 
```python

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.uix.card import MDCard

kv = """
ScreenManager:
    Screen1:
    Screen2:
    Screen3:

<Screen1>
    name: 'Screen1'
    
    MDBoxLayout:
        spacing: 30
        padding: 20
        Button:
            text: 'light'
            on_release:
                app.theme_cls.theme_style = 'Light'
        Button:
            text: 'dark'
            on_release:
                app.theme_cls.theme_style = 'Dark'
        Button:
            text: 'Screen2'
            on_release:
                app.root.current = 'Screen2'
        Button:
            text: 'Screen3'
            on_release:
                app.root.current = 'Screen3'

<Screen2>
    name: 'Screen2'
    MDBoxLayout:
        spacing: 30
        padding: 20

        MDCard:
            on_release:
                app.root.current = 'Screen1'

<Screen3>
    name: 'Screen3'
    box: box
    MDBoxLayout:
        id: box
        spacing: 30
        padding: 20
        
        MDCard:
            on_release:
                app.root.current = 'Screen1'
            Label:
                text: 'back'

"""
class Screen1(Screen):
    pass

class Screen2(Screen):
    pass

class Screen3(Screen):

    def on_pre_enter(self):
            self.box.add_widget(MDCard())
            

class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()


```
this code should work (I hope)

**Comment by HeaTTheatR** [comment]
@Kak0ytachel Write an algorithm for reproducing the bug...

**Comment by Kak0ytachel** [comment]
@HeaTTheatR Click 'light' - 'Screen3' - 'back' - 'dark' - 'Screen3' - 'back' - repeat.
Every time you get to Screen3 it adds a MDCard colors of the current theme to the screen. After you have exited Screen3, changed the theme and returned the previously initiated MDCards should adjust to the current theme, which does not happen in kivymd 1.0.2, but happened in previous versions (0.104.2)

**Comment by HeaTTheatR** [comment]
@Kak0ytachel I use the master version of the KivyMD library and don't see any bugs.

**Comment by Kak0ytachel** [comment]
@HeaTTheatR I have installed master (1.1.0.dev0) version but still getting this bug

![Снимок экрана 2022-09-15 142257](https://user-images.githubusercontent.com/108612918/190392112-bedd2506-e547-442a-9249-8c807b0aa455.png)

**Comment by HeaTTheatR** [comment]
@Kak0ytachel I don't find any bugs. Make a screen recording.

**Comment by Kak0ytachel** [comment]
@HeaTTheatR Are you joking? Here you go

https://user-images.githubusercontent.com/108612918/190396454-14c458da-d228-476b-adc4-4a924f402a6c.mp4

**Comment by HeaTTheatR** [comment]
@Kak0ytachel Update KivyMD library from master branch.

**Comment by Kak0ytachel** [comment]
@HeaTTheatR I have unistalled kivymd ` pip uninstall kivymd` , re-installed using `pip install https://github.com/kivymd/KivyMD/archive/master.zip` and nothing changed

**Comment by HeaTTheatR** [comment]
@HeaTTheatR `pip install https://github.com/kivymd/KivyMD/archive/master.zip --no-cache-dir`

**Comment by Kak0ytachel** [comment]
@HeaTTheatR I have re-installed one more time using `pip install https://github.com/kivymd/KivyMD/archive/master.zip --no-cache-dir` and still getting the same result

**Comment by Kak0ytachel** [comment]
Running the same code in kivymd 0.104.2 looks like that 

https://user-images.githubusercontent.com/108612918/190400225-073617a8-b7ec-4bed-8183-78f1298be3d7.mp4

**Comment by HeaTTheatR** [comment]
@Kak0ytachel There is no such bug in the master branch.

**Comment by Kak0ytachel** [comment]
@HeaTTheatR But why then am I getting it?

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/compare/55780b7a88d4...0ec639ee0436
