### ISSUE TITLE
BUG callback MDFloatingActionButtonSpeedDial

### ISSUE THREAD

**Issue by Mau005** [kivymd/KivyMD#1355]
### Description of the Bug

Hello, I have been working on a project for months and recently I got an error, that the MDFloatingActionButtonSpeedDial button did not perform any action, I compiled it and did nothing, then in the interpreter it did not start doing anything either, it turns out that I created a new project and I don't have access to the widget callback, I tried examples on the internet and everything happens the same way without being able to access a callback in the code

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

screen = '''
Screen: 

    MDFloatingActionButtonSpeedDial:
        on_release_stack_button:app.callback
        data:app.data
        rotation_root_button:True
        hint_animation:True
        bg_hint_color: app.theme_cls.primary_light
'''


class Wolf(MDApp):
    data = {
        "help-rhombus": "Help",
        'triangle': 'Setting',
        'key': 'Register', }

    def callback(self, instance):
        if instance.icon == 'help-rhombus':
            print('Callback self.help-rhombus()')
        elif instance.icon == 'key':
            print('Callback self.key()')
        elif instance.icon == 'triangle':
            print('Callback self.triangles()')

    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.theme_cls.primary_palette = 'Green'
        screen_r = Builder.load_string(screen)
        return screen_r

Wolf().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/31163804/191261608-c98cb82c-79a7-438f-b289-0c69c47d5a54.png)
![image](https://user-images.githubusercontent.com/31163804/191261688-b4af4e72-d6b1-4411-b5a4-6a7fa596b382.png)

### Versions

* OS: Fedora 36
* Python: 3.9
* Kivy:  2.1.0
* KivyMD:  1.1.0.dev0

**Comment by HeaTTheatR** [comment]
@Mau005 https://kivymd.readthedocs.io/en/latest/components/button/#binds-to-individual-buttons
