### ISSUE TITLE
importing MDDatePicker Error [Raspbian Bullseye]

### ISSUE THREAD

**Issue by ryangania** [kivymd/KivyMD#1363]
### Description of the Bug

Importing the MDDatePicker gives me error

### Code and Logs

```python
from kivymd.uix.pickers import MDDatePicker
```

### Screenshots
![image](https://user-images.githubusercontent.com/37531209/193090617-54850028-6a92-4ea8-8dbc-56ab15722494.png)

### Versions

* OS: Raspbian
* Python:  3.9
* Kivy:  2.1.0
* KivyMD:  1.1.0

**Comment by HeaTTheatR** [comment]
@ryangania This has long been fixed in the master version of the KivyMD library.

**Comment by ryangania** [comment]
why I still receiving this error?

**Comment by HeaTTheatR** [comment]
@ryangania 
![Снимок экрана 2022-09-29 в 21 00 23](https://user-images.githubusercontent.com/16930280/193107597-fa098a56-177d-42c3-b192-2bed19fd39e9.png)

**Comment by ryangania** [comment]
Yes I installed the master version

**Comment by HeaTTheatR** [comment]
@ryangania Solve the problem with your virtual environments.
