### ISSUE TITLE
MDTextField , defining 'on_focus' function inside the python file removes the 'icon_left_color_focus' effect.

### ISSUE THREAD

**Issue by DaveMalek** [kivymd/KivyMD#1364]
### Description of the Bug

I am trying to make a custom MDTextField class. If I define the 'on_focus' function inside the python file, the effect of 'icon_left_color_focus' will be removed!  
when I delete the 'on_focus' function from the end of my python file, then the 'icon_left_color_focus' will work!

Please note that I have to define my 'on_focus' function inside the python file and not 'kv' file! 

, and please note that just 'icon_left_color_focus' is not working and nothing else.

By the way, the only reason I am creating a custom MDTextField is that the 'line_color_normal' property does not work for 'round' mode.

Thanks!

### Code and Logs
```python

from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.core.window import Window
from kivymd.uix.textfield import MDTextField
class MyTextField(MDTextField):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.mode = 'round'
        self.pos_hint = {"center_x":0.5, "center_y":0.5}
        self.size_hint = None, None
        self.width = 340

        self.fill_color_normal = (25/255,25/255,25/255,1)
        self.hint_text_color_normal = (130/255,130/255,130/255,1)
        self.text_color_normal = (1,1,1,1)
        self.text_color_focus = (1,1,1,1)
        #self.line_color_normal = (1,115/255,225/255,0)
        self.line_color_focus = (0,115/255,225/255,1)
        self.icon_left_color_normal = (130/255,130/255,130/255,1)
        self.icon_left_color_focus = (0,115/255,225/255,1)

    def on_focus(self, instance_text_field, focus:False):  #this function causes issue, if deleted it, 'icon_color' issue will be solved!
        print('yes')

kv = """

MDFloatLayout:
    md_bg_color: (25/255,25/255,25/255,1)
    MyTextField:
        id: user_text
        hint_text: 'User Name'
        icon_left: 'account-circle'
    # KV-Code
"""

class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)

if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![textfield](https://user-images.githubusercontent.com/48634171/193154556-70f78243-cbac-4ebd-a4a2-c4818c8c9391.png)

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@DaveMalek 
```python
class MyTextField(MDTextField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        [...]
        self.bind(focus=self.field_focus)

    def field_focus(*args):
        pass
```

**Comment by DaveMalek** [comment]
@HeaTTheatR, Thank you so much for the response. It worked perfectly.
A quick question about MDTextField, 'line_color_normal' is not available for 'round' mode? correct?

**Comment by HeaTTheatR** [comment]
@DaveMalek No (it's probably a bug). But the `line_color_focus` attribute works.
