### ISSUE TITLE
Support for data-tables in KivyMD

### ISSUE THREAD

**Issue by lijose** [kivymd/KivyMD#138]
#### Description of the Feature

Currently data-table is not available KivyMD. I looking for this feature to create a desktop app in Kivy.
Any one planing to add this in near future ??

**Comment by HeaTTheatR** [comment]
There are many plans. There are few performers.

**Comment by BillBridge** [comment]
Together with Zuhaib we've developed some widgets including a datatable.
https://gitlab.com/zuhaib/KivyMD/-/branches
I guess this code must be adapted in order to incorporate it in this kivyMD fork.

**Comment by HeaTTheatR** [comment]
@BillBridge Yes, we can work with this, but there is something that needs to be fixed for Python3

**Comment by BillBridge** [comment]
That's right. It was developed for python 2.7.

**Comment by BillBridge** [comment]
@lijose could you give it a try to adapt it to Python3?

**Comment by BillBridge** [comment]
Just to give you some idea on how the datatable looks like:

![datatable](https://user-images.githubusercontent.com/18249253/68295155-0d80ee00-0092-11ea-954d-35d908565665.png)

**Comment by HeaTTheatR** [comment]
There is a list of tasks that I must complete before moving on to tables

**Comment by ArtemSBulgakov** [comment]
Material Design specification: https://material.io/components/data-tables/

**Comment by CultureCitizen** [comment]
I wrote a kivy table widget in case anyone wants to use it as a starting point/ reference 

https://github.com/CultureCitizen/kivy_qztable

**Comment by HeaTTheatR** [comment]
@CultureCitizen Too many heavy third-party libraries are used by you!

**Comment by CultureCitizen** [comment]
> 
> 
> @CultureCitizen Too many heavy third-party libraries are used by you!
Sory about that. Different design principles I guess . Displaying a dataframe / numpy array with one line was a must for me. Once it is stable I might make a branch which is data source agnostic.

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/datatables.py
