### ISSUE TITLE
MDFloatLayout not working properly

### ISSUE THREAD

**Issue by twobrainsink** [kivymd/KivyMD#1398]
MDFloatLayout does not resize some widgets when the window is resized. For example:
Before the window was resized:
![image](https://user-images.githubusercontent.com/77238864/195990763-e4cccfdd-3a97-487f-b704-33e440a54aa2.png)
After:
![image](https://user-images.githubusercontent.com/77238864/195990776-ddd9e5b3-b95c-4d96-8e88-a6560b587b32.png)
As a test, I made a window consisting of MDFlatButton:
Before the window was resized:
![image](https://user-images.githubusercontent.com/77238864/195990391-b2ae4977-3608-4510-8fd4-b1001f86dc53.png)
After:
![image](https://user-images.githubusercontent.com/77238864/195990416-83462c6b-b6fb-46de-b24b-541764e5e0ff.png)
They just shrunk in size, but they didn't start to overlap. As far as I understand, MDFloatLayout cannot resize widgets such as text box and label.

**Comment by HeaTTheatR** [comment]
@NoneDev-git MDFloatLayout == FloatLayout

**Comment by twobrainsink** [comment]
I know, but it doesn't work.

**Comment by HeaTTheatR** [comment]
@NoneDev-git Your issue is not related to the KivyMD library

**Comment by twobrainsink** [comment]
This layout does not work with your widgets
