### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by zworkb** [kivymd/KivyMD#140]
### Description of the Feature

Although there is no formal spec in material.io sometime it is practical to have
a *ComboBox* which is an edit field with a dropdown list. See [Wikipedia](https://en.wikipedia.org/wiki/Combo_box) for a definition. I have a working prototype
and would be happy about suggestions. When there is approval I can make a PR.

### Test it
I have prototyped it in my [fork](https://github.com/zworkb/KivyMD/tree/combobox).
It is integrated there in the kitchen_sink under the menu *ComboBox*.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.factory import Factory
from kivy.lang import Builder

Builder.load_string(
    '''
#:import toast kivymd.toast.toast
#:import MDComboBox kivymd.uix.combobox.MDComboBox


<MyRoot@BoxLayout>
    orientation: 'vertical'

    MDToolbar:
        title: "Test MDDropDownItem"
        md_bg_color: app.theme_cls.primary_color
        elevation: 10
        left_action_items: [['menu', lambda x: x]]

    FloatLayout:

        MDComboBox:
            id: dropdown_item
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            size_hint:(.3, None)
            items: app.items
            text:'Item '

        MDComboBox:
            id: dropdown_item_lower
            pos_hint: {'center_x': 0.5, 'center_y': 0.45}
            size_hint:(.3, None)
            items: app.items
            text:'Item '

        MDRaisedButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            text: 'Check Item'
            on_release: toast(dropdown_item.text)
''')


class Test(MDApp):

    def build(self):
        self.items = [f"Item {i}" for i in range(100)]
        return Factory.MyRoot()


if __name__ == '__main__':
    Test().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

**Comment by HeaTTheatR** [comment]
@zworkb So far this is not working properly ...
![Снимок экрана 2019-11-10 в 11 57 55](https://user-images.githubusercontent.com/16930280/68541488-54802380-03b1-11ea-84d0-8ab282e57fa4.png)
![Снимок экрана 2019-11-10 в 11 58 04](https://user-images.githubusercontent.com/16930280/68541489-54802380-03b1-11ea-9651-de1a1b17b4c7.png)
![Снимок экрана 2019-11-10 в 11 58 12](https://user-images.githubusercontent.com/16930280/68541490-5518ba00-03b1-11ea-941b-c79506fe681c.png)
![Снимок экрана 2019-11-10 в 11 58 25](https://user-images.githubusercontent.com/16930280/68541491-5518ba00-03b1-11ea-96f7-c34c6bdbdf9b.png)

**Comment by zworkb** [comment]
why did you close it? Let me know if you would like this feature in KivyMD.
If yes, I fix the problems. If no, I just will use it internally in my projects

**Comment by HeaTTheatR** [comment]
@zworkb https://www.youtube.com/watch?v=Q8s3pnPP4oo (52 second) - This is how it should look.

**Comment by ArtemSBulgakov** [comment]
@zworkb Please fix problems and let us know about it.

**Comment by zworkb** [comment]
> @zworkb https://www.youtube.com/watch?v=Q8s3pnPP4oo (52 second) - This is how it should look.

ok, thanks for the hint, I assume you refer to time position 0:44 in that video.

from the visual representation it seems clear, but I have some questions there:

- especially for long lists, would it not be better to filter instead of just highlight the items?
  A good behavior pattern would be the intellitext in Pycharm
- shall the menu just grow downwards or should it be flexible in case the combobox is at the lower end of the screen?
- shall I display a triangle as it is done in DropdownItem?

**Comment by HeaTTheatR** [comment]
@zworkb It is advisable that everything be done according to the official guidelines of material design. We are now paying particular attention to this.

**Comment by ArtemSBulgakov** [comment]
@zworkb It should have two behaviours: filtering (by default) and highlighting. User should also be able to change filter function (that returns list of items to display) and selecting highlighted item function (that returns index of item to highlight).

Triangle in the right should be displayed.
Material Design spec: https://material.io/components/menus/#exposed-dropdown-menu

**Comment by zworkb** [comment]
fine, thanks for the link, i always looked for combobox in the specs and did not find it,
what we need is the `Editable dropdown menu`, now I know what to do...
