### ISSUE TITLE
MDDropDownItem open crashes on android

### ISSUE THREAD

**Issue by ElMastro** [kivymd/KivyMD#1400]
Greetings;
I made a program with a MDDropDownItem; the program works well on Archlinux, however, when I build it with buildozer as an APK, on android the program crashes when I click the Button that recalls the menu.

Trying many times, I discovered that the line that crashes the program is

`self.menu.open()`, before that everything works.
the adb logcat says:
`10-27 00:02:23.808  5897  5938 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 in tid 5938 (SDLThread), pid 5897 (org.test.myapp)
10-27 00:02:23.900  5952  5952 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
10-27 00:02:23.900   872   872 I tombstoned: received crash request for pid 5938
10-27 00:02:23.901  5952  5952 I crash_dump64: performing dump of process 5897 (target tid = 5938)
10-27 00:02:23.905  5952  5952 E DEBUG   : failed to read /proc/uptime: Permission denied
10-27 00:02:24.047  5952  5952 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-27 00:02:24.047  5952  5952 F DEBUG   : Build fingerprint: 'motorola/nio_retaile/nio:12/S1RTS32.41-20-16-1-4/e53b3-5dfde:user/release-keys'
10-27 00:02:24.047  5952  5952 F DEBUG   : Revision: 'pvt'
10-27 00:02:24.047  5952  5952 F DEBUG   : ABI: 'arm64'
10-27 00:02:24.047  5952  5952 F DEBUG   : Timestamp: 2022-10-27 00:02:23.905403895+0200
10-27 00:02:24.047  5952  5952 F DEBUG   : Process uptime: 0s
10-27 00:02:24.047  5952  5952 F DEBUG   : Cmdline: org.test.myapp
10-27 00:02:24.047  5952  5952 F DEBUG   : pid: 5897, tid: 5938, name: SDLThread  >>> org.test.myapp <<<
10-27 00:02:24.047  5952  5952 F DEBUG   : uid: 10403
10-27 00:02:24.047  5952  5952 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40
10-27 00:02:24.047  5952  5952 F DEBUG   : Cause: null pointer dereference
10-27 00:02:24.047  5952  5952 F DEBUG   :     x0  0000000000000001  x1  0000000000000000  x2  0000000000000003  x3  000000000000001c
10-27 00:02:24.047  5952  5952 F DEBUG   :     x4  00000073df9a295c  x5  0000000000000003  x6  00000073df9a2c0c  x7  000000000008a000
10-27 00:02:24.047  5952  5952 F DEBUG   :     x8  0000000000000003  x9  0000000000000003  x10 0000007247a1d164  x11 00000073df9a2964
10-27 00:02:24.047  5952  5952 F DEBUG   :     x12 00000074cf99053c  x13 0000007247a1d16c  x14 0000000000000000  x15 0000000000000000
10-27 00:02:24.047  5952  5952 F DEBUG   :     x16 0000000000000001  x17 0000000000000000  x18 0000000000000000  x19 0000007247a1d2b0
10-27 00:02:24.047  5952  5952 F DEBUG   :     x20 00000073df9a28a0  x21 00000074cf98e090  x22 0000000000000000  x23 0000000000000003
10-27 00:02:24.047  5952  5952 F DEBUG   :     x24 0000000000000000  x25 0000000000000001  x26 0000000000000000  x27 0000000000000001
10-27 00:02:24.047  5952  5952 F DEBUG   :     x28 0000000000000068  x29 0000007247a1d170
10-27 00:02:24.047  5952  5952 F DEBUG   :     lr  000000729f3a1cd8  sp  0000007247a1d130  pc  000000729f3b44a0  pst 0000000060001000
10-27 00:02:24.047  5952  5952 F DEBUG   : backtrace:
10-27 00:02:24.047  5952  5952 F DEBUG   :   NOTE: Function names and BuildId information is missing for some frames due
10-27 00:02:24.047  5952  5952 F DEBUG   :   NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
10-27 00:02:24.047  5952  5952 F DEBUG   :   NOTE: found under the lib/ directory are readable.
10-27 00:02:24.047  5952  5952 F DEBUG   :   NOTE: On this device, run setenforce 0 to make the libraries readable.
10-27 00:02:24.047  5952  5952 F DEBUG   :       #00 pc 00000000003944a0  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!7b4d3d680da059de73d7f9795dc456!428fbbc7d8!+368) (BuildId: 6ed071dcc5279ff9a4e9167c06e65ecf)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #01 pc 0000000000381cd4  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!f56be09eb88f86833124f1df42e945!428fbbc7d8!+4180) (BuildId: 6ed071dcc5279ff9a4e9167c06e65ecf)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #02 pc 0000000000176ad8  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!6b200851123c7898055fe62ff9f71f!428fbbc7d8!+616) (BuildId: 6ed071dcc5279ff9a4e9167c06e65ecf)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #03 pc 000000000016e710  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!77df12deb6a622478efa8fb9929034!428fbbc7d8!+376) (BuildId: 6ed071dcc5279ff9a4e9167c06e65ecf)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #04 pc 000000000000b380  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/vbo.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #05 pc 0000000000014b38  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #06 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #07 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #08 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #09 pc 00000000000151c4  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #10 pc 0000000000016a04  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #11 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #12 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #13 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #14 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #15 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #16 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #17 pc 0000000000015270  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #18 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #19 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #20 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #21 pc 00000000000151c4  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #22 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #23 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #24 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #25 pc 00000000000151c4  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #26 pc 0000000000008ca8  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #27 pc 000000000001267c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #28 pc 0000000000011ebc  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #29 pc 00000000000151c4  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #30 pc 0000000000016a04  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #31 pc 000000000002084c  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #32 pc 0000000000162c08  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #33 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #34 pc 0000000000228ee8  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8728)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #35 pc 000000000015a564  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #36 pc 000000000015c79c  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #37 pc 0000000000022634  /data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/_event.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #38 pc 0000000000162818  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #39 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #40 pc 0000000000228ee8  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8728)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #41 pc 000000000015a564  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #42 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #43 pc 0000000000228ee8  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8728)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #44 pc 000000000015a564  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #45 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #46 pc 0000000000228ee8  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8728)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #47 pc 000000000015a564  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #48 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #49 pc 000000000022a064  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+13204)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #50 pc 000000000015a564  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #51 pc 000000000022bd78  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #52 pc 0000000000228ee8  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8728)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #53 pc 000000000022cc34  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so
10-27 00:02:24.047  5952  5952 F DEBUG   :       #54 pc 0000000000226bfc  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (PyEval_EvalCode+80)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #55 pc 000000000026a048  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libpython3.9.so (PyRun_SimpleFileExFlags+1180)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #56 pc 00000000000026dc  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libmain.so (SDL_main+2664) (BuildId: c064e0a309a70d5e38a139daeb49e3baeec1dad1)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #57 pc 000000000009b2c0  /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/lib/arm64/libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+592) (BuildId: 296952d7abc2adedc741bdef1d70444e794eb46e)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #58 pc 0000000000440554  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #59 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #60 pc 000000000000bdd6  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~ojEVlu5iTsn48s2LW2jhWQ==/org.test.myapp-z6ZVshXNVN4jz3LHE_l88w==/base.apk!classes3.dex] (org.libsdl.app.SDLMain.run+114)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #61 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #62 pc 00000000000f6740  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #63 pc 0000000000436b6c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #64 pc 0000000000468938  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #65 pc 0000000000468620  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+388) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #66 pc 0000000000618040  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1668) (BuildId: 56e704c544e6c624201be2ab4933e853)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #67 pc 00000000000b6974  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 37a328c30fb8c595fc3ebc7c80be6ac1)
10-27 00:02:24.047  5952  5952 F DEBUG   :       #68 pc 0000000000053210  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 37a328c30fb8c595fc3ebc7c80be6ac1)
10-27 00:02:24.060   872   872 E tombstoned: Tombstone written to: tombstone_24
10-27 00:02:24.064  1855  5955 W ActivityTaskManager:   Force finishing activity org.test.myapp/org.kivy.android.PythonActivity`

This **Cause: null pointer dereference** seems to me that some library uploaded on android has some error in the building/linking

Marco M.

**Comment by HeaTTheatR** [comment]
Not related to the KivyMD library.

**Comment by ElMastro** [comment]
I apologize.

Have a good day,
Marco
________________________________
Da: Yuri Ivanov ***@***.***>
Inviato: giovedì 27 ottobre 2022 03:23
A: kivymd/KivyMD ***@***.***>
Cc: ElMastro ***@***.***>; Author ***@***.***>
Oggetto: Re: [kivymd/KivyMD] MDDropDownItem open crashes on android (Issue #1400)


Not related to the KivyMD library.
