### ISSUE TITLE
MDLabel not change its color when theme is switched to "Dark" after switching screens

### ISSUE THREAD

**Issue by noob00007** [kivymd/KivyMD#1403]
### Description of the Bug

MDLabel is not changing its color when theme is switched to "Dark" after switching between different screens. It was working fine in version **1.0.2** but not working in the version **1.2.0.dev0**

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

UI = '''
MDScreenManager:

    MDScreen:

        name : "screen_1"
    
        MDBoxLayout:

            orientation : "vertical"
            spacing : "15dp"

            MDTopAppBar:
                title : "Screen 1"
                elevation : 0
                shadow_softness : 50
            
            MDLabel:
                text : "This is MDLabel"
                halign : "center"
                
            MDRaisedButton:
                text : "Change Screen"
                pos_hint : {"center_x" : 0.5}
                on_release : app.root.current = "screen_2"
                elevation : 0
                shadow_softness : 50

            MDWidget:
    
    MDScreen:

        name : "screen_2"

        MDBoxLayout:
            orientation : "vertical"

            MDTopAppBar:
                title : "Screen 2"
                left_action_items : [["arrow-left", lambda x : app.callback_return_home()]]
                elevation : 0
                shadow_softness : 50
        
            MDLabel:
                text : "This is MDLabel"
                halign : "center"
            
            MDRaisedButton:
                text : "Change Theme"
                pos_hint : {"center_x" : 0.5}
                on_release : app.callback_change_theme()
                elevation : 0
                shadow_softness : 50
            
            MDWidget:    
'''

class MyApp(MDApp):

    def callback_change_theme(self):
        if self.theme_cls.theme_style == "Light":
            self.theme_cls.theme_style = "Dark"
        else:
            self.theme_cls.theme_style = "Light"
    
    def callback_return_home(self):
        self.root.current = "screen_1"
    
    def build(self):
        app = Builder.load_string(UI)
        return app
    
root = MyApp()

if __name__ == "__main__":
    root.run()
```

### Screenshots

![1](https://user-images.githubusercontent.com/116895016/198844331-ccbe4400-1de6-4ee7-8d9a-edb9a01bce92.PNG)
![2](https://user-images.githubusercontent.com/116895016/198844338-0af7d78b-3331-48b5-a16b-37e59bac9cb8.PNG)
![3](https://user-images.githubusercontent.com/116895016/198844344-15eca049-4290-45d2-af4c-1175f41c486f.PNG)
![4](https://user-images.githubusercontent.com/116895016/198844349-a0b648c2-0559-4b71-811c-0ba70fdb3470.PNG)

https://user-images.githubusercontent.com/116895016/198844751-b9c8786e-9ed1-4f33-ab48-a8f8b30d6100.mp4

### Versions

* OS: Windows 8
* Python: 3.8.10
* Kivy: 2.1.0
* KivyMD: 1.2.0.dev0

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1401#ref-commit-3dc7d1d

**Comment by noob00007** [comment]
@HeaTTheatR This bug is there in the latest commit.

**Comment by noob00007** [comment]
Tried it, but still it's not working!

**Comment by HeaTTheatR** [comment]
@noob00007 It works.

**Comment by HeaTTheatR** [comment]
@noob00007 

https://user-images.githubusercontent.com/16930280/202852510-62651acd-b950-4084-8c0e-bec1517bc5fd.mov

**Comment by HeaTTheatR** [comment]
@noob00007 Update KivyMD library from master branch.

**Comment by noob00007** [comment]
@HeaTTheatR Ya, I updated it, but it's not working. Can you please tell the exact terminal command which I have to run to update it?

**Comment by HeaTTheatR** [comment]
@noob00007 You haven't updated the KivyMD library.

**Comment by noob00007** [comment]
@HeaTTheatR Ok, please tell me, how to update it?

**Comment by HeaTTheatR** [comment]
@noob00007 Please solve the problems with your virtual environments....

**Comment by noob00007** [comment]
@HeaTTheatR Oh, is it some problem with my virtual env?

**Comment by HeaTTheatR** [comment]
@noob00007 We are currently writing tests for the KivyMD library. And the test on this issue has been successfully passed.

**Comment by noob00007** [comment]
@HeaTTheatR Ya, it's working, now.

But, there are lot more issues, I will raise them, when I will get time. Thanks!
