### ISSUE TITLE
Slow UI and Scroll Delay

### ISSUE THREAD

**Issue by Chitkaran** [kivymd/KivyMD#141]
#### Description of the Bug

I've created an app using KivyMD and build it using buildozer. The following have a noticeable delay and make the overall user experience bad.
1. UI
2. Widget Scroll
3. Animations (bottom menu, floatmenu etc)
4. Screen Transitions
5. Text Scroll

Is this a known bug or am I not doing something incorrect ?

**Comment by HeaTTheatR** [comment]
KivyMD does not have a Scroll widget - all you do is Kivy. Give a video of your application where your problem is visible.

**Comment by Chitkaran** [comment]
Hi,

**Comment by Chitkaran** [comment]
h

**Comment by Chitkaran** [comment]
Sure, here's the video which shows the problem. 
https://photos.app.goo.gl/TNAkAF6hzfQxpVVx7

Please let me know why there's lagging in the app usage

thanks in advance

**Comment by Chitkaran** [comment]
Hi Buddy,

Did you get a chance to look at this one ?

**Comment by HeaTTheatR** [comment]
@Chitkaran Everything works fine on my phone and I don’t see any brakes - https://drive.google.com/open?id=11sEsHdi8LBM7bsVJqQyUM_v1KHt1dPmw

**Comment by Chitkaran** [comment]
The lagging is evident in the video as you would have seen.

Could you guide me how to remove it ?

**Comment by Chitkaran** [comment]
How did you build the APK ?
I mean could you share the buildozer spec file - may be I'm not putting something correct there.

**Comment by HeaTTheatR** [comment]
@Chitkaran 
https://github.com/HeaTTheatR/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec
Unlikely. Most likely the matter is in your device.
