### ISSUE TITLE
MDTextField gets text color to black when disabled using dark theme (almost invisible)

### ISSUE THREAD

**Issue by magowiz** [kivymd/KivyMD#1410]
### Description of the Bug

When disabling MDTextField using disabled property, via kv language, if the theme style is Dark, the text color of the content becomes black, almost invisible.

#### workaround
I was able to workaround setting explicitly `disabled_foreground_color` inside a loop in `on_kv_post` method:
```python
# list of ids of textfield widgets
self.list_of_widgets = ['currency_pref', 'temperature_pref',
                                   'pressure_pref', 'wind_pref']

# for each one set disabled_foreground_color to gray (visible in dark theme)
for wid_id in self.list_of_widgets:
           self.ids.get(wid_id).disabled_foreground_color = 'gray'
```
### Code and Logs (Testcase that reproduces the issue)

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
from kivy.lang import Builder

KV = """
#:import get_color_from_hex kivy.utils.get_color_from_hex
Screen:
    MDTextField:
        text: 'hello!'
        disabled: True
"""

class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Red"
        screen = Builder.load_string(KV)
        return screen

MainApp().run()
```
### Screenshots

https://paste.pics/461d1b574bb5572a5c081d84151606d7

### Versions

* OS: Ubuntu Linux 22.10
* Python: 3.10.7
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
Try use KivyMD library from master branch.

**Comment by magowiz** [comment]
Hi @HeaTTheatR,
I tried using master branch creating a new venv and installing kivymd using:
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

like described on project README.md
anyway using the same example provided by me in this issue I'm still facing the same problem.

**Comment by HeaTTheatR** [comment]
@magowiz This problem has been fixed in the master version of the library.

**Comment by HeaTTheatR** [comment]
@magowiz Or attach a minimal sample code that reproduces your problem.

**Comment by magowiz** [comment]
@HeaTTheatR I tried like the master version, and I get, with same code I provided above, the same exactly problem you can see also in mine linked screenshot. The minimal sample code is just on first message of this bug report, in the section "Code and Logs (Testcase that reproduces the issue)",  Did you try it? Maybe simply I didn't explain well the issue.

**Comment by HeaTTheatR** [comment]
@magowiz This is not a minimal code example.

**Comment by HeaTTheatR** [comment]
@magowiz https://discord.com/channels/566880874789076992/618108815774056488/816265169880875018

**Comment by magowiz** [comment]
ok @HeaTTheatR, I understood, thanks for clarifying what you mean with minimal code example, I removed all parts that are not needed to reproduce the issue, also with this code the problem persists
```python
from kivymd.app import MDApp
from kivy.lang import Builder

KV = """
MDTextField:
   text: 'hello!'
   disabled: True
"""

class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        textfield = Builder.load_string(KV)
        return textfield

MainApp().run()
```
