### ISSUE TITLE
Issue with Elevation and ScreenTransition

### ISSUE THREAD

**Issue by Ziboo** [kivymd/KivyMD#1411]
I'm having an issue with elevation when transitioning screen.
It doesn't refresh or stays in the background:

How to repro:

Add a screen with an elevated widget and use the MDScreenManager to switch between screen:

`
<HomeScreenView>

    MDScrollView:
        MDBoxLayout:
            padding: 0, 120
            #size_hint_y: None
            halign: "center"
            height: self.minimum_height
            adaptive_height: True
            orientation: 'vertical'

            
            MDCard:
                orientation: "vertical"
                #adaptive_: True
                size_hint: .9, None
                elevation: 2
                #size: "280dp", "180dp"
                radius: 12
                pos_hint: {"center_x": .5, "center_y": .5}
                

                MDLabel:
                    text: "Welcome !"
                    size_hint_y: None
                    halign: "center"
`

Video:

https://user-images.githubusercontent.com/3506180/200913690-4fb8631b-8bbe-4b05-8fe1-5fd8ebc68922.mp4

Thank you very much

**Comment by OJtheDJ** [comment]
Hi, I have the same issue in version 1.2.0 master # 939ece4 from 28 Oct 2022. There were no issues in version 104.2. 

The issue only occurs after the first screen switch. It looks like the shadow of MDRaisedButton stays in place (first screenshot) while the label itself is scrolling. 

If you uncomment the line 
`transition: NoTransition()`
in my example below, the shadow disappears (second screenshot). Then you have to scroll to the top of the MDList to make it reappear. But the shadow will again stay in place when scrolling down.


working example below:

```
from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.metrics import dp
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.properties import ObjectProperty
from kivy.clock import Clock
from kivymd.uix.button import MDRaisedButton

root_kv = """
#:import NoTransition kivy.uix.screenmanager.NoTransition
MyClass:
    mylist: mylist
    screen_m: screen_m
    orientation: 'vertical'
    spacing: '20dp'
    MDBoxLayout:
        adaptive_height: True
        MDRaisedButton:
            text: 'to screen_1'
            on_press: root.screen_m.current = 'screen_1'
        MDRaisedButton:
            text: 'to screen_2'
            on_press: root.screen_m.current = 'screen_2'
        
        
    MDBoxLayout:
        ScreenManager:
            id: screen_m
            transition: NoTransition()
            MDScreen:
                name: 'screen_1'
                MDBoxLayout:
                    ScrollView:
                        MDList:
                            id: mylist
                            spacing: '10dp'
                            
            MDScreen:
                name: 'screen_2'
    
"""

class MyClass(MDBoxLayout):

    mylist = ObjectProperty(None)
    screen_m = ObjectProperty(None)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.app = MainApp.get_running_app()
        Clock.schedule_once(self.create_widgets)

    def create_widgets(self, *args):
        for i in range(20):
            btn_text = (20-i) * 'A'
            btn = MDRaisedButton(text=btn_text, on_press=self.reload_screen)
            self.mylist.add_widget(btn)

    def reload_screen(self, *args):
        self.remove_child_widgets(self.mylist)
        self.create_widgets()

    def remove_child_widgets(self, path_to_parent):
        '''Remove all children widgets - path_to_parent is id of parent'''
        while path_to_parent.children:
            path_to_parent.remove_widget(path_to_parent.children[0])


class MainApp(MDApp):

    def __init__(self, **kwargs):
        self.title = "My Material Application"
        super().__init__(**kwargs)

    def build(self):
        self.theme_cls.theme_style = 'Light'
        self.theme_cls.primary_palette = "Orange"
        self.theme_cls.accent_palette = 'LightGreen'
        self.root = Builder.load_string(root_kv)

if __name__ == "__main__":
    MainApp().run()
```

![Elevation_Behaviour_Bug](https://user-images.githubusercontent.com/99122639/201515331-e2da9f80-73d9-498b-ba02-932a9c758c31.PNG)

![Elevation_Behaviour_Bug_2](https://user-images.githubusercontent.com/99122639/201515593-3d3930df-80d0-4a32-9012-87a2ad9773ee.PNG)

**Comment by blokkies48** [comment]
Hi, I seem to have the same or similar issue. Or am I doing something wrong?
First I have a FAB that goes to another page, but when I go back its shadow goes off till I interact again. 
My second point is when activating the pop up it isn't in the dark theme. And when pressing the FAB to go to the other page, the page is also back into the light theme.

![kivyMD_fab_shadow](https://user-images.githubusercontent.com/66180897/202686456-4eb89f95-f8fb-4d90-8e0c-980bce0b02e0.png)
![kivyMD_theme_color](https://user-images.githubusercontent.com/66180897/202686468-d5999728-1076-4323-894d-d81a1167f0ff.png)

**Comment by RanjithKumarS2002** [comment]
Yes, I'm also facing the same issue. With FAB. But this issue is not there with version 1.0.2, it is only on 1.1.1

**Comment by blokkies48** [comment]
Hi yes. I went hack to version 1.0.2

**Comment by JGAguado** [comment]
Having the same issue. I posted on https://stackoverflow.com/questions/74400494/kivymd-when-switching-between-screens-the-palette-and-the-elevation-gets-lost without any solution yet :(

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1352
