### ISSUE TITLE
Mdtopappbar crashes packaged app

### ISSUE THREAD

**Issue by Ahd999** [kivymd/KivyMD#1416]
Hi there,
I am having issue with the mdtopappbar,i encounter this error after I package the py file to apk, the topbar works just fine when a I run it on my pc but after packing, when I start the apk it just shows me a black screen for 1 second and crashes after showing the splash screen, this behaviour is only experienced when I use any of the toolbars be top or bottom.
Thanks.

Os:Win11
Py - - ver: python37

**Comment by xuniuer** [comment]
Can use logcat to see what happened.

**Comment by Ahd999** [comment]
> Can use logcat to see what happened.
Sure, will post once home

**Comment by Ahd999** [comment]
[logcat.txt](https://github.com/kivymd/KivyMD/files/10022718/logcat.txt)

**Comment by Ahd999** [comment]
This logcat is catched through adb logcat | findstr /c:"I python"  since I ve packaged it using colab I am unable to use buildozer logcat

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1352

**Comment by Ahd999** [comment]
Thank you so much for helping out, i will recompile the apk
