### ISSUE TITLE
Speeddial button position incorrect

### ISSUE THREAD

**Issue by LazzaAU** [kivymd/KivyMD#1419]
The bug is in version 1.1.1 of kivyMD and is related to the positioning of the root button of a **MDFloatingActionButtonSpeedDial:** button.

I've noticed that if you use more than  1 **MDBottomNavigationItem** the root speedDial button shifts to the left of the screen and when clicked the stack opens to the right. Expected behaviour is the root button sits in the right bottom corner and stack opens from right bottom corner. 

In the below code, if you comment out 
```
 MDBottomNavigationItem:
    id: settings
```
so only 1 navigationItem is present then the problem seems to correct it self.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDBoxLayout:
        orientation: 'vertical'

        MDBottomNavigation:
        
            MDBottomNavigationItem:
                name: 'settings'
                icon: 'cog'

            MDBottomNavigationItem:
                name: 'map_screen'
                icon: 'map'                        

                MDFloatingActionButtonSpeedDial:
                    id: speed_dial
                    data: {'LogOut': 'logout', "re-center":'target', "Help": "help"}
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Linux and android
* Python: 
* Kivy: 
* KivyMD: yes

**Comment by LazzaAU** [comment]
just in case it helps with locating the bug....

in buttons.py

```
def set_pos_root_button(*args):
            if self.anchor == "right":
                instance_floating_root_button.y = dp(20)
                instance_floating_root_button.x = self.parent.width - (
                            dp(56) + dp(20)
                            ```
For me, self.parent.width on start up is always smaller number than it should be. (a value of 100 in my case, when a value of 420 is expected) this pushes the root button to the left of the screen. 
Rotating the screen to landscape then back to portrait fixes the speed dial button position. 

I don't know how to fix that cause i'm not a guru :) but that's my observations so far. Hope that helps

**Comment by LazzaAU** [comment]
update:

```
def set_pos_root_button(*args):
            if self.anchor == "right":
                instance_floating_root_button.y = dp(20)
                instance_floating_root_button.x = self.parent.width - (
                    dp(56) + dp(20)
                )
        Clock.schedule_once(set_pos_root_button)
```
Further update in case it helps diagnosis. To me , it seems ```Clock.schedule_once(set_pos_root_button)``` is run too soon after start up and by then it hasn't had time to evaluate its true parent width ( or something like that ) 

I've simply changed ```Clock.schedule_once(set_pos_root_button)``` to ```Clock.schedule_once(set_pos_root_button, 8)``` and for me it puts the button on the right bottom side of the screen as expected, albeit, 8 seconds later but any less than that and it's too soon for my screen anyway.

**Comment by mrTokar** [comment]
KivyMD: 1.1.1

I also encountered this problem, but when switching between screens and using multithreading. I solved the problem a little differently, without resorting to editing the module code.

The **MDFloatingActionButtonSpeedDial** (widget in my code has id `speed_dial_btn`) was on screen B, so I overridden the `on_pre_enter `method on that screen.

```python
def on_pre_enter(self, *args):
        """This function corrects the display
        of the `speed_dial_btn` button. After the first call,
        it redefines itself to an empty function."""

        self.ids.speed_dial_btn._update_pos_buttons(
            self.ids.speed_dial_btn,
            self.width,
            self.height
        ) 
        self.on_pre_enter = lambda *args: None
```
In fact, there is no need to pass any arguments when calling the `_update_pos_buttons` function. Because they are not used in execution. So you can even do it like this:
```python
def on_pre_enter(self, *args):
        self.ids.speed_dial_btn._update_pos_buttons(None, None, None)
        self.on_pre_enter = lambda *args: None
```

**Comment by b3y0ndb3z0tch** [comment]
Thank you for this information!

Can anyone show a posted code of the speed dial and running different functions from those speed dials.  Function called from the button in the .kv file, and called into python .py file.  I keep seeing different ways, and none are working for me, as I am using a screen manager and I cannot find the proper way to link the *app.myfunction* or what the call is.

**Comment by mrTokar** [comment]
```python
class MySpeedDial(MDActionSpeedDialButton):
    def __init__(self, *args, **kwargs):
        self.data = {
            "Button1": ["plus", "on_release", self.f1],
            "Button2": ["arrow-left", "on_release", self.f2] ,
        }
        super().__init__()

    def f1(self, called):
        pass

    def f2(self, called):
        pass
```

**Comment by b3y0ndb3z0tch** [comment]
Hello!  Thanks!!!
do you have any projects you can share?
I am doing a screenmanager project with multiple screens.  I am curious on where to place this class.  Also, how to add this class into the .kv file.  I have something looking like this:


<TestingScreens>:
    name: "testing_screens"
    MDScreen:

        MDScreenManager:
            id: testingscreens
            transition: NoTransition()
            TestingScreen1:
                name: "testing_screen_1"
            TestingScreen2:
                name: "testing_screen_2"
            UserProfile:
                name: "user_profile"
                ProfileDialButton:
                    id: profile_dialfrom kivy.properties import StringProperty, ObjectProperty
from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial

from kivymd.uix.label import MDLabel, MDIcon
from kivymd.uix.screen import MDScreen
from kivymd.uix.selectioncontrol import MDSwitch
from kivymd.uix.textfield import MDTextField


class TestingScreens(MDScreen):
    pass

class ProfileDialButton(MDFloatingActionButtonSpeedDial):
    app_inst = MDApp.get_running_app()
    data = {'Position': ['language-python',"on_press", lambda x: print("position was pressed")], 'PHP': 'language-php','C++': 'language-cpp',}
    root_button_anim = True
    hint_animation = True
    #bg_hint_color = app_inst.BACKGROUNDCOLOR2
    #anchor: "right"
    icon = "hockey-sticks"
    type = "small"
    #callback: self.trying_action2
But that doesn't work properly.   On Thursday, August 17, 2023 at 11:41:33 PM PDT, mrTokar ***@***.***> wrote:  
 
 

class MySpeedDial(MDActionSpeedDialButton):
    def __init__(self, *args, **kwargs):
        self.data = {
            "Button1": ["plus", "on_release", self.f1],
            "Button2": ["arrow-left", "on_release", self.f2] ,
        }
        super().__init__()

    def f1(self, called):
        pass

    def f2(self, called):
        pass

**Comment by b3y0ndb3z0tch** [comment]
I have tried to add the lambda to call a function of self.trying_action and defining that under the class itself, to no success.  I will be trying your coding now and getting back to you.  thank you.    On Friday, August 18, 2023 at 09:59:13 PM PDT, adam williams ***@***.***> wrote:  
 
 Hello!  Thanks!!!
do you have any projects you can share?
I am doing a screenmanager project with multiple screens.  I am curious on where to place this class.  Also, how to add this class into the .kv file.  I have something looking like this:


<TestingScreens>:
    name: "testing_screens"
    MDScreen:

        MDScreenManager:
            id: testingscreens
            transition: NoTransition()
            TestingScreen1:
                name: "testing_screen_1"
            TestingScreen2:
                name: "testing_screen_2"
            UserProfile:
                name: "user_profile"
                ProfileDialButton:
                    id: profile_dialfrom kivy.properties import StringProperty, ObjectProperty
from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial

from kivymd.uix.label import MDLabel, MDIcon
from kivymd.uix.screen import MDScreen
from kivymd.uix.selectioncontrol import MDSwitch
from kivymd.uix.textfield import MDTextField


class TestingScreens(MDScreen):
    pass

class ProfileDialButton(MDFloatingActionButtonSpeedDial):
    app_inst = MDApp.get_running_app()
    data = {'Position': ['language-python',"on_press", lambda x: print("position was pressed")], 'PHP': 'language-php','C++': 'language-cpp',}
    root_button_anim = True
    hint_animation = True
    #bg_hint_color = app_inst.BACKGROUNDCOLOR2
    #anchor: "right"
    icon = "hockey-sticks"
    type = "small"
    #callback: self.trying_action2
But that doesn't work properly.   On Thursday, August 17, 2023 at 11:41:33 PM PDT, mrTokar ***@***.***> wrote:  
 
 

class MySpeedDial(MDActionSpeedDialButton):
    def __init__(self, *args, **kwargs):
        self.data = {
            "Button1": ["plus", "on_release", self.f1],
            "Button2": ["arrow-left", "on_release", self.f2] ,
        }
        super().__init__()

    def f1(self, called):
        pass

    def f2(self, called):
        pass

**Comment by b3y0ndb3z0tch** [comment]
I actually can't get your code to work either, and with the class just being defined in the .py file, I cannot get the actiondial to even be displayed.
    On Friday, August 18, 2023 at 10:01:23 PM PDT, adam williams ***@***.***> wrote:  
 
  I have tried to add the lambda to call a function of self.trying_action and defining that under the class itself, to no success.  I will be trying your coding now and getting back to you.  thank you.    On Friday, August 18, 2023 at 09:59:13 PM PDT, adam williams ***@***.***> wrote:  
 
 Hello!  Thanks!!!
do you have any projects you can share?
I am doing a screenmanager project with multiple screens.  I am curious on where to place this class.  Also, how to add this class into the .kv file.  I have something looking like this:


<TestingScreens>:
    name: "testing_screens"
    MDScreen:

        MDScreenManager:
            id: testingscreens
            transition: NoTransition()
            TestingScreen1:
                name: "testing_screen_1"
            TestingScreen2:
                name: "testing_screen_2"
            UserProfile:
                name: "user_profile"
                ProfileDialButton:
                    id: profile_dialfrom kivy.properties import StringProperty, ObjectProperty
from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial

from kivymd.uix.label import MDLabel, MDIcon
from kivymd.uix.screen import MDScreen
from kivymd.uix.selectioncontrol import MDSwitch
from kivymd.uix.textfield import MDTextField


class TestingScreens(MDScreen):
    pass

class ProfileDialButton(MDFloatingActionButtonSpeedDial):
    app_inst = MDApp.get_running_app()
    data = {'Position': ['language-python',"on_press", lambda x: print("position was pressed")], 'PHP': 'language-php','C++': 'language-cpp',}
    root_button_anim = True
    hint_animation = True
    #bg_hint_color = app_inst.BACKGROUNDCOLOR2
    #anchor: "right"
    icon = "hockey-sticks"
    type = "small"
    #callback: self.trying_action2
But that doesn't work properly.   On Thursday, August 17, 2023 at 11:41:33 PM PDT, mrTokar ***@***.***> wrote:  
 
 

class MySpeedDial(MDActionSpeedDialButton):
    def __init__(self, *args, **kwargs):
        self.data = {
            "Button1": ["plus", "on_release", self.f1],
            "Button2": ["arrow-left", "on_release", self.f2] ,
        }
        super().__init__()

    def f1(self, called):
        pass

    def f2(self, called):
        pass

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
