### ISSUE TITLE
theming.py raise error: KivyMD: App object should be inherited from `kivymd.app.MDApp`

### ISSUE THREAD

**Issue by mobilEKG** [kivymd/KivyMD#142]
#### Description of the Bug
 Traceback (most recent call last):
   File "main.py", line 112, in <module>
     main()
   File "main.py", line 98, in main
     icon_background=os.path.join('data', 'images', 'icon.png')
   File "C:\project\Windows\python\KivyMD\libs/applibs\bugreporter\bugreporter.py", line 41, in __init__
     super(BugReporter, self).__init__(**kwargs)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
     rule_children=rule_children)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\lang\builder.py", line 538, in apply
     rule_children=rule_children)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "C:\dev\Anaconda\v3\lib\site-packages\kivy\lang\builder.py", line 654, in _apply_rule
     child = cls(__no_builder=True)
   File "C:\project\Windows\python\KivyMD\libs/applibs\kivymd\uix\button.py", line 730, in __init__
     super().__init__(**kwargs)
   File "C:\project\Windows\python\KivyMD\libs/applibs\kivymd\uix\button.py", line 637, in __init__
     super().__init__(**kwargs)
   File "C:\project\Windows\python\KivyMD\libs/applibs\kivymd\theming.py", line 373, in __init__
     "KivyMD: App object should be inherited from "
 ValueError: KivyMD: App object should be inherited from `kivymd.app.MDApp`. See https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#api-breaking-changes
### Versions
* OS: Windows 10
* Python: 3.7.4
* Kivy: 
* KivyMD:

**Comment by ArtemSBulgakov** [comment]
Use
```python
from kivymd.app import MDApp

class MainApp(MDApp):
    def __init__(**kwargs):
        self.theme_cls.theme_style = "Dark"
        super().__init__(**kwargs)
```
Instead of
```python
from kivy.app import App
from kivymd.theming import ThemeManager

class MainApp(App):
    theme_cls = ThemeManager()
    theme_cls.theme_style = "Dark"
```
See https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#api-breaking-changes

**Comment by ssgray** [comment]
I did import MDApp but im getting this error.
![code](https://user-images.githubusercontent.com/46230114/70698525-a5fa3600-1d02-11ea-9a45-479d3cee6f0a.PNG)
![logerror](https://user-images.githubusercontent.com/46230114/70698527-a692cc80-1d02-11ea-92e2-76a86d6249f0.PNG)
Do let me know if I'm not clear enough. Thanks

**Comment by ArtemSBulgakov** [comment]
@seangray123 There is an error in your code
```python
    def __init__(self, **kwargs):
```
Also you need to remove the line
```python
    theme_cls = ...
```

**Comment by ssgray** [comment]
The MDExpansionPanel isn't working properly. The contents of the expansion panel are not resized. Any advice?

    from kivy.lang import Builder
    from kivy.uix.screenmanager import ScreenManager, Screen
    from kivymd.app import MDApp
    from kivy.properties import (StringProperty, NumericProperty, ObjectProperty,
                                 ListProperty, DictProperty, BooleanProperty)
    from kivy.uix.label import Label
    from kivymd.uix.expansionpanel import MDExpansionPanel
    from kivy.uix.boxlayout import BoxLayout
    from kivymd.uix.list import TwoLineIconListItem
    from kivy.metrics import dp


    class MainScreen(Screen):
        pass

    class FriendExpand(MDExpansionPanel):
        friend_id = StringProperty()

        def __init__(self,**kwargs):
            super(FriendExpand, self).__init__(**kwargs)
            self.title = "1"
            self.icon = "data/logo/kivy-icon-128.png"

            # Add the friend's ID
            friend_label = TwoLineIconListItem(text = "IGN", secondary_text = kwargs['friend_id'])
            self.content = ContentForAnimCard(orientation = "vertical", padding = dp(10), spacing = dp(10), size_hint_y = None, height = self.minimum_height)
            self.content.add_widget(friend_label)

            # Add the friend's score
            score_label = TwoLineIconListItem(text = "Score", secondary_text = "crazy")
            self.content.add_widget(score_label)

    class ContentForAnimCard(BoxLayout):
        pass

    class MyScreenManager(ScreenManager):
        pass

    main_widget_kv = ('''
    #: import ScrollEffect kivy.effects.scroll.ScrollEffect
    #: import FadeTransition kivy.uix.screenmanager.FadeTransition

    MyScreenManager:
        MainScreen:
            id: main

    <MainScreen>:
        name: "friend"
        BoxLayout:
            pos_hint: {"top": 1.1}
            size_hint_y: 0.25
            canvas.before:
                Color:
                    rgba: (1,0,0,1)
                Rectangle:
                    size: self.size
                    pos: self.pos
        BoxLayout:
            pos_hint: {"x": 0.1, "top": 1.1}
            size_hint: 0.8,0.2
            MDLabel:
                font_style: 'H5'
                theme_text_color: 'Primary'
                text: "FRIENDS"
                theme_text_color: 'Custom'
                text_color: (1,1,1,1)
                size_hint_y: None
                height: self.texture_size[1] + dp(4)
        FloatLayout:
            id: chong
            ScrollView:
                size_hint: 0.98,0.8
                pos_hint: {"center_x": 0.5, "center_y": 0.45}
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0)
                    Rectangle:
                        size: self.size
                        pos: self.pos
                GridLayout:
                    id: anim_list
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height

    ''')

    class TestApp(MDApp):
        def build(self):
            main_widget = Builder.load_string(main_widget_kv)
            return main_widget

        def on_start(self):
            friends_list_array = ["1","2","3"]
            for friend in friends_list_array:
                friend_expand = FriendExpand(friend_id = friend)
                self.root.ids['main'].ids['anim_list'].add_widget(friend_expand)

    if __name__ == '__main__':
        TestApp().run()

![image](https://user-images.githubusercontent.com/46230114/70861457-4782c100-1f69-11ea-9b33-e898704af522.png)

**Comment by ArtemSBulgakov** [comment]
@seangray123 
To get support, please ask your questions in the Discord server: https://github.com/HeaTTheatR/KivyMD#support

https://github.com/HeaTTheatR/KivyMD/blob/master/.github/CONTRIBUTING.md

If you think that it is a bug, you should open new issue.
