### ISSUE TITLE
1.1.1: from kivymd.uix.behaviors import FocusBehavior fails

### ISSUE THREAD

**Issue by cederom** [kivymd/KivyMD#1422]
### Description of the Bug

* Documentation of Focus [1] gives a code example that does not work (import error).
* If you look at `kivymd.uix.behaviors` source code [2] you will notice that `FocusBehavior` is not imported. That causes import error from the application code.

### Code and Logs

Code example comes straight from the KivyMD docs [1]:

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.behaviors import RectangularElevationBehavior, FocusBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
MDScreen:
    md_bg_color: 1, 1, 1, 1

    FocusWidget:
        size_hint: .5, .3
        pos_hint: {"center_x": .5, "center_y": .5}
        md_bg_color: app.theme_cls.bg_light

        MDLabel:
            text: "Label"
            theme_text_color: "Primary"
            pos_hint: {"center_y": .5}
            halign: "center"
'''


class FocusWidget(MDBoxLayout, RectangularElevationBehavior, FocusBehavior):
    pass


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)


Test().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

```
 Traceback (most recent call last):
   File "/XXX/kivy/examples/kivymd-focus_behavior-1.py", line 4, in <module>
     from kivymd.uix.behaviors import RectangularElevationBehavior, FocusBehavior
 ImportError: cannot import name 'FocusBehavior' from 'kivymd.uix.behaviors' (/XXX/lib/python3.9/site-packages/kivymd/uix/behaviors/__init__.py)

```

### Versions

* OS: `FreeBSD octagon 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-n253075-2b20cade1eca: Sun Nov 13 20:06:09 CET 2022     root@octagon:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64`.
* Python: `3.9.15`.
* Kivy: `2.1.0`.
* KivyMD: `1.1.1`.

### References

* [1] https://kivymd.readthedocs.io/en/1.1.1/behaviors/focus/#module-kivymd.uix.behaviors.focus_behavior
* [2] https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/behaviors/__init__.py

**Comment by cederom** [comment]
Solution proposition: https://github.com/kivymd/KivyMD/pull/1423 :-)

**Comment by cederom** [comment]
Before reviewing the proposition, it would be good to reconsider class rename to `MDFocusBehavior` as `FocusBehavior` is already part of Kivy and does something else. Here is the report: https://github.com/kivymd/KivyMD/issues/1424.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1424
