### ISSUE TITLE
MDTextField is blocking the keyboard listener for android back button

### ISSUE THREAD

**Issue by PythonLaboratory** [kivymd/KivyMD#1425]
### Description of the Bug

Back button stops working after using MDTextField on Android devices

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDTextField:
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint_x: .5
'''
class Test(MDApp):

    def build(self):
        
        return Builder.load_string(KV)

Test().run()
```

### Versions

* OS: Android 12, Ubuntu 22.04
* Python: 3.10.0
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
This has nothing to do with the KivyMD library

**Comment by PythonLaboratory** [comment]
> This has nothing to do with the KivyMD library
Where then to apply?

**Comment by Neizvestnyj** [comment]
> > This has nothing to do with the KivyMD library
> Where then to apply?
> 

https://github.com/kivy/python-for-android/issues/2423

**Comment by PythonLaboratory** [comment]
> > > This has nothing to do with the KivyMD library
> > > Where then to apply?
> 
> [kivy/python-for-android#2423](https://github.com/kivy/python-for-android/issues/2423)

I'm sorry, but I still don't understand what I need to do to fix this bug...

**Comment by PythonLaboratory** [comment]
I found a solution. I did so `requirements = python3,kivy==master,kivymd,sdl2_ttf==20.20.1,android` and `p4a.branch = develop`
