### ISSUE TITLE
MDMenu crashes on Android 11

### ISSUE THREAD

**Issue by PythonLaboratory** [kivymd/KivyMD#1429]
### Description of the Bug

When you double tap on MDLabe, the application crashes immediately after opening MDMenu.  This problem is ONLY observed on Xiaomi Redmi 9T with Android 11. On Samsung Galaxy Tab A7 Lite with Android 12 the app works PERFECTLY.  I am more than sure that the problem is either in KivyMD or in python-for-android

### Code and Logs

https://github.com/PythonLaboratory/TestMDMenu

main.py https://github.com/PythonLaboratory/TestMDMenu/blob/main/main.py

buildozer.spec https://github.com/PythonLaboratory/TestMDMenu/blob/main/buildozer.spec

Log https://github.com/PythonLaboratory/TestMDMenu/blob/main/error_log.txt

### Versions

* OS: Android 11
* Python: 10.0.0
* Kivy: 2.1.0
* KivyMD: master

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1352
