### ISSUE TITLE
switch_tab in MDTabs at start 

### ISSUE THREAD

**Issue by Dreamer-4pda** [kivymd/KivyMD#1431]
tabs.switch_tab not work properly when i try to switch tab at app start.
Tab is switching, but tab list not scroll to active tab:
![image](https://user-images.githubusercontent.com/4630430/207608239-f3023290-fe03-4f5f-83a5-81c08cf0d8f2.png)
Code sample:
```
def on_start(self):
    for i in range(20):
        self.root.ids.tabs.add_widget(Tab(title=f"Tab {i}"))
    self.root.ids.tabs.switch_tab('Tab 8')
```

**Comment by HeaTTheatR** [comment]
@Dreamer-4pda 

```python
        Clock.schedule_once(
            lambda x: self.root.ids.tabs.switch_tab("Tab 8")
        )
```
