### ISSUE TITLE
Shadow still now fixed in 1.1.1 when config.ini has rotation set

### ISSUE THREAD

**Issue by Kasperror** [kivymd/KivyMD#1432]
Using any element with elevation when kivy's config file _config.ini_ has rotation set to 270 or 90 degrees leads to shadow being completely misplaced from its "parent"

To reproduce set `rotation` under `[graphics]` section to 270
then run app with element which has `ElevationBehavior` and animates on screen - for example a `Snackbar`

Result:
![shadow_error](https://user-images.githubusercontent.com/47153317/207951433-3c1dea75-6bbe-496f-9d67-b76afd5d8333.png)

### Versions

* OS: Windows 10 64-bit / Pi OS bullseye 64-bit
* Python: 3.10.8
* Kivy: 2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
All versions of the KivyMD library, with the exception of the master version, are broken.
https://github.com/kivymd/KivyMD/issues/1352
