### ISSUE TITLE
MDBottomSheet doesn't animate properly

### ISSUE THREAD

**Issue by woxy005** [kivymd/KivyMD#1434]
### Description of the Bug

There is a bug in the method resize_content_layout of MDBottomSheet.
If animation, Animation(height=height).start(_layout).
But the correct argument is "layout", not "_layout".

### Versions

* KivyMD:  1.1.1

**Comment by HeaTTheatR** [comment]
At the moment, the MDBottomSheet class is completely in refactoring. So I'm closing this problem.
