### ISSUE TITLE
Cannot set font_size when instantiating MDLabel

### ISSUE THREAD

**Issue by PythonLaboratory** [kivymd/KivyMD#1435]
### Description of the Bug

When I try to set font_size when instantiating MDLabel class nothing happens (font size doesn't change)

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.label import MDLabel


class Test(MDApp):
    def build(self):
        
        label = MDLabel(text="MDLabel", font_size=40.0)
        
        return label


Test().run()
```

I see
![Снимок экрана от 2022-12-19 22-04-45](https://user-images.githubusercontent.com/119929553/208501938-6ea2dbb6-3377-45ce-9611-e42972635c02.png)

**But when I write like this...**
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.label import MDLabel


class Test(MDApp):
    def build(self):
        
        label = MDLabel(text="MDLabel")
        label.font_size = 40.0
        
        return label


Test().run()
```
...everything works!

![Снимок экрана от 2022-12-19 22-05-04](https://user-images.githubusercontent.com/119929553/208502346-460f24c6-53f0-43ea-b74c-dcc700e0faca.png)

### Versions

* OS: Ubuntu 22.p4
* Python: 3.10.6
* Kivy: master
* KivyMD: master

**Comment by PythonLaboratory** [comment]
@HeaTTheatR, please reopen the issue. Again the same problem, but only with `font_style`

**Comment by HeaTTheatR** [comment]
@PythonLaboratory I don't see any problems.

**Comment by PythonLaboratory** [comment]
@HeaTTheatR, when I write 
```
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.label import MDLabel


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        return (
            MDScreen(
                MDLabel(
                    text="MDLabel",
                    font_style="H1"
                )
            )
        )


Test().run()
```

I see

![изображение](https://user-images.githubusercontent.com/119929553/210804683-18d94519-b873-49fc-9f44-e7b8eb20562b.png)

`font_style` don't work
