### ISSUE TITLE
Cards elevation disappear when using ScreenManager after the first appearence

### ISSUE THREAD

**Issue by adirmorgan** [kivymd/KivyMD#1439]
When using ScreenManager (or MDScreenManager) with MDCard in the screen, cards elevation disappear after the screen first appearence (when everything still looks OK).

* When debugging it, it seems like the _elevation field of the card is still set on the correct value
* this happens to *all* cards on screen  

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager
from kivymd.uix.screen import MDScreen

class Screen1(MDScreen):
    pass

class Screen2(MDScreen):
    pass

sm = ScreenManager()
sm.add_widget(Screen1(name='screen1'))
sm.add_widget(Screen2(name='screen2'))

kv = """
#:kivy 2.1.0

ScreenManager:
    Screen1:
    Screen2:

<Screen1>:
    name:'screen1'
    MDCard:
        elevation: 10
        orientation: 'vertical'
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint: 0.3, 0.3
        md_bg_color: app.theme_cls.bg_darkest
        MDLabel:
            text: 'Screen 1'
            halign: 'center'
            pos_hint: {'center_x': 0.5,'center_y':0.8}


        MDRectangleFlatButton:
            text: 'Next screen'
            pos_hint: {'center_x': 0.5,'center_y':0.2}
            on_press:
                root.manager.current ='screen2'

<Screen2>:
    name:'screen2'
    MDCard:
        elevation: 10
        orientation: 'vertical'
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint: 0.3, 0.3
        md_bg_color: app.theme_cls.bg_darkest
        MDLabel :
            text: 'Screen 2'
            halign: 'center'
        MDRectangleFlatButton:
            text: 'Previous screen'
            pos_hint: {'center_x': 0.5,'center_y':0.2}
            on_press:
                root.manager.current ='screen1'
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
First appearence of screen1:
![image](https://user-images.githubusercontent.com/22156741/209527053-60457372-fea8-4920-8783-fa466e1c7e71.png)

Then first appearence of screen2: 
![image](https://user-images.githubusercontent.com/22156741/209527109-99601833-925a-4f3b-acd6-d8a30c2c2f39.png)

Now back to screen1, card elevation dissapeared:
![image](https://user-images.githubusercontent.com/22156741/209527257-f88cdee4-5425-469d-b305-e3095004ffcd.png)

And also for screen2:
![image](https://user-images.githubusercontent.com/22156741/209527290-bb308655-1567-4e45-b9f0-55038e1f2fa4.png)

### Versions

* OS: Ubuntu 22.04.1 LTS
* Python: 3.10.6
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
@adirmorgan KivyMD 1.1.1 - broken. Use the KivyMD library master branch:

```
pip install https://github.com/kivy/kivy/archive/master.zip
pip install https://github.com/kivymd/KivyMD/archive/master.zip
```
