### ISSUE TITLE
Extend Button width

### ISSUE THREAD

**Issue by darpan5552** [kivymd/KivyMD#144]
#### Description of the Feature

I wanted someone to help me draw a button whose width is equal to width of window, no matter how small the button text is.
Currently, size of button depends on length of text.

**Comment by ArtemSBulgakov** [comment]
Use Discord server to get support
https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#support

Or exclude the word "help" from issue

**Comment by HeaTTheatR** [comment]
@darpan5552 The width of the button will always be equal to the width of the texture of text. Because it complies with the rules of material design.

https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/button.py#L410

**Comment by HeaTTheatR** [comment]
@darpan5552 But if you want you can increase the width of the button with `increment_width` - https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/button.py#L876

**Comment by darpan5552** [comment]
Oh yes, actually I was trying to do it with rounded flat button. So unable to do that.
Thanks for quick reply.

**Comment by ArtemSBulgakov** [comment]
@darpan5552 If you really want to use percents instead of pixels, you can set `size_hint`:
```yaml
    MDRaisedButton:
        text: "Click me!"
        size_hint: 1, 1
```
If you need to use `width` property with `size_hint_x: None`, you have to create your own Python class:
```python
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton

root_kv = """
BoxLayout:
    MDLabel:
        text: "Hello World"

    MyMDRaisedButton:
        text: "Click me!"
        size_hint: None, None
        width: dp(100)
        height: dp(200)
"""


class MyMDRaisedButton(MDRaisedButton):
    width = NumericProperty(100)  # Same as in Widget class
    height = NumericProperty(100)  # Same as in Widget class


class MainApp(MDApp):

    def build(self):
        self.root = Builder.load_string(root_kv)


if __name__ == "__main__":
    MainApp().run()
```

**Comment by HeaTTheatR** [comment]
@Mountaino Width will remain unchanged anyway

**Comment by ArtemSBulgakov** [comment]
@HeaTTheatR That's right...
@darpan5552 I found another way. Width is binded to `lbl_txt.texture_size`, you need to bind again:
```python
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton

root_kv = """
BoxLayout:
    MDLabel:
        text: "Hello World"

    MyMDRaisedButton:
        text: "Click me!"
        size_hint: None, None
        width: dp(100) + (self.ids.lbl_txt.texture_size[0] - self.ids.lbl_txt.texture_size[0])
        height: dp(200)
"""


class MyMDRaisedButton(MDRaisedButton):
    width = NumericProperty(100)  # Same as in Widget class
    height = NumericProperty(100)  # Same as in Widget class


class MainApp(MDApp):

    def build(self):
        self.root = Builder.load_string(root_kv)


if __name__ == "__main__":
    MainApp().run()
```

**Comment by tasen-sp** [comment]
> @darpan5552 If you really want to use percents instead of pixels, you can set `size_hint`:
> 
> ```yaml
>     MDRaisedButton:
>         text: "Click me!"
>         size_hint: 1, 1
> ```
> 
> If you need to use `width` property with `size_hint_x: None`, you have to create your own Python class:
> 
> ```python
> from kivy.lang import Builder
> from kivy.properties import NumericProperty
> from kivymd.app import MDApp
> from kivymd.uix.button import MDRaisedButton
> 
> root_kv = """
> BoxLayout:
>     MDLabel:
>         text: "Hello World"
> 
>     MyMDRaisedButton:
>         text: "Click me!"
>         size_hint: None, None
>         width: dp(100)
>         height: dp(200)
> """
> 
> 
> class MyMDRaisedButton(MDRaisedButton):
>     width = NumericProperty(100)  # Same as in Widget class
>     height = NumericProperty(100)  # Same as in Widget class
> 
> 
> class MainApp(MDApp):
> 
>     def build(self):
>         self.root = Builder.load_string(root_kv)
> 
> 
> if __name__ == "__main__":
>     MainApp().run()
> ```

I have done this but I can't do it in code method it doesn't do anything with size_hint

**Comment by tasen-sp** [comment]
I can't do this in code method

**Comment by tasen-sp** [comment]
Help me

**Comment by HeaTTheatR** [comment]
@tasen-sp 
```python
from kivy.lang import Builder
from kivymd.app import MDApp

root_kv = """
Screen:

    MDRaisedButton:
        text: "Click me!"
        size_hint: None, None
        width: dp(400) + (self.ids.lbl_txt.texture_size[0] - self.ids.lbl_txt.texture_size[0])
        height: dp(200)
        pos_hint: {"center_x": .5, "center_y": .5}
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(root_kv)


MainApp().run()
```

**Comment by tasen-sp** [comment]
I know that.thanks for rapid reply.but I wanted to do this in code method.it
can't access the pos_hint and md_bg_color in code method.i need it
badly.pls help me

**Comment by HeaTTheatR** [comment]
@tasen-sp https://discordapp.com/channels/566880874789076992/618108815774056488/715460114378915933

**Comment by tasen-sp** [comment]
Reply pls

**Comment by HeaTTheatR** [comment]
@tasen-sp https://discordapp.com/channels/566880874789076992/618108815774056488/715460114378915933

**Comment by tasen-sp** [comment]
I meant can I do it without builder

**Comment by tasen-sp** [comment]
Can I ?

**Comment by HeaTTheatR** [comment]
@tasen-sp https://discordapp.com/channels/566880874789076992/618108815774056488/715460114378915933

**Comment by tasen-sp** [comment]
Can you give me the code here.pls??

**Comment by tasen-sp** [comment]
Can you give me the code here.pls??

**Comment by tasen-sp** [comment]
I can't use discord

**Comment by HeaTTheatR** [comment]
@darpan5552 If you encounter an error in the code or if something could not be done, attach a minimal code that can be run without additional manipulations so that developers can look at the working script and fix it. Write also what you expected from the script and what happened as a result. No need to take screenshots on which you display your code.

**Comment by tasen-sp** [comment]
Sorry,I can't figure out how to send a code .but I'm writing the code here:
boxlayout.add_widget(MDRectangleFlatIvonButton (size_hint=(1,.1), icon='settings',text='text'))

It gives no error.everything works but the size hint of X doesn't influence the code.

**Comment by tasen-sp** [comment]
Hello.reply.anyone

**Comment by HeaTTheatR** [comment]
@tasen-sp 
```python
MDRectangleFlatIconButton(icon=`git', text='text', md_bg_color=(0, 0, 1, 1))
```

**Comment by tasen-sp** [comment]
the size_hint and  md_bg_color doesn't influence the code .what to do

**Comment by HeaTTheatR** [comment]
@tasen-sp You have already been answered about the size of the buttons.

**Comment by HeaTTheatR** [comment]
@tasen-sp `MDRectangleFlatIconButton` is a button with transparent background!

**Comment by HeaTTheatR** [comment]
@tasen-sp Read the docs - https://kivymd.readthedocs.io/en/latest/components/button/index.html

**Comment by tasen-sp** [comment]
> @tasen-sp `MDRectangleFlatIconButton` is a button with transparent background!

But md_bg_color works in builder methof

**Comment by tasen-sp** [comment]
> @tasen-sp
> 
> ```python
> from kivy.lang import Builder
> from kivymd.app import MDApp
> 
> root_kv = """
> Screen:
> 
>     MDRaisedButton:
>         text: "Click me!"
>         size_hint: None, None
>         width: dp(400) + (self.ids.lbl_txt.texture_size[0] - self.ids.lbl_txt.texture_size[0])
>         height: dp(200)
>         pos_hint: {"center_x": .5, "center_y": .5}
> """
> 
> 
> class MainApp(MDApp):
>     def build(self):
>         self.root = Builder.load_string(root_kv)
> 
> 
> MainApp().run()
> ```

This is with builder method.it can't be done without it(size_hint)
I know I'm making you angry  .......

**Comment by HeaTTheatR** [comment]
@tasen-sp 
```python
from kivy.clock import Clock
from kivy.metrics import dp
from kivy.uix.screenmanager import Screen

from kivymd.app import MDApp
from kivymd.uix.button import MDRectangleFlatIconButton


class MyMDRectangleFlatIconButton(MDRectangleFlatIconButton):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Clock.schedule_once(self.set_width)

    def set_width(self, i):
        self.width = dp(200) + (
            self.ids.lbl_txt.texture_size[0] - self.ids.lbl_txt.texture_size[0]
        )


class MainApp(MDApp):
    def build(self):
        self.root = Screen()
        self.root.add_widget(
            MyMDRectangleFlatIconButton(
                icon="git",
                text="text",
                pos_hint={"center_x": 0.5, "center_y": 0.5},
                text_color=(0, 0, 1, 1),
            )
        )


MainApp().run()
```

**Comment by tasen-sp** [comment]
Thanks

**Comment by tasen-sp** [comment]
How to switch screen without using builder in kivymd.pls tell me

**Comment by tasen-sp** [comment]
Reply pls

**Comment by manoharthakur351** [comment]
[U r great it worked](https://github.com/kivymd/KivyMD/issues/144#issuecomment-661676124)
