### ISSUE TITLE
Memory leak FigureCanvasKivyAgg, after removing the widget

### ISSUE THREAD

**Issue by iliodium** [kivymd/KivyMD#1440]
Hello, i have +- same problem with FigureCanvasKivyAgg(https://github.com/kivymd/KivyMD/issues/1332), with each click some memory leak, but when I press about 10 times part of the memory is returned
when i start 155MB, each click +3MB
memory within [160-210] but it small plot and only once

matplotlib 3.1.3
Kivy 2.1.0
kivymd 1.1.1
Windows 10
Python 3.7

i make simple test

`
        import matplotlib.pyplot as plt
        from kivymd.app import MDApp
        from kivymd.app import Builder
        from kivy.garden.matplotlib import FigureCanvasKivyAgg
      
    kv = """
    
    MDGridLayout:
        cols:1
        MDBoxLayout:
            id: plot
        MDBoxLayout:
            MDFlatButton:
                text:'DRAW'
                on_release: app.plot()
            MDLabel:
                id: counter
                adaptive_size: True
                text: 'Click 0'
    """
  
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3, 4], [1, 7, 4, 8])
    
    
    class MainApp(MDApp):

    def build(self):
        self.count = 0
        return Builder.load_string(kv)

    def plot(self):
        self.count += 1
        self.root.ids.counter.text = f'Click {self.count}'
        self.root.ids.plot.clear_widgets()
        self.root.ids.plot.add_widget(FigureCanvasKivyAgg(fig))

  
    if __name__ == "__main__":
        MainApp().run()
`

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch
