### ISSUE TITLE
Cannot set font_style when instantiating MDLabel 

### ISSUE THREAD

**Issue by PythonLaboratory** [kivymd/KivyMD#1446]
### Description of the Bug

When I try to set font_style when instantiating MDLabel class nothing happens (font style doesn't change)

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.label import MDLabel


class Test(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        return (
            MDScreen(
                MDLabel(
                    text="MDLabel",
                    font_style="H1"
                )
            )
        )


Test().run()
```

I see

![изображение](https://user-images.githubusercontent.com/119929553/210806549-cbd801b5-91c5-4ef2-bdd2-56841cc3380a.png)

### Versions

* OS: Ubuntu 22.04
* Python: 3.10.6
* Kivy: master
* KivyMD: master

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1435
