### ISSUE TITLE
The Widget MDTopAppBar is not working in Android

### ISSUE THREAD

**Issue by venkataraja705** [kivymd/KivyMD#1449]
### Description of the Bug

I was trying to use the MDTopAppbar.
the actual code is working in Good when i run in windows
the apk generation is done with no errors
tested on android emulator with android version 7.0 working good.
when I use the same Apk file and run on my actual phone with android version 12.0 the application is not running and it is crashing.
I am Testing Each and Every widget i have Test MDScrollView it is working in my Android Device. now to my test
the MDTopAppBar widget is not Working in Android.

### Code and Logs

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.snackbar import Snackbar

KV = '''
MDScreen:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "MDTopAppBar"
            left_action_items: [["menu", "This is the navigation"]]
            right_action_items:
                [["dots-vertical", lambda x: app.callback(x), "this is the More Actions"]]

        MDLabel:
            text: "Content"
            halign: "center"
'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def callback(self, button):
        Snackbar(text="Hello World").open()

Test().run()

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: windows 
* Python: 3.9
* Kivy: 2.1.0
* KivyMD: 1.1.0

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device

**Comment by venkataraja705** [comment]
It is not working the app is crashing.

**Comment by vabt-igd** [comment]
@HeaTTheatR 
Is there currently any solution available to get the MDTopAppBar running on Android?
It seems like a lot of components using shaders are broken when run on Adreno GPUs and Android...
Simple examples like https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/ are crashing immediately even with the 'fix' (https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device)...

**Comment by HeaTTheatR** [comment]
Use Kivy/KivyMD from master branch
