### ISSUE TITLE
Expansion panel content.height

### ISSUE THREAD

**Issue by LazzaAU** [kivymd/KivyMD#1453]
### Description of the Bug

I have a MDExpansionPanel in my app. On the very first click to expand the panel, the expansion panel grossly over extends the height. Closing the panel then re opening it the second time and it displays as i would expect it to.

Unfortunately i have tried to make a minimal code of the issue with no success. So this bug report is perhaps something to keep in the back of the mind in case it sparks a thought in the future.

**What i've noticed the cause is **
In expansionpanel.py and in the def open_panel() method there is a animation that uses content.height
for me the self.content.height is way larger than the desired figure on the second opening 
```
print(f"Open panel method, animation height -> \n content.height = {self.content.height} \n self.height = {self.height}")
anim = Animation(
            height=self.content.height + self.height,
            d=self.opening_time,
            t=self.opening_transition,
        )
        anim.bind(on_complete=self._add_content)
        anim.bind(on_complete=self._disable_anim)
```
When i add a print statement above that animation, i notice that on first click of the panel my self.content.height is 1690
On second click (when it displays correctly) the self.content.height is 560.
```
#first opening
Open panel method, animation height -> 
 content.height = 1690.0 
self.height = 56.0

# Second opening
Open panel method, animation height -> 
 content.height = 560 
self.height = 56.0

```
My panel Content is made up of a MDCard and around 6 MDLabels, but as i say i can't replicate it in minimal code just yet so i'm documenting it for reference  

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by LazzaAU** [comment]
This below code doesn't fix this issue,  but it's in the same file..... i did find a potential issue in the code 
```
   def check_open_panel(
        self,
        instance_panel: [
            MDExpansionPanelThreeLine,
            MDExpansionPanelTwoLine,
            MDExpansionPanelThreeLine,
            MDExpansionPanelLabel,
        ],
    ) -> None:
    ```
    there is two MDExpansionPanelThreeLine in this block of code, suspect one of them should be a PanelOneLine
    
    i would do a PR , but my fork of this file is not clean atm :)

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version

**Comment by technology11** [comment]
Good day @HeaTTheatR ,
What does "The issue is deprecated due to the new API of the KivyMD library 2.0.0 version" mean...

**Comment by HeaTTheatR** [comment]
@technology11 This means that today the master branch will have KivyMD version 2.0.0, which is incompatible with previous versions of the library. Therefore, all issues are marked as deprecated.
