### ISSUE TITLE
Some Behaviors are not adapted to RelativeLayout

### ISSUE THREAD

**Issue by woxy005** [kivymd/KivyMD#1454]
Some Behaviors will have their coordinates shifted when mixed with RelativeLayout.
However, some other behaviors are adapted to RelativeLayout.
And most of these problems can be solved by modifying
```
self.pos
self.center
```
to
```
self.to_local(*self.pos)
self.to_local(*self.center)
```
I would like all Behaviors to work consistently.

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
