### ISSUE TITLE
resycleview not showing after deploy to apk

### ISSUE THREAD

**Issue by zox47** [kivymd/KivyMD#1471]
hey guys! i have a problem with resycleview when o deploy app to apk the items not showing 

# Code and Logs

def set_list_md_icons(self, text="", search=False):
       
        def add_icon_item(country, number, id):
            

            self.ids.rvs.data.append(
                {
                    "viewclass": "CustomOneLineIconListItems",
                    "icon": "/storage/emulated/0/projet/backup.png",
                    "second": "Now",
                    "text": country,
                    "three": str(number),
                    "id": id,

                }
            )

        self.ids.rvs.data = []
        
        for name_icon in listss:

            h= name_icon.split("|", 3)
        #    print (h[1])
     #       print (h[2])

            if search:
                if text in name_icon:
                    add_icon_item(h[0], h[1] , h[2]) 

            else:
                add_icon_item(h[0], h[1] , h[2]) 

                pause.seconds(0.01)

* OS: android
* Python: 3.9
* Kivy: 2.0.1
* KivyMD: 1.0.1

**Comment by HeaTTheatR** [comment]
The issue is not related to the KivyMD library.
