### ISSUE TITLE
MDNavigationRail Docs v 1.1.1

### ISSUE THREAD

**Issue by AnderSchofield** [kivymd/KivyMD#1473]
Hey guys! First off, my apologies if this isn't the right channel to bring this up, but I came across an issue while tinkering with MD's code. The MDNavigationRaid module has a function that references a variable that doesn't exist in its docstrings. I tried to edit it on GitHub, but I couldn't find the files. However, I did notice that the latest module's docstrings have fixed this issue. Unfortunately, the website and PDF contents of v.1.1.1 still contain the error.

Here's the issue I found:

def set_radius(self, *args):
    if self.rounded_button:
        self._radius = self.radius = self.height / 4

And here's the fixed code (Already inside the module's docstring as said)

def set_radius(self, *args):
    if self.rounded_button:
        value = self.height / 4
        self.radius = [value, value, value,  #value]
        self._radius = value
Thanks for your help in advance!

_Originally posted by @AnderSchofield in https://github.com/kivymd/KivyMD/discussions/1077#discussioncomment-5308698_

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.
