### ISSUE TITLE
keybaord fix

### ISSUE THREAD

**Issue by pythonsus** [kivymd/KivyMD#1476]
### Description of the Bug

running my app on the app store weather psychic on a iphone then type co in the text field and press a suggestion on the default iphone keyboard like columbus or something like that then the text becomes cocolumbus instead of columbus

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 16
* Python: 3.9
* Kivy: lastest
* KivyMD: lastest

**Comment by HeaTTheatR** [comment]
Not related to the KivyMD library.

**Comment by pythonsus** [comment]
It is a kivymd app
