### ISSUE TITLE
MDBottomAppBar icon size small can not be changed

### ISSUE THREAD

**Issue by cryptoone** [kivymd/KivyMD#1480]
no matter what size you put, always the icon size is small, never fills the free button
icon_size does not change anything
MDBottomAppBar:
                    md_bg_color: app.light
                    MDTopAppBar:
                        title:""
                        md_bg_color: app.light
                        icon: "./pics/icons/scan.png"
                        type: "bottom"
                        icon_color:app.light
                        mode:'center'
                        icon_size:"128sp"

### Description of the Bug

Your text

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
