### ISSUE TITLE
How can I run the whole program on the right side?

### ISSUE THREAD

**Issue by moba-sel** [kivymd/KivyMD#1481]
Hello, I am a Persian language user

The problem is that kivymd does not support Persian language and we have to use some other libraries to use Persian language

Unlike English, Persian language starts from the right side

For example, in dialogues, the title and texts cannot be displayed on the right side, and the appearance of the program becomes very bad

If you add these 2 topics to kivymd it will be great

1- Persian language support
2- Right folding of the entire software

**Comment by T-Dynamos** [comment]
KivyMD uses [Kivy](https://kivy.org)'s Label, So you should not report issue here as it is not related to kivymd.

Instead report [here](https://github.com/kivy/kivy/issues/new?assignees=&labels=&template=feature_request.md&title=%5BEnhancement%5D%3A%20Add%20Persian%20language%20support)
