### ISSUE TITLE
MDDialog apk open and crash

### ISSUE THREAD

**Issue by cunhavitor** [kivymd/KivyMD#1486]
I build my apk in buildozer, the apk run normally, when open a MDDialog after 1 second crash...
Here is the logcat:

4-17 16:16:07.128 15312 15380 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 in tid 15380 (SDLThread), pid 15312 (SDLActivity)
04-17 16:16:07.208 15541 15541 E DEBUG   : failed to read /proc/uptime: Permission denied
04-17 16:16:07.372 15541 15541 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-17 16:16:07.372 15541 15541 F DEBUG   : Build fingerprint: 'POCO/lmi_eea/lmi:12/SKQ1.211006.001/V13.0.8.0.SJKEUXM:user/release-keys'
04-17 16:16:07.372 15541 15541 F DEBUG   : Revision: '0'
04-17 16:16:07.372 15541 15541 F DEBUG   : ABI: 'arm64'
04-17 16:16:07.372 15541 15541 F DEBUG   : Timestamp: 2023-04-17 16:16:07.208154235+0000
04-17 16:16:07.372 15541 15541 F DEBUG   : Process uptime: 0s
04-17 16:16:07.372 15541 15541 F DEBUG   : Cmdline: org.test.fms2
04-17 16:16:07.372 15541 15541 F DEBUG   : pid: 15312, tid: 15380, name: SDLThread  >>> org.test.fms2 <<<
04-17 16:16:07.372 15541 15541 F DEBUG   : uid: 10509
04-17 16:16:07.372 15541 15541 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40
04-17 16:16:07.372 15541 15541 F DEBUG   : Cause: null pointer dereference
04-17 16:16:07.372 15541 15541 F DEBUG   :     x0  0000000000000001  x1  0000000000000000  x2  0000000000000003  x3  000000000000001c
04-17 16:16:07.372 15541 15541 F DEBUG   :     x4  b400006faff3bbbc  x5  0000000000000003  x6  b400006faff3be6c  x7  00000000000ca000
04-17 16:16:07.372 15541 15541 F DEBUG   :     x8  0000000000000003  x9  0000000000000003  x10 0000006fb206b234  x11 b400006faff3bbc4
04-17 16:16:07.372 15541 15541 F DEBUG   :     x12 b400006fafda076c  x13 0000006fb206b23c  x14 0000000000000000  x15 0000000000000000
04-17 16:16:07.372 15541 15541 F DEBUG   :     x16 0000000000000001  x17 0000000000000000  x18 0000000000000000  x19 0000006fb206b380
04-17 16:16:07.372 15541 15541 F DEBUG   :     x20 b400006faff3bb00  x21 b400006fafd9e2c0  x22 0000000000000000  x23 0000000000000003
04-17 16:16:07.372 15541 15541 F DEBUG   :     x24 0000000000000000  x25 0000000000000001  x26 0000000000000000  x27 0000000000000001
04-17 16:16:07.372 15541 15541 F DEBUG   :     x28 0000000000000068  x29 0000006fb206b240
04-17 16:16:07.372 15541 15541 F DEBUG   :     lr  000000700e592ce0  sp  0000006fb206b200  pc  000000700e5a54a8  pst 0000000060001000
04-17 16:16:07.372 15541 15541 F DEBUG   : backtrace:
04-17 16:16:07.372 15541 15541 F DEBUG   :   NOTE: Function names and BuildId information is missing for some frames due
04-17 16:16:07.372 15541 15541 F DEBUG   :   NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
04-17 16:16:07.372 15541 15541 F DEBUG   :   NOTE: found under the lib/ directory are readable.
04-17 16:16:07.372 15541 15541 F DEBUG   :   NOTE: On this device, run setenforce 0 to make the libraries readable.
04-17 16:16:07.372 15541 15541 F DEBUG   :       #00 pc 00000000003944a8  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!7b4d3d680da059de73d7f9795dc456!db3d445dbc!+368) (BuildId: c8ff05ee7770eabb902f5e18c4c04e0a)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #01 pc 0000000000381cdc  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!f56be09eb88f86833124f1df42e945!db3d445dbc!+4180) (BuildId: c8ff05ee7770eabb902f5e18c4c04e0a)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #02 pc 0000000000176ad8  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!6b200851123c7898055fe62ff9f71f!db3d445dbc!+616) (BuildId: c8ff05ee7770eabb902f5e18c4c04e0a)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #03 pc 000000000016e710  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!77df12deb6a622478efa8fb9929034!db3d445dbc!+376) (BuildId: c8ff05ee7770eabb902f5e18c4c04e0a)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #04 pc 000000000000ae20  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/vbo.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #05 pc 0000000000014428  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #06 pc 0000000000008418  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #07 pc 0000000000012234  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #08 pc 0000000000011a74  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #09 pc 0000000000014ac0  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #10 pc 0000000000015fe8  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #11 pc 0000000000008418  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #12 pc 0000000000012234  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #13 pc 0000000000011a74  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #14 pc 0000000000008418  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #15 pc 0000000000012234  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #16 pc 0000000000011a74  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #17 pc 0000000000014ac0  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #18 pc 0000000000008418  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #19 pc 0000000000012234  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #20 pc 0000000000011a74  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #21 pc 0000000000014ac0  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #22 pc 0000000000008418  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #23 pc 0000000000012234  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #24 pc 0000000000011a74  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #25 pc 0000000000014ac0  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #26 pc 0000000000015fe8  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #27 pc 00000000000205dc  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #28 pc 0000000000166fb8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #29 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #30 pc 0000000000228ca8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9972)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #31 pc 000000000015e5dc  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #32 pc 00000000001609f4  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #33 pc 00000000000259d0  /data/data/org.test.fms2/files/app/_python_bundle/site-packages/kivy/_event.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #34 pc 0000000000166b44  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #35 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #36 pc 0000000000228ca8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9972)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #37 pc 000000000015e5dc  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #38 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #39 pc 0000000000228ca8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9972)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #40 pc 000000000015e5dc  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #41 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #42 pc 0000000000228ca8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9972)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #43 pc 000000000015e5dc  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #44 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #45 pc 0000000000229c84  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+14032)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #46 pc 000000000015e5dc  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #47 pc 000000000022bcc0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #48 pc 0000000000228ca8  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9972)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #49 pc 000000000022cc9c  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so
04-17 16:16:07.372 15541 15541 F DEBUG   :       #50 pc 00000000002264e0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (PyEval_EvalCode+76)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #51 pc 0000000000266f0c  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libpython3.9.so (PyRun_SimpleFileExFlags+1192)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #52 pc 00000000000026e0  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libmain.so (SDL_main+2664) (BuildId: 956b10576cc55b3ffaf8ea6a1bff89f98e3ad048)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #53 pc 00000000000b0190  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/lib/arm64/libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+772) (BuildId: 7d755fa3a27aa11bc32d47ac14211278da93cdbf)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #54 pc 0000000000461554  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #55 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #56 pc 000000000001016e  /data/app/~~P-2jc9Aw39ecUvE86do_xw==/org.test.fms2-YU-nN7WjNXBKUDGz7d1CcA==/oat/arm64/base.vdex
04-17 16:16:07.372 15541 15541 F DEBUG   :       #57 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #58 pc 00000000000f6740  /apex/com.android.art/javalib/core-oj.jar
04-17 16:16:07.372 15541 15541 F DEBUG   :       #59 pc 0000000000457b6c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #60 pc 0000000000484e54  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #61 pc 0000000000484b20  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+400) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #62 pc 00000000005ce334  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1684) (BuildId: 289d75599f6112d5757113220599e90b)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #63 pc 00000000000efb14  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 94065bf91428f6ae9fb310c478171302)
04-17 16:16:07.372 15541 15541 F DEBUG   :       #64 pc 000000000008c35c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 94065bf91428f6ae9fb310c478171302)
04-17 16:16:07.380 15541 15541 E crash_dump64: cannot open system/lib64/libmiuindbg.so: Permission denied
04-17 16:16:07.384   746   746 E tombstoned: Tombstone written to: tombstone_21
04-17 16:16:07.441 25305 25404 E CpuruntimeResource: getPkgRuntimeInfo exception: /proc/package/pkg/show_fb_showall: open failed: EACCES (Permission denied)
04-17 16:16:07.449  1399  1399 E ClientCache: failed to get buffer, invalid process token
04-17 16:16:07.449  1399  1399 E BpTransactionCompletedListener: Failed to transact (-32)
04-17 16:16:07.450  1399  1399 E BpTransactionCompletedListener: Failed to transact (-32)
04-17 16:16:07.521 31209 31209 E BlurUtils: fastBlurDirectly ratio=0.0   win=com.android.internal.policy.PhoneWindow@fe3f5f4
04-17 16:16:07.543 31209 31209 E RotationHelper: setCurrentTransitionRequest: request=0
04-17 16:16:07.543 31209 31209 E RotationHelper: setCurrentTransitionRequest: request=0
04-17 16:16:07.590 27750 27750 E FullInputEventModel: onStartInput event aborted: rj.z: could not obtain extracted text (class rj.z)
04-17 16:16:07.638 27750 27750 E FullInputEventModel: selectionUpdated event aborted: rj.z: Could not create selection changed event (class rj.z)
04-17 16:16:07.644 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap': No such file or directory
04-17 16:16:07.644 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap
04-17 16:16:07.645 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap': No such file or directory
04-17 16:16:07.645 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap
04-17 16:16:07.645 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap': No such file or directory
04-17 16:16:07.645 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap
04-17 16:16:07.646 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap': No such file or directory
04-17 16:16:07.646 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap
04-17 16:16:07.646 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap': No such file or directory
04-17 16:16:07.646 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-neutral-3Qrx.frro@idmap
04-17 16:16:07.646 15186 15397 E system_server: Failed to open file '/data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap': No such file or directory
04-17 16:16:07.646 15186 15397 E system_server: failed to read IDMAP /data/resource-cache/data@resource-cache@com.android.systemui-accent-LHyN.frro@idmap
04-17 16:16:07.671 27750 27750 E FullInputEventModel: selectionUpdated event aborted: rj.z: Could not create selection changed event (class rj.z)
04-17 16:16:07.678 27750 27750 E FullInputEventModel: onStartInput event aborted: rj.z: could not obtain extracted text (class rj.z)

**Comment by HeaTTheatR** [comment]
Attach the minimum code and versions of the libraries you use and create issue again.
