### ISSUE TITLE
Add property/method on MDDataTable for dynamically insert/remove colums after table creation

### ISSUE THREAD

**Issue by Tungsteno74** [kivymd/KivyMD#1488]
### Description of the Feature

Good morning,
I'm just starting to use your version of Kivy (before I used Kivy base) and I noticed that the MDDataTable widget doesn't allow to add or remove columns to a table after its creation.
I tried looking in the code, but there is no function or property that does such feature.

At the moment to add a new column, I have to create a new table, insert the values of the old table and display it with the new column replacing it with the parent layout of the old table.
It seems to me that this is not the most efficient way to do this.

Do you think it is possible to optimize this operation in some way or need a new feature?

Thank you and good evening.

### Code and Logs

No code.

### Screenshots

No image.

### Versions

Any.

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/datatables/#kivymd.uix.datatables.datatables.MDDataTable.add_row

**Comment by Tungsteno74** [comment]
@HeaTTheatR Hello, i saw it, but this method add a row of the table not a column.

What I was asking for was a quick method to add/remove (or show/hide) columns in a table with the same number of rows.

To do this I currently have to create a new table and import the data_row of the old one by adding a column and data to each row in the old table. 
Not a very practical way to do this. If it were integrated widget would be ideal.

Can it be added as a feature?
