### ISSUE TITLE
MDTextField:  helper_text_mode: "on_focus" doesn't work as expected

### ISSUE THREAD

**Issue by magowiz** [kivymd/KivyMD#1494]
### Description of the Bug
I'm trying examples provided in official documentation pages about textfields: https://kivymd.readthedocs.io/en/1.1.1/components/textfield/ , In particular the one named "Helper text mode on on_focus event" : https://kivymd.readthedocs.io/en/1.1.1/components/textfield/#helper-text-mode-on-on-focus-event

I created a small example just to load only that component and try its behavior, anyway I noticed that  the text below the field (the one saying "his will disappear when you click off") appears when I click on field but doesn't go away if I click elsewhere.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
MDScreen:
    MDTextField:
        hint_text: "Helper text on focus"
        helper_text: "This will disappear when you click off"
        helper_text_mode: "on_focus"
'''


class Example(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        return Builder.load_string(KV)


Example().run()
```

### Screenshots
I attached a screenshot of final result, after I focused the field and then I click somewhere else:
![immagine](https://user-images.githubusercontent.com/1067544/234018714-9bfcc243-b8bc-4311-ae4a-3a6acd627245.png)

### Versions

* OS: Ubuntu 23.04
* Python: 3.9.16
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
I don't know what you're talking about

**Comment by magowiz** [comment]
I mean that after clicking the field the helper text appears, and never disappears if I click outside of the textfield. I understood the helper text should disappear but remains, no matter what I do.

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch.
