### ISSUE TITLE
Have a "_no_ripple_effect" variable in MDApp that controls all widgets

### ISSUE THREAD

**Issue by acgc99** [kivymd/KivyMD#1499]
### Description of the Feature

Like when you do `MDApp.theme_cls.primary_palette` to change color of all widgets, I purpose having `MDApp._no_ripple_effect` that affects all widgets, instead of having to set this property to all of them individually, that could cause mismatches if you forget to deactivate some widgets.

### Versions

* OS: Windows 11
* Python: 3.11.2
* Kivy: 2.2.0.dev0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
You cannot disable the ripple effect for all widgets. Only for the selected widget.
