### ISSUE TITLE
MDTextField' object has no attribute '_cursor_blink

### ISSUE THREAD

**Issue by mcroni** [kivymd/KivyMD#15]
When playing with the kitchen_sink and i try to open the TextField screen, upon touching or clicking on any of the textfields, the app crushes with this error
` File "kivy\weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__ (kivy\weakproxy.c:1386)
 AttributeError: 'MDTextField' object has no attribute '_cursor_blink'`

I updated my python version to 3.7 and this issues didnt occur but it did occur witih python 3.4

**Comment by HeaTTheatR** [comment]
@mcroni, I can not reproduce this problem! When building packages for Android and iOS, Python 2.7 / 3.7 is used, so there is no point in worrying.
