### ISSUE TITLE
MDLabel color issue

### ISSUE THREAD

**Issue by orkino** [kivymd/KivyMD#1505]
Hello,

Lately, the MDLabel seems to have an issue, the attribute md_bg_color doesn't work with the text. It makes the text disappear no matter what the text color is?

**Comment by HeaTTheatR** [comment]
Attach a minimal code example

**Comment by orkino** [comment]
`        self.colored_label = MDLabel(text=str(self.task_index),
                                     size_hint=(0.1, 1), halign="center")
        self.colored_label.color = "white"
        self.colored_label.md_bg_color = "#91529F"`
        
        This doesn't display the text at all. I had this issue today, it worked before.

**Comment by HeaTTheatR** [comment]
```python
from kivymd.uix.label import MDLabel
from kivymd.app import MDApp


class Test(MDApp):
    def build(self):
        colored_label = MDLabel(
            text="MDLabel",
            halign="center",
            theme_text_color="Custom",
            text_color="brown",
        )
        colored_label.md_bg_color = "#91529F"
        return colored_label


Test().run()
```

And use KivyMD from master branch.
