### ISSUE TITLE
MDBottomAppBar not displaying the contents of MDTopAppBar

### ISSUE THREAD

**Issue by TanishqPokharia** [kivymd/KivyMD#1519]
### Description of the Bug

Contents of a child MDTopAppBar not appearing inside parent MDBottomAppBar

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
MDBoxLayout:
    orientation: 'vertical'
    MDTopAppBar:
        title: "MyApp"
        left_action_items: [["menu"]]
        right_action_items: [["dots-vertical"]]

    MDLabel:
        id: my_label
        text: "Welcome User!"
        halign: "center"

    MDBottomAppBar:
        MDTopAppBar:
            title: "Title"
            icon: "git"
            type: "bottom"

"""
class MyApp(MDApp):

    def build(self):
        return Builder.load_string(kv)


if __name__ == '__main__':
    MyApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.
![Screenshot 2023-06-30 144147](https://github.com/kivymd/KivyMD/assets/114491890/2edff2cc-418b-465a-ab85-0612523a6a08)

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
`app.theme_cls.material_style = "M2"`

**Comment by TanishqPokharia** [comment]
Thank you so much :)
