### ISSUE TITLE
MDTextField not showing left icon when both icons are defined

### ISSUE THREAD

**Issue by magdutra** [kivymd/KivyMD#1526]
### Description of the Bug

MDTextField not showing left icon when both icons are defined

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = '''
MDTextField:
	icon_left: 'lock'
	icon_right: 'eye-off'
'''

class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)

MainApp().run()
```

### Screenshots

![Screenshot_2023-07-10_20-58-08](https://github.com/kivymd/KivyMD/assets/20996887/3a22e685-e93f-4ad6-89c0-46d8473897d6)

### Versions

* OS: Debian 12.0
* Python: 3.11.2
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
