### ISSUE TITLE
MDTopAppBar with action items is making text invisible when the theme style is changed

### ISSUE THREAD

**Issue by magdutra** [kivymd/KivyMD#1527]
### Description of the Bug

MDTopAppBar with action items is making text invisible when the theme style is changed. It happens either with Dark or Light themes. The text color doesn't get updated, which makes it invisible in the dark or light background.

If the line containing "left_action_items" is commented, the problem disappears. The same problem happens with "right_action_actions" as well.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = '''
MDBoxLayout:
    orientation: 'vertical'
    MDTopAppBar:
        left_action_items: [ [ 'arrow-left' ] ]
    MDBoxLayout:
        MDLabel:
            text: 'Visible Label'
        MDSwitch:
            on_active: app.switch_theme(*args)
'''

class MainApp(MDApp):
    def build(self):
        return Builder.load_string(kv)
    def switch_theme(self, switch, state):
        self.theme_cls.theme_style = 'Dark' if state else 'Light'

MainApp().run()
```

### Screenshots

![Screenshot_2023-07-11_07-50-06](https://github.com/kivymd/KivyMD/assets/20996887/7ff3b8f2-78a9-4e00-b33e-d35fe462d209)
![Screenshot_2023-07-11_07-49-40](https://github.com/kivymd/KivyMD/assets/20996887/c9220a1f-4c09-4105-b14e-e88ec42148d5)

### Versions

* OS: Debian 12.0
* Python: 3.11.2
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch
