### ISSUE TITLE
Text field rectagle mode

### ISSUE THREAD

**Issue by GvozdevLeonid** [kivymd/KivyMD#1533]
Пожалуйста добавьте dp в TextField при анимации hint_text
    def set_pos_hint_text(self, y: float, x: float = 12) -> None:
        """Animates the x-axis width and y-axis height of the hint text."""

        if self.mode != "round":
            Animation(_hint_y=y, duration=0.2, t="out_quad").start(self)
            if self.mode == "rectangle":
                if not self.icon_left:
                    _hint_x = dp(x) < -- если указать dp, то отображение будет правильным ( MAC OS)
                else:
                    if y == dp(10):
                        _hint_x = dp(-4)
                    else:
                        _hint_x = dp(20)

                Animation(
                    _hint_x=_hint_x,
                    duration=0.2,
                    t="out_quad",
                ).start(self)

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
