### ISSUE TITLE
MDDialog().open crashes app without an error.

### ISSUE THREAD

**Issue by gigajuad** [kivymd/KivyMD#1535]
### Description of the Bug

Example code from kivymd dialog documentation crashes the android app without any error, same with a snackbar. I tried it both on pydroid3 and by building an app using buildozer, everything works fine until the MDDialog.open method is called.
It works fine on pc but doesnt work on phone, no errors, in the build i also checked logcat and there were no errors.

### Code and Logs
Code is copy pasted from mddialog docs page - https://kivymd.readthedocs.io/en/1.1.1/components/dialog/#kivymd.uix.dialog.dialog.MDDialog.update_items
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.dialog import MDDialog

KV = '''
MDFloatLayout:

    MDFlatButton:
        text: "ALERT DIALOG"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_alert_dialog()
'''


class Example(MDApp):
    dialog = None

    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        return Builder.load_string(KV)

    def show_alert_dialog(self):
        if not self.dialog:
            self.dialog = MDDialog(
                text="Discard draft?",
                buttons=[
                    MDFlatButton(
                        text="CANCEL",
                        theme_text_color="Custom",
                        text_color=self.theme_cls.primary_color,
                    ),
                    MDFlatButton(
                        text="DISCARD",
                        theme_text_color="Custom",
                        text_color=self.theme_cls.primary_color,
                    ),
                ],
            )
        self.dialog.open()


Example().run()
```

### Versions

* OS:  Android 13
* Python: 3.9 (pydroid3) and 3.10 (buildozer build)
* Kivy: 2.2.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch

**Comment by gigajuad** [comment]
### unable to build when using the master branch

`[INFO]:    Unpacking kivy for arm64-v8a
[DEBUG]:   -> running basename https://github.com/kivy/kivy/archive/2.2.0.zip
[DEBUG]:        2.2.0.zip
[INFO]:    -> directory context /home/user/cruffin_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/kivy/arm64-v8a__ndk_target_21
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/user/cruffin_app/.buildozer/android/platform/python-for-android
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding freetype for arm64-v8a
[INFO]:    freetype has no prebuild_arm64_v8a, skipping
[INFO]:    Prebuilding hostpython3 for arm64-v8a
[INFO]:    hostpython3 has no prebuild_arm64_v8a, skipping
[INFO]:    Applying patches for hostpython3[arm64-v8a]
[INFO]:    hostpython3 already patched, skipping
[INFO]:    Prebuilding jpeg for arm64-v8a
[INFO]:    jpeg has no prebuild_arm64_v8a, skipping
[INFO]:    Prebuilding libffi for arm64-v8a
[INFO]:    libffi has no prebuild_arm64_v8a, skipping
[INFO]:    Applying patches for libffi[arm64-v8a]
[INFO]:    Applying patch remove-version-info.patch
[DEBUG]:   -> running patch -t -d /home/user/cruffin_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/libffi/arm64-v8a__ndk_target_21/libffi -p1 -i /home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/remove-version-info.patch
[DEBUG]:        can't find file to patch at input line 3
[DEBUG]:        Perhaps you used the wrong -p or --strip option?
[DEBUG]:        The text leading up to this was:
[DEBUG]:        --------------------------
[DEBUG]:        |--- libffi/Makefile.am.orig    2018-12-21 16:11:26.159181262 +0100
[DEBUG]:        |+++ libffi/Makefile.am 2018-12-21 16:14:44.075179374 +0100
[DEBUG]:        --------------------------
[DEBUG]:        No file to patch.  Skipping patch.
[DEBUG]:        1 out of 1 hunk ignored
Exception in thread background thread for pid 12231:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/patch -t -d /home/user/cruffin_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/libffi/arm64-v8a__ndk_target_21/libffi -p1 -i /home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/remove-version-info.patch

  STDOUT:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- libffi/Makefile.am.orig    2018-12-21 16:11:26.159181262 +0100
|+++ libffi/Makefile.am 2018-12-21 16:14:44.075179374 +0100
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored


  STDERR:

[INFO]:    STDOUT:
        can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- libffi/Makefile.am.orig    2018-12-21 16:11:26.159181262 +0100
|+++ libffi/Makefile.am 2018-12-21 16:14:44.075179374 +0100
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
[INFO]:    STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 497, in build_recipes
    recipe.apply_patches(arch)
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 532, in apply_patches
    self.apply_patch(
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 249, in apply_patch
    shprint(sh.patch, "-t", "-d", build_dir, "-p1",
  File "/home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/patch -t -d /home/user/cruffin_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/libffi/arm64-v8a__ndk_target_21/libffi -p1 -i /home/user/cruffin_app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/remove-version-info.patch

  STDOUT:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- libffi/Makefile.am.orig    2018-12-21 16:11:26.159181262 +0100
|+++ libffi/Makefile.am 2018-12-21 16:14:44.075179374 +0100
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored


  STDERR:

# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=cruffinwriter', '--bootstrap=sdl2', '--requirements=python3,kivy,https://github.com/kivymd/KivyMD/archive/master.zip,pyserial,usb4a,usbserial4a,svgpathtools,svg-to-gcode,Kivy-Garden,pillow,numpy,svgwrite,pyjnius,kivygradient', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/user/cruffin_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WSL_DISTRO_NAME = 'Ubuntu'
#     NAME = 'JavedPC'
#     PWD = '/home/user/cruffin_app'
#     LOGNAME = 'user'
#     HOME = '/home/user'
#     LANG = 'C.UTF-8'
#     WSL_INTEROP = '/run/WSL/11_interop'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'user'
#     SHLVL = '1'
#     WSLENV = ''
#     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = ('/home/user/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program '
 'Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin:/mnt/c/Program '
 'Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/libnvvp:/mnt/c/Program '
 'Files/PlasticSCM5/server:/mnt/c/Program '
 'Files/PlasticSCM5/client:/mnt/c/Program Files/NVIDIA GPU Computing '
 'Toolkit/CUDA/v12.1/bin:/mnt/c/Program Files/NVIDIA GPU Computing '
 'Toolkit/CUDA/v12.1/libnvvp:/mnt/c/Program '
 'Files/Microsoft/jdk-11.0.18.10-hotspot/bin:/mnt/c/Program '
 'Files/Oculus/Support/oculus-runtime:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program '
 'Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA '
 'Corporation/PhysX/Common:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files '
 '(x86)/QuickTime/QTSystem/:/mnt/c/Program Files '
 '(x86)/GtkSharp/2.12/bin:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python310/Scripts:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program '
 'Files/Git/cmd:/mnt/c/Program '
 'Files/KTX-Software/bin:/mnt/c/Users/admin/Downloads/platform-tools_r33.0.3-windows/platform-tools:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python310/:/mnt/c/Program '
 'Files (x86)/dotnet/:/mnt/c/Program '
 'Files/nodejs/:/mnt/f/AndroidSDK/Sdk/platform-tools:/mnt/c/Program '
 'Files/NVIDIA Corporation/Nsight Compute 2022.1.0/:/mnt/c/Program '
 'Files/NVIDIA/CUDNN/bin:/mnt/e/CodingFiles/_AndroidStudio/_SDK/DevRoot/android-sdk/emulator:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/admin/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/admin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/admin/AppData/Local/Programs/Microsoft '
 'VS '
 'Code/bin:/mnt/c/Users/admin/.dotnet/tools:/mnt/c/Users/admin/AppData/Roaming/npm:/mnt/c/ffmpeg/bin:/snap/bin')
#     HOSTTYPE = 'x86_64'
#     OLDPWD = '/'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/home/user/.buildozer/android/packages'
#     ANDROIDSDK = '/home/user/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/user/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2`

**Comment by HeaTTheatR** [comment]
@JavedWilde Make sure you are using the master version of the KivyMD library

**Comment by gigajuad** [comment]
@HeaTTheatR i have this in me buildozer.spec file for kivy and kivymd

`requirements = kivy==master, https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by HeaTTheatR** [comment]
@JavedWilde It doesn't matter. Look at the logs.

**Comment by gigajuad** [comment]
how do i specify the kivymd version if not from buildozer.spec?

**Comment by HeaTTheatR** [comment]
@JavedWilde https://github.com/kivymd/KivyMD/pull/1529#issuecomment-1659071182
