### ISSUE TITLE
MDSegmentedControl

### ISSUE THREAD

**Issue by venkataraja705** [kivymd/KivyMD#1539]
### Description of the Bug
we are using the MDSegmentedControl element where we want to create a UI interface that can switch between tabs
here working is proper but the UI is not properly adjustable to window size
the MDSegmentedControl UI is not able to adjust to the screen
when i resize the window it is not able to reduce the size of it.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
MDScreen:
                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: "15dp"
                        MDTopAppBar:
                            title: "Remote Control"
                            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
                        MDSegmentedControl:
                            id:mdsegmentcontrol
                            pos_hint: {"center_x": .5, "center_y": .5}
                            adaptive_size: True
                            on_active: app.segment_active(*args)
                            MDSegmentedControlItem:
                                text: "Mode"
                            MDSegmentedControlItem:
                                text: "Functions"
                            MDSegmentedControlItem:
                                text: "Suspension"
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
when the window size is big enough it is okkk
![image](https://github.com/kivymd/KivyMD/assets/62138941/f80802bf-d1de-4e5f-9bab-ac25b382e158)

but when i reduce it is not as expected

![image](https://github.com/kivymd/KivyMD/assets/62138941/cf45aea6-2704-45e6-8c8d-42248ad163d9)

### Versions

* OS: windows
* Python: 3.9
* Kivy: 2.1.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
This widget has been removed from the KivyMD 2.0.0 library
