### ISSUE TITLE
Default dot is showing on my app NavigationDrawerIconButton

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#154]
Can we disable it because in my scenario it is creating a problem for me?
see how it looks like.
https://ibb.co/hY4L3H8
and my code is 
https://pastebin.com/4mb4zUcx

**Comment by HeaTTheatR** [comment]
NavigationDrawerIconButton - not exists!
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed

**Comment by navjotcis** [comment]
it exists in a 0.100.2 version.

**Comment by HeaTTheatR** [comment]
@navjotcis Current version - 0.103.0!

**Comment by navjotcis** [comment]
So it means every time I need to change in code. is there any stable version?

**Comment by HeaTTheatR** [comment]
@navjotcis No!

**Comment by navjotcis** [comment]
ok thanks for the suggestion
