### ISSUE TITLE
When debugging in Python 3.10.12 debugger crashes locking up system

### ISSUE THREAD

**Issue by weaved459** [kivymd/KivyMD#1540]
Open a main.py file in Pycharm and set break point on a code line.

Start the debugger and poof ... no error, no warning and the entire system locks up requiring a reboot.  The main.py file runs properly by itself or from Pycharm.

I did at first think it was Pycharm so I tested a non kivymd python application and the debugger worked as expected.  I contacted Pycharm and was asked to test the debugger from the command line which I did and got the same result as above.

As far as I can tell there's something with kivyMD that the debugger doesn't like.

Environment:

OS: ubuntu 22.04.3 LTS desktop
Python: 3.10.12
kivy: 2.2.1
kivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
There is no essence of the issue.
