### ISSUE TITLE
3 issues with MDDialog and MDLabel

### ISSUE THREAD

**Issue by Goldybin** [kivymd/KivyMD#1545]
There are 3 issues:
1. MDLabel under the latest version of iOS renders completely black if its size is bigger than a certain threshold (can happen with either a lot of text or if the text font size is big, so it's more about the total space or maybe about the texture size). I couldn't clearly understand the minimum size threshold when it happens, but it's not very big actually.. This happens ONLY on iOS, on my MacOS it always works regardless of the size, even with huge texts. I tried many different approaches with different layouts etc., but the problem is always the MDLabel itself.
2. For custom dialogs, it's impossible to specify size_hint_y or adaptive_height for the entire window height (not for the window and not even for the main MDBoxLayout inside that window), only the fixed y size works. The only (bad) workaround I found - to use the on_open() event handler and there set manually the height of the main MDBoxLayout with the contents to Window.height * 0.9 . 
3. Scrolling in custom dialogs is a huge problem too, to make it work I spent MANY hours and MANY different approaches until I found a combination of settings, which finally made the scrolling possible (a combination of adaptive_height and omitting of any height indication helped, but it took a lot of trial and errors). Probably it should not be sooo complicated to make it work.

All code for all three issues is very trivial, nothing special, you can easily replicate it. Basically it's the code from the official KivyMD examples as the foundation.

And there is one more question - I tried to combine MDIconButton and MDLabel to make an "icon button with a small text below" - but it didn't work. Any hints if it can be done? Many thanks!

**Comment by HeaTTheatR** [comment]
Yes, I know. This has nothing to do with the KivyMD library. This is a question for the Label widget.
