### ISSUE TITLE
Kivytoast text too big and blurry (overflows screen)

### ISSUE THREAD

**Issue by pakal** [kivymd/KivyMD#1547]
### Description of the Bug

Since update from 1.0.2, the "kivytoast" (used under desktop and iOS, not android) has become big, with big and blurry text which quickly overflows the screen.
The "bounding box" doesn't seems respected anymore.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.toast import toast


kv = """
Screen:
    # KV-Code
    Button:
        text: 'Display toast'
        on_release: app.display_toast()
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)
    def display_toast(self):
        toast_options = {"duration": 1.5}
        toast("This is a mildly long text for a toast", **toast_options)

if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![image](https://github.com/kivymd/KivyMD/assets/330629/db68502d-884c-4cb8-a863-a53f72e7dc1d)

### Versions

* OS: Windows 11
* Python: 3.0
* Kivy: 2.2.1
* KivyMD: master (ex. commit 1152d3c312)

**Comment by HeaTTheatR** [comment]
Attach APK

**Comment by pakal** [comment]
There is no apk, it works fine under Android with native toasts in my big apps.

It's under **Desktop** environment (and also ios, but I have no package prepared yet) that it has font issues ; launching the mini-app above should reproduce the problem.

Update : under Ubuntu 20 in a virtualbox the fonts are much better (see below), so it's for now only a Windows+iOS issue

![image](https://github.com/kivymd/KivyMD/assets/330629/e55e4715-fe7a-40f4-983b-9e52cff11532)

**Comment by HeaTTheatR** [comment]
It is not related to the KivyMD library

**Comment by pakal** [comment]
I do not get it, it's the toast() from KivyMD which makes this bug 
You do not reproduce it on your own Windows tests, you mean ?
It'd be a bug of Kivy itself so ?

**Comment by HeaTTheatR** [comment]
@pakal Instead, use a [snackbar](https://github.com/kivymd/KivyMD/tree/2.0.0/kivymd/uix/snackbar) or a native toast.
