### ISSUE TITLE
It seems that the elevation bug still exists

### ISSUE THREAD

**Issue by ShaojieJiang** [kivymd/KivyMD#1548]
### Description of the Bug

I was trying the KitchenSink demo recently, and noticed that there was some issues with the shadow, please see the attached screen recording below.
After some search I found this issue was already reported and closed in #1411, but it still appears on my side.
Is it an OS-specific issue?

### Code and Logs

Simply clone the KitchenSink and run `python main.py` to reproduce the problem.

A workaround to this problem is by commenting out [this line](https://github.com/kivymd/KitchenSink/blob/35f0ec61c79071d310e7f88dcdd982d49d6ba53a/View/MenuScreen/menu_screen.py#L28):
```python
  "title": name_card,
#   "elevation": 1,
  "shadow_softness": 4,
```

### Screenshots

https://github.com/kivymd/KivyMD/assets/26806376/4118158d-1dcb-4f54-a48d-e04f597ae80c

### Versions

* OS: macOS 13.4.1 Ventura
* Python: both 3.9 and 3.11
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch
