### ISSUE TITLE
Navigation drawer closing issue

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#155]
In kivymd 0.103.0 when I am clicking on navigation drawer 's  OneLineAvatarListItem then it is not closing the navigation bar automatically every time I need to click on the close button why this is not closing automatically on click on OneLineAvatarListItem?

**Comment by HeaTTheatR** [comment]
@navjotcis This behavior is not implemented because the `NavigationDrawer` is an empty `MDCard` class. Closing you must control yourself.

https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/navigationdrawer.py#L292
