### ISSUE TITLE
Tap Target View on MDFloatingActionButtonSpeedDial

### ISSUE THREAD

**Issue by t0theRANCH** [kivymd/KivyMD#1552]
This is less of a feature request and more of a suggestion to add to documentation

I tried adding a Tap Target View to an MDFloatingActionButtonSpeedDial only to have the tap target view appear in a strange location. After many hours debugging, I realized the root of my issue was that the speed dial class itself was technically not the button I wanted to highlight with a Tap Target View. When adding the Tap Target View, I inserted the following to make the widget display as intended:

    def add_tap_target(self, *args):
        speed_dial = None
        for child in self.ids.speed_dial.children:
            if isinstance(child, MDFloatingRootButton):
                speed_dial = child
        self.tap_target_view = MDTapTargetView(
            widget=speed_dial,
            title_text="Title",
            description_text="This is a description",
            widget_position="right_bottom"
        )

### Versions

* OS: Ubuntu 22.04.3 LTS
* Python: 3.10
* Kivy: 2.20
* KivyMD: 1.2.0

**Comment by HeaTTheatR** [comment]
SpeedDial and TapTargetView are removed in KivyMD version 2.0.0
