### ISSUE TITLE
MDFileManager on android only list image file type ,other file type don't list

### ISSUE THREAD

**Issue by huligh70** [kivymd/KivyMD#1553]
### Description of the Bug

MDFileManager on android only list image file type ,other file type don't list
I'm not sure that  \
Is there a bug in "kivymd/uix/filemanager/filemanager.py" at line 513 
The logic bug in function show()

### Code and Logs
Part of buildozer.spec
```python
requirements = python3,
                          kivy==2.2.1,
                          https://github.com/kivymd/KivyMD/archive/master.zip,
                          cython==0.29.28
android.api=31
android.ndk=25b
```
Part of code

```python
file_choose=MDFileManager(exit_manager=self.exit_filechoose,select_path=self.select_file_path,preview=False,)
file_choose.show(primary_storage_dir)
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
I don't understand your question...

**Comment by huligh70** [comment]
> I don't understand your question...
en.....

When using the MDFileManager component, it works normally on the Windows platform, while on the Android platform, only files in image format are displayed in the file list, and other file formats are not displayed.

**Comment by HeaTTheatR** [comment]
I can't confirm it.

**Comment by huligh70** [comment]
OK,
Still very grateful for replying
![微信图片_20230915142230](https://github.com/kivymd/KivyMD/assets/45496476/b02fe25e-8f74-45a9-8fe7-5296908c948e)
![微信图片_20230915142239](https://github.com/kivymd/KivyMD/assets/45496476/72f36243-c562-4d28-a657-bd28083b4a7d)

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/filemanager/#kivymd.uix.filemanager.filemanager.MDFileManager.preview

**Comment by huligh70** [comment]
![2023-09-15_143602](https://github.com/kivymd/KivyMD/assets/45496476/a70017fe-5414-4e94-8e30-6937677e36ae)
The code work well on PC
