### ISSUE TITLE
MDDropdownMenu not functioning as expected.

### ISSUE THREAD

**Issue by ramayanbindas** [kivymd/KivyMD#1554]
I had tried all the available example present in the kivymd documentation related to MDDropdownMenu.
to run my system but it not works as shown picture below in the documentation.
How it is not working: During opening the list it shows the wite pop up with no items in it event provieded the items properly. Dosn't metter much because I had copy pasted the code as it is form the documetation.
For curisity I had try some dif
ferent approach to do that I just try to provide a extra key `viewclass` during creating the list items after running that code. It show the item over it but as I accepted as not.
It displaying one item more as I provided in the item list but with the blank white space over there.
However I am using python 3.10 and kivymd 1.1.1. So please give a answer what should I do.

**Comment by HeaTTheatR** [comment]
Create a new issue according to the rules...
