### ISSUE TITLE
Kivymd MDTabsBase

### ISSUE THREAD

**Issue by ramayanbindas** [kivymd/KivyMD#1555]
MDTabsbase is not recognised with in the .kv files as well as after importing it from kivymd.uix.tab.tab, Besides this it works from the script as examples mentioned in the docs. But why it can't  access by the .kv file?

**Comment by HeaTTheatR** [comment]
Most likely, widgets such as `MDTabs` and `MDDialog` cannot be used from KV files.

**Comment by ramayanbindas** [comment]
> Most likely, widgets such as `MDTabs` and `MDDialog` cannot be used from KV files.

Its okay I understand but have any one working to solve this issue this would improve consistency through out the project.

**Comment by HeaTTheatR** [comment]
So far, this is not the highest priority task for the KivyMD project
