### ISSUE TITLE
MDNavigationDrawer state

### ISSUE THREAD

**Issue by noembryo** [kivymd/KivyMD#156]
Just a quick question.

In previous versions, I there was an `MDNavigationDrawer.panel.state` that I could check, to see if the `MDNavigationDrawer` was open, so I would close it (e.g. when pressing the back button).
Trying to use the `MDNavigationDrawer.__state` does not work in the same way.
It gives me a very strange error:
`AttributeError: 'MDNavigationDrawer' object has no attribute '_Base__state'`
`Base` is my `root` class, but I don't know how it gets there..

### Versions

* OS: Win7x64 SP1
* Python: 3.7.2
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
@noembryo You do not need to check if the panel is open or closed. Just call the `toggle_nav_drawer ` method - it will open or close the panel itself, depending on the state

https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/navigationdrawer.py#L292

**Comment by noembryo** [comment]
Yes, but I don't want to open it if I press the back button for some other reason...

**Comment by HeaTTheatR** [comment]
@noembryo I don't understand what you mean...

**Comment by noembryo** [comment]
When I'm on the main page of an app and the MDNavigationDrawer is open, I want to close it by pressing the back button.
If the MDNavigationDrawer is closed, pressing the back button should exit the app, not re-open the MDNavigationDrawer...

**Comment by HeaTTheatR** [comment]
@noembryo 

https://github.com/HeaTTheatR/KivyMD/commit/11807153bc04ec464702498ca95c9551a1bba63c
https://github.com/HeaTTheatR/KivyMD/commit/6abb482b2ab4934e34e03b19b4a0b6dcd639b63a

**Comment by noembryo** [comment]
Great, thank you!

**Comment by Vampirebat** [comment]
im looking for these properties as well... how would i open and close the nav drawer from python...
also i have set the same properties as the nav drawer has like 
    swipe_edge_width =  NumericProperty
    elevation = NumericProperty
    enable_swiping = BooleanProperty
    swipe_edge_width = NumericProperty
    set_state = StringProperty

but i just cant create or find the class to change these via a python function
thanx
