### ISSUE TITLE
MDTextField hint_text is offset.

### ISSUE THREAD

**Issue by grinheckerdev** [kivymd/KivyMD#1560]
### Description of the Bug

MDTextField hint_text is offset.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp

kv = """
MDTextField:
	size_hint: .8, None
	pos_hint: {"center_y": 0.5, "center_x": 0.5}
	hint_text: "Login"
	mode: "rectangle"
"""

class BugExample(MDApp):
	def build(self):
		self.theme_cls.theme_style = "Dark"
		return Builder.load_string(kv)

if __name__ == '__main__':
	app = BugExample()
	app.run()
```

https://github.com/kivymd/KivyMD/assets/148703318/6a93e1c8-df32-43fc-8021-caf9941b9b0c

### Versions

* OS: macOS 13.4 (22F66)
* Processor / Video card: M2 (if this might help)
* Python: 3.11.4:d2340ef257
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by grinheckerdev** [comment]
KivyMD version: 1.1.1
Kivy version: 2.2.1

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch

**Comment by grinheckerdev** [comment]
Requirement already satisfied: kivymd==1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.1.1)

**Comment by grinheckerdev** [comment]
I've installed it using pip just like in the readme.md

**Comment by grinheckerdev** [comment]
`
pip3 install --upgrade kivymd==1.1.1
Requirement already satisfied: kivymd==1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.1.1)
Requirement already satisfied: kivy>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kivymd==1.1.1) (2.2.1)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kivymd==1.1.1) (10.0.0)
Requirement already satisfied: Kivy-Garden>=0.1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kivy>=2.0.0->kivymd==1.1.1) (0.1.5)
Requirement already satisfied: docutils in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kivy>=2.0.0->kivymd==1.1.1) (0.20.1)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kivy>=2.0.0->kivymd==1.1.1) (2.16.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd==1.1.1) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd==1.1.1) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd==1.1.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd==1.1.1) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd==1.1.1) (2023.5.7)
`

**Comment by HeaTTheatR** [comment]
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by grinheckerdev** [comment]
Nope, still:

https://github.com/kivymd/KivyMD/assets/148703318/832bdb18-9a10-4655-8f88-f4590466551a

**Comment by grinheckerdev** [comment]
With color schemes it looks even worse:
<img width="335" alt="Снимок экрана 2023-10-30 в 2 14 10 PM" src="https://github.com/kivymd/KivyMD/assets/148703318/7373f415-9bd0-42ef-a061-b0c818063869">

**Comment by HeaTTheatR** [comment]
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by vhuszaroakley** [comment]
![Screenshot_2023-11-26-11-52-12-82_c759c44d10a956b96f85cc66750ff86e.jpg](https://github.com/kivymd/KivyMD/assets/10073118/89346627-5242-49ae-ae20-e8f7be591ea7)

![Screenshot_2023-11-26-11-54-05-45_c759c44d10a956b96f85cc66750ff86e.jpg](https://github.com/kivymd/KivyMD/assets/10073118/4311de85-c95d-44b0-99df-0b8c8bda1d21)

I'm using the latest on dev branch and still have this issue.
