### ISSUE TITLE
MDTextField hint_text not scaling properly when dragging application between different screens/monitors

### ISSUE THREAD

**Issue by wcvo** [kivymd/KivyMD#1561]
### Description of the Bug

I am trying to use an MDTextField with hint_text, however the hint text is not scaling correctly when moving the kivy application window between different screens. To reproduce the problem, please run the code in your local environment - once the application opens and you can see the interface, notice how the hint text of the MDTextField looks good. Then, if you have an external monitor available to you, drag the application window to the external monitor and notice how the hint text does not scale correctly (it is much larger than it should be).

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.textfield import MDTextField
from kivy.config import Config

class MyApp(MDApp):
    def build(self):
        layout = BoxLayout(orientation='vertical', padding=10, spacing=10)
        
        param = "Test hint"
        input_field = MDTextField(multiline=False, pos_hint={'center_x': 0.5, 'center_y': 0.5}, hint_text=param.upper())
        layout.add_widget(input_field)
        
        btn = Button(text='Click me!', size_hint=(None, None), size=(150, 50), pos_hint={'center_x': 0.5})
        layout.add_widget(btn)
        
        return layout

if __name__ == '__main__':
    MyApp().run()

```

### Screenshots
![Screenshot 2023-10-31 at 9 54 19 AM](https://github.com/kivymd/KivyMD/assets/145414990/8c370645-4776-4a84-9356-c89f65ba75a4)
<img width="608" alt="Screenshot 2023-10-31 at 9 54 34 AM" src="https://github.com/kivymd/KivyMD/assets/145414990/ae2ea9f3-f494-425f-89c0-7974eef97c22">

### Versions

* OS: macOS 13.4.1
* Python: 3.11.4
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
