### ISSUE TITLE
MDExpansionPanel

### ISSUE THREAD

**Issue by phvbrito** [kivymd/KivyMD#1562]
Good afternoon, guys, see if anyone can help me, I've tried everything and I can't figure out what I'm doing wrong, I can't get the items to be displayed. This code will be modified later to display the final items, follow...

`#TelaConsultaPro.py

from kivymd.uix.screen import MDScreen
from kivy.uix.screenmanager import SlideTransition
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelThreeLine
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.button import Button

class TelaConsultaPro(MDScreen):
    
    def transicao_tela(self, tela):
        self.manager.transition = SlideTransition(direction="right")
        self.manager.current = tela

    def on_start(self):
    
        for i in range(10):
            panel = MDExpansionPanel(text="Painel " + str(i))
            content = BoxLayout(orientation="vertical")
            content.add_widget(Label(text="Conteúdo do painel " + str(i)))
            content.add_widget(Button(text="Botão " + str(i)))
            panel.content = content
            self.ids.box.add_widget(panel)
`

`#TelaConsultaPro.kv

<TelaConsultaPro>:
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Cadastro"
            left_action_items: [["menu", lambda x: app.callback()]]
            right_action_items: [["arrow-left", lambda x: root.transicao_tela("TelaPrincipal")]]
            elevation: 10
            md_bg_color: "#000000"
            specific_text_color: "white"

        MDScrollView:
            MDGridLayout:
                id: box
                cols: 1
                adaptive_height: True               
               
        MDTopAppBar:
            type: "bottom"
            mode: "free-end"
            elevation: 10
            md_bg_color: "#000000"`

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
