### ISSUE TITLE
Implement `MDRaisedIconButton`

### ISSUE THREAD

**Issue by acgc99** [kivymd/KivyMD#1563]
### Description of the Feature

We have `MDRectangleFlatIconButton` but not `MDRaisedIconButton` (like `MDRaisedButton` with an icon).

I asked on [discord](https://discord.com/channels/566880874789076992/1170071498497724437/1170071498497724437) about this, and the proposed answer was to change `MDRectangleFlatIconButton` background color, but I think that that is not optimal, primary palette might change and therefore colors, but not in this case because it has been specified. You can bypass this with bindings, but I still think that this has to be implemented on base. 

### Code and Logs

Just playing with source code (docstring not modified):

```
class MDRaisedIconButton(
    BaseButton, OldButtonIconMixin, ButtonContentsIconText
):
    """
    A flat button with (by default) rounded corners, a primary color fill,
    primary color text and a primary color icon on the left.

    For more information, see in the
    :class:`~BaseButton` and
    :class:`~OldButtonIconMixin` and
    :class:`~ButtonContentsIconText`
    classes documentation.
    """

    _default_md_bg_color = None
    _default_md_bg_color_disabled = None
    _default_theme_text_color = "Custom"
    _default_theme_icon_color = "Custom"
    _default_text_color = "PrimaryHue"
    _default_icon_color = "PrimaryHue"

```

### Versions

* OS: Windows 11
* Python: 3.11.4
* Kivy: 2.2.1
* KivyMD: 1.2.0.dev0

**Comment by HeaTTheatR** [comment]
At the moment, all the issue and suggestions for the KivyMD library version 1.2.0 are deprecated. All issue will be closed with the "deprecated" mark after the release of KivyMD version 2.0.0. The KivyMD library version 2.0.0 is based on the specifications of the material design version 3. And no widgets will be added/changed if they do not comply with this specification.
![bbb](https://github.com/kivymd/KivyMD/assets/16930280/97ef4b86-534a-4a37-b9b8-3ce619d9c120)
