### ISSUE TITLE
MDCard elevation crashes build on android but not when project is run from linux/windows

### ISSUE THREAD

**Issue by eviscerat** [kivymd/KivyMD#1564]
### Description of the Bug

If I give elevation to MDCard, the android built apk will crash, but not if I run the project from linux/wsl. There the elevation works fine.
I attached the buildozer spec and the logcat output of the crash.

## To reproduce

Comment the elevation in MDCard, rebuild and the android build will not crash

### Code and Logs

```python
from kivy.config import Config
from kivy.uix.screenmanager import NoTransition
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.app import MDApp
from kivy.core.window import Window
from kivy.lang import Builder

# Window.size = (2400, 1080)
# Window.size = (450,1000)
# Window.top = 1

kv = """
<LoginScreen>:
    MDCard:
        size_hint: (0.7, 0.5)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        elevation: 5
        padding: 25
        spacing: 25
        orientation: 'vertical'

        MDTextField:
            id: user
            hint_text: "username"
            mode: "round"
            size_hint_x: .85
            max_text_length: 40
            font_size: 18
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: passkey
            hint_text: "passkey"
            max_text_length: 40 #32 char
            mode: "round"
            size_hint_x: .85
            font_size: 18
            password: True
            pos_hint: {"center_x": 0.5}

        MDFillRoundFlatButton:
            text: 'Login'
            font_size: 18
            pos_hint: {'center_x': 0.5}
            size_hint_x: .85
            on_press: 
                root.manager.current = 'main'

<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        Button:
            text: 'My settings button'
        Button:
            text: 'Back to menu'
            on_press: root.manager.current = 'login'
"""
class LoginScreen(Screen):
    pass

class MainScreen(Screen):
    pass


class FlixlistApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "BlueGray"
        sm = ScreenManager(transition=NoTransition())
        sm.add_widget(LoginScreen(name='login'))
        sm.add_widget(MainScreen(name='main'))
        return sm


if __name__ == '__main__':
    FlixlistApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Ubuntu 22.04.2 LTS runing from windows 10 WSL
* Python: 3.10.12
* Kivy: 2.2.1
* KivyMD: 1.1.1
[buildozer_spec.txt](https://github.com/kivymd/KivyMD/files/13258908/buildozer_spec.txt)
[logcat_output.txt](https://github.com/kivymd/KivyMD/files/13258909/logcat_output.txt)

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch

**Comment by eviscerat** [comment]
> `buildozer android clean`

Thank you, this solved the issue.

**Comment by eviscerat** [comment]
> Use KivyMD from master branch

Using in build.spec:
`requirements = python3,kivy==master,https://github.com/kivymd/KivyMD/archive/master.zip,pillow==10.1.0`
did not solve the issue

**Comment by HeaTTheatR** [comment]
You are not using the KivyMD library master branch

**Comment by eviscerat** [comment]
> You are not using the KivyMD library master branch

I literally followed the steps as described in the readme:

![image](https://github.com/kivymd/KivyMD/assets/17407021/70097b41-959b-483b-becc-c841ed24ba64)

**Comment by HeaTTheatR** [comment]
`buildozer android clean`
