### ISSUE TITLE
Missing import for `IconLeftWidget` in list docs under "Custom list item".

### ISSUE THREAD

**Issue by UriyaHarpeness** [kivymd/KivyMD#1569]
This example does not work as-is, and is missing the import for `IconLeftWidget`.
I can open a PR to fix it if it's ok.
And in a more general note - is it maybe a possibility to make an automatic "sanity" check, that all these code snippets are valid (don't crash right away), for example all the samples that are marked as "complete" or something?

https://github.com/kivymd/KivyMD/blob/1152d3c31229b357336cb9e19cfaa2ba8c6941bc/kivymd/uix/list/list.py#L747C33-L747C47

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
