### ISSUE TITLE
No common MDToolbar in NavigationLayout

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#157]
There is no common MDToolbar on NavigationLayout every time we need to create MDToolbar for each screen.

**Comment by HeaTTheatR** [comment]
@navjotcis Yes it is.

**Comment by navjotcis** [comment]
@HeaTTheatR But every time when we switch the screen MDtoolbar is also moving with it so It will not look good

**Comment by HeaTTheatR** [comment]
@navjotcis Is there anything similar in KitchenSink examples?

**Comment by navjotcis** [comment]
@HeaTTheatR NO but when you add multiple screens on KitchenSink NavigationDrawer then you will face the same scenario.

**Comment by HeaTTheatR** [comment]
@navjotcis https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed

**Comment by navjotcis** [comment]
@HeaTTheatR yes when you use more than one screen in ScreenManager then you will face the issue. I have tried to make it common for all screens but in that case, it is not visible on the app

**Comment by HeaTTheatR** [comment]
@navjotcis Inherit your screens from your own `Screen` class in which there is already a `Toolbar`

**Comment by navjotcis** [comment]
@HeaTTheatR https://pastebin.com/Knmg8ihE

**Comment by HeaTTheatR** [comment]
@navjotcis It doesn’t tell me anything.

**Comment by navjotcis** [comment]
@HeaTTheatR But inheriting Toolbar screen is not resolving an issue because when you switch from one screen to another you Toolbar is also moving from right to left with a screen. I just want a fixed toolbar that will not move when the screen will change.

**Comment by HeaTTheatR** [comment]
@navjotcis Show your code and show the behavior of this code

**Comment by navjotcis** [comment]
@HeaTTheatR  This is the piece of code I am using please check it 
https://pastebin.com/iQueAPMC

**Comment by HeaTTheatR** [comment]
@navjotcis Your code is not complete, how can I run it?

**Comment by navjotcis** [comment]
@HeaTTheatR it is working please check it with python3.7 environment or kivymd (0.103)

**Comment by HeaTTheatR** [comment]
@navjotcis Your code is not complete, how can I run it?

**Comment by navjotcis** [comment]
@HeaTTheatR  what issue you are facing to run my code?

**Comment by HeaTTheatR** [comment]
@navjotcis Your code is not complete!

**Comment by navjotcis** [comment]
Hello,
Please find attached source files. It contains requirements.txt, please create a virtualenv with the requirements mentioned and then simply run main.py. I hope you will be able to run it.
[kivy-project.zip](https://github.com/HeaTTheatR/KivyMD/files/4021796/kivy-project.zip)

**Comment by HeaTTheatR** [comment]
@navjotcis Show me the minimal code that reproduces your error

**Comment by navjotcis** [comment]
Do you use Skype? or something more better to communicate ?

**Comment by navjotcis** [comment]
[sample_video.zip](https://github.com/HeaTTheatR/KivyMD/files/4021805/sample_video.zip)
Here check with the video when user click on test1 or test2 then NavigationDrawer is also moving with a screen so why NavigationDrawer is not common for all screens?

**Comment by HeaTTheatR** [comment]
@navjotcis 

https://github.com/HeaTTheatR/KivyMD/commit/d86a7a1ae2ca634d937701690d998ca53138b659

```python
NavigationLayout:

    MDToolbar:
        id: toolbar
        pos_hint: {"top": 1}
        title: "Navigation Drawer"
        md_bg_color: app.theme_cls.primary_color
        elevation: 10
        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

    ScreenManager:
        id: scr_mngr
        size_hint_y: None
        height: root.height - toolbar.height

        Test1:
            id:sc1
        Test2:
            id:sc2
        Test3:
            id:sc3

    MDNavigationDrawer:
        id: nav_drawer

        ContentNavigationDrawer:
            id: content_drawer
```
