### ISSUE TITLE
MDTopAppBar crash app

### ISSUE THREAD

**Issue by yehuu** [kivymd/KivyMD#1570]
### Description of the Bug

MDTopAppBar: - code in kv file crash the app if kivymd version set to kivymd==1.1.1 in buildozer.spec file
I have changed the version to kivymd==1.0.2 then it doesnt crash anymore. 
Specially in Xiamoi note models. For ex: MI Note 8

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
<Interface>:
    Screen:
        MDBoxLayout:
            orientation: "vertical"
            valign: "top"
            MDTopAppBar:
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch
