### ISSUE TITLE
My discord account has been compromised 

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#1572]
To the moderators of KivyMD,

My discord was recently hacked. In case you get any crypto messages, I noticed I have already been banned. And I also noticed some weird crypto messages sent to all my private contacts on discord. I have already broadcast a message stating that those links were not sent by me. I have currently gained back access, but I'm still in the process of changing my password and enabling 2 factor auth. I don't know if I will be granted access back into the discord community. But I'm looking forward to getting back into the community. 

PS: I have never said or done anything related in crypto, I only use crypto for making and receiving payments. I'm not a fan of crypto referral programs or trading.

**Comment by HeaTTheatR** [comment]
Yes, thanks for the message.
