### ISSUE TITLE
MDTextField ('utf-8')

### ISSUE THREAD

**Issue by OdzOdz** [kivymd/KivyMD#1573]
Hello,
There is an issue with typing Persian-Arabic text in MDTextField. You might suggest changing the font, but that doesn't work. Using libraries like python-bidi and arabic_reshaper can fix it with a lot of hassle, but there is still another problem. The issue is that the text is written from bottom to top. For example:

"What is your name?
How are you
Hello"

Please fix the UTF-8 issue in MDLabel and MDTextField as well.

**Comment by HeaTTheatR** [comment]
Not related to the KivyMD library.
