### ISSUE TITLE
MDLabel and MDTextField rtl bug

### ISSUE THREAD

**Issue by OdzOdz** [kivymd/KivyMD#1575]
### Description of the Bug

When we want to write rtl text, ltr texts are written in reverse
And when we want to write ltr text, rtl texts are written in reverse

And when we set the font direction, rtl texts are written from bottom to top on ltr
In general, writing rtl text in MDLabel and MDTextField has many problems

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
    MDLabel:
        font_name:'/path/font_name.ttf'
        font_direction:'rtl'
        #font_direction:'ltr'
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
It is not related to the KivyMD library
