### ISSUE TITLE
MDTextField hint_text does not update

### ISSUE THREAD

**Issue by ClaesFredo** [kivymd/KivyMD#1577]
Problem Description

MDTextField hint_text does not update when Chinese (Arab, etc) fonts are used. [Kivy TextInput work for text and hint_text]

This is not a font problem as the text variable works fine with the characters and fonts identical to those for the hint_text variable. 

A Chinese font can be downloaded here: https://fonts.google.com/noto/specimen/Noto+Sans+SC 

The figure shows the lengthier code example with different variations of defining the MDTextField. tf_1 is at the top.  
![MDTextField_hint_text_problem](https://github.com/kivymd/KivyMD/assets/12477840/92506815-c2a7-4c2f-965c-f88b56823200)

Minimal Code Example:

from kivymd.app import MDApp
from kivymd.uix.textfield import MDTextField
#
class DebugThis(MDApp):
    def build(self):        
        ch_fnt = './fonts/NotoSansSC-Regular.ttf'
        tf_3 = MDTextField( )
        tf_3.font_context=None
        tf_3.text='中国人'
        tf_3.font_name = ch_fnt 
        tf_3.hint_text='中国人'
        tf_3.font_name_hint_text = ch_fnt 
        return tf_3
#    
DebugThis().run()

Lengthier Code Example:

from kivymd.app import MDApp
from kivymd.uix.textfield import MDTextField
from kivy.uix.gridlayout import GridLayout
#
class DebugThis(MDApp):
    def build(self):        
        ch_fnt = './fonts/NotoSansSC-Regular.ttf'
        tf_1 = MDTextField(
            text='中国人',
            font_context=None,
            font_name = ch_fnt, 
            hint_text='中国人',
            font_name_hint_text = ch_fnt, 
            )
        tf_2 = MDTextField(
            text='中国人',
            font_context=None,
            )
        tf_2.font_name = ch_fnt
        tf_2.hint_text='中国人'
        tf_2.font_name_hint_text = ch_fnt 
#
        tf_3 = MDTextField( )
        tf_3.font_context=None
        tf_3.text='中国人'
        tf_3.font_name = ch_fnt 
        tf_3.hint_text='中国人'
        tf_3.font_name_hint_text = ch_fnt 
#
        gl = GridLayout(cols=1)
        gl.add_widget(tf_1)
        gl.add_widget(tf_2)
        gl.add_widget(tf_3)
        return gl
#    
DebugThis().run()

**Comment by HeaTTheatR** [comment]
Use fonts with Arabic/Chinese language support

**Comment by ClaesFredo** [comment]
The text variable would not render correctly if I did not use fonts with Chinese language support.  

This is not a font problem.

**Comment by HeaTTheatR** [comment]
@ClaesFredo https://discord.com/channels/566880874789076992/566880874789076994/1176284293618745423
