### ISSUE TITLE
OneLineAvatarIconListItem doesn't render text vertically in the middle

### ISSUE THREAD

**Issue by kristoffer-paulsson** [kivymd/KivyMD#158]
#### Description of the Bug

Some of the list items doesn't render the text vertically centered. This happens in my own app as well as in the kitchen sink.

### Code and Logs

Reproduces even in the kitchen sink app

### Screenshots

![image](https://user-images.githubusercontent.com/40502502/71739715-84e8b900-2e5a-11ea-9abf-b8080901022a.png)

![image](https://user-images.githubusercontent.com/40502502/71739698-76020680-2e5a-11ea-9457-8a0312b21ed5.png)

### Versions

* OS: macOS Catalina 10.15.2
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.103.0 - Beta

**Comment by HeaTTheatR** [comment]
@kristoffer-paulsson This is related to the use of the RecycleView and it is easily fixed.
