### ISSUE TITLE
Ошибка с MDLabel

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#1585]
Всем приветики,у вас тут какая то ошибка с MDLabel, раньше такого не было, спокойно сидел на версии 1.2.0 и тут обнову выкатитли,решил попробовать и ниче не выходит:
Код:
` MDLabel:
    adaptive_size:True
    text: 'Авторизация'
    halign: 'center'
    pos_hint: {'center_x': 0.5}`

Лог ошибки:
![res](https://github.com/kivymd/KivyMD/assets/138012612/1a92fa57-6ca5-4bec-bdea-fc7a796f0b1c)

* OS: Windows 11
* Python: 3.10
* Kivy: 2.3.0
* KivyMD: 2.0.1

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/label/label.py#L93

**Comment by ghost** [comment]
Спс, а будешь ли менять туторы в доках, а то там старый стиль написания

**Comment by HeaTTheatR** [comment]
The documentation has been fully updated.
