### ISSUE TITLE
Error Importing MDApp (cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils')

### ISSUE THREAD

**Issue by Fretless14** [kivymd/KivyMD#1587]
Hi,

In the main (development into v2.0.0) branch simply importing
`from kivymd.app import MDApp`

is causing an error:
```
 Traceback (most recent call last):
   File "/main.py", line 16, in <module>
     from kivymd.app import MDApp
   File "/venv/lib/python3.9/site-packages/kivymd/app.py", line 67, in <module>
     from kivymd.theming import ThemeManager
   File "/venv/lib/python3.9/site-packages/kivymd/theming.py", line 52, in <module>
     from materialyoucolor.utils.color_utils import argb_from_rgb
 ImportError: cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils' (/venv/lib/python3.9/site-packages/materialyoucolor/utils/color_utils.py)
```

### Versions

* OS: Mac Ventura 13.4
* Python: 3.9.13
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by HeaTTheatR** [comment]
How to install KivyMD?

**Comment by T-Dynamos** [comment]
@HeaTTheatR You might need to specify version of `materialyoucolor` in `setup.py`.

**Comment by Fretless14** [comment]
Ah yeah I forgot about dependencies outside of KivyMD;

I had a requirements.txt file that points to master, so I tried installing and had to upgrade my Kivy version and delete asynckivy from the requirements.txt file to update it - I came from kivymd==1.2.0.dev0

I'll try removing materalyoucolor from the requirements.txt file and see how it goes

**Comment by Fretless14** [comment]
Yep that fixed it. I agree with @T-Dynamos

**Comment by Fretless14** [comment]
Side note unrelated, are there docs published yet for 2.0? 

I only see 1.2.0.dev0, and would like to know what to replace obsolete widgets with (ie MDRaisedButton with -?)

**Comment by HeaTTheatR** [comment]
@Fretless14 The documentation is completely ready. But there is a problem with building documentation on GitHub. Until this problem is resolved, you can build locally on your computer:

```
cd docs
make html
```

**Comment by Fretless14** [comment]
gotchya thank you!

**Comment by Allamaris0** [comment]
What version of materialyoucolor is required? I can't install higher than 1.2.0

**Comment by HeaTTheatR** [comment]
@Allamaris0 Version `1.2.0` does not use the `materialyoucolor` library

**Comment by Allamaris0** [comment]
> @Allamaris0 Version `1.2.0` does not use the `materialyoucolor` library

I didn't mean version of kivymd but materialyoucolor. I can't install version higher than 1.2.0 with pip. So what version is required by kivymd 2.0.0  because I also got that error `cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils'`

**Comment by HeaTTheatR** [comment]
@Allamaris0 Please attach the full KivyMD installation log...

**Comment by Fretless14** [comment]
> > @Allamaris0 Version `1.2.0` does not use the `materialyoucolor` library
> 
> I didn't mean version of kivymd but materialyoucolor. I can't install version higher than 1.2.0 with pip. So what version is required by kivymd 2.0.0 because I also got that error `cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils'`

if you are installing from a requirements file (`pip install -r requirements.txt`), simply find materialyoucolor in the list in your requirements.txt file and remove it; kivymd requires it to be installed so it will fetch the one you need for you.

If you are just trying to do `pip install kivymd`, and you don't have materialyoucolor, you should be fine as well. If you already have it, uninstall it with `pip uninstall materialyoucolor`, then run `pip install kivymd` and you should be set as it will fetch the depended packages

**Comment by Allamaris0** [comment]
Ech you still don't understand me. I installed kivymd 2.0.0 with github link. It installed materialyoucolor version 1.2.0.  and I got the error 
```
from materialyoucolor.utils.color_utils import argb_from_rgb
 ImportError: cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils' (/venv/lib/python3.9/site-packages/materialyoucolor/utils/color_utils.py)
```
I can't install higher version of materialyoucolor
![obraz_2024-01-21_211754855](https://github.com/kivymd/KivyMD/assets/51059882/d26b0d6a-2869-4f9c-9a08-cbd0714eb6cc)

So I want to know what version is required for kivymd 2.0.0 because is not precised in setup.py

**Comment by HeaTTheatR** [comment]
```
pip install kivy
pip install https://github.com/kivymd/KivyMD/archive/master.zip
```

**Comment by T-Dynamos** [comment]
> Ech you still don't understand me. I installed kivymd 2.0.0 with github link. It installed materialyoucolor version 1.2.0. and I got the error
> 
> ```
> from materialyoucolor.utils.color_utils import argb_from_rgb
>  ImportError: cannot import name 'argb_from_rgb' from 'materialyoucolor.utils.color_utils' (/venv/lib/python3.9/site-packages/materialyoucolor/utils/color_utils.py)
> ```
> 
> I can't install higher version of materialyoucolor ![obraz_2024-01-21_211754855](https://private-user-images.githubusercontent.com/51059882/298409259-d26b0d6a-2869-4f9c-9a08-cbd0714eb6cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzE3MTcsIm5iZiI6MTcwNTg3MTQxNywicGF0aCI6Ii81MTA1OTg4Mi8yOTg0MDkyNTktZDI2YjBkNmEtMjg2OS00ZjljLTlhMDgtY2JkMDcxNGViNmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDIxMTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZjM0NDRmNzE4YWEwNWY4MTAwNGU2NDc3YWE2ZTQyOGI3NGJiZDRiOTNiMGExZGI5NjUzYzczMjYxNmU3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV0RH9rvYdmVIOV6YYLni1G_eswqvDXvA4npnmi7OKY)
> 
> So I want to know what version is required for kivymd 2.0.0 because is not precised in setup.py

Install `materialyoucolor` 2.0.5

**Comment by Allamaris0** [comment]
> ```
> pip install kivy
> pip install https://github.com/kivymd/KivyMD/archive/master.zip
> ```

I wrote that I installed kivymd from github link, so why do you write that I should install it when I have 2.0.0 installed? 
How many times I must write that I can't install materialyoucolor higher than 1.2.0 :tired_face: until you understand.
