### ISSUE TITLE
KivyMD Installation fails with error "Failed building wheel for materialyoucolor"

### ISSUE THREAD

**Issue by TechLearner18** [kivymd/KivyMD#1588]
### Description of the Bug

Trying to install KivyMD using both pip and git clone. Both exited with following

 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for materialyoucolor
Successfully built kivymd
Failed to build materialyoucolor
ERROR: Could not build wheels for materialyoucolor, which is required to install pyproject.toml-based projects

### Versions

* OS: 14.2.1 (23C71)
* Python: Python 3.8.2
* Kivy: 2.2.1
* KivyMD:

**Comment by HeaTTheatR** [comment]
Specify the OS version and the full stacktrace...

**Comment by TechLearner18** [comment]
OS Version: macOS Sonoma 14.2.1 

I also tried pip3 install materialyoucolor --upgrade
which is also having the same issue. Heres the log

pip3 install materialyoucolor --upgrade

Collecting materialyoucolor
  Using cached materialyoucolor-2.0.5.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow (from materialyoucolor)
  Using cached pillow-10.2.0-cp38-cp38-macosx_10_10_x86_64.whl.metadata (9.7 kB)
Using cached pillow-10.2.0-cp38-cp38-macosx_10_10_x86_64.whl (3.5 MB)
Building wheels for collected packages: materialyoucolor
  Building wheel for materialyoucolor (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for materialyoucolor (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      Skipping download...
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.14.6-x86_64-cpython-38
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor
      copying materialyoucolor/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_fruit_salad.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_monochrome.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_vibrant.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_fidelity.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_content.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_android.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_rainbow.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_tonal_spot.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_expressive.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/dynamic_scheme.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme_neutral.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/scheme.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      copying materialyoucolor/scheme/variant.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/scheme
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dislike
      copying materialyoucolor/dislike/dislike_analyzer.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dislike
      copying materialyoucolor/dislike/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dislike
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/quantize
      copying materialyoucolor/quantize/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/quantize
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      copying materialyoucolor/hct/viewing_conditions.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      copying materialyoucolor/hct/hct.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      copying materialyoucolor/hct/cam16.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      copying materialyoucolor/hct/hct_solver.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      copying materialyoucolor/hct/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/hct
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      copying materialyoucolor/utils/image_utils.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      copying materialyoucolor/utils/math_utils.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      copying materialyoucolor/utils/theme_utils.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      copying materialyoucolor/utils/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      copying materialyoucolor/utils/color_utils.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/utils
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/blend
      copying materialyoucolor/blend/blend.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/blend
      copying materialyoucolor/blend/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/blend
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/score
      copying materialyoucolor/score/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/score
      copying materialyoucolor/score/score.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/score
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      copying materialyoucolor/dynamiccolor/contrast_curve.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      copying materialyoucolor/dynamiccolor/material_dynamic_colors.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      copying materialyoucolor/dynamiccolor/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      copying materialyoucolor/dynamiccolor/dynamic_color.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      copying materialyoucolor/dynamiccolor/tone_delta_pair.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/dynamiccolor
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/contrast
      copying materialyoucolor/contrast/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/contrast
      copying materialyoucolor/contrast/contrast.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/contrast
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/temperature
      copying materialyoucolor/temperature/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/temperature
      copying materialyoucolor/temperature/temperature_cache.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/temperature
      creating build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/palettes
      copying materialyoucolor/palettes/core_palette.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/palettes
      copying materialyoucolor/palettes/__init__.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/palettes
      copying materialyoucolor/palettes/tonal_palette.py -> build/lib.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/palettes
      running build_ext
      building 'materialyoucolor.quantize.celebi' extension
      creating build/temp.macosx-10.14.6-x86_64-cpython-38
      creating build/temp.macosx-10.14.6-x86_64-cpython-38/materialyoucolor
      creating build/temp.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/quantize
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/Users/techlearner/kivyapp/pocketdict/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c materialyoucolor/quantize/celebi.cc -o build/temp.macosx-10.14.6-x86_64-cpython-38/materialyoucolor/quantize/celebi.o -fvisibility=hidden -g0 -std=c++17
      materialyoucolor/quantize/celebi.cc:17:10: fatal error: 'cpp/quantize/celebi.h' file not found
      #include "cpp/quantize/celebi.h"
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for materialyoucolor
Failed to build materialyoucolor
ERROR: Could not build wheels for materialyoucolor, which is required to install pyproject.toml-based projects

**Comment by T-Dynamos** [comment]
Materialyoucolor yet supports wheels only for 3.9 and 3.9+. You can try build from source `pip3 install git+https://github.com/T-Dynamos/materialyoucolor-pyhton`

**Comment by TechLearner18** [comment]
I moved to an older version of Kivymd (1.1.1)
