### ISSUE TITLE
MDApp on Android

### ISSUE THREAD

**Issue by BernardinD** [kivymd/KivyMD#159]
#### Description of the Bug

I am trying to build an application that used the previous implementation of some of the KivyMD modules. When attempting to update the application to the current implementation I get the error " ModuleNotFoundError: No module named 'kivymd.app' " when ran on my android.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.clock import Clock
from kivy.core.clipboard import Clipboard
from kivy.logger import LOG_LEVELS, Logger
from kivy.properties import StringProperty, BooleanProperty
from kivy.uix.screenmanager import Screen

...

class MainApp(MDApp):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def build(self):
        self.icon = "docs/images/icon.png"

def main():
    MainApp().run()


### Versions

* OS: Android 7.0
* Python: python-for-android==2019.10.6
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/wiki/Modules-Material-App

**Comment by BernardinD** [comment]
Hi, thanks for getting back to me so quickly. 

It was my mistake. I had kivy-garden's version of kivymd previously installed and it conflicted.

Running "buildozer android clean" fixed the issue
