### ISSUE TITLE
kivymd version 1.2.0 not exist documentation on oficial web page but it exist in pip

### ISSUE THREAD

**Issue by SoroMoise** [kivymd/KivyMD#1594]
### Kivymd doc is not complet

when i do : 
`pip install kivymd==latest` 
i have : 
`ERROR: Could not find a version that satisfies the requirement kivymd==latest (from versions: 0.1.0, 0.1.1, 0.1.2, 0.100.2, 0.102.0, 0.102.1, 0.103.0, 0.104.0, 0.104.1, 0.104.2, 1.0.1, 1.0.2, 1.1.1, 1.2.0)
ERROR: No matching distribution found for kivymd==latest`

that is normal, but when i go to to kivymd doc i don't see the last version as `1.2.0` [kivymd doc](https://kivymd.readthedocs.io/en/1.2.0)

### Versions

* OS: Ubuntu 22.04.3 LTS
* Python: Python 3.11.0rc1
* Kivy: 2.3.0
* KivyMD:

**Comment by HeaTTheatR** [comment]
KivyMD version 1.2.0 is no longer supported

**Comment by SoroMoise** [comment]
ok thank

**Comment by cederom** [comment]
yeah, but the package is avialable.. while 2.0.0 is not out yet as a package. shall we stick to 1.1.1 until 2.0.0 is out?

would it be possible to at least add TAG for 1.2.0 on GitHub to see what works and how?
