### ISSUE TITLE
DatePicker little popups don't disappear

### ISSUE THREAD

**Issue by lucashudson-eng** [kivymd/KivyMD#1596]
Hello!

I am using DatePicker as a Dialog. But when I press the OK button after choosing the date, sometimes the popups of the days of the weekend, Next month or Previous month dont't disappear, staying in the application in any screen I am in until I close it.

The problem is shown in the images below.

![Screenshot_2](https://github.com/kivymd/KivyMD/assets/72749364/93276fc8-ecfd-4997-b431-a4c968bfd242)
![Screenshot_1](https://github.com/kivymd/KivyMD/assets/72749364/c730107a-0119-436a-8ba3-5ca4674843dd)
![WhatsApp Image 2024-01-24 at 20 48 44](https://github.com/kivymd/KivyMD/assets/72749364/340433a1-0821-41ba-8b00-19788dd280fe)

**Comment by HeaTTheatR** [comment]
The version of the KivyMD library that you are using is not supported. Use version 2.0.0
