### ISSUE TITLE
WindowController: _WindowSDL2Storage issue 

### ISSUE THREAD

**Issue by AnEx-ofc** [kivymd/KivyMD#1597]
# WindowController example from doc not working on Ubuntu

OS: Ubuntu 22.04.3 LTS

## Suggestion:
- remove: ` from kivy.core.window.window_sdl2 import WindowSDL`
 - change: ` 
      def _on_resize(
        self, window: Window, width: int, height: int
         ) -> None:
 `

## Logs:

> [INFO   ] [Logger      ] Record log in /home/hitech/.kivy/logs/kivy_24-01-28_18.txt
> [INFO   ] [Kivy        ] v3.0.0.dev0
> [INFO   ] [Kivy        ] Installed at "/home/hitech/.local/lib/python3.10/site-packages/kivy/__init__.py"
> [INFO   ] [Python      ] v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
> [INFO   ] [Python      ] Interpreter at "/bin/python3"
> [INFO   ] [Logger      ] Purge log fired. Processing...
> [INFO   ] [Logger      ] Purge finished!
> [INFO   ] [KivyMD      ] 2.0.1.dev0, git-Unknown, 2024-01-27 (installed at "/home/hitech/.local/lib/python3.10/site-packages/kivymd/__init__.py")
> [INFO   ] [Factory     ] 195 symbols loaded
> pygame 2.5.2 (SDL 2.28.2, Python 3.10.12)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.5.1
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_ffpyplayer 
> [INFO   ] [Text        ] Provider: pygame
> [INFO   ] [Window      ] Provider: pygame
> [WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/hitech/.local/lib/python3.10/site-packages/kivy/core/window/window_pygame.py line 42.Called from /home/hitech/.local/lib/python3.10/site-packages/kivy/core/__init__.py line 71 by core_select_lib().
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] Backend used <gl>
> [INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1'>
> [INFO   ] [GL          ] OpenGL vendor <b'Intel'>
> [INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) Xe Graphics (TGL GT2)'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 6
> [INFO   ] [GL          ] Shading version <b'4.60'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <32>
> [WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/hitech/.local/lib/python3.10/site-packages/kivy/core/image/img_pygame.py line 27.Called from /home/hitech/.local/lib/python3.10/site-packages/kivy/core/image/__init__.py line 460 by load().
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
>  Traceback (most recent call last):
>    File "/home/hitech/Projects/Deploy_Utils/viwer.dev/test2.py", line 5, in <module>
>      from kivymd.uix.controllers import WindowController
>    File "/home/hitech/.local/lib/python3.10/site-packages/kivymd/uix/controllers/__init__.py", line 11, in <module>
>      from .windowcontroller import WindowController
>    File "/home/hitech/.local/lib/python3.10/site-packages/kivymd/uix/controllers/windowcontroller.py", line 37, in <module>
>      from kivy.core.window.window_sdl2 import WindowSDL
>    File "/home/hitech/.local/lib/python3.10/site-packages/kivy/core/window/window_sdl2.py", line 28, in <module>
>      from kivy.core.window._window_sdl2 import _WindowSDL2Storage
>  ModuleNotFoundError: No module named 'kivy.core.window._window_sdl2'

**Comment by HeaTTheatR** [comment]
You are using Kivy 3.0.0.dev0 which has not been released yet

**Comment by AnEx-ofc** [comment]
I was facing issue with  kivy = v2.3.0 and kivymd = 1.1.1 that while using the app randomly and suddenly hole OS got stuck even mouse and keyboard not responds. That's why I was exploring the kivy master if got any better result.
Please let me know if this is a known issue, or I have done something wrong.
Thanks
