### ISSUE TITLE
Full MDBottomSheet not showing with narrow window size.

### ISSUE THREAD

**Issue by kristoffer-paulsson** [kivymd/KivyMD#160]
#### Description of the Bug

My MDBottomSheet is partially hidden when using narrow window sizes.
Can this be altered or overridden so that the full content is showing?

### Versions

* OS: macOS Catalina 10.15.2
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.103.0 Beta

**Comment by Jonatanjrss** [comment]
Show  your code, please.

**Comment by kristoffer-paulsson** [comment]
It is a Kivy-macOS specific problem. I solved it using pos_hint={"center_x": .5, "center_y": .5} on MDBottomSheet and MDDialog.

**Comment by HeaTTheatR** [comment]
Fixed in the master branch.
