### ISSUE TITLE
Implement new "stretch and bounce back" scroll effect

### ISSUE THREAD

**Issue by T-Dynamos** [kivymd/KivyMD#1602]
With Android 12:

| Pull stretch | Fling stretch |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/19204050/119530567-a65d8400-bd72-11eb-9785-7d8f840b7b8f.gif)  | ![image](https://user-images.githubusercontent.com/19204050/119530578-abbace80-bd72-11eb-9ce1-c4caf191e54f.gif) |

> Starting in Android 12 (API level 31), the visual elements stretch and bounce back on a drag event and fling and bounce back on a fling event.

Source: https://developer.android.com/develop/ui/views/touch-and-input/gestures/scroll

**Comment by HeaTTheatR** [comment]
Perhaps this will somehow help in the implementation  of this effect - https://www.youtube.com/watch?v=_HP3T5NLXlQ
