### ISSUE TITLE
Broken discord invite link in README

### ISSUE THREAD

**Issue by BlackCatDevel0per** [kivymd/KivyMD#1603]
Hi, I can't join to the server via an invitation link and I was recently banned for no reason or explanation.. But I'm more interested in why the link doesn't work for my friends too? (they have never been on this server before)

[https://](https://discord.gg/wu3qBST)[disc](https://discord.gg/wu3qBST)[ord.gg/wu3qBST](https://discord.gg/wu3qBST)

**Comment by HeaTTheatR** [comment]
The link is working.

**Comment by BlackCatDevel0per** [comment]
![Screenshot_20240201-131615952](https://github.com/kivymd/KivyMD/assets/61960169/9f84cb29-3572-4466-be0b-f149a89008b4)
![Screenshot_20240201-131622759](https://github.com/kivymd/KivyMD/assets/61960169/b47473e3-7013-4192-bbe6-501cc6fd26bf)
(my second account & my friend on this link..)

**Comment by HeaTTheatR** [comment]
Contact Discord support. The link is working

**Comment by BlackCatDevel0per** [comment]
> Contact Discord support. The link is working

Ok.. Could you please give me contacts? I didn't find..

**Comment by HeaTTheatR** [comment]
@BlackCatDevel0per https://support.discord.com

**Comment by BlackCatDevel0per** [comment]
I wrote to the admin, and it turned out that the server bot banned me for some code block XD

But it seems the link doesn’t really work for everyone, which is strange.. Any way, the problem is probably really with discord..

**Comment by BlackCatDevel0per** [comment]
I wrote to the admin, and it turned out that the server bot banned me for some code block XD

But it seems the link doesn’t really work for everyone, which is strange.. Any way, the problem is probably really with discord..
