### ISSUE TITLE
Impossible to access menu items properties

### ISSUE THREAD

**Issue by GXcells** [kivymd/KivyMD#1606]
Is there a simple way to access the items of a menu using ids? 

Currently it seems impossible. Only some really unnecessary complicated solutions such as 
https://stackoverflow.com/questions/51861245/python-kivy-kivymd-how-to-fetch-values-of-mddropdownmenu

Any update concerning that issue?

**Comment by HeaTTheatR** [comment]
```python
        menu_items = [
            {
                "text": f"Item {i}",
                "on_release": lambda x=f"Item {i}": self.menu_callback(x),
            } for i in range(5)
        ]
        self.menu = MDDropdownMenu(
            header_cls=MenuHeader(),
            caller=self.screen.ids.button,
            items=menu_items,
        )

    def menu_callback(self, text_item):
        print(text_item)```

**Comment by GXcells** [comment]
Yes that is a workaround and  I should probably use something like that.

Still, it would be useful to be able to directly call the properties of the menu items.

**Comment by HeaTTheatR** [comment]
I can't imagine a situation where this might be necessary.

**Comment by GXcells** [comment]
Yes that is true. I was so fixating on getting that to work that I did not think that we actually don't need it.
