### ISSUE TITLE
ContentNavigationDrawer response issue

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#161]
when I am clicking on the navigation drawer button then it is not responding properly you can see in the video given below
[sample.zip](https://github.com/HeaTTheatR/KivyMD/files/4021969/sample.zip)

**Comment by HeaTTheatR** [comment]
@navjotcis 
![ezgif-7-19697838c5fb](https://user-images.githubusercontent.com/16930280/71766720-e587fc80-2f13-11ea-835a-1569fb9b5969.gif)

**Comment by navjotcis** [comment]
[testapp.zip](https://github.com/HeaTTheatR/KivyMD/files/4021989/testapp.zip)
Please check this video

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer

**Comment by navjotcis** [comment]
when you click it multiple times then only you can face the issue or some time it will appear on the first click please check this

**Comment by HeaTTheatR** [comment]
I do not see any problems.

**Comment by navjotcis** [comment]
[test_it.zip](https://github.com/HeaTTheatR/KivyMD/files/4022013/test_it.zip)
try to make the project with given zip then you will face the issue

**Comment by HeaTTheatR** [comment]
I do not see any problems.
![ezgif-7-446b9ef5e79a](https://user-images.githubusercontent.com/16930280/71767025-24b84c80-2f18-11ea-8a39-40a3b8e6fcc5.gif)

**Comment by navjotcis** [comment]
[test.zip](https://github.com/HeaTTheatR/KivyMD/files/4022036/test.zip)
see video till the end this issue appears when you click it again and again

**Comment by HeaTTheatR** [comment]
Your problem cannot be reproduced!

**Comment by lakshyacis** [comment]
@HeaTTheatR Me also facing the same issue. Please have look given below file
[issue.zip](https://github.com/HeaTTheatR/KivyMD/files/4025773/issue.zip)
You can also replace the 2 files from the demo app, then you'll get my code.
[kivy_project1.zip](https://github.com/HeaTTheatR/KivyMD/files/4025776/kivy_project1.zip)

**Comment by lakshyacis** [comment]
@HeaTTheatR Me also facing the same issue. Please have look given below file
Sometimes it works fine and sometimes not. So, please test it more number of times.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53042932/71814709-442fb080-30a3-11ea-8ea6-461e3b6f07c0.gif)

**Comment by lakshyacis** [comment]
You can also replace the 2 files from the demo app, then you'll get my code.
kivy_project1.zip
