### ISSUE TITLE
MDLabel text size not changing 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1615]
MDLabel:
    		#size_hint_y:None
    		#height:self.texture_size[1]
    		font_size:'50sp'
    		text:'3x10=?'
    		pos_hint_x:{'center_x':0.5}
    		halign:'center'

### Screenshots
![image](https://github.com/kivymd/KivyMD/assets/57060638/991a2ebb-0746-4b7b-932a-a35f1fd3f1e4)

### Versions

* OS: kubuntu 
* Python:3.10 
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/themes/theming/#kivymd.theming.ThemableBehavior.theme_font_size

```
MDLabel:
    theme_font_size: "Custom"
    font_size:'50sp'
```
