### ISSUE TITLE
pip install kivymd == 2.0.0 not installing 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1616]
pip install kivymd==2.0.0

**Comment by HeaTTheatR** [comment]
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by argades** [comment]
This pip install https://github.com/kivymd/KivyMD/archive/master.zip don't download the real  kivymd==2.0.0

How really download the 2.0.0 version?
There ins't release link.
Thanks

**Comment by HeaTTheatR** [comment]
> This pip install https://github.com/kivymd/KivyMD/archive/master.zip don't download the real kivymd==2.0.0
> 
> How really download the 2.0.0 version? There ins't release link. Thanks

https://github.com/kivymd/KivyMD/issues/1616#issuecomment-1929894426
