### ISSUE TITLE
KV file not recognising MDRaisedButton

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1617]
error
kivy.factory.FactoryException: Unknown class <MDRaisedButton>

    	  MDGridLayout:
    		  cols:2
    		  MDRaisedButton:
    		  Button:
    		  Button:
    		  Button:
### Versions

* OS: 
* Python: 3.10
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0,

**Comment by HeaTTheatR** [comment]
https://kivymd.readthedocs.io/en/latest/components/button/#api-break

**Comment by Sahil-pixel** [comment]
width of mdbutton not changing 

MDButton:
    			#pos_hint_x:{'center_x':0.25}
    			width:'60dp'
    			

    			style: "filled"
    			MDButtonText:
        			text: "Filled"
        			width:'60dp'

**Comment by HeaTTheatR** [comment]
@Sahil-pixel https://kivymd.readthedocs.io/en/latest/components/button/#customization-of-buttons
