### ISSUE TITLE
OneLineAvatarListItem or ContentNavigationDrawer response issue

### ISSUE THREAD

**Issue by lakshyacis** [kivymd/KivyMD#162]
when I am clicking on the navigation drawer button then it is not responding properly you can see in the video given below
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53042932/71876251-54e83100-314c-11ea-8065-38046499ee4d.gif)
You can also replace the 2 files from the demo app, then you'll get my code.
[kivy_project1.zip](https://github.com/HeaTTheatR/KivyMD/files/4029338/kivy_project1.zip)

**Comment by ArtemSBulgakov** [comment]
This will be fixed soon

**Comment by HeaTTheatR** [comment]
Attach only working examples with minimal code that can be run without additional manipulations

**Comment by lakshyacis** [comment]
Check The working code given below.
Try to test a minimum of 5-6 times, then you'll face the same issue which I'm facing. Sometimes, it will work on the first or second time, but the maximum time we have to click it more time to close the navigation window. So, please check it and help.
[test.zip](https://github.com/HeaTTheatR/KivyMD/files/4030145/test.zip)

**Comment by HeaTTheatR** [comment]
@lakshyacis There are no mistakes! Give a detailed algorithm of actions until the moment when you get an error

**Comment by HeaTTheatR** [comment]
@lakshyacis Your problem cannot be reproduced!

**Comment by lakshyacis** [comment]
@HeaTTheatR please put print statement inside navigationdrawer.py then you will get what is happening in the background
so please make it like that
```
def toggle_nav_drawer(self):
    if self.__state == "open":
        self.animation_close()
        print('toggle....................................', self.__state)
    elif self.__state == "close":
        self.animation_open()
        print('toggle....................................', self.__state)
```
and see what is printing on terminal
![Screenshot from 2020-01-07 16-44-01](https://user-images.githubusercontent.com/53042932/71891910-a6ed7e80-316d-11ea-9769-cfd4a41e54f2.png)

__________________________
VIDEO:
[console.zip](https://github.com/HeaTTheatR/KivyMD/files/4030343/console.zip)

**Comment by HeaTTheatR** [comment]
@lakshyacis There are no mistakes! Give a detailed algorithm of actions until the moment when you get an error.  Your problem cannot be reproduced!
