### ISSUE TITLE
 EM_X86_64 (62) instead of EM_AARCH64 (183)

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1621]
# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,https://github.com/kivymd/KivyMD/archive/master.zip,materialyoucolor,exceptiongroup,asyncgui,asynckivy,pillow
# (str) Custom source folders for requirements

error logs 
app/arm64-v8a/kivymd/app.py", line 67, in <module>
02-09 22:57:17.449 28784 28852 I python  :    File "/home/sahil/Math_Puzzle/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/kivymd/theming.py", line 58, in <module>
02-09 22:57:17.449 28784 28852 I python  :    File "/home/sahil/Math_Puzzle/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/materialyoucolor/quantize/__init__.py", line 1, in <module>
02-09 22:57:17.449 28784 28852 I python  :  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
02-09 22:57:17.449 28784 28852 I python  : Python for android ended.

**Comment by HeaTTheatR** [comment]
`p4a.source_dir = /path/to/python-for-android`

**Comment by HeaTTheatR** [comment]
Try `p4a.branch = develop`

**Comment by emendir** [comment]
> Try `p4a.branch = develop`

In January 2025, this is still the solution to this issue.

**Comment by Novfensec** [comment]
> > Try `p4a.branch = develop`
> 
> In January 2025, this is still the solution to this issue.

Just add x86_64 to `android.archs` in `buildozer.spec` like this;

This will increase app size though.

```spec
android.archs = armeabi-v7a, arm64-v8a, x86_64
```

**Comment by emendir** [comment]
> > > Try `p4a.branch = develop`
> > 
> > 
> > In January 2025, this is still the solution to this issue.
> 
> Just add x86_64 to `android.archs` in `buildozer.spec` like this;
> 
> This will increase app size though.
> 
> android.archs = armeabi-v7a, arm64-v8a, x86_64

No. The issue isn't that we're having trouble running the app on an x86-64 machine, the issue is that we're having trouble running the app on an arm64 machine, and the default p4a seems to have a bug in which it provides x86_64 binaries in an arm64 app, but the develop branch of p4a seems to have solved that.

**Comment by Novfensec** [comment]
@emendir I am working on an app which needs `x86_64` native libraries to run some components on my device Android 14 Amd64 and I made this change and it works on Amd64 Arm64 and whatever. 

The fact is that it builds natively for all aarchs at the same time which though increases the app size.

I never used the develop branch!!!
You may give a try to this.

**If the `develop` branch has any additional setting to itself include `x86_64` native libraries whether defined in android.archs or not and you have no errors, that's also good!**

Also they have upgraded the `master` branch too, so now one might not have trouble using that.
