### ISSUE TITLE
MDGridlayout adaptive_height: True is not working 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1623]
##
TACKeyBoard:
    		key_enter:root.call_key_enter
    		key_update:root.call_key_update
    		pos_hint:{"x":0.0,"y":0.0 }
    		size_hint_x:1
    
##3

![Screenshot_20240215_202931](https://github.com/kivymd/KivyMD/assets/57060638/d67a5057-fd2b-405b-a075-c701060ce7c0)
![Screenshot_20240215_203007](https://github.com/kivymd/KivyMD/assets/57060638/81fc8869-f100-4587-8021-6612b15d7bb1)

### Screenshots

Remove this section if no images here

### Versions

* OS: kubuntu 
* Python: 3.10
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0,

**Comment by HeaTTheatR** [comment]
Attach minimal code

**Comment by T-Dynamos** [comment]
@Sahil-pixel I speculate that your `TACKeyBoard` is `GridLayout` instead of `MDGridLayout`. As you are using canvas for color instead `md_bg_color`.

Closing as it is not reproducable, test code:

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel

KV = """
MDBoxLayout:
    orientation:"vertical"
    Widget:
    MDGridLayout:
        md_bg_color:app.theme_cls.primaryColor
        adaptive_height:True
        size_hint_x:None
        width:dp(100)
        cols:1
        id:main_grid
    MDButton:
        style: "elevated"
        pos_hint: {"center_x": .5, "center_y": .1}
        on_release:
            main_grid.add_widget(app.MDLabel(text="TEST", size_hint_y=None, height=dp(50)))
        MDButtonIcon:
            icon: "plus"
        MDButtonText:
            text: "Add"
"""

class Example(MDApp):
    
    MDLabel = MDLabel

    def build(self):
        return Builder.load_string(KV)

Example().run()
```
