### ISSUE TITLE
kivymd: No source code for this example

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#164]
I want to create a progress and activity circular moving bar just as shown in the screenshot.But when i click on ''source code" it gives a toast "no source code for this example".
Does anyone know how to animate this moving circular progress &activity bar?
This is from kivymd projec
![Screenshot from 2020-01-12 11-46-01](https://user-images.githubusercontent.com/58817288/72214959-89843000-3532-11ea-866a-46d8420064f6.png)
t.

**Comment by HeaTTheatR** [comment]
While the source code examples in the `KitchenSink` do not work - https://github.com/HeaTTheatR/KivyMD/blob/master/demos/kitchen_sink/libs/kv/progress.kv

**Comment by atheistrepublic** [comment]
How to use this inside a class.I mean i know how to use this from .kv file but i want to use it inside another python class.
For example :
`class Anoop(Screen):
 def anoop(self):
            self.spin1=MDSpinner() 
            self.spin1.pos_hint={'center_x': .5, 'center_y': .5}
            self.spin1.size_hint=(None, None)
            self.spin1.size=dp(46), dp(46)
            self.spin1.active=True
`

**Comment by atheistrepublic** [comment]
How to use this like this:

class Anoop(Screen):
 def anoop(self):
            self.spin1=MDSpinner() 
            self.spin1.pos_hint={'center_x': .5, 'center_y': .5}
            self.spin1.size_hint=(None, None)
            self.spin1.size=dp(46), dp(46)
            self.spin1.active=True
