### ISSUE TITLE
Does palate change work?

### ISSUE THREAD

**Issue by MrBillium** [kivymd/KivyMD#1645]
I originally posted this on stackoverflow  couple of weeks ago but got no replies

I spent a few hours getting my KivyMD 1.2 app running on 2.0 and it works now but the colors are horrible. I tried setting and changing palate and I can see that the App is accepting my new palate string but none of the widgets are changing any colors. 
My 1.2 app has a palate changer screen which works as expected but I have been unable to get 2.01 Dev0 to change colors on anything. 
Is this broken or have you changed what the palate setting is supposed to do?

        ```class myApp(MDApp):
        
              def build(self):
                  # changing style works but primary_palate makes no color changes to any of the Widgets in my app!
                  self.theme_cls.theme_style = "Dark"
                  self.theme_cls.primary_palette = "Green"
                  # self.theme_cls.theme_style = "Light"
                  # self.theme_cls.primary_palette = "Red"



I tried running your examples/dynamic_color_schemes.py  too and could not get that to visibly change palate colors either.

**Comment by T-Dynamos** [comment]
> I can see that the App is accepting my new palate string but none of the widgets are changing any colors.

Please attach minimal code.

**Comment by MrBillium** [comment]
Ok, I built a 1 button hello world in a new venv and that is working in
that changing primary palate does indeed change the button color.
So, I need to strip down a copy of my ( large) app until I get color
changes working too.
Busy week for me so it may take a while before I report back on the cause.
