### ISSUE TITLE
Minimum required OpenGL version (2.0) NOT found!

### ISSUE THREAD

**Issue by HugoP** [kivymd/KivyMD#1668]
### Description of the Bug

When I run a minimal example on Windows 10 with Python 3.11.0, Kivy 2.3.0 and KiviMD 2.0.1.dev0

I get [CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

I found a work around for kivy
```python
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'
```

But this does not work with kivymd.

Any ideas?

### This works

```python
from kivy.app import App
from kivy.uix.label import Label

# Work around that works
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'


class MainApp(App):
    def build(self):
        return Label(text="Hello, World")


MainApp().run()
```

### And this does not

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel

# Work around that does not work
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'


class MainApp(MDApp):
    def build(self):
        return MDLabel(text="Hello, World", halign="center")


MainApp().run()

```

### Screenshots

![image](https://github.com/kivymd/KivyMD/assets/20987887/31d430f6-5d6d-4948-9233-99907aa990dd)

### Versions

* OS: Microsoft Windows [Version 10.0.19045.4170]
* Python:  3.11.0
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by T-Dynamos** [comment]
I suspect that:
```python
# Work around that does not work
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'
```
this should be added at top of file, before kivymd import.
