### ISSUE TITLE
Python self.theme_cls.backgroundColor set after on_start() 

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#1674]
### Description of the Bug

In the theming example  https://kivymd.readthedocs.io/en/latest/themes/theming/ , the KV version works, but the Python version does not.  

It fails because in the example  `self.theme_cls.backgroundColor == [1.0, 1.0, 1.0, 1.0]` when used.
It appears the value is correctly set some time step after on_start, as shown by adding

```
    def on_start(self):
        super().on_start()
        print('Background  Color is ',self.theme_cls.backgroundColor)
```

This is, I assume, an issue with KivyMD, not with the example.

### Screenshots

Python code example, expected (and KV) behavior is a dark background 

![Screenshot 2024-04-13 170357](https://github.com/kivymd/KivyMD/assets/34464649/4fa2c0b7-1f37-4e80-870d-272d5fd0a82b)

Expected behavior shown in the example:

![primary-palette-m3](https://github.com/kivymd/KivyMD/assets/34464649/81c09b48-fdf6-4552-a019-caade0f78535)

### Versions

* OS: Windows 11
* Python: 3.11.1
* Kivy: 2.3.0
* KivyMD: 2.01.dev0

**Comment by T-Dynamos** [comment]
@RobertFlatt Hi!, Please test #1675

**Comment by RobertFlatt** [comment]
@T-Dynamos 

https://github.com/kivymd/KivyMD/pull/1675 works on Windows. Thanks.

**Comment by facutoledo** [comment]
I'm experiencing a similar issue, when the application is loaded, the theme_cls.background and others are set to [1,1,1,1] value.
I'm having a similar issue with the examples.
When implementing a button to toggle theme_cls.theme_style between Dark and Light, the changes are reflected in most controls, except for the background of the screen. 
To change the backgraund color of the screen, I have to do self.md_bg_color = self.theme_cls.backgroundColor within the button function.
The code below is the last thing I was traying:
```
from kivy.clock import Clock
from kivymd.uix.screenmanager import ScreenManager
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.button import MDButton, MDButtonText
from kivymd.uix.label import MDLabel

class ConfigScreen(MDScreen):
    def __init__(self, **kw):
        super().__init__(**kw)
        
        self.app=MDApp.get_running_app()
        self.theme_cls = MDApp.get_running_app().theme_cls
        self.md_bg_color = self.theme_cls.backgroundColor

        list_items = MDBoxLayout(
            orientation="vertical",
        )
        list_items.add_widget(
            MDLabel(
                id="label",
                text="Press Style Button",
                font_style="Title",
                role="large"
                )
            )
        
        list_items.add_widget(
            MDButton(
                MDButtonText(
                    text="Style"),
                on_release=self.set_theme_style
            )
        )
        list_items.add_widget(
            MDButton(
                MDButtonText(
                    text="Palette"),
                on_release=self.set_color_palette
            )
        )
        self.add_widget(list_items)
    
    def set_theme_style(self, *args):
        self.theme_cls.theme_style = (
            "Dark" if self.theme_cls.theme_style == "Light" else "Light"
        )
        self.md_bg_color = self.theme_cls.backgroundColor        

    def set_color_palette(self, *args):
        self.theme_cls.primary_palette = (
            "Orange" if self.theme_cls.primary_palette == "Red" else "Red"
        )

    def volver(self, *args):
        pass

class ACC(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        self.sm = ScreenManager()
        self.sm.add_widget(ConfigScreen(name='config'))#, md_bg_color = self.theme_cls.backgroundColor))
        
    def build(self):
        self.theme_cls.theme_style_switch_animation = True
        self.theme_cls.primary_palette = "Skyblue"
        self.theme_cls.theme_style = "Dark"

        return self.sm
    
    # def on_start(self):
    #     def on_start(*args):
    #         self.root.md_bg_color = self.theme_cls.backgroundColor
    #         print(self.theme_cls.backgroundColor)

    #     Clock.schedule_once(on_start)
    
ACC().run()
```
When app start. 
![image](https://github.com/kivymd/KivyMD/assets/62722937/c6c1ffd3-7f7a-4290-9534-e220969a8b73)

Press for first time Style button
![image](https://github.com/kivymd/KivyMD/assets/62722937/5c755377-e567-42a3-a40a-ab6dcbbb5fd3)

Press for second time Style button (this was the expected result when app start)
![image](https://github.com/kivymd/KivyMD/assets/62722937/d9d3a4f4-69c2-483d-bc9c-5351afc73700)


Versions
- OS: Windows 10
- Python: 3.11.2
- Kivy: 2.3.0
- KivyMD: 2.01.dev0 (downloaded yesterday)

**Comment by T-Dynamos** [comment]
@facutoledo This is a known issue #1601  and is expected to be fixed soon.

**Comment by facutoledo** [comment]
@T-Dynamos I tried loading the screens inside the Build method, after declaring the styles. This has resulted in the background color loading when starting.
The issue still persists with the background not automatically changing when switching styles.
Below I leave the changes I made from the previous code.

```

class ConfigScreen(MDScreen):
     def __init__(self, **kw):
        super().__init__(**kw)
        
        self.app=MDApp.get_running_app()
        self.theme_cls = MDApp.get_running_app().theme_cls
        
    def on_pre_enter(self, *args):
        self.md_bg_color = self.theme_cls.backgroundColor

        list_items = MDBoxLayout(
            orientation="vertical",
        )    
    (...)
    def set_theme_style(self, *args):
        self.theme_cls.switch_theme()
    (...)

class ACC(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        self.sm = ScreenManager()
        
    def build(self):
        self.theme_cls.theme_style_switch_animation = True
        self.theme_cls.primary_palette = "Skyblue"
        self.theme_cls.theme_style = "Dark"

        self.sm.add_widget(ConfigScreen(name='config'))

        return self.sm
    
ACC().run()
```

**Comment by T-Dynamos** [comment]
@facutoledo Yes it is the same issue.
