### ISSUE TITLE
Use a `dp` metric to measure the radius value of `MDNavigationItemIcon`

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#1677]
Looks not okay on android

![image](https://github.com/kivymd/KivyMD/assets/42192162/1dcdd57b-ccd4-4fd4-bfa3-d2e569dbabad)

### Expected

![image](https://github.com/kivymd/KivyMD/assets/42192162/07574aae-4782-461b-a6c5-fa259c9507ad)

https://github.com/kivymd/KivyMD/blob/cfe5aac30f50708c6208c8b33b0ef1aa390721e8/kivymd/uix/navigationbar/navigationbar.kv#L62

### Proposed fix

```kv
radius: [dp(16),]
```

**Comment by HeaTTheatR** [comment]
Yes, most likely a typo
