### ISSUE TITLE
Navigation Drawer closing after multiple click

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#168]
I have created a small app here when I am clicking on screen it is not closing navigation drawer but when I click it multiple time it closes so why it is not closing automatically at the first time when I click on screen?

Below is my code:-
https://pastebin.com/WEQB9p2V

See the behaviour of the navigation drawer.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33522186/72604951-e3756300-3941-11ea-873f-c0b1987a1ff1.gif)

**Comment by ArtemSBulgakov** [comment]
This will be fixed soon

**Comment by shashi278** [comment]
@navjotcis  Which OS is that you're testing it on? 'cause it's working fine on my Ubuntu 19.10.

Moreover, I don't think it's an issue at all. It's closing probably because it's draggable, meaning you can close the drawer by double-clicking anywhere outside the drawer and dragging the pointer.
If you carefully observe the media you've attached above, you'll see a very slight movement(towards left) in the pointer just before the drawer gets closed.

**Comment by navjotcis** [comment]
@shashi278 I am using Ubuntu 16.04 or 18.04 both and I am facing the above issue.
Yes It is draggable you can open it by dragging from left to right and again you can close it by dragging right to let but in older version on MD if you click outside the drawer it closes on single click and on latest version of MD you can check sometimes it is not closing on double click so this is an issue for user perspective It should be more user-friendly.

**Comment by shashi278** [comment]
> sometimes it is not closing on double click

@navjotcis, it's not sometimes. It's just that it has not been implemented that way to get closed by clicking outside of it. I created a PR referencing the same but for some reason, they want to implement it another way. Btw, if you need that to work right now, you can use my suggested way. It's working fine.

**Comment by navjotcis** [comment]
@shashi278  thank you for a suggestion.

**Comment by navjotcis** [comment]
@shashi278 ok thank you for the suggestion, for now, I will User your approach. But can you reopen the issue until it is not fixed permanently?

**Comment by shashi278** [comment]
@navjotcis Just clone the repository and update the section of code as I did and run `setup.py install` to use my approach temporarily.

And you mean reopening the PR? I didn't close it, they did. They might have a better implementation but we'll have to wait for that.

**Comment by navjotcis** [comment]
@Mountaino thank you for fixing the above issue.
