### ISSUE TITLE
Toolbar right_action_items auto clicked twice

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#169]
I am creating a demo app in that I am implementing a copy button option in the toolbar. when I am clicking that copy button then it is automatically clicked twice this issue appears randomly so try to test the same case 5-6 times then you will face the same issue. For debugging the issue please bind the method with right_action_items like given below.

![image](https://user-images.githubusercontent.com/33522186/72615372-89cd6280-395a-11ea-9bef-b54b32e7da17.png)

then put the print inside the method definition

![image](https://user-images.githubusercontent.com/33522186/72615451-baad9780-395a-11ea-89fb-47b01e4865fc.png)

then after that, I have clicked the copy button only once but it is printing print statements twice.

![image](https://user-images.githubusercontent.com/33522186/72615663-3d365700-395b-11ea-936e-829afe9db3ae.png)

below is the sample code please test the case 5-6 times then you will get the issue.
https://pastebin.com/0DCcv1EB

**Comment by HeaTTheatR** [comment]
@navjotcis I could not reproduce what you are writing about.
