### ISSUE TITLE
MDSwiper not working 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#1691]
### Description of the Bug
swiping error 
line 213, in on_touch_move
     self.effect_x.convert_overscroll(touch)
 AttributeError: '_ScrollViewHardStop' object has no attribute 'convert_overscroll'. Did you mean: 'on_overscroll'?

and 
line 218, in on_touch_up
     self.effect_x.reset_scale()
 AttributeError: '_ScrollViewHardStop' object has no attribute 'reset_scale'

Your text

### Code and Logs

```from kivy.lang.builder import Builder

from kivymd.app import MDApp

kv = '''
<MySwiper@MDSwiperItem>

    FitImage:
        source: "bg.jpg"
        radius: [dp(20),]


MDScreen:
    md_bg_color: self.theme_cls.backgroundColor

    MDSwiper:
        size_hint_y: None
        height: root.height - dp(40)
        y: root.height - self.height - dp(20)

        MySwiper:

        MySwiper:

        MySwiper:

        MySwiper:

        MySwiper:
'''


class Main(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(kv)


Main().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: ubuntu 
* Python: 3.10
* Kivy: 2.3.0
* KivyMD: 2.0.1 dev

**Comment by jtoror** [comment]
I have the same error with the example code.

It's a complete hassle to program with kivymd.

I'm already abandoning it completely.
