### ISSUE TITLE
Bug with MDCard shadow

### ISSUE THREAD

**Issue by allan-rcos** [kivymd/KivyMD#1697]
### Description of the Bug

Hello everyone! My problem is it, I'm trying to place a elevated card in my program to create a dashboard, but the shadow is horrible, I don't know wy, but it's not turning out the way it should. I tryed to disable the ripple and it still running... The shadow is such multiples translucent rectangles piled up. I tryed to customize the shadow, but don't changes anything.

### Code and Logs

```python
from kivy.core.window import Window
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:        
        MDScreen:
            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                size_hint: .9, .9
'''


class Example(MDApp):
    def build(self):
        Window.maximize()
        return Builder.load_string(KV)


Example().run()
```

### Screenshots

https://github.com/kivymd/KivyMD/assets/118565541/0786d473-3f36-4a05-a930-996d1b98abf9

### Versions

* OS: Windows 10
* Python: 3.12
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by HeaTTheatR** [comment]
https://github.com/kivy/kivy/issues/8593
