### ISSUE TITLE
Make NavigationDrawer the focus

### ISSUE THREAD

**Issue by BernardinD** [kivymd/KivyMD#170]
Hi,

Is there a way to make it so that when the MDNavigationDrawer is open the Screen behind it doesn't accept input? I've been looking for this type of behavior, since Popups have a similar behavior to what I"m looking for. But no luck finding the parameter for the MDNavigationDrawer

Thanks,

**Comment by HeaTTheatR** [comment]
@BernardinD Specify what do you mean?

**Comment by BernardinD** [comment]
While the NavigationDrawer is open I don't want anything else to be active. Specifically, everything layered behind it

**Comment by shashi278** [comment]
It's not an issue of NavigationDrawer. You can trigger events you want upon opening and closing of the NavigationDrawer itself. For instance, to stop getting input while it's open, you can disable the TextInput and enable it back upon closing the drawer.

**Comment by BernardinD** [comment]
@shashi278  I had the same idea but it breaks when using the dragging features. I currently using a flag and a custom _toggle_ function located in the MDApp object, and this function runs the drawer's toggle function while handing the controls/flag. But when the dragging features are used it bypasses the custom function and breaks the logic so the idea doesn't work completely

**Comment by shashi278** [comment]
@BernardinD I just tried it with a `TextInput` and I think yes that's an issue. I think it should work more like a `ModalView` which doesn't allow interaction with widgets underneath while it's open.
Until it gets fixed, you can try another way around. `MDNavigationDrawer` has a property called `state` which can be tracked.
<pre>
 TextInput:
    hint_text: "Enter your text"
    disabled: True if root.ids.nav_drawer.state=="open" else False`
</pre>

**Comment by BernardinD** [comment]
@shashi278 Were you able to get snippet that  to work? I thought of doing something like this before and I got the same error I'm getting now.  "_AttributeError: 'MDNavigationDrawer' object has no attribute 'state'_ "

**Comment by HeaTTheatR** [comment]
@BernardinD https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/navigationdrawer.py#L243

**Comment by BernardinD** [comment]
This is what I'm doing when I get the error

```
Screen:
	BoxLayout:
		orientation: 'vertical'
	MDToolbar:
		id: toolbar
		title: "Scanner"
		pos_hint: {"top": 1}
		size_hint: 1, 0.1
		md_bg_color: app.theme_cls.primary_color
		elevation: 10
		left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]
	NavigationLayout:
		id: navigation_id
		size_hint: 1, 0.9
		ScreenManager:
			id: screen_manager_id
			size_hint_y: None
			height: root.height - toolbar.height
			#disabled: False if root.ids.nav_drawer.state=="open" else False
```

And I also tried binding in '_on_start_' of my MDApp `self.root.ids.navigation_id.bind(state=self.toggle_nav_drawer)`. But then a get a KeyError for state

**Comment by HeaTTheatR** [comment]
@BernardinD Correct your last post and show the minimal working code that I can run and look your error.

**Comment by ArtemSBulgakov** [comment]
Kivy's ModalView and Popup allow interactions with other widgets.
![popup-textinput-interaction](https://user-images.githubusercontent.com/44732506/73126575-8030a400-3fc5-11ea-9228-099c9b064031.gif)
On the video: when text in TextInput changes, it open Popup. Focus states on TextInput and I can interact with it.

If you really want to clear focus, you can bind function to `state` and clear focus when it changes to `"open"`.

**Comment by BernardinD** [comment]
@Mountaino were you able to get a working snippet of this? Like I mentioned before, any attempt to get the `state` returns an error of it not existing

**Comment by BernardinD** [comment]
Never mind. I just realized he update the code. Thx @HeaTTheatR

**Comment by BernardinD** [comment]
@HeaTTheatR Currently the way the navbar is set up now it seems I lose the ability to use the Toolbar but it stays visible. Would it be possible to keep the toolbar active as well to use its icon as a way to close the NavDrawer?

**Comment by HeaTTheatR** [comment]
@BernardinD What do you mean?

**Comment by BernardinD** [comment]
![image](https://user-images.githubusercontent.com/27456730/74362711-2f77c400-4d97-11ea-839e-d5bda209e807.png)



Currently when the NavigationDrawer is opened it is the only thing active and it is at a depth above everything else, which is great. Everything except for the Toolbar that is. The Toolbar stays on the same level as the NavigationDrawer but it is unresponsive. And I don't seem to be able to raise the height of the Navigation Drawer to cover it.

I'd like to either keep the Toolbar where it is and make it interactive, or push it to the back with the everything besides the NavigationDrawer and extend the height of the NavigationDrawer to take up the whole screen

**Comment by HeaTTheatR** [comment]
@BernardinD https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer
