### ISSUE TITLE
datatables in kivymd 2.0.1 dev0 

### ISSUE THREAD

**Issue by amadboly** [kivymd/KivyMD#1702]
Hi 
from kivymd.uix.datatables import MDDataTable
is not a viable in kivymd rev, 2.0.1 dev0
OS: windows 10
kivyMD : 2.0.1 dev0 (latest)

**Comment by HeaTTheatR** [comment]
The MDDataTable widget will soon be available in another package - https://github.com/kivymd-extensions

**Comment by schneidersteve** [comment]
@HeaTTheatR Any news regarding the datatable extension?
