### ISSUE TITLE
Problem with three dependencies taken from Kivymd_uix_pickers, but there are others too.

### ISSUE THREAD

**Issue by Dariosky-01** [kivymd/KivyMD#1706]
Hi I'm new, I'm also new and unfamiliar with programming but there seems to be a problem with certain things in KivyMD because the anthers work.
I apologize if I write something wrong but I translate with google, however I am quite good at using it, I use it all the time, I don't speak English well.
Many features of KivyMD work though if I try to import: "MDDockedDatePicke;
MDModalDatePicker;
MDModalInputDatePicker" using VScode everything doesn't seem to work, usually I notice it immediately because the dependencies don't appear to be hit and I understand everything doesn't work but if I copy the examples verbatim they don't work at all and they give me other errors underneath because those three imported dependencies don't work to integrate. Here I took a look at the folder: "https://github.com/kivymd/KivyMD/tree/master/kivymd/uix/pickers" and from what you can see the files of those three dependencies are missing, I presume be this the problem why they don't work, I could be wrong though, if I import "datepicker" it works in VScode, I haven't tried "timepicker" but it will probably work.

I have kivy 2.3.0, kivyMD2.0.1.dev0 and I have python 3.11.4.

If you can give me some help I would be grateful.

I also wanted to point out that I noticed other dependencies that don't work in the same way, but I'm going by memory because I don't have a PC nearby and because I tried some example test codes left on the site. One dependency that doesn't work is one I tried which is found inside the code to find the images of the icons from a search bar, another is a dependency found in the color code where the names and codes of the shades are shown, but I can't say exactly what they are at the moment, I can only provide links to where they are located.

I'll put them below.

Icons:
https://kivymd.readthedocs.io/en/latest/themes/icon-definitions/

..I went to look for it and I realized it's part of the Kivy 1.1.1 branch, however, I have version 2.3.0 so I think I shouldn't have any problems since I'm on a more recent version but still I have this similar problem.
The reference site is:

https://kivymd.readthedocs.io/en/1.1.1/themes/color-definitions/index.html

**Comment by Dariosky-01** [comment]
I apologize, I updated the text, I forgot to change the language in Google Translate and I didn't realize I had copied the untranslated text.

**Comment by Dariosky-01** [comment]
I wanted to show a photo of the screen inside my VScode with the problems I noticed after making the exact copy, literally from the site of the code used to test "MDModalDatePicker" and I also tried running the .py file.

![Test](https://github.com/kivymd/KivyMD/assets/81451904/12b2da1f-38c3-44b2-ba3a-11d54cd48d9b)

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch.

**Comment by Dariosky-01** [comment]
@HeaTTheatR 

Sorry, you were very stringent, I need more information to understand what you mean by me resolving the situation.

If you intend to use:

"from kivymd.uix import MDModalDatePicker"

or

"from kivymd import MDModalDatePicker"

In both cases it doesn't work, if you mean something different you should be a little more specific, perhaps publishing something because I'm not a professional, I'm new and impractical.

**Comment by Dariosky-01** [comment]
However, it seems clear to me that the problem is not mine given that I have all the latest available versions of the packages necessary for operation, but also due to the fact that the test code is also the one copied from the official site for the test.

https://kivymd.readthedocs.io/en/latest/components/datepicker/index.html

**Comment by tdmart05** [comment]
@Dariosky-01 the following code was run using this version of main [INFO   ] [KivyMD      ] 2.0.1.dev0, git-Unknown, 2024-05-30

from kivymd.uix.pickers import MDModalDatePicker
  
class DatePickerDialog(MDModalDatePicker):
  def open(self) -> None:
	  self.year = date.today().year
	  self.month = date.today().month
	  self.day = date.today().day
	  return super().open()

  def on_ok(self, *args) -> None:
	  set_string = str(date) + str(dt.now().strftime(' %H:%M:%S'))
	  os.system(f"sudo date -s '{set_string}' &")
	  Logger.debug(f'Date Picker: Clicked!!!')
	  self.dismiss()
	  return super().on_ok(*args)

  def on_cancel(self, *args) -> None:
	  self.dismiss()
	  return super().on_cancel(*args)

I can't get the code formatting to work here is a screenshot
![image](https://github.com/kivymd/KivyMD/assets/4061529/3d6119a4-b121-41d0-aa14-062344850e0f)


![image](https://github.com/kivymd/KivyMD/assets/4061529/f5349a30-6a2e-4eef-8b95-38fa3dfc9301)

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1706#issuecomment-2153467328

![Снимок экрана 2024-06-08 в 00 07 35](https://github.com/kivymd/KivyMD/assets/16930280/d76e70d7-ba2f-41dc-9f4a-1e8ba0fbd241)

**Comment by Dariosky-01** [comment]
> [#1706 (comment)](https://github.com/kivymd/KivyMD/issues/1706#issuecomment-2153467328)
> 
> ![Снимок экрана 2024-06-08 в 00 07 35](https://private-user-images.githubusercontent.com/16930280/337793960-d76e70d7-ba2f-41dc-9f4a-1e8ba0fbd241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTY3MDQsIm5iZiI6MTcxNzc5NjQwNCwicGF0aCI6Ii8xNjkzMDI4MC8zMzc3OTM5NjAtZDc2ZTcwZDctYmEyZi00MWRjLTlmNGEtMWU4YmEwZmJkMjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIxNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjdjYjliMGFkN2M0NGY0ODUzNDY4ZThhM2FlZDYyODcyNDgxMTJkMzg4MzIwNDlkZDUxOGM1YTdlNTBiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mG1MXKOED0X1qFH9SWPAftZeDPsS-R0GC-i0E_Kh8ws)

I recopied, but it still doesn't work.
Below is the error notification while I try to run.

If you want I can do some specific tests to verify that everything is correct, the material is needed to start correctly but I need the commands, I'm a Windows user.

![22](https://github.com/kivymd/KivyMD/assets/81451904/e7b0fd48-a860-4b8c-acbc-f4defbb53f15)

**Comment by HeaTTheatR** [comment]
Solve problems with your virtual environments.

**Comment by Dariosky-01** [comment]
It would be very useful to be able to use software that reads the saves on the PC to automatically see if anything is missing or needs to be updated.

I can try to reinstall and reread what is needed but I think I have done everything.
