### ISSUE TITLE
i couldn't be happier

### ISSUE THREAD

**Issue by bobtylen** [kivymd/KivyMD#1707]
My project was stuck in the past resembling the old Windows 98 OS.
Yesterday i discovered KivyMD and began incorporating it into my app.
Honestly this was a game-changer! 
After experimenting with numerous libraries and nearly giving up, KivyMD came to the rescue.
Huge thanks to the developers!
Keep up the amazing work❤️

**Comment by T-Dynamos** [comment]
Thank you!

Closing, as it is not an issue, feel free to open discussion.
