### ISSUE TITLE
Bug in mdslider on Android

### ISSUE THREAD

**Issue by AHiXilTOr** [kivymd/KivyMD#1711]
### Screenshots

![IMG_20240613_141355](https://github.com/kivymd/KivyMD/assets/59434506/d88ca0ff-90cc-42f5-9b14-f0db88852b04)

### Versions

* OS: android
* Python: 3.12
* Kivy: 2.3.0
* KivyMD: dev

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1695
