### ISSUE TITLE
Builder.load_all_kivy_files issue

### ISSUE THREAD

**Issue by TaqsBlaze** [kivymd/KivyMD#1714]
### Description of the Bug

When I try to load multiple kv files using the `load_all_kv_files` method it failes with the following error:
` AttributeError: 'BuilderBase' object has no attribute 'load_all_kv_files'`

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_all_kv_files("path/to/dir")


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

[Code and error screenshot.](https://snipboard.io/yULIEQ.jpg)

Remove this section if no images here

### Versions

* OS: Kali linux
* Python: 3.11
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by T-Dynamos** [comment]
`  AttributeError: 'BuilderBase' object has no attribute 'load_all_kv_files'`

Not related to kivymd.
