### ISSUE TITLE
Incorrect button width when window not resized

### ISSUE THREAD

**Issue by ilya2008ss** [kivymd/KivyMD#1718]
### Description of the Bug

At the start of the program, the width of the button is incorrect, and the width can be corrected only by resizing the window

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = """
MDBoxLayout:
    orientation: 'vertical'

    MDRectangleFlatIconButton:
        text: 'Hello world'
        width: self.parent.width
"""

class MainApp(MDApp):
    def build(self):
        return Builder.load_string(KV)
    
MainApp().run()

```

### Screenshots

Before resizing:
![Desktop Screenshot 2024 07 04 - 03 43 46 86](https://github.com/kivymd/KivyMD/assets/98224203/c7239127-7bba-4314-877e-4f26288e658e)

After resizing:
![Desktop Screenshot 2024 07 04 - 03 53 42 01](https://github.com/kivymd/KivyMD/assets/98224203/ae149be7-eb20-4ada-9b43-474241674b58)

### Versions

* OS: Windows 10
* Python: 3.10.6
* Kivy: 2.3.0
* KivyMD: 1.2.0

**Comment by HeaTTheatR** [comment]
KivyMD: 1.2.0 is not supported
