### ISSUE TITLE
New MDNavigationDrawer ver.0.103.0 is not showing with finger on Android

### ISSUE THREAD

**Issue by Aleich** [kivymd/KivyMD#173]
#### Description of the Bug

The navigation box no longer opens when you try to pull it out from the edge of the screen on Android (with finger). But in the previous version of KiwiMD 0.102.0 everything worked!

### Code and Logs

I used example from https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed, and yet CreatorKivyProject

""".kv
<ContentNavigationDrawer>

    BoxLayout:
        orientation: 'vertical'

        FloatLayout:
        ...

Screen:

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        md_bg_color: app.theme_cls.primary_color
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Widget:

        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer
"""

### Versions

* OS: Android 8.0.0
* Python: 3.6
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by ArtemSBulgakov** [comment]
Try to run your code with KivyMD from master branch. https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#how-to-install
Please write here if problem keeps.

**Comment by HeaTTheatR** [comment]
My tests show that the Android `MDNavigationDrawer` works great on an Android device!

**Comment by Aleich** [comment]
Hello again!

I'm trying to use the latest version from the master branch - and cheers, the navigation box works as it should!

However, how I did it. I copied the .zip file of the master branch, unzipped it, and manually copy files from /kivymd to /home/kivy/Projects/myproject1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myproject1/kivymd/  -  and it's work!

However, naturaly, i need to specify the requirements = kivy == 1.11.1, python3, git + https: //github.com/HeaTTheatR/KivyMD.git  in buildozer.spec
- and at this point the script will be hangs. Just install kivymd on the system via pip install git + https: //github.com/HeaTTheatR/KivyMD.git - execution hangs on "Running the git command clone -q https://github.com/ ..." Why??

And one more remark. The new navigation drawer feels less responsive than the old one. The screen, as if it often does not work, you have to move your finger again and again. It’s necessary to show the video what I’m talking about ...

**Comment by HeaTTheatR** [comment]
@Aleich Your problems are not reproducible on my devices!

**Comment by ArtemSBulgakov** [comment]
@Aleich Seems like git works wrong on your system. Bulldozer uses pip to download package. Pip uses git to download package by url. Try to reinstall git 
And please send video with Navigation Drawer.
