### ISSUE TITLE
MDBottomNavigation is above the maximum bound

### ISSUE THREAD

**Issue by Arch4ng3l** [kivymd/KivyMD#174]
#### Description of the Bug

There seems to be an issue with Bottom Navigation, even when I build from fresh clone from your repo, I still get the same error even from from the kitchen_sink demo. Started exactly 4 days ago when last changes we're made.

### Code and Logs

01-30 02:26:01.499 14163 14628 I python  :    File "/home/archangel/TEMP/KivyMD/demos/kitchen_sink/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/kitchen_sink/kivy/lang/builder.py", line 707, in _apply_rule
01-30 02:26:01.499 14163 14628 I python  :  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 40:
01-30 02:26:01.500 14163 14628 I python  :  ...
01-30 02:26:01.500 14163 14628 I python  :       38:
01-30 02:26:01.500 14163 14628 I python  :       39:    width:
01-30 02:26:01.500 14163 14628 I python  :  >>   40:        root.panel.width / len(root.panel.ids.tab_manager.screens)        if len(root.panel.ids.tab_manager.screens) != 0 else root.panel.width
01-30 02:26:01.500 14163 14628 I python  :       41:    padding: (dp(12), dp(12))
01-30 02:26:01.500 14163 14628 I python  :       42:    on_press:
01-30 02:26:01.500 14163 14628 I python  :  ...
01-30 02:26:01.500 14163 14628 I python  :  ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)

### Versions

* OS: Linux
* Python: 3.7.5
* Kivy: 1.11.1
* KivyMD: v0.103.0 - Beta

**Comment by HeaTTheatR** [comment]
No error, I just checked.

![ezgif-3-31db0f7e2c05](https://user-images.githubusercontent.com/16930280/73426583-c8ddb980-4345-11ea-8e4f-b98db14fcb6d.gif)

**Comment by Arch4ng3l** [comment]
Wow, I'm speechless, I already reinstalled kivy. Thanks for the quick reply I'll keep digging!

**Comment by Masikini** [comment]
Has this issue been resolved? @Arch4ng3l , were you able to find a solution? Am facing the same problem, eveything works fine on my linux but once i get things deployed on my Huawei p20, my logs point to this error "ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)"

**Comment by Arch4ng3l** [comment]
@Masikini Not even after purging and reinstalling python and even linux after killing it accidentally trying to solve this purging and reinstalling packages... However I found out using the previous version ( Version 0.102.1 ) it builds properly and runs on my phone no problem, I can run the code on my PC fine with the latest version too,  its only after I build it with buildozer that I get the same error as you. 

Try with the earlier version of KivyMD see if it works for you too:

https://github.com/HeaTTheatR/KivyMD/tree/ffebeb4ee7c85526b31300e32f4817bf950e6175

I never got the time to get back to the authors of KivyMD tho.

**Comment by Arch4ng3l** [comment]
@Masikini also check the owner's comment at the bottom. 

https://github.com/HeaTTheatR/KivyMD/issues/179
