### ISSUE TITLE
Update kivymd pypi

### ISSUE THREAD

**Issue by minkxx** [kivymd/KivyMD#1744]
### Update KivyMD pypi version from 1.2.5 to 2.0.0
Please do update your pypi versio

### Versions

* OS: Windows 7
* Python: 3.8.9
* Kivy: 2.0.0
* KivyMD: 1.2.5

**Comment by 9acca9** [comment]
Hi.
Im trying to get also kivymd 2.0.0. 
were you able to install it?
Thanks!

**Comment by Schnieker** [comment]
pip install https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by Tear4Pixelation** [comment]
I had the same problem and stumbled across this:
`pip install kivymd2`
And found on PyPI: https://pypi.org/project/kivymd2/

**Comment by minkxx** [comment]
> I had the same problem and stumbled across this: `pip install kivymd2` And found on PyPI: https://pypi.org/project/kivymd2/

This worked for me!
