### ISSUE TITLE
MDDilog not closing.

### ISSUE THREAD

**Issue by MrJaatt** [kivymd/KivyMD#1755]
When click on "ok" button  dialog should close. However it show error.
![image_2024-12-21_215544367](https://github.com/user-attachments/assets/3dc797d9-d0d4-4a1d-af28-95400e8541b2)

### Code and Logs

```

    def show_invalid_id_dialog(self):
        print("Show_invalid_id.... -  runned")
        if not self.dialog:
            print("Show_invalid_id.... - if -runned")
            self.dialog = MDDialog(
            MDDialogHeadlineText(
                text="Wrong User Name",
                halign="left",
            ),
            MDDialogSupportingText(
                text="You need to enter correct username. If you forgot then contact Meerut Farm using whatsapp. Please do not call",
                halign="left",),
            MDDialogButtonContainer(
                Widget(),
                MDButton(
                    MDButtonText(text="ok"),
                    style="text",
                    on_release = self.close_dialog()),
                spacing="8dp",
            ),
        ).open()

    def close_dialog(self, *args):
        self.dialog.dismiss()

```

```
 Traceback (most recent call last):
   File "/home/vic/MFL/C_app/main.py", line 444, in <module>
     MyApp().run()
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 413, in on_touch_up
     return super().on_touch_up(touch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "/home/vic/MFL/C_app/main.py", line 249, in close_dialog
     self.dialog.dismiss()
     ^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'dismiss'

```

### Versions

* OS: ubuntu 24.04 ,windows 11
* Python: latest
* Kivy:     2.2.1
* KivyMD: latest

**Comment by MrJaatt** [comment]
If I use ```on_release = self.close_dialog),``` like this then the dialog box open but it do not close.  if I click on 'ok' button however if I click outside of the dialog box then it get close.

**Comment by Enigmatyxx** [comment]
I believe you both need to use lambda:

dialog = MDDialog(
...
    MDDialogButtonContainer(
        ...
        on_release=lambda *args: dialog.dismiss()

dialog.open()

**Comment by MrJaatt** [comment]
Thanks for the reply, although I have tried this but I will try it again. Thanks again 😊.

Although I have faced a similar issue with other widgets like date pickers, but I will try this.

Please do not close this issue I will revert soon.

**Comment by MrJaatt** [comment]
I am a beginner developer. So things are difficult at this stage. 
however thanks for your reply . 
Copilot  provided a huge help and provided a good code to fix my issue. 
 I was finally able to use "MDDialog" properly.
 
 if anyone in future face the issue here is an example code for them for kivymd 2.0.1
 
 
 `
#  Imports for the code
#------------------------------------------------------------------------------------------------------
from kivy.uix.widget import Widget
from kivymd.uix.widget import MDWidget
from kivymd.app import MDApp
from kivymd.uix.button import MDButton, MDButtonText
from kivymd.uix.dialog import MDDialog, MDDialogHeadlineText, MDDialogButtonContainer
#------------------------------------------------------------------------------------------------------
`

`
#------------------------------------------------------------------------------------------------------
class Example(MDApp):

    def build(self):
        return MDWidget(md_bg_color=self.theme_cls.backgroundColor)
    def on_start(self):
        self.dialog = MDDialog(
            MDDialogHeadlineText(text="Delivered\nDo you really want to replace previous data?", halign="left",),
            MDDialogButtonContainer(
                Widget(),
                MDButton(MDButtonText(text="YES"), style="text", on_release=self.on_yes),
                MDButton(MDButtonText(text="NO"), style="text", on_release=self.on_no), 
                spacing="8dp",
            ),
        )
        self.dialog.open()

    def on_yes(self, *args):
        print("YES button pressed!")
        self.dialog.dismiss()

    def on_no(self, *args):
        print("NO button pressed!")
        self.dialog.dismiss()
Example().run()


`

**Comment by MrJaatt** [comment]
:)
