### ISSUE TITLE
icon_definitions home-circle-outline not showing on android

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivymd/KivyMD#177]
```python
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.properties import StringProperty

from kivymd.uix.list import OneLineAvatarListItem

KV = '''
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path


<NavigationItem>
    theme_text_color: 'Custom'
    divider: None

    IconLeftWidget:
        icon: root.icon


<ContentNavigationDrawer>

    BoxLayout:
        orientation: 'vertical'

        FloatLayout:
            size_hint_y: None
            height: "200dp"

            canvas:
                Color:
                    rgba: app.theme_cls.primary_color
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                id: top_box
                size_hint_y: None
                height: "200dp"
                #padding: "10dp"
                x: root.parent.x
                pos_hint: {"top": 1}

                FitImage:
                    source: f"{images_path}kivymd_alpha.png"

            MDIconButton:
                icon: "close"
                x: root.parent.x + dp(10)
                pos_hint: {"top": 1}
                on_release: root.parent.toggle_nav_drawer()

            MDLabel:
                markup: True
                text: "[b]KivyMD[/b]\\nVersion: 0.102.1"
                #pos_hint: {'center_y': .5}
                x: root.parent.x + dp(10)
                y: root.height - top_box.height + dp(10)
                size_hint_y: None
                height: self.texture_size[1]

        ScrollView:
            pos_hint: {"top": 1}

            GridLayout:
                id: box_item
                cols: 1
                size_hint_y: None
                height: self.minimum_height


Screen:

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        md_bg_color: app.theme_cls.primary_color
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Widget:


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer

'''


class ContentNavigationDrawer(BoxLayout):
    pass


class NavigationItem(OneLineAvatarListItem):
    icon = StringProperty()


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for items in {
            "update": "Home",
            "home-circle-outline": "Check for Update",
            "settings-outline": "Settings",
            "exit-to-app": "Exit",
        }.items():
            self.root.ids.content_drawer.ids.box_item.add_widget(
                NavigationItem(
                    text=items[1],
                    icon=items[0],
                )
            )


TestNavigationDrawer().run()
```

I compile this for android

<img src="https://user-images.githubusercontent.com/38758320/73890867-32dcee00-4873-11ea-8450-6d71a8c13b4f.png" width="400" height="600">

**Comment by ArtemSBulgakov** [comment]
Seems that all icons with 32-bit code don't work. Test it with `"radio-off"` which code is `"\U000F0247"`. It gives blank icon too

**Comment by allanmarigi** [comment]
I have used kivymd for some time and am tring to create an application. With the new version the changer how to draw navigation drawer. I have alreadiy implemented it in my app but I don’t know how to open deferent screen when I press an item on the navigation.

This is my code

    def on_enter(self):
        icons_item = {
            "leaf": "My profile",
            "message": "Messages",
            "check": "Likes",
            "eye": "Views",
            "settings": "Settings",
            "close": "Exit"
            
        }
        for icon_name in icons_item.keys():
            self.ids.content_drawer.ids.md_list.add_widget(
                NavigationItem(icon=icon_name, text=icons_item[icon_name],
                on_press=lambda x, y=icons_item: self.callback(x, y))
            )
            for item in icons_item:
                if item == "My profile":
                    screen_manager = "login"

    def callback(self, instance, value):
        toast("Pressed item menu %d" %value)

how do I switch to the settings screen the I press on settings. I have already created the screen in my kv file
Any help will be appreciated

**Comment by HeaTTheatR** [comment]
@allanmarigi Full code, please...

**Comment by allanmarigi** [comment]
This is the code in the .py class

class Main_Screen(Screen):


    def on_enter(self):
        icons_item = {
            "leaf": "My profile",
            "message": "Messages",
            "check": "Likes",
            "eye": "Views",
            "settings": "Settings",
            "close": "Exit"

        }
        for icon_name in icons_item.keys():
            self.ids.content_drawer.ids.md_list.add_widget(
                NavigationItem(icon=icon_name, text=icons_item[icon_name],
                on_press=lambda x, y=icons_item: self.callback(x, y))

            )
            for item in icons_item:
                if item == "My profile":
                    screen_manager = "login"

    def callback(self, instance, value):
        toast("Pressed item menu %d" %value)

And this is the code in my .kv file
<Main_Screen>:

    name : "main"

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        id: toolbar
                        title: 'Menu'
                        size_hint: 1.0,0.05
                        background_color: [0.0, 0.0, 0.0, 0.4]
                        elevation: 10
                        left_action_items: [['menu', lambda
 x: nav_drawer.toggle_nav_drawer()]]

                    Widget:

    MDNavigationDrawer:
        id: nav_drawer

        ContentNavigationDrawer:
            id: content_drawer

<NavigationItem>
    theme_text_color: "Custom"
    on_release: self.parent.set_color_item(self)
    divider: None

    IconLeftWidget:
        id : Icon_Left_Widget
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color


<ContentNavigationDrawer>

    id: content_drawer


    BoxLayout:
        orientation: 'vertical'

        FloatLayout:
            size_hint_y: None
            height: "200dp"



            BoxLayout:
                id: top_box
                size_hint_y: None
                height: "200dp"
                x: root.parent.x
                pos_hint: {"top": 1}
                FitImage:
                    source:  f
'E:/New folder/super_girl-wallpaper-11343919.jpg'

            MDLabel:
                markup: True
                font_size: 25
                text: "[color=1565C0] profile name [/color]"
                x: root.parent.x + dp(10)
                y: root.height - top_box.height + dp(10)
                size_hint_y: None
                height: self.texture_size[1]

        MDSeparator:

        ScrollView:
            pos_hint: {"top": 1}


            DrawerList:
                id: md_list

I have other screen in the app like the settings screen. how do i switch to
the settings screen after i press on settings on the navigation drawer?
you can modify my code

**Comment by HeaTTheatR** [comment]
@allanmarigi 
```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import ObjectProperty

from kivymd.app import MDApp

KV = '''
<ContentNavigationDrawer>:

    ScrollView:

        MDList:
            id: md_list

            OneLineListItem:
                text: "Screen 1"
                on_press:
                    root.nav_drawer.set_state("close")
                    root.screen_manager.current = "scr 1"

            OneLineListItem:
                text: "Screen 2"
                on_press:
                    root.nav_drawer.set_state("close")
                    root.screen_manager.current = "scr 2"


Screen:

    NavigationLayout:

        ScreenManager:
            id: screen_manager

            Screen:
                name: "scr 1"

                MDLabel:
                    text: "Screen 1"
                    halign: "center"

            Screen:
                name: "scr 2"
                
                MDLabel:
                    text: "Screen 2"
                    halign: "center"

        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                screen_manager: screen_manager
                nav_drawer: nav_drawer
'''


class ContentNavigationDrawer(BoxLayout):
    screen_manager = ObjectProperty()
    nav_drawer = ObjectProperty()


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)

TestNavigationDrawer().run()
```

**Comment by allanmarigi** [comment]
Thank you, i have changed to the format given and managed to implement it

**Comment by mkc2019** [comment]
Guys, someone has figured this out. It turns out this bug comes from p4a, not kivymd.
See #257

@HeaTTheatR I guess you can consider closing it too?

**Comment by ArtemSBulgakov** [comment]
Solution: https://github.com/HeaTTheatR/KivyMD/issues/257#issuecomment-665599554
