### ISSUE TITLE
How to display(add) text right at the center of MDSpinner in kivymd 

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#180]
I am using MDSpinner in my kivy program and want to show(display) text right in the middle of MDSpinner.I tried adding MDLabel but it is always slightly off from center for different screen sizes.Is there any way to add text in the middle of MDSpinner circle?

**Comment by HeaTTheatR** [comment]
@atheistrepublic This is against the rules of material design. You can make your custom spinner using `MDSpinner` as a basis.
