### ISSUE TITLE
Some kind of dependence on Theming won't allow me to run.

### ISSUE THREAD

**Issue by punkscience** [kivymd/KivyMD#183]
#### Description of the Bug

Using the most minimal app (using MDApp) I get an error as follows:

 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from kivymd.app import MDApp
   File "/Users/.../.local/share/virtualenvs/apptest-ggq0gN21/lib/python3.7/site-packages/kivymd/app.py", line 14, in <module>
     from kivymd.theming import ThemeManager
 ModuleNotFoundError: No module named 'kivymd.theming'

### Code and Logs

```python
from kivy.app import App
from kivymd.app import MDApp
...

class PongApp(MDApp):


    def __init__(self, **kwargs):
        self.title = "My Material Application"
        super().__init__(**kwargs)
```

* OS:

Mac OS
 
* Python:
3.7 
* Kivy: Latest 
* KivyMD: Latest

**Comment by HeaTTheatR** [comment]
@eyesno Show the minimal working code that reproduces such an error.
