### ISSUE TITLE
unknown syntax error

### ISSUE THREAD

**Issue by lazarus-muya** [kivymd/KivyMD#185]
#### Description of the Bug

Hello, i got bellow error even before making any proceedings.
Any advice i will appreciate. Thank you.

### Code and Logs
chairman@Chairman:~/Desktop/kapps/new$ ls
kivymd  main.py  player.kv
chairman@Chairman:~/Desktop/kapps/new$ python -d main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "/home/chairman/Desktop/kapps/new/kivymd/__init__.py", line 40
    fonts_path = os.path.join(path, f"fonts{os.sep}")
                                                                                 ^
SyntaxError: invalid syntax

```python3

from kivymd.app import MDApp

class PlayerApp(MDApp):
        pass

PlayerApp().run()

**Comment by HeaTTheatR** [comment]
https://kivy.org/doc/stable/gettingstarted/first_app.html
