### ISSUE TITLE
When i press button inside NavigationLayout it presses outside screen button

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#186]
I have made this app and added this NavigationLayout.Everything was working fine but when i press on any of the side menus buttons instead of calling the corresponding function the program behaves as if i was pressing the outside screen(black screen) buttons.That is instead of calling the menu button like 'Author' it presses the button that is right under it(on the black screen).How can i fix this behavior?
I am attaching the screenshot.  
![Screenshot from 2020-02-21 17-58-10](https://user-images.githubusercontent.com/58817288/75035075-a2d6af80-54d4-11ea-94b3-a0d41ade344d.png)

**Comment by HeaTTheatR** [comment]
@atheistrepublic ```python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git```

**Comment by atheistrepublic** [comment]
it is stuck at Running command git clone -q https://github.com/HeaTTheatR/KivyMD.git /tmp/pip-req-build-qbfy4cu5
![Screenshot from 2020-02-21 22-30-45](https://user-images.githubusercontent.com/58817288/75054892-fd363700-54f9-11ea-93ac-bfa02bdf18bd.png)

**Comment by atheistrepublic** [comment]
After this installation process i am still getting the same issue?

**Comment by HeaTTheatR** [comment]
@atheistrepublic Show the minimal code that reproduces your problem.

**Comment by atheistrepublic** [comment]
This is the code that i am using :
`from pathlib import Path
from kivymd.uix.dialog import MDDialog
from kivy.uix.progressbar import ProgressBar
from kivymd.uix.spinner import MDSpinner
import multiprocessing
import os
from openpyxl import Workbook
from openpyxl import load_workbook
import codecs
from ast import literal_eval
import itertools
import re
import xlrd
import time as wtime
from datetime import datetime,time
from openpyxl.styles import Font,Fill
from openpyxl.styles.colors import RED
from openpyxl.styles.colors import BLACK
from openpyxl.styles import PatternFill,Border,Side,Alignment,Protection,Font
from openpyxl.styles import colors
from openpyxl.styles.colors import BLUE
#import pygame
#from Tkinter import *
#import Tkinter
#import tkMessageBox
import logging
import json
import random
import numpy as np
#from pygame.locals import *
import xlsxwriter
#import pandas as pd
from shutil import copyfile
from kivymd.app import MDApp
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout 
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button
from kivy.uix.widget import Widget
from kivy.properties import ObjectProperty
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.lang import Builder
from kivymd.theming import ThemeManager
from kivymd.uix.menu import MDDropdownMenu
from kivymd.toast import toast
from kivy.core.window import Window
Window.softinput_mode = 'below_target'
#from kivymd.uix.button import MDRaisedButton

from kivy.clock import Clock
from kivy.graphics.context_instructions import Color
from kivy.graphics.stencil_instructions import (
    StencilPush,
    StencilUse,
    StencilPop,
    StencilUnUse,
)
from kivy.graphics.vertex_instructions import Ellipse, RoundedRectangle,Rectangle
from kivy.lang import Builder
from kivy.metrics import dp
from kivy.app import runTouchApp
from kivy.uix.button import Button
from kivy.uix.image import Image
from kivy.utils import get_color_from_hex
from kivy.properties import (
    StringProperty,
    BoundedNumericProperty,
    ListProperty,
    AliasProperty,
    BooleanProperty,
    NumericProperty,
    OptionProperty,
)
from kivy.uix.anchorlayout import AnchorLayout
from kivy.uix.behaviors import ButtonBehavior
from kivy.animation import Animation
from kivy.uix.scrollview import ScrollView
from kivymd.uix.behaviors.backgroundcolorbehavior import (
    SpecificBackgroundColorBehavior,
)
from kivymd.uix.behaviors import (
    CircularRippleBehavior,
    RectangularRippleBehavior,
)
from kivymd.uix.behaviors import (
    CommonElevationBehavior,
    RectangularElevationBehavior,
    CircularElevationBehavior,
)
from kivymd.theming import ThemableBehavior

#from android.permissions import request_permissions, Permission
#request_permissions([Permission.WRITE_EXTERNAL_STORAGE])
#request_permissions([Permission.READ_EXTERNAL_STORAGE, Permission.WRITE_EXTERNAL_STORAGE]) 

#android.whitelist = [org.test.myapp]
##from permissions.location import check_permission, ask_permission
from kivymd.uix.label import MDLabel 



Builder.load_string("""

#:import MDLabel kivymd.uix.label.MDLabel
#:import MDTextField kivymd.uix.textfield.MDTextField
#:import MDRaisedButton kivymd.uix.button.MDRaisedButton
#:import get_hex_from_color kivy.utils.get_hex_from_color
#:import utils kivy.utils
#:import NavigationDrawerSubheader kivymd.uix.navigationdrawer.NavigationDrawerSubheader
#:set color_shadow [0, 0, 0, .2980392156862745]
#:set color_lilac [.07058823529411765, .07058823529411765, .14901960784313725, .8]
<WindowManager>:
    MainWindow:
        name:"main"


<MainWindow>:
    name: "main"
    lid1:lid1
    FloatLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                #rgb: 1,1,1
                rgba:utils.get_color_from_hex('#1f1f1f')
            Rectangle:
                #source: 'image.jpg'
                size: self.size
                pos: self.pos

        BoxLayout:
            orientation:"horizontal"
            #padding:[50,0,0,0]
            size_hint:[0.4,0.2]
            pos_hint:{"x":0.05,"y":.4}
            
            canvas.before:
                Color: 
                    rgba:utils.get_color_from_hex('#474747')
                RoundedRectangle:
                    pos:self.pos
                    size:self.size
            
            Icon:
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                halign: 'center'
                font_style: 'Icon'
                icon_name: 'account'
                text: md_icons.get(self.icon_name)
                font_size: 85
                theme_text_color: 'Custom'
                    
                text_color: utils.get_color_from_hex('#ebebeb')
                on_release:
                    print("*******This should not be pressed*****")



        NavigationLayout:
            id:lid1
            MDNavigationDrawer:
                drawer_logo: 'image2.jpg'
                NavigationDrawerSubheader:
                    text:'Menu'
                NavigationDrawerIconButton:
                    icon:'information'
                    text:'About'
                    on_release:
                        print("ABOUT YES")
                        
                NavigationDrawerIconButton:
                    icon:'account'
                    text:'Author'
                    on_release:
                        print("AUTHOR YES")
                        

                NavigationDrawerIconButton:
                    icon:'file-video'
                    text:'Demo'
                    on_release:
                        print("DEMO YES")
                NavigationDrawerIconButton:
                    icon:'license'
                    text:'License'
                    on_release:
                        print("LICENSE YES")


""")

class WindowManager(ScreenManager):
    pass

class MainWindow(Screen):
    pass

class Icon(MDLabel,Button):
    icon_name = StringProperty()




class MyMainApp(MDApp):
    #theme_cls=ThemeManager()
    def build(self):
        return WindowManager()


if __name__ == "__main__":
    
    MyMainApp().run()

`

**Comment by atheistrepublic** [comment]
This is a complete running program.As you can see NavigationLayout does not work as expected.When i click 'Author' menu it prints two statement while it should print only one.
I am attaching the screenshot:
![Screenshot from 2020-02-22 08-15-18](https://user-images.githubusercontent.com/58817288/75085093-ba04b400-554b-11ea-8eb0-8eca56934c6f.png)

**Comment by atheistrepublic** [comment]
Ok i resolved this myself.Thanks anyway :)
