### ISSUE TITLE
How can i add a custom sized image at the top of the navigation layout

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#188]
I want to place an image at the top of the navigation layout.I know how to do it but that takes the whole part of the top navigation layout.I want  the image to be of only a certain size and have some flexibility on positioning it at the top.For example a circular or rectangular custom sized image that takes only certain part of the top navigationlayout and not whole.I am attaching the screenshot and also part of the code:

<MainWindow>:
    name: "main"
    lid1:lid1
    

    NavigationLayout:
        id:lid1
        MDNavigationDrawer:
            
            NavigationDrawerSubheader:
                text:'Menu'
            NavigationDrawerIconButton:
                icon:'information'
                text:'About'
                on_release:
                    app.root.current='ABOUT'
                    root.manager.transition.direction = "left"
            NavigationDrawerIconButton:
                icon:'account'
                text:'Author'
                on_release:
                    app.root.current='AUTHOR'
                    root.manager.transition.direction = "left"

            NavigationDrawerIconButton:
                icon:'file-video'
                text:'Demo'
            
![Screenshot from 2020-02-22 16-56-27](https://user-images.githubusercontent.com/58817288/75091524-505cc800-5594-11ea-912c-4251d8554eb9.png)
    on_release:
                    app.root.current='DEMO'
                    root.manager.transition.direction = "left"

**Comment by HeaTTheatR** [comment]
@atheistrepublic I do not understand what you want.

**Comment by atheistrepublic** [comment]
![PicsArt_02-22-05 10 30](https://user-images.githubusercontent.com/58817288/75091722-6f5c5980-5596-11ea-8845-3765dee1d6c9.png)

I want something like this

**Comment by HeaTTheatR** [comment]
Your code is deprecated! Similar constructions are not used in KivyMD version 0.103.0!

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed

**Comment by atheistrepublic** [comment]
Thanks
