### ISSUE TITLE
How to create a loading screen while the app is loading

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#189]
I have made an app and it has around 10000 to 12000(12k) lines.So the app takes some time(around6-8) seconds to open/load.I have a single main.py file and it has different classes inside it and each class has a corresponding kv code(not .kv file separately).I want to know how can I create loading screen (a progress bar or MDSpinner or something else) while the app is opening.
Example code:

Builder("""
<Mainwindow>:
         name: 'main'
         BoxLayout:
                   .......
<SecondWindow>:
          name:'second'
          FloatLayout:
                    .......
""")
class MainWindow (Screen):
    pass
class SecondWindow (Screen):
    pass

**Comment by HeaTTheatR** [comment]
@atheistrepublic This question relates to Kivy, not KivyMD.
