### ISSUE TITLE
Example of MaterialList with LeftListItemBody (e.g. MaterialCheckBox)

### ISSUE THREAD

**Issue by salomonderossi** [kivymd/KivyMD#19]
Can you please give an example of a MaterialList with LeftListItemBody and/or RightListItemBody, please? Something with MaterialCheckBox maybe?

**Comment by mixedCase** [comment]
There's an example in the kitchen sink. Be warned: The MaterialList code is a horrible, underperforming abomination and will be completely scrapped in favor of a less dynamic solution.

**Comment by salomonderossi** [comment]
Thank you for your fast answer :)
I looked in the kitchen sink and found examples where the left_container_size is set to 'big' but non where the free space is filled with a widget (e.g. MaterialCheckBox or image). Maybe you can help me here a bit

**Comment by mixedCase** [comment]
It should work like in the other containers. I'll be closing this issue since the code is unsupported, undocumented and pending rewrite. If you still wanna work with it, you'll have to take a look at the code, sorry.

**Comment by salomonderossi** [comment]
Okay. I try to figure it out by myself. Sorry for the inconvenience

**Comment by mixedCase** [comment]
@salomonderossi The list rewrite has been implemented and documented. Might wanna take a look if you're interested. Cheers.

**Comment by salomonderossi** [comment]
Thanks. Needed to update to kivy 1.9.1 (used 1.9.0) and it worked like a charm :)
