### ISSUE TITLE
only use the icon in the MDChip component.

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#196]
### Description of the Feature

Can I only use the icon on the MDChip component?

### Code

```python

kv = """
GridLayout:
    cols: 1
    size_hint_y: None
    MDChip:
        icon: "refresh"
        label: ""
"""
```

### Versions

* OS: Ubuntu
* Python: 3.x
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
@aprilahijriyan What for?

**Comment by aprilahijriyan** [comment]
for me to use?
