### ISSUE TITLE
Autocomplete menu in the text field

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#197]
### Description of the Feature

Does the text field have autocomplete menu support?

### Versions

* OS: Ubuntu
* Python: 3.x
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
@aprilahijriyan Formulate your question so that we understand it.

**Comment by aprilahijriyan** [comment]
Sorry! I mean, does the Textfield component have autocomplete menu support if I enter text in the Textfield component?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan No.

**Comment by aprilahijriyan** [comment]
maybe the autocomplete menu feature would be better added to the text field component?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan We work within the framework of material design. If this is not in the design specifications, then this will not be in KivyMD
