### ISSUE TITLE
How to use Back Functionality 

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#199]
I have created an app and it has different classes and screens and i want to use back button functionality.That is when i click back button on my android i want it to go to a different screen(previous or next).Any working example or suggestion  or link will be really helpful.
Thanks

**Comment by HeaTTheatR** [comment]
@atheistrepublic https://github.com/kivy/kivy/issues

**Comment by atheistrepublic** [comment]
Using window.bind results in a keyboard popping up automatically while the app opens.
I have implemented the same thing in my program.But this results in a keyboard popping up at the starting of the app.That is when the app opens on android there is a keyboard opening automatically.How can I stop this behaviour but still have the back button functionality?

**Comment by HeaTTheatR** [comment]
@atheistrepublic Your question is not related to the KivyMD library.

**Comment by atheistrepublic** [comment]
Here is the screenshot of the code i'm using and the keyboard popping up unnecessarily on android when the app starts.
This happens because of Window.bind(on_keyboard).
I think this is a bug @kivy site.

![Capture+_2020-03-08-17-45-45](https://user-images.githubusercontent.com/58817288/76200387-8f874c00-6217-11ea-9100-bf9addf67056.png)
![Screenshot from 2020-03-08 17-41-44](https://user-images.githubusercontent.com/58817288/76200415-9a41e100-6217-11ea-8b06-18d9ef64d292.png)

**Comment by atheistrepublic** [comment]
The Kivy App is also on playstore.You can see when the app opens a keyboard automatically opens.
https://play.google.com/store/apps/details?id=org.anoop.myapp
