### ISSUE TITLE
Possible bug Navigation Drawer

### ISSUE THREAD

**Issue by 2n2u** [kivymd/KivyMD#20]
Setting the property side to right causes the navbar to be locked at a the initial position. If you resize the window there is no change in "spawning". Setting it to left, it behaves as expected. Probably some problem at slidingpanel.py

**Comment by mixedCase** [comment]
SlidingPanel, the parent class of NavigationDrawer is supposed to work with the 'side' parameter. NavDrawer however is not. This is working as intended, since it's following the [Navigation drawer specs](http://www.google.com/design/spec/patterns/navigation-drawer.html).
