### ISSUE TITLE
cannot use the IconRightWidget component

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#201]
### Description of the Bug

I take an example from here https://github.com/HeaTTheatR/KivyMD/wiki/Components-Expansion-Panel-and-MDCard and change the IconLeftWidget component to IconRightWidget.

### Code and Logs

https://github.com/HeaTTheatR/KivyMD/wiki/Components-Expansion-Panel-and-MDCard

### Versions

* OS: ubuntu
* Python: 3.x
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
![Снимок экрана 2020-03-05 в 18 40 19](https://user-images.githubusercontent.com/16930280/75997213-15ea1800-5f10-11ea-860b-8e384607c011.png)
@aprilahijriyan https://kivymd.readthedocs.io/en/latest/components/list/index.html#listitems-with-widget-containers
