### ISSUE TITLE
Expansion Panel component is not responsive.

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#203]
### Description of the Bug

I tried the example from https://github.com/HeaTTheatR/KivyMD/wiki/Components-Expansion-Panel and I tried to click one by one component and the most recent component, the content is not visible.

### Screenshots

![Cuplikan layar dari 2020-03-07 18-43-40](https://user-images.githubusercontent.com/37798612/76142821-c6d4ec00-60a3-11ea-96fc-4120f76c8a2f.png)

### Versions

 *   OS: ubuntu
 *  Python: 3.x
 *  Kivy: 1.11.1
 *  KivyMD: 0.103.0

**Comment by HeaTTheatR** [comment]
@aprilahijriyan I changed the example, everything works.
