### ISSUE TITLE
Not able to implement clicable icon inside textInput field.

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#204]
![image](https://user-images.githubusercontent.com/33522186/76145964-a2cdd680-60b4-11ea-9bd2-0ff6cbfd8349.png)
In the above image I am trying to put icon clicable button inside TextInput but I am not able to make it like that so if you people have made anything like that please suggest me.

**Comment by HeaTTheatR** [comment]
This feature has been removed since version 0.102.0.

**Comment by navjotcis** [comment]
can you provide me the link?

**Comment by HeaTTheatR** [comment]
@navjotcis Search in commits

**Comment by HeaTTheatR** [comment]
@navjotcis version 0.99.92

**Comment by HeaTTheatR** [comment]
@navjotcis But this is an old version and I would not recommend using it
