### ISSUE TITLE
how to add icons with labels

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#205]
can you give an example of using a label with an icon?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan I do not understand what you mean

**Comment by aprilahijriyan** [comment]
Does the MDLabel component support adding icons?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan No

**Comment by aprilahijriyan** [comment]
Can you give examples of text components with icons?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan I don't understand what you need

**Comment by aprilahijriyan** [comment]
sorry, but my problem is solved. thanks!

**Comment by aisjdevmahesh** [comment]
How do you done it? Please explain it.

**Comment by aprilahijriyan** [comment]
@aisjdevmahesh it's been too long on this, I had forgotten.
