### ISSUE TITLE
Bug Report on KivyMD:Window.bind(on_keyboard) doesn't work as expected

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#208]
[NOT_WORKING.txt](https://github.com/HeaTTheatR/KivyMD/files/4311423/NOT_WORKING.txt)
I have included WIndow.bind(on_keyboard=self.keyboard) but this have the result that when the app opens on android  a keyboard also open up automatically .I noted that this happens in KivyMD only and not in Kivy.I am attaching the screenshots.One of them is for kivy case which works  fine and no keyboard popsup when app opens.But the next screenshot  where MDApp is used doesn't work correctly.That is in this case(MDApp) the keyboard unnecessarily pops up when the app starts on android.
Moreover i am attaching a reproducible example of what is not working in .py file.I dont't want the keyboard to open(popup) automatically when the app starts on android.
![Screenshot from 2020-03-10 14-49-31](https://user-images.githubusercontent.com/58817288/76298272-34209100-62df-11ea-9efe-a51296e509f5.png)
![Screenshot from 2020-03-10 14-49-37](https://user-images.githubusercontent.com/58817288/76298278-35ea5480-62df-11ea-9c47-4835a70091d4.png)
[NOT_WORKING.txt](https://github.com/HeaTTheatR/KivyMD/files/4311413/NOT_WORKING.txt)
![Capture+_2020-03-08-17-45-45](https://user-images.githubusercontent.com/58817288/76298541-9c6f7280-62df-11ea-942c-b5b9797b67a8.png)

**Comment by HeaTTheatR** [comment]
@atheistrepublic Thanks for the question. We will explore this later.

**Comment by atheistrepublic** [comment]
Here is the complete reproducible .py file that show the problem of keyboard popping up unnecessarily when app starts.
[complete_program.txt](https://github.com/HeaTTheatR/KivyMD/files/4312523/complete_program.txt)

**Comment by HeaTTheatR** [comment]
This bug is currently not reproducible.
