### ISSUE TITLE
Expansion Panel crashing 

### ISSUE THREAD

**Issue by volion80** [kivymd/KivyMD#209]
Multiple clicking on the item breaks down the markup and app crashing. 
The issue can be reproduced with the Kitchen Sink app.
![Screenshot_20200310-124757_KivyMD Kitchen Sink](https://user-images.githubusercontent.com/48555419/76307039-b48bc580-62d0-11ea-9fd6-7003cff836f7.jpg)

**Comment by HeaTTheatR** [comment]
You have a library error in the screenshot! Use the master branch!
