### ISSUE TITLE
Can't change button text color for MDFlatButton

### ISSUE THREAD

**Issue by Kozubi** [kivymd/KivyMD#21]
Hi
Kivy 1.9.1 and python 3.4.4 here
When I use MDFlatButton and want to change it text color it does not change :(

I tried both with kv land and in python

MDFlatButton:
        background_color: (0,0,0,.2)
        text: "1212"
        text_color: (1,0,0,1)
        pos_hint: {'x':0.5, 'y':0.4}

or 
bt.text_color = (1,0,0,1)

text remains unchanged (is some kind of blue)

**Comment by mixedCase** [comment]
Fixed. You should now be able to set `text_color`. Please keep in mind that for the buttons to use the color set in `text_color`, you have to set `theme_text_color` to `'Custom'`.

**Comment by Kozubi** [comment]
Thx for additional feedback!
