### ISSUE TITLE
MDRaisedButton behavior is not correct after updating its text

### ISSUE THREAD

**Issue by AndreMPCosta** [kivymd/KivyMD#21]
As stated in the title, after updating the text of a MDRaisedButton, its size and position changes, that it's not intended.

![Alt Text](https://i.imgur.com/m0aGDLQ.gif)

If I swap to a Button, it behaves correctly:
![Alt Text](https://i.imgur.com/gemPZ1P.gif)

on_press:

```    
def test(self, *args):
        args[0].text = 'teste'
```

EDIT: Every MDButton behaves this way, the problem should be on a class that all of them inherit.

**Comment by AndreMPCosta** [comment]
Seems like it doesn't love stuff like this:

size: (some_size_reference, self.height)

if I use this instead:
size: (some_size_reference, self.size[1])

The size problem is fixed.

**Comment by HeaTTheatR** [comment]
@AndreMPCosta 

```python
from kivy.app import App
from kivy.uix.floatlayout import FloatLayout

from kivymd.button import MDRaisedButton
from kivymd.theming import ThemeManager


class Test(App):
    theme_cls = ThemeManager()

    def press(self, instance):
        instance.text = 'New Text'

    def build(self):
        box = FloatLayout()
        button = MDRaisedButton(on_press=self.press, text='Text',
                                pos_hint={'center_x': .5, 'center_y': .5})
        box.add_widget(button)
        return box


if __name__ == '__main__':
    Test().run()
```

![111](https://user-images.githubusercontent.com/16930280/51622483-be752c80-1f47-11e9-947e-a399792fa2c7.gif)

**Comment by AndreMPCosta** [comment]
Hey! The problem was setting the button with a different size than default. But I've managed to fix the problem in my code, as I've said in my 2nd reply, it doesn't like self.height in the size_y property. All good now :)
