### ISSUE TITLE
STRANGER THINGS(bug report):MDTextFieldRound does not work correctly

### ISSUE THREAD

**Issue by atheistrepublic** [kivymd/KivyMD#211]
So i was debugging my program for the keyboard popup automatically when the app starts on android.And noticed that this only happens when i include MDTextFieldRound: inside my code.When i remove the code that includes MDTextFieldRound the app works fine that is no keyboard popsup  when the app starts but the moment i add the MDTextFieldRound inside my code the keyboard starts popping up unnecessarily when app starts.
This is a very basic yet major issue that needs to be addressed and that is why i am opening another issue/thread.I'm attaching a file that has the code which results in keyboard popping up.Note that when you remove the MDTextFieldRound section(in AUTHOR) from the code no keyboard popsup.I hope you find and fix the problem.
##THIS IS A BUG REPORT
This is the part of code that is causing the problem
MDTextFieldRound:
                        
                        
                        multiline:False
                        hint_text:"Institute Name"
                        #hint_text_color:utils.get_color_from_hex('#ffffff')
                        #normal_color: utils.get_color_from_hex('#8A2BE2')
                        color_active:1,0,0,1
                        
                        pos_hint: {"x":0.11, "top":0.13}
                        size_hint: 0.8, 0.12
                        icon_type:'without'
[main.txt](https://github.com/HeaTTheatR/KivyMD/files/4319572/main.txt)

**Comment by HeaTTheatR** [comment]
@atheistrepublic There, just somewhere, the focus receives the value of `True`. I'll check it later

**Comment by HeaTTheatR** [comment]
Related issue - https://github.com/HeaTTheatR/KivyMD/issues/208
