### ISSUE TITLE
History Issue with MDFilemanager

### ISSUE THREAD

**Issue by NameKhan72** [kivymd/KivyMD#215]
Hello, I have noticed an Issue with the kivyMD Filemanager. 

For arguments sake I will use the [example](https://kivymd.readthedocs.io/en/latest/components/file-manager/index.html) provided in the docs.

When selecting a file or directory with either the floating button or just by clicking on it everything works. Reopening the filemanager and trying to go back one folder results in: 
IndexError: pop from empty list.

Commenting out the following lines in the [filemanager.py](https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/filemanager.py) file solves the issue:
Starting from line 736:
```python
    def select_dir_or_file(self, path):
        """Called by tap on the name of the directory or file."""

        if os.path.isfile(path):
            #self.history = [] <<<<<
            self.select_path(path)
            return

        self.current_path = path
        self.show(path)

    def back(self):
        """Returning to the branch down in the directory tree."""
        if len(self.history) == 1:
            path, end = os.path.split(self.history[0])
            if end == "":
                self.exit_manager(1)
                return
            self.history[0] = path
        else:
            self.history.pop()
            path = self.history[-1]
        self.history_flag = False
        self.select_dir_or_file(path)

    def select_directory_on_press_button(self, *args):
        #self.history = [] <<<<<
        self.select_path(self.current_path)
```

Is this supposed to be like this and I am just using the filemanager incorrectly or is this actually a bug?

Thank you for your advice

NameKhan72

**Comment by HeaTTheatR** [comment]
@NameKhan72 We will fix it later.
