### ISSUE TITLE
Kv files are not included to pyinstaller.spec

### ISSUE THREAD

**Issue by quitegreensky** [kivymd/KivyMD#220]
### Description of the Bug

Kv files are not included to pyinstaller.spec:

### Code and Logs
After making exe package and execute it i get following error: 
![Untitled](https://user-images.githubusercontent.com/55235027/77253939-78b31180-6c7b-11ea-906a-2f9a44de41a4.png)

**Comment by RobertFlatt** [comment]
Possibly not a KivyMD issue. For Pyinstaller, Kivy .kv files have to be specified as data files
https://groups.google.com/d/msg/kivy-users/JlFi2C-TGjA/ZaMdKdVkCgAJ
