### ISSUE TITLE
How can we change the color of tab text

### ISSUE THREAD

**Issue by jaisnow** [kivymd/KivyMD#227]
I have been trying to chage the color of tab sub header text from balck to white but  I am not able to find any property for it so if you people know any method for it the please let me know.

![image_2020_03_25T21_06_55_986Z](https://user-images.githubusercontent.com/62672781/77585806-212ad500-6f0b-11ea-8cf5-9d9e7d0cdc6b.png)

**Comment by HeaTTheatR** [comment]
'normal_color'

**Comment by jaisnow** [comment]
I have try to change text from black to white but is it is not changing anything see below my code is.

<Tab@BoxLayout+MDTabBase>
MDTabs:
        id: tb_pnl
        tab_display_mode: "text"
        Tab:
             text: "what to change color of this text"
             normal_color: 1,1,1,1

**Comment by jaisnow** [comment]
@HeaTTheatR I have tried above solution but it is not affecting anything so can you try on your end or can you please give me any working example?

**Comment by HeaTTheatR** [comment]
@jaisnow Sorry! 
```python
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.icon_definitions import md_icons

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs
        text_color_normal: 1, 0, 1, 1


<Tab>:

    MDIconButton:
        id: icon
        icon: app.icons[0]
        user_font_size: "48sp"
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    icons = list(md_icons.keys())[15:30]

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for name_tab in self.icons:
            self.root.ids.android_tabs.add_widget(Tab(text=name_tab))


Example().run()
```

**Comment by HeaTTheatR** [comment]
@jaisnow https://kivymd.readthedocs.io/en/latest/components/tabs/index.html#kivymd.uix.tab.MDTabs.text_color_normal
