### ISSUE TITLE
Components Card MDCardPost import error

### ISSUE THREAD

**Issue by SrikanthKoti** [kivymd/KivyMD#228]
Components Card Example
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Card-Post

ImportError: cannot import name 'MDCardPost' from 'kivymd.uix.card'

**Comment by HeaTTheatR** [comment]
@SrikanthKoti `MDCardPost` will be deleted - https://kivymd.readthedocs.io/en/latest/components/card/index.html
