### ISSUE TITLE
Persian/Arabic Support

### ISSUE THREAD

**Issue by asefycom** [kivymd/KivyMD#229]
### Description of the Feature

Hi there and thank you for all your efforts,

I use [Arabic Reshaper library](https://github.com/mpcabd/python-arabic-reshaper) for Persian/Arabic texts to be included in kivymd widgets as you can see in the code snippet below. 

The letters of the words in Arabic and Persian stick together and I cannot have a continues text in a widget by simply adding a custom font to it.

I think we (kivy and kivymd developers in Persian and Arabic speaking countries) need a standard way embedded in kivy/kivymd for it.

### Code and Logs

import bidi.algorithm
from kivy.core.text import LabelBase
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.button import MDRectangleFlatButton
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
import arabic_reshaper

class MainApp(MDApp):
    def build(self):
        LabelBase.register(name="ir", fn_regular="ir.ttf")
        reshaped_text = arabic_reshaper.reshape("زبان شیرین پارسی")
        bidi_text = bidi.algorithm.get_display(reshaped_text)
        label = MDLabel(text=bidi_text, halign="center", font_style="Iran")
        btn = MDRectangleFlatButton(text=bidi_text, font_name="ir.ttf")

        box =  BoxLayout(orientation="vertical")
        box.add_widget(label)
        box.add_widget(btn)
        return box

MainApp().run()

### Versions

* OS: Windows 10
* Python: 3.7.*
* Kivy: 1.11.1
* KivyMD: 0.104.0

**Comment by HeaTTheatR** [comment]
![Снимок экрана 2020-03-30 в 08 55 13](https://user-images.githubusercontent.com/16930280/77879558-5d3f9c00-7263-11ea-83cf-fb9a62a65ecb.png)

**Comment by asefycom** [comment]
Thank you for your reply. can you give me the code for the capture you sent.
How can I implement this? Setting font_name with a Persian font not working for me.

**Comment by asefycom** [comment]
Hi there,
As you can see below, KivyMD does not work well with Persian fonts.

This is my font:
https://easyupload.io/kbdqij

This is my output:
https://i.imgur.com/4zabrfE.jpg

And this is my code:
`
KV = '''
Screen:
    BoxLayout:
        orientation: 'vertical'
        halign: "center"
        spacing: dp(50)
        padding: dp(50)

        MDLabel:
            text: "سلام"
            font_name: "iransans.ttf"
            
        MDTextField:
            id: search_field
            hint_text: 'سلام'
            font_name: "iransans.ttf"
            
        MDRectangleFlatButton:
            text: "سلام"
            halign: "center"   
            font_name: "iransans.ttf"         
            markup: True
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            
        MDFlatButton:
            text: "سلام"
            font_size: "18sp"
            font_name: "iransans.ttf"
            
'''

from kivy.core.text import LabelBase

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles


class MainApp(MDApp):
    def build(self):
        LabelBase.register(
            name="JetBrainsMono",
            fn_regular="caladea_reg.ttf")

        theme_font_styles.append('JetBrainsMono')
        self.theme_cls.font_styles["JetBrainsMono"] = [
            "JetBrainsMono",
            16,
            False,
            0.15,
        ]
        return Builder.load_string(KV)


MainApp().run()

`

**Comment by moazkamal** [comment]
It didn't work for me please help
