### ISSUE TITLE
toggle_nav_drawer()

### ISSUE THREAD

**Issue by Brianzhengca** [kivymd/KivyMD#23]
in line 254 of the kitchen_sink main.py
[['menu', lambda x: app.root.toggle_nav_drawer()]]
I did not see the function toggle_nav_drawer() been defined anywhere nor been imported.
How can this function be used???

**Comment by HeaTTheatR** [comment]
@Brianzhengca, **kivymd/navigationdrawer.py:**

```puthon
    def toggle_nav_drawer(self):
        self.toggle_state(True)
```
