### ISSUE TITLE
Font Style for MDButtons

### ISSUE THREAD

**Issue by asefycom** [kivymd/KivyMD#231]
### Description of the Feature

Hi there,

How can I use a font style I have already defined for a MDlabel, at the same time for a MDRectangleFlatButton?

There should be a standard way for it. It is a waste of time to define a font_name for each button rule.

**Comment by HeaTTheatR** [comment]
```
<CustomMDRectangleFlatButton@MDRectangleFlatButton>
    font_name: "font.ttf"
```

**Comment by asefycom** [comment]
Thank you but I mean font Style not font name.

**Comment by HeaTTheatR** [comment]
@mostafa-asefy It does not change the essence

**Comment by asefycom** [comment]
I want to define a font style with font name, font size and ... for using in labels and buttons and other widgets simultaneously.
