### ISSUE TITLE
Automatic Reload Kivy Application

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#232]
I want to add an auto reload file using the kaki application https://github.com/tito/kaki.

**Comment by HeaTTheatR** [comment]
@aprilahijriyan I do not know who needs this library and why. Therefore, I can not answer you.

**Comment by aprilahijriyan** [comment]
I want to auto reload * .kv file in my application if there are changes.

**Comment by HeaTTheatR** [comment]
@aprilahijriyan https://github.com/kivy/kivy/blob/master/kivy/tools/kviewer.py
