### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.uix.boxlayout'

### ISSUE THREAD

**Issue by senchoi** [kivymd/KivyMD#234]
Hi getting error when running kitchen_sink demo and otherwise as well when importing BoxLayout. Error: **ModuleNotFoundError: No module named 'kivymd.uix.boxlayout'**.  boxlayout.py file exists in kivymd.uix folder.

**Comment by HeaTTheatR** [comment]
`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`
