### ISSUE TITLE
 ModuleNotFoundError: No module named 'kivymd.app'

### ISSUE THREAD

**Issue by ShakedBraimok** [kivymd/KivyMD#236]
### Description of the Bug

The KivyMD already installed, but import method not works for kivymd.app, only for kivymd (import kivymd).

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel


class MainApp(MDApp):
    def build(self):
        return MDLabel(text="Hello, World", halign="center")


MainApp().run()
```
 Log:
     from kivymd.app import MDApp
 ModuleNotFoundError: No module named 'kivymd.app'

### Versions

* OS: Mac
* Python: 3.7
* Kivy: 2.0.0
* KivyMD: 0.104

**Comment by Lashwanth1234** [comment]
Use the Following code to help you fix the error:

pip install --force-reinstall https://github.com/kivymd/KivyMD/archive/master.zip
it helped me with the same problem so past the above code in your IDE editor and your Command prompt and then run you coed after that

**Comment by Magrid0** [comment]
> Use the Following code to help you fix the error:
> 
> pip install --force-reinstall https://github.com/kivymd/KivyMD/archive/master.zip it helped me with the same problem so past the above code in your IDE editor and your Command prompt and then run you coed after that

i've done it but the error still appear

**Comment by HeaTTheatR** [comment]
@HotCoffeMug Please solve the problems with your virtual environment. So far I see that you are not using the master branch of the library. Or do you have a file named `kivymd.py` in your project.

**Comment by hafeeltigeen** [comment]
I have the same issue now. Is the issue resolved @ShakedBraimok

**Comment by Lashwanth1234** [comment]
Nope
