### ISSUE TITLE
Unicode text display

### ISSUE THREAD

**Issue by senchoi** [kivymd/KivyMD#237]
i was following along with
https://www.youtube.com/watch?v=PaaVaBNIFnM&t=896s
I couldn't change the text to Korean.
it worked on MDLabel: or buttons
font_name: didn't work on a lot of cases
So far I found it didn't work on Tab, MDToolbar-title, TwoLineAvatarIconListItem(list items in general i think.)

**Comment by HeaTTheatR** [comment]
@senchoi This does not apply to the KivyMD library
