### ISSUE TITLE
ImportError: cannot import name 'MDAdaptiveWidget'

### ISSUE THREAD

**Issue by elmschaym** [kivymd/KivyMD#242]
Windows 10
Python 3.6

![error kivy](https://user-images.githubusercontent.com/6017220/78692869-1883c700-792d-11ea-80f1-dc85de36039a.JPG)

**Comment by HeaTTheatR** [comment]
`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`
