### ISSUE TITLE
Value Error : MDBottomNavigationHeader.width is below the minimum bound (80)

### ISSUE THREAD

**Issue by tusharraju7** [kivymd/KivyMD#244]
I am Writing a code for an application. The application works great on my desktop but when i build the code for android using buildozer. I recieve this error.

[main.txt](https://github.com/HeaTTheatR/KivyMD/files/4459713/main.txt)
[error.txt](https://github.com/HeaTTheatR/KivyMD/files/4459714/error.txt)
[buildozersepc.txt](https://github.com/HeaTTheatR/KivyMD/files/4459719/buildozersepc.txt)

**Comment by HeaTTheatR** [comment]
`requirements = kivy==1.11.1, git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by tusharraju7** [comment]
I made the changes, yet still the error persists.

**Comment by HeaTTheatR** [comment]
This error has been fixed in the master branch!

**Comment by HeaTTheatR** [comment]
```
buildozer android clean
```

**Comment by tusharraju7** [comment]
Thanks, The issue is gone!

**Comment by tusharraju7** [comment]
The app works now but i can see only half of the navigation bar. What would i need to change to make it work?
![WhatsApp Image 2020-04-10 at 11 23 31 AM](https://user-images.githubusercontent.com/55238467/78966549-ce156c80-7b1d-11ea-80be-8f2ff62f20e8.jpeg)

**Comment by HeaTTheatR** [comment]
How many `MDBottomNavigationItem` in `MDBottomNavigation` do you use?

**Comment by tusharraju7** [comment]
3 - Water,Data & Settings

**Comment by HeaTTheatR** [comment]
@tusharraju7 I can’t confirm that you have a problem. Attach a minimal code that reproduces this behavior.
![20200410_090006](https://user-images.githubusercontent.com/16930280/78967047-0612b480-7b0a-11ea-8783-cf2c4506e7af.png)
