### ISSUE TITLE
MDDialog Bug | Dialog black on linux and android

### ISSUE THREAD

**Issue by Felipe738743872** [kivymd/KivyMD#247]
### Description of the Bug

Hello! When I use a dark theme my MDDialog turns black, apparently Dialog is showing errors only on Linux and Android, on MacOS no problem.

Thanks, sorry for my English ;-;

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.dialog import MDDialog

kv = """
Screen:
    Button
        on_release:
            app.open_dialog()
"""

class MainApp(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.root = Builder.load_string(kv)

    def open_dialog(self):
        dialog = MDDialog(
            size_hint=(0.4, 0.4)
        )
        dialog.open()

if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

https://15530009509605697547.googlegroups.com/attach/1a53a550b4873/Screenshot%20from%202020-04-10%2010-21-53.png?part=0.1&view=1&vt=ANaJVrG5JEx3h-p_UTXGlHHYL2Plry4RnfCjpm77-hqY7vklW8GLCTr7rqjYvliAmv0aSu6XYqlgyms9ftvplLrlCe-uGeGD7U_49KTBFY_fy_zaJj9B9EA

### Versions

* OS: Ubuntu 19.04 LTS + Android
* Python: 3.7.6
* Kivy: 1.11.1
* KivyMD: 0.104.0

**Comment by HeaTTheatR** [comment]
`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`
https://kivymd.readthedocs.io/en/latest/components/dialog/index.html

**Comment by Noor-Kalibbala** [comment]
am having this problem aslo , currently running on linux os
i installed kivymd using pip just recently, how did u resolve this problem

**Comment by HeaTTheatR** [comment]
@Noor-Kalibbala This issue has already been fixed. Both in PyPi and in the master branch.

**Comment by Noor-Kalibbala** [comment]
thanks
