### ISSUE TITLE
MDDialog ommit top spacing if content_cls is provided

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#251]
I have a use case where if I assign **content_cls** to a **MDDialog**, there is top unwanted spacing due to padding/ widgets inserted.

If you have an AnchorLayout positioned centered vertically within the content_cls widget, which will be relative to the parent dialog, this would offset the content_cls.

To avoid the offset I handle this by setting:

`modal_obj.ids.spacer_top_box.padding = (0, 0, 0, 0)`

Just my opinion for consistency, I think there should only be an offset under the custom+content_cls if the title is provided. 
OR
If a content_cls is provided, no other widgets are inserted (including title)

**Comment by HeaTTheatR** [comment]
@grandvalley Show me the unwanted indentation in the screenshot.

**Comment by ghost** [comment]
I'll close this for now, I'll look at the code more in depth later on and get back to you. There seems to be additional padding even if I remove the title widget. It's probably just the widget being pushed to the bottom, so it may be an issue on my end. Thanks and sorry.
