### ISSUE TITLE
Persian/Arabic Typography

### ISSUE THREAD

**Issue by asefycom** [kivymd/KivyMD#252]
Hi there,
As you can see below, KivyMD does not work well with Persian fonts.

This is my font:
https://www.onlinewebfonts.com/download/766132c828a90cbecf6f7f4027d12725

This is my output:
https://i.imgur.com/4zabrfE.jpg

And this is my code:

KV = '''
Screen:
BoxLayout:
orientation: 'vertical'
halign: "center"
spacing: dp(50)
padding: dp(50)

    MDLabel:
        text: "سلام"
        font_name: "iransans.ttf"
        
    MDTextField:
        id: search_field
        hint_text: 'سلام'
        font_name: "iransans.ttf"
        
    MDRectangleFlatButton:
        text: "سلام"
        halign: "center"   
        font_name: "iransans.ttf"         
        markup: True
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        
    MDFlatButton:
        text: "سلام"
        font_size: "18sp"
        font_name: "iransans.ttf"
'''

from kivy.core.text import LabelBase

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles

class MainApp(MDApp):
def build(self):
LabelBase.register(
name="JetBrainsMono",
fn_regular="caladea_reg.ttf")

    theme_font_styles.append('JetBrainsMono')
    self.theme_cls.font_styles["JetBrainsMono"] = [
        "JetBrainsMono",
        16,
        False,
        0.15,
    ]
    return Builder.load_string(KV)
MainApp().run()

**Comment by HeaTTheatR** [comment]
https://stackoverflow.com/questions/30514853/kivy-text-input-for-arabic-text

**Comment by asefycom** [comment]
I am already familiar with arabic reshaper. but it is not a good choice.
Be lucky!
