### ISSUE TITLE
Font Style Error when Defining MDLabel Dynamically in Code

### ISSUE THREAD

**Issue by asefycom** [kivymd/KivyMD#253]
**Here is the code:**

from kivy.core.text import LabelBase
from kivy.uix.label import Label
from kivymd.app import MDApp
from kivy.uix.boxlayout import BoxLayout
from kivymd.font_definitions import theme_font_styles
from kivymd.uix.button import MDRectangleFlatButton
from kivymd.uix.label import MDLabel
from kivymd.uix.textfield import MDTextField

class MainApp(MDApp):

    def build(self):
        LabelBase.register("Caladea", fn_regular="caladea_reg.ttf")

        theme_font_styles.append("Caladea")

        self.theme_cls.font_styles["Caladea"] = [
            "caladea_reg",
            20,
            False,
            0.15,
        ]

        bidi_text = "hello"
        label = MDLabel(text=bidi_text, font_style="Caladea", halign='center')
        boxLayout = BoxLayout(orientation="vertical")
        boxLayout.add_widget(label)
        return boxLayout

testApp = MainApp()
testApp.run()

**Here is the output Error**

 ValueError: MDLabel.font_style is set to an invalid option 'caladea_reg'. Must be one of: ['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Subtitle1', 'Subtitle2', 'Body1', 'Body2', 'Button', 'Caption', 'Overline', 'Icon']

**Comment by HeaTTheatR** [comment]
@mostafa-asefy https://kivymd.readthedocs.io/en/latest/themes/theming/index.html#kivymd.theming.ThemeManager.font_styles

**Comment by asefycom** [comment]
Define MDLabel Dynamically in code Not in a KV String or file.
Just test my code!

**Comment by HeaTTheatR** [comment]
@mostafa-asefy I showed you how to correctly add custom font styles to `MDLabel`.

**Comment by asefycom** [comment]
I want to teach your library in my country. Take a minute and read my questions precisely.
I need to define it in code. It should work the same way, no?

**Comment by HeaTTheatR** [comment]
I have given you an exhaustive answer. I have nothing more to add.

**Comment by asefycom** [comment]
Then, How do I use arabic reshaper to organize my text **if I must define MDLabel in KV.**
As you refer the link below:
https://stackoverflow.com/questions/30514853/kivy-text-input-for-arabic-text

**Comment by asefycom** [comment]
> @mostafa-asefy https://kivymd.readthedocs.io/en/latest/themes/theming/index.html#kivymd.theming.ThemeManager.font_styles

This is your code you refered to it, with **MDLabel Removed from KV string to code**. and it is not working:

from kivy.core.text import LabelBase

from kivy.lang import Builder
from kivy.uix.screenmanager import Screen

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles
from kivymd.uix.label import MDLabel


class MainApp(MDApp):
    def build(self):
        LabelBase.register(
            name="JetBrainsMono",
            fn_regular="JetBrainsMono-Regular.ttf")

        theme_font_styles.append('JetBrainsMono')
        self.theme_cls.font_styles["JetBrainsMono"] = [
            "JetBrainsMono",
            16,
            False,
            0.15,
        ]
        
        label = MDLabel(text="Hi Bug", font_style="JetBrainsMono", halign='center')

        screen = Screen()
        screen.add_widget(label)
        return screen


MainApp().run()


So, did you understand what I mean?

**Comment by HeaTTheatR** [comment]
@mostafa-asefy I don’t understand what are you writing here

**Comment by HeaTTheatR** [comment]
@mostafa-asefy 
```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
#:import arabic_reshaper arabic_reshaper
#:import get_display bidi.algorithm.get_display


Screen:

    MDRaisedButton:
        text: get_display(arabic_reshaper.reshape("كلمة المرور"))
        pos_hint: {"center_x": .5, "center_y": .5}
        font_name: "DroidNaskh-Regular.ttf"
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```
![ezgif-4-8f54b67bb417](https://user-images.githubusercontent.com/16930280/79299470-cd4d5380-7eec-11ea-98cf-93698804bd63.gif)
