### ISSUE TITLE
custom icons for NavigationDrawerIconButton

### ISSUE THREAD

**Issue by Brianzhengca** [kivymd/KivyMD#26]
can i use my own icons for navigationdrawericonbutton or add icons to icon definitions?

**Comment by HeaTTheatR** [comment]
Yes you can. What is the problem?

**Comment by Brianzhengca** [comment]
I want an app that user can upload their own icons and it will be displayed on a navigation drawer. Currently I am able to let the users upload the image but can’t get the image to be on the navigation drawer.

**Comment by HeaTTheatR** [comment]
@Brianzhengca Show me your sample code ...

**Comment by Brianzhengca** [comment]
currently i don't have access to that computer right now, but most of my code is just from the kitchen_sink navigation drawer. the upload part is tkinter askopenfilename, i can get the icon path

**Comment by HeaTTheatR** [comment]
@Brianzhengca What does Tkinter have to do with it? Show how and what you do and what result you want to get!

**Comment by Brianzhengca** [comment]
tkinter is just used to get the path of the file. I can probably get the file by the end of the month and i will post my code and the result here

**Comment by Brianzhengca** [comment]
i think i found the solution now. i can change the NavigationDrawerIconButton in navigationdrawer.py. I will change the source NDIconLabel to display the image that i want
