### ISSUE TITLE
AttributeError: 'ThemeManager' object has no attribute 'font_styles'

### ISSUE THREAD

**Issue by arunkrishnan1856** [kivymd/KivyMD#261]
I got the following error when I tried to use this repository.

<

font_info = self.theme_cls.font_styles[self.font_style]
AttributeError: 'ThemeManager' object has no attribute 'font_styles'

I am new to kivymd and I couldn't figure a way out of this. I can't even run kitchen sink nor a simple kivymd script without this error throwing up.
<
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel

class MainApp(MDApp):
def build(self):
return MDLabel(text="Hello, World", halign="center")

MainApp().run()

even this wont run.
I'm using kivy v1.11.1 and python v3.7.3

**Comment by HeaTTheatR** [comment]
@arunkrishnan1856 Show me full log.

**Comment by shumendra** [comment]
I am getting the same error. Here is the code(Indentations are correct in the actual code):
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel

class MainApp(MDApp):
    def build(self):
        a = MDLabel(text = "A Label")
        return a

if __name__ == "__main__":
    MainApp().run()
---------------------------------------------------------------------------
 Here is the full log:
"C:\Users\Shumendra\PycharmProjects\TestApp\Scripts\python.exe" "C:/Users/Shumendra/PycharmProjects/MDLearn/main.py"
[INFO   ] [Logger      ] Record log in C:\Users\Shumendra\.kivy\logs\kivy_20-06-23_18.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer_dev" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle_dev" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew_dev" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2_dev" 0.2.0
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\Shumendra\PycharmProjects\TestApp\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Shumendra\PycharmProjects\TestApp\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 23.20.16.5018'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 23.20.16.5018'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:/Users/Shumendra/PycharmProjects/MDLearn/main.py", line 10, in <module>
     MainApp().run()
   File "C:\Users\Shumendra\PycharmProjects\TestApp\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "C:/Users/Shumendra/PycharmProjects/MDLearn/main.py", line 6, in build
     a = MDLabel(text = "A Label")
   File "C:\Users\Shumendra\PycharmProjects\TestApp\lib\site-packages\kivymd\uix\label.py", line 322, in __init__
     self.update_font_style()
   File "C:\Users\Shumendra\PycharmProjects\TestApp\lib\site-packages\kivymd\uix\label.py", line 326, in update_font_style
     font_info = self.theme_cls.font_styles[self.font_style]
 AttributeError: 'ThemeManager' object has no attribute 'font_styles'

Process finished with exit code 1

**Comment by shumendra** [comment]
It's clear now. Probably the problem was because of installation of -dev packages. I installed the interpreter for the new project in pycharm again with only kivy, angle, glew, gstreamer, sdl2 and kivymd and it's working now. Just for somebody with the same problem.
