### ISSUE TITLE
App crashes after the loading screen(default kivy's loading)

### ISSUE THREAD

**Issue by srajith** [kivymd/KivyMD#262]
### Description of the Bug

r4j@rajith-pc:~/kivy_app$ buildozer -v android debug deploy run logcat
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/r4j/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /home/r4j/kivy_app/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /home/r4j/kivy_app/.buildozer/android/platform/python-for-android
* master 8cf66cc1 [origin/master] Merge pull request #2111 from kivy/release-2020.03.30
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'pytoml\' \'virtualenv<20\''
# Cwd None
# Apache ANT found at /home/r4j/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/r4j/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 19b
# Android NDK found at /home/r4j/.buildozer/android/platform/android-ndk-r19b
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy==1.11.1,kivymd --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21'
# Cwd /home/r4j/kivy_app/.buildozer/android/platform/python-for-android
/home/r4j/kivy_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:85: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Recipe kivy: version "1.11.1" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (26, 27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/r4j/.buildozer/android/platform/android-ndk-r19b
[INFO]:    Found NDK version 19b
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /home/r4j/.local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	myapp: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, kivymd, git+https://github.com/heattheatr/kivymd.git, certifi), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
# Build the application #4
# Copy application source from /home/r4j/kivy_app
# Create directory /home/r4j/kivy_app/.buildozer/android/app
# Copy /home/r4j/kivy_app/main.kv
# Copy /home/r4j/kivy_app/attend.py
# Copy /home/r4j/kivy_app/main.py
# Package the application
# project.properties updated
# Gradle project detected, copy files /home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/src/main/java
# Run '/usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name myapp --name \'My Application\' --version 0.3 --package org.test.myapp --minsdk 21 --ndk-api 21 --private /home/r4j/kivy_app/.buildozer/android/app --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir="/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21'
# Cwd /home/r4j/kivy_app/.buildozer/android/platform/python-for-android
/home/r4j/kivy_app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:85: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (26, 27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/r4j/.buildozer/android/platform/android-ndk-r19b
[INFO]:    Found NDK version 19b
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /home/r4j/.local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	myapp: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, kivymd, git+https://github.com/heattheatr/kivymd.git, certifi), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	myapp: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, kivymd, git+https://github.com/heattheatr/kivymd.git, certifi), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
[INFO]:    -> directory context /home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a
Listing '/tmp/p4a-extra-env-nnco0b4b'...
Listing '/home/r4j/kivy_app/.buildozer/android/app'...
Listing '/home/r4j/kivy_app/.buildozer/android/app/_applibs'...
Compiling '/home/r4j/kivy_app/.buildozer/android/app/attend.py'...
Compiling '/home/r4j/kivy_app/.buildozer/android/app/main.py'...
Compiling '/home/r4j/kivy_app/.buildozer/android/app/sitecustomize.py'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/modules'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/Kivy-1.11.1-py3.8.egg-info'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/android'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/certifi'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/certifi-2020.4.5.1.dist-info'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src/org'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src/org/jnius'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/audio'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/camera'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/clipboard'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/gl'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/image'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/spelling'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/text'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/video'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/window'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/fonts'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/glsl'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/images'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/keyboards'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/logo'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/deps'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/effects'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/extras'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/garden'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/graphics'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/graphics/cgl_backend'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/include'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input/postproc'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input/providers'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lang'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib/gstplayer'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib/vidcore_lite'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/modules'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/network'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/storage'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/gles_compat'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/highlight'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/packaging'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/packaging/pyinstaller_hooks'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/pep8checker'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/theming'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/theming/defaulttheme'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix/behaviors'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix/recycleview'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/fonts'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/images'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/stiffscroll'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/toast'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/toast/androidtoast'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/toast/kivytoast'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/tools'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/tools/packaging'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/tools/packaging/pyinstaller'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/uix'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/uix/behaviors'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/utils'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/vendor'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/vendor/circleLayout'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd/vendor/circularTimePicker'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivymd-0.104.0.dist-info'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/_vendor'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/_vendor/packaging'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/extern'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pyjnius-1.2.1-py3.8.egg-info'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/_vendor'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/_vendor/packaging'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/command'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/extern'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools-40.9.0-py3.8.egg-info'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local'...
Listing '/home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local/bin'...
[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 30.0.0-rc2
[INFO]:        Building with gradle, as gradle executable is present
[DEBUG]:   -> running gradlew assembleDebug
[DEBUG]:   	
[DEBUG]:   	> Task :compileDebugJavaWithJavac 
[DEBUG]:   	Note: Some input files use or override a deprecated API.
[DEBUG]:   	Note: Recompile with -Xlint:deprecation for details.
[DEBUG]:   	Note: Some input files use unchecked or unsafe operations.
[DEBUG]:   	Note: Recompile with -Xlint:unchecked for details.
[DEBUG]:   	
[DEBUG]:   	
[DEBUG]:   	BUILD SUCCESSFUL in 10s
[DEBUG]:   	27 actionable tasks: 12 executed, 15 up-to-date

[INFO]:    <- directory context /home/r4j/kivy_app/.buildozer/android/platform/python-for-android
[INFO]:    # Copying APK to current directory
[INFO]:    # APK filename not found in build output. Guessing...
[INFO]:    # Found APK file: /home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/outputs/apk/debug/myapp__armeabi-v7a-debug.apk
[INFO]:    # Add version number to APK
[INFO]:    # APK renamed to myapp__armeabi-v7a-debug-0.3-.apk
[DEBUG]:   -> running cp /home/r4j/kivy_app/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/outputs/apk/debug/myapp__armeabi-v7a-debug.apk myapp__armeabi-v7a-debug-0.3-.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied: src/patches/SDLActivity.java.patch
# Android packaging done!
# APK myapp__armeabi-v7a-0.3-armeabi-v7a-debug.apk available in the bin directory
# Run '/home/r4j/.buildozer/android/platform/android-sdk/platform-tools/adb devices'
# Cwd None
List of devices attached

# Application pushed.
# Application started.
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/r4j/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS:  Ubuntu, arch
* Python: Python 3.7.5
* Kivy: 1.11.1
* KivyMD: 0.104.0

**Comment by HeaTTheatR** [comment]
@srajith Edit your question.

**Comment by srajith** [comment]
what do i change in spec file ?

**Comment by HeaTTheatR** [comment]
@srajith https://github.com/HeaTTheatR/KivyMD/issues/new?assignees=&labels=&template=bug_report.md&title=
