### ISSUE TITLE
MDDropdownMenu set_menu_properties

### ISSUE THREAD

**Issue by td1803** [kivymd/KivyMD#263]
def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.register_event_type("on_dismiss")
        self.menu = self.ids.md_menu
        **Clock.schedule_once(self.set_menu_properties, 2)** 

this should be replaced by

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.register_event_type("on_dismiss")
        self.menu = self.ids.md_menu
        Clock.schedule_once(self.set_menu_properties, -1)

**Comment by HeaTTheatR** [comment]
@td1803 This is done for a specific purpose.
