### ISSUE TITLE
Is there any possiblity to make bubble text in kivymd ?

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#264]
I have been trying to make chat UI the same as Whatsapp and I have tried to make bubble text on my screen but I did not found anything like that.

![image](https://user-images.githubusercontent.com/33522186/80082287-c28c6180-8571-11ea-9c18-27fa2c1cb7cf.png)
 see in above picture two people conversation text is in a bubble so I am trying to implement the same thing so If you guys know how to implemented please help me and the help will be appreciated

**Comment by HeaTTheatR** [comment]
@navjotcis These interface elements are not related to material design.
