### ISSUE TITLE
How can we fix the spinne dropdown to not move on the scroll.

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#265]
Whenever I am trying to implement the spinner on any screen on kivymd navigation drawer and if the screen is having scrolling length or more data on a screen then I am facing issues with spinner dropdown so if anyone having a solution please suggest me.

below is my sample code
[test.zip](https://github.com/HeaTTheatR/KivyMD/files/4523523/test.zip)
here the issue is showing on spinner dropdown
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33522186/80120683-fe8ee900-85a8-11ea-8150-1d7e037c5f58.gif)

**Comment by HeaTTheatR** [comment]
I did not change your code.

![ezgif-4-188b274e0844](https://user-images.githubusercontent.com/16930280/80122213-e8c3f880-8595-11ea-8bb0-c246c910cc5f.gif)

**Comment by navjotcis** [comment]
@HeaTTheatR, please keep open your spinner and then only scroll so you will get the issue.

**Comment by HeaTTheatR** [comment]
@navjotcis Test this example with `ScrollView` (`Kivy`).

**Comment by navjotcis** [comment]
@HeaTTheatR  yes if you will put it on screen and if the screen is having large data the same thing will happen with spinner. so is there any way to make is fix with a spinner?

**Comment by navjotcis** [comment]
@HeaTTheatR  because it should move up with spinner when we scroll. so In this way, it will be more user friendly.

**Comment by HeaTTheatR** [comment]
@navjotcis You tested this example with ScrollView (Kivy)?

**Comment by navjotcis** [comment]
@HeaTTheatR facing the same issue with ScrollView.

**Comment by HeaTTheatR** [comment]
@navjotcis Then ask this question on the `Kivy` forum.

**Comment by navjotcis** [comment]
ok thanks for the support

**Comment by navjotcis** [comment]
@HeaTTheatR I have fixed it.
