### ISSUE TITLE
Error: DropDownItem: attribute error: on_select

### ISSUE THREAD

**Issue by loan-mgt** [kivymd/KivyMD#266]
I have a error runing my app on anrdoid,

but everything is runing fine on windows

the log of my phone is this:

	04-23 23:24:21.447 17007 17035 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
	04-23 23:24:21.474 17007 17035 I python  : [INFO   ] [Text        ] Provider: sdl2
	04-23 23:24:21.523 17007 17035 I python  : [INFO   ] [Window      ] Provider: sdl2
	04-23 23:24:21.548 17007 17035 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
	04-23 23:24:21.549 17007 17035 I python  : [INFO   ] [GL          ] Backend used <sdl2>
	04-23 23:24:21.549 17007 17035 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@420.0 (GIT@3f24407, I72742cdabd, 1573384904) (Date:11/10/19)'>
	04-23 23:24:21.550 17007 17035 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
	04-23 23:24:21.550 17007 17035 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 616'>
	04-23 23:24:21.550 17007 17035 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
	04-23 23:24:21.550 17007 17035 I python  : [INFO   ] [GL          ] Texture max size <16384>
	04-23 23:24:21.550 17007 17035 I python  : [INFO   ] [GL          ] Texture max units <16>
	04-23 23:24:21.553 17007 17035 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
	04-23 23:24:21.554 17007 17035 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
	04-23 23:24:21.555 17007 17035 I python  : [INFO   ] [KivyMD      ] v0.104.0
	04-23 23:24:21.624 17007 17035 I python  : [INFO   ] [GL          ] NPOT texture support is available
	04-23 23:24:21.821 17007 17035 I python  : {'Femmelle1': 'CFVGBNJ'}
	04-23 23:24:21.822 17007 17035 I python  : hello
	04-23 23:24:21.916 17007 17035 I python  :  Traceback (most recent call last):
	04-23 23:24:21.916 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/lang/builder.py", line 725, in _apply_rule
	04-23 23:24:21.917 17007 17035 I python  :  AttributeError: select
	04-23 23:24:21.917 17007 17035 I python  :  
	04-23 23:24:21.917 17007 17035 I python  :  During handling of the above exception, another exception occurred:
	04-23 23:24:21.917 17007 17035 I python  :  
	04-23 23:24:21.917 17007 17035 I python  :  Traceback (most recent call last):
	04-23 23:24:21.917 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/app/main.py", line 77, in <module>
	04-23 23:24:21.918 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/app.py", line 828, in run
	04-23 23:24:21.918 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/app.py", line 599, in load_kv
	04-23 23:24:21.918 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/lang/builder.py", line 301, in load_file
	04-23 23:24:21.918 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/lang/builder.py", line 403, in load_string
	04-23 23:24:21.919 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/lang/builder.py", line 732, in _apply_rule
	04-23 23:24:21.919 17007 17035 I python  :  kivy.lang.builder.BuilderException: Parser: File "/data/data/maeght.csvtest/files/app/main.kv", line 67:
	04-23 23:24:21.919 17007 17035 I python  :  ...
	04-23 23:24:21.919 17007 17035 I python  :       65:
	04-23 23:24:21.919 17007 17035 I python  :       66: pos_hint: {"center_x": .5, "center_y": .4}
	04-23 23:24:21.919 17007 17035 I python  :  >>   67: on_select: app.handle_select_F(*args)
	04-23 23:24:21.919 17007 17035 I python  :       68: dropdown_bg: [1, 1, 1, 1]
	04-23 23:24:21.919 17007 17035 I python  :       69:
	04-23 23:24:21.919 17007 17035 I python  :  ...
	04-23 23:24:21.920 17007 17035 I python  :  AttributeError: select
	04-23 23:24:21.920 17007 17035 I python  :    File "/home/loan/Bureau/csvtest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/csvtest/kivy/lang/builder.py", line 725, in _apply_rule
	04-23 23:24:21.920 17007 17035 I python  :  
	04-23 23:24:21.920 17007 17035 I python  : Python for android ended.

my python code: main.py

import kivy
	from fonction import *

	from kivy.app import App
	from kivy.uix.label import Label
	from kivy.uix.floatlayout import FloatLayout
	from kivy.uix.textinput import TextInput
	from kivy.uix.button import Button
	from kivy.uix.widget import Widget
	from kivy.properties import ObjectProperty
	from kivy.graphics import Rectangle
	from kivy.graphics import Color
	from kivy.graphics import Line
	from kivy.lang import Builder
	from kivy.uix.screenmanager import ScreenManager, Screen
	from kivy.core.window import Window
	from kivymd.app import MDApp
	from kivymd.icon_definitions import md_icons
	####from kivymd.theming import ThemeManager
	from kivymd.uix.picker import MDDatePicker
	from kivy.properties import ObjectProperty, StringProperty
	from kivymd.uix.menu import MDDropdownMenu

	import csv
	Window.clearcolor = (1, 1, 1, 1)

	print(updatelist([],[])[0])

	class MainApp(MDApp):
		##date_selectionneur= ObjectProperty(None)
		label_accueil = StringProperty('')
		label_date = StringProperty('')
		ffList = []
		fmList = []
		
		ffList = updatelist([],[])[0]
		fmList = updatelist([],[])[1]

		handle_select_F_value = StringProperty('')
		handle_select_M_value = StringProperty('')
		print("hello")
		

		def show_datepicker(self):
			picker = MDDatePicker(callback = self.got_date)
			picker.open()

		def got_date(self, the_date):
			print(the_date)
			self.label_date = str(the_date)

		def labeltext(self):
			print("hello")
			#self.label_accueil = str(readtest())
		def write_csv_classe(self,date,M,F):
			print(M)
			print(F)
			#write_csv(date,M,F)

		def handle_select_F(self, instance, value):
			print(instance, value)
			self.handle_select_F_value = value
		def handle_select_M(self, instance, value):
			print(instance, value)
			self.handle_select_M_value = value
		

		def build(self):
			pass
	        

	if __name__ == "__main__":
	     MainApp().run()

fonction.py
	def num(nbr):
	    nbr = str(nbr)
	    liste = ["0","1", "2", "3", "4", "5", "6", "7", "8", "9"]
	    verif = 0
	    
	    for i in range (0, len(str(nbr))):
	        for z in range (0, len(liste)):
	            if nbr[i]== liste[z]:
	                verif += 1
	                break
	    if verif == len(nbr):
	        return True
	    else:
	        return False

	def verif(nbr):
	    liste = ["\\","/"]
	    barre1= 0
	    barre2= 0
	    for i in range (0, len(nbr)):
	        
	        if num(nbr[i]) == False:
	            if barre1==0:
	                barre1=i
	            else:
	                barre2=i
	    if barre1==0:
	        return False
	    
	    if int(nbr[0:barre1])>31:
	        return False
	    if int(nbr[barre1+1:barre2])>12:
	        return False
	    
	    for z in range(0,2):
	        if nbr[barre1]==liste[z]:
	            for z in range(0,2):
	                if nbr[barre2]==liste[z]:
	                    return True
	    return False
	def sommedate(date,temp):
	    mois_en_j=dict({"01":31,"02":28,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31})
	    z=date[3:5]
	    if (int(date[6:10]))%4 == 0:
	        mois_en_j=dict({"01":31,"02":29,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31})
	    else:
	        mois_en_j=dict({"01":31,"02":28,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31})
	        
	    nbr_de_jour= mois_en_j[date[3:5]]
	    j_total= temp+int(date[0:2])
	    if j_total/nbr_de_jour <= 1:
	        
	        if j_total<10:
	            j_total= "0"+str(j_total)
	        ret= str(j_total)+str(date[2:10])
	        return ret
	    else:
	        while int(j_total)/int(nbr_de_jour) > 1:
	            if (int(date[6:10]))%4 == 0:
	                mois_en_j=dict({"01":31,"02":29,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31})
	            else:
	                mois_en_j=dict({"01":31,"02":28,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31})
	        
	            j_total= j_total-int(nbr_de_jour)
	            
	            if j_total<10:
	                j_total="0"+str(j_total)
	            mois= str(int(date[3:5])+1)
	            if int(mois)<10:
	                mois= "0"+str(mois[len(mois)-1])
	            date=str(j_total)+"/"+mois+date[5:10]
	            if int(date[3:5]) > int(12):
	                innt=int(date[6:10])+1
	                date= str(date[0:3])+"01/"+str(innt)

	        return date

	def read(x,y):
	    reponse="none"
	    import csv

	    f = open('D:\pgOS\data_couv.csv', 'r')

	    reader = csv.reader(f)
	        
	    xx=0
	    yy=0
	    try:
	        while True:
	            for row in reader:
	                yy+=1
	                xx=0
	                for e in row:
	                    xx+=1
	                    if yy == y:
	                    
	                        if xx == x:
	                        
	                            reponse = e
	                            return reponse
	    except:
	        
	        return reponse

	def verifV():
	    nbr = 0
	    import csv

	    f = open('D:\pgOS\data_couv.csv', 'r')
	    reader = csv.reader(f)
	    for row in reader:
	        for e in row:
	            nbr += 1
	    nbr= nbr/6
	    liste = []
	    y = 2
	    B = True
	    while y < nbr+1:
	        try:
	            if read(4,y) == "V":
	                liste.append(y)
	        except:
	            B = False
	        y += 1
	    return liste

	def testdict(dic,key):
	    if key in dic:
	        return True
	    return False
	d={'a':1,'b':2,'c':3}

	def updatelist(fflist,fmlist):
	        #import os
	        #global fflist
	        #global fmlist
	        try:
	                        
	                ff= open("Flist.txt","r+")
	                fm=open("Mlist.txt","r+")
	               
	        except:
	                fm= open("Mlist.txt","w+")
	                ff= open("Flist.txt","w+")
	               

	        #if os.stat("Flist.txt").st_size == 0:
	         #       ff.write('{"none":"none"}')
	          #      ff.close()
	           #     ff= open("Flist.txt","r+")
	        #if os.stat("Mlist.txt").st_size == 0:
	         #       fm.write('{"none":"none"}')
	          #      fm.close()
	           #     fm=open("Mlist.txt","r+")
	        fmreader = fm.readlines()
	        for row in fmreader:
	                fmlist = row
	        fmlist = eval(fmlist)
	        
	        ffreader = ff.readlines()
	        for row in ffreader:
	                fflist = row
	        fflist = eval(fflist)
	        return fflist, fmlist

	def convertdict(dic):
	    dic = str(dic)
	    retur = ()
	    x = 0
	    while True:
	        start = 0
	        end = 0
	        for i in range (0,len(dic)):
	            
	            if dic[i] == ",":
	                start = i
	                for z in range (i,len(dic)):
	                
	                    if dic[z] == ":":
	                        
	                        end = z
	                        break
	           
	                retur = retur + (dic[int(start)+3:end-1],)
	            if dic[i] == "{" :
	                start = i
	                for z in range (i,len(dic)):
	                  
	                    if dic[z] == ":":
	                        
	                        end = z
	                        break
	              
	                retur = retur + (dic[int(start)+2:end-1],)
	        
	        break
	    return retur

	def dic_to_str(dic):
	    import csv
	    rep=""
	    rep = dic["Date"]+","+dic["Duré"]+","+dic["Fin"]+","+dic["Valide"]+","+dic["M"]+","+dic["F"]+"\n"

	    return rep

	def update_cvs_to_F(csv_name, y, valide):
	    import csv
	    y =y-1
	    file = str(csv_name)+".csv"
	    
	    file_list=[]

	    original = open(file, "r")
	    reader = csv.DictReader(original , delimiter = ',')
	    for row in reader:
	        
	        file_list.append(row)
	   
	    ################### edition
	    new_file_list=[0]*len(file_list)
	    for i in range(len(file_list)):
	        
	        if i==y:
	            
	            edit_dic = dict(file_list[i])
	            edit_dic["Valide"]= valide
	            new_file_list[i]=edit_dic
	            
	        else:
	            new_file_list[i]=file_list[i]

	    original.close()
	    
	    new_file = str(csv_name)+".csv"
	    
	    new = open(file, "w")
	    fieldnames ="Date,Duré,Fin,Valide,M,F\n"
	    
	    
	    new.write(fieldnames)
	    for i in new_file_list:
	        new.write(dic_to_str(dict(i)))

	def update_csv(csv_name):
	    import csv
	    file = str(csv_name)+".csv"
	    
	    file_list=[]

	    original = open(file, "r")
	    reader = csv.DictReader(original , delimiter = ',')
	    for row in reader:
	        
	        file_list.append(row)
	   
	    ################### edition
	    new_file_list=[]
	    for i in range(len(file_list)):

	        edit_dic = dict(file_list[i])
	        valide= edit_dic["Valide"]
	        if valide=="V":
	            new_file_list.append(file_list[i])

	            
	    original.close()
	    
	    new_file = str(csv_name)+".csv"
	    
	    new = open(file, "w")
	    fieldnames ="Date,Duré,Fin,Valide,M,F\n"
	    
	    
	    new.write(fieldnames)
	    for i in new_file_list:
	        print(i)
	        new.write(dic_to_str(dict(i)))

	#update_csv("Data_couv")

	def list_for_tabel():
	    print(verifV())
	    list_tabel =[]
	    list_verif = verifV()
	    #tableaucouv.insert_row([read(3,liste[z-1]),read(5,liste[z-1]),read(6,liste[z-1])])
	    z =1
	    for i in list_verif:
	       
	        list_tabel.append([read(3,i),read(5,i),read(6,i)])
	        
	    return list_tabel
	            
	def temps_restant(date): 
	    import datetime
	    if verif(date) == True:
	        str(date)
	        anne=int(date[6:10])
	        mois = int(date[3:5])
	        jours = int(date[0:2])
	        tday = datetime.date.today()
	        day = datetime.date(anne, mois, jours)
	        j_restant = str(day - tday)
	        for i in range(len(j_restant)):
	            if j_restant[i] == " ":
	                indice = i
	                break
	        return int(j_restant[0:indice])

	def CLE_Fin(ligne):
	    return int( temps_restant(ligne['Fin']))

	def ranger_csv(csv_name):
	    import csv
	    file = str(csv_name)+".csv"
	    
	    file_list=[]

	    original = open(file, "r")
	    reader = csv.DictReader(original , delimiter = ',')
	    for row in reader:
	        
	        file_list.append(row)
	    original.close()
	    ################### edition
	    new_file_list=[]
	   
	    ordre= {}

	    for i in range(len(file_list)):
	        file_listi=file_list[i]
	       
	        if temps_restant(file_listi["Fin"]) > -1:
	            up = {i:temps_restant(file_listi["Fin"])}
	            ordre.update(up)
	           
	    for i in ordre:
	        new_file_list.append(file_list[i])
	   
	    new_file_list = sorted(new_file_list, key=CLE_Fin, reverse = False)
	  
	    
	            
	            
	    
	    ##########réecriture
	    new_file = str(csv_name)+".csv"
	    
	    new = open(file, "w")
	    fieldnames ="Date,Duré,Fin,Valide,M,F\n"
	    
	    
	    new.write(fieldnames)
	    for i in new_file_list:
	        
	        new.write(dic_to_str(dict(i)))

	#ranger_csv("D:\pgOS\data_couv")
	def cleandate(indate):
	    dateclean = str(indate)[8:10]+"/"+str(indate)[5:7]+"/"+str(indate)[0:4]

	    return dateclean

	def write_csv(indate,M,F):

	    from datetime import date

	    today = date.today()
	    print(str(indate))
	    dateclean = cleandate(indate)

	    file = open("data_couv.csv", "a")

	    file.write(str(cleandate(today))+","+str(18)+","+sommedate((dateclean),int(18))+","+"V"+','+str(M)+","+str(F)+"\n")
	    file.flush()
	    file.close()

and my kv file: main.kv

	MDBottomNavigation:
			##"date_selectionneur" : "date_selectionneur"
			MDBottomNavigationItem:
					name: "screnn1"
					#icon: "duck"
					icon: 'format-list-bulleted'
					FloatLayout:
							Label:
									color: (0, 0, 0, 1)
									font_size: 40
									
									text: "List de Pigeon"
									pos_hint: {'x':0, 'y': 0.2}
							Button:
									text: 'Ajouter un Pigeon'
									size_hint: (0.4, 0.1)
									font_size: 40
									
									pos_hint: {'x': 0.3, 'y': 0.4}
							

			MDBottomNavigationItem:
					name: "screnn2"
					icon: "home-outline"
					FloatLayout:
							Label:
									color: (0, 0, 0, 1)
									font_size: 40
									text: "Acceuil"
									pos_hint: {'x':0, 'y': 0.2}
					FloatLayout:
							Label:
									color: (0, 0, 0, 1)
									font_size: 40
									text: app.label_accueil
									pos_hint: {'x':0, 'y': 0.1}
							

					
			MDBottomNavigationItem:
					name: "scren3"
					icon: "calendar"
					FloatLayout:
							Label:
									color: (0, 0, 0, 1)
									font_size: 40
									text: "Couvaison"
									pos_hint: {'x':0, 'y': 0.3}
							Button:
									id: "date_selectionneur"
									text: app.label_date if app.label_date != "" else 'Date de Ponte'
									size_hint: (0.4, 0.1)
									font_size: 40
									
									pos_hint: {'x': 0.3, 'y': 0.45}
									on_release:
											app.show_datepicker()
											app.labeltext()
							
							MDDropDownItem: 
									id: "Femmelle_selc"

									items: app.ffList
									
									pos_hint: {"center_x": .5, "center_y": .4} 
									on_select: app.handle_select_F(*args)
									dropdown_bg: [1, 1, 1, 1]

							MDDropDownItem: 
									id: "Male_selc"
									items: app.fmList 
									pos_hint: {"center_x": .5, "center_y": .3} 
									on_select: app.handle_select_M(*args)
									dropdown_bg: [1, 1, 1, 1]

							Button:
									id: valide_couv
									text: 'Valider'
									pos_hint: {'center_x': 0.5, "center_y": 0.2}
									font_size: 40
									size_hint: (0.4, 0.1)
									on_release:
											app.write_csv_classe(app.label_date,app.handle_select_F_value,app.handle_select_M_value)

**Comment by HeaTTheatR** [comment]
@Qypol342 API breaking changes - https://kivymd.readthedocs.io/en/latest/components/dropdown-item/index.html

**Comment by loan-mgt** [comment]
> @Qypol342 API breaking changes - https://kivymd.readthedocs.io/en/latest/components/dropdown-item/index.html

How can a force update KivyMD on windows?

**Comment by loan-mgt** [comment]
> @Qypol342 API breaking changes - https://kivymd.readthedocs.io/en/latest/components/dropdown-item/index.html

How is it possible that on my windows machine it work under v0.104.0 but not on android?

**Comment by HeaTTheatR** [comment]
@Qypol342 `requirements = kivy==1.11.1, git+https://github.com/HeaTTheatR/KivyMD.git`
