### ISSUE TITLE
DropdownMenu callback stopped working

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#267]
### Description of the Bug

The DropdownMenu callback is not invoked. This worked before the latest MDMenu changes.

### Code and Logs
Below is the example from the docs, modified with adding a callback
https://kivymd.readthedocs.io/en/latest/components/menu/index.html#usage

The text "======selected======" does not appear in the console

```python

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def selected(self):
        print("=====selected=======")
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"icon": "git",
                       "text": f"Item {i}",
                       "callback": self.selected} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button, items=menu_items, width_mult=4
        )

    def build(self):
        return self.screen


Test().run()

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here


### Versions

* OS:  Windows 10
* Python:  Python 3.6.1
* Kivy:   1.11.1
* KivyMD:   master 4/24/2020

**Comment by RobertFlatt** [comment]
Oh I see, the callback specification moved from the menu item to the menu.

Suggestion: an enhancement to the docs for this component would be helpful.

**Comment by pks-97** [comment]
Hi @RobertFlatt, @HeaTTheatR could you please point me where is the error. I am still facing the same error. Some pointers would be great!

**Comment by HeaTTheatR** [comment]
@pks-97 

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)

    def build(self):
        return self.screen


Test().run()
```

https://kivymd.readthedocs.io/en/latest/components/menu/#usage

**Comment by pks-97** [comment]
Hi @HeaTTheatR, thank you for the reply. I read the docs. But can we somehow bind a callback to each of the DropDownMenu items? just like @RobertFlatt tried to do in his code. 

For example, I want to bind a callback to each of the dropdown menu item such that the callback is triggered after selecting a particular item. Any help would be greatly appreciated. Thanks :)

**Comment by HeaTTheatR** [comment]
@pks-97 
```python
    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)
```

**Comment by pks-97** [comment]
Hi, @HeaTTheatR. I tried the exact code as in the documentation and as you suggested. However, upon pressing a menu item I do not get values printed as the menu_callback is supposed to print i.e the instance menu and instance_menu_item do not get printed. I wanted to trigger a callback function upon pressing a menu item in the DropDown menu, but as of now I cannot find any method of doing it using the current docs, could you please suggest a way

**Comment by HeaTTheatR** [comment]
@pks-97 

```python
    def menu_callback(self, instance_menu, instance_menu_item):
        if instance_menu_item.text == "Item 1":
            self.calllback_1()
        [...]
```

**Comment by themockingjester** [comment]
@HeaTTheatR 
i am also facing the same issue when i am clicking on menu items above menu_callback method is not printing anything

**Comment by HeaTTheatR** [comment]
@themockingjester Use the KivyMD library from the master branch.

**Comment by themockingjester** [comment]
@HeaTTheatR  I am using kivymd library still not working

**Comment by iotpanama** [comment]
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print('Por aqui paso compadre')
        print(instance_menu, instance_menu_item)

    def build(self):
        return self.screen


Test().run()

**Comment by iotpanama** [comment]
### The menu_callback in the DropdownMenu component does not work
*** Good evening. I am trying to find a solution to the problem of the menu_callback function of the sketch presented below. since it does not return anything. I have reviewed the KivyMD version and it is the master drama. I leave this application to be tested. since I am in a very big development with KivyMD for a telemetric control.***

from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
      def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print('Por aqui paso compadre')
        print(instance_menu, instance_menu_item)

    def build(self):
        return self.screen


Test().run()

**Comment by HeaTTheatR** [comment]
@iotpanama Use KivyMD library from master branch.

**Comment by charlie2clarke** [comment]
@HeaTTheatR I'm using v0.104.1 and call back when clicking menu items isn't working for me either

**Comment by HeaTTheatR** [comment]
@HeaTTheatR Use KivyMD library from master branch.

**Comment by iotpanama** [comment]
I´m using work with 0.104.1 version and download the master branch. I have another solution that sending for this way working KivyMD framework.

 

def __init__(self, **kwargs):

        super().__init__(**kwargs)

        self.app = MDApp.get_running_app()

        Clock.schedule_once(self.on_start)

 

def on_start(self,*args):

        # menu item

        unit_items = [{"text": f"{i}",} for i in self.unit]

        # create dropdown menu

        self.menu_in = MDDropdownMenu(

            caller=self.ids.unit_in,

            items=unit_items,

            width_mult=2.8,

            position='bottom',

            callback=self.menu_callback_in

        )

 

        # create dropdown menu

        self.menu_out = MDDropdownMenu(

            caller=self.ids.unit_out,

            items=unit_items,

            width_mult=2.8,

            position='bottom',

            callback=self.menu_callback_out

        )

 

    def menu_callback_in(self, instance_menu_item):

        print(instance_menu_item.text)

        if instance_menu_item.text == "psi":

            self.unit_in = "psi"

            print("1")

        elif instance_menu_item.text == "bar":

            self.unit_in = "bar"

            print("2")

        elif instance_menu_item.text == "pas":

            self.unit_in = "pas"

            print("3")

        elif instance_menu_item.text == "mmh":

            self.unit_in = "mmh"

            print("4")

        self.menu_in.dismiss()

        Clock.schedule_once(self.sending)

 

    def menu_callback_out(self, instance_menu_item):

        print(instance_menu_item.text)

        if instance_menu_item.text == "psi":

            self.unit_out = "psi"

            print("1")

        elif instance_menu_item.text == "bar":

            self.unit_out = "bar"

            print("2")

        elif instance_menu_item.text == "pas":

            self.unit_out = "pas"

            print("3")

        elif instance_menu_item.text == "mmh":

            self.unit_out = "mmh"

            print("4") 

        self.menu_out.dismiss()

        Clock.schedule_once(self.sending)

 

As you can see in the graph, these two dropdown calling two callbacks and it is working perfectly. I think some other aspects of the framework need to be improved, such as the response speed of the buttons as well as a number of other details that I can share with you. I am developing an app for a client to control pressure control valves of the city water pipeline.

 

 

____________________________



 

Ing. Jorge Quevedo

Movil +50763280221

Movil +50762028069

Web:  <http://www.iotpanama.com/> www.iotpanama.com

Panama city - Panama

 

Por favor, tenga en cuenta su responsabilidad ambiental.

Antes de imprimir este mensaje de correo electrónico, pregúntese si realmente necesita una copia en papel.

 

El contenido de este mensaje es confidencial.

Este mensaje no tiene carácter vinculante.

Este mensaje va dirigido, de manera exclusiva, a su destinatario y contiene información confidencial sujeta al secreto profesional cuya divulgación no está permitida por la ley. En caso de haber recibido este mensaje por error le rogamos, que de forma inmediata, nos lo comunique mediante correo electrónico remitido a nuestra atención y proceda a su eliminación así como a la de cualquier documento adjunto al mismo.

 

De: Yuri Ivanov <notifications@github.com> 
Enviado el: jueves, 4 de marzo de 2021 2:20 p. m.
Para: kivymd/KivyMD <KivyMD@noreply.github.com>
CC: Jorge Quevedo <jquevedo@iotpanama.com>; Mention <mention@noreply.github.com>
Asunto: Re: [kivymd/KivyMD] DropdownMenu callback stopped working (#267)

 

 <https://github.com/HeaTTheatR> @HeaTTheatR Use KivyMD library from master branch.
