### ISSUE TITLE
MDBottomNavigation bug on Kivymd-master

### ISSUE THREAD

**Issue by Felipe738743872** [kivymd/KivyMD#271]
### Description of the Bug

Hi! Why is MDBottomNavigation strange on KivyMD-Master?
There is no such problem in kivymd...

### main.py

```python
from kivymd.app import MDApp
from kivy.lang.builder import Builder as New
from kivy.uix.screenmanager import Screen
from kivymd.uix.dialog import MDDialog
from kivymd.uix.button import MDFlatButton

KV = """
#:import MDFillRoundFlatButton kivymd.uix.button.MDFillRoundFlatButton

ScreenManager:
    Screen:
        name: "menu"
        Button
            text: "Wait 5 seconds to press this button"
            on_release: app.root.current = "myscreen"

        MDToolbar
            title: "my screen 1"
            md_bg_color: 0, 0.5, 0.5, 1
            elevation: 12
            size_hint: 1, 0.1
            pos_hint: {"top":1}
            left_action_items: [["menu", lambda x: self]]
            right_action_items: [["power", lambda x: app.dialog_exit()]]


    Myscreen
        name: "myscreen"
        BoxLayout:
            orientation: "vertical"
        
            MDToolbar:
                title: "My screen 2"
                md_bg_color: 0, 0.5, 0.5, 1
                size_hint: 1, 0.1

            MDBottomNavigation
                MDBottomNavigationItem
                    text: "example 1"
                    name: "screen1"
                    
                MDBottomNavigationItem:
                    text: "example 2"
                    icon: 'border-all'
                    name: 'screen2'
                
                MDBottomNavigationItem:
                    text: "example 3"
                    icon: "card-text"
                    name: "screen3"
"""

class Myscreen(Screen):
    pass

class Builder(MDApp):
    def build(self, *args):
        self.theme_cls.theme_style = 'Dark'
        return New.load_string(KV)

    def back_screen(self):
        MDApp.get_running_app().root.transition.direction = 'right'
        MDApp.get_running_app().root.current = 'menu'

    def dialog_exit(self):
        self.dialog = MDDialog(
            text="Você quer sair?",
            size_hint=(0.50, 0.40),
            radius=[20, 7, 20, 7],
            buttons=[
                MDFlatButton(
                    text="Cancelar", text_color=self.theme_cls.primary_color,
                    on_release=self.auto_dismiss),
                MDFlatButton(
                    text="Sim", text_color=self.theme_cls.primary_color,
                    on_release=self.stop)
            ]
        )
        self.dialog.open()

    def auto_dismiss(self, text_of_selection):
        self.dialog.dismiss()


Builder().run()
```

### Versions

* OS: Mac High Sierra 10.13.6
* Python: 3.7.6
* Kivy: 1.11.1
* KivyMD: 0.104.0 - MASTER

**Comment by HeaTTheatR** [comment]
@Felipe738743872 While I can offer this option:

```

            MDBottomNavigation:
                id: bottom_navigation
```

```
    Myscreen
        name: "myscreen"
        on_enter: bottom_navigation._refresh_tabs()
```

**Comment by mateoaita** [comment]
Oh thanks, i could fit them the right way now!
The problem is that i have 5 items and if the screen isn't wide enough, some items become invisible at the screen.
There should be 5 items and you can only see 3
![foto tact it 2](https://user-images.githubusercontent.com/48486276/84781989-e5f5ea80-afbd-11ea-9637-c78a748605e6.png)

**Comment by HeaTTheatR** [comment]
@mateoaita https://material.io/components/bottom-navigation#usage

![Снимок экрана 2020-06-16 в 17 12 34](https://user-images.githubusercontent.com/16930280/84785900-b7dfcd00-aff4-11ea-9f9b-a532991fb342.png)

**Comment by HeaTTheatR** [comment]
Fix https://github.com/HeaTTheatR/KivyMD/commit/f2a57f966c1e9db9ac4868cd92153b9b95d6d43d

**Comment by BananaMasterz** [comment]
> ```python
> from kivymd.app import MDApp
> from kivy.lang.builder import Builder as New
> from kivy.uix.screenmanager import Screen
> from kivymd.uix.dialog import MDDialog
> from kivymd.uix.button import MDFlatButton
> 
> KV = """
> #:import MDFillRoundFlatButton kivymd.uix.button.MDFillRoundFlatButton
> 
> ScreenManager:
>     Screen:
>         name: "menu"
>         Button
>             text: "Wait 5 seconds to press this button"
>             on_release: app.root.current = "myscreen"
> 
>         MDToolbar
>             title: "my screen 1"
>             md_bg_color: 0, 0.5, 0.5, 1
>             elevation: 12
>             size_hint: 1, 0.1
>             pos_hint: {"top":1}
>             left_action_items: [["menu", lambda x: self]]
>             right_action_items: [["power", lambda x: app.dialog_exit()]]
> 
> 
>     Myscreen
>         name: "myscreen"
>         BoxLayout:
>             orientation: "vertical"
>         
>             MDToolbar:
>                 title: "My screen 2"
>                 md_bg_color: 0, 0.5, 0.5, 1
>                 size_hint: 1, 0.1
> 
>             MDBottomNavigation
>                 MDBottomNavigationItem
>                     text: "example 1"
>                     name: "screen1"
>                     
>                 MDBottomNavigationItem:
>                     text: "example 2"
>                     icon: 'border-all'
>                     name: 'screen2'
>                 
>                 MDBottomNavigationItem:
>                     text: "example 3"
>                     icon: "card-text"
>                     name: "screen3"
> """
> 
> class Myscreen(Screen):
>     pass
> 
> class Builder(MDApp):
>     def build(self, *args):
>         self.theme_cls.theme_style = 'Dark'
>         return New.load_string(KV)
> 
>     def back_screen(self):
>         MDApp.get_running_app().root.transition.direction = 'right'
>         MDApp.get_running_app().root.current = 'menu'
> 
>     def dialog_exit(self):
>         self.dialog = MDDialog(
>             text="Você quer sair?",
>             size_hint=(0.50, 0.40),
>             radius=[20, 7, 20, 7],
>             buttons=[
>                 MDFlatButton(
>                     text="Cancelar", text_color=self.theme_cls.primary_color,
>                     on_release=self.auto_dismiss),
>                 MDFlatButton(
>                     text="Sim", text_color=self.theme_cls.primary_color,
>                     on_release=self.stop)
>             ]
>         )
>         self.dialog.open()
> 
>     def auto_dismiss(self, text_of_selection):
>         self.dialog.dismiss()
> 
> 
> Builder().run()
> ```

I just ran this with the Master (cant find the version but I download it today with the font update changes) and I get this:

![image](https://user-images.githubusercontent.com/45745548/93567908-0f952800-f998-11ea-91ad-1278476d9999.png)

If I resize the window or move it, the center themselves. I tried refresh tabs on enter but did nothing. I also digged in the librady but couldn't find why it's happening.

**Comment by BananaMasterz** [comment]
Note that this happens only if the bottom navigation is part of a screen manager. If it's loaded the moment the app starts it works normally.

**Comment by kulothunganug** [comment]
> @Felipe738743872 While I can offer this option:
> 
> ```
> 
>             MDBottomNavigation:
>                 id: bottom_navigation
> ```
> 
> ```
>     Myscreen
>         name: "myscreen"
>         on_enter: bottom_navigation._refresh_tabs()
> ```
i used `refresh_tabs()`(in latest version) but
problem not solved bro

**Comment by BananaMasterz** [comment]
> > @Felipe738743872 While I can offer this option:
> > 
> > ```
> > 
> >             MDBottomNavigation:
> >                 id: bottom_navigation
> > ```
> > 
> > ```
> >     Myscreen
> >         name: "myscreen"
> >         on_enter: bottom_navigation._refresh_tabs()
> > ```
> i used `refresh_tabs()`(in latest version) but
> problem not solved bro

I solved it by resizing the window +1 and -1 just to trigger the on_resize function

**Comment by BananaMasterz** [comment]
@Kulothungan16 
```python

from kivy.core.window import Window

self.parent.current = "name of the screen"
Window.size = (Window.width+1, Window.height+1)
Window.size = (Window.width-1, Window.height-1)

```
That's my solution

**Comment by kulothunganug** [comment]
> @Kulothungan16
> 
> ```python
> from kivy.core.window import Window
> 
> self.parent.current = "name of the screen"
> Window.size = (Window.width+1, Window.height+1)
> Window.size = (Window.width-1, Window.height-1)
> ```
> 
> That's my solution

bro, I can't understand what are you saying (i am a noobie :( )
can you give an example code

**Comment by podraco** [comment]
self.parent.current = "name of the screen"
this makes no sence...
you shall never import inside a class or a function, it might create a duplicate of the function in memory

**Comment by podraco** [comment]
i advice you yo check how imports works in python

**Comment by kulothunganug** [comment]
> ```python
> self.parent.current = "name of the screen"
> Window.size = (Window.width+1, Window.height+1)
> ```

thx bro it worked

**Comment by BananaMasterz** [comment]
> self.parent.current = "name of the screen"
> this makes no sence...
> you shall never import inside a class or a function, it might create a duplicate of the function in memory
> 

Yes I don't actually import it inside the class... I just copied the lines needed to make it work.
