### ISSUE TITLE
How do I open another .kv screen by just pressing a button 

### ISSUE THREAD

**Issue by pj-mathematician** [kivymd/KivyMD#272]
I am making an app and want to incorporate a screen manager, but I am having problems while working with both kivy and kivyMD.
In kivy, i was using kivy.uix.screenmanager and adding an 'on_release' condition under the button. But this doesn't seem to work well with kivyMD. So please suggest a way to do this

**Comment by HeaTTheatR** [comment]
@pj-mathematician Your question is too general. I don’t know what you are doing and don’t see your code. `KivyMD` has no problems with the screen manager.

**Comment by pj-mathematician** [comment]
This is my main.py file
````
from kivy.lang import Builder
from kivy.uix.screenmanager import *
from kivymd.uix.label import MDLabel
from kivymd.font_definitions import theme_font_styles
from kivymd.app import *

Builder.load_file('SignUp.kv')
class SignUpWindow(Screen):
	pass

sm = ScreenManager(transition=CardTransition())
sm.add_widget(SignUpWindow(name='SignUp'))
class Test(MDApp):
	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.screen = Builder.load_file('Login.kv')

	def build(self):
		self.theme_cls.theme_style = "Dark"  
		screen = Screen()
		
		return self.screen
	
	

if __name__ == '__main__':
	Test().run()
````
This is my button in 'Login.py'
````
    MDFillRoundFlatButton:
    	id:subut
        size_hint: (0.2,0.0675)
        font_size: '20sp'
        text: "Sign Up"
        pos_hint:{'center_x':0.62,'center_y':0.37}
        on_release:
             app.root.manager.current = 'SignUp'
````
Now when I am using the button, the screen is not changing

**Comment by HeaTTheatR** [comment]
@pj-mathematician I do not understand what you need?

**Comment by pj-mathematician** [comment]
How should I use the screen manager of kivy to switch between screens of kivyMD by the use of a button

**Comment by HeaTTheatR** [comment]
@pj-mathematician Also, as is done in `Kivy` - https://kivy.org/doc/stable/api-kivy.uix.screenmanager.html

**Comment by pj-mathematician** [comment]
https://stackoverflow.com/questions/61471347/how-to-use-a-kivy-screen-manager-simultaneously-with-kivymd
Please check this sir

**Comment by HeaTTheatR** [comment]
@pj-mathematician You are not working correctly with the screen manager. Read carefully the information that is described on this page - https://kivy.org/doc/stable/api-kivy.uix.screenmanager.html

**Comment by tasen-sp** [comment]
How can I switch screen without builder.pls tell me
