### ISSUE TITLE
Proper text not view in MDTextField 

### ISSUE THREAD

**Issue by WithSJ** [kivymd/KivyMD#274]
### Description of the Bug

when typing in MDTextField char move right to left when type more text. its perfectly work but problem in last char that i typed in that not show.
To view that char need to use right arrow key to move cursor after that char view 

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.lang import Builder
kv="""
MDTextField:
    hint_text: "Email"
    pos_hint: {"center_x":0.5, "center_y":0.6}
    size_hint: 0.2,0.09

"""
class MyApp(MDApp):
    def build(self):
        screen = Screen()
        screen.add_widget(Builder.load_string(kv) )
        
        return screen

MyApp().run()
```

**Comment by allasca** [comment]
@WithSJ @HeaTTheatR this is a bug of TextInput
![](https://cdn.discordapp.com/attachments/440127913837330444/717050918096338984/Peek_2020-06-01_23-23.gif)

**Comment by WithSJ** [comment]
@HeaTTheatR @allasca
when the same code run in the android text field works perfectly...
I think this bug only in desktop

**Comment by podraco** [comment]
it might be from SDL2, so it's internal of Kivy

**Comment by podraco** [comment]
It looks like it's a problem from kivy
the cursor moves the character amount before it shows in screen, so it might have not real limiter on the right side while the text is "moved" to the left
simplified:
```yaml
press a key
  add char to textbox
  the cursor moves correctly to the right of the last letter added
  then the cursor should move with the text back to the limit. but somehow the text is in the wrong position . 
```
The text it's at the maximum length. 
![python_oCvDVH42EG](https://user-images.githubusercontent.com/5509325/90386967-eefd4980-e04a-11ea-8628-ad436197b9a3.png)

char A is added and it's out of the stencil view, but inside the label base:
![python_GscujagOyX](https://user-images.githubusercontent.com/5509325/90387046-17854380-e04b-11ea-9edf-b09077233e16.png)

char B is added, same as A, the cursor is in the correct position, but the end of the label it's not.
![python_FwbDVEYwOT](https://user-images.githubusercontent.com/5509325/90387073-25d35f80-e04b-11ea-915a-789dc63cda47.png)

Key left is pressed, so the textbox update event launchs
![python_LtD4UsGj1D](https://user-images.githubusercontent.com/5509325/90387149-469bb500-e04b-11ea-91ac-ece533a5419e.png)

(it might not be a stencil view, but for explaining, acts the same.)

**Comment by HeaTTheatR** [comment]
I am closing this issue because it is not related to `KivyMD` library.
