### ISSUE TITLE
Running App in Xcode 

### ISSUE THREAD

**Issue by fraanco7** [kivymd/KivyMD#275]
Hello,
I need to build an app for a student project. Everything works fine, however, when I launch the app with the Iphonesimulator in Xcode the app crashes immediately with the following Error:

<img width="623" alt="Bildschirmfoto 2020-04-28 um 21 37 57" src="https://user-images.githubusercontent.com/64320249/80530436-49d63c80-8999-11ea-9e70-5d550af349f9.png">

Running an app without kivymd works fine. Does someone know how to fix this?

**Versions**

OS: Mac Catalina 10.15.4
Python: 3.7.7
Kivy: v1.11.1
KivyMD: v0.104.1
Xcode: 10.3

**Comment by HeaTTheatR** [comment]
@fraanco7 The essence of the issue is missing.
