### ISSUE TITLE
Xcode - ModuleNotFoundError: No module named 'kivymd'

### ISSUE THREAD

**Issue by fraanco7** [kivymd/KivyMD#276]
Hello,
I need to build an app for a student project. Everything works fine, however, when I launch the app with the Iphonesimulator in Xcode the app crashes immediately with the following Error:

<img width="623" alt="Bildschirmfoto 2020-04-28 um 21 37 57" src="https://user-images.githubusercontent.com/64320249/80531552-1e545180-899b-11ea-96da-4c7dfd92135f.png">

Running an app without kivymd works fine. Does someone know how to fix this?

Versions

OS: Mac Catalina 10.15.4
Python: 3.7.7
Kivy: v1.11.1
KivyMD: v0.104.1
Xcode: 10.3

**Comment by HeaTTheatR** [comment]
https://github.com/kivy/kivy-ios/issues/320

**Comment by fraanco7** [comment]
Thank you very much! Copy the kivymd package from `/usr/local/lib/python3.7/site-packages` into `kivy-ios/dist/root/python3/lib/python3.8` works for me.
