### ISSUE TITLE
Problem in creating Apk file 

### ISSUE THREAD

**Issue by WithSJ** [kivymd/KivyMD#280]
### Description of the Bug

When I use KivyMD code and compile apk for android that app did not run in android auto close when I start that app on my phone.
but when I use only kivy module and compile apk that apk works perfectly.

### Code and Logs
# kivy code that apk perfectly works
```python
from kivy.app import App
from kivy.uix.label import Label
class MyApp(App):
    def build(self):
        return Label(text="With.SJ")
MyApp().run()
```
# kivymd code that apk not works
```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
class MyApp(MDApp):
    def build(self):
        return MDLabel(text="With.SJ",halign="center")
MyApp().run()
```
### Versions

* OS: Ubuntu
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@WithSJ What is the "auto close"???

**Comment by WithSJ** [comment]
@HeaTTheatR  when I start the app in my phone that app close immediately.

**Comment by HeaTTheatR** [comment]
@WithSJ Attach full log.

**Comment by WithSJ** [comment]
@HeaTTheatR Log after this command || buildozer android debug deploy run || show in terminal
[log.txt](https://github.com/HeaTTheatR/KivyMD/files/4569671/log.txt)

**Comment by HeaTTheatR** [comment]
@WithSJ `adb logcat | grep python`

**Comment by WithSJ** [comment]
@HeaTTheatR 
[log.txt](https://github.com/HeaTTheatR/KivyMD/files/4569686/log.txt)

**Comment by HeaTTheatR** [comment]
@WithSJ https://github.com/HeaTTheatR/KivyMD#how-to-use-with-buildozer
