### ISSUE TITLE
MDFloatingActionButtonSpeedDial how do I interact with the sub buttons

### ISSUE THREAD

**Issue by pj-mathematician** [kivymd/KivyMD#281]
After I have added the data dictionary, how do I give individual functions to all the components

**Comment by HeaTTheatR** [comment]
@pj-mathematician https://kivymd.readthedocs.io/en/latest/components/button/index.html#kivymd.uix.button.MDFloatingActionButtonSpeedDial.callback

**Comment by pj-mathematician** [comment]
Sir, can you give me an example of how to use it or tell me how to use it, i can not find it anywhere

**Comment by HeaTTheatR** [comment]
@pj-mathematician 
```python
from kivy.uix.screenmanager import Screen

from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial


class Example(MDApp):
    data = {
        'language-python': 'Python',
        'language-php': 'PHP',
        'language-cpp': 'C++',
    }

    def build(self):
        screen = Screen()
        speed_dial = MDFloatingActionButtonSpeedDial(callback=self.callback)
        speed_dial.data = self.data
        speed_dial.rotation_root_button = True
        screen.add_widget(speed_dial)
        return screen

    def callback(self, instance):
        print(instance.icon)

Example().run()
```

**Comment by pj-mathematician** [comment]
Yes, i saw that, if I want to add a function which gets executed when 'Python' is tapped, what should I do?

**Comment by HeaTTheatR** [comment]
@pj-mathematician I do not understand.

**Comment by pj-mathematician** [comment]
How to call different functions when different sub buttons are tapped?,how should I use callback()

**Comment by HeaTTheatR** [comment]
@HeaTTheatR ```if-else```

**Comment by HeaTTheatR** [comment]
@pj-mathematician 
```python
    def callback(self, instance):
        if instance.icon == value:
            calback1()
        if instance.icon == value2:
            calback2()
```

**Comment by pj-mathematician** [comment]
Thanks alot, i am very sorry to disturb you

**Comment by Vinzth** [comment]
can u tell me the code you applied to callback() function
