### ISSUE TITLE
HotReloadViewer issue 

### ISSUE THREAD

**Issue by did0u007** [kivymd/KivyMD#282]
### Description of the Bug

Unable to import package 'kivymd.utils.hot_reload_viewer.HotReloadViewer'

* OS: linux 
* Python: 36 & 37
* Kivy: 1.11
* KivyMD: 0.104

**Comment by HeaTTheatR** [comment]
@did0u007 Reinstall library from master branch.

**Comment by richierh** [comment]
Now it does not work still using python 3.7.8 and kivyMD master

**Comment by chris-aeviator** [comment]
same for me

@HeaTTheatR  why has this been closed , could you please provide info on howto solve the issue?
Running on kivy 2.0 , reinstalling kivyMD via pip or via pip git does not resolve the issue

![image](https://user-images.githubusercontent.com/11522213/103303718-025fee80-4a07-11eb-9877-9c82b5173116.png)

**Comment by HeaTTheatR** [comment]
@did0u007 
![Снимок экрана 2020-12-30 в 10 58 45](https://user-images.githubusercontent.com/16930280/103338046-2ca8bf00-4a8e-11eb-888c-083de9155e25.png)

**Comment by chris-aeviator** [comment]
@HeaTTheatR could you please explain? This seems like the most up2date version to me?

**Comment by HeaTTheatR** [comment]
@chris-aeviator https://github.com/kivymd/KivyMD/blob/master/kivymd/__init__.py#L35

**Comment by danielgis** [comment]
pip install kivymd==0.104.2....work!
