### ISSUE TITLE
MDDialog buttons, on_release events are not called

### ISSUE THREAD

**Issue by gunerguney** [kivymd/KivyMD#284]
I was already using the dialog screen. When I made changes with the update, I noticed that the buttons were not clicked.

When I run the MDDialog test, the buttons are not clickable on the dialog screen. The dialog closes as if there were no buttons on the screen.

from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.dialog import MDDialog

KV = '''
<Content>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    MDTextField:
        hint_text: "City"

    MDTextField:
        hint_text: "Street"

FloatLayout:

    MDFlatButton:
        text: "ALERT DIALOG"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_confirmation_dialog()
'''

class Content(BoxLayout):
    pass

class Example(MDApp):
    dialog = None

    def build(self):
        return Builder.load_string(KV)

    def OKBtnHandler(self):
        print("OK-Pressed")

    def show_confirmation_dialog(self):
        if not self.dialog:
            self.dialog = MDDialog(
                title="Address:",
                type="custom",
                content_cls=Content(),
                buttons=[
                    MDFlatButton(
                        text="CANCEL", text_color=self.theme_cls.primary_color
                    ),
                    MDFlatButton(
                        text="OK", text_color=self.theme_cls.primary_color, on_release=self.OKBtnHandler
                    ),
                ],
            )
        self.dialog.open()

Example().run()

### Versions

* OS: Ubuntu 18.04
* Python: 3.6
* Kivy: 1.10.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@gunerguney 
```python
        self.dialog = MDDialog(
            auto_dismiss=False,
            ...
            )
```
