### ISSUE TITLE
weak reference error in MDToolBar

### ISSUE THREAD

**Issue by Charanpreet-Singh-AI** [kivymd/KivyMD#286]
### Description of the Bug

weak reference error in left_action_button and right_action_button in mdtoolbar

logs :

> 05-05 16:40:33.661 23302 23332 I python  :  Traceback (most recent call last):
05-05 16:40:33.661 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/app/main.py", line 1316, in <module>
05-05 16:40:33.661 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
05-05 16:40:33.661 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
05-05 16:40:33.662 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
05-05 16:40:33.662 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
05-05 16:40:33.662 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 339, in idle
05-05 16:40:33.663 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/clock.py", line 591, in tick
05-05 16:40:33.663 23302 23332 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.663 23302 23332 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.663 23302 23332 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.664 23302 23332 I python  :    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
05-05 16:40:33.664 23302 23332 I python  :    File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
05-05 16:40:33.664 23302 23332 I python  :    File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/weakmethod.py", line 56, in is_dead
05-05 16:40:33.664 23302 23332 I python  :  ReferenceError: weakly-referenced object no longer exists
05-05 16:40:33.664 23302 23332 I python  : Python for android ended.

**Comment by HeaTTheatR** [comment]
@Charanpreet123 https://github.com/HeaTTheatR/KivyMD/issues/273

**Comment by Charanpreet123** [comment]
i got this error again and again , whenever i use left_action_button and right_action_button

**Comment by HeaTTheatR** [comment]
@Charanpreet123 https://github.com/HeaTTheatR/KivyMD/issues/new?assignees=&labels=&template=bug_report.md&title=
