### ISSUE TITLE
Dynamically built menu optimization

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#289]
### Description of the Bug
The menu documentation tells me what not to do when building dynamic menus in order to avoid latency issues:

> menu = MDDropdownMenu(caller=self.screen.ids.button, items=menu_items)
> menu.open()

But it does not tell me what to do to minimize the latency issue, in cases that are not the case to avoid.

I use the API not .kv

After changing a menu the menu does not get rebuilt until menu.open() , apparently regardless of what happens in between. The code does not look like the quote from the docs, but it behaves like it.

How do I force a rebuild of the menu when I create it? 
If this is possible please add to the docs.

Unrelated feature request: the menu always leaves space for left and right icons for each item. It would be nice to disable these if the user does not use icons. 

### Versions

* OS: Windows 10 , Android 10
* Python: 3.8.2
* Kivy: 2.0.0rc1
* KivyMD: master

**Comment by HeaTTheatR** [comment]
Dublicate - https://github.com/kivymd/KivyMD/issues/624
