### ISSUE TITLE
How can we open MDFileManager in android devices

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#290]
I have been trying to implement the MDFileManager feature for android devices but I am not to get android device internal storage for android devices so do you people have implemented it for Android devices? if you have any idea how it is possible then please help me to implement it.

**Comment by HeaTTheatR** [comment]
The question is not related to the `KivyMD` library.

**Comment by wasimafser** [comment]
> I have been trying to implement the MDFileManager feature for android devices but I am not to get android device internal storage for android devices so do you people have implemented it for Android devices? if you have any idea how it is possible then please help me to implement it.

you should set storage permission first.
EDIT: I'm also facing the same problem ! after setting storage permission i get the following error: 
`jnius.jnius.JavaException: Class not found b'org/jnius/NativeInvocationHandler'`

**Comment by navjotcis** [comment]
@wasimafser and @HeaTTheatR Now I am successfully able to get the access of internal storage in android devices but facing some other kivyMD related issue so the problem is when I am clicking on back directory option then the first time it  is working 

![image](https://user-images.githubusercontent.com/33522186/81299104-56dae600-9093-11ea-8a53-cf090a975528.png)

and when I am clicking it again

![image](https://user-images.githubusercontent.com/33522186/81299164-6ce8a680-9093-11ea-9e01-1b94703b9ba4.png)

then it is giving exception in the MD file and this error is only coming in android devices so if anyone knows the solution please suggest to me. Error is given below 

![image](https://user-images.githubusercontent.com/33522186/81298757-d9af7100-9092-11ea-8023-04cdef90c707.png)

**Comment by HeaTTheatR** [comment]
@navjotcis This bug is fixed in the latest version of the library.

**Comment by wasimafser** [comment]
Yes , it works for me too without that problem atleast !
