### ISSUE TITLE
Change title color of dialog box

### ISSUE THREAD

**Issue by pj-mathematician** [kivymd/KivyMD#291]
I am not able to find an attribute to change the color of the title of the MDDialog box. I tried to search the master file, https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/dialog.py#L119 and the documentation but wasn't able to find anything.

**Comment by HeaTTheatR** [comment]
@pj-mathematician 
https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/dialog.py#L119
https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/dialog.py#L137
