### ISSUE TITLE
MDCard border_radius property not working

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#293]
I tried to give border_ radius property to my MDCard but it is not working so I ended up using RoundedRectangle to achieve that (it will be very nice if you guys fix it)

**Comment by pooory** [comment]
People advise to use canvas its OK, but it increase your coding and make it very complex. Just go to the Kivymd>uix>card.py line 631 change the default from 3dp to for example 20dp or whatever you want. then go back to your code and type radius: [] and insert your desire number from 20 to 0. Done!!!

**Comment by kengoon** [comment]
> People advise to use canvas its OK, but it increase your coding and make it very complex. Just go to the Kivymd>uix>card.py line 631 change the default from 3dp to for example 20dp or whatever you want. then go back to your code and type radius: [] and insert your desire number from 20 to 0. Done!!!

Thanks man

**Comment by HeaTTheatR** [comment]
@kengoon Do not close issues marked "type-enhancement." This shortcut is intended for developers so that they can make improvements related to this issue.

**Comment by kengoon** [comment]
Ok... Never saw that

**Comment by HeaTTheatR** [comment]
@kengoon 
```
MDCard:
    radius: [15,]
```
