### ISSUE TITLE
managerswiper component not found

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#297]

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/blob/master/docs/sources/changelog/0.104.0.rst

![Снимок экрана 2020-05-10 в 16 40 24](https://user-images.githubusercontent.com/16930280/81500624-06a29480-92dc-11ea-8cd7-4e176f342ca5.png)

**Comment by aprilahijriyan** [comment]
Why deleted?

**Comment by HeaTTheatR** [comment]
@aprilahijriyan This widget has nothing to do with Material Design.
