### ISSUE TITLE
Not all of button inside a dialog is clickable

### ISSUE THREAD

**Issue by AnonymousX86** [kivymd/KivyMD#299]
### Description of the Bug

I've tried to use many dialogs, but I've probably found a bug. When a dialog opens I can click only above text bottom line. Everything what's under the text is not clickable.

### Code and Logs

```python
def show_ctx(self, instance):
    _ctx_dialog = MDDialog(
        title=instance.text.capitalize(),
        text='',
        buttons=[
            MDRectangleFlatIconButton(
                icon='content-copy',
                text='Do something',
                on_release=lambda x: print('First button clicked')
            ),
            MDRectangleFlatIconButton(
                icon='arrow-left-thick',
                text='Back',
                on_release=lambda x: _ctx_dialog.dismiss()
            )
        ]
    )
    _ctx_dialog.open()
```

### Screenshots

This is clickable area on button:
![image](https://user-images.githubusercontent.com/53279236/81751358-9187b880-94af-11ea-9eaa-bfe50f6d0958.png)

### Versions

* OS: Windows 10
* Python: 3.7.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/issues/284
