### ISSUE TITLE
No cursor blink with kivy 1.10.1 in MDTextField

### ISSUE THREAD

**Issue by BillBridge** [kivymd/KivyMD#30]
Hi,
I upgraded from kivy 1.10.0 to 1.10.1 which caused the cursor in MDTextField to disappear. It can be reproduced with the Kitchen_sink demo set. I tried to change the cursor color but that did not help.
I am running Windows 10.

**Comment by HeaTTheatR** [comment]
@BillBridge On my computer, the problem does not reproduce!
