### ISSUE TITLE
Errors and on focus in kivymd text fields

### ISSUE THREAD

**Issue by pj-mathematician** [kivymd/KivyMD#301]
the code snippet attached, i have made two input kivymd input fields for email and confirm email. I want to show a red error message if the text in the confirm email section doesn't match with the email section. my attached code does this fine but has some bugs in it for example-

The code snippet-
```
        DefaultInput:
            id: email
            hint_text: 'Enter Email ID'
            pos_hint: {'center_x': 0.5, 'center_y': 0.55}
            helper_text: "Enter Email"
            helper_text_mode: "on_focus"    

        DefaultInput:
            id: confirm_email
            hint_text: 'Confirm Email ID'
            pos_hint: {'center_x': 0.5, 'center_y': 0.45}
            helper_text: "Confirm Email" if confirm_email.text=='' else "Emails do not match" if confirm_email.text!=email.text else "Perfect !"
            helper_text_mode: "on_focus" if confirm_email.text=='' else "on_focus" if confirm_email.text!=email.text else "on_focus"   
            error : False if confirm_email.text=='' else True if confirm_email.text!=email.text else False

<DefaultInput@MDTextField>:
    size_hint: 0.50, 0.10
```
Examples-- [Initial photo (looks as if it is gonna work fine)](https://i.stack.imgur.com/hZO3p.png)

[The error message that I should get(still looks fine)](https://i.stack.imgur.com/ayDoE.png)

[First bug when I changed back to correct email](https://i.stack.imgur.com/o3Ahx.png)

[But when I tap outside the box, it becomes fine](https://i.stack.imgur.com/Tl3Sk.png)

[Another bug that I am getting when I only input one character the box doesn't become red](https://i.stack.imgur.com/iLhHq.png)

Please help me with these bugs

**Comment by HeaTTheatR** [comment]
The code works great!

**Comment by pj-mathematician** [comment]
Please check the links i have attached, these are the bugs i want to remove

**Comment by HeaTTheatR** [comment]
@pj-mathematician  I do not see any errors!

**Comment by pj-mathematician** [comment]
https://i.stack.imgur.com/iLhHq.png

**Comment by HeaTTheatR** [comment]
@pj-mathematician Where do you see error?

**Comment by pj-mathematician** [comment]
The two text fields do not match but there isn't a red outline of the textfield

**Comment by HeaTTheatR** [comment]
@pj-mathematician https://kivymd.readthedocs.io/en/latest/components/text-field/index.html#helper-text-mode-on-error

**Comment by pj-mathematician** [comment]
https://i.stack.imgur.com/Rwp4l.png
Still doesn't work, i have to click outside the text field to have it working.

**Comment by HeaTTheatR** [comment]
@pj-mathematician 
![Снимок экрана 2020-05-14 в 08 29 25](https://user-images.githubusercontent.com/16930280/81896326-1280a600-95bd-11ea-85e0-b059b8b3dbce.png)

**Comment by pj-mathematician** [comment]
I do not understand what you are trying to say

**Comment by wasimafser** [comment]
Create a new issue stating that you want a live check feature instead of on_focus implementation of text field.
