### ISSUE TITLE
Sometimes MDDropdown Menus don't get positioned correctly

### ISSUE THREAD

**Issue by pepsakdoek** [kivymd/KivyMD#305]
### Description of the Bug

Sometimes if you open a MDDropdownmenu very early on after running the app, it will create the dropdown in the wrong position.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu, RightContent
from kivy.properties import ObjectProperty


KV = '''
<RightContentCls>
	disabled: True

	MDIconButton:
		icon: root.icon
		user_font_size: "16sp"
		pos_hint: {"center_y": .5}

	MDLabel:
		text: root.text
		font_style: "Caption"
		size_hint_x: None
		width: self.texture_size[0]
		text_size: None, None

Screen
	GridLayout:
		cols:1
		padding:10

		GridLayout:
			adaptive_height: True
			cols: 2
			pos_hint: {"top": 1}

			MDTextField:
				id: project
				hint_text: "Project"
				text : " "
				icon_right: "arrow-down-drop-circle-outline"
				on_focus: if self.focus: app.callprojectmenu()

			MDTextField:
				id: room
				hint_text: "Room"
				text : " "
				icon_right: "arrow-down-drop-circle-outline"
				on_focus: if self.focus: app.callroommenu()


'''


class RightContentCls(RightContent):
	pass

class Test(MDApp):
	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.screen = Builder.load_string(KV)

		projectgroupitems = [{"text":"Project 1"},{"text":"Project 2"}]
		self.projectgroupmenu = MDDropdownMenu(
			caller=self.screen.ids.project,
			items=projectgroupitems,
			position="bottom",
			callback=self.setproject,
			width_mult=4
		)
		roomitems = [{"text": "Room 1"}, {"text": "Room 2"}]
		self.roommenu = MDDropdownMenu(
			caller=self.screen.ids.room,
			items=roomitems,
			position="bottom",
			callback=self.setroom,
			width_mult=4
		)

	def callprojectmenu(self):
		self.projectgroupmenu.open()

	def callroommenu(self):
		self.roommenu.open()

	def setroom(self,instance):
		self.screen.ids.room.text = instance.text

	def setproject(self,instance):
		self.screen.ids.project.text = instance.text

	def build(self):
		return self.screen


Test().run()
```
### Screenshots

https://youtu.be/zkEUEAJr6UM

### Versions

* OS: Windows 10
* Python: 3.7.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by bitbytenybble** [comment]
I've also faced the same issue. When I've used it, the dropdown menu usually ends up in the wrong position after a window resize.

**Comment by kaminetzky** [comment]
I'm having the same issue. Did you find out how to fix it?

If I switch to a second screen and open a menu, it opens on the bottom left corner of the window. If I resize the window before opening the menu, it shows up on the correct position. I can post my code later if it's useful.

Cheers!

**Comment by kaminetzky** [comment]
After a quick glance at the `kivymd/uix/menu.py` file, I realized that calling `menu.set_menu_properties(interval)` before opening the menu fixes the issue. However, I'm not sure if it will raise other issues. I'll look into it in detail tomorrow.

**Comment by kaminetzky** [comment]
Okay, here's what's going on.

When `MDDropdownMenu` is instantiated, `set_menu_properties` is called, calculating `_start_coords` as follows:

```python
self._start_coords = self.caller.to_window(self.caller.center_x, self.caller.center_y)
```

In some cases, `caller.center_x` and `caller.center_y` are not the values we're expecting them to be, because the caller's position has not loaded yet or other reasons. When this happens, the `MDDropdownMenu` is be placed incorrectly.

In order to fix this, `self._start_coords` should be updated whenever `self.caller.center_x` or  `self.caller.center_y` change. `center_x` and `center_y` depend on the numeric properties `x` and `y` of a widget, so we can bind them to a function.

Currently, `set_menu_properties` is called whenever the main window is resized, so I decided to try something similar. I added the following code to the `__init__` of `MDDropdownMenu`:

```python
self.caller.bind(
    x=lambda *_: Clock.schedule_once(self.set_menu_properties, 0.5),
    y=lambda *_: Clock.schedule_once(self.set_menu_properties, 0.5))
```

Now, whenever the `x` or `y` values of the caller change, the `set_menu_properties` will be called and the `_start_coords` of the menu will be set to the correct value. In my case, `to_window` returns incorrect values when `set_menu_properties` is called instantly after `x` or `y` change, probably because the widget tree is still updating. Adding a small delay before calling `set_menu_properties` fixed this.

I tested this fix on my code and it worked wonderfully. I can upload a minimal working example showing the differences if it's of use. Moreover, I tried this on @pepsakdoek's code and apparently it's working, too. It would be fantastic if @dillon-pinto could try it.

I hope my fix helps people having this issue! I can submit it as a pull request if it's working properly for everybody. 😄

**Comment by bitbytenybble** [comment]
Thanks for looking into it @akaminetzkyp! It partially fixed the bug in my drop-down menus, I have 2 buttons aligned vertically and the fix works only on the right button's drop-down. I've written up a file that can reproduce the issue, the left button's drop-down menu still ends up in the wrong place after a window resize. Let me know if you're able to reproduce it. Thanks again! 



```python
from kivy.lang import Builder
from kivymd.uix.screen import Screen
from kivymd.app import MDApp
from kivy.uix.scrollview import ScrollView
from kivymd.uix.gridlayout import MDGridLayout
from kivymd.uix.button import MDRectangleFlatButton
from kivymd.uix.textfield import MDTextField
from kivymd.uix.boxlayout import BoxLayout
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.dropdownitem import MDDropDownItem



class SomeScreen(Screen):
	def __init__(self, **kwargs):
		super(SomeScreen, self).__init__(**kwargs)

		self.grid = MDGridLayout(
			cols=1, 
			padding=150, 
			spacing=50,
			size_hint=(1, None), 
			width=900
		)

		self.grid.bind(
			minimum_height=self.grid.setter('height')
		)
			
		self.ScrollviewLayout = ScrollView(
			bar_width = 10,
			size_hint=(1, 0.95), 
			size=(900, 620),
			pos_hint={'center_x': .5, 'center_y': .4}, 
			do_scroll_x=False
		)

		self.createMenuButtons()
		self.ScrollviewLayout.add_widget(self.grid)
		self.add_widget(self.ScrollviewLayout)



	def createMenuButtons(self):

		self.button1 =MDRectangleFlatButton()
		self.button1.text = "Button1"
		self.button1.font_size = 15
		self.button1.size=(480, 50)
		self.button1.size_hint=(1, None)
		self.button1.halign='center'
		self.button1.valign='middle'
		

		self.button2 =MDRectangleFlatButton()
		self.button2.text = "Button2"
		self.button2.font_size = 15
		self.button2.size=(480, 50)
		self.button2.size_hint=(1, None)
		self.button2.halign='center'
		self.button2.valign='middle'


		items1 = [{"icon": "git", "text":  f"{thing}"} for thing in ["Stuff", "More Stuff"]]
		menu1 = MDDropdownMenu(
            caller=self.button1, items=items1, 
			width_mult=4,
		)

		items2 = [{"icon": "git", "text": f"{thing}"} for thing in ["Stuff", "More Stuff"]]
		menu2 = MDDropdownMenu(
            caller=self.button2,items=items2,
			width_mult=4,
		)


		self.button1.on_press = menu1.open
		self.button2.on_press = menu2.open

		bl = BoxLayout()
		bl.spacing = 10

		bl.add_widget(self.button1)
		bl.add_widget(self.button2)
		self.grid.add_widget(bl)


class TestApp(MDApp):
    def build(self):
        return SomeScreen()


TestApp().run()
```

**Comment by jaredliw** [comment]
I am facing this problem right now. The code @akaminetzkyp provided works perfectly for me. 

Is this issue still being updated?
![img](https://user-images.githubusercontent.com/57293776/83773772-8b07ed80-a6b7-11ea-9cdd-c16d39a83186.png)
![img](https://user-images.githubusercontent.com/57293776/83773843-9fe48100-a6b7-11ea-9d8e-8cc6111daae6.png)

**Comment by kaminetzky** [comment]
Thanks for checking if the fix works! In my code it's not working all the time, so there's still work to be done.

I'll be pretty busy for a while but I'll try to check this issue again as soon as possible. 😃

**Comment by bitbytenybble** [comment]
No worries! I'll take a look into it too and post updates if I'm able to find a fix.

**Comment by bitbytenybble** [comment]
I've been testing how the bug reacts to sizing. I noticed that, in my case, it happens on window snapping to the edges or corner of the screen. Window snapping doesn't fire the on_resize event handler for the window and holds on to the coordinates before the window snap/resize took place. 

So the only way I've found to force the dialog to update the coordinates is by calling `set_menu_properties` on the first line of `MDDropdownMenu`'s inner open function:

```python
    def open(self):
        """Animate the opening of a menu window."""

        def open(interval):
            self.set_menu_properties(0)

            if not self._calculate_complete:
                return
```

However, I think this might make some of the binding redundant, including the `check_position_caller` function. I tested this on Windows so I'm not sure if this is a problem on MacOS or Linux.

**Comment by kaminetzky** [comment]
That's a fantastic idea! I included it in my code and it looks like it's working properly now.

It would be ideal if we could find a fix that doesn't call `set_menu_properties` when it's not necessary. However, it looks like your solution is working. Thank you! 🎉

**Comment by BaggioMarco** [comment]
Hi,

could please share an example of how to integrate your following code:

```
    def open(self):
        """Animate the opening of a menu window."""

        def open(interval):
            self.set_menu_properties(0)

            if not self._calculate_complete:
                return
```

in the code below?


```
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = """
#:import toast kivymd.toast.toast


Screen:

    MDToolbar:
        pos_hint: {"top": 1}
        title: "MDDropDownItem"

    MDDropDownItem:
        id: dropdown_item
        text: "Item 0"
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        dropdown_bg: [1, 1, 1, 1]
        on_release: app.menu.open()

    MDRaisedButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        text: 'Chek Item'
        on_release: toast(dropdown_item.current_item)
"""


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"icon": "git", "text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.dropdown_item,
            items=menu_items,
            position="center",
            callback=self.set_item,
            width_mult=4,
        )

    def set_item(self, instance):
        self.screen.ids.dropdown_item.set_item(instance.text)

    def build(self):
        return self.screen


Test().run()
```

Even if the position of the menu in the above example works fine without your code, it would help to understand how to integrate it in other cases where the issue of the menu wrong position happens. Thank you in advance, some tips will be really helpful
