### ISSUE TITLE
Facing back directory issue in case of android.

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#306]
I have been working with android app long ago and recently I have implemented file manager in my desktop and android app both and using KivyMD(0.104.1) in my app so in case of a desktop it is working fine but when I am implementing it in my android device so I am providing my android storage path in it like given below.
![image](https://user-images.githubusercontent.com/33522186/82123358-9f428400-97b6-11ea-987c-a24cf72bb887.png)
So after providing this path, my file manager will look like
![Screenshot_20200516-204222](https://user-images.githubusercontent.com/33522186/82123419-eb8dc400-97b6-11ea-8774-9210005737d4.png)
so cross button is working fine but when we click on the back directory button then the first time it is working fine but when I am clicking it again it is crashing the app.
![Screenshot_20200516-205218](https://user-images.githubusercontent.com/33522186/82123466-3ad3f480-97b7-11ea-9c73-2b6656b5df5a.png)
and the error will look like
![image](https://user-images.githubusercontent.com/33522186/82123660-29d7b300-97b8-11ea-8c31-984a1a6b4485.png)
so can you implement any exception handling in the backend for managing android cases
or if you people have any solution for it which can help me to fix the issue from my end so please help me to fix it.

**Comment by HeaTTheatR** [comment]
@navjotcis Unfortunately, there are no people yet and there is no time to solve all the errors ... I am working in another project, so for about a month I will not be able to fix these errors ...

**Comment by HeaTTheatR** [comment]
Fix in master branch.
