### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'kivy.properties.BoundedNumericProperty'

### ISSUE THREAD

**Issue by garantor** [kivymd/KivyMD#310]
Got the below error when trying to compile kivy/kivymd app

--------- beginning of crash
--------- beginning of system
--------- beginning of main
05-18 21:26:46.346 26514 26596 I python  : Initializing Python for Android
05-18 21:26:46.346 26514 26596 I python  : Setting additional env vars from p4a_env_vars.txt
05-18 21:26:46.362 26514 26596 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
05-18 21:26:46.362 26514 26596 I python  : /data/user/0/org.test.sendit/files/app
05-18 21:26:46.368 26514 26596 I python  : Preparing to initialize python
05-18 21:26:46.368 26514 26596 I python  : _python_bundle dir exists
05-18 21:26:46.368 26514 26596 I python  : calculated paths to be...
05-18 21:26:46.368 26514 26596 I python  : /data/user/0/org.test.sendit/files/app/_python_bundle/stdlib.zip:/data/user/0/org.test.sendit/files/app/_python_bundle/modules
05-18 21:26:46.383 26514 26596 I python  : set wchar paths...
05-18 21:26:46.566 26514 26596 I python  : Initialized python
05-18 21:26:46.567 26514 26596 I python  : AND: Init threads
05-18 21:26:46.607 26514 26596 I python  : testing python print redirection
05-18 21:26:46.609 26514 26596 I python  : Android path ['.', '/data/user/0/org.test.sendit/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.test.sendit/files/app/_python_bundle/modules', '/data/user/0/org.test.sendit/files/app/_python_bundle/site-packages']
05-18 21:26:46.609 26514 26596 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/framework-oahl-backward-compatibility.jar:/system/framework/android.test.base.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/os-framework.jar:/system/framework/transsion-framework.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-telecom-common.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar', 'ANDROID_SOCKET_zygote_secondary': '11', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.test.sendit/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.test.sendit/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.test.sendit/files', 'ANDROID_UNPACK': '/data/user/0/org.test.sendit/files/app', 'PYTHONHOME': '/data/user/0/org.test.sendit/files/app', 'PYTHONPATH': '/data/user/0/org.test.sendit/files/app:/data/user/0/org.test.sendit/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
05-18 21:26:46.609 26514 26596 I python  : Android kivy bootstrap done. __name__ is __main__
05-18 21:26:46.609 26514 26596 I python  : AND: Ran string
05-18 21:26:46.609 26514 26596 I python  : Run user program, change dir and execute entrypoint
05-18 21:26:46.946 26514 26596 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
05-18 21:26:46.947 26514 26596 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
05-18 21:26:46.989 26514 26596 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.sendit/files/app/.kivy/logs/kivy_20-05-18_0.txt
05-18 21:26:46.990 26514 26596 I python  : [INFO   ] [Kivy        ] v1.11.1
05-18 21:26:46.991 26514 26596 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.sendit/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
05-18 21:26:46.993 26514 26596 I python  : [INFO   ] [Python      ] v3.8.1 (default, May 18 2020, 18:00:22) 
05-18 21:26:46.993 26514 26596 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
05-18 21:26:46.994 26514 26596 I python  : [INFO   ] [Python      ] Interpreter at ""
05-18 21:26:46.997 26514 26596 I python  : [INFO   ] [KivyMD      ] v0.104.1
05-18 21:26:47.012 26514 26596 I python  : [INFO   ] [Factory     ] 184 symbols loaded
05-18 21:26:49.807 26514 26596 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
05-18 21:26:49.959 26514 26596 I python  : [INFO   ] [Window      ] Provider: sdl2
05-18 21:26:50.064 26514 26596 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
05-18 21:26:50.067 26514 26596 I python  : [INFO   ] [GL          ] Backend used <sdl2>
05-18 21:26:50.068 26514 26596 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 build 1.10@5130912'>
05-18 21:26:50.069 26514 26596 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Imagination Technologies'>
05-18 21:26:50.070 26514 26596 I python  : [INFO   ] [GL          ] OpenGL renderer <b'PowerVR Rogue GE8320'>
05-18 21:26:50.071 26514 26596 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
05-18 21:26:50.072 26514 26596 I python  : [INFO   ] [GL          ] Texture max size <4096>
05-18 21:26:50.073 26514 26596 I python  : [INFO   ] [GL          ] Texture max units <16>
05-18 21:26:50.152 26514 26596 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
05-18 21:26:50.154 26514 26596 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
05-18 21:26:50.174 26514 26596 I python  : [INFO   ] [Text        ] Provider: sdl2
05-18 21:26:50.400 26514 26596 I python  : [INFO   ] [GL          ] NPOT texture support is available
05-18 21:26:54.645 26514 26596 I python  : [INFO   ] [Clipboard   ] Provider: android
05-18 21:26:58.614 26514 26596 I python  : [WARNING] [GL          ] Unpack subimage support is not available
05-18 21:26:59.011 26514 26596 I python  :  Traceback (most recent call last):
05-18 21:26:59.011 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 921, in _build_canvas
05-18 21:26:59.012 26514 26596 I python  :    File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
05-18 21:26:59.013 26514 26596 I python  :  TypeError: float() argument must be a string or a number, not 'kivy.properties.BoundedNumericProperty'
05-18 21:26:59.013 26514 26596 I python  :  
05-18 21:26:59.013 26514 26596 I python  :  During handling of the above exception, another exception occurred:
05-18 21:26:59.013 26514 26596 I python  :  
05-18 21:26:59.014 26514 26596 I python  :  Traceback (most recent call last):
05-18 21:26:59.014 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/app/main.py", line 37, in <module>
05-18 21:26:59.015 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/app.py", line 829, in run
05-18 21:26:59.016 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/app/main.py", line 33, in build
05-18 21:26:59.017 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/app/mainFile/cointainer.py", line 73, in __init__
05-18 21:26:59.018 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/floatlayout.py", line 65, in __init__
05-18 21:26:59.018 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/layout.py", line 76, in __init__
05-18 21:26:59.019 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/widget.py", line 359, in __init__
05-18 21:26:59.020 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/widget.py", line 467, in apply_class_lang_rules
05-18 21:26:59.020 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 536, in apply
05-18 21:26:59.021 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 658, in _apply_rule
05-18 21:26:59.021 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 656, in _apply_rule
05-18 21:26:59.022 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/widget.py", line 467, in apply_class_lang_rules
05-18 21:26:59.022 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 536, in apply
05-18 21:26:59.023 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 658, in _apply_rule
05-18 21:26:59.024 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 658, in _apply_rule
05-18 21:26:59.024 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 656, in _apply_rule
05-18 21:26:59.025 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/uix/widget.py", line 467, in apply_class_lang_rules
05-18 21:26:59.025 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 536, in apply
05-18 21:26:59.026 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 595, in _apply_rule
05-18 21:26:59.026 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 924, in _build_canvas
05-18 21:26:59.027 26514 26596 I python  :  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 5:
05-18 21:26:59.027 26514 26596 I python  :  ...
05-18 21:26:59.027 26514 26596 I python  :        3:    canvas:
05-18 21:26:59.028 26514 26596 I python  :        4:        Color:
05-18 21:26:59.028 26514 26596 I python  :  >>    5:            rgba: self.md_bg_color
05-18 21:26:59.028 26514 26596 I python  :        6:        RoundedRectangle:
05-18 21:26:59.028 26514 26596 I python  :        7:            size: self.size
05-18 21:26:59.029 26514 26596 I python  :  ...
05-18 21:26:59.029 26514 26596 I python  :  TypeError: float() argument must be a string or a number, not 'kivy.properties.BoundedNumericProperty'
05-18 21:26:59.029 26514 26596 I python  :    File "/home/afolabi/sendit/src/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/SendIt/kivy/lang/builder.py", line 921, in _build_canvas
05-18 21:26:59.029 26514 26596 I python  :    File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
05-18 21:26:59.030 26514 26596 I python  :  
05-18 21:26:59.030 26514 26596 I python  : Python for android ended.
^CException ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
The author did not provide additional information.
