### ISSUE TITLE
The icon does not appear on the MDDropdownMenu component

### ISSUE THREAD

**Issue by aprilahijriyan** [kivymd/KivyMD#316]
### Description of the Bug

I run the example https://kivymd.readthedocs.io/en/0.104.1/components/menu/index.html but the icon does not appear :(

### Screenshots

![2020-05-20 07 37 04](https://user-images.githubusercontent.com/37798612/82391899-bb6f4b00-9a6c-11ea-9168-3613414ddc24.jpg)

### Versions

* OS: Ubuntu
* Python: 3.x
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
This behavior does not repeat on my computer!

**Comment by HeaTTheatR** [comment]
@aprilahijriyan Try running this example and see if the icons are displayed - https://kivymd.readthedocs.io/en/0.104.1/themes/icon-definitions/index.html#to-preview-the-icons-and-their-names-you-can-use-the-following-application

**Comment by aprilahijriyan** [comment]
> @aprilahijriyan Try running this example and see if the icons are displayed - https://kivymd.readthedocs.io/en/0.104.1/themes/icon-definitions/index.html#to-preview-the-icons-and-their-names-you-can-use-the-following-application

I run the kitchen_sink example program and see that almost all icons work perfectly.

But, when I run the MDDropdownMenu component example, the icon doesn't appear.

![IMG20200520194535](https://user-images.githubusercontent.com/37798612/82448008-4daa3a00-9ad3-11ea-8680-0c2d5e44f195.jpg)

**Comment by aprilahijriyan** [comment]
@HeaTTheatR ?!

**Comment by aprilahijriyan** [comment]
![JPEG_20200521_230340](https://user-images.githubusercontent.com/37798612/82579204-aa7f2080-9bb7-11ea-8d38-988e2c859dab.jpg)

Oops sorry, this is my mistake, I just need to reinstall kivymd, and finally it works!

Sorry btw
