### ISSUE TITLE
Buttons don't work in custom MDDialog

### ISSUE THREAD

**Issue by agisbrec** [kivymd/KivyMD#321]
### Description of the Bug

The Buttons in the example for custom dialog don't work.
This is because it is not possible to define
height: "120dp"
in the KV-file. A workaround is to replace it with an integer.

This gets borked in dialog.py
```
        if self.type == "custom":
            if self.content_cls:
                self.ids.container.remove_widget(self.ids.scroll)
                self.ids.container.remove_widget(self.ids.text)
                self.ids.spacer_top_box.add_widget(self.content_cls)
                self._spacer_top = self.content_cls.height + dp(24)   # <<<<------ here
                self.ids.spacer_top_box.padding = (0, "24dp", "16dp", 0)
```

### Code and Logs

```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.dialog import MDDialog

KV = '''
<Content>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    MDTextField:
        hint_text: "City"

    MDTextField:
        hint_text: "Street"


FloatLayout:

    MDFlatButton:
        text: "ALERT DIALOG"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_confirmation_dialog()
'''


class Content(BoxLayout):
    pass


class Example(MDApp):
    dialog = None

    def build(self):
        return Builder.load_string(KV)

    def show_confirmation_dialog(self):
        if not self.dialog:
            self.dialog = MDDialog(
                title="Address:",
                type="custom",
                content_cls=Content(),
                buttons=[
                    MDFlatButton(
                        text="CANCEL", text_color=self.theme_cls.primary_color, on_release=self.callback
                    ),
                    MDFlatButton(
                        text="OK", text_color=self.theme_cls.primary_color
                    ),
                ],
            )
        self.dialog.open()

    def callback(self, *args):
        print('it works!')

Example().run()
```

### Versions

* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/issues/284

**Comment by agisbrec** [comment]
This is not the same bug.

**Comment by HeaTTheatR** [comment]
@agisbrec This is the same bug.

**Comment by agisbrec** [comment]
This has nothing to do with "auto_dismiss=False".
This bug is due to
`self._spacer_top = self.content_cls.height + dp(24) `
I.e.:
"120dp" + dp(24)
Is not properly defined

**Comment by HeaTTheatR** [comment]
@agisbrec The question is closed!

**Comment by agisbrec** [comment]
For anyone googling this problem, you can work around it
by defining height with a an integer e.g.
`height: 120`
instead of
`height: "120dp"`

**Comment by HeaTTheatR** [comment]
@agisbrec There is no error description in your question. The code you attached works flawlessly. So I closed the question. If you want to receive an answer, you must describe the error and attach a code that reproduces this error.

**Comment by agisbrec** [comment]
It does not produce an error. It does not print "it works!" on pressing cancel.
Upon further investigation, it can be indeed fixed with "auto_dismiss=False",
but this adds an unwanted behavior of disabling the dismiss feature by clicking outside the window.
The real problem seems to be that the boundaries of the window are not computed correctly.
Even if it does not produce an error, it is not working properly.

**Comment by HeaTTheatR** [comment]
@agisbrec As soon as you show me the error, then I will work to resolve it. At the moment, I do not observe errors!

![ezgif-4-975d69574fd9](https://user-images.githubusercontent.com/16930280/82594263-7a7e5000-9bac-11ea-96bf-06efb5044cea.gif)

**Comment by agisbrec** [comment]
![exmp](https://user-images.githubusercontent.com/13858650/82597401-30479f80-9ba9-11ea-8099-8d68178aeec4.gif)
![exmp_](https://user-images.githubusercontent.com/13858650/82597410-3473bd00-9ba9-11ea-9bd0-ee687908cbe5.gif)

**Comment by HeaTTheatR** [comment]
@agisbrec https://github.com/HeaTTheatR/KivyMD/issues/284

**Comment by agisbrec** [comment]
OK, so the issue is that MDDialog inherits from ModalView
and ModalView does not update its size when widgets are added to it,
or when children widgets change their size.
Therefore, the collide_point property of MDDialog does not correspond to the real size of MDDialog.
This can be fixed by updating the size of MDDialog at the end of initialisation.
```        total_height = 0
        sum_over = ['title',
                    'spacer_top_box',
                    'text',
                    'scroll',
                    'spacer_bottom_box',
                    'root_button_box',
                    ]
        for name, widget in self.ids.items():
            if hasattr(widget, 'height') and name in sum_over:
                total_height += widget.height

        total_height += self.ids.container.padding[1]
        total_height += self.ids.container.padding[-1]

        self.height = total_height```

**Comment by HeaTTheatR** [comment]
@agisbrec I don’t understand what you are talking about.

**Comment by agisbrec** [comment]
ModalView has these functions:
```
    def on_touch_down(self, touch):
        self._touch_started_inside = self.collide_point(*touch.pos)
        if not self.auto_dismiss or self._touch_started_inside:
            super(ModalView, self).on_touch_down(touch)
        return True

    def on_touch_up(self, touch):
        if self.auto_dismiss and not self._touch_started_inside:
            self.dismiss()
            return True
        super(ModalView, self).on_touch_up(touch)
        return True
```
When someone interacts with the dialog, it checks whether the touch was inside the dialog window, or outside. If it was outside, the dialog is dismissed.
The problem is, that the actual size of MDDialog does not correspond to the size of ModalView.
Therefore the dialog is dismissed even if the interaction was inside the window.

**Comment by HeaTTheatR** [comment]
@agisbrec Thank! Now I understand what you mean!
