### ISSUE TITLE
SandboxViolation

### ISSUE THREAD

**Issue by EvansPM** [kivymd/KivyMD#324]
### Description of the Bug

On KivyMD folder, after following command:
```python ./setup.py install```

I got:
```error: SandboxViolation: mkdir('C:\\Users\\EvansPM\\.kivy',) {}```

### Versions
* OS: Windows
* Python: 3.8
* Kivy: -2.0.0rc2
* KivyMD:  0.104.1

**Comment by HeaTTheatR** [comment]
@EvansPM 
1. The error is not related to the `KivyMD library`.
2. `Kivy` has not officially announced support for `Python 3.8` and `Kivy 2.0.0rc2`.
3. `KivyMD` library not tested on `Python 3.8`  and `Kivy 2.0.0rc2`.
