### ISSUE TITLE
Blank 32-bit icons

### ISSUE THREAD

**Issue by juanjavatus** [kivymd/KivyMD#327]
Opening MDicons in kitchen_sink demo, all icons with 32-bit code doesn't visualize correctly. They are all blank icons.
![KitchenSink-MDicons](https://user-images.githubusercontent.com/54139622/83033682-b3e50e80-a037-11ea-86b2-314aacf88300.png)

Ubuntu18
Python3.6
kivy1.11.1
kivymd 0.104.1

**Comment by HeaTTheatR** [comment]
Look at here - https://github.com/HeaTTheatR/KivyMD/issues/257

**Comment by juanjavatus** [comment]
Excuses for my ignorance, that seems to refer to a python-for-android issue and I'm running kivyMD on ubuntu before any compilation, do I need to follow the same process described?

**Comment by HeaTTheatR** [comment]
@juanjavatus Your problem cannot be reproduced on desktop!

**Comment by juanjavatus** [comment]
Well, I reproduced it in mine, I send an screenshot. Could be a problem of my os?

**Comment by HeaTTheatR** [comment]
@juanjavatus 
![Снимок экрана 2020-05-27 в 21 40 05](https://user-images.githubusercontent.com/16930280/83059500-abee9400-a062-11ea-97ba-cd7b1b52e516.png)

**Comment by juanjavatus** [comment]
I would like to have the same, what a luck! I don't know what could be my problem. In short, it is what it is. Thanks anyway.

**Comment by HeaTTheatR** [comment]
@juanjavatus I hope that soon we can figure out what is the reason

**Comment by juanjavatus** [comment]
thanks again, very nice of you

**Comment by ArtemSBulgakov** [comment]
Solution: https://github.com/HeaTTheatR/KivyMD/issues/257#issuecomment-665599554
