### ISSUE TITLE
Is it possible to have 2 datepickers on the same screen?

### ISSUE THREAD

**Issue by macattack086** [kivymd/KivyMD#33]
Is it possible to have 2 datepickers on the same screen? I need to be able to set an upper and lower date for a query to an api but because the datepicker is using self.previous date my two datepickers are linked up.

How do I have two datepickers that are working independently from each other?

Or can I have a single datepicker choose two dates?

Thanks for all your work!

**Comment by HeaTTheatR** [comment]
@macattack086 I do not see the problem! Everything is solved by one screen MDDatePicker!
