### ISSUE TITLE
MDTextField sizing and hints not triggering correctly

### ISSUE THREAD

**Issue by sanderland** [kivymd/KivyMD#331]
### Description of the Bug
MDTextField with mode: rectangle has some bugs with switching between the no text/some text modes. In particular, it seems to assume the text does not change when not in focus, whereas you can programatically set it as well (triggering on_text without on_focus)

In addition, it does not seem to respect it's parent width.
The example below is with `width: sibling.width - dp(26)` which compensates for this.

### Code
Will add an example later if needed, but essentially setting the .text property causes the issues.

### Screenshots
![mdtextbug](https://user-images.githubusercontent.com/48946947/83196249-dceec780-a13b-11ea-98bd-15db51c92173.gif)

### Versions

* OS: Windows 10
* Python: 3.7
* Kivy:  2.0.0rc2
* KivyMD:  0

.104.1

**Comment by sanderland** [comment]
Also seems to affect setting `self.error`

Example:
```
from kivy.clock import Clock
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.textfield import MDTextField


class MyMDTextField(MDTextField):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Clock.schedule_once(lambda dt: self.check_error(self.text), 0)

    def check_error(self, text):
        self.error = text != "correct"
        print("checking error for", text, "->", self.error)

    def on_text(self, widget, text):
        self.check_error(text)
        return super().on_text(widget, text)


KV = """
BoxLayout:
    padding: "10dp"

    MyMDTextField:
        id: text_field_error
        text: 'incorrect'
        hint_text: "Helper text on error (press 'Enter')"
        helper_text: "There will always be a mistake"
        helper_text_mode: "on_error"
        pos_hint: {"center_y": .5}
"""


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def build(self):
        return self.screen

Test().run()
```
This does not give an error on startup, only when focussing

**Comment by AM-ash-OR-AM-I** [comment]
@sanderland Did you figure out the solution? I'm having same issue with MDTextField set to rectangular mode.
![IMG_20210102_123807](https://user-images.githubusercontent.com/59698257/103452846-bdcf9e00-4cf9-11eb-8d33-ea6319e5357e.jpg)

**Comment by HeaTTheatR** [comment]
The issue is open, it has not been resolved yet

**Comment by sanderland** [comment]
@AM-ash-OR-AM-I  My workaround is to use a layout with no border (just canvas:before draw a line above the textbox), which makes it look ok.
![image](https://user-images.githubusercontent.com/48946947/103455314-52330400-4cec-11eb-94bc-237ac2de12eb.png)

**Comment by HeaTTheatR** [comment]
@AM-ash-OR-AM-I https://github.com/kivymd/KivyMD/compare/ab7527cd9d17...f46b6971d5c8
