### ISSUE TITLE
Change the Default Tab 

### ISSUE THREAD

**Issue by pooory** [kivymd/KivyMD#333]
### Description of the Feature

How i can change the default Tab of MDBottomNavigation ?
i made 3 Tabs MDBottomNavigation for my app and  first Tab from left is default Tab.
i want to remove this default Tab and change to  first Tab from right as default.
It means that when i run the app First Tab in right side is Home Tab.
please see below image.

### Screenshots
https://gofile.io/d/ewQsou

### Versions

* OS: windows
* Python: 3.7
* Kivy: 
* KivyMD: 1.11.1

**Comment by HeaTTheatR** [comment]
@pooory Adding more information to your question.

**Comment by allasca** [comment]
@pooory run me, look at def on start.
for near future, dont ask kind this question on github, you can ask it on kivyMD discord

```python
from kivymd.app import MDApp
from kivy.lang import Builder

KV = '''
ScreenManager:
    Screen:
        MDBottomNavigation:
            id: nav
            MDBottomNavigationItem:
                name: "tab 1"
                text: "tab 1"
            MDBottomNavigationItem:
                name: "tab 2"
                text: "tab 2"
            MDBottomNavigationItem:
                name: "tab3"
                text: "tab 3"
'''

class MyApp(MDApp):
    def on_start(self):
        self.root.ids.nav.switch_tab("tab3")

    def build(self):
        return Builder.load_string(KV)

MyApp().run()
```

**Comment by pooory** [comment]
Sure.Thank you allasca
