### ISSUE TITLE
Is iOS platform supported?

### ISSUE THREAD

**Issue by mnba** [kivymd/KivyMD#335]
### Please provide information on iOS platform support level,
at least short info.

Thanks!

**Comment by HeaTTheatR** [comment]
@mnba The question is not related to the KivyMD library. Contact support here - https://github.com/kivy/kivy/issues/new/choose

**Comment by mnba** [comment]
Kivy site mentions that iOS is supported, does that automatically means that KivyMD has iOS support? You have many Android mentions on here, but there is no any mentions of iOS platform, that is why I was asking

**Comment by HeaTTheatR** [comment]
@mnba KivyMD == Kivy
