### ISSUE TITLE
How to close a MDDialog Box in latest version of MD

### ISSUE THREAD

**Issue by prachiy** [kivymd/KivyMD#339]
I am creating a mddialog box in my project but i am not able to close that popup on the click of Cancel button even i had tried the dismiss method on it ,that method also wont work on that button , so please      
give  me some suggestions for closing the mddialog box.

**Comment by st-den** [comment]
Add `on_release` attribute to your "cancel" button. It takes a pointer to the function, which should call `dismiss()` on your dialog. Or you can use a lambda like that:

```
...
def show_dialog(self, instance):
    if not self.dialog:
        self.dialog = MDDialog(
            buttons=[
                MDFlatButton(
                    on_release=lambda _: self.dialog.dismiss()
                )
            ],
        )
    self.dialog.open()
```

**Comment by prachiy** [comment]
Okay and i want to add this dismiss method on a callback function ,like when a popup opens then after clicking on yes button then that popup will get auto dismiss.

**Comment by MrJaatt** [comment]
In 2024 facing the same issue.


`def show_invalid_id_dialog(self):
    print("Show_invalid_id.... -  runned")
    if not self.dialog:
        print("Show_invalid_id.... - if -runned")
        self.dialog = MDDialog(
        MDDialogHeadlineText(
            text="Wrong User Name",
            halign="left",
        ),
        MDDialogSupportingText(
            text="You need to enter correct username. If you forgot then contact Meerut Farm using whatsapp. Please do not call",
            halign="left",),
        MDDialogButtonContainer(
            Widget(),
            MDButton(
                MDButtonText(text="ok"),
                style="text",
                on_release= self.close_dialog),
            spacing="8dp",
        ),
    ).open()

def close_dialog(self, *args):
    self.dialog.dismiss()`







`   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 413, in on_touch_up
     return super().on_touch_up(touch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/vic/MFL/A_app/myenv/lib/python3.12/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "/home/vic/MFL/C_app/main.py", line 249, in close_dialog
     self.dialog.dismiss()
     ^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'dismiss'`
