### ISSUE TITLE
Add example List with Icon and Checkbox to Wiki

### ISSUE THREAD

**Issue by macattack086** [kivymd/KivyMD#34]
Could you add an example to the Wiki for Lists? Specifically the one that you have in the sample app where you have a logo, text and checkbox.

I want to have a list of items and have check boxes, I want to select the ones I want and then hit a button on the page outside of the List itself that then does work with the list of data but I'm not sure how to do it. 

Thank you for all your work and quick responses!

**Comment by HeaTTheatR** [comment]
@macattack086 https://github.com/HeaTTheatR/KivyMD/wiki/List-item-with-Checkbox
