### ISSUE TITLE
MDTabs on_tab_switch is not called on a tab switch by swipe

### ISSUE THREAD

**Issue by st-den** [kivymd/KivyMD#341]
### Description of the Bug

The most intuitive way to change a tab is a swipe. Currently, `on_tab_switch function` is called only when one taps on a tab label. The other option is `on_carousel_index`, which a) doesn't work (#340) and b) contains no convenient way to work with MDTabsBase-like widgets.

So, there is no, at least obvious to me, way to add/remove widgets from tab screens, thus no way to implement pagination for tabs. My app loads circa 15 seconds, adding 40 lightweight list widgets total to 5 tabs.

### Code

```python
from kivymd.app import MDApp
from kivy.app import Builder
from sys import exit as sys_exit

kv = """
<Tab@FloatLayout+MDTabsBase>
    text: "circle"

BoxLayout
    MDTabs
        on_tab_switch: app.on_tab_switch(*args)
        Tab
        Tab
"""


class App(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def on_tab_switch(self, *args):
        sys_exit()


App().run()

```

### Versions

* OS: Win10 1909
* Python: 3.8.3
* Kivy: 2.0.0rc2
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@hematogender I do not understand the essence of the issue.

**Comment by st-den** [comment]
Users switch tabs mostly by swiping, not by clicking on tab labels at the top of the screen.

The name of the function is `on_tab_switch`. It is not called when tab changes by swipe, it is only called when you click on a label.

I want to implement pagination in my app, thus I need a way to know when the tab is switched to another. Neither `on_tab_switch` nor `on_carousel_index` is suitable to do it.

**Comment by HeaTTheatR** [comment]
The behavior that is described in this issue has not been confirmed during testing.

**Comment by BananaMasterz** [comment]
I'm having the same issue. I changed the code to print instead of closing so it's easier to see:

```
from kivymd.app import MDApp
from kivy.app import Builder
from sys import exit as sys_exit

kv = """
<Tab@FloatLayout+MDTabsBase>
    text: "circle"

BoxLayout
    MDTabs
        on_tab_switch: app.on_tab_switch(*args)
        Tab
        Tab
"""


class App(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def on_tab_switch(self, *args):
        print('hello')


App().run()
```

if you click the tab it switches and prints hello to the console. If you swipe with the mouse, it switches tabs but does not print hello. Thus, the on_tab_switch works only with click and not with swipe.
