### ISSUE TITLE
OSError: File ./kivymd/fonts/Roboto-Regular.ttf not found

### ISSUE THREAD

**Issue by harshinivarma** [kivymd/KivyMD#344]
### Description of the Bug
application form build with buildozer, it is successsfully installed in my phonebut when i open the app in my phone it is showing an error (error for ready reference below)

### Code and Logs
Traceback (most recent call last):
06-04 13:31:33.802 25877 25899 I python  :    File "/home/spiniz/Survey/.buildozer/android/app/main.py", line 4, in <module>
06-04 13:31:33.803 25877 25899 I python  :    File "/home/spiniz/Survey/.buildozer/android/app/kivymd/app.py", line 47, in <module>
06-04 13:31:33.803 25877 25899 I python  :    File "/home/spiniz/Survey/.buildozer/android/app/kivymd/theming.py", line 42, in <module>
06-04 13:31:33.804 25877 25899 I python  :    File "/home/spiniz/Survey/.buildozer/android/app/kivymd/font_definitions.py", line 49, in <module>
06-04 13:31:33.804 25877 25899 I python  :    File "/home/spiniz/Survey/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/text/__init__.py", line 315, in register
06-04 13:31:33.804 25877 25899 I python  :  OSError: File ./kivymd/fonts/Roboto-Regular.ttf not found
06-04 13:31:33.804 25877 25899 I python  : Python for android ended.
```python

import kivymd
from kivy.app import App
from kivymd.app import MDApp
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.theming import ThemeManager
from kivy.lang import Builder
import requests
import json
from myfirebase import MyFirebase
from kivy.uix.boxlayout import BoxLayout
from myfirebase import MyFirebase
from kivy.clock import Clock

    
class MainApp(MDApp):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_file('main.kv')
        self.my_firebase = MyFirebase()
    


MainApp().run()


### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here


### Versions

* OS: windows 10
* Python:  python 3.8
* Kivy: 
* KivyMD:

**Comment by wasimafser** [comment]
you're Sp!n!zA ???
