### ISSUE TITLE
MDRaisedButton md_bg_color attribute won't work as expected

### ISSUE THREAD

**Issue by mozesa** [kivymd/KivyMD#345]
### Description of the Bug

You cannot instantiate a new `MDRaisedButton` in python with altered color even though `md_bg_color` parameter is provided with a new color.

### **NOK** as parameter
```python
from kivy.uix.screenmanager import Screen
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton


class App(MDApp):
    def build(self) -> None:
        screen = Screen()
        raised_button = MDRaisedButton(
            text="Hello",
            md_bg_color=[1, 0, 0, 1],
            pos_hint={"center_x": 0.5, "center_y": 0.5},
        )
        screen.add_widget(raised_button)
        self.root = screen


app = App()
app.run()
```
![image](https://user-images.githubusercontent.com/49973426/83768034-9ab71000-a67e-11ea-91e8-15677a05d7da.png)

---

### **OK** as attribute set
```python
from kivy.uix.screenmanager import Screen
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton


class App(MDApp):
    def build(self) -> None:
        screen = Screen()
        raised_button = MDRaisedButton(
            text="Hello", pos_hint={"center_x": 0.5, "center_y": 0.5},
        )
        raised_button.md_bg_color = [1, 0, 0, 1]
        screen.add_widget(raised_button)
        self.root = screen


app = App()
app.run()
```
![image](https://user-images.githubusercontent.com/49973426/83767860-6a6f7180-a67e-11ea-8220-e6fe752715d6.png)

### Versions

* OS: Windows 10
* Python: 3.8.3
* Kivy: v2.0.0rc2
* KivyMD: v0.104.1 (master)

**Comment by HeaTTheatR** [comment]
@mozesa So far it will work that way.

**Comment by podraco** [comment]
Does this mean the widget doesn't check if there's already a set for md_bg_color before the instance?

**Comment by podraco** [comment]
i believe that this might solve a problem found in the test app of #447 that I think is derived from this strange behavior
