### ISSUE TITLE
MDBottomNavigation miss-arrangement

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#346]
### Description of the Bug

each time i use MDBottomNavigation widget within a Screen it stacks it self to the right. If i expand the window a little bit, it goes back to normal and it does the same thing when i compile it into an apk.

Moreover, the ScreenManager is my root widget and the Screen widget is a child of ScreenManager

### Screenshots
<img src="https://i.ibb.co/JkDQGsj/bottom-nav-er.png" alt="bottom-nav-er" border="0">
here is the run of the code..

<img src="https://i.ibb.co/yS3Svgq/botom-code.png" alt="botom-code" border="0">
here is the code
Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Linux
* Python: 3.7
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@kengoon Duplicate - https://github.com/HeaTTheatR/KivyMD/issues/271
