### ISSUE TITLE
 MDFileManager how to get root path like "storage/emulated/0/"

### ISSUE THREAD

**Issue by DAMIAN-Adol** [kivymd/KivyMD#350]
### Description

I tried to read the internal storage of my phone with the following code but I cannot access it.

self.file_manager.show ('storage / emulated / 0')

how can I do this?

 Thanks in advance.

### My code

```python
from kivy.core.window import Window
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.filemanager import MDFileManager
from kivymd.toast import toast



KV = '''
BoxLayout:
    orientation: 'vertical'
    MDToolbar:
        title: "MDFileManager"
        left_action_items: [['menu', lambda x: None]]
        elevation: 10
    FloatLayout:
        MDRoundFlatIconButton:
            text: "Open manager"
            icon: "folder"
            pos_hint: {'center_x': .5, 'center_y': .6}
            on_release: app.file_manager_open()
'''
class Example(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Window.bind(on_keyboard=self.events)
        self.manager_open = False
        self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
            previous=True,
        )
    def build(self):
        return Builder.load_string(KV)
    def file_manager_open(self):
        self.file_manager.show('storage/emulated/0')  #<<<<<<<<<<<<<<<<HERE!!!!!!!!!!!!!!!!!
        self.manager_open = True
    def select_path(self, path):
        self.exit_manager()
        toast(path)

    def exit_manager(self, *args):
        self.manager_open = False
        self.file_manager.close()
    def events(self, instance, keyboard, keycode, text, modifiers):

        if keyboard in (1001, 27):
            if self.manager_open:
                self.file_manager.back()
        return True
Example().run()
```

### Versions

* OS: Ubuntu 18.04
* Python: 3.7.5
* Kivy: 1.10.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@DAMIAN-Adol Grant App Permissions

**Comment by kengoon** [comment]
@DAMIAN-Adol It is not "storage/emulated/0" but "/storage/emulated/0".  You are missing out "/" in front of "storage"

**Comment by DAMIAN-Adol** [comment]
@HeaTTheatR @kengoon  Thanks for answering ...I did all of the above but it didn't work.

Now I found a solution to it.

_I added to the header._
`from android.storage import primary_external_storage_path`
`primary_storage_dir = primary_external_storage_path()`


I changed the path  to `self.file_manager.show(primary_storage_dir)` ... it works perfectly.


the value of `primary_storage_dir` is `/storage/emulated/0`

thanks to[`storage_paths` from python for android](https://github.com/kivy/python-for-android/pull/1598/files)

**Comment by RobertFlatt** [comment]
But (I think) the Android features that enable implementation of this function are depreciated in Android 9, and removed in Android 10.

**Comment by DAMIAN-Adol** [comment]
@Ham-Merhead it works on android 10 i used it on mine 😀.
