### ISSUE TITLE
Open Browser App when a Button is Touched

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#351]
```from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.screen import Screen
from kivymd.uix.floatlayout import FloatLayout
import webbrowser


class DemoApp(MDApp):

	def build(self):
		screen = Screen()
		btn = MDFlatButton(text='Open Browser', pos_hint={'center_x': 0.5, 'center_y': 0.5},
		 on_release=self.open_browser)
		screen.add_widget(btn)
		return screen

	def open_browser(self, obj):
		webbrowser.open('www.google.co.in')

if __name__ == "__main__":
	DemoApp().run()```

**Comment by kulothunganug** [comment]
using the above code

**Comment by yari-iran** [comment]
from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton
from kivymd.uix.screen import Screen
from kivymd.uix.floatlayout import FloatLayout
import webbrowser


class DemoApp(MDApp):

   def build(self):
      screen = Screen()
      btn = MDFlatButton(text='Open Browser', pos_hint={'center_x':
0.5, 'center_y': 0.5},
       on_release=self.open_browser)
      screen.add_widget(btn)
      return screen

   def open_browser(self, obj):
      webbrowser.open('www.google.co.in')

if __name__ == "__main__":
   DemoApp().run()

**Comment by kulothunganug** [comment]
thx bro
