### ISSUE TITLE
Unicode issue kivyMD

### ISSUE THREAD

**Issue by yacine-re** [kivymd/KivyMD#352]
### Description of the Bug

i am using kivyMD to develop an app , the problem when i use text in Arabic or French language, it show symboles :/ After googling i find some solution for MDLabel widget by adding Font name

```
            MDLabel:
            text:str(root.bidi_text)
            font_name: './fonts/Shoroq-Font.ttf'
```

The problem for other widgets like MDlist, MDbutton , title of Toolbar, ..etc.. it doesn't work Any solution ?

![Capture](https://user-images.githubusercontent.com/66906337/84592294-d606cb00-ae44-11ea-8221-28820ffa3dfb.PNG)

### Versions

* OS: 
* Python: 3.6
* Kivy: 1.1
* KivyMD:

**Comment by HeaTTheatR** [comment]
https://medium.com/@ahmedfgad/supporting-arabic-alphabet-in-kivy-for-building-cross-platform-applications-7a1e7c14a068
