### ISSUE TITLE
Why does the app crash when using the KivyMD?

### ISSUE THREAD

**Issue by grabtrap** [kivymd/KivyMD#353]
```
Traceback (most recent call last):
File "/home/m/8/.buildozer/android/app/main.py", line 10, in <module>
File "/home/m/8/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivymd/uix/filemanager.py", line 119, in <module>
ModuleNotFoundError: No module named 'PIL'
Python for android ended.
```
buildozer.spec:
`requirments = python3, kivy, kivymd, yandex-geocoder, requests, mapview, geopy`
I do not use PIL, tried to add pillow / PIL in the requirements, but then the application is not going to

**Comment by HeaTTheatR** [comment]
@grabtrap 
KivyMD uses the PIL - https://github.com/HeaTTheatR/KivyMD#dependencies This dependency will be removed in the future. At the moment, specify the PIL package in the specification file to  dependency of your project. If you have problems installing the PIL package, contact the Kivy community for help.

**Comment by grabtrap** [comment]
@HeaTTheatR  How then are you building the application? What do you indicate in the requirements?
