### ISSUE TITLE
MDFloatingActionButtonSpeedDial not usable

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#354]
I can't use MdFloatingActionButtonSpeedDial, it keeps giving me "TypeError: 'float' object is not iterable. I even tried the one on kitchen sink it still gives the same error

**Comment by HeaTTheatR** [comment]
@kengoon We cannot give you any answer, because at the moment the MDFloatingActionButtonSpeedDial component works on both mobile and desktop systems. Show a minimal code example that get you an error.

**Comment by kengoon** [comment]
![minimal](https://user-images.githubusercontent.com/42192162/84666969-a675c280-af19-11ea-8776-4ec1acab1d6c.png)

**Comment by HeaTTheatR** [comment]
@kengoon No need to attach images with a code.

**Comment by kengoon** [comment]
@HeaTTheatR ok, 

i'm still getting used to markdown

**Comment by kengoon** [comment]
![image](https://user-images.githubusercontent.com/42192162/84668838-ffdef100-af1b-11ea-87e0-5dcc732c4f0a.png)


this is the error that is showing each time i run my code

**Comment by ArtemSBulgakov** [comment]
@kengoon It works for `0.104.1` and `master`. Try to reinstall KivyMD

**Comment by ArtemSBulgakov** [comment]
@kengoon Please also say your Kivy version

**Comment by kengoon** [comment]
kivy version is 1.11.1

**Comment by kengoon** [comment]
it is working fine now 
i actually did not install the kivymd package 
i just copied it directly to my to my project folder.
