### ISSUE TITLE
MDbottomnavigation items not correctly placed on phones

### ISSUE THREAD

**Issue by mateoaita** [kivymd/KivyMD#355]
Hello, i got an issue regarding MDbottomnavigation items. They are not placed in the center in every phone, i have to change the size of the screen and the problem is fixed, but on phones that is not possible, so te problem does not let me sleep haha, I would really appreciate if someone helps me

**Comment by HeaTTheatR** [comment]
@mateoaita There is no information in your question so that someone can help you. Attach the code that you use, show what specifically does not work.

**Comment by mateoaita** [comment]
Sorry! Here is the code and the problem:

<ScreenOne>:

    BoxLayout:
        id:Botones
        name:Botones
        orientation:'vertical'


        MDBottomNavigation:

            panel_color: .2, .2, .2, 1
            gcolor: .0, 0.1, .1, .8
            #pos_hint: {"center_x": 1, "center_y": 0.99}
            #size_hint:1,1


            MDBottomNavigationItem:
                id: play
                text: 'Play'
                icon: 'soccer'
                on_tab_press: root.jugar(Botones.name)

            MDBottomNavigationItem:
                text: "Team"
                icon: 'account-multiple'
                on_tab_press: root.manager.current='screen2'

            MDBottomNavigationItem:
                text: 'Table'
                id:posiciones
                icon: 'format-align-justify'
                on_tab_press: root.manager.current='posiciones'

            MDBottomNavigationItem:
                text: 'Results'
                id:posiciones
                icon: 'view-list'
                on_tab_press: root.manager.current='lastres'

            MDBottomNavigationItem:
                text: 'Slow'
                id:speed
                icon: 'play'
                on_tab_press: root.velocity()

The first pic is how it should be looking, the second one is what actually happens in most phones no matter what I do with the pos_hint and size_hint properties, I wrote the # to leave them as default.
![foto tact it](https://user-images.githubusercontent.com/48486276/84779064-4a16af80-afba-11ea-8551-5ecf464dc93e.png)
![foto tact it 2](https://user-images.githubusercontent.com/48486276/84779072-4c790980-afba-11ea-9251-4eac34e44cd3.png)

**Comment by HeaTTheatR** [comment]
@mateoaita https://github.com/HeaTTheatR/KivyMD/issues/271

**Comment by mateoaita** [comment]
Hey! thanks for the advice, I could solve that problem. The thing is now the app on my phone crashes after some time using it and I believe it is due to this command to reload the MDBottomNavigation and I don't know how to fix it.
Here's the code:
<ScreenOne>:
    on_enter: bot_nav._refresh_tabs() #this is what helped me fixed the positioning problem but the new suspect as well
    BoxLayout:
        id:Botones
        name:Botones
        orientation:'vertical'




        MDBottomNavigation:
            id:bot_nav
            panel_color: .2, .2, .2, 1
            gcolor: .0, 0.1, .1, .8
            #pos_hint: {"center_x": .5, "center_y": 0.99}
            size_hint:0.97,1
            on_kv_post:self.ids.tab_bar.spacing=1
            #inactive_font_size: sp(3)
            #active_font_size: self.inactive_font_size

            MDBottomNavigationItem:
                id: play
                text: 'Play'
                icon: 'soccer'
                on_tab_press: root.jugar(Botones.name)


            MDBottomNavigationItem:
                text: "Team"
                icon: 'account-multiple'
                on_tab_press: root.manager.current='screen2'

            MDBottomNavigationItem:
                text: 'Table'
                id:posiciones
                icon: 'format-align-justify'
                on_tab_press: root.manager.current='posiciones'

            MDBottomNavigationItem:
                text: 'Results'
                id:posiciones
                icon: 'view-list'
                on_tab_press: root.manager.current='lastres'

**Comment by mateoaita** [comment]
Hey! thanks for the advice, I could solve that problem. The thing is now the app on my phone crashes after some time using it and I believe it is due to this command to reload the MDBottomNavigation and I don't know how to fix it.
Here's the code:
<ScreenOne>:
    on_enter: bot_nav._refresh_tabs() #Solved positioning issue but it is the new suspect
    BoxLayout:
        id:Botones
        name:Botones
        orientation:'vertical'




        MDBottomNavigation:
            id:bot_nav
            panel_color: .2, .2, .2, 1
            gcolor: .0, 0.1, .1, .8
            #pos_hint: {"center_x": .5, "center_y": 0.99}
            size_hint:0.97,1
            on_kv_post:self.ids.tab_bar.spacing=1
            #inactive_font_size: sp(3)
            #active_font_size: self.inactive_font_size

            MDBottomNavigationItem:
                id: play
                text: 'Play'
                icon: 'soccer'
                on_tab_press: root.jugar(Botones.name)


            MDBottomNavigationItem:
                text: "Team"
                icon: 'account-multiple'
                on_tab_press: root.manager.current='screen2'

            MDBottomNavigationItem:
                text: 'Table'
                id:posiciones
                icon: 'format-align-justify'
                on_tab_press: root.manager.current='posiciones'

            MDBottomNavigationItem:
                text: 'Results'
                id:posiciones
                icon: 'view-list'
                on_tab_press: root.manager.current='lastres'

**Comment by HeaTTheatR** [comment]
@mateoaita If the application crashes, see the log. And only then can we draw any conclusions.

**Comment by mateoaita** [comment]
Hey! thanks for the advice, I could solve that problem. The thing is now the app on my phone crashes after some time using it and I believe it is due to this command to reload the MDBottomNavigation and I don't know how to fix it.


<ScreenOne>:
    **on_enter: bot_nav._refresh_tabs() #Solved positioning issue but it is the new suspect**
    BoxLayout:
        id:Botones
        name:Botones
        orientation:'vertical'

        MDBottomNavigation:
            id:bot_nav
            panel_color: .2, .2, .2, 1
            gcolor: .0, 0.1, .1, .8
            #pos_hint: {"center_x": .5, "center_y": 0.99}
            size_hint:0.97,1
            on_kv_post:self.ids.tab_bar.spacing=1
            #inactive_font_size: sp(3)
            #active_font_size: self.inactive_font_size

            MDBottomNavigationItem:
                id: play
                text: 'Play'
                icon: 'soccer'
                on_tab_press: root.jugar(Botones.name)


            MDBottomNavigationItem:
                text: "Team"
                icon: 'account-multiple'
                on_tab_press: root.manager.current='screen2'

            MDBottomNavigationItem:
                text: 'Table'
                id:posiciones
                icon: 'format-align-justify'
                on_tab_press: root.manager.current='posiciones'

            MDBottomNavigationItem:
                text: 'Results'
                id:posiciones
                icon: 'view-list'
                on_tab_press: root.manager.current='lastres'
