### ISSUE TITLE
MDFillRoundFlatButton height and background color inside RecycleBoxLayout

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#358]
I want to use MDFillRoundFlatButton  but i want to change it dimensions and it's background color 

I tried this 

```
size_hint_y: .3
height: 55
button_height: 55
```

but no thing change in the button ?

**Comment by HeaTTheatR** [comment]
@hussam132 https://github.com/HeaTTheatR/KivyMD/issues/144
