### ISSUE TITLE
MDCardSwipe not working under scrollview

### ISSUE THREAD

**Issue by gauravity30** [kivymd/KivyMD#360]
### Description of the Bug
Using the example of MDCardSwipe from the docs.. And under ScrollView the Swipe function is not working correctly.. it is vary hard to swipe.. please review it.

### Versions

* OS: Kali Linux 2020.1
* Python: 3.8
* Kivy: Latest
* KivyMD: Latest

**Comment by mp-007** [comment]
I think if you just reduce your scroll_timeout in the scroll view widget it will solve your problem.

ex:
```
ScrollView:
     scroll_timeout : 100
```

**Comment by gauravity30** [comment]
Maybe we could try that.. but under scroll view it acts like a jammed door and takes a loot of effort to swipe it..

**Comment by HeaTTheatR** [comment]
Looks like `scroll_timeout` solves the problem.

**Comment by gauravity30** [comment]
That's nice.. if it works.. I will try it out later..
