### ISSUE TITLE
MDInputDialog got removed in minor (patch) release

### ISSUE THREAD

**Issue by cstatz** [kivymd/KivyMD#363]
### Description of the Bug

MDInputDialog used to be available in `kivymd/uix/dialog.py`.
In the 0.104.1 minor release it got removed. This breaks code that relies on MDInputDialog.
I would expect API-breaking changes only in major releases.

### Versions

* OS: any
* Python: 3.X 
* Kivy: any
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@cstatz Yes. API libraries are still changing. And we cannot guarantee its stability in the future. But we try to avoid it.
