### ISSUE TITLE
MDFileManager only displaying image files

### ISSUE THREAD

**Issue by daddymonster2020** [kivymd/KivyMD#364]
### Description of the Bug

Apologies in advance if this is my implementation rather than a bug.  It works perfectly except it only displays image files and no other file types.  I wish to view all the flies in each folder.  How do I achieve this?

### Code and Logs

```python
class FileManager(MDFileManager):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Window.bind(on_keyboard=self.events)
        self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
            previous=True
        )
        self.file_manager.show('C:\\Users\\David\\PycharmProjects\\thememanager')
        self.manager_open = True

    def select_path(self, path):
        self.exit_manager()
        toast(path)

    def exit_manager(self, *args):
        self.manager_open = False
        self.file_manager.close()
```

### Versions

* OS: Windows 10
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@daddymonster2020 `MDFileManager` in `previous = True` mode displays only images.

**Comment by daddymonster2020** [comment]
@HeaTTheatR Yes, saw that in the docs. I should have mentioned: it's the same with it set to False. Format changes to rows, same files.
```
        self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
            previous=False
        )
```

**Comment by HeaTTheatR** [comment]
@daddymonster2020 https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/uix/filemanager.py#L409

**Comment by HeaTTheatR** [comment]
@daddymonster2020  In open issues there is already such a theme. This will be fixed in new versions.

**Comment by daddymonster2020** [comment]
@HeaTTheatR Perfect, thanks for your help.
