### ISSUE TITLE
how to add icon and the text in the MDTabsBase

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#368]
I want add icon and text inside MDTabsBase

this's my code

```
from kivy.lang import Builder
from kivymd.app import MDApp
KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs
        MDTabsBase:
            text: 'language-python main.py' # here i want to add icon and main.py like in the text editors
            size_hint_x:.5
            MDLabel:
                id: label
                text: "Tab 0"
                halign: "center"
        MDTabsBase:
            text: 'py.png'
            MDLabel:
                id: label
                text: "Tab 0"
                halign: "center"
                
 
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()

```

**Comment by HeaTTheatR** [comment]
@hussam132 https://kivymd.readthedocs.io/en/0.104.1/components/tabs/index.html#usage

**Comment by ghost** [comment]
the doc shows me how to set text or icon but not both !!

**Comment by HeaTTheatR** [comment]
@hussam132 

```python

from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd import fonts_path
from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.icon_definitions import md_icons

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs


<Tab>:
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    icons = list(md_icons.keys())[15:30]

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for name_tab in self.icons:
            self.root.ids.android_tabs.add_widget(
                Tab(text=f"[font={fonts_path + 'materialdesignicons-webfont.ttf'}]{md_icons[name_tab]}[/font] {name_tab}")
            )


Example().run()
```

![Снимок экрана 2020-06-25 в 16 02 19](https://user-images.githubusercontent.com/16930280/85724988-61ae1080-b6fd-11ea-9bb6-6bede464363b.png)

**Comment by ghost** [comment]
the following line will display what I want the ii con and the text that I want but how i can use it in the kv language if that possible 
`text=f"[font={fonts_path + 'materialdesignicons-webfont.ttf'}]{md_icons['language-python']}[/font] {'python'}"`
I tried this 
`text: f"[font={fonts_path + 'materialdesignicons-webfont.ttf'}]{md_icons['language-python']}[/font] {'oython'}"
`
but I'm getting error
`NameError: name 'fonts_path' is not defined
`
??

**Comment by ArtemSBulgakov** [comment]
@hussam132 Import fonts_path
```
#:import fonts_path kivymd.fonts_path
```
or use font name `[font=Icons]...`

**Comment by ghost** [comment]
I modified to be 
`text: f"[font=Icons]{md_icons['language-python']}[/font] {'python'}"`

but I'm getting error

`TypeError: 'module' object is not subscriptable`

**Comment by ArtemSBulgakov** [comment]
@hussam132 This error is in your code.

Please, the next time you need support, ask your questions in the Discord server: https://github.com/HeaTTheatR/KivyMD#support

**Comment by ghost** [comment]
thanks a lot @ArtemSBulgakov I wasn't knew about kivymd support chat room 

And that's a simple solution for my issue in case some interested about how to make MDTabs that contains icon and some custom text together in the kv language
```
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
#:import md_icons kivymd.icon_definitions.md_icons

BoxLayout:
    orientation: "vertical"

    MDTabs:
        id: android_tabs
        MDTabsBase:
            text: f"[font=Icons]{md_icons['language-python']}[/font] {'main.py'}"

        MDTabsBase:
            text: f"[font=Icons]{md_icons['language-go']}[/font] {'main.go'}"

'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```
