### ISSUE TITLE
Stiff Scroll Effect

### ISSUE THREAD

**Issue by mozesa** [kivymd/KivyMD#372]
### Description of the Bug

I would like to use `Stiff Scroll Effect` together with `RecycleView`.
The problem that after having a certain amount (?) of items I get an `RecursionError: maximum recursion depth exceeded in comparison`  error.
It belongs to the `Stiff Scroll Effect` because when I uncomment that line, the error goes away.
What I would like to achive not to have overscroll effect.

[traceback.txt](https://github.com/HeaTTheatR/KivyMD/files/4835777/traceback.txt)

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.recycleview import RecycleView
from kivymd.stiffscroll import StiffScrollEffect

Builder.load_string(
    """
<RV>:
    viewclass: 'Label'
    RecycleBoxLayout:
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
"""
)


class RV(RecycleView):
    def __init__(self, **kwargs):
        super(RV, self).__init__(**kwargs)
        self.effect_cls = StiffScrollEffect
        self.data = [{"text": str(x)} for x in range(100)]


class TestApp(App):
    def build(self):
        return RV()


if __name__ == "__main__":
    TestApp().run()
```

### Versions

* OS: _Windows 10_
* Python: _v3.8.3_
* Kivy: _v2.0.0rc3_
* KivyMD: _master_

Thanks for your help!

**Comment by HeaTTheatR** [comment]
@mozesa Yes. There is such a bug on Python 3.8
