### ISSUE TITLE
KivyMD Extensions Library

### ISSUE THREAD

**Issue by ArtemSBulgakov** [kivymd/KivyMD#378]
Hi all.
We have an idea to create a repository with small components (like Kivy Garden). I think, all of you have widgets based on KivyMD and want to share them with people. We want to make this action as simple as possible.

We think that it could be ONE repository with name `kivymd_components` (or another name) containing the folders with the components. This way you can just make Pull Request, where you add folder with code. If we would use multiple repositories, as Kivy Garden does, it would be difficult to create new components.

**We want to get advice by you**
- **What is the best name for repository?** (`kivymd_components` may confuse people because there is a Components section in KivyMD documentation)
- Maybe you know better way to do such?

**Comment by adywizard** [comment]
May I suggest kivymd_plugins, just like flutter plugins.

**Comment by ArtemSBulgakov** [comment]
We have a discussion in our [Discord server](https://github.com/HeaTTheatR/KivyMD#support). *([link to the first message](https://discordapp.com/channels/566880874789076992/566880874789076994/728578527397675018))*

Ideas are `kivymd_extensions` (or shortly `kivymd_exts`), `kivymd_library` and `kivymd_addons`.
"Extensions" are better because it can contain not only components (widgets), but also extensions, such as themes or utilities.

Big widgets or widgets that are not described at material.io will be in this library.

**Comment by moonpyx** [comment]
hi, i like kivymd_extensions although it sounds more familiar to me with a standard with kivy calling it kivymd_garden mm ... if it is somewhat simplistic

**Comment by allasca** [comment]
`from kivymd.extensions import ImagesHeader`

look good

**Comment by kulothunganug** [comment]
`kivymd_extensions` library has launched pls close 🙏🏽
