### ISSUE TITLE
How to add custom icon in KivyMD?

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#384]
I'm trying to add custom icon to my design instead of kivymd icons I don't how but my idea is to put my icon in the kivymd icons folder and then I call with its name , if my idea is correct where I can find the icons folder and if not how I can make it HOW i can add custom icon ?

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/icon_definitions.py

**Comment by ArtemSBulgakov** [comment]
It is not full answer. I will write instruction today.

**Comment by ArtemSBulgakov** [comment]
## Use images where possible

For MDIcon widget you can set `icon` to path to image. It will display its texture. For some widgets (that use MDIcon) you can try to set path to image.

## Webfont

We use webfont by [Material Design Icons community](https://materialdesignicons.com/). You can find the .ttf file in [kivymd/fonts](https://github.com/HeaTTheatR/KivyMD/tree/master/kivymd/fonts) directory.

To update this file and generate [icon_definitions.py](https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/icon_definitions.py) I wrote tool [update_icons.py](https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/tools/update_icons.py). This tool just downloads [Templarian/MaterialDesign-Webfont](https://github.com/Templarian/MaterialDesign-Webfont) repository, copies [.ttf font](https://github.com/Templarian/MaterialDesign-Webfont/tree/master/fonts) and gets list of icons (and their codes) from [preview.html](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/preview.html).

Main repository of Material Design Icons is [Templarian/MaterialDesign](https://github.com/Templarian/MaterialDesign). They generate Webfont using [Templarian/MaterialDesign-Font-Build](https://github.com/Templarian/MaterialDesign-Font-Build) tool.

## How to add custom icon to this font?

You can fork [Templarian/MaterialDesign](https://github.com/Templarian/MaterialDesign) repository, add your SVG icon and generate Webfont using [Templarian/MaterialDesign-Font-Build](https://github.com/Templarian/MaterialDesign-Font-Build) tool. Update .ttf font and icon_definitions.py in KivyMD using [update_icons.py](https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/tools/update_icons.py) tool (don't forget to change [font_path and preview_path](https://github.com/HeaTTheatR/KivyMD/blob/187ce490b91957d70f738096b7b1cbcefc36925b/kivymd/tools/update_icons.py#L38-L39)).

**Comment by hussam132** [comment]
can you give more details like where I should add icon  the link  [Templarian/MaterialDesign-Font-Build](https://github.com/Templarian/MaterialDesign-Font-Build) it's shows me how to build ??
please help

**Comment by hussam132** [comment]
also I want to knew what I should put in the `meta.json` and  `font-build.json`

**Comment by ghost** [comment]
@ArtemSBulgakov 

hi I find the way how to generate the the custom icon and new I want to Update .ttf font and icon_definitions.py in KivyMD and I modified the two lines in the preview.html like this
```
temp_font_path = f"{temp_repo_path}C:/Users/husam/OneDrive/Desktop/MaterialDesign-SVG-master/dist/fonts/fonts/materialdesignicons-webfont.ttf"
temp_preview_path = f"{temp_repo_path}C:/Users/husam/OneDrive/Desktop/preview.html"
```

but I'm getting this error 
```
C:\Users\husam\OneDrive\Desktop>python update_icons.py
Traceback (most recent call last):
  File "update_icons.py", line 22, in <module>
    os.chdir(os.path.dirname(__file__))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''
```

**Comment by HeaTTheatR** [comment]
@hussam132 The error text says what is the reason

**Comment by ArtemSBulgakov** [comment]
@hussam132 Remove the `{temp_repo_path}` from paths.

**Comment by hussam132** [comment]
can i repleace `os.chdir(os.path.dirname(__file__))` with` os.chdir(os.path.dirname(os.path.abspath(__file__)))`

**Comment by ghost** [comment]
I knew this issue was closed very long time ago but still facing some issue you said the  update_icons.py. will update the icon
 .ttf font and icon_definitions.py using  list of icons (and their codes) from preview.html. but there is the issue the web font tool said you need to download  [this](https://github.com/Templarian/MaterialDesign-Font-Build) and but your svg and then use the web font tool to generate new web font but the the tool will generate 
```
dist/
  css/
    materialdesignicons.css
    materialdesignicons.css.map
    materialdesignicons.min.css
    materialdesignicons.min.css.map
  fonts/
    materialdesignicons-webfont.eot
    materialdesignicons-webfont.ttf
    materialdesignicons-webfont.svg
    materialdesignicons-webfont.woff
    materialdesignicons-webfont.woff2
  scss/
    materialdesignicons.scss
    _animated.scss
    _core.scss
    _extras.scss
    _functions.scss
    _icons.scss
    _paths.scss
    _variables.scss
  index.html
```
this web font contain the icon that i added and the icon Unicode i can find it in `materialdesignicons-webfont.svg` but the tool will not create preview.html that contain the new icon Unicode and there is the issue i can't update the icon definition file but i tried to do that manually by adding the new icon name and Unicode after that all the icon not working only the new one 
so where i can find the preview.html that contain the icons Unicode that was generated by the the web font tool ?
I hope my issue clear new
