### ISSUE TITLE
Can't change the value of FitImage source after initalization

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#388]
### Description of the Bug

I wanted to change the value of source in FitImage after assigning it the initial value, but it refused to change ( I changed It using the on_enter event )

**Comment by HeaTTheatR** [comment]
@zworkb 

What you describe is not true. Perhaps you need to update the library from the master branch - `python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`

```python
from kivy.lang import Builder

from kivymd.app import MDApp


KV = '''
Screen:

    FitImage:
        id: fit_image
        source: "african-lion-951778_1280.png"

    MDRaisedButton2:
        text: "SET NEW IMAGE"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        on_press: app.set_new_image()

'''


class MainApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def set_new_image(self):
        self.root.ids.fit_image.source = "beautiful-931152_1280.png"


MainApp().run()
```

**Comment by kengoon** [comment]
@HeaTTheatR I update my library as you suggested but I started having a problem with MDNavigation icons(they are not properly arranged) and I also tried the new "refresh_tap()" method but no success

**Comment by HeaTTheatR** [comment]
@kengoon Create a new issue.
