### ISSUE TITLE
get_hex_from_color

### ISSUE THREAD

**Issue by mathe1s** [kivymd/KivyMD#39]
Please insert:
in load_string:
#:import get_hex_from_color kivy.utils.get_hex_from_color

in header:
from kivy.utils import get_hex_from_color

For correct functionality.

**Comment by HeaTTheatR** [comment]
Which line and which file?

**Comment by mathe1s** [comment]
In file: main.py
I needed to insert:
from kivy.utils import  get_hex_from_color on line 18

And 
#:import get_hex_from_color kivy.utils.get_hex_from_color on line 59

To use all avaliable controls.

**Comment by HeaTTheatR** [comment]
Update KivyMD library! Current version - 0.96.8
![Снимок экрана 2019-04-21 в 23 47 08](https://user-images.githubusercontent.com/16930280/56475364-d1889180-648f-11e9-9828-f2c78a19750b.png)
