### ISSUE TITLE
MDFloatingActionButtonSpeedDial, DropDownMenu in the new version, the icons disappeared

### ISSUE THREAD

**Issue by sanodin** [kivymd/KivyMD#390]
Good afternoon, in the new version kivymd 0.104.1, the icons disappeared MDFloatingActionButtonSpeedDial, DropDownMenu

### Screenshots
<a href="https://ibb.co/Zzb9gN2"><img src="https://i.ibb.co/3mPKFkR/kivymd.png" alt="kivymd" border="0"></a>
[https://ibb.co/Zzb9gN2](url)

### Versions

* OS: windows 7, ubuntu
* Python: 3.6
* Kivy:  v1.10.1
* KivyMD:

**Comment by HeaTTheatR** [comment]
Dublicate - https://github.com/HeaTTheatR/KivyMD/issues/327
