### ISSUE TITLE
Your Demo work perfect but here is an error on program when i written by follow your documentation

### ISSUE THREAD

**Issue by sparrow-code** [kivymd/KivyMD#392]
I write code

from kivymd.app import MDApp
from kivymd.uix.label import MDLabel

class MainApp(MDApp):
def build(self):
return MDLabel(text="Hello, World", halign="center")

MainApp().run()

then show me error by python idle 
ModuleNotFoundError: No Module Named 'kivymd.app'; 'kivymd' is not a package

**Comment by HeaTTheatR** [comment]
@sparrow-code In your working directory with your program is the file `kivymd.py`. No need to name your files with the names of other libraries.
