### ISSUE TITLE
KivyMD version(0.104.1) dropdown in not working

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#393]
hello guys I have updated my kivyMD version(0.104.0) a few days ago and my MDdropdown was working fine before updating but in latest MD version(0.104.1) it is not working so do you guys having any solutions for it? please fix it because it is not working on kivyMD demo app too
below is the same code which I am using
https://pastebin.com/GDPEXmGk

**Comment by HeaTTheatR** [comment]
@navjotcis https://kivymd.readthedocs.io/en/latest/components/menu/index.html#center-position

**Comment by navjotcis** [comment]
@HeaTTheatR, I have tried using above giving URL for the dropdown problem and it makes the dropdown working but it have some problems so do you guys have any permanent fix for it 
![image](https://user-images.githubusercontent.com/33522186/91478373-58881e00-e8bd-11ea-8f15-47f39dc1c300.png)
 These errors appears multiple times when someone try to open the dropdown.
