### ISSUE TITLE
texture_size is not updated consistently

### ISSUE THREAD

**Issue by jun0** [kivymd/KivyMD#395]
### Description of the Bug

`MDLabel`'s `texture_size` member seems not to be updated to consistently reflect the actual display size when `font_size` is changed.  In the following code, an `on_size` function tries to maintain a fixed size relative to the window size by scaling the `font_size` by a factor computed from the window size and `texture_size`.  When you run this on a PC and repeatedly resize the window, you see the size of the text fluctuating wildly, eventually shrinking into a dot.  If you remove all instances of `md` and `MD` from this example so that you have a pure kivy program (using `Label` instead of `MDLabel`, for example), the text size is kept constant relative to the window size, no matter how many times you resize.

I'm not entirely sure if I'm supposed to use `texture_size` in KivyMD (I mean, it doesn't even exist on `MDRoundFlatButton` and things), but I need this to compute the size of a very large numerical display.  Using a large, fixed size would mean overrunning the available screen size on smaller devices.

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.lang import Builder

class MyLayout (MDBoxLayout):
    def on_size (self, inst, size):
        # Try to keep the text at 90% of available width.
        if self.ids.lab.texture_size[0] > 0:
            self.ids.lab.font_size *= size[0] * 0.9 / self.ids.lab.texture_size[0]

class MyApp (MDApp):
    def build (self):
        return Builder.load_string ('''
MyLayout:
    MDLabel:
        id: lab
        text: "Test text"
''')

if __name__ == '__main__':
    MyApp ().run ()
```

### Versions

* OS: Ubuntu 20.04 LTS
* Python: 3.8
* Kivy: v1.10.1 (via apt-get)
* KivyMD: v0.104.1 (via pip)

**Comment by HeaTTheatR** [comment]
@jun0 https://github.com/HeaTTheatR/KivyMD/issues/217

**Comment by jun0** [comment]
Ah, I see, thank you.  Sorry for missing that.
