### ISSUE TITLE
MDTextField needs to allow Text Color changes

### ISSUE THREAD

**Issue by edwit1971** [kivymd/KivyMD#398]
### Description of the Feature

Currently the programmer can not change the TextColor attribute of a MDTextField Object.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@edwit1971 
https://kivymd.readthedocs.io/en/latest/components/text-field/index.html#color-mode

```line_color_focus: 1, 0, 1, 1```
