### ISSUE TITLE
Icons NOT showing on Device in either MDNavigationDrawer or MDDropdownMenu

### ISSUE THREAD

**Issue by edwit1971** [kivymd/KivyMD#400]
### Description of the Bug

while developing on my PC the icons show just fine.  But when I compile with Buildozer to make an APK file, when I run the App on the Tablet none of the icons are showing in either my MDDropdownMenu or MDNavigationDrawer.

This might be a Buildozer or Python-4-Android bug actually...

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@edwit1971 Dublicate - https://github.com/HeaTTheatR/KivyMD/issues/327
