### ISSUE TITLE
Contained button with icon *spacings*

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#403]
### Description of the Feature

At [MDFillRoundFlatIconButton](https://kivymd.readthedocs.io/en/latest/components/button/index.html?highlight=MDFillRoundFlatIconButton#mdfillroundflaticonbutton) you can see that the spacings/paddings are not correct. The right padding seems a bit too much and according to material design's [button specs](https://material.io/components/buttons#specs) it should be 12 from the left, 8 between the icon and the text and 16 on the right. 

I'm not sure if this a bug or a lack of feature but it doesn't feel like a bug. So I'm adding it here.

### Screenshots

![image](https://user-images.githubusercontent.com/45745548/87355991-fc19ab00-c569-11ea-9425-01dbe0daa333.png)

![image](https://user-images.githubusercontent.com/45745548/87356015-076cd680-c56a-11ea-902d-124d2aa2f613.png)

**Comment by HeaTTheatR** [comment]
@BananaMasterz Yes, thanks for the question. Obviously indentations is not correct.

**Comment by HeaTTheatR** [comment]
@BananaMasterz This is fixed, just old screenshots in the documentation
