### ISSUE TITLE
Push OneLineItem widget to the top

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#404]
Please is there a way I can push a widget to the top of other widgets if an event occurred. Just like Whatsapp, if a new message comes in, the widget associated with the new message goes to the top. Thanks in advance

**Comment by HeaTTheatR** [comment]
@kengoon What does this related to do with the KivyMD library?

**Comment by kengoon** [comment]
> @kengoon What does this related to do with the KivyMD library?

I'm just asking if it is improper I would not ask again

**Comment by HeaTTheatR** [comment]
@kengoon Your issue is not related to the work of the `KivyMD` library. Try to ask in the [Kivy](https://discord.gg/UKnb6dK) or [KivyMD](https://discord.gg/aTkt235) servers.
