### ISSUE TITLE
center_x not working with MDLabel 

### ISSUE THREAD

**Issue by Harman-Sandhu** [kivymd/KivyMD#407]
### Description of the Bug

While setting the center_x in pos_hint for the MDLabel, the MDLabel does not move to the correct place.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.theming import ThemeManager

KV = """
FloatLayout:
    Label:
        text: "Kivy"
        pos_hint: {"center_x":.5,"center_y":.5}
    MDLabel:
        text: "KivyMD"
        pos_hint: {"center_x":.5,"center_y":.5}

"""


class Test(MDApp):
    def build(self):
        ThemeManager.theme_style = "Dark"
        return Builder.load_string(KV)


Test().run()
```

### Screenshots

![image](https://user-images.githubusercontent.com/35080189/87734503-b3acf800-c7ca-11ea-9235-371ec23721fd.png)

### Versions

* OS: Windows
* Python: 3.7
* Kivy:  v2.0.0rc3
* KivyMD: v0.104.1

**Comment by HeaTTheatR** [comment]
@RealHarmZ `halign: 'center'`
