### ISSUE TITLE
MDFileManager (Pillow) Error!

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#411]
when i tried to use the mdfilemanager it works well in pc but when i build that and test, it tells : import error 'from PIL import Image'
so pls remove the pillow library and add the alternative of that

**Comment by HeaTTheatR** [comment]
@Kulothungan16 `python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by HeaTTheatR** [comment]
@Kulothungan16 `requirements = kivy==1.11.1, git+https://github.com/HeaTTheatR/KivyMD.git`
