### ISSUE TITLE
Problems with MDFileManager

### ISSUE THREAD

**Issue by Eretick** [kivymd/KivyMD#417]
### Description of the Bug

The file manager returns wrong path in non-preview mode. It's add to folder path full abs path of file instead just it`s name. 
For example, i have _Win10PE_v5_1_1_RU.txt_ file in _D:\Zona Downloads\Windows 10 PE_.
And I expect to get D:\Zona Downloads\Windows 10 PE\Win10PE_v5_1_1_RU.txt as result of choosing file.

But instead i got _/Zona Downloads/Windows 10 PE//Zona Downloads/Windows 10 PE\readme — Win10PE_v5_1_1_RU.txt_
Tha part of path is duplicated because files are shown not as  (for example) _Win10PE_v5_1_1_RU.txt_ but _/Zona Downloads/Windows 10 PE\readme — Win10PE_v5_1_1_RU.txt_

So of cource i cant open file because of invalid path. 
The fun part - no problems in preview mode. But i dont need images. 

No code here, cause it the same even on example code from documentation.

**Comment by HeaTTheatR** [comment]
Fix https://github.com/HeaTTheatR/KivyMD/commit/2407f3c4b2b23f390c29a7233235f8765f55186b
