### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.uix.managerswiper'

### ISSUE THREAD

**Issue by arvindmajhi** [kivymd/KivyMD#418]
### Description of the Bug

I tried to replicate SwipeManager feature but got ModuleNotFoundError: No module named 'kivymd.uix.managerswiper' also
self.theme_cls.primary_palette = doesn't work so I had to comment and execute.

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Windows
* Python: 3.6.5
* Kivy: v2.0.0rc3
* KivyMD: v0.104.1

**Comment by HeaTTheatR** [comment]
This module has been removed. Reinstall library from master branch - `python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`
https://kivymd.readthedocs.io/en/latest/themes/material-app/index.html#kivymd.app.MDApp.theme_cls
