### ISSUE TITLE
Error building following README instructions on master

### ISSUE THREAD

**Issue by brentpicasso** [kivymd/KivyMD#42]
Followed instructions for installing, errors compiling

sudo python ./setup.py install

=============
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/progressbar.py to progressbar.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/ripplebehavior.py to ripplebehavior.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/vendor/circleLayout/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/vendor/circularTimePicker/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/vendor/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/vendor/navigationdrawer/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/backgroundcolorbehavior.py to backgroundcolorbehavior.pyc
  File "/usr/local/lib/python2.7/dist-packages/kivymd/backgroundcolorbehavior.py", line 48
    options=['Primary', 'Accent', *palette])
                                  ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/imagelists.py to imagelists.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/snackbars.py to snackbars.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/kivymd/font_definitions.py to font_definitions.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/kivymd-0.97_.2.egg-info
$ python --version
Python 2.7.12

**Comment by ArtemSBulgakov** [comment]
Python 3 is supported. Developers don't use Python 2

**Comment by ArtemSBulgakov** [comment]
You can use KivyMD without installing. Try to place directory "kivymd" to your project files

**Comment by brentpicasso** [comment]
Thanks for the tip. If that's the case, I recommend that the requirements in README should indicate required version of python.

**Comment by HeaTTheatR** [comment]
@brentpicasso KivyMD works with Python 2 too.
