### ISSUE TITLE
How to Remove The MDBottomAppBar White Background

### ISSUE THREAD

**Issue by qodzero** [kivymd/KivyMD#421]
**Reproduce**: Run the MDBottomAppBar example from the docs

The widget has a white background, even seen on the example behind the FAB. Is there a way to remove that white background? I tried checking the docs AND the implementation but seems like the MDBottomAppBar simply inherits from a FloatLayout with no canvas instructions(I checked all canvas instructions associated with the widget and zilch).

Is there ANY way of doing this? even if its a hack because I have a ScrollView behind that Bar and that white background simply messes up my design hopes

**Comment by HeaTTheatR** [comment]
@qodzero Do you mean this?
![Снимок экрана 2020-07-25 в 19 15 41](https://user-images.githubusercontent.com/16930280/88461368-78d25080-ceab-11ea-91a7-4a505784c9c7.png)

**Comment by qodzero** [comment]
Yes, that

**Comment by qodzero** [comment]
@HeaTTheatR or atleast in my case, change the color of that white background

**Comment by HeaTTheatR** [comment]
@qodzero It cannot be removed as this white circle is for technical purposes.

**Comment by qodzero** [comment]
Hmm..ok then, @HeaTTheatR , is it atleast possible to make it smaller, I think maybe its a bug but sometimes, the white back appears quite big, as demonstrated in the image below:
![appbar](https://user-images.githubusercontent.com/26411825/88547304-d1c1f600-d01d-11ea-8892-c8facecf5666.png)

**Comment by podraco** [comment]
it looks like the end of the scroll view
so that means that the shadow should be dissmissed or cut in two where the floating button starts and ends

**Comment by qodzero** [comment]
@podraco Which ScrollView are you referring to?

**Comment by podraco** [comment]
well, not scroll view, but the layer below the MDBottomAppBar. the line mustt be the end of the layer below. and if i'm right, the shadow is from the MDBottomAppBar

**Comment by HeaTTheatR** [comment]
Fix https://github.com/kivymd/KivyMD/pull/798
