### ISSUE TITLE
Inline Datatables

### ISSUE THREAD

**Issue by lemousehunter** [kivymd/KivyMD#424]
So far, DataTables have always ran as a popup, and thus far I see no viable way to place them inline (e.g. within a screen). As such, this may result in a non-streamlined user ex. as the user will be click a button to view the data table.

**Comment by HeaTTheatR** [comment]
@lemousehunter Tables are a very complex widget. Unfortunately, now there are no free resources to start optimizing this widget ...

**Comment by lemousehunter** [comment]
I think I meant whether it is possible to implement MDDataTables inside a layout or screen instead of a dialog box

**Comment by senc22** [comment]
> 
> 
> I think I meant whether it is possible to implement MDDataTables inside a layout or screen instead of a dialog box

@lemousehunter this would be quite useful, did you manage to implement this?

**Comment by podraco** [comment]
it's really a feature needed, since people might use it more in a Screen rather a dialog box. i tried once, but the touch was being digested by an unknown widget TT-TT

**Comment by lemousehunter** [comment]
@podraco @senc22 I've created my own custom table...its a bit rough around the edges but works for my purpose. It works using a ScrollView rather than RecycleView, working on the princple of pagination (directly linked to a database). If you're interested do let me know I'll create a repo and put it up there...I'm not creating PR reason being the code is definitely not optimized like how most of the stuff on the MDKivy repo is...and I have neither the time nor the energy to do it. Also its a bit rough on the edges...such as Pagination not being implemented yet...

**Comment by podraco** [comment]
Thanks, i really appreciate that.
I already have done something similar, but the idea is to add it to kivyMD so everyone will be able to use it. 

If it wasn't because an NDA, I would have added that ages ago :/

**Comment by lemousehunter** [comment]
I can see why the feature hasnt been implemented tho...datatables are indeed a very complex widget (realised this after doing up a custom one from scratch) and there's no 'one size fits all' for everyone; each datatable is gonna be needed to be customized for the needs of each app so creating a generic one is gonna be hard...i guess thats why the devs decided on a dialog box instead? not too sure...am just speculating haha. Though I must say, I wish that creating a datatable in kivy and python is as easy as creating one in html... :')

**Comment by podraco** [comment]
i believe that if we use constructor, we might be able to do something similar to a generig datatable

**Comment by podraco** [comment]
it would be usefull if we use No SQL to store values, like a Json, or a pickle, and access to intervals in the file to show the elements needed.

```
"head":
    We save the order we want to show here
    "keys":[a,b,c,d]
    We declare the row list with their callbacks, the type of element and if they should be sort-able and in case, the sort call
    "a": [config ...]
    "b": [config ...]
    [etc ...]
"data":
Stored as CSV like values, every entry is a row and every item in the entry is the elemen in the order shown in databse[head][keys]
[1,2,3,4,],[1,2,3,4] 
"config":
   general configuration of the database like, elements per page, or if the ammount of element should be rotating between them, etc, etc.
colors, boxes, drawings, and callback if you reach the end.
```

in this model, we only load in screen an interval declared by x_min, and x_max, for the indexes, so we would be able to call something like:
```
update_widget:
   buffer=database[xmin:xmax] + [[""]*len(database[head][keys])]*(widget in screen - elements in database[xmin:xmax])
   for a,b in enumerate (buffer):
     element_in_screen[a].store=buffer[a]


``` 
and the element in row reads the store property and loads it accordingly.

**Comment by podraco** [comment]
```py
memory={
    "headers":{
        "col1":{
            "type":"numeric",
            "orderby":True,
            [otherconf ...]
        },
        "col4":{
            "type":"text",
            "orderby":True,
            [otherconf ...]
        },
        "col2":{
            "type":"numeric",
            "orderby":False,
            [otherconf ...]
        },
        "col3":{
            "type":"numeric",
            "orderby":True,
            "dropdown":["op","ti","on"],
            "drop_callback":self.some_function
            [otherconf ...]
        },
        # the "keys" storage gives the orer in wich the datatable shall load the cols
        "keys":["col1","col2","col3","col4",]
    },
    # CSV like data in the order that the cols key shows
    "data":[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]] 
}
```

**Comment by kevin-schumann** [comment]
@lemousehunter I've modified the data table to be inline for a personal project. I can share the code if still needed.
