### ISSUE TITLE
[Bug] Dropdown menu for pagination does not update pos of dropdown 

### ISSUE THREAD

**Issue by lemousehunter** [kivymd/KivyMD#426]
As mentioned in title, dropdown menu for pagination is buggy: upon immediate fullscreen (in windowed mode), the datatable does not update the pos of the dropdown menu, causing it to float in its original position.

An example would be this:
![data_table_fullscreen_bug](https://user-images.githubusercontent.com/60069055/88958124-9ac83a80-d2d2-11ea-80e0-729f338c9db0.png)

However, what's interesting to note is that it works (the pos of dropdown menu is automatically updated) upon manual resizing of window.

Code to reproduce error:
`from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp
if __name__ == '__main__':

    class DataTable:
        def __init__(self):
            self.data_tables = MDDataTable(
                size_hint=(0.9, 0.6),
                use_pagination=True,
                column_data=[
                    ("No.", dp(30)),
                    ("Column 1", dp(30)),
                    ("Column 2", dp(30)),
                    ("Column 3", dp(30)),
                    ("Column 4", dp(30)),
                    ("Column 5", dp(30)),
                ],
                row_data=[
                    (f"{i + 1}", "1", "2", "3", "4", "5") for i in range(50)
                ],
            )

        def open(self):
            self.data_tables.open()

    class App(MDApp):
        def build(self):
            return DataTable().open()

    App().run()
`

**Comment by lemousehunter** [comment]
I managed to fix the issue by editing the src - I bound 2 methods: `on_maximize` and `on_restore` to `self.set_menu_properties`. Will be sending a pull request soon (once i figure out how git works lol)

**Comment by HeaTTheatR** [comment]
@lemousehunter OK!
