### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'kivymd.elevationbehavior'

### ISSUE THREAD

**Issue by lemousehunter** [kivymd/KivyMD#427]
### ModuleNotFoundError: No module named 'kivymd.elevationbehavior'

When trying to import 'MDCheckbox' from `kivymd.selectioncontrols`, the above-mentioned error is raised. Upon further inspection, I realized that in line 15 of `kivymd.selectioncontrols`, the following import statement `from kivymd.elevationbehavior import CircularElevationBehavior` throws this error, as the module kivymd.elevationbehavior does not exist in the kivymd library.

### Potential Fix/Workaround
Replace `kivymd.elevationbehavior` with `kivymd.uix.behaviors`

### Other Errors and their fixes
**Error:**
Mispelled key 'Grey' - eg. `colors['Gray']` results in `KeyError: 'Grey'`
**Fix:**
Replace all 'Grey' words with 'Gray'.

### Code and Logs

```
File "xxx.py", line 19, in <module>
     from kivymd.selectioncontrols import MDCheckbox
   File "%APPDATA%\Python\Python38\site-packages\kivymd\selectioncontrols.py", line 15, in <module>
     from kivymd.elevationbehavior import CircularElevationBehavior
 ModuleNotFoundError: No module named 'kivymd.elevationbehavior'
```

### Versions

* OS: Windows 10
* Python: 3.8
* Kivy: 0.20
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@lemousehunter `from kivymd.uix.selectioncontrols import MDCheckbox`

**Comment by lemousehunter** [comment]
@HeaTTheatR still doesnt work, throws `ModuleNotFoundError: No module named 'kivymd.elevationbehavior'`. It references the same file, "%APPDATA%/Python/Python38/site-packages/kivymd/selectioncontrols.py" that `kivymd.uix.selectioncontrols` does.

**Comment by HeaTTheatR** [comment]
@lemousehunter 
Show the full log from start application to error.
Show the minimal code that leads to the error.

**Comment by HeaTTheatR** [comment]
@HeaTTheatR `python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`
