### ISSUE TITLE
[Bug] MDFlaotingActionButton

### ISSUE THREAD

**Issue by ElLoko233** [kivymd/KivyMD#433]
### Code and Logs

from kivymd.uix.screen import Screen
from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial

class Example(MDApp):
    data = {
        'language-python': 'Python',
        'car': 'PHP',
        'language-cpp': 'C++',
        'pizza':'yumyum'
    }

    def build(self):
        screen = Screen()
        speed_dial = MDFloatingActionButtonSpeedDial()
        speed_dial.bg_color_root_button = (1, 1, 0.4, 1)
        speed_dial.data = self.data
        speed_dial.label_text_color = (0.5, 1, 0, 1)
        
        screen.add_widget(speed_dial)
        return screen

Example().run()

###expectation 
I expected the code to run but it threw an error

### error

[INFO   ] [Logger      ] Record log in /storage/emulated/0/My programs/KivyMD practise/.kivy/logs/kivy_20-07-31_124.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, Jun 15 2020, 02:19:10) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 v1.r22p0-01rel0.9ec4ae29cda192f74d35a11091de4ace'>
[INFO   ] [GL          ] OpenGL vendor <b'ARM'>
[INFO   ] [GL          ] OpenGL renderer <b'Mali-T830'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 2
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/storage/emulated/0/My programs/KivyMD practise/KivyDemo.py", line 25, in <module>
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/app.py", line 829, in run
     root = self.build()
   File "/storage/emulated/0/My programs/KivyMD practise/KivyDemo.py", line 17, in build
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivymd/uix/button.py", line 1684, in on_bg_color_root_button
     self._get_count_widget(MDFloatingRootButton).md_bg_color = value
 AttributeError: 'NoneType' object has no attribute 'md_bg_color'

### Versions

* OS: 
* Python: 3.8
* Kivy: 
* KivyMD: 1.11.1

**Comment by HeaTTheatR** [comment]
@ElLoko233 If you encounter an error in the code or if something could not be done, attach a minimal code that can be run without additional manipulations so that developers can look at the working script and fix it. Write also what you expected from the script and what happened as a result. No need to take screenshots on which you display your code.  Less words, more code. We all speak different languages ​​with you, but we have one programming language - Python!
