### ISSUE TITLE
Adding support for "static/standard" Navigation Drawer in MDNavigationDrawer

### ISSUE THREAD

**Issue by wasimafser** [kivymd/KivyMD#436]
### Description of the Feature
As we know Kivy is not only used for mobile apps but also for desktop apps, the implementation of a standard navigation drawer would be a great addition to the MDNavigationDrawer.

While this can be achieved using a simple BoxLayout, it would be better with the already available MDNavigationDrawer , as it would help both the developers and the users to customise the navigation. ( if this options is a property for example `type: 'static'` , then developers can embed this option in their App's settings to let users choose the type of navigation they want, all that just with a property change )

### Screenshots / Reference

https://material.io/components/navigation-drawer#usage

#### [STATIC NAV DRAWER]
![image](https://user-images.githubusercontent.com/46491838/89103213-bac04100-d42d-11ea-81d0-b1613f3d5d26.png)

#### [MODAL NAV DRAWER ( Currently in MDNavigationDrawer ) ]
![image](https://user-images.githubusercontent.com/46491838/89103203-a67c4400-d42d-11ea-85a5-bd77e433f189.png)

**Comment by ArtemSBulgakov** [comment]
Fixed by #441
