### ISSUE TITLE
MDTabs no dynamic changes

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#446]
### Description of the Bug

In the code below if you switch tabs, the text from hello should change to bye but nothing happens.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.app import Builder
from sys import exit as sys_exit
from kivymd.uix.tab import MDTabsBase
from kivy.uix.scrollview import ScrollView

kv = """

BoxLayout
    MDTabs:
        id: tabs
        
        Tab:
            text: "hello" if self.tab_label is tabs.carousel.current_slide.tab_label else "bye"
            markup: True

        Tab:
            text: "whatever"
        
"""


class App(MDApp):
    def build(self):
        return Builder.load_string(kv)

    class Tab(ScrollView, MDTabsBase):
        pass

App().run()
```

**Comment by BananaMasterz** [comment]
so I found out that the following works instead, BUT if I swipe to switch tabs, everything works correctly. If I click the label to switch tabs, the label doesn't change unless I click it one more time. See the video sample below.

```
from kivymd.app import MDApp
from kivy.app import Builder
from sys import exit as sys_exit
from kivymd.uix.tab import MDTabsBase
from kivy.uix.scrollview import ScrollView

kv = """

BoxLayout
    MDTabs:
        id: tabs
        on_tab_switch: 
            tab1.text = "on" if tab1.tab_label is tabs.carousel.current_slide.tab_label else "off"
            tab2.text = "on" if tab2.tab_label is tabs.carousel.current_slide.tab_label else "off"
        Tab:
            id: tab1
            text: "whatever"
            markup: True

        Tab:
            id: tab2
            text: "whatever"
        
"""


class App(MDApp):
    def build(self):
        return Builder.load_string(kv)

    class Tab(ScrollView, MDTabsBase):
        pass

App().run()
```



![exam](https://user-images.githubusercontent.com/45745548/89732844-199f3f00-da5a-11ea-8929-8d393119b6cc.gif)

**Comment by HeaTTheatR** [comment]
@BananaMasterz When switching a tab, the value for the `current_slide` is set later. Therefore, your expressions are not correct.

**Comment by HeaTTheatR** [comment]
@BananaMasterz Use `on_tab_switch`.

**Comment by BananaMasterz** [comment]
> @BananaMasterz Use `on_tab_switch`.

You're correct, on_tab_switch works indeed but not correctly. Please see my answer above too. ( I answered to my own question before and you might have not seen it)

**Comment by p0lygun** [comment]
@BananaMasterz 
```
from kivymd.app import MDApp
from kivy.app import Builder
from sys import exit as sys_exit
from kivymd.uix.tab import MDTabsBase
from kivy.uix.scrollview import ScrollView

kv = """

BoxLayout
    MDTabs:
        id: tabs
        on_tab_switch: app.on_tab_switch(*args)
        Tab:
            id: tab1
            text: "whatever"
            markup: True

        Tab:
            id: tab2
            text: "whatever"
        
"""


class Tab(ScrollView, MDTabsBase):
    pass


class App(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def on_tab_switch(self, instance_tabs, instance_tab, instance_tab_label, tab_text):
        """Called when switching tabs.

        :type instance_tabs: <kivymd.uix.tab.MDTabs object>;
        :param instance_tab: <__main__.Tab object>;
        :param instance_tab_label: <kivymd.uix.tab.MDTabsLabel object>;
        :param tab_text: text or name icon of tab;
        """
        instance_tab.text = "off"


App().run()
```

**Comment by HeaTTheatR** [comment]
@BananaMasterz I see that everything is working.

**Comment by BananaMasterz** [comment]
> @BananaMasterz
> 
> ```
> from kivymd.app import MDApp
> from kivy.app import Builder
> from sys import exit as sys_exit
> from kivymd.uix.tab import MDTabsBase
> from kivy.uix.scrollview import ScrollView
> 
> kv = """
> 
> BoxLayout
>     MDTabs:
>         id: tabs
>         on_tab_switch: app.on_tab_switch(*args)
>         Tab:
>             id: tab1
>             text: "whatever"
>             markup: True
> 
>         Tab:
>             id: tab2
>             text: "whatever"
>         
> """
> 
> 
> class Tab(ScrollView, MDTabsBase):
>     pass
> 
> 
> class App(MDApp):
>     def build(self):
>         return Builder.load_string(kv)
> 
>     def on_tab_switch(self, instance_tabs, instance_tab, instance_tab_label, tab_text):
>         """Called when switching tabs.
> 
>         :type instance_tabs: <kivymd.uix.tab.MDTabs object>;
>         :param instance_tab: <__main__.Tab object>;
>         :param instance_tab_label: <kivymd.uix.tab.MDTabsLabel object>;
>         :param tab_text: text or name icon of tab;
>         """
>         instance_tab.text = "off"
> 
> 
> App().run()
> ```

that's not the behavior I'm going for. I want to change the label according to which tab is active. This just switches to off when the tab is clicked and then never changes again.

**Comment by BananaMasterz** [comment]
> @BananaMasterz I see that everything is working.

Please see the video carefully. When I click the label, the label doesn't switch to "on" even though the indicator shows that it changed the tab. I have to click again for the label to update. But when I swipe, you can see it changes instantly. I'm sorry if I'm being confusing.

**Comment by HeaTTheatR** [comment]
@BananaMasterz In the `on_tab_switch` method, you have all the data to check which tab is currently active. Your question is not related library bugs or problems and is only about your code.

**Comment by HeaTTheatR** [comment]
@BananaMasterz Therefore, it is better to ask such questions on the Discord server - https://discord.gg/wu3qBST
