### ISSUE TITLE
MDTextField class not working as spected

### ISSUE THREAD

**Issue by podraco** [kivymd/KivyMD#448]
### Description of the Bug

This is a list of errors i encountered while working with the MDTextfield widget class.

#### Open

2. The filling is drawing after all the textures. if the filling has an Alpha of 1, the whole widget will be turned the color, hiding everything inside the widget.
- This could be solved by either drawing the filling in the canvas.before
This might cause the text to be illegible over the filling, since it's not taking any color from it, it might be a good idea to drop the alpha channel of the text to 0.9 to allow the text to merge and gain some strength from the filling, as it happens with the filling example with the filling color of `[0, 0, 0, 0.4]`
- Or parsing the filling color as an RGB format and adding a default Alpha of 0.5.

3. The MDTextField doesn't change the text to black when unfocused in any iteration of the properties 
This will mislead the end user to believe he's changing a field that is not on focus. Or in the case that the UI has multiple fields, loss track of what was the end-user doing.

4. The rectangle of MDTextField when `mode: "rectangle"` is not changing color when unfocused or on_focus.
As the point before, this will mislead the end-user  to believe that they had selected a text field not on focus.

5. The filled MDTextField and `mode: "rectangle"` draws the instruction outside the widget, it requires an extra padding of dp(16) around it to show properly.

### update 2020-08-10-6:33 AM GTM-6

When the MDTextField canvas.before is modified (added a new instruction), the last added color is used to draw the text. This might lead to the bug. Since it might be caused because the text color is not settled.

#### Fixed
1. The `hint_text `object doesn't work properly when `on_error `status is active, if the MDTextfield had text inside once, the color of the `hint_text `will turn black instead of red. but before the MDTextfield had any text it worked properly.
This behavior is consistent with every error status, independent if it's launched by `requider:True`, `max_text_length`or manually set to error.
It seems that the red text is being drawn below the black text as seen in the pictures below, might have something to do with the texture of the label.
FIXED IN #520 

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

from kivymd.app import MDApp

KV="""
BoxLayout:
    padding:dp(8)
    MDGridLayout:
        cols:2
        spacing:dp(16)
        MyTextField:
            hint_text: "No helper text"
        MyTextField:
            hint_text: "Helper text on focus"
            helper_text: "This will disappear when you click off"
            helper_text_mode: "on_focus"
        MyTextField:
            hint_text: "Persistent helper text"
            helper_text: "Text is always here"
            helper_text_mode: "persistent"
        MyTextField:
            id: text_field_error
            hint_text: "Helper text on error (press 'Enter')"
            helper_text: "There will always be a mistake"
            helper_text_mode: "on_error"
            pos_hint: {"center_y": .5}
        #
        MyTextField:
            hint_text: "required = True"
            required: True
            helper_text_mode: "on_error"
            helper_text: "Enter text"
        MyTextField:
            hint_text: "Max text length = 5"
            max_text_length: 5
        MyTextField:
            multiline: True
            hint_text: "Multi-line text"
        MyTextField:
            hint_text: "color_mode = 'accent'"
            color_mode: 'accent'
        MyTextField:
            hint_text: "color_mode = 'custom'"
            color_mode: 'custom'
            helper_text_mode: "on_focus"
            helper_text: "Color is defined by 'line_color_focus' property"
            line_color_focus: 1, 0, 1, 1
        MyTextField:
            hint_text: "Line color normal"
            line_color_normal: app.theme_cls.accent_color
        MyTextField:
            hint_text: "Rectangle mode"
            mode: "rectangle"
        MyTextField:
            hint_text: "Fill mode"
            mode: "fill"
            fill_color: 0, 0, 0, .4
"""

class MyTextField(MDTextField):
    pass


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def build(self):
        self.screen.ids.text_field_error.bind(
            on_text_validate=self.set_error_message,
            on_focus=self.set_error_message,
        )
        return self.screen

    def set_error_message(self, instance_textfield):
        self.screen.ids.text_field_error.error = True

Test().run()


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

in this images you can see that the black text has somewhat a red dye around the text, 
the circle is the zoomed part of the cursor, taken with share X.
In this image the error state is launched by `required: True`.
![ShareX_MfusgeyTWM](https://user-images.githubusercontent.com/5509325/89765584-38362200-dabc-11ea-84bc-b217a5c91c19.png)
In this image the error state is launched by `max_text_length: 5`.
![ShareX_8kr9aCg4it](https://user-images.githubusercontent.com/5509325/89765572-33716e00-dabc-11ea-8460-5df48f01a447.png)

In this image the filling color is `[0, 0, 0, 1]` text `"asd"`
![ShareX_CZx6Rgrsf5](https://user-images.githubusercontent.com/5509325/89769171-530b9500-dac2-11ea-9ac2-b104e05c3da5.png)
In this image the filling color is `[0, 0, 0, 0.4]` text `"asd"`
![ShareX_QIhZWWrDYe](https://user-images.githubusercontent.com/5509325/89769287-7cc4bc00-dac2-11ea-8b55-d2f626a55242.png)

In this image you can see that every TextField is not on focus, yet the color of the text is different from a normal color.
![python_gZp7RhB2q9](https://user-images.githubusercontent.com/5509325/89770695-be566680-dac4-11ea-9ffd-e6b3aef01687.png)

In this image, you can see that the box is on primary color instead of a semi transparent shade of gray (ideally `[0,0,0,0.2]`)
![python_tTNl3tReXH](https://user-images.githubusercontent.com/5509325/89770965-29a03880-dac5-11ea-8e5f-abeb04c87f46.png)

In this image the widget is on focus
![python_AqJjYbRCRA](https://user-images.githubusercontent.com/5509325/89770980-2e64ec80-dac5-11ea-996e-40b126eb373c.png)

In this image the widget is not on focus, and the box is not turning gray
![python_ZSbchlpX85](https://user-images.githubusercontent.com/5509325/89770976-2c9b2900-dac5-11ea-9cda-ae48a98d15bb.png)

Without enough padding, the Graphic instructions overlap everything else around them.
![ShareX_Q7RvMcg038](https://user-images.githubusercontent.com/5509325/89771412-e2ff0e00-dac5-11ea-8571-5c289f7ea028.png)

### Versions

* OS:  Windows 10 rev 1909
* Python:  3.7
* Kivy: 1.11.1
* KivyMD:  master branch

**Comment by podraco** [comment]
the #520 doesn't fix everything listed here. Only the animation part.

**Comment by HeaTTheatR** [comment]
```python
from kivy.lang import Builder

from kivymd.app import MDApp


KV = '''
MDScreen:

    MDTextField:
        mode: "rectangle"
        hint_text: 'Field with left and right icons'
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint_x: .5

'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

> The rectangle of MDTextField when mode: "rectangle" is not changing color when unfocused or on_focus.
As the point before, this will mislead the end-user to believe that they had selected a text field not on focus:

Fixed - https://github.com/kivymd/KivyMD/commit/db96907e11dc0981e0011e20e2fa411a9d066132


https://user-images.githubusercontent.com/16930280/104105584-3b7a4780-52c0-11eb-9f06-c643d85271f3.mov
