### ISSUE TITLE
MDDialog/create_items fails for non-Avatar ListItems

### ISSUE THREAD

**Issue by michaelu123** [kivymd/KivyMD#451]
An MDDialog with items of class OneLineListItem fails in dialog.py/create_items(). The call edit_padding_for_item does not find attributes _left_container and _txt_left_pad, these exist only for AvatarListItems.

**Comment by HeaTTheatR** [comment]
@michaelu123 Please show me your code that is causing the error.

**Comment by wasimafser** [comment]
@HeaTTheatR I created the PR #303 for this very reason.

**Comment by michaelu123** [comment]
Hi,
this is my code:

class SelectItem(OneLineListItem):
   def __init__(self, arbExcel, text):
        super().__init__(text=text)

class ArbExcel:
    def readExcelSheet():
     …

self.dialog = MDDialog(
    title="Choose sheet",
    type="simple",
    items=[SelectItem(self, t) for t in sheetnames],
)
self.dialog.open()


As a workaround, I put the call of edit_padding_for_item into a try-except-clause:
dialog.py, line 553:


def create_items(self):
    self.ids.container.remove_widget(self.ids.text)
    height = 0

    for item in self.items:
        if issubclass(item.__class__, BaseListItem):
            height += item.height  # calculate height contents
            try: #MUH
                self.edit_padding_for_item(item)
            except:
                pass
            self.ids.box_items.add_widget(item)

    if height > Window.height:
        self.set_normal_height()
        self.ids.scroll.height = self.get_normal_height()
    else:
        self.ids.scroll.height = height





because, in edit_padding_for_item, there is no ids._left_container in an instance_item of type OneLineListItem:



def edit_padding_for_item(self, instance_item):
    instance_item.ids._left_container.x = 0
    instance_item._txt_left_pad = "56dp"

**Comment by HeaTTheatR** [comment]
This issue is closed because the author did not provide a sufficient description of his problem and code that can demonstrate this problem.
