### ISSUE TITLE
Example code for MDDialog is missing a class 

### ISSUE THREAD

**Issue by michaelu123** [kivymd/KivyMD#453]
The example code for MDDialog seems to be missing a definition of CheckBoxRightWidget (contained in dialog.py, Line 342), or CheckBoxLeftWidget (contained in https://kivymd.readthedocs.io/en/latest/components/dialog/index.html ).

**Comment by HeaTTheatR** [comment]
@michaelu123 This was fixed a long time ago in the master branch.
