### ISSUE TITLE
Add option for icon in MDFlatButton.

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#454]
### Description of the Feature

I would like to see the option to have an icon at **MDFlatButton**. I tried using **MDRectangleFlatIconButton** but it has the border which doesn't have an option for disabling it.

**Comment by HeaTTheatR** [comment]
@BananaMasterz 
```python
from kivy.uix.screenmanager import Screen

from kivymd.app import MDApp
from kivymd.uix.button import MDRectangleFlatIconButton


class Example(MDApp):
    def build(self):
        screen = Screen()
        screen.add_widget(
            MDRectangleFlatIconButton(
                text="MDRectangleFlatIconButton",
                icon="language-python",
                line_color=(0, 0, 0, 0),
                pos_hint={"center_x": .5, "center_y": .5},
            )
        )
        return screen


Example().run()
```

https://github.com/kivymd/KivyMD/commit/970de13cc11e69a2d1361246e4f79cfc477d957e

**Comment by BananaMasterz** [comment]
> @BananaMasterz
> 
> ```python
> from kivy.uix.screenmanager import Screen
> 
> from kivymd.app import MDApp
> from kivymd.uix.button import MDRectangleFlatIconButton
> 
> 
> class Example(MDApp):
>     def build(self):
>         screen = Screen()
>         screen.add_widget(
>             MDRectangleFlatIconButton(
>                 text="MDRectangleFlatIconButton",
>                 icon="language-python",
>                 line_color=(0, 0, 0, 0),
>                 pos_hint={"center_x": .5, "center_y": .5},
>             )
>         )
>         return screen
> 
> 
> Example().run()
> ```
> 
> [970de13](https://github.com/kivymd/KivyMD/commit/970de13cc11e69a2d1361246e4f79cfc477d957e)

Amazing! Thanks!
