### ISSUE TITLE
Please Release KivyMD Studio

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#456]
Please release KivyMD Studio 🙏🙏🙏

**Comment by podraco** [comment]
that's a different project. not KivyMD

**Comment by kulothunganug** [comment]
which project...?
that is also related to kivymd

**Comment by podraco** [comment]
Kivymd studio is an app that builds with kivymd. Not the other way. Because of that, this repo is only to report bugs, and some improvements to the kivymd library
Feel free to use the discord server of kivymd, if you have any request or need any help with your code.
