### ISSUE TITLE
In list.py CheckboxRightWidget instead of CheckboxLeftWidget 

### ISSUE THREAD

**Issue by DJBrause** [kivymd/KivyMD#462]
Possibly related to https://github.com/kivymd/KivyMD/issues/453

As per list.py, line 991:
```
class CheckboxRightWidget(ILeftBodyTouch, MDCheckbox):
    pass
```
I assume this is an error and CheckboxLeftWidget was named CheckboxRightWidget by mistake. At any rate, this causes the checkbox to appear on the left, rather than on the right side.

### Versions

* OS: Windows 10
* Python:  3.8
* Kivy: 2.0.0rc3
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@DJBrause This was fixed a long time ago in the master branch.
