### ISSUE TITLE
Blur in MDDialog

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#466]
### Description of the Feature

It would be nice if there was an option to have blur behind a dialog like in the picture below:

![image](https://user-images.githubusercontent.com/45745548/90542241-71415700-e18c-11ea-9df9-dd508a38a462.png)

**Comment by podraco** [comment]
it would need to take a picture of the background,
store it in memory and apply a x blur and a y blur, as seen in the kivymd russian article
something like:
```yaml
Launch_dialog_call:
  Take_background_picture
  Transform_background_picture:
    Apply_X_blur_effect
    Apply_Y_blur_effect
  Draw_background_picture, in the canvas.before
  Show_dialog
```

What do you think?

**Comment by BananaMasterz** [comment]
I don't think that's very elegant. I first thought of using the blur widget effect from kivy and applying it to the background of the modal view. I'm not sure how tho.

**Comment by HeaTTheatR** [comment]
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.dialog import MDDialog

KV = """
#:import Animation kivy.animation.Animation
#:import effect kivy.uix.effectwidget.EffectWidget
#:import HorizontalBlurEffect kivy.uix.effectwidget.HorizontalBlurEffect
#:import VerticalBlurEffect kivy.uix.effectwidget.VerticalBlurEffect


MDScreen:
    blur: 0

    EffectWidget:
        effects: (HorizontalBlurEffect(size=root.blur), VerticalBlurEffect(size=root.blur), )

        FitImage:
            source: "demos/kitchen_sink/assets/african-lion-951778_1280.png"
            
        MDRaisedButton:
            text: "TEST"
            pos_hint: {"center_x": .5, "center_y": .5}
            on_release:
                app.open_dialog()
                Animation(blur=8, d=0.3).start(root)
"""


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def open_dialog(self):
        self.dialog = MDDialog(text="Discard draft?")
        self.dialog.open()


Test().run()
```

**Comment by podraco** [comment]
https://stackoverflow.com/questions/54597761/how-to-convert-the-widget-into-a-image-file-in-kivy
if you capture the root widget wheres the dialog background is shown, then this is how it would look
use widget.export_to_png to get the image

**Comment by HeaTTheatR** [comment]
```python
from kivy.animation import Animation
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivy.uix.effectwidget import EffectWidget

from kivymd.app import MDApp
from kivymd.uix.dialog import MDDialog
from kivymd.uix.screen import MDScreen

Builder.load_string(
    """
#:import HorizontalBlurEffect kivy.uix.effectwidget.HorizontalBlurEffect
#:import VerticalBlurEffect kivy.uix.effectwidget.VerticalBlurEffect


<Content>
    FitImage:
        source: "demos/kitchen_sink/assets/african-lion-951778_1280.png"
        
    MDRaisedButton:
        text: "TEST"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.open_dialog()


<BlurManager>
    effects:
        (HorizontalBlurEffect(size=root.blur), VerticalBlurEffect(size=root.blur), )
"""
)


class BlurManager(EffectWidget):
    blur = NumericProperty(0)


class Content(MDScreen):
    def __init__(self, **kw):
        super().__init__(**kw)
        self.dialog = MDDialog(text="Discard draft?")
        self.dialog.bind(on_dismiss=self.dismiss_dialog)

    def dismiss_dialog(self, *args):
        Animation(blur=0, d=0.3).start(self.parent)

    def open_dialog(self):
        self.dialog.open()
        Animation(blur=8, d=0.3).start(self.parent)


class Test(MDApp):
    def build(self):
        content = Content()
        blur_manager = BlurManager()
        blur_manager.add_widget(content)
        return blur_manager


Test().run()
```

**Comment by HeaTTheatR** [comment]
@podraco Why take a screenshot of the screen? It's not practical.

**Comment by podraco** [comment]
Because it's a dialog box
and the Dialog box shows over the root widget.
To get the effect, you should be able to apply the effect to the background.

And it's easier if for the device to only apply the effect to a buffered image rather than every other element in the screen.

It's the most practical event you can get. So, you could be able to apply it to every screen. Without having to make multiple instances of effects, they're pretty much heavy to load

the idea is to have a self-contained widget that doesn't disturb the whole widget tree

**Comment by HeaTTheatR** [comment]
@podraco Chances are you are right, I don't see much of a problem implementing this anyway.

**Comment by podraco** [comment]
Ho, your solution it's quite elegant, but i think for the kivyMD purpose the object should be self-contained, and it must be the base of the self containded widget form
the first sotution you gave covers the basic behavior, and might as well be added as a behavior to any widget that shows over teh root. 
like the toogle button behavior, something similar.

**Comment by podraco** [comment]
The blur effect is not mentioned inside the material IO spec. Should we still consider this as an enhancement to kivyMD?

**Comment by HeaTTheatR** [comment]
@podraco I think not. The blur effect can be added on its own if needed. It should not be part of the API of the KivyMD library.

**Comment by podraco** [comment]
Then this issue should be closed, do you agree?
