### ISSUE TITLE
NavigationLayout does not accept toolbar

### ISSUE THREAD

**Issue by rubengerad** [kivymd/KivyMD#468]
### Description of the Bug

In Kivy it is possible to use a common toolbar header in NavigationLayout. In kivyMD I had to repeat adding toolbar in every Screen as the layout only supports ScreenManager & NavigationDrawer.  Same applies for any footer widgets.

**Comment by HeaTTheatR** [comment]
@rubengerad https://kivymd.readthedocs.io/en/latest/components/navigation-drawer/index.html#switching-screens-in-the-screenmanager-and-using-the-common-mdtoolbar
