### ISSUE TITLE
Toolbar font & size

### ISSUE THREAD

**Issue by rubengerad** [kivymd/KivyMD#469]
### Description of the Bug

The MDToolbar widget does not allow changing font style or font size.

**Comment by HeaTTheatR** [comment]
@rubengerad
```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        id: toolbar
        title: "MDToolbar"

    MDLabel:
        text: "Content"
        halign: "center"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.toolbar.ids.label_title.font_style = "Button"


Test().run()```

**Comment by rubengerad** [comment]
The given solution seems incorrect and unable to affect any change to
Toolbar font family, font style or font size.

KV file



#:set default_font_size "16sp" # Using kivy method to set a default size

MDToolbar:
    id:dashtoolbar
    title: 'Dashboard'
    pos_hint: {'top':.87}
    # label_title:  # does not have font_style settable attribute
    font_style:'Custom'
    font_name: 'resources/fonts/Pacifico-Regular'
    height:'50dp'
    font_size: default_font_size # Tried kivy method for global
default size but does not work.


App.py


Builder.load_string(dashboard_layout)

def on_start(self):
    self.root.ids.dashtoolbar.ids.label_title.font_style = 'Button'


#AttributeError: 'NoneType' object has no attribute 'ids'

*The MDToolbar attributes do not support any changes to font, style or
size, making it difficult to work with.  Hoping for a bugfix release
soon.*

Please be advised that all the code changes have been implemented
here, the purpose of the project is to create a blueprint for my team
to follow and set some common standards for future projects.

https://github.com/rubengerad/kivymd-blueprint

Thanks for the navigationlayout link Yuri, it worked.

**Comment by HeaTTheatR** [comment]
@rubengerad https://github.com/rubengerad/kivymd-blueprint - bad decision!

**Comment by nishanth123kgr** [comment]
That worked thank you bro
