### ISSUE TITLE
Accordionlistitem - change avatar to iconbutton and create an action

### ISSUE THREAD

**Issue by mathe1s** [kivymd/KivyMD#47]
Hello, 
In the file accordionlistitem.py

I changed AvatarLeft from:
class AvatarLeft(ILeftBody, Image):
     pass
to:
class AvatarLeft(ILeftBodyTouch, MDIconButton):
    source = StringProperty()

And the result was a black circle icon in the left of each MDAccordionListItem (look at the picture)

How can I program an action 'on_release' to use in my application using this button? and also change the icon.

Thanks in advance!

![image](https://user-images.githubusercontent.com/31517078/57151390-348afa00-6da7-11e9-9eba-2cd3d3be83ad.png)

**Comment by HeaTTheatR** [comment]
@mathe1s View your code.
