### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by rubengerad** [kivymd/KivyMD#471]
It would be great if you can modify the deprecated Builder.template feature to load a dictionary of keys to replace the .KV UI with different language options so based on locale the correct dictionay can be substituted for keywords.

Builder.template(Kvfile, dictionary ...)

**Comment by podraco** [comment]
That would be too expensive (time consuming) and it's a feature thats deprecated, since you can call load_file and unload_file from Builder

also, that request should be in the kivy repo, not kivymd
