### ISSUE TITLE
MDTextField: the last character is not displayed.

### ISSUE THREAD

**Issue by openedhardware** [kivymd/KivyMD#476]
### Description of the Bug
If I input many characters to the MDTextField widget, the last character is hidden and cannot see the cursor.

### Code and Logs

```python
from kivymd.uix.textfield import MDTextField
from kivy.uix.widget import Widget
from kivy.uix.boxlayout import BoxLayout
from kivymd.app import MDApp


class TestApp(MDApp):
    txt = None

    def build(self):
        box = BoxLayout(orientation="vertical", padding=100, spacing=10)
        box.add_widget(Widget())
        txt = MDTextField(size_hint_x=.3)
        txt.font_size = 40
        box.add_widget(txt)
        box.add_widget(Widget())
        return box


TestApp().run()

```

### Screenshots

![ice_video_20200821-053418](https://user-images.githubusercontent.com/16890683/90828503-b2925c00-e370-11ea-9cda-143a5a577d9a.gif)

### Versions

* OS: Windows/Ubuntu18.04
* Python: 3.7 64bit
* Kivy: 1.11.1
* KivyMD: latest(master branch)

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/274
