### ISSUE TITLE
How to dynamically change MDDataTable values

### ISSUE THREAD

**Issue by icarus-0** [kivymd/KivyMD#483]
```python

from kivy.metrics import dp
from kivy.clock import Clock
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.lang import Builder
from kivy.core.window import Window
Window.size = (1920, 1080)
KV = '''

FloatLayout:
    MDRaisedButton:
        text: "Strategies Using Date Only"
        pos_hint: {'center_x': .5, 'center_y': .10}
        on_release : app.create_table()
        elevation: 12

    MDCard:
        id: card   
        size_hint: None, None
        size: "1000dp", "1000dp"
        pos_hint: {"center_x": .5, "center_y": .8}
        ripple_behavior: True
        elevation: 12


'''


class Example(MDApp):
    r_data = [('3100','20.5')]
    c_data = [('Strike Price',dp(30)),('Price',dp(30))]
    i = 0
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        Clock.schedule_interval(self.update_table,0.5)
        

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    
    
    def create_table(self):
        self.data_tables = MDDataTable(
            id = 'table',
            size_hint=(0.9, 0.6),
            use_pagination=True,
            check=True,
            column_data=self.c_data,
            row_data=self.r_data,
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        self.root.ids.card.add_widget(self.data_tables)
    
    def update_table(self, *args):
        
        self.r_data = [(str(3100+self.i),str(20.5+self.i))]
        self.i += 1
        try:
            self.root.ids.card.clear_widgets()
            self.create_table()
        except:
            pass

        

Example().run()

```

I am using this code to change row values of Datatable but I am not able to checkmark the row , Is there is another way to do this?

**Comment by icarus-0** [comment]
@ArtemSBulgakov please help me with this problem

**Comment by icarus-0** [comment]
@HeaTTheatR help me please

**Comment by HeaTTheatR** [comment]
@naman-echo Your code example displays an empty table. Also, why are you setting the app screen size in the example? Someone testing your code might have a small monitor.

**Comment by icarus-0** [comment]
@HeaTTheatR i am making this app for my laptop thats why i am setting the screen size..
can you please give me a code in which the MDDatable value is changing in runtime

**Comment by icarus-0** [comment]
@HeaTTheatR thanks in advance

**Comment by HeaTTheatR** [comment]
@naman-echo There is no API for dynamically changing table rows yet. I can advise you to adopt a new `row_data` -  https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables.py#L760 dictionary every time you want to change something in the table.

**Comment by naman-echo** [comment]
from kivy.metrics import dp
from kivy.clock import Clock
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.lang import Builder
from kivy.core.window import Window
Window.size = (1920, 1080)
from kivy.properties import ObjectProperty
from kivy.uix.widget import Widget


class EAT(MDApp):
    r_call_data = [('3100','20.5')]
    c_call_data = [('Strike Price',dp(40)),('Price',dp(30))]

    r_put_data = [('3100','20.5')]
    c_put_data = [('Strike Price',dp(40)),('Price',dp(30))]
    i = 0

    
    def on_start(self):
        try:
            Clock.schedule_interval(self.update_table,1.5)
            self.create_table()
        except:
            pass

    def on_row_press_call(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''
        try:
            print(instance_table, instance_row)
        except:
            pass

    def on_check_press_call(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''
        try:
            print(instance_table, current_row)
        except:
            pass

    def on_row_press_put(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''
        try:
            print(instance_table, instance_row)
        except:
            pass

    def on_check_press_put(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''
        try:
            print(instance_table, current_row)
        except:
            pass
    
    
    def create_table(self):
        try:
            self.data_tables_call = MDDataTable(
                                    id = 'call_table',
                                    size_hint=(0.9, 0.6),
                                    use_pagination=True,
                                    check = True,
                                    column_data=self.c_call_data,
                                    row_data=self.r_call_data,
                                    )
            
            self.data_tables_call.bind(on_row_press=self.on_row_press_call)
            self.data_tables_call.bind(on_check_press=self.on_check_press_call)
            self.root.ids.call_values.add_widget(self.data_tables_call)

            self.data_tables_put = MDDataTable(
                                    id = 'put_table',
                                    size_hint=(0.9,0.6),
                                    use_pagination= True,
                                    check=True,
                                    column_data=self.c_put_data,
                                    row_data= self.r_put_data,
                                    )

            self.data_tables_put.bind(on_row_press=self.on_row_press_put)
            self.data_tables_put.bind(on_check_press=self.on_check_press_put)
            self.root.ids.put_values.add_widget(self.data_tables_put)
        
        except:
            pass
        
    def update_table(self, *args):
        
        self.r_call_data = [(str(3100+self.i),str(20.5+self.i))]
        self.r_put_data = [(str(3100+self.i),str(20.5+self.i))]
        self.i += 1
        if True:
            if self.i%4 == 0:
                self.root.ids.delta.text_color = (1,0,0,1)    
            else:
                self.root.ids.delta.text_color = (0.0745098039,0.1725490196,0.431372549,1)
                

            self.root.ids.delta.text = str(self.i)
            #print(self.data_tables_call)
            print('A')
            
            self.root.ids.call_table.row_data = self.r_call_data
            
        else:
            pass

        

EAT().run()

**Comment by icarus-0** [comment]
```python
from kivy.metrics import dp
from kivy.clock import Clock
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.lang import Builder
from kivy.core.window import Window
Window.size = (1920, 1080)
from kivy.properties import ObjectProperty
from kivy.uix.widget import Widget


class EAT(MDApp):
    r_call_data = [('3100','20.5')]
    c_call_data = [('Strike Price',dp(40)),('Price',dp(30))]

    r_put_data = [('3100','20.5')]
    c_put_data = [('Strike Price',dp(40)),('Price',dp(30))]
    i = 0

    
    def on_start(self):
        try:
            Clock.schedule_interval(self.update_table,1.5)
            self.create_table()
        except:
            pass

    def on_row_press_call(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''
        try:
            print(instance_table, instance_row)
        except:
            pass

    def on_check_press_call(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''
        try:
            print(instance_table, current_row)
        except:
            pass

    
    
    
    def create_table(self):
        try:
            self.data_tables_call = MDDataTable(
                                    id = 'call_table',
                                    size_hint=(0.9, 0.6),
                                    use_pagination=True,
                                    check = True,
                                    column_data=self.c_call_data,
                                    row_data=self.r_call_data,
                                    )
            
            self.data_tables_call.bind(on_row_press=self.on_row_press_call)
            self.data_tables_call.bind(on_check_press=self.on_check_press_call)
            self.root.ids.call_values.add_widget(self.data_tables_call)

            
        
        except:
            pass
        
    def update_table(self, *args):
        
        self.r_call_data = [(str(3100+self.i),str(20.5+self.i))]
        self.r_put_data = [(str(3100+self.i),str(20.5+self.i))]
        self.i += 1
        if True:
            if self.i%4 == 0:
                self.root.ids.delta.text_color = (1,0,0,1)    
            else:
                self.root.ids.delta.text_color = (0.0745098039,0.1725490196,0.431372549,1)
                

            self.root.ids.delta.text = str(self.i)
            self.data_tables_call.row_data = self.r_call_data
            print('A')
            
            
        else:
            pass

        

EAT().run()
```

**Comment by icarus-0** [comment]
@HeaTTheatR i am using this code but it's not reflecting on the screen

**Comment by icarus-0** [comment]
![Screenshot from 2020-08-23 22-44-13](https://user-images.githubusercontent.com/46519285/90985588-a0940180-e59a-11ea-85e9-92f0ceb1e6df.png)

**Comment by icarus-0** [comment]
@HeaTTheatR the app is looks like this but i want to change the stike price values in run time

**Comment by HeaTTheatR** [comment]
@naman-echo I have already answered this question.

**Comment by icarus-0** [comment]
@HeaTTheatR sorry if I am disturbing you , but really I didn't get it . Can you please give me a example code in which the row_data is changing . It will really help me . I really need to complete this project and I tried everything. Please help

**Comment by HeaTTheatR** [comment]
@naman-echo 
```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        self.set_table(
            [
                (f"{i + 1}", "2.23", "3.65", "44.1", "0.45", "62.5")
                for i in range(50)
            ]
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)

    def set_table(self, data):
        self.data_tables = MDDataTable(
            size_hint=(0.9, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(30)),
                ("Column 2", dp(30)),
                ("Column 3", dp(30)),
                ("Column 4", dp(30)),
                ("Column 5", dp(30)),
            ],
            row_data=data,
        )

    def on_start(self):
        self.data_tables.open()

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        self.data_tables.dismiss()
        self.set_table(
            [
                (f"{i + 1}", "0", "0", "0", "0", "0")
                for i in range(50)
            ]
        )
        self.data_tables.open()

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)


Example().run()
```

There is no API for dynamically changing table rows yet.

**Comment by icarus-0** [comment]
@HeaTTheatR thank you so much for your help

**Comment by icarus-0** [comment]
@HeaTTheatR Sorry to disturb you agian but i am getting a error in kivymd

XXX: resource creation failed

when my code continuously changing the table values i got that error

**Comment by icarus-0** [comment]
![Screenshot from 2020-08-24 13-33-52](https://user-images.githubusercontent.com/46519285/91019345-7aa84480-e60e-11ea-9ed2-7cb71595c1ec.png)

**Comment by icarus-0** [comment]
XXX: resource creation failed
XXX: resource creation failed
XXX: resource creation failed
XXX: resource creation failed
XXX: resource creation failed
Segmentation fault (core dumped)


@HeaTTheatR how can i solve this after some iteration code is crashed and i got this error

**Comment by Rhtyme** [comment]
@dastaan-0 if you want something advanced, move to flutter

**Comment by charlie2clarke** [comment]
@HeaTTheatR I just tried using your previous solution, however, it only seems to update the table when using .open() and when using this function you do not have control over where on the screen it is placed. I've also tried removing and re-adding the widget but seems to have no effect. Any work arounds you can think of?

**Comment by charlie2clarke** [comment]
Ah well I overlooked the use of pos_hint to place the data table as a pop-up, but when it opens as a pop-up the rest of the screen is disabled.

**Comment by HeaTTheatR** [comment]
@charlie2clarke The `MDDataTable` class does not have a `open` method. You are using a deprecated API...

**Comment by HeaTTheatR** [comment]
@icarus-0
### Add/Remove rows
```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.button import MDRaisedButton


class Example(MDApp):
    data_tables = None

    def build(self):
        layout = MDFloatLayout()  # root layout
        # Creating control buttons.
        button_box = MDBoxLayout(
            pos_hint={"center_x": 0.5},
            adaptive_size=True,
            padding="24dp",
            spacing="24dp",
        )

        for button_text in ["Add row", "Remove row"]:
            button_box.add_widget(
                MDRaisedButton(
                    text=button_text, on_release=self.on_button_press
                )
            )

        # Create a table.
        self.data_tables = MDDataTable(
            pos_hint={"center_y": 0.5, "center_x": 0.5},
            size_hint=(0.9, 0.6),
            use_pagination=False,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(40)),
                ("Column 2", dp(40)),
                ("Column 3", dp(40)),
            ],
            row_data=[("1", "1", "2", "3")],
        )
        # Adding a table and buttons to the toot layout.
        layout.add_widget(self.data_tables)
        layout.add_widget(button_box)

        return layout

    def on_button_press(self, instance_button: MDRaisedButton) -> None:
        """Called when a control button is clicked."""

        try:
            {
                "Add row": self.add_row, "Remove row": self.remove_row,
            }[instance_button.text]()
        except KeyError:
            pass

    def add_row(self) -> None:
        last_num_row = int(self.data_tables.row_data[-1][0])
        self.data_tables.add_row((str(last_num_row + 1), "1", "2", "3"))

    def remove_row(self) -> None:
        if len(self.data_tables.row_data) > 1:
            self.data_tables.remove_row(self.data_tables.row_data[-1])


Example().run()
```
![data-tables-add-remove-row](https://user-images.githubusercontent.com/16930280/157718095-c47cef27-39e4-4bc8-952f-2d16e86e665e.gif)

### Change row
```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.button import MDRaisedButton


class Example(MDApp):
    data_tables = None

    def build(self):
        layout = MDFloatLayout()
        layout.add_widget(
            MDRaisedButton(
                text="Change 2 row",
                pos_hint={"center_x": 0.5},
                on_release=self.change_row,
                y=24,
            )
        )
        self.data_tables = MDDataTable(
            pos_hint={"center_y": 0.5, "center_x": 0.5},
            size_hint=(0.9, 0.6),
            use_pagination=False,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(40)),
                ("Column 2", dp(40)),
                ("Column 3", dp(40)),
            ],
            row_data=[(f"{i + 1}", "1", "2", "3") for i in range(3)],
        )
        layout.add_widget(self.data_tables)

        return layout

    def change_row(self, instance_button: MDRaisedButton) -> None:
        updated_second_row_data = ["2", "A", "B", "C"]
        self.data_tables.row_data[1] = updated_second_row_data


Example().run()
```
![data-tables-change-row](https://user-images.githubusercontent.com/16930280/157719034-fc84abbf-0ab7-4182-82c4-8d571fdb43b1.gif)

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/850
