### ISSUE TITLE
Speedometer example?

### ISSUE THREAD

**Issue by beyonlo** [kivymd/KivyMD#490]
Hello, nice work!

Please, could you to create a simple Speedometer example to start?

Thank you.

**Comment by ArtemSBulgakov** [comment]
Hi. This is the Kivy question, not KivyMD, so you should ask in Kivy Issues or Discord server.
I think you want to draw a circle outline with start and end angles. You can use canvas with [Line](https://kivy.org/doc/stable/api-kivy.graphics.vertex_instructions.html#kivy.graphics.vertex_instructions.Line.circle] for this purpose.
