### ISSUE TITLE
MDCards in Dark Mode lose their radius.

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#492]
### Description of the Bug

Whenever I switch from light to dark and vice versa, the radius of the MDCards becomes zero.
In the first pic it's the way it should be, and then I click dark mode the radius goes away as seen in the second picture.

### Screenshots

![image](https://user-images.githubusercontent.com/45745548/91347489-1db5b580-e7eb-11ea-830d-e4299a6bb397.png)

![image](https://user-images.githubusercontent.com/45745548/91347581-3de57480-e7eb-11ea-98ac-fdbaaad9b687.png)

This is the dropdown Item from kitchen sink if you want to recreate the problem but it works with any MDCard.

**Comment by Kulothungan16** [comment]
your issue has been fixed https://github.com/kivymd/KivyMD/commit/fa299ed0e5b3b21944dbebb5186291bfac8b7509

**Comment by HeaTTheatR** [comment]
@BananaMasterz This has been fixed in the master branch of the library. Try reinstalling KivyMD from the master branch
