### ISSUE TITLE
 AttributeError: 'ThemeManager' object has no attribute 'font_styles'

### ISSUE THREAD

**Issue by DaedlyKitten** [kivymd/KivyMD#496]
A ton of the widgets will cause this error when being loaded at first time..

there indeed doesnt seem to be a font_styles in the theming.py?

sorry if this is a very noobish question rather than a bug

**Comment by ArtemSBulgakov** [comment]
https://github.com/kivymd/KivyMD/blob/9f6ed12c229922711df2557dc0d941bb16c04a57/kivymd/theming.py#L794-L811

**Comment by ArtemSBulgakov** [comment]
@DaedlyKitten Please say your KivyMD version

**Comment by DaedlyKitten** [comment]
I installed with  'git clone https://gitlab.com/kivymd/KivyMD.git' and setup.py

while running it gives:
`[INFO   ] [KivyMD      ] KivyMD version: 0.1.2
`
and retrying with pip install kivymd==0.104.1, it gives:
`Requirement already satisfied: kivymd==0.104.1 in d:\2\python37\lib\site-packages (0.104.1)`


I also had to manually add 'palette' in the color_definitions.py, then copy paste from 'Grey' to add item 'Gray' as errors for them were met,
maybe its problem with the versions for windows?

@ArtemSBulgakov

**Comment by ArtemSBulgakov** [comment]
@DaedlyKitten Don't use KivyMD from GitLab. Install only via `pip install kivymd` (as described in [Readme on GitHub](https://github.com/kivymd/KivyMD#installation)). KivyMD runs normally on Windows.
Try `pip install --force-reinstall kivymd` to reinstall KivyMD.
All examples from [documentation](https://kivymd.readthedocs.io/) should work without errors.

**Comment by DaedlyKitten** [comment]
Thanks!! 👍 👍 👍
