### ISSUE TITLE
There's a strange bug with the isort hook in precommit

### ISSUE THREAD

**Issue by podraco** [kivymd/KivyMD#504]
### Description of the Bug
<img src="https://user-images.githubusercontent.com/5509325/92063987-17cb5180-ed62-11ea-99bc-216c15da2695.jpg" width="45" height="35"> Isort hook presents a strange behavior, being unable to complete it's work when there's a comment between the imports. And there's no space between imports and comments.

The error message doesn't correspond to the actual problem, thus hiding the bug's true root cause.

#### Failing file examples :

1. example 

```py
from kivy.graphics.vertex_instructions import Ellipse, RoundedRectangle
from kivy.lang import Builder
# Eliminar

from kivy.logger import Logger
from kivy.metrics import dp, sp
```

2. example 

```py
from kivy.graphics.vertex_instructions import Ellipse, RoundedRectangle
from kivy.lang import Builder

# Eliminar
from kivy.logger import Logger
from kivy.metrics import dp, sp
```

3. example 

```py
from kivy.graphics.vertex_instructions import Ellipse, RoundedRectangle
from kivy.lang import Builder
# Eliminar
from kivy.logger import Logger
from kivy.metrics import dp, sp
```
In examples 1 and 2 the isort hook is able to change the file and after another run or two the error disappears, but, with example 3, isort cannot move the comments from the imports correctly and gets stuck in that position.

This behavior only appears while using the precommit hook and not when the stand-alone isort package is used with the file.

LOG of pre-commit in any case:
```python
isort....................................................................Failed
- hook id: isort
- files were modified by this hook
Fixing kivymd\uix\button.py
c:\users\manue\.cache\pre-commit\repopbml79aw\py_env-python3.7\lib\site-packages\setuptools\distutils_patch.py:27: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
```

The easiest solution: avoid placing comments between imports, even if it's for documentation or structure while using the isort hook. And placing a warning in the page on how to create a pull request, etc.

### Versions

* OS: WINDOWS 10 built 1909
* Python:  3.7
* Kivy: 1.11.x
* KivyMD: master

**Comment by HeaTTheatR** [comment]
Fix in master branch.
