### ISSUE TITLE
NavigationLayout doesn't shrink unless navigation drawer open

### ISSUE THREAD

**Issue by dwmoffatt** [kivymd/KivyMD#506]
### Description of the Bug

When using navigation layout with Navigation drawer. The screen will expanded but will not shrink unless the navigation drawer is open. 

There is a video showing the issue in the attached zip file.
[example.zip](https://github.com/kivymd/KivyMD/files/5178893/example.zip)

### Code and Logs

```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp

KV = '''
Screen:

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]
                        right_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Widget:


        MDNavigationDrawer:


            id: nav_drawer

            ContentNavigationDrawer:
'''


class ContentNavigationDrawer(BoxLayout):
    pass


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)


TestNavigationDrawer().run()
```

### Versions

* OS: Ubuntu 20.04
* Python: Python 3.8.2
* Kivy: 2.0.0rc3
* KivyMD: Master

**Comment by HeaTTheatR** [comment]
@dwmoffatt Yes, this is a bug. And, apparently it came with recent commits.

**Comment by dwmoffatt** [comment]
Sounds good. Look forward to having it fixed!

**Comment by dwmoffatt** [comment]
I have a fix for this issue. I am just trying to figure out how to download the environment so I can run the tests needed.

**Comment by dwmoffatt** [comment]
I have branched, run the code through Black and I have tested the functionality. When I go to push my commit to this repo I get this:

ERROR: Permission to kivymd/KivyMD.git denied to dwmoffatt.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can someone give me permissions?

**Comment by HeaTTheatR** [comment]
@dwmoffatt You don't need any special permissions to make a pull request. Just clone the library repository, commit your changes, and make a pull request.

**Comment by dwmoffatt** [comment]
@HeaTTheatR I am pushing my commit to the repo from my branch and I am getting the permission denied.

I have tried this to master as while and it is not working.

**Comment by dwmoffatt** [comment]
@HeaTTheatR Figured it out.

**Comment by HeaTTheatR** [comment]
Fix https://github.com/kivymd/KivyMD/pull/508
