### ISSUE TITLE
Adapative_width definition on BoxLayout, GridLayout, StackLayout incorrect

### ISSUE THREAD

**Issue by dwmoffatt** [kivymd/KivyMD#507]
### Description of the Bug

adaptive width definition is incorrect on BoxLayout, GridLayout, StackLayout

adaptive_width: True

Equivalent

size_hint_x: None
**height: self.minimum_width**

should be:
width: self.minimum_width

### Versions

* OS: Ubuntu 20.04
* Python: 3.8.2
* Kivy: 2.0.0rc3
* KivyMD: Master

**Comment by dwmoffatt** [comment]
I can fix it if you give me permissions to do so. I would like to contribute to this repo.

**Comment by HeaTTheatR** [comment]
@dwmoffatt https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/__init__.py#L48

**Comment by dwmoffatt** [comment]
Yeh I know that shows it as correct but when you look at the BoxLayout, GridLayout, StackLayout Docs it shows them as incorrect.

**Comment by HeaTTheatR** [comment]
@dwmoffatt Please describe your question in one message, attach a minimal code code that may be run without additional manipulations, so developers can look at the working script and fix it. Also write what you expect from the script and what happened wrong. If needed, attach links or screenshots to explain us what you want to do. Less words, more code.

**Comment by dwmoffatt** [comment]
![Screenshot from 2020-09-07 16-26-29](https://user-images.githubusercontent.com/52943347/92420250-267d8400-f127-11ea-9c1c-06be2722c8af.png)
![Screenshot from 2020-09-07 16-27-24](https://user-images.githubusercontent.com/52943347/92420254-28dfde00-f127-11ea-85d7-7ee7795bb3a9.png)
![Screenshot from 2020-09-07 16-27-35](https://user-images.githubusercontent.com/52943347/92420257-2aa9a180-f127-11ea-86d3-9f5bbd20d608.png)
 
Those are screenshots of the Docs for KivyMd you can see the adaptive width definition is incorrect on this page. Which I take it comes from the .py file since it looks like that is what these docs are generated on.
