### ISSUE TITLE
DataTable: refer to the row being pressed/current row with an id

### ISSUE THREAD

**Issue by DaedlyKitten** [kivymd/KivyMD#509]
So is there a way to get the row that's being pressed? like the row number, or a custom ID that's being assigned to a row that is not shwon on the table (which is much more convenient when implementing functions like filter, search, etc)

in the docs and example,

```
 def on_row_press(self, instance_table, instance_row):
         print(instance_table, instance_row,)
```

I only managed to get the exact concent of the cell being pressed/tapped with 'instance_row.text'
But how do I get the row that is being pressed/selected?

**Comment by HeaTTheatR** [comment]
@DaedlyKitten Yes, so far there are a lot of flaws in the MD DataTable. Hope this will be fixed soon.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables.py#L825
