### ISSUE TITLE
Add some options for widgets

### ISSUE THREAD

**Issue by Roma9o** [kivymd/KivyMD#510]
### Description of the Feature

It would be cool to add some options to widgets... 
1. For toast messege - option to change pop-up the y-direction.
[something like this](https://crcomcstorage.blob.core.windows.net/images/android_toast_center_screen.jpg)

2. Bottom navigation menu - is the font size in menu, and change icon font on custom

3. Making it possible to color a status bar is as easy as choosing a theme.

**Comment by HeaTTheatR** [comment]
1 - Fixed in master branch;

**Comment by HeaTTheatR** [comment]
2 - https://github.com/kivymd/KivyMD/blob/master/kivymd/utils/set_bars_colors.py
