### ISSUE TITLE
kivymd.uix.list.BaseListItem - Divider Documentation incorrect

### ISSUE THREAD

**Issue by dwmoffatt** [kivymd/KivyMD#512]
### Description of the Bug

divider

    Divider mode. Available options are: ‘Full’, ‘Inset’ and default to ‘Full’.

--->>>> incorrect:    tertiary_font_style is a OptionProperty and defaults to ‘Body1’.

* KivyMD: master

**Comment by HeaTTheatR** [comment]
@dwmoffatt Thanks, we will definitely fix this!

**Comment by dwmoffatt** [comment]
@HeaTTheatR no problem!
