### ISSUE TITLE
Data Table in kichen sink crashes the app when Scrolled on

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#514]
### Description of the Bug
Why does the data Table cause the app to crash when I scroll on it (I was about using it on my project when I just decided to test the one in kitchen sink)

### Code and Logs(Below is the final error Traceback I get)

```python
 File "kivy/weakproxy.pyx", line 299, in kivy.weakproxy.WeakProxy.__str__
 RecursionError: maximum recursion depth exceeded while getting the str of an object
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@kengoon Unfortunately, I was unable to reproduce the bug you are describing ...
![ezgif-7-f1e76f7f7d5e](https://user-images.githubusercontent.com/16930280/92726023-a9941980-f375-11ea-8658-052b32fdb3ee.gif)

**Comment by hemarle** [comment]
I also got the same error in my app. I couldn't even scroll down too

**Comment by HeaTTheatR** [comment]
@kengoon @hemarle To find out the cause of the error, you must first specify the specifications:
![Снимок экрана 2020-09-10 в 19 44 30](https://user-images.githubusercontent.com/16930280/92765658-3652cd80-f39e-11ea-8371-76fdc4bfc101.png)

You also need to attach a minimal example of code that reproduces the error you are describing. If the bug occurs on an Android device, attach the APK package for testing.

**Comment by hemarle** [comment]
My Version:
    OS: Windows 8
    Python: 3.7
    Kivy: 1.11.1
    KivyMD: 0.104.2

The py file:

```python
from kivymd.app import MDApp
from kivymd.uix.screen import Screen
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp


class MyApp(MDApp):
    def build(self):
        self.screen = Screen()
        data = MDDataTable(column_data=[('Column1', dp(30)), ('Column2', dp(30))],
                           row_data=[('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'),
                                     ('boy', 'girl'), ('boy', 'girl'), ('boy', 'girl'), ],
                           pos_hint={'center_x':0.5,'center_y':0.5},
                           rows_num=30

                           )
        self.screen.add_widget(data)
        return self.screen

MyApp().run()
```

![error](https://user-images.githubusercontent.com/43211279/92769848-47e1a880-f391-11ea-97e4-af9795293b1f.png)

**Comment by hemarle** [comment]
The indentation is actually correct, it got mumbled up when I copied and paste it. The code ran but crashed after I tried clicking (especially when double clicked) and I also can't scroll down

**Comment by HeaTTheatR** [comment]
@HeaTTheatR Your error is due to the `stiffscroll` module not working correctly in `Windows`.

**Comment by kengoon** [comment]
@HeaTTheatR 
OS: Parrot Security Linux
Python: 3.7.7
Kivy: 1.11.1
Kivymd: 1.104.2.dev


the code is the same as the one in the kitchen sink without any modification

**Comment by onodnawij** [comment]
@kengoon 
Updated my kivy 2.0.0rc3, and my code don't produce that error anymore.

**Comment by HeaTTheatR** [comment]
Updating `Kivy` to `2.0.0rc3`
