### ISSUE TITLE
can't bind function to a button

### ISSUE THREAD

**Issue by KurdishSage** [kivymd/KivyMD#522]
i'm generating multiple buttons,i want to bind each button on_release event and each button return a unique ID to the assigned function, here's my whole code:-

`class APP(MDApp):
    class MovieScreen(Screen):
        def on_enter(self, *args):
            pass

    def addMoreMovies(self, obj):
        print('imdbid')

    Config.set('graphics', 'width', '450')
    Config.set('graphics', 'height', '700')
    Config.write()

    def build(self):
        self.theme_cls = ThemeManager()
        self.theme_cls.primary_palette = "Green"
        self.theme_cls.theme_style = "Dark"
        screen = Builder.load_string(screen_helper)
        return screen

    def on_start(self):
        amountOfMovies = 10

        movies = getMovie(amountOfMovies)
        for i in range(len(movies[0])):
            image = movies[1][i]
            name = movies[0][i]
            imdbid = movies[2][i]
            tile=SmartTileWithLabel()
            tile.id=str(imdbid)
            tile.bind(on_release=self.addMoreMovies)
            tile.source=str(image)
            tile.text=str(name)
            tile.size=(182,268)
            tile.height='240dp'
            tile.size_hint_y=None
            self.root.ids.grid.add_widget(tile)`

the code kinda works, but all the buttons are returning the last assigned ID,

i realized that i have to change my code from

`tile.bind(on_release=lambda x: APP.addMoreMovies(self,imdbid=imdbid))`

to

`tile.bind(on_release=APP.addMoreMovies(self,imdbid=imdbid))`

so that each button instance it's own function. but when i run the code i get this following error:-

`File "kivy\_event.pyx", line 419, in kivy._event.EventDispatcher.bind
 AssertionError: None is not callable`
* OS: Windows 10
* Python: 3.6
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@KurdishSage 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.imagelist import SmartTileWithLabel

KV = '''
ScrollView:

    MDGridLayout:
        id: box
        cols: 3
        adaptive_height: True
        padding: dp(4), dp(4)
        spacing: dp(4)

'''


class MyApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for i in range(3):
            self.root.ids.box.add_widget(
                SmartTileWithLabel(
                    size_hint_y=None,
                    height="240dp",
                    source="cat.png",
                    text=f"[size=26]Cat {i}[/size]\n[size=14]cat-{i}.jpg[/size]",
                    on_release=self.tap_on_tile,
                )
            )

    def tap_on_tile(self, *args):
        print(args)


MyApp().run()
```
