### ISSUE TITLE
What i want to do if i use more screens?

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#526]
### Description

#511 

if i use more screens what i want to do
pls illustrate with example... 🙏🏽

**Comment by podraco** [comment]
### Remember this channel it's only for kivymd related issues and improvements.
This is a kivy question, please don't spam those here.

If you want to use multiple screens use ScreenManager
read more at the kivy documentation
https://kivy.org/doc/stable/api-kivy.uix.screenmanager.html

**Comment by kulothunganug** [comment]
i need to use drop drop down for a project 
sry @podraco

**Comment by podraco** [comment]
I'm sorry, but i don't understand your question.
You should ask in the kivy's discord server for kivy related questions

**Comment by podraco** [comment]
https://kivy.org/doc/stable/api-kivy.uix.dropdown.html

**Comment by kulothunganug** [comment]
i want to use a drop down menu but it telling __getatr__
and @HeaTTheatR telled me
```
Never use an application architecture where the KV file is automatically searched for in the home directory. This is a very bad practice. I am closing your question because it is not related to the KivyMD library. In the code that I attached above, you can see that your code works fine.
```
see  #511 to have more clearence

but i have using more screen want i have to do now

**Comment by podraco** [comment]
### Kivy MD is a set of widgets that comply with Google's Material Design.
it rely completely on the **kivy** framework project.

**For you to use KivyMD you need to learn Kivy First.**
There's a lot of documentation that might help you in kivy's site

for what i read you need to learn the following:

#### -1. What's the main difference between a open source code project and a privative one?
**answer**: you are free to read the code and see in file examples and documentation: propose improvements and bug fixes as well.

0. What's Kivy and what's KivyMD and it's differences
1. how to use kivy (a simple app)
2. whats a kivy's widget object
3. What0s a kivy property?
4. what's a Layout
5. What's a Screen
6. How do the Screen Manager Works
7. What's kv lang
8. What's the difference between KV lang and python instances
9. What's the kivy's Clock? (kivy.clock.Clock)
10. What's an Event?
11. How do Screens Work
12. How add a reference to an ID in kv Lang
13. What's `widget.__self__` do in kv lang and why should i look up for it?
14. How do i create screens in dynamically and register them to the screen manager
15. how do the kivy's DropdownMenu works?
16. is there any difference between kivy's DropdownMenu  and kivymd MDDropdownMenu 


### This channel is only to report bugs and improvements ideas that are related with kviyMD.

I may ask you to check the kivy discord server, where you may find people with more experience that may guide and teach you the basics

Here's the discord chatroom of the kivy framework.
https://chat.kivy.org

i may also advise you that there are some books available that might help you thought your learning curve. They helped me.
https://www.oreilly.com/library/view/creating-apps-in/9781491947333/ch01.html
https://www.amazon.com/-/es/Roberto-Ulloa/dp/1783281596

**Comment by kulothunganug** [comment]
thx for ur brief reply ☺️
