### ISSUE TITLE
kivymd button icon not showing 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#529]
### Description code
from kivymd.app import MDApp
from kivymd.uix.button import*
from kivymd.uix.card import*
from kivymd.uix.boxlayout import*
from kivymd.uix.screen import*
from kivy.lang import*
from plyer import*

Builder.load_file('main.kv')

class Main(MDScreen):

	def choose(self):
		filechooser.open()

class MyApp(MDApp):
	def build(self):
		return Main()

MyApp().run()

##main.kv

1. > <Main>:
2. > 	BoxLayout:
3. > 		orientation: 'vertical'
4. > 		MDToolbar:
5. > 			title: 'hello'
6. > 		Widget: 
7. > 		MDBottomAppBar:
8. > 			MDToolbar:
9. > 				title: 'hello'
10. > 				type: "bottom"
11. > 				icon: "git"
12. > 				mode: "end"
13. > 
14. 
15. 

### Versions

* OS: kubuntu 18.04
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.2.dev0,

**Comment by HeaTTheatR** [comment]
@Sahil-pixel https://github.com/kivymd/KivyMD/issues/257

**Comment by Sahil-pixel** [comment]
but 0.104.1 version of Kivymd working fine button icon ..but master version has this problem ...

**Comment by Sahil-pixel** [comment]
sir i am running on kubuntu 18.04
see #505

**Comment by HeaTTheatR** [comment]
@Sahil-pixel Please edit your issue. Because it is difficult for me and other people to understand what your problem is.

**Comment by Sahil-pixel** [comment]
please see

**Comment by podraco** [comment]
This bug report has no start nor end,

I may ask you to reformulate the report to know exactly what are you talking about

### Until then, this thread will be closed.
