### ISSUE TITLE
Non-ASCII character '\xc3' in file declaration needed for each file

### ISSUE THREAD

**Issue by surbhicis** [kivymd/KivyMD#53]

**Comment by ArtemSBulgakov** [comment]
KivyMD supports only Python3.

**Comment by surbhicis** [comment]
@Mountaino So why you people are not maintaining different branches or tags for kivymd for python 2 as well ,as previously my build was made with support of python2 and in that case it will broke

**Comment by ArtemSBulgakov** [comment]
So decided @HeaTTheatR . I do not use Python 2, so I'm not opposed

**Comment by surbhicis** [comment]
@HeaTTheatR  if possible can you plan out for manageing different python version especially 2.7 ,as I am using this repo for build with buildozer and application runs on 2.7.12

**Comment by ArtemSBulgakov** [comment]
@surbhicis Why you cannot use Python 3?

**Comment by surbhicis** [comment]
I am running an application which uses python 2.7 and I am in mid of creating a mobile client for it and using buildozer I am creating build for it and in requirements I am using this repo for kivymd support and it turns fails today when I recreate build
Note:: I was using previously  version 0.91.0(HeaTTheatR/KivyMD/) which was running with python 2

**Comment by HeaTTheatR** [comment]
@surbhicis This year, Kivy stops supporting Python 2. Therefore, it was decided to abandon support for Python 2. Use the 2to3 utility to automatically convert code - https://www.youtube.com/watch?v=8qxKYnAsNuU
