### ISSUE TITLE
PIL linking problem on windows 10 python 3.6

### ISSUE THREAD

**Issue by Woundrite** [kivymd/KivyMD#530]
### Description of the Bug

I Downloaded the kivy zip and ran the setup.py file, and then when i ran the demo file for reference, it is giving me problems

### Code and Logs

the kivy demo code

### Screenshots

![problem](https://user-images.githubusercontent.com/46297894/93472605-87207400-f912-11ea-9d20-d6287c81f496.png)

### Versions

* OS: windows 10
* Python: 3.6
* Kivy: 2.0.0rc3
* KivyMD: kivymd-0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@Woundrite Your error is not related to the KivyMD library. And is not related to the PIL library. You are having trouble installing the Kivy framework. Ask a question on their server.

**Comment by podraco** [comment]
basically you need to follow the kivy instructions of how to install kivy on windows
https://kivy.org/doc/stable/installation/installation-windows.html
#### remember, in windows you need to instal the provider deps, such as Glew, Angle and SDL, or gstreamer if needed.
