### ISSUE TITLE
Unable to get a window, Abort.  Error

### ISSUE THREAD

**Issue by Woundrite** [kivymd/KivyMD#533]
### Description of the Bug
I recently had this problem which I some how fixed(uninstalling PIL and manually installing it again.).
https://github.com/kivymd/KivyMD/issues/530  (thank you for helping me with that one.)
but now I am having another problem and I don't know how to solve it

### Code and Logs

kivymd built-in example name kitchen_sink

### Screenshots
![image](https://user-images.githubusercontent.com/46297894/93600109-c5826580-f9dc-11ea-85a2-b1df4d560799.png)

### Versions

* OS: windows 10
* Python: 3.6
* Kivy: 2.0.0rc3
* KivyMD: kivymd-0.104.2.dev0

**Comment by podraco** [comment]
Sadly, this is a kivymd repo, and that is a kivy problem, seems like you forgot to install some dependencies like ask, angle and glew

**Comment by podraco** [comment]
Also, you need python 3.8 to use kivy 2.0

**Comment by Woundrite** [comment]
oh is that sooo
thankyou

**Comment by Woundrite** [comment]
but i dont think that that is helping as it is still giving me a lot of errors

**Comment by podraco** [comment]
If you installed python 3.8, you need to install again all packages, since they have different paths

**Comment by Woundrite** [comment]
i already have python 3 preinstalled on my computer, the problem is that is does not compile on python3.8 and kivymd is somehow giving the same problem still even but when i install angle and other dependencies, it says that they are already installed

**Comment by Woundrite** [comment]
can u please give me a bit more detailed info...
#noob

**Comment by Woundrite** [comment]
by python 3 i mean python 3.8 and 3.9 i installed 3.6 by myself

**Comment by podraco** [comment]
are you using python.exe from 3.8?
remember to use the python verison exe and not the pat if you have/had multiple instalations of pyhton.
use
[python3.8]/python.exe  -m install --upgrade __package__
replace python3.8 for the instalation dir where python.exe resides 
and replace __package__ with the list of packages you need
remember to follow the deps instalation of kivy since you're going to develop, you might want to install all dependencies as stated install kivy from source (even if you use pip)

**Comment by Woundrite** [comment]
the problem is solved thanks i literally had to reinstall pip as it was the pip installer which was broken and wasen't taking all the files but and now i am certain that my computer is going crazzy as it won't let me run the shrine sub demo application
![image](https://user-images.githubusercontent.com/46297894/93663500-23b75300-fa86-11ea-9ffd-fc89fa0f37df.png)

**Comment by HeaTTheatR** [comment]
@Woundrite This is an old bug of `FitImage` widget and it has been fixed in the master branch.

**Comment by Woundrite** [comment]
so what do i do now???

**Comment by HeaTTheatR** [comment]
@Woundrite Reinstall `KivyMD` library from master branch.

**Comment by Woundrite** [comment]
crapppp
