### ISSUE TITLE
MDTabs not working properly!

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#534]
### Description of the Bug

when i use tabs sometimes it reacts like this (tab shaking)
![latestts](https://user-images.githubusercontent.com/63696279/93659274-176ccf00-fa61-11ea-9159-74a1d6fdcfa6.gif)

### Code
```python
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
        on_tab_switch: app.on_tab_switch(*args)
        Tab:
        	text: 'tab1'
        Tab:
        	text: 'tab2'
        Tab:
        	text: 'tab3'
        Tab:
        	text: 'tab4'

<Tab>:

    MDLabel:
        id: label
        text: "Tab 0"
        halign: "center"
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_tab_switch(
        self, instance_tabs, instance_tab, instance_tab_label, tab_text
    ):
        instance_tab.ids.label.text = tab_text


Example().run()

```

### Versions

* OS: Debain 10
* Python: v3.7.3
* Kivy: v2.0.0rc3, git-20c14b2, 20200615
* KivyMD: 0.104.2.dev0, git-Unknown, 2020-09-18

**Comment by Matan22g** [comment]
Ive encountered the same problem.. it has something to do with the auto stretching function, it causes also shrinking bug when being switched really fast, a temporary solution Ive found was disabling the strech func: 
        
allow_stretch: False

**Comment by Kulothungan16** [comment]
> Ive encountered the same problem.. it has something to do with the auto stretching function, it causes also shrinking bug when being switched really fast, a temporary solution Ive found was disabling the strech func:
> 
> allow_stretch: False

when i use `allow_stretch: False` the tabs are going left side
![hud](https://user-images.githubusercontent.com/63696279/93851061-16d87080-fccd-11ea-846d-2e9c6d3fae79.png)

**Comment by yashBhosale** [comment]
For someone else that wants to take a look at this, I tried to figure out what was going on and figured out that the twitch is caused by the start tab and the end tab being resized to their original size and then immediately being re-resized back to normal. I think it has something to do with re-rendering textures?
