### ISSUE TITLE
Make Menu with MDToolbar (CustomToolbar) better in docs!

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#535]
### Description of the Feature
when use [custom mdtoolbar](https://kivymd.readthedocs.io/en/latest/components/menu/index.html#menu-with-mdtoolbar) for dropdownmenu the labels and icon colous are in black always (see the below screenshots)
but in original kivymd's mdtoolbar changes textcolor of labels (and icons) according to theme_cls.primary_palette

add these two two code block in docs for others reference

in root
```
md_bg_color: self.theme_cls.primary_color
```

in all mdlabels and mdiconbuttons
```
theme_text_color: "Custom"
text_color: root.specific_text_color
```
*full code below*

### Code 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivymd.theming import ThemableBehavior
from kivymd.uix.behaviors import RectangularElevationBehavior
from kivymd.uix.boxlayout import MDBoxLayout

KV = '''
<CustomToolbar>:
    size_hint_y: None
    height: self.theme_cls.standard_increment
    padding: "5dp"
    spacing: "12dp"
    md_bg_color: app.theme_cls.primary_color

    MDIconButton:
        id: button_1
        icon: "menu"
        pos_hint: {"center_y": .5}
        theme_text_color: "Custom"
        text_color: root.specific_text_color
        on_release: app.menu_1.open()

    MDLabel:
        text: "MDDropdownMenu"
        pos_hint: {"center_y": .5}
        size_hint_x: None
        width: self.texture_size[0]
        text_size: None, None
        font_style: 'H6'
        theme_text_color: "Custom"
        text_color: root.specific_text_color

    Widget:

    MDIconButton:
        id: button_2
        icon: "dots-vertical"
        pos_hint: {"center_y": .5}
        theme_text_color: "Custom"
        text_color: root.specific_text_color
        on_release: app.menu_2.open()

Screen:

    CustomToolbar:
        id: toolbar
        elevation: 10
        pos_hint: {"top": 1}
'''


class CustomToolbar(
    ThemableBehavior, RectangularElevationBehavior, MDBoxLayout,
):
    pass


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        self.menu_1 = self.create_menu(
            "Button menu", self.screen.ids.toolbar.ids.button_1,
        )
        self.menu_2 = self.create_menu(
            "Button dots", self.screen.ids.toolbar.ids.button_2,
        )

    def create_menu(self, text, instance):
        menu_items = [{"icon": "git", "text": text} for i in range(5)]
        menu = MDDropdownMenu(caller=instance, items=menu_items, width_mult=5)
        menu.bind(on_release=self.menu_callback)
        return menu

    def menu_callback(self, instance_menu, instance_menu_item):
        instance_menu.dismiss()

    def build(self):
        return self.screen


Test().run()

```

### Screenshots
in all theme (primary_palette) mdlabels and mdicons in black in color
![bad1](https://user-images.githubusercontent.com/63696279/93712300-9b62ac00-fb72-11ea-9d15-6d2763758319.png)        ![bad2](https://user-images.githubusercontent.com/63696279/93712304-ab7a8b80-fb72-11ea-911e-7feca359e842.png)

according to the current theme (primary_palatte) mdlabels and mdicons changes colors to specific_text_color 
![gud1](https://user-images.githubusercontent.com/63696279/93712308-ae757c00-fb72-11ea-8fd3-e25e1dbbf571.png)        ![gud2](https://user-images.githubusercontent.com/63696279/93712309-b0d7d600-fb72-11ea-8b2e-83cacf70b11a.png)

### Versions

* OS: Debain 10
* Python: v3.7.3
* Kivy: v2.0.0rc3, git-20c14b2, 20200615
* KivyMD: 0.104.2.dev0, git-Unknown, 2020-09-18

**Comment by podraco** [comment]
Hello.
Just a note before verifying this behavior, 

The voice you're using to write your texts are too imperative. This is often interpreted as an order, and not a suggestion, thus making the sentence a very rude way for asking for something. 

I know that maybe this is the literal way to translate the thought, but I would suggest you to read a little more about active, imperative and passive voices in English, 

This is not a callback nor anything like that, but a suggestion to avoid any misunderstanding between contributors. 

### Update -
the example code does not works

**Comment by kulothunganug** [comment]
sry i don't know english (little only know),
and above code works good in my pc.
what error are u facing pls tell me

**Comment by podraco** [comment]
You could try and use lingue, from deepl, it's an Artificial intelligence that can translate almost anything
There's an error when builder loads since the theme_cls is not yet an object

**Comment by podraco** [comment]
It you want to do something better, the best fitting word would be improve, improving, improves, improved

**Comment by kulothunganug** [comment]
hi bro i have changed 
```
md_bg_color: app.theme_cls.primary_color
```
to 
```
md_bg_color: self.theme_cls.primary_color
```
try it .
and i googled for lingue from deepl it does not have my language (tamil language, tamil nadu, india) but i will try to impove my english
