### ISSUE TITLE
MDIconButton - size

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#541]
### Description of the Bug
#528 
> in some phones which have bigger font size kivymd looks bad

when i use mdiconbutton in mobiles which have bigger font size, the icon are not showing properly
### Screenshots --> MDIconButton
![WhatsApp Image 2020-09-23 at 7 44 33 AM](https://user-images.githubusercontent.com/63696279/93979526-13131f80-fd9b-11ea-96b4-1e923d3c1162.jpeg)
![WhatsApp Image 2020-09-22 at 5 33 12 PM](https://user-images.githubusercontent.com/63696279/93979543-19a19700-fd9b-11ea-853d-8ce00499a6f4.jpeg)

and also the card radius is not working properly in mobiles (which have bigger font size)

### Screenshots --> MDCard

![WhatsApp Image 2020-09-23 at 7 40 41 AM](https://user-images.githubusercontent.com/63696279/93979534-160e1000-fd9b-11ea-9095-58608608d6ba.jpeg)

### Versions

* OS: Debain 10
* Python: v3.7.3
* Kivy: v2.0.0rc3, git-20c14b2, 20200615
* KivyMD: 0.104.2.dev0, git-Unknown, 2020-09-18

**Comment by podraco** [comment]
remember to use SP for fonts instead of PX or DP

**Comment by kulothunganug** [comment]
> remember to use SP for fonts instead of PX or DP

bro, I did not use any font size

**Comment by podraco** [comment]
thats odd...
i tested in different phones and i don't see that behavior... what OS verison did you used?

**Comment by podraco** [comment]
hoooo, i think i know what might be the problem
try to use #501  to build the test
it might be due to the text_size property not being the correct size upon the screen. it completely depends on the font size.

**Comment by kulothunganug** [comment]
> thats odd...
> i tested in different phones and i don't see that behavior... what OS verison did you used?

os used for packaging kivymd app: Debian 10

**Comment by kulothunganug** [comment]
> hoooo, i think i know what might be the problem
> try to use #501 to build the test
> it might be due to the text_size property not being the correct size upon the screen. it completely depends on the font size.

yes bro i will check it out

**Comment by podraco** [comment]
I meant android or mobile is

**Comment by kulothunganug** [comment]
redmi 7s, android 9, bro

**Comment by podraco** [comment]
that's odd...
well, you can always try #501 and see if the behavior keeps or it's fixed
