### ISSUE TITLE
Snackbar github docs mention button_color but snackbar module doesn't have that property

### ISSUE THREAD

**Issue by dwmoffatt** [kivymd/KivyMD#542]
### Description of the Bug

Kivymd Docs for snackbar talk about button_color but snackbar module doesn't have that property. 

### Screenshots

![Screenshot from 2020-09-23 17-06-22](https://user-images.githubusercontent.com/52943347/94086243-3d76d400-fdbf-11ea-9af2-960f96a19c55.png)

* KivyMD: Master

**Comment by kulothunganug** [comment]
use

```py
snack = Snackbar(text="This is a snackbar")
snack.buttons = [
            MDFlatButton(
                text="WITH A BUTTON",
                text_color=(1, 1, 1, 1),
                on_release=callback,
            )
        ]
snack.open()
```

bro there is more updated kivymd but the docs are not

**Comment by HeaTTheatR** [comment]
@dwmoffatt Build documentation is broken.

![Снимок экрана 2020-09-24 в 08 01 55](https://user-images.githubusercontent.com/16930280/94103102-65f0e380-fe3c-11ea-8848-adc921c7515a.png)

**Comment by dwmoffatt** [comment]
@HeaTTheatR Fair Enough. Can't argue with that.

**Comment by kulothunganug** [comment]
> @dwmoffatt Build documentation is broken.
> 
> ![Снимок экрана 2020-09-24 в 08 01 55](https://user-images.githubusercontent.com/16930280/94103102-65f0e380-fe3c-11ea-8848-adc921c7515a.png)

👍🏽, sorry bro i don't know much about git

**Comment by podraco** [comment]
is it broken in the repo or where?
i can still use sphinx to generate a new one.

**Comment by dwmoffatt** [comment]
Do you guys generate the gh pages manually or do you have a workflow setup to do it and post it?
