### ISSUE TITLE
Toolbar buttons dont work while using datatable

### ISSUE THREAD

**Issue by dheerajshenoy** [kivymd/KivyMD#543]
### Description of the Bug

Toolbar buttons dont work with the datatable in the same screen, but navigation drawer works by swiping from the left. 
I have not attached the code as I have split the code for the toolbar from other modules, including the data table. I have made use of many screen in my app with a single toolbar for all the screens. The toolbar is responsive in all of the screen, except the screen containing the datatable. I think that the datatable is stealing mouse focus from the toolbar for highlighting rows.

### Versions

* OS: Linux
* Python: 3.8.5
* Kivy: 1.11.1
* KivyMD: latest (master branch)

**Comment by kulothunganug** [comment]
can u give that code which produces error

**Comment by dheerajshenoy** [comment]
I'll try

**Comment by dheerajshenoy** [comment]
Should I post the code here?

**Comment by dheerajshenoy** [comment]
https://pastebin.com/ZFSqbM5t

**Comment by dheerajshenoy** [comment]
This is not the actual code I'm working on, but it is enough to show the problem. As you can see, the toolbar buttons are not responding to click, but swiping from the left makes the navigation drawer visible.

**Comment by HeaTTheatR** [comment]
@dheerajshenoy Because the `MDDataTable` widget has its parent class `ModalView` - https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables.py#L663

**Comment by dheerajshenoy** [comment]
So, is there any workaround ?

**Comment by HeaTTheatR** [comment]
@dheerajshenoy You must embed the table in some widget.

**Comment by dheerajshenoy** [comment]
I'll try that out. Thanks for the reply!
