### ISSUE TITLE
Beautiful Speedometer - TODO List.

### ISSUE THREAD

**Issue by beyonlo** [kivymd/KivyMD#544]
Hello!

I'm using this kivy speedmeter ( https://github.com/kivy-garden/speedmeter ). But it is very ugly and has some bugs, as I reported in that project https://github.com/kivy-garden/speedmeter/issues/1

I would like a example very beautiful speedometer. I do not found a beautiful picture for you now, but tried to find on internet some examples (are attached), but somes is not so beautiful too, but as reference is good.
Here has other options too: https://www.vectorstock.com/royalty-free-vectors/speedometers-vectors

I remembered about car speed Android App, developed using kivy, where has some beautiful speedometer, but I not remember the app name. Anyway, I think this is fine for you, for now :)

**Important:**
1. Anyway, I suggest you to do a speedmeter where is possible to configure it to be 360, 180 or 90 degrees, because when used in small devices, the 180 and 90 degrees are very good options to optimize screen space.
2. to be possible to configure tick and subtick, like as is possible to do with that https://github.com/kivy-garden/speedmeter

I will to try still to found a beautiful speedometer to send you.

Thank you so much :)

![power-gauge-meter-stages-eps-vector_csp19653387](https://user-images.githubusercontent.com/630637/91342330-3f924680-e7b1-11ea-93f9-38fa6d61251e.jpg)
![black-speedometer-scale-speed-gauge-vector-16749487](https://user-images.githubusercontent.com/630637/91342332-402add00-e7b1-11ea-91d0-610db6209621.jpg)
![futuristic-car-speedometers-speed-eps-vector_csp55818647](https://user-images.githubusercontent.com/630637/91342334-402add00-e7b1-11ea-9934-0187706fa57a.jpg)
![futuristic-car-speedometer-speed-hud-kilometer-vector-22579459](https://user-images.githubusercontent.com/630637/91342336-40c37380-e7b1-11ea-8054-b784909e7eba.jpg)

**Comment by podraco** [comment]
They look beautiful, but they aren't part of the Google's material design standard.
there's a repo that works with kivymd that add a lot of different widgets. That are animated in 2D and 3D, maybe you've been interested to apport to that one.

**Comment by beyonlo** [comment]
@podraco 

It's fine to me, and for most people, a speedometer following the material design standard. It's possible?

Thanks.

**Comment by podraco** [comment]
I'm not sure how to interpret that message.

It's possible for anyone to create a widget that resembles the material design common rules.

But since it's not part of the material design standard i don't think the main repo is the best place to incorporate it.

theres a repo that develops that kind of widget as a plug in for the kivymd repo.
i don't remember it's name, but he usually post on the discord server. in the channel your projects if i'm right.

**Comment by podraco** [comment]
https://github.com/quitegreensky/akivymd
