### ISSUE TITLE
MDDropdownMenu item responsive area right shifted

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#552]
### Description of the Bug

MDDropdownMenu item responsive area is right shifted.

In the demo example the responsive area for each item starts at the right end of the text "Item", and extends to the to the right side of the item area.
The area to the left of the text "Item", and including the text "Item" is unresponsive to touch events.

I suggest the full item area should be responsive.

Vertical responsiveness is correct for the item height and position.

No error messages are seen in the console, only the status message from the callback.

Possibly related to #505  but this comment https://github.com/kivymd/KivyMD/issues/505#issuecomment-687124723 only tests the 'good' item area as described in this post, the 'bad' area described here is not tested. Also possibly related to #455 

### Code and Logs

Using this example   https://kivymd.readthedocs.io/en/latest/components/menu/index.html

### Versions

* OS: Windows 10
* Python: 3.8
* Kivy: 2.0.0rc3
* KivyMD: pip install git+https://github.com/HeaTTheatR/KivyMD.git  installed 9/27/2020

**Comment by kulothunganug** [comment]
@RobertFlatt i also have that problem bro 

code that i have [used](https://kivymd.readthedocs.io/en/latest/components/menu/index.html#usage)
![dropdown](https://user-images.githubusercontent.com/63696279/94415321-0b88b780-019b-11eb-89da-e5b5426313f3.gif)

**Comment by RobertFlatt** [comment]
Update:
The description the the original post applies when width = 3 ,4, or 5
For width = 2  the second quarter of the width (from the left) is inactive, the remainder is active.
For width = 1  the first quarter of the width (from the left) is active, the remainder is inactive.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/pull/562

**Comment by RobertFlatt** [comment]
Thank you.
