### ISSUE TITLE
MDToolbar title position

### ISSUE THREAD

**Issue by ElLoko233** [kivymd/KivyMD#553]
### Description of the Feature

ability to change the position of the MDToolbar title to the right end,  left end  and the middle

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    MDToolbar:
       title: 'Title'
       title_pos: 'right'

""'
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by kulothunganug** [comment]
bro your issue has been fixed by #560  pls close
