### ISSUE TITLE
More icon options

### ISSUE THREAD

**Issue by ElLoko233** [kivymd/KivyMD#554]
### Description of the Feature
more icons

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@ElLoko233 The question is closed due to the lack of the essence of the question. Try asking more specific questions.
