### ISSUE TITLE
MDExpansionPanel is not working for icon names from md_icons

### ISSUE THREAD

**Issue by thmswrnr** [kivymd/KivyMD#557]
### Description of the Bug

MDExpansionPanel is not working for icon names from md_icons. Error for icon name e.g. 'bus': 
[ERROR  ] [Image       ] Error reading file bus

Result: White blocks where icons should be (see image).

When no icon name is given, there is no error but there are still white blocks.

Code is taken from the [docs](https://kivymd.readthedocs.io/en/latest/components/expansion-panel/index.html)

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelThreeLine
from kivymd import images_path

KV = """
<Content>
    adaptive_height: True
    TwoLineIconListItem:
        text: "(050)-123-45-67"
        secondary_text: "Mobile"
        IconLeftWidget:
            icon: 'phone'
ScrollView:
    MDGridLayout:
        id: box
        cols: 1
        adaptive_height: True
"""


class Content(MDBoxLayout):
    """Custom content."""


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for i in range(10):
            self.root.ids.box.add_widget(
                MDExpansionPanel(
                    icon="bus",
                    content=Content(),
                    panel_cls=MDExpansionPanelThreeLine(
                        text="Text",
                        secondary_text="Secondary text",
                        tertiary_text="Tertiary text",
                    ),
                )
            )


Test().run()
```

### Screenshots

![dump](https://user-images.githubusercontent.com/5938163/94856490-5a02b400-0430-11eb-8a42-53c9a614ca2a.PNG)

### Versions

* OS: Windows 10
* Python: 3.7.6
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@21bumfit Try update KivyMD library from master branch:

![Снимок экрана 2020-10-02 в 00 22 51](https://user-images.githubusercontent.com/16930280/94864989-7fe68380-0445-11eb-82a7-ca94ecf9acc5.png)

**Comment by thmswrnr** [comment]
Thanks, that fixed it.
