### ISSUE TITLE
RecursionError in MDDropdownMenu

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#559]
### Description of the Bug

when i use MDDropdownMenu slowly it works fine but when i use it fastly it produces an error (RecursionError)

![sasad](https://user-images.githubusercontent.com/63696279/94905512-9ed32d00-04ba-11eb-80f0-45ead7830d6e.gif)

### Code

example code of [DropdownMenu](https://kivymd.readthedocs.io/en/latest/components/menu/index.html#usage)

### Versions

* OS: Debian 10
* Python: v3.7.3
* Kivy: v2.0.0rc3,
* KivyMD: 0.104.2.dev0, git-Unknown, 2020-10-02

**Comment by HeaTTheatR** [comment]
Duplicate - https://github.com/kivymd/KivyMD/issues/552
