### ISSUE TITLE
KivyMd 0.104.2.dev0 dark theme style too dark

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivymd/KivyMD#569]
when u set the theme_style to dark, the background is too dark compared to the normal one

**Comment by HeaTTheatR** [comment]
@Noor-Kalibbala
All colors are in accordance with material design specification - https://material.io/design/color/dark-theme.html

**Comment by mistvfx** [comment]
@Noor-Kalibbala , WRT Google's Material Design and also in general, Dark mode was required to make the device screen darker in case of low light environment. Having it any lighter wouldn't serve the purpose of dark mode, also, the color was chosen in such a way that amoled devices require less / no power to light up those pixels.

Without a reply, we can close this issue I guess ?

also, if you want it lighter, you can alter the variables that specify the color. Following a pre-made specification globally is better than suiting for our own need.

**Comment by wasimafser** [comment]
@Noor-Kalibbala , WRT Google's Material Design and also in general, Dark mode was required to make the device screen darker in case of low light environment. Having it any lighter wouldn't serve the purpose of dark mode, also, the color was chosen in such a way that amoled devices require less / no power to light up those pixels.

Without a reply, we can close this issue I guess ?

also, if you want it lighter, you can alter the variables that specify the color. Following a pre-made specification globally is better than suiting for our own need.

**Comment by Noor-Kalibbala** [comment]
@HeaTTheatR  actually this problem rises in the development version of kivymd, but in the pyp vesion the color is okay

**Comment by Noor-Kalibbala** [comment]
@wasimafser am using the development version since i wanted to use new features in the development version which is not yet in pyp, when i used the kivymd version in pyp the color was okay , it was gray rather dark
