### ISSUE TITLE
MDTextField mode='rectangle' bug

### ISSUE THREAD

**Issue by allexeyj** [kivymd/KivyMD#572]
### Description of the Bug

If u don't wanna read description of the bug or u don't understand me, see this video(https://yadi.sk/i/yhY1Wcz6L90nAw), all bugs were shown in this video

I have a code that located below.
At first, i edited field's text to 'hhh' and pressed on my button, as the result, i got new normal text of my field, however when i clicked on my field, line of field intersected field's hint_text like in 4-th screenshot.

But after that, i had held backspace until field's text is equal to empty string(''), and then i pressed on my button.
And after that i got a strange behavior. See the first and the second screenshots  below.

That's first part of my report.
Second part:
I made all actions from first part and changed field's text from "New text" to "New tex" and pressed on my button, as u can see on the 3th screenshot, i got normal behavior without any bugs, but  after that i pressed on my field and i got strange line of my field that intersects with field's hint text, see screenshot 4

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp


KV = '''
Screen:
    MDRaisedButton:
        text: 'update field text'
        pos_hint: {'center_y': .5, 'center_x': .5}
        on_release: app.change()
    MDTextField:
        size_hint: .7, .1
        mode: "rectangle"
        id: field
        text: ''
        hint_text: 'Bug'
        pos_hint: {'center_y': .7, 'center_x': .5}
'''


class Test(MDApp):
    def change(self):
        self.root.ids.field.text = 'New text'

    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Screenshots
![Test 06 10 2020 13_49_29](https://user-images.githubusercontent.com/71039746/95192546-0cdd6400-07db-11eb-8b30-afc338a58670.png)
![Test 06 10 2020 13_49_36](https://user-images.githubusercontent.com/71039746/95192555-0f3fbe00-07db-11eb-8623-ebc2ec981b00.png)
![Test 06 10 2020 14_02_25_LI](https://user-images.githubusercontent.com/71039746/95193658-d1439980-07dc-11eb-9037-b3803a9f6ba1.jpg)
![Test 06 10 2020 13_58_34_LI](https://user-images.githubusercontent.com/71039746/95193766-00f2a180-07dd-11eb-9963-02201a9cef9a.jpg)

### Versions

* OS: win10
* Python: 3.7
* Kivy: last version
* KivyMD: master branch

**Comment by shashi278** [comment]
Almost same as #571. Same solution will work.
