### ISSUE TITLE
Expansion Panel bug

### ISSUE THREAD

**Issue by allexeyj** [kivymd/KivyMD#574]
### Description of the Bug

When expansion panel is open and when i try to add widget into my panel i got strange behavior.
See screenshot

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelThreeLine
from kivymd.uix.list import TwoLineIconListItem


KV = '''
<Content>
    adaptive_height: True
    orientation: 'vertical'

<Item>:
    text: "(050)-123-45-67"
    secondary_text: "Mobile"
    IconLeftWidget:
        icon: 'phone'
Screen:
    ScrollView:
        MDList:
            id: box
            Widget:
                size_hint_y: None
                height: 100
            MDRaisedButton:
                text: 'add item into panel'
                on_release: app.add_into_panel()
            Widget:
                size_hint_y: None
                height: 100
'''
class Content(MDBoxLayout):
    '''Custom content.'''


class Item(TwoLineIconListItem):
    pass


class Test(MDApp):
    panel = ''
    panel_2 = ''

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.panel = MDExpansionPanel(
            icon=f"image",
            content=Content(),
            panel_cls=MDExpansionPanelThreeLine(
                text="Text",
                secondary_text="Secondary text",
                tertiary_text="Tertiary text",
            )
        )
        self.panel_2 = MDExpansionPanel(
            icon=f"image",
            content=Content(),
            panel_cls=MDExpansionPanelThreeLine(
                text="Text",
                secondary_text="Secondary text",
                tertiary_text="Tertiary text",
            )
        )

        self.root.ids.box.add_widget(self.panel)
        self.root.ids.box.add_widget(self.panel_2)

    def add_into_panel(self):
        print('adding')
        self.panel.content.add_widget(Item())


Test().run()
```

### Video
Pls, see that: https://yadi.sk/i/2gW5b5Zzc3_JHA

### screenshot

![Test 07 10 2020 22_11_41](https://user-images.githubusercontent.com/71039746/95376708-2f11d780-08ea-11eb-8911-1695afd34929.png)

### Versions

* OS: win10
* Python: 3.7
* Kivy: last version
* KivyMD: master branch

**Comment by HeaTTheatR** [comment]
@alexcode4u 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelThreeLine
from kivymd.uix.list import TwoLineIconListItem


KV = '''
<Content>
    adaptive_height: True
    orientation: 'vertical'


<Item>:
    text: "(050)-123-45-67"
    secondary_text: "Mobile"

    IconLeftWidget:
        icon: 'phone'


Screen:

    ScrollView:

        MDList:
            id: box

            Widget:
                size_hint_y: None
                height: 100

            MDRaisedButton:
                text: 'add item into panel'
                on_release: app.add_into_panel()

            Widget:
                size_hint_y: None
                height: 100
'''


class Content(MDBoxLayout):
    pass


class Item(TwoLineIconListItem):
    pass


class Test(MDApp):
    panel_is_open = False

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.panel = MDExpansionPanel(
            icon=f"image",
            content=Content(),
            panel_cls=MDExpansionPanelThreeLine(
                text="Text",
                secondary_text="Secondary text",
                tertiary_text="Tertiary text",
            )
        )
        self.panel.bind(on_open=self.panel_open, on_close=self.panel_close)
        self.root.ids.box.add_widget(self.panel)

    def panel_open(self, *args):
        self.panel_is_open = True

    def panel_close(self, *args):
        self.panel_is_open = False

    def add_into_panel(self):
        item = Item()
        self.panel.content.add_widget(item)
        if self.panel_is_open:
            self.panel.height += item.height


Test().run()```

**Comment by allexeyj** [comment]
Thank u. But for now i found another strange behavior.
https://yadi.sk/i/Gj3nfhUv8Rnx7Q
Pay attention to the:
1) shadow that appearance when button has been pressed
2) Big space after panel that appearance if panel is open and button has been pressed.
Note: if panel already has one or many items, and if user press on the button and panel is open, that space won't appearance, however shadow will appearance

**Comment by HeaTTheatR** [comment]
@alexcode4u 
```python
    def add_into_panel(self):
        item = Item()
        self.panel.content.add_widget(item)
        if self.panel_is_open and len(self.panel.content.children) > 1:
            self.panel.height += item.height
```

**Comment by allexeyj** [comment]
Unfortunately, problem hasn't been resolved
Pls, pls, see that: https://yadi.sk/i/KHZGgLaBSGjByg
There are all bugs.

**Comment by allexeyj** [comment]
That's new video-report
Video: 30s

**Comment by allexeyj** [comment]
I will try to fix wrong spacing, but i don't know what should i do with shadow

**Comment by HeaTTheatR** [comment]
@alexcode4u 
``` Clock.schedule_once(app.add_into_panel, 0.5)```

**Comment by allexeyj** [comment]
```
            MDRaisedButton:
                text: 'add item into panel'
                on_release: app.panel_callback()
```

```python
    def panel_callback(self):
        Clock.schedule_once(self.add_into_panel, 0.5)

```

What do i make wrong? 

TypeError: add_into_panel() takes 1 positional argument but 2 were given

**Comment by HeaTTheatR** [comment]
@alexcode4u 
```
    MDRaisedButton:
        on_release: Clock.schedule_once(app.add_into_panel, 0.5)
```

```python
    def add_into_panel(self, interval):
        [...]
```

**Comment by allexeyj** [comment]
@HeaTTheatR Thank u for ur support. I have two questions:
1) Shadow haven't gone completely, but behavior with Clock is better. Will be in future versions of kivy or KivyMD updates that could be resolve this problem? Will be updates for removing excess space?
2)What can i do with that?:)
![Test 08 10 2020 0_54_35](https://user-images.githubusercontent.com/71039746/95392131-e285c680-0900-11eb-873b-99b70c122e62.png))

**Comment by HeaTTheatR** [comment]
@alexcode4u What problems are you talking about?

**Comment by allexeyj** [comment]
@HeaTTheatR  1) When i use events or methods for panel(on_open, close_panel) i get shadow.
2) When i use panel.add_widget, i get excess space.
3)And i also found out that when i close or open panel, panel a bit twitched.

**Comment by HeaTTheatR** [comment]
@alexcode4u 

1) When i use events or methods for panel(on_open, close_panel) i get shadow
    This is natural behavior. You slide the button during the ripple animation. I showed you how to fix it.

2) When i use panel.add_widget, i get excess space.
    I showed you how to fix it.

3)And i also found out that when i close or open panel, panel a bit twitched.
    Yes that's a problem.

**Comment by allexeyj** [comment]
@HeaTTheatR 1)Ok, but i wrote that shadow hadn't completely disappeared
2) Yes, u showed me how to fix that, but i still don't know what can i do with that
![Test 08 10 2020 0_54_35](https://user-images.githubusercontent.com/71039746/95392131-e285c680-0900-11eb-873b-99b70c122e62.png)
There is one little excess space
I tried many variants.

**Comment by HeaTTheatR** [comment]
@alexcode4u What shadow are you talking about?

**Comment by allexeyj** [comment]
@HeaTTheatR 

https://yadi.sk/i/p27RVkRwlcmy0Q

I don't know will u see it.
Bellow the button will appearance shadow.

**Comment by allexeyj** [comment]
I fixed 2) problem

**Comment by allexeyj** [comment]
if anyone want to know how i did it

```python
    def add_into_panel(self, interval):
        item = Item()
        self.panel.content.add_widget(item)
        if self.panel_is_open and len(self.panel.content.children) > 1:
            self.panel.height += item.height
        elif self.panel_is_open and len(self.panel.content.children) == 1:
            self.panel.height -= (self.panel.height - item.height) - self.panel.panel_cls.height
```

I haven't made all test yet, and i'm so tierd, therefore some bugs can be in my solution.

**Comment by allexeyj** [comment]
@HeaTTheatR 
Another video that better shows bug 1)(shadow)
https://yadi.sk/i/ZIK1Husua270cA
