### ISSUE TITLE
Request for new version on Pyp

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivymd/KivyMD#578]
when u read the current kivymd documentation for menus, the new features correspond to development version which is not yet in pyp and it brings confusion to new users, and i find problem using development versions for audio since kivy use sdl for audio and it cant play audios on linux.

**Comment by HeaTTheatR** [comment]
@Noor-Kalibbala KivyMD is just additional widgets for Kivy. The KivyMD library has nothing to do with audio or video providers.

**Comment by Noor-Kalibbala** [comment]
okay thanks
