### ISSUE TITLE
OSError: File .....\kivymd\fonts/Roboto-Regular.ttf not found

### ISSUE THREAD

**Issue by k4mrul** [kivymd/KivyMD#58]
Hello, I created a package for windows with pyinstaller (pyinstaller --onefile myscript.py). After that, when I try to open the .exe file within dist directory, I get that error

`OSError: File C:\Users\HP\AppData\Local\Temp\_MEI131442\kivymd\fonts/Roboto-Regular.ttf not found`

The app doesn't startup. It immediately crash. I also tried to create the package from example scripts. No luck, get the same error whenever I try to open .exe

Is there any fix? Thanks

**Comment by ArtemSBulgakov** [comment]
Is KivyMD directory in the folder with myscript.py?

**Comment by k4mrul** [comment]
Yes. I put 'kivymd' directory in the same folder with myscript.py and created the package again. Still getting that error.

**Comment by HeaTTheatR** [comment]
@k4mrul Try replacing strings:

with

```python
fonts_path = os.path.join(path, 'fonts/')
images_path = os.path.join(path, 'images/')
```
to

```python
fonts_path = os.path.join(path, f'fonts{os.sep}')
images_path = os.path.join(path, f'images{os.sep}')
```

in kivymd/font_definitions.py module.

**Comment by k4mrul** [comment]
I didn't find those lines in myproject/kivymd/font_definitions.py file. However those lines exist on myproject/kivymd/__init__.py file. So I modified those lines in __init__.py file and build the package again. Now I am getting this error

`OSError: File userpath\AppData\Local\Temp\_MEI130082\kivymd\fonts\Roboto-Regular.ttf not found`

It seems the path is correct but no font file exist within that path.

**Comment by HeaTTheatR** [comment]
@k4mrul userpath\AppData\Local\Temp\_MEI130082 - where does this path lead? This is clearly not your project.

**Comment by ArtemSBulgakov** [comment]
This is temp dir where pyinstaller unpack bundled app

**Comment by HeaTTheatR** [comment]
@k4mrul This question does not apply to KivyMD. Ask on the forum PayInstaller.

**Comment by k4mrul** [comment]
@Mountaino is correct.

However, I think this is not an issue of pyinstaller because I used same command to pack kivy app. It works perfectly. The problem occurs on kivymd app. Anyway thanks for your help.

**Comment by HeaTTheatR** [comment]
@k4mrul This is not a KivyMD problem. Look in the assembly, is there a directory with fonts?

**Comment by k4mrul** [comment]
No. There is no fonts directory. So I think I have to add kivymd directory with my project whenever I use pyinstaller command.

**Comment by HeaTTheatR** [comment]
@k4mrul I can not help you unfortunately. I do not use Windows and I do not use PyInstaller. You have a problem with the assembly in PyInstaller. KivyMD has nothing to do with your mistake.

**Comment by k4mrul** [comment]
Ok. No problem. I am dealing with that issue. Anyway, is there any other way to pack the kivymd app for windows other than pyinstaller?

**Comment by HeaTTheatR** [comment]
@k4mrul I have no idea. Everything related to Windows is a question not for me. I think you need to fix the rules for assembling into PyInstaller, because it simply does not add KivyMD fonts to the package.

**Comment by ArtemSBulgakov** [comment]
I can write later how to do it

**Comment by k4mrul** [comment]
I've fixed the issue. If anyone facing the same problem in windows, open kivymd/__init__.py and modify the lines as @HeaTTheatR suggested. Now if you want to use pyinstaller to pack the app, just add the kivymd folder with your script. You can use this tool auto-py-to-exe (pip install auto-py-to-exe) which have GUI of pyinstaller that will help to ease the task.

Thanks everyone.

**Comment by BernardinD** [comment]
And for anyone who doesn't want to have the kivymd directory copied into every build and are having trouble with it [check this out](https://stackoverflow.com/a/59213720) .

**Comment by Genjidegaulle** [comment]
Thanks @BernardinD, the above link worked perfectly for me :)
