### ISSUE TITLE
button click issue

### ISSUE THREAD

**Issue by dovahkinnn** [kivymd/KivyMD#580]
ı click button and app close. kivymd cant support pytube?

### Code and Logs

main.kv
<MyGrid>:

    name: name
    

    GridLayout:
        cols:1
        size: root.width - 200, root.height -225
        pos: 100, 350

        GridLayout:
            cols:1

            MDLabel:
                text: "YOUTUBE Video Dowloader"
                halign: "left"

            MDTextFieldRect:
                size_hint: 1, None
                height: "30dp"
                
                id: name
                halign: "left"
                hint_text: 'Empty field'

            MDRectangleFlatButton:
                text: "indirmek icin tikla"
                text_color: 0, 0, 1, 1
                md_bg_color: 0, 1, 0, 1
                halign: "left"
                on_press: root.btn()
main.py
import kivy
from kivy.app import App

from kivy.uix.gridlayout import GridLayout

from kivy.uix.widget import Widget
from kivy.properties import ObjectProperty
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.label import MDLabel
from pytube import YouTube
Builder.load_file('main.kv')

class MyGrid(Widget):
    name = ObjectProperty(None)
    

    def btn(self):
        print("'", self.name.text,"'",)
        a=("'", self.name.text,"'")
        
        yt=YouTube(str(a))
        stream = yt.streams.filter(only_audio=True).first()
        stream.download()
        
       
        
    
   

class MainApp(MDApp):
    def build(self):
        self.theme_cls.primary_palette = "Blue" 
        return MyGrid()

if __name__ == "__main__":
    MainApp().run()

**Comment by dwmoffatt** [comment]
Does the App crash when deployed on your phone or on your computer? 

Do you have a copy the log?

Does the app work if you remove:
```
yt=YouTube(str(a))
stream = yt.streams.filter(only_audio=True).first()
stream.download()
```

**Comment by HeaTTheatR** [comment]
@dovahkinnn I have to close this question because it is not related to KivyMD library.
