### ISSUE TITLE
MDTextField multiline bug

### ISSUE THREAD

**Issue by allexeyj** [kivymd/KivyMD#585]
### Description of the Bug

I took that line(
"[INFO   ] [GL          ] NPOT texture support is available

"
) from log, and when i copy this line to the field, i get multiline, however i declared multiline = False parameter

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
BoxLayout:
    padding: "50dp"

    MDTextField:
        multiline: False
        hint_text: "Helper text on error (press 'Enter')"
        pos_hint: {"center_y": .5}
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def build(self):
        return self.screen


Test().run()
```

### Screenshots

![Test 14 10 2020 21_43_46](https://user-images.githubusercontent.com/71039746/96031789-7eb24f00-0e66-11eb-9ff5-3a338c0c139a.png)

### Versions

* OS: win10
* Python: 3.7
* Kivy: last version
* KivyMD: master branch

**Comment by HeaTTheatR** [comment]
Fix - https://github.com/kivymd/KivyMD/pull/587/commits/07569e5a0fa7d5f9263cf58cbadfe89d09b225e9
