### ISSUE TITLE
Application canvas doesn't render correctly & KivyMD menu.py doesn't work.

### ISSUE THREAD

**Issue by prawnydagrate** [kivymd/KivyMD#592]
### Description of the Bug

# Rendering
I'm on macOS X Catalina. When I run my app with `python3 main.py`, something goes wrong: [Here's the video](https://github.com/kivymd/KivyMD/files/5396254/Kivy.Screen.zip)
I watched a YouTube video on how to run Kivy apps on macOS. It said there's this macOS app called Kivy that comes with a command line tool. When I run `kivy main.py`, I get a `ModuleNotFoundError`. So I tried `kivy -m pip install
 <module>` but that doesn't work for any module. So I cloned the required modules from GitHub and pasted them in the modules directory of the CLI. But then I get an error caused by PyObjus and I don't know how to fix it.

# menu.py
When I run `kivy main.py` I get an error caused by `menu.py`: [Here's the video](https://github.com/kivymd/KivyMD/files/5396305/Kivy.CLI.Screen.zip)

### Versions

* OS: macOS X Catalina
* Python: 3.8
* Kivy: Latest from PyPI
* KivyMD: Latest from PyPI

**Comment by HeaTTheatR** [comment]
@Python3-8 Your issue is not related to the KivyMD library.

**Comment by prawnydagrate** [comment]
Is there any solution to this problem?
