### ISSUE TITLE
Weird behavior of MagicBehavior

### ISSUE THREAD

**Issue by quitegreensky** [kivymd/KivyMD#605]
### Description of the Bug

I noticed there is a problem with using relativelayout and magicbehavior . This bug also affects MDSwiper inside demo app. 

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang.builder import Builder

kv = """

<MyButton@MDRaisedButton+MagicBehavior>

<MyItem@RelativeLayout>
    MyButton:
        text: 'press'
        pos_hint: {'center_x': .5, 'center_y': .5}

Screen:

    BoxLayout:
        spacing: dp(5)

        MyItem:

        MyItem:

        MyItem:

        MyItem:

        """

class Main(MDApp):

    def build(self):
        return Builder.load_string(kv)

Main().run()

```

### Screenshots

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/55235027/97064195-14f61b80-15b1-11eb-9da9-e3e9ec3154ba.gif)

**Comment by kulothunganug** [comment]
i also have a problem with magic behavior
the widgets under the magic behavior class are shaking when using it
![magi](https://user-images.githubusercontent.com/63696279/97078186-e9eae680-1607-11eb-8768-d665f995bd1c.gif)

```py
from kivy.lang import Builder
from kivymd.app import MDApp

KV = """
<HeartButton@MagicBehavior+MDIconButton>

BoxLayout:

    MDLabel:
        text: 'One'

    MDRaisedButton:
        text: 'One'

    HeartButton:
        icon: 'heart-outline'
        on_release:
            self.grow()

    MDLabel:
        text: 'Two'

    MDRaisedButton:
        text: 'Two'

"""


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()

```

**Comment by kulothunganug** [comment]
> i also have a problem with magic behavior
> the widgets under the magic behavior class are shaking when using it
> ![magi](https://user-images.githubusercontent.com/63696279/97078186-e9eae680-1607-11eb-8768-d665f995bd1c.gif)
> 
> ```python
> from kivy.lang import Builder
> from kivymd.app import MDApp
> 
> KV = """
> <HeartButton@MagicBehavior+MDIconButton>
> 
> BoxLayout:
> 
>     MDLabel:
>         text: 'One'
> 
>     MDRaisedButton:
>         text: 'One'
> 
>     HeartButton:
>         icon: 'heart-outline'
>         on_release:
>             self.grow()
> 
>     MDLabel:
>         text: 'Two'
> 
>     MDRaisedButton:
>         text: 'Two'
> 
> """
> 
> 
> class Test(MDApp):
>     def build(self):
>         return Builder.load_string(KV)
> 
> 
> Test().run()
> ```

not solved bro
