### ISSUE TITLE
Erro: ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by mattewid** [kivymd/KivyMD#609]
Hello, I have an app that needs to import a java class using the autoclass, but I'm getting an error when trying to import it

Error code: `WebView = autoclass ('android.webkit.WebView')`

Error: **ReferenceError: weakly-referenced object no longer exists**

**Obs**: I'm importing other class java using the autoclass and it is working perfectly (only the one indicated above that is giving this error). This same code I am using is working perfectly in standard Kivy, but in KivyMD it is not.

**Comment by HeaTTheatR** [comment]
@HK-Mattew Your question is not related to Kivy library. 
https://github.com/kivy/kivy/issues
