### ISSUE TITLE
app crashes using the master branch

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#617]
10-27 12:15:00.451 10128 10198 I python  : Android kivy bootstrap done. __name__ is __main__
10-27 12:15:00.451 10128 10198 I python  : AND: Ran string
10-27 12:15:00.451 10128 10198 I python  : Run user program, change dir and execute entrypoint
10-27 12:15:01.069 10128 10198 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
10-27 12:15:01.070 10128 10198 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
10-27 12:15:01.088 10128 10198 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.kivy.kivymd.akivymd.mindset.nocenstore.nocenstore/files/app/.kivy/logs/kivy_20-10-27_0.txt
10-27 12:15:01.089 10128 10198 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.kivy.kivymd.akivymd.mindset.nocenstore.nocenstore/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
10-27 12:15:01.090 10128 10198 I python  : [INFO   ] [Python      ] v3.8.1 (default, Oct 27 2020, 11:14:17) 
10-27 12:15:01.090 10128 10198 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
10-27 12:15:01.091 10128 10198 I python  : [INFO   ] [Python      ] Interpreter at ""
10-27 12:15:04.281 10128 10198 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
10-27 12:15:04.472 10128 10198 I python  : [INFO   ] [Loader      ] using a thread pool of 2 workers
10-27 12:15:04.506 10128 10198 I python  : [INFO   ] [Factory     ] 186 symbols loaded
10-27 12:15:05.671 10128 10198 I python  :  Traceback (most recent call last):
10-27 12:15:05.672 10128 10198 I python  :    File "/home/kengo/PycharmProjects/NOCENSTORES/.buildozer/android/app/main.py", line 12, in <module>
10-27 12:15:05.675 10128 10198 I python  :    File "/home/kengo/PycharmProjects/NOCENSTORES/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/nocenstore/kivymd/__init__.py", line 56, in <module>
10-27 12:15:05.677 10128 10198 I python  :  PermissionError: [Errno 13] Permission denied: '/data/.kivymd'
10-27 12:15:05.677 10128 10198 I python  : Python for android ended.

requirements python3,kivy==2.0.0rc3,https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by HeaTTheatR** [comment]
@kengoon Yes, this is a bug. We will try to fix it as soon as possible.

**Comment by kengoon** [comment]
> @kengoon Yes, this is a bug. We will try to fix it as soon as possible.

is there a version I can use(which contains latest features) because my company is in production mode, I need to use kivymd today (please i need your help)
