### ISSUE TITLE
Bottom navigation is rendered off-center in combination with a navigation drawer

### ISSUE THREAD

**Issue by timovwb** [kivymd/KivyMD#618]
### Description of the Bug

When placing a bottom navigation on a second screen in combination with a navigation drawer, the bottom navigation is rendered too far to the right, placing the right most item offscreen. Resizing the window pops it back in the right place.

The code sample below is just the combination of the bottom navigation and navigation drawer examples from the documentation. Click the button on the main screen to switch to the screen that shows the bug.

### Code and Logs

```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp

KV = '''
Screen:

    NavigationLayout:

        ScreenManager:
            id: screen_manager

            Screen:
                name: 'main_screen'

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: 'Navigation Drawer'
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Button:
                        text: 'Switch to bottom nav screen'
                        on_press: screen_manager.current = 'bottom_nav_screen'

            Screen:
                name: 'bottom_nav_screen'
                
                MDBottomNavigation:

                    MDBottomNavigationItem:
                        text: 'Python'
                        icon: 'language-python'
            
                        Button:
                            text: 'Switch to main screen'
                            on_press: screen_manager.current = 'main_screen'

                    MDBottomNavigationItem:
                        text: 'C++'
                        icon: 'language-cpp'

                    MDBottomNavigationItem:
                        text: 'JS'
                        icon: 'language-javascript'

        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
'''


class ContentNavigationDrawer(BoxLayout):
    pass


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)


TestNavigationDrawer().run()

```

### Versions

* Python: 3.6.9
* Kivy: 2.0.0rc4 (same for 2.0.0rc3 and 1.11.1)
* KivyMD: 0.104.2.dev0 (same for 0.104.1)

**Comment by timovwb** [comment]
@HeaTTheatR Can this issue be opened again since the fix has been reverted?

**Comment by Ratulhasan14789** [comment]
Same issue, using latest version kivy: 2.0.0, kivymd: 0.104.1, py: 3.8.5
Nav bar is stuck at right, showing only the half, resizing the window even a pixel fixes the problem. However it's not possible on Android (thought of making this bug as a feature, but now it's causing trouble)

Reopen this issue please

**Comment by HeaTTheatR** [comment]
@Ratulhasan14789
We do not support version 0.104.1. Use the master branch of the library.

**Comment by RaSan147** [comment]
> @Ratulhasan14789
> We do not support version 0.104.1. Use the master branch of the library.

Tried the master version, bottomnav works fine on computer, but the mddialog seems buggy in master
And after compiling to apk (yes i putted the master link in the requirements) the bottom nav is stuck at right (half is invisible)
Screen|-----item0-----item1|/screen----item2

Also android shows the buggy Mddialog after compiling with master.zip link

**Comment by HeaTTheatR** [comment]
@Ratulhasan14789 If you keep getting this error, then most likely you are not using the master branch. Delete the directory `.buildozer` in the project folder and restart the compilation process.

**Comment by RaSan147** [comment]
> @Ratulhasan14789 If you keep getting this error, then most likely you are not using the master branch. Delete the directory `.buildozer` in the project folder and restart the compilation process.

Checked with logcat, both kivy and kivymd are from master branch version. And deleting .buildozer folder will also delete android sdk ndk etc folder and i have pretty poor connection (may take a day to redownload and compile) any tips to move those files safely before deleting the .buildozer file

**Comment by HeaTTheatR** [comment]
@Ratulhasan14789 https://github.com/kivymd/KivyMD/issues/271

**Comment by ghost** [comment]
The program shows two current screens at same time when using both navigation drawer and bottom navigation. How can I fix so it only shows one current screen at time?

My python file:

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import ObjectProperty

class ContentNavigationDrawer(BoxLayout):
    screen_manager = ObjectProperty()
    nav_drawer = ObjectProperty()

class NavigationScreen(MDApp):
    def build(self):
        return Builder.load_file("navigation.kv")

NavigationScreen().run()

My kv file:
#: import get_color_from_hex kivy.utils.get_color_from_hex

<ContentNavigationDrawer>:

    # Making the menu inside the toolbar
    BoxLayout:
        orientation: "vertical"

        # Show logo inside the navigation bar
        Image:
            source: "logo.png"

        # The list of items inside the navigation bar
        ScrollView:
            MDList:
                OneLineIconListItem:
                    text: "Profile"
                    on_press:
                        root.nav_drawer.set_state("close")
                        root.screen_manager.current = "profile"
                    IconLeftWidget:
                        icon: "account"

                OneLineIconListItem:
                    text: "My Best Results"
                    on_press:
                        root.nav_drawer.set_state("close")
                        root.screen_manager.current = "best results"
                    IconLeftWidget:
                        icon: "arm-flex"

                OneLineIconListItem:
                    text: "Log Out"
                    on_press:
                        root.nav_drawer.set_state("close")
                        root.screen_manager.current = "logout"
                    IconLeftWidget:
                        icon: "logout"

                OneLineIconListItem:
                    text: "Settings"
                    on_press:
                        root.nav_drawer.set_state("close")
                        root.screen_manager.current = "settings"
                    IconLeftWidget:
                        icon: "cog"

# Bottom navigation bar
Screen:
    MDBottomNavigation:
        panel_color: get_color_from_hex("#016064")
        text_color_active: get_color_from_hex("F5F5F5")
        MDBottomNavigationItem:
            name: 'session'
            text: 'New Session'
            icon: 'run'

            MDLabel:
                text: "session screen"
                pos_hint: {"center_x": 0.93, "center_y": 0.6}

        MDBottomNavigationItem:
            name: 'result'
            text: 'Test Result'
            icon: 'plus'

            MDLabel:
                text: "result screen"
                pos_hint: {"center_x": 0.93, "center_y": 0.6}

        MDBottomNavigationItem:
            name: 'goat league'
            text: 'Goat League'
            icon: 'sheep'

            MDLabel:
                text: "goat league screen"
                pos_hint: {"center_x": 0.93, "center_y": 0.6}

    # Creating the toolbar at top of the screen
    MDToolbar:
        id: toolbar
        pos_hint: {"top": 1}
        title: "GoatMentor"
        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
        md_bg_color: get_color_from_hex("#016064")

    # Screen manager to navigate between multiple screens
    MDNavigationLayout:
        ScreenManager:
            id: screen_manager

            # Creating profile screen
            Screen:
                name: "profile"

                MDLabel:
                    text: "Profile screen"
                    halign: "center"

            # Creating best results screen
            Screen:
                name: "best results"

                MDLabel:
                    text: "Best Results screen"
                    halign: "center"

            # Creating logout screen
            Screen:
                name: "logout"

                MDLabel:
                    text: "Logout screen"
                    halign: "center"

            # Creating settings screen
            Screen:
                name: "settings"

                MDLabel:
                    text: "Settings screen"
                    halign: "center"

            Screen:
                name: "screen 1"

                MDLabel:
                    text: "Settings screen"
                    halign: "center"

        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                screen_manager: screen_manager
                nav_drawer: nav_drawer

**Comment by HeaTTheatR** [comment]
@Heddaolsen Please, edit your comment so that it can be understood.
