### ISSUE TITLE
MDDataTable pagination issue

### ISSUE THREAD

**Issue by tksundar** [kivymd/KivyMD#621]
### Description of the Bug
When you have less number of rows than rows/page and use_pagination is set to True, datatable still shows pagination controls and allow clicking on the right arrow. On clicking this app crashes with index out of bounds
`MDDataTable` is created in the `get_table()` method

### Code and Logs

```
from kivy.metrics import dp
from kivy.properties import ListProperty, BooleanProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.screenmanager import Screen
from kivymd.uix.datatables import MDDataTable

import tryout

sort_param = ''


def parsePdf(pdf, password):
    products = tryout.read_pdf(pdf, password)
    return products


def get_sort_key(obj):
    if sort_param == 'symbol':
        return obj.symbol
    if sort_param == 'name':
        return obj.name
    if sort_param == 'quantity':
        return obj.quantity
    if sort_param == 'price':
        return obj.price
    if sort_param == 'nav':
        return obj.nav


def sort(param, pf_data):
    global sort_param
    sort_param = param
    pf_data.sort(key=get_sort_key, reverse=True if param == 'quantity' or param == 'price' or param == 'nav' else False)
    for pf in pf_data:
        print(pf)


class PnLScreen(Screen):
    data = ListProperty(defaultvalue=[])
    processing = BooleanProperty(defaultvalue=False)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        tryout.get_nse_prices()
        tryout.get_bse_prices()
        tryout.get_isin_to_symbol_map()

    def go_home(self, instance):
        print("called from %s" % instance.text)
        # will figure out how to go home!

    def build(self):
        return self

    def get_table(self, data):
        row_data = []
        for item in data:
            if item.nav == 0:
                continue
            row = [item.name[:40], item.quantity, item.price, item.nav]
            row_data.append(row)

        table = MDDataTable(
            size_hint=(0.9, 0.9),
            pos_hint={'center_x': 0.5, 'center_y': 0.5},
            use_pagination=True,
            rows_num=10,
            check=False,
            column_data=[
                ("Name", dp(30)),
                ("Quantity", dp(30)),
                ("Price", dp(30)),
                ("NAV", dp(30)),
            ],
            row_data=row_data
        )

        return table

    def make_widget(self):
        self.processing = True
        pf_data = list(tryout.product_dict.values())
        pf_nav = 0
        for pi in pf_data:
            print(pi)
            pf_nav += pi.nav
        pf_nav = round(pf_nav, 2)
        sort("nav", pf_data)
        data = pf_data
        box = BoxLayout(orientation='vertical')
        button = Button(text='NAV is ' + str(pf_nav), size_hint_y=None)
        button.bind(on_press=self.go_home)
        box.add_widget(button)
        # ---------------- lambda x: self.go_home not working. Need more investigation!
        # toolbar = MDToolbar(title='Net Asset Value : INR ' + str(pf_nav))
        # toolbar.md_bg_color = (.2, .2, .2, 1)
        # toolbar.left_action_items = [["home", lambda x: self.go_home]]
        # box.add_widget(toolbar)
        floatLayOut = FloatLayout()
        table = self.get_table(data)
        floatLayOut.add_widget(table)
        box.add_widget(floatLayOut)
        return box


```
### Logs
Traceback (most recent call last):
   File "C:/dev/mark2market/main.py", line 137, in <module>
     Mark2MarketApp().run()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 166, in <module>
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\datatables.py", line 624, in set_next_row_data_parts
     self.set_row_data()
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\datatables.py", line 524, in set_row_data
     for row in self._row_data_parts[self._rows_number]:
 IndexError: list index out of range

### Screenshots

Add images to explain us this bug. Paste urls here.
![datatable](https://user-images.githubusercontent.com/53440744/97399482-448b8780-1913-11eb-899a-9ccb0f87eb67.png)

### Versions

* OS: Windows 10
* Python: 3.8
* Kivy: 2.0.0rc4
* KivyMD: Version: 0.104.1 ( with a local modification for fixing orientation )

**Comment by brunocpradom** [comment]
I was facing the same issue . Than I find a solution that solve for me the question.
I edited the file datatable.py . 
I put a try / except in the function set_next_row_data_parts(), that is called when switching the pages of the table.
 in line 616 and the app don't crash anymore. 
```
def set_next_row_data_parts(self, direction):
        """Called when switching the pages of the table."""
        try:
            if direction == "forward":
                self._rows_number += 1
                self.pagination.ids.button_back.disabled = False
            elif direction == "back":
                self._rows_number -= 1
                self.pagination.ids.button_forward.disabled = False
            
            self.set_row_data()
            self.set_text_from_of(direction)
            
            if self._to_value == len(self.row_data):
                self.pagination.ids.button_forward.disabled = True
            if self._current_value == 1:
                self.pagination.ids.button_back.disabled = True
        except:
            pass ```

**Comment by shashi278** [comment]
@brunocpradom but it has already been fixed in the master

**Comment by brunocpradom** [comment]
@shashi278 I have recent reinstalled the kivymd version 0.104.1 with pip. Earlier this week
And I was facing this problem.
It's weird

**Comment by shashi278** [comment]
@brunocpradom It's been updated in the master branch so you need to install development version from master for it to work.
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by HeaTTheatR** [comment]
@brunocpradom There is nothing strange. In PyPi does not have the latest version of the library. If you want to use the new APIs, install the library from their branch master.

**Comment by brunocpradom** [comment]
Thank you @HeaTTheatR
