### ISSUE TITLE
size issue MDDialog

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#631]
### Description of the Bug

more space between the dialog and window especially in mobile (redmi note 7s, android 10)

### Code and Logs
used kitchen_sink demo app for test

### Screenshots
![3](https://user-images.githubusercontent.com/63696279/97967111-c6cbee00-1de2-11eb-8a24-f92ecce68005.jpg)    ![2](https://user-images.githubusercontent.com/63696279/97967119-c7fd1b00-1de2-11eb-9490-b3b6c7d23848.jpg)    ![1](https://user-images.githubusercontent.com/63696279/97967122-c92e4800-1de2-11eb-8d78-50f3c3c42292.jpg)

**Comment by shashi278** [comment]
I think a better way to resolve this would be to add a property something like `width_offset` with default current offset value in `MDDialog` which will allow you to customize the space b/w screen and the dialog.

**Comment by kulothunganug** [comment]
@shashi278 does making this [function](https://github.com/kivymd/KivyMD/blob/5aad2e70021d426850282b62abae885d5b7a9577/kivymd/uix/dialog.py#L562) into this :point_down:  will be fix?
```py
    def update_width(self, *args):
        self.width = dp(max(
            self.height + dp(48),
            min(
                dp(560) if DEVICE_TYPE == "desktop" else dp(280),
                Window.width - dp(48),
            ),
        ))
```

**Comment by shashi278** [comment]
@Kulothungan16 no, it won't fix that. You need to change that `dp(48)` as in `Window.width - dp(48)` with a class property with default value as `dp(48)` so that one can change it by setting that property.
I encourage you to fix this and create a PR. Or if you need more help, let me know :)

**Comment by kulothunganug** [comment]
> @Kulothungan16 no, it won't fix that. You need to change that `dp(48)` as in `Window.width - dp(48)` with a class property with default value as `dp(48)` so that one can change it by setting that property.
> I encourage you to fix this and create a PR. Or if you need more help, let me know :)

@shashi278 i had no idea on this bro

**Comment by shashi278** [comment]
@Kulothungan16 no problem. I'll create a PR then :)

**Comment by shashi278** [comment]
@Kulothungan16 It's been fixed in the master so I'm closing it now but feel free to open if you run into issues again :)
