### ISSUE TITLE
MDDropdown menu call back not working

### ISSUE THREAD

**Issue by Hareesh10** [kivymd/KivyMD#632]
### Description of the Bug

Call back function not working for me for any kivymd examples.
Tried all examples available in kivymd docs

### Code and Logs
#Examples from https://kivymd.readthedocs.io/en/latest/components/menu/

### Versions

* OS: Windows 10
* Python: 3.6.8
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by shashi278** [comment]
I cannot reproduce the error. Also suggesting you to use the master version.
`pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by Hareesh10** [comment]
I did pip install https://github.com/kivymd/KivyMD/archive/master.zip, but no changes. I resolved issue by changing python version to 3.7

**Comment by Hareesh10** [comment]
pip install https://github.com/kivymd/KivyMD/archive/master.zip doesn't made any change, I manually added kivyMD folder in venv folder  and it worked.
