### ISSUE TITLE
MDDatatable doesn't display correctly if there is only one row

### ISSUE THREAD

**Issue by tksundar** [kivymd/KivyMD#637]
### Description of the Bug

`MDDataTable `does not display all columns of a row if there is only one row in row_data

### Code and Logs

The below code is Example.py modified to have just one row

```python
from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        data_tables = MDDataTable(
            size_hint=(0.9, 0.6),
            use_pagination=True,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(30)),
                ("Column 2", dp(30)),
                ("Column 3", dp(30)),
                ("Column 4", dp(30)),
                ("Column 5", dp(30)),
            ],
            row_data=[
                (f"{i + 1}", "1", "2", "3", "4", "5") for i in range(1)
            ],
        )
        layout.add_widget(data_tables)
        return layout


Example().run()
![datatable_single_row_bug](https://user-images.githubusercontent.com/53440744/98094547-72db0b00-1eaf-11eb-951e-9c46b17bc151.png)

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![datatable_single_row_bug](https://user-images.githubusercontent.com/53440744/98094596-80909080-1eaf-11eb-9d74-7d0ee6db4dba.png)

### Versions

* OS: WIndows 10
* Python: 3.8
* Kivy: 2.0.0rc4
* KivyMD: 0.104.1

**Comment by tksundar** [comment]
Adding a dummy row works for me. But this may not be ok for everybody

**Comment by shashi278** [comment]
I have it tested on Linux. Working fine for me.

**Comment by kulothunganug** [comment]
@tksundar check whether ur `KivyMD` is up-to-date, if not run the below commands
1. `pip uninstall kivymd`
2. `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by shashi278** [comment]
I have the latest KivyMD. However, I've a lower version of Kivy.

**Comment by tksundar** [comment]
Does the latest version has the fix for the orientation bug (horizontal doesn't work for RecycleGridLayout)?

**Comment by shashi278** [comment]
By latest I meant the version with the latest fixes( in this case, master as suggested by @Kulothungan16  ) so yeah it's up-to-date and well, I supppose it has the fix for the orientation bug.

**Comment by Kulothungan16** [comment]
Try with Kivy 2.0.0rc4

**Comment by shashi278** [comment]
@tksundar I'm not sure if it has something to do with the Kivy version. Also, for me it's 1.11.1. We can wait to see if someone with  Kivy 2.0.0rc4 can reproduce this error.

**Comment by tksundar** [comment]
> @tksundar check whether ur `KivyMD` is up-to-date, if not run the below commands
> 
> 1. `pip uninstall kivymd`
> 2. `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

I tried this. The orientation : 'horizontal' is still an issue with kivy 20.0.0rc4. So I couldn' test the 1 row problem

`   File "C:\dev\mark2market\PandLScreen.py", line 47, in get_table
     table = MDDataTable(
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\datatables.py", line 1315, in __init__
     self.table_data = TableData(
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivymd\uix\datatables.py", line 660, in __init__
     super().__init__(**kwargs)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\recycleview\__init__.py", line 409, in __init__
     super(RecycleView, self).__init__(**kwargs)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\recycleview\__init__.py", line 201, in __init__
     super(RecycleViewBehavior, self).__init__(**kwargs)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\scrollview.py", line 539, in __init__
     super(ScrollView, self).__init__(**kwargs)
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 138:
 ...
     136:        height: self.minimum_height
     137:        width: self.minimum_width
 >>  138:        orientation: "vertical"
     139:        multiselect: True
     140:        touch_multiselect: True
 ...
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
   File "C:\Apps\Anaconda3\envs\mark2market\lib\site-packages\kivy\lang\builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1253, in kivy.properties.OptionProperty.check`

**Comment by kevin-schumann** [comment]
Updating to the kivy master branch resolves the issue. This doesn't seem to be a kivymd bug.

**Comment by HeaTTheatR** [comment]
@kevin-schumann 
No, this is a bug.
![Снимок экрана 2021-03-14 в 10 15 58](https://user-images.githubusercontent.com/16930280/111060497-56c72600-84ae-11eb-8be6-002f2ce4ec32.png)

**Comment by kevin-schumann** [comment]
@HeaTTheatR I know that this is a bug. All I am saying is that this doesn't seem to be a bug within kivymd. Updating **kivy**  to its master branch resolves this bug.

**Comment by HeaTTheatR** [comment]
@kevin-schumann Fixes only the position of the root widget. But, rows in columns, as we can see, unfortunately, are not displayed if we use a row.

**Comment by kevin-schumann** [comment]
When using the kivy v2.1.0.dev0 this bug doesn't occur anymore. @HeaTTheatR  and I confirmed this via other communication channels.

**Comment by mp-007** [comment]
just for info
https://github.com/kivy/kivy/issues/7255

**Comment by HeaTTheatR** [comment]
@marcets ???

**Comment by mp-007** [comment]
@HeaTTheatR this bug is created in kivy 2.0.0 release as you can see in kivy issue 7255. It is now fix in the kivy master branch. MDDatatable use RecycleGridLayout.

**Comment by vimalva777** [comment]
can u help me install this version of  kivy v2.1.0 ,  ?     i am new to kivy

**Comment by mp-007** [comment]
@vimalva777 
```
python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/master.zip"
```
