### ISSUE TITLE
clear widgets in MDTabs

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#643]
### Description of the Feature

adding clear_ widgets method to MDTabs so after I call this method the MDtabs children are removed 
so the MDTabs will be like following after I run the clear_widgets method
### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
Screen:
    MDTabs:
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

**Comment by HeaTTheatR** [comment]
@hussam132 Sorry, I don't understand the essence of the question.

**Comment by ghost** [comment]
If I use the  [on_ref_press()](https://kivymd.readthedocs.io/en/latest/components/tabs/index.html) to close the MDTabBase it close any except the last tabbase so I ask for method that will close the all tabsbase even the last tabbase
