### ISSUE TITLE
Minor color definition issue in chip.py's code 

### ISSUE THREAD

**Issue by DaedlyKitten** [kivymd/KivyMD#647]
### Description of the Bug

in the last line of chip.py from ..\kivymd\uix\,   chip.color = theme_cls.primary_color

might should have been chip.color =self.color

as i noticed that if I set a custom color to MDChip inside a MDChooseChip, pressing to select one of them will cause all others to revert back to the default color, which is fixed with changing this line 

chip.color = theme_cls.primary_color
to 
chip.color = self.color

### Code and Logs

```python
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if not self.color:
            self.color = self.theme_cls.primary_color
    def on_icon(self, instance, value):
        if value == "":
            self.icon = "checkbox-blank-circle"
            self.remove_widget(self.ids.icon)
    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            md_choose_chip = self.parent
            if self.selected_chip_color:
                Animation(
                    color=self.theme_cls.primary_dark
                    if not self.selected_chip_color
                    else self.selected_chip_color,
                    d=0.3,
                ).start(self)
            if issubclass(md_choose_chip.__class__, MDChooseChip):
                for chip in md_choose_chip.children:
                    if chip is not self:
                        chip.color = theme_cls.primary_color
```

### Versions

* OS: Win10 
* Python: v3.7.6
* Kivy: v2.0.0rc4
* KivyMD:  v0.104.1

**Comment by shashi278** [comment]
@DaedlyKitten Thanks for pointing it out! Just tested your suggestion, it doesn't fix the issue. It'll be looked into.
