### ISSUE TITLE
Button Speed Dial Icons corrupted with pango text provider

### ISSUE THREAD

**Issue by azzadeen** [kivymd/KivyMD#659]
### Description of the Bug

When switching the text provider to pango, icons for the MDFloatingActionButtonSpeedDial are not showing correctly.
ScreenShot of the KitchenSink demo app attached along with Kivy Logs to show the Text Provider switched to Pango.
Only modification done in the KitchenSink main.py is adding the following line at the top of the file to force Text Provider to pango.
os.environ['KIVY_TEXT'] = 'pango'

### Screenshots

![Screen Shot 2020-11-10 at 9 03 56 AM](https://user-images.githubusercontent.com/1346360/98634683-c8db0300-2334-11eb-8c2e-7de23497861d.png)

### Versions

* OS: MacOS 10.14.6
* Python: 3.8.5
* Kivy: 2.0.0rc4
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@azzadeen `os.environ ['KIVY_TEXT'] = 'pango'` - what for?

**Comment by azzadeen** [comment]
To support RTL languages and fonts.

**Comment by azzadeen** [comment]
The same issue goes for the chips with icons.

**Comment by HeaTTheatR** [comment]
@azzadeen Everything is displayed well on the `Mac`. You may not have installed additional libraries for `pango` to work.

**Comment by azzadeen** [comment]
@HeaTTheatR I have the following with each dependencies installed correctly using home-brew:
pango: 1.46.2
cairo: 1.16.0_3
fontconfig: 2.13.1
fribidi: 1.0.10
glib: 2.66.2
harfbuzz: 2.7.2

The test was redone after upgrading pango to v 1.48.0 with the same results!
I stared to think it could be a limitation from kivy side but you mentioned it displayed well on Mac for you. Any idea what could be missing libraries I should be installing?
FYI: [kivy Pango Text Provider](https://github.com/kivy/kivy/blob/2.0.0rc4/kivy/core/text/text_pango.py)

**Comment by azzadeen** [comment]
Tested with Raspbian buster with raspberry pi 4. Same results found on Mac for both Speed Dial and chips with icons. Icon images corrupted for both.

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
