### ISSUE TITLE
Ability to provide custom color to column data in MDDataTable

### ISSUE THREAD

**Issue by tksundar** [kivymd/KivyMD#663]
### Description of the Feature

Presently the column data styling is non-configurable. That is, one can not add custom font(from available fonts) or custom color to any label. There are numerous use cases where this feature is desirable. For example, for the app I am working on, I would like the ability to add, green or red color to numeric data depending upon certain  criteria.  For example, in the screenshot, I have data available to decide whether the price data or nav data should be in green or red. But I have no way of passing this info in row_data. 

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![nav_screen](https://user-images.githubusercontent.com/53440744/99062630-49b22d00-25c9-11eb-98b6-7e1794ee0be2.jpg)

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@tksundar Use `markup` strings.

**Comment by tksundar** [comment]
How? I can do this for the kivy label with something like like this 
text = '[color=FF0000]'+ str(nav) +'[/color]' and then this
label = Label(text=text, markup=True) for nav to appear in red. 
If I do this for a column data in MDDataTable, it doesn't work.  I don't have a way to pass markup =True .  What am i missing?

**Comment by HeaTTheatR** [comment]
@tksundar 
```python
from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        data_tables = MDDataTable(
            size_hint=(0.9, 0.6),
            use_pagination=True,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(30)),
                ("[color=#52251B]Column 2[/color]", dp(30)),
                ("Column 3", dp(30)),
                ("[size=32][color=#C042B8]Column 4[/color][/size]", dp(30)),
                ("Column 5", dp(30)),
            ],
            row_data=[
                (
                    f"{i + 1}",
                    "[color=#297B50]1[/color]",
                    "[color=#C552A1]2[/color]",
                    "[color=#6C9331]3[/color]", "4", "5") for i in range(50)
            ],
        )
        layout.add_widget(data_tables)
        return layout


Example().run()
```

**Comment by tksundar** [comment]
on which version is this available? I am using 0.104.1. Also if i need to use a newer version of kivymd , which is the compatible kivy version that will work with this feature

**Comment by HeaTTheatR** [comment]
@tksundar We do not maintain backward compatibility with older versions. Use the latest version from the master branch.

**Comment by tksundar** [comment]
Sure. Will it work with kivy 2.0.0rc4?

**Comment by HeaTTheatR** [comment]
@tksundar Yes.
