### ISSUE TITLE
MDSpinner can't change color

### ISSUE THREAD

**Issue by Landris18** [kivymd/KivyMD#673]
### Description of the Bug

I can't change spinner color

* OS: Manjaro
* Python: 3.8
* Kivy: 1.11
* KivyMD: 0.104.2

**Comment by kulothunganug** [comment]
@Landris18 Please, Write good and clear description, paste code sample and, if possible, attach a screenshot.

**Comment by Landris18** [comment]
@Kulothungan16k, okay` 
         

       MDSpinner:

                id : loader

                size_hint: None, None

                size: dp(20), dp(20)

                pos_hint: {'center_x':0.75, 'center_y':0.29}

                active: True

                palette: 0.38627450980392155, 0.8431372549019608, 0.596078431372549, 1

                color: 0.48627450980392155, 0.8431372549019608, 0.596078431372549, 1`

I want to change the color but it doesn't work !

**Comment by HeaTTheatR** [comment]
@Landris18 
Reinstall KivyMD library from master branch.

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:

    MDSpinner:
        size_hint: None, None
        size: dp(20), dp(20)
        active: True
        palette: 0.38627450980392155, 0.8431372549019608, 0.596078431372549, 1  # must be list
        color: 0.48627450980392155, 0.8431372549019608, 0.596078431372549, 1  # it work
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```
