### ISSUE TITLE
Can't create MDTextFieldRound using python.

### ISSUE THREAD

**Issue by Alkabann** [kivymd/KivyMD#674]
### Description of the Bug

First example is a working example of MDTextFieldRect creation with python.
Second example is a working example of MDTextFieldRound creaction with kv.
Third example is a bugging example of MDTextFieldRound creaction with python.

### Code and Logs

```
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.textfield import MDTextFieldRect

from kivy.lang import Builder

class App(MDApp):
    def build(self):
        self.screen = Screen()
        return self.screen

    def on_start(self):
        l = BoxLayout()
        self.screen.add_widget(l)
        w = MDTextFieldRect()
        l.add_widget(w)

App().run()
```

```
from kivymd.app import MDApp
from kivy.lang import Builder

KV = '''
Screen:
    
    MDTextFieldRound:
        icon_left: 'key-variant'
        normal_color: app.theme_cls.accent_color
'''

class App(MDApp):
    def build(self):
        self.screen = Builder.load_string(KV)
        return self.screen

App().run()
```

```
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.textfield import MDTextFieldRound

from kivy.lang import Builder

class App(MDApp):
    def build(self):
        self.screen = Screen()
        return self.screen

    def on_start(self):
        l = BoxLayout()
        self.screen.add_widget(l)
        w = MDTextFieldRound()
        l.add_widget(w)

App().run()
```

[kivy_20-11-18_66.txt](https://github.com/kivymd/KivyMD/files/5561150/kivy_20-11-18_66.txt)

### Versions

* OS: Windows
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by kulothunganug** [comment]
@Alkabann installing master version of kivymd `pip install https://github.com/kivymd/KivyMD/archive/master.zip` will fix ur problem

**Comment by Alkabann** [comment]
So it's a version problem @Kulothungan16 ? I don't understand  why installing this will work better than the last actual version (which should be patch if an oldest version works). :/

**Comment by kulothunganug** [comment]
@Alkabann sorry bro, i also getting the same problem 😐
