### ISSUE TITLE
clicking on icons of MDDropdown item doesnt select the item at all. Kivy MD

### ISSUE THREAD

**Issue by mannutheman3** [kivymd/KivyMD#678]
### Description of the Bug

When i develeped an app with dropdown list and used code from kitchensink project, i found that the icons on the left side of every items in drop down are just for show, clicking or touching on them doesnt do anything, If those icons are place to just give it a nice look then its fine, but if they are also meant to be clicked to select the item then there is surely a bug. even in kitchen sink app the dropdown item's icons are not clickable or clicking them doesn't do anything.

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: Android, windows,
* Python: 3.7.5
* Kivy: 1.11.1
* KivyMD: master

**Comment by shashi278** [comment]
Does it work when you click on the text? Also provide a minimal code example.
