### ISSUE TITLE
MDTextFieldRound color bug

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#684]
### Description of the Bug

- when setting a custom color in `MDTextFieldRound` it works. when on focus (first time) and unfocus the color changes
to `text_color`.
- and also the `hint_text_color` attr not working.

#### icon color
```python
from kivymd.app import MDApp
from kivy.lang import Builder


KV = """
#: import gch kivy.utils.get_color_from_hex


AnchorLayout:
	MDTextFieldRound:
		hint_text: "Select dates"
		icon_left: "calendar"
		icon_left_color: (1, 0, 0, 1)
		size_hint: (.7, .1)

"""


class Example(MDApp):
	def build(self):
		return Builder.load_string(KV)


Example().run()
```
#### hint text color not works
```py
from kivymd.app import MDApp
from kivy.lang import Builder


KV = """
#: import gch kivy.utils.get_color_from_hex


AnchorLayout:
	canvas:
		Color:
			rgba: gch("#5D1049")
		Rectangle:
			size: self.size
			pos: self.pos
	MDTextFieldRound:
		hint_text: "Select dates"
		icon_left: "calendar"
		icon_left_color: gch("#C79EBE")
		size_hint: (.7, .07)
		color_active: gch("#720D5D")
		normal_color: gch("#720D5D")
		line_color: (0, 0, 0, 0)
		foreground_color: gch("#C79EBE")
		hint_text_color: (1, 0, 0, 1) # not works
"""


class Example(MDApp):
	def build(self):
		return Builder.load_string(KV)


Example().run()
```

### Screenshots
![bug-txt](https://user-images.githubusercontent.com/63696279/100057579-c48f0980-2e4d-11eb-91e8-a86dccf9533b.gif)

### Versions

* OS: Debian 10
* Python: v3.9.0
* Kivy: v2.0.0rc4
* KivyMD: master

**Comment by shashi278** [comment]
@Kulothungan16 If possible pls create a new issue for `hint_text_color` as it's a different issue and may be fixed later( because I think it needs more analysis)

**Comment by kulothunganug** [comment]
@shashi278 not fixed (on master)
![bug-txt](https://user-images.githubusercontent.com/63696279/100083826-f913bd00-2e6f-11eb-9f55-fa721c59126d.gif)

**Comment by shashi278** [comment]
@Kulothungan16 kindly re-check if you're using the updated version. It's working on my end.
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/37111736/100084627-02515980-2e71-11eb-9cc7-6ae7ff403997.gif)

**Comment by kulothunganug** [comment]
@shashi278 no bro, mine is up-to-date
in log `[[1;32mINFO[0m   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2020-11-24 (installed at "/usr/local/lib/python3.9/site-packages/kivymd/__init__.py")`
i also checked it manually.

**Comment by shashi278** [comment]
I see. Can you verify the code changes by looking into your local `kivymd/uix/textfield.py` inside `MDTextFieldRound`? Changes should be similar to those in #686

**Comment by kulothunganug** [comment]
@shashi278 ya it's same that's why i telled that 
> i also checked it manually.

**Comment by shashi278** [comment]
@Kulothungan16 You seem to be right :thinking: 
Turned out my fork wasn't updated. I'm opening it again and I'll try to fix it up soon.

**Comment by shashi278** [comment]
@Kulothungan16 It should be good now :crossed_fingers:

**Comment by Xenshirn** [comment]
have you been tried this:
theme_icon_right_color  : 'custom'
icon_right_color :  rgba_color

**Comment by HeaTTheatR** [comment]
@Kulothungan16 https://kivymd.readthedocs.io/en/latest/components/textfield/#round-mode
