### ISSUE TITLE
Theme_cls.style changes toolbar specific color

### ISSUE THREAD

**Issue by ElLoko233** [kivymd/KivyMD#691]
### Description of the Bug

when i change the theme_cls.style while the app is running, all my toolbar's specific_color change to default color

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
MDScreen:
    name: "HomePage"

    BoxLayout:
        orientation: 'vertical'

        MDToolbar:
            right_action_items: [['flashlight', app.change_style]]
            specific_text_color: [226 / 255, 19 / 255, 19 / 255, 1]
'''


class Test(MDApp):


    def build(self):
        return Builder.load_string(KV)

    def change_style(self, instance):
        # Changing the style
        self.theme_cls.theme_style = 'Light' if self.theme_cls.theme_style == 'Dark' else 'Dark'

        # Changing icon
        instance.icon = 'flashlight-off' if self.theme_cls.theme_style == 'Dark' else 'flashlight'



Test().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: windows
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: latest version till 2020-11-25

**Comment by shashi278** [comment]
Please make sure the minimal code you're providing is error-free

**Comment by shashi278** [comment]
Moreover, this is an expected behavior. `specific_text_color` changes based on `theme_style`. So if you're changing `specific_text_color`, make sure you're taking into account the `theme_style`.
You can do something like,
```kivy
MDToolbar:
    specific_text_color: [some_color] if app.theme_cls.theme_style == "Light" else [some_other_color]
```
