### ISSUE TITLE
icon of button not showing 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#708]
### Description of the Bug

icon of button not showing 

### Code and Logs

```python
from kivy.uix.screenmanager import Screen

from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial


class Example(MDApp):
    data = {
        'language-python': 'Python',
        'language-php': 'PHP',
        'language-cpp': 'C++',
    }

    def build(self):
        screen = Screen()
        speed_dial = MDFloatingActionButtonSpeedDial()
        speed_dial.data = self.data
        speed_dial.rotation_root_button = True
        screen.add_widget(speed_dial)
        return screen


Example().run() 

```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here
![image](https://user-images.githubusercontent.com/57060638/101193604-d4df8980-3682-11eb-8016-ba0d81a94557.png)

### Versions

* OS: kubuntu 18.04
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@Sahil-pixel This is most likely due to dependencies that you have not installed.

**Comment by Sahil-pixel** [comment]
but lower version is showing icons... please tell me which dependencies I have to Install ..

**Comment by kulothunganug** [comment]
@Sahil-pixel please see https://github.com/kivymd/KivyMD/issues/630
