### ISSUE TITLE
MDSwitch color not working properly

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#720]
### Description of the Bug

The property `thumb_color_down` doesn't change the trail of the MDSwitchButton, it stills primary_color with low aupacity.
Except of that. on switch between 'Dark' and 'Light' mode the MDSwitchButton color resets back to primary color, ignoring the `thumb_color_down` property. 

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
Screen:
    MDTextButton:
        text: "change theme style!"
        on_release: app.theme_cls.theme_style = "Dark" if app.theme_cls.theme_style == "Light" else "Light"
        pos_hint: {"center_x":.5,"center_y":.7}

    MDSwitch:
        id: negotiable_switch
        thumb_color_down: 1,0,1,1
        pos_hint: {"center_x":.5,"center_y":.8}

'''

class TestCard(MDApp):
    def on_start(self):
        self.theme_cls.theme_style = "Light"

    def build(self):
        return Builder.load_string(KV)


TestCard().run()
```
python: 3.9
kivyMD library: 14/12/20 updated

**Comment by HeaTTheatR** [comment]
@tthomas66 
```
    MDSwitch:
        thumb_color: 1, 0, 1, 1
        thumb_color_down: 1, 0, 1, 1
```

**Comment by ghost** [comment]
![2020-12-15 02-14-23](https://user-images.githubusercontent.com/71156350/102151420-80ef5480-3e7b-11eb-93f9-6217c480d2f8.gif)

Don't see any fix here. As you can see the thumb starts with the color given `1, 0, 1, 1` but when the app switches to Dark Mode the color changes to blue. Except of this, the trail of the button is always Light Blue no matter what color you give with `thumb_color`

**Comment by sagarhm** [comment]
How to change theme_style color insted of light ineeded coustm color
