### ISSUE TITLE
How to open MDDataTable after clicking a button?

### ISSUE THREAD

**Issue by BS-98** [kivymd/KivyMD#722]
Hi,

I wrote some code a few months ago and I implemented MDDataTable showing after clicking a button. I made this just by **self.data_table.open()**. I see that at this moment it does not work and I do not know why. 

Could tell me (or show a simple example) how to open MDDataTable after clicking on button?

I would be grateful for any help.

**Comment by HeaTTheatR** [comment]
@BS-98 
https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/libs/kv/data_tables.kv
https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/libs/baseclass/data_tables.py
