### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by dovahkinnn** [kivymd/KivyMD#728]
### Description of the Bug
how to refresh mdlist in item?

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@dovahkinnn https://kivymd.readthedocs.io/en/latest/components/refresh-layout/
