### ISSUE TITLE
MDNavigationDrawer does not close when clicking on an empty area

### ISSUE THREAD

**Issue by IvanNazaruk** [kivymd/KivyMD#732]
### Description of the Bug
MDNavigationDrawer does not close on android when clicking on an empty area

### Code

```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp

KV = '''
Screen:

    MDNavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawerset_state("open")]]

                    Widget:


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
'''


class ContentNavigationDrawer(BoxLayout):
    pass


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)


TestNavigationDrawer().run()
```

### Video
https://user-images.githubusercontent.com/46572469/103106189-07eeba80-463c-11eb-9241-3f8aad200d5c.mp4

### Versions

* OS: Android 10
* Python: v3.8.1
* Kivy: v2.0.0rc3
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@Ivanzzzc Have you tested the `MDNavigationDrawe`r on other devices?

**Comment by IvanNazaruk** [comment]
I tested this on another device:

https://user-images.githubusercontent.com/46572469/103127214-862d7a00-4699-11eb-95ca-27559384bcfe.mp4

Yes, on the other device it works.
But on my device in the KivyMD app it also works, but not in my app. _(I noticed that the closing works, but in a 1 in 100 case)_



https://user-images.githubusercontent.com/46572469/103128005-50d65b80-469c-11eb-8f24-960f9a3ca830.mp4

[Better quality](https://drive.google.com/file/d/1LSIkpZdKPPs87AahTEHn6pCCzH8M_iKG/view?usp=sharing)

**Comment by HeaTTheatR** [comment]
@Ivanzzzc Yes, this is strange, you need to figure it out.

**Comment by HeaTTheatR** [comment]
@Ivanzzzc Why did you close the issue?

**Comment by IvanNazaruk** [comment]
I think the problem is only with my device and not with MDNavigationDrawer, because everything works fine on other devices.
For that reason, I closed the issue.

Maybe I'm wrong in thinking that the problem is with my device
