### ISSUE TITLE
Datatables with async data

### ISSUE THREAD

**Issue by nihilok** [kivymd/KivyMD#735]
### Description of the Bug
There are times when I'm returning an empty table. The pagination buttons by default allow a click of the forward button, which throws up an index out of range exception.
I got round it by adding the following to the datatables.py line 552:
```
    def set_text_from_of(self, direction):
        ...
        if self.pagination:
            if direction == "forward" and self._row_data_parts:     # checking if there are pages
        ...
```

I will probably try to include a condition in my code that sets pagination to False if there is now row data, but it could be in the source code too to check for that. Should I create a pull request or what?

### EDIT: 
I now removed the previous check and simply changed line 940 to:

`        if self.use_pagination and self.row_data:`

this just doesn't add the pagination menu if there's no data. I don't know if this is desirable in all cases but avoids the initial issue and is a little cleaner for my purposes.

### Versions

* OS: Win
* Python: 3.7
* Kivy: v1.11.1
* KivyMD: v0.104.1

**Comment by shashi278** [comment]
Hi! I think by empty you mean table with no `row_data` attribute, right? I could not reproduce this issue. The pagination buttons are shown but are not clickable.

**Comment by shashi278** [comment]
Could you reproduce it on your end @HeaTTheatR?

**Comment by HeaTTheatR** [comment]
@HeaTTheatR This does not work

**Comment by shashi278** [comment]
I'm sorry, I didn't get you. Does it throw an index error when using datatable without `row_data`? @HeaTTheatR

**Comment by HeaTTheatR** [comment]
@shashi278 Sorry. I mean, your last pull request (https://github.com/kivymd/KivyMD/pull/747) isn't working.

**Comment by nihilok** [comment]
I mean I have the row_data attribute which is assigned by an api call which can return None. In this case i was able to click the forward button and it threw the IndexError

EDIT: code example:

```
 data_tables = MDDataTable(
                    size_hint=(0.9, 1),
                    pos_hint={'center_x': 0.5},
                    use_pagination=True,
                    column_data=[
                        ("Date", dp(25)),
                        ("New Cases", dp(25)),
                        ("New Deaths", dp(25)),
                    ],
                    row_data=[(item['date'], item['newCases'], (item['newDeaths'] if item['newDeaths'] else item['newDeathsByPublishDate'])) for item in data['data']],
                )
```

**Comment by shashi278** [comment]
@nihilok is it like, if I've Initialized DataTable with row_data and later if I set row_data as a empty list then the forward button is clickable and gives an index error?

**Comment by nihilok** [comment]
> @nihilok is it like, if I've Initialized DataTable with row_data and later if I set row_data as a empty list then the forward button is clickable and gives an index error? 

Yes that's correct I think. But I think it may have also happened even if the row_data is an empty list from the beginning. I'll test it when I have some time

**Comment by shashi278** [comment]
> it may have also happened even if the row_data is an empty list from the beginning

I tested it and it's not the problem.

Please provide a minimal working example to verify this issue against.
