### ISSUE TITLE
Icons with \U definitions not working on android

### ISSUE THREAD

**Issue by sanderland** [kivymd/KivyMD#737]
### Description of the Bug

Using an MDCheckbox/MDIcon with an icon which has an 8 byte definition such as "checkbox-blank-off-outline" results in a blank outline in android.

Possibly this is related to the code points not existing.

### Screenshots

Android
![image](https://user-images.githubusercontent.com/48946947/103172523-6db58f00-4854-11eb-93d6-29efd8722e80.png)

There is a checkbox on the right, but a blank space is shown. 

### Attempts to find the cause
* The `.text' property is set correctly, it is not missing in md_icons

* Using unicodedata.name we see that the codepoints used don't exist. Trying to find code points that also do not have a name with an ord() < 65536 finds 'zip-box', which works on android. There are no code points > 65536 in the icons list which have a name in this package.

### Workaround
Only use icons with code points < 65536

### Versions

* OS: android/buildozer
* Python: 3.7
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@sanderland  https://github.com/kivymd/KivyMD/issues/257
