### ISSUE TITLE
MDInputDialog displays widgets in background

### ISSUE THREAD

**Issue by degenerateddev** [kivymd/KivyMD#74]
When I run the KivyMD Test everything works fine, but when I try to use the `MDInputDialog` in my code the buttons and textfields show only up in the background (If I set the size_hint to `None, None` the window is small enough that I can see that the widgets are only behind the window... if I set a specific size_hint the widgets disappear again).  The solution for [this](https://github.com/HeaTTheatR/KivyMD/issues/71) issue didn't help me. I didn't really change much of the code used in the Example in the dialog.py module but if you need the source code just ask.

Thanks in advance!

**Comment by HeaTTheatR** [comment]
@neuraln3t I do not understand what you are talking about. Show me screenshot

**Comment by degenerateddev** [comment]
@HeaTTheatR When I set the size_hint to None, None
![Test1](https://user-images.githubusercontent.com/26187756/61174148-b0ba6e80-a59c-11e9-8988-cd80f6ff58f5.PNG)

And when I set the size_hint to .8, .4
![Test2](https://user-images.githubusercontent.com/26187756/61174152-be6ff400-a59c-11e9-8c34-d5abe2149ff4.PNG)

**Comment by HeaTTheatR** [comment]
@neuraln3t Send me your code.

**Comment by degenerateddev** [comment]
@HeaTTheatR I've created a Github repository. The method for the Popup screen is in the **floatlayout.py** file in the modules folder. The method is called `Popup` and it's the second `popup` variable (but both don't work the right way). The `Popup` method is called by the NavigationDrawerIconButton in the **design.kv** file (line 56)

**Comment by HeaTTheatR** [comment]
@neuraln3t Give me the link!

**Comment by degenerateddev** [comment]
@HeaTTheatR https://github.com/neuraln3t/LinguTrainer

**Comment by HeaTTheatR** [comment]
@neuraln3t Send me a minimal sample code that reproduces your problem. Your repository is full of errors!
