### ISSUE TITLE
Hint text getting overlapped with rectangular text field

### ISSUE THREAD

**Issue by AM-ash-OR-AM-I** [kivymd/KivyMD#746]
### Description of the Bug
While while using MD rectangular text field hint-text is getting overlapped with the rectangular field.

### Screenshot

![IMG_20210102_123807](https://user-images.githubusercontent.com/59698257/103452640-68928d00-4cf7-11eb-918f-76aa5781a839.jpg)

### Versions

* OS: Android (Created and deployed using Ubuntu)
* Python: 3.7
* Kivy: 2.0.0rc1
* KivyMD: Latest version form Master.

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/331
