### ISSUE TITLE
Deprecated Kivy lang template syntax used

### ISSUE THREAD

**Issue by the7dev** [kivymd/KivyMD#75]
Deprecated Kivy lang template syntax used
"[MDAccordionItemTitle@MDAccordionItemTitleLayout]".
Templates will be removed in a future version

https://github.com/HeaTTheatR/KivyMD/blob/427d9ef8c5410e73a88624337a5c932873b3bfe2/kivymd/accordion.py#L127

**Comment by HeaTTheatR** [comment]
@the7dev https://github.com/kivy/kivy/blob/master/kivy/uix/accordion.py#L314

**Comment by HeaTTheatR** [comment]
@the7dev 
![Снимок экрана 2019-07-19 в 12 56 38](https://user-images.githubusercontent.com/16930280/61527249-a7aa2100-aa24-11e9-971e-967a241fff01.png)
