### ISSUE TITLE
Custom Theme Colors

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#754]
### Description of the Feature

The Theme Color Palette and Font Choices listed in the Material Design site are meant to be indicative and not prescriptive, as both the text and the palette design tool make clear.

It should be possible to set up a template using any combination of colors and fonts - whilst at the same making it very easy to use Out of the Box with the standard MD palette.

This could be done by allowing the `colors` object in `ThemeManager` to be overridden with a custom object. This is how [@AngularMaterial](https://material.angular.io/) address the same problem,

All that would be needed is the following - I will try to send a PR with this in.

- replace all usages of `colors`  with `self.colors`.
- change `__init__` as follows:
```
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.rec_shadow = Atlas(f"{images_path}rec_shadow.atlas")
        self.rec_st_shadow = Atlas(f"{images_path}rec_st_shadow.atlas")
        self.quad_shadow = Atlas(f"{images_path}quad_shadow.atlas")
        self.round_shadow = Atlas(f"{images_path}round_shadow.atlas")
        Clock.schedule_once(lambda x: self.on_theme_style(0, self.theme_style))
        self._determine_device_orientation(None, Window.size)
        Window.bind(size=self._determine_device_orientation)
        self.colors = colors
```

You will then be able to create your own version of `color_definitions.py`, import that into your `main.py` and do the following (for instance ) in the `MDApp.__init__()`

```
self.theme_cls.colors = custom.colors
self.theme_cls.primary_palette = "Blue"
```

It is working in my app at the moment.

**Comment by kulothunganug** [comment]
Duplicate of #727

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/commit/3274d622abc0986c82719393a357b6a745e061f2
