### ISSUE TITLE
MDTooltip not working on MDLabel

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#757]
### Description of the Bug

I am getting an odd bug.

When I add MDTooltip to a working MDLabel definition - I get this error message:

```
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.7/site-packages/kivy/uix/boxlayout.py", line 306, in do_layout
  l, t, r, b = self.padding

builtins.ValueError: not enough values to unpack (expected 4, got 2)
```
This is despite the docs saying

"
MDTooltip only works correctly with button and label classes.
"

### Code and Logs

```
<Details@MDLabel+MDTooltip>
    size_hint_max_y: "30sp"
    valign: "center"
    theme_text_color: "ContrastParentBackground"
```

**Comment by HeaTTheatR** [comment]
@runette Reinstall KivyMD library from master branch

**Comment by runette** [comment]
I tried that. The current Master Branch DOES NOT WORK. A whole rash of errors - all to do with color and mostly the ._current_button_color method.

**Comment by HeaTTheatR** [comment]
@runette Attach full log.

**Comment by runette** [comment]
I seem to have solved all of the problems by upgrading to Kivy 2.0.0 and Python 3.8 - which is a good thing to do anyway. A new stable release of kivyMD through pip with a dependency on kivy 2.0.0 would be really good
