### ISSUE TITLE
icon bug and checkbox bug

### ISSUE THREAD

**Issue by kushurox** [kivymd/KivyMD#759]
### Description of the Bug

MDCheckBox aren't shown in android. So are the icons.
I am using kivymd version  https://github.com/kivymd/KivyMD/archive/b70abb5.zip

### Versions

* OS:  Android
* Python: python3.7
* Kivy: 2.0.0
* KivyMD: https://github.com/kivymd/KivyMD/archive/b70abb5.zip

**Comment by HeaTTheatR** [comment]
@kushurox https://github.com/kivymd/KivyMD/issues/257
