### ISSUE TITLE
Add maximum height for multiline text,

### ISSUE THREAD

**Issue by frsnmk** [kivymd/KivyMD#761]
### Description of the Bug

I am using MDTextField with `multiline:true`. When I fill the text field with very long text, the textfield becomes so long that it fills the screen. I hope this MDTextField adds some kind of max-height feature or something.

I thought it would be great to add this kind of text field to kivymd.
https://kstatic.googleusercontent.com/files/2abf608909cec8e9e2e85e5f3b1976ec3bf4a098c75362d600f20c94386c3bc0174596897fb5c2b1e46bb072662d2b1bf92f099def1f2d2a4552e507486586eb

**Comment by HeaTTheatR** [comment]
@frsnmk Good idea!

**Comment by HeaTTheatR** [comment]
@frsnmk 
```python
    from kivy.lang import Builder

    from kivymd.app import MDApp

    KV = '''
    MDScreen

        MDTextField:
            size_hint_x: .5
            hint_text: "multiline=True"
            max_height: "200dp"
            mode: "fill"
            fill_color: 0, 0, 0, .4
            multiline: True
            pos_hint: {"center_x": .5, "center_y": .5}
    '''


    class Example(MDApp):
        def build(self):
            return Builder.load_string(KV)


    Example().run()
```

![text-field-fill-mode-multiline-max-height](https://user-images.githubusercontent.com/16930280/103983722-d545d580-5196-11eb-9797-e65ea7b24342.gif)

**Comment by frsnmk** [comment]
wow fantastic,  i didn't expect to get it that fast, really thank you so much...I am very grateful...

**Comment by ipapop** [comment]
Extremely useful **Thanks!!**  There is however ,as I can see ,a little thing when you update the text input via KV ids : The focus is at the end of ,sometimes, a very long ..input.

**Comment by dephantom1** [comment]
That is super fantastic! I love it!
How do you limit it to the parent's size though?
I have a Tab Content, which contains a MDScrollView which contains a box layout, which contains the the text MDTextField. However, the overflow becomes hidden from view when it reaches the top of the tab content boundary.
I would like to see it start scrolling once it reaches the bounds of the tab content.
I see all kinds of people asking this request on various sites with not one answer! 

Long live KivyMD!

**Comment by E-Unit** [comment]
@dephantom1 - If you haven't found a solution (or the one bellow for that matter), this may be what you are looking for:
```
MDScrollView:
    id: scrlv
    MDTextField:
        multiline: True
        write_tab: False
        size_hint: 1, None
        height: max((len(self._lines)+1)*self.line_height, scrlv.height)
```

**Comment by E-Unit** [comment]
@HeaTTheatR , is there a way to force the MDTextField size to a predefined size and then limit the total text length (or max characters) to what would fit inside the text box?.
I'm looking for something similar to the screenshot below, I just haven't figured out the max characters that can fit in it.
The screenshot uses the regular Kivy TextField.
![image](https://github.com/kivymd/KivyMD/assets/10116215/4ff86f65-c3e4-430f-ab43-74efc6c24a80)

**Comment by HeaTTheatR** [comment]
> inside

https://kivymd.readthedocs.io/en/latest/components/text-fields/#kivymd.uix.textfield.textfield.MDTextField.max_height

**Comment by E-Unit** [comment]
@HeaTTheatR - Really appreciate the quick response. I have tried setting the max_height on my text field, however when the max height is reached, the text starts scrolling. This would be fine in most cases but I want to actually stop the input of text when the box is filled. I am making an app to use at work for data entry to replace MS Access. This data will be aggregated and turned into a PDF form so I have to limit the amount of text allowed so I don't' run out of space.
The PDF form will be printed as a standard letter size with a bunch of other info as well.

**Comment by HeaTTheatR** [comment]
You can use the TextInput widget from the Kivy framework.
