### ISSUE TITLE
kivymd textfield input not support arabic text even with  get_display&arabic_reshaper

### ISSUE THREAD

**Issue by mustafa20211** [kivymd/KivyMD#762]
### Description of the Bug

I can not input arabic text correctly to any type MDTextField 
even using get_display&arabic_reshaper

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
#:import arabic_reshaper arabic_reshaper
#:import get_display bidi.algorithm.get_display

Screen:

    MDTextField:
        text: get_display(arabic_reshaper.reshape('الله واكبر ولله الحمد  '))
        hint_text:  get_display(arabic_reshaper.reshape(' واكبر'))
        pos_hint: {"center_x": .5, "center_y": .5}
        font_name: "DejaVuSansCondensed.ttf"
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()

"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by mustafa20211** [comment]
please any one can help with that

**Comment by HeaTTheatR** [comment]
@mustafa20211 https://medium.com/@ahmedfgad/supporting-arabic-alphabet-in-kivy-for-building-cross-platform-applications-7a1e7c14a068

**Comment by mustafa20211** [comment]
thank you but the link is not available if there another link please 
and I wonder if this solution will solve all Arabic text like in label , toast , drop down menu and other component accept text 
sorry for annoying you 

(I have the same problem with toast and I cant set Arabic font for main screen and not solved the problem)
