### ISSUE TITLE
Carousel inside one of the tab .

### ISSUE THREAD

**Issue by purushottam858** [kivymd/KivyMD#765]
### Description of the Bug
problem is that when carousel is one of the child of tab , 
it is not working properly. when tried to swipe or scroll  , the focus is going to tabs and tabs are getting swiped . To swipe the widgets inside the tabs , I need to wait for time delay and swipe slowly which is not comfortable for the  users . I found this bug when app is running on android but not in ubuntu . 
swiping of the tabs should happen only the swipe (touch) is not handled by child widgets .
First the swipe   on the screen should be passed to the children of the tabs , if it is not handled by any child then the switching of tabs should happen .  

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/764
