### ISSUE TITLE
Icon and Label in MDBottomNavigation are stacked to on each other

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#774]
### Description of the Bug

here is an image
[<a href="https://ibb.co/wWvBChm"><img src="https://i.ibb.co/XswjpxR/bug-bottom-navigation.png" alt="bug_bottom_navigation" border="0"></a>](url)

### Code and Logs

* OS: Pop_Os
* Python: python3.7
* Kivy: 2.0.0
* KivyMD: master

**Comment by sysnux** [comment]
Same here on:
    OS: Fedora 32
    Python: v3.8.6
    Kivy: v2.0.0rc4
    KivyMD: master
and also on Android.

**Comment by timovwb** [comment]
The fix seems to switch the label and icon position. It used to be icon top, label bottom. Now it is label top, icon bottom.

**Comment by HeaTTheatR** [comment]
@timovwb No

**Comment by timovwb** [comment]
Running the example from [the docs](https://kivymd.readthedocs.io/en/latest/components/bottom-navigation/). There it shows the label underneath the icon and how it used to be. Now it has switched.

![kivymd_bottom_nav_ex](https://user-images.githubusercontent.com/893402/104601443-8b6b5c80-567a-11eb-91b0-a2bf9e183df6.png)

**Comment by HeaTTheatR** [comment]
@timovwb You are wrong.

**Comment by timovwb** [comment]
I'm not trying to play a yes/no game. Atleast tell me where I'm wrong. The documentation shows label under icon, KivyMD 0.104.1 shows the same, even installing master from 2 weeks ago shows it that way.

**Comment by HeaTTheatR** [comment]
@timovwb In `KivyMD`, in the `MDBottomNavigation` class, the icon was always at the bottom.

**Comment by timovwb** [comment]
That just can't be true. Here's the documentation example:

![docs](https://raw.githubusercontent.com/HeaTTheatR/KivyMD-data/master/gallery/kivymddoc/bottom-navigation.gif)

KivyMD 0.104.1:

![kivymd_bottom_nav_ex_v0 104 1](https://user-images.githubusercontent.com/893402/104607537-3717ab00-5681-11eb-989d-28b992e3c102.png)

KivyMD master from Januray 1st (two weeks ago):

![kivymd_bottom_nav_ex_master20210101](https://user-images.githubusercontent.com/893402/104607251-ebfd9800-5680-11eb-8642-fc803e9bfb5b.png)

**Comment by HeaTTheatR** [comment]
@timovwb Yes you are right.

**Comment by HeaTTheatR** [comment]
@timovwb https://github.com/kivymd/KivyMD/commit/ef5b96143aeade1a21e8befb0c37873890ecee11

**Comment by timovwb** [comment]
@HeaTTheatR Thanks! Works as intended again.

**Comment by ghost** [comment]
How can I get a navigation bar to the screen when the "menu" icon is clicked? I want to get a navigation bar with a list of 3 items. When for example "item1" is clicked, then the screen changes to "item1 screen". Can someone solve this problem? Now, the program I have written shows a toolbar at top of the screen with a menu icon, and a bottom navigation bar with three icons. The only problem is to add a navigation bar to the menu icon, and use screenmanager to switch between screens when items is clicked inside the navigation bar.

Here is my python file:
from kivymd.app import MDApp
from kivy.lang import Builder


class Test(MDApp):
    def build(self):
#        self.theme_cls.primary_palette = "Gray"
        return Builder.load_file("test.kv")

Test().run()

And here is my kv file:
#: import get_color_from_hex kivy.utils.get_color_from_hex

Screen:
    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: 'Test'
            md_bg_color: get_color_from_hex("#088F8F")
            specific_text_color: get_color_from_hex("F5F5F5")
            left_action_items: [["menu"]]

        MDBottomNavigation:
            panel_color: get_color_from_hex("#088F8F")
            text_color_active: get_color_from_hex("F5F5F5")

            MDBottomNavigationItem:
                name: 'screen 1'
                text: 'New Session'
                icon: 'plus'
                MDLabel:
                    text: 'New session screen'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 2'
                text: 'Add Test Result'
                icon: 'clock'
                MDLabel:
                    text: 'Test result screen'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 3'
                text: 'Goat'
                icon: 'sheep'
                MDLabel:
                    text: 'Goat screen'
                    halign: 'center'

**Comment by Heddaolsen** [comment]
Can someone write a program with this inside:

-A toolbar at top of the screen
-Menu icon inside the toolbar
-Navigation bar show up when menu icon clicked
-Add three items to inside a scrollview inside the navigation bar
-use screenmanager to switch between screens when items is clicked
-a bottom navigation bar with 3 icons

**Comment by HeaTTheatR** [comment]
@Heddaolsen Tell us exactly what you can't do and attach a minimal sample code that reproduces the problem you described.

**Comment by ghost** [comment]
> @Heddaolsen Tell us exactly what you can't do and attach a minimal sample code that reproduces the problem you described.

Okay, so I have made a screen with a toolbar at top of the screen and a bottom navigation bar. It is a menu icon left at the toolbar. I want a navigation bar to show up when the menu icon is clicked. And switch between screens when items is clicked in the navigation bar.

**Comment by ghost** [comment]
this is my kv file:

Screen:
    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: 'GoatMentor'
            md_bg_color: get_color_from_hex("#088F8F")
            specific_text_color: get_color_from_hex("F5F5F5")
            left_action_items: [["menu"]]

        MDBottomNavigation:
            panel_color: get_color_from_hex("#088F8F")
            text_color_active: get_color_from_hex("F5F5F5")

            MDBottomNavigationItem:
                name: 'screen 1'
                text: 'New Session'
                icon: 'plus'
                MDLabel:
                    text: 'New session screen'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 2'
                text: 'Add Test Result'
                icon: 'clock'
                MDLabel:
                    text: 'Test result screen'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 3'
                text: 'Goat League'
                icon: 'sheep'
                MDLabel:
                    text: 'Goat league screen'
                    halign: 'center'
