### ISSUE TITLE
MDDialog broken when called from MDFloatingActionButtonSpeedDial inside a FloatLayout

### ISSUE THREAD

**Issue by floi** [kivymd/KivyMD#775]
### Description of the Bug

When modifying the example code for the MDFloatingActionButtonSpeedDial by replacing `Screen` with `FloatLayout` and adding a callback that opens an instance of `MDDialog`, instead of the dialog, I get what looks like broken diagonal black shadows.

### Code and Logs

**With Screen (this works)**
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.dialog import MDDialog

KV = """
Screen:

    MDFloatingActionButtonSpeedDial:
        data: app.data
        root_button_anim: True
        callback: app.show_dialog
"""


class Example(MDApp):
    data = {
        "language-python": "Python",
        "language-php": "PHP",
        "language-cpp": "C++",
    }

    def build(self):
        return Builder.load_string(KV)

    def show_dialog(self, instance):
        dialog = MDDialog(text=self.data[instance.icon])

        dialog.open()


Example().run()
```

**With FloatLayout (this is broken)**

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.dialog import MDDialog

KV = """
FloatLayout:

    MDFloatingActionButtonSpeedDial:
        data: app.data
        root_button_anim: True
        callback: app.show_dialog
"""


class Example(MDApp):
    data = {
        "language-python": "Python",
        "language-php": "PHP",
        "language-cpp": "C++",
    }

    def build(self):
        return Builder.load_string(KV)

    def show_dialog(self, instance):
        dialog = MDDialog(text=self.data[instance.icon])

        dialog.open()


Example().run()
```

### Screenshots

Both screenshots were taken after clicking on the Python button at the topmost position of the stack, but the result is the same for the other buttons.

**With Screen**
![working](https://i.imgur.com/4gL0DIt.png)

**With FloatLayout**
![broken](https://i.imgur.com/uMeUOrP.png)

### Versions

* OS: Ubuntu 18.04.4
* Python: 3.7.9
* Kivy: 1.11.1
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@floi You are not using the master branch of the library.
