### ISSUE TITLE
Tooltip on Widget in MDTabs displays even when the tab is not visible

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#783]
### Description of the Bug

If you have a widget with MDTooltip enabled on a MDTab and the MDTabs do not cover the whole width of the screen, then the tooltip text is displayed in the wrong part of the screen when the tab is not visible.

When the tab is not visible, then the tooltip should not be visble.

### Code and Logs

You can reproduce the problem using the following snippet. move to any tab except the first tab (i.e. so that there is content in slides to the left of the displayed slide.

Hover over the displayed button. You will get a tooltip. Then move the mouse to the left. In the middle of the left hand panel there will be an incorrect tooltip.

```python

from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout
from kivy.properties import ObjectProperty, StringProperty

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.icon_definitions import md_icons
from kivymd.uix.tooltip import MDTooltip
from kivymd.uix.button import MDIconButton

KV = '''

MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDGridLayout:
        rows: 1

        Widget:

        MDTabs:
            id: tabs


<Tab>:

    TooltipButton:
        id: icon
        icon: root.icon
        user_font_size: "48sp"
        pos_hint: {"center_x": .5, "center_y": .5}
        tooltip_text: root.tooltip_text
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''
    icon = ObjectProperty()
    tooltip_text = StringProperty()


class TooltipButton(MDIconButton, MDTooltip):
    pass


class Example(MDApp):
    icons = list(md_icons.keys())[15:30]

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for name_tab in self.icons:
            tab = Tab(text="This is " + name_tab, icon=name_tab, tooltip_text=name_tab)
            self.root.ids.tabs.add_widget(tab)


Example().run()

```

### Versions

* OS: mac
* Python: 3.8.6
* Kivy: 2.0.0
* KivyMD: Master

**Comment by HeaTTheatR** [comment]
@runette I did not find any bugs.

**Comment by runette** [comment]
Did you change the tab to any tab other than the first tab?

**Comment by runette** [comment]
Typical example. I have reproduced this on two machines, one mac on python 3.8 and one windows on python 3.7. You have to imagine the mouse is hovering where the tooltip has appeared.

<img width="912" alt="Screenshot 2021-01-19 at 19 33 44" src="https://user-images.githubusercontent.com/2239795/105083855-6d906400-5a8d-11eb-81ca-9ccb71570828.png">

**Comment by HeaTTheatR** [comment]
@runette  I did not find any bugs.

**Comment by runette** [comment]
I am not sure if you are saying that you cannot reproduce the behaviour or that you can reproduce the behaviour and that you do not think it is a bug?

**Comment by runette** [comment]
A short video showing the error

https://youtu.be/wzi4sHQY0js

**Comment by HeaTTheatR** [comment]
@runette This is not a bug in the `KivyMD` library. This is the usual behavior for a `Carousel` widget. And `MDTabs` widget uses this widget. First, you shouldn't use the `Carousel` in this way, because the previous slide just extends beyond the borders of the `Carousel`.

![Без имени](https://user-images.githubusercontent.com/16930280/105136195-5049ad00-5b02-11eb-8aaf-2a870561edbe.png)

**Comment by runette** [comment]
I completely and absolutely disagree. 

Your Tab component does NOT behave either as expected or as specified by Material Design. The Material Design specs clearly state that what I am asking for is not only allowed but recommended - see the Tab Placement section https://material.io/components/tabs#placement

<img width="829" alt="Screenshot 2021-01-20 at 09 18 29" src="https://user-images.githubusercontent.com/2239795/105153795-be8d7000-5b00-11eb-982a-be3447540c8a.png">

Despite what you claim - the content is NOT visible in the left pane and THEREFORE the Tooltip should NOT be visible in that pane. the expected behaviour is that the MDTabs widget can be be placed in any reasonable placement - in line with kivy standards and in line with MD standards - and that the content - including dynamic content - is only visible INSIDE the widget.

It is not expected that MDTabs content is visible outside of the extent of the widget!

**Comment by HeaTTheatR** [comment]
@runette Yes, I seem to be wrong and with `Kivy` widgets I was unable to reproduce this bug.

**Comment by runette** [comment]
+1

**Comment by runette** [comment]
This is actually a slightly larger problem - for instance tooltips appear when the Widget is covered by an MDDropdownMenu etc.

**Comment by HeaTTheatR** [comment]
@runette Tried to figure out what the problem is. I couldn't figure it out yet.

**Comment by runette** [comment]
I have put a patch on the problem(s) for my app. I don't think this is a production solution but it might help you think about a solution.

I am using two patches - both in the HoverBehaviour script

1 - check to see if there is an MDDropdownMenu active. If there is - then turn off all hover behaviour. This is brute force but works and is an acceptable solution - you don't want any tooltips coming up when the focus is on the menu anyway.

2 - for the widget with HoverBehavior attached  - when there is a valid event - walk the tree of ancestors to the Widget and collide the mouse position with each parent Widget in turn.

If the mouse point collides with the child Widget but NOT with the parent widget then the child is not visible. Discard the mouse event.

This is also a brute force fix and I am sure is not very generic. But it has patched the problem for me. The code in the HoverBehavior class is :

```python
    def on_mouse_pos(self, *args):
        if not self.get_root_window():
            return  # do proceed if I'm not displayed <=> If have no parent
        pos = args[1]
        # Next line to_widget allow to compensate for relative layout
        inside = self.collide_point(*self.to_widget(*pos))
        if self.hovered == inside:
            # We have already done what was needed
            return
        if inside:
            children = Window.children
            for child in children:
                # For each top level widget - check if it is a Menu. If a menu is visible
                # it will be here
                if type(child).__name__ == "MDDropdownMenu":
                    inside = False
                    break
            widget = self
            while True:
                # Walk up the Widget tree from the target Widget
                parent = widget.parent
                try:
                    # See if the mouse point collides with the parent
                    pinside = parent.collide_point(*pos)
                except:
                    # The collide_point will error when you reach the root Window
                    break
                if not pinside:
                    inside = False
                    break
                # Iterate upwards
                widget = parent
        self.border_point = pos
        self.hovered = inside
        if inside:
            self.dispatch("on_enter")
        else:
            self.dispatch("on_leave")

```

**Comment by HeaTTheatR** [comment]
@runette The code that is used in the `hover_behavior.py` module is actually not very good. This issue only confirms this. In addition, there is a related issue with this module - https://github.com/kivymd/KivyMD/issues/786. So we need to find a more elegant solution for the hover behavior.

**Comment by runette** [comment]
+1

**Comment by ZianiOussama** [comment]
the problem is with HoverbeBavior witch is what MDTooltip depends on. it's changing when the mouse is on top of the widget(when it's pos == mouse pos).so it would be displayed whether it's visible
or not.
HoverBehavior should change when the widget's pos == the mouse's pos and the widget is visible.
