### ISSUE TITLE
Icon List Webpage

### ISSUE THREAD

**Issue by Vampirebat** [kivymd/KivyMD#784]
### Description of the Feature
Love kivymd thankx for the work, i hope i can contribute one day

is there anyway to just make a webpage that displays the icons... even if its not as preety as they will be in the app.. the pic of the icon with the name would help alot...

**Comment by HeaTTheatR** [comment]
This issue is not related to the KivyMD library so I am closing it.

**Comment by mp-007** [comment]
https://materialdesignicons.com/

**Comment by HeaTTheatR** [comment]
@marcets ???

**Comment by mp-007** [comment]
@Vampirebat don't want a web page with all the icon and name in kivymd. If this is not the case, I was lost in translation. Sorry.

**Comment by HeaTTheatR** [comment]
@Vampirebat I do not understand.

**Comment by Vampirebat** [comment]
its ok, I understand... I was saying... that a list of all the icons with they're name would be helpful... a list not made in python... like a quick reference... but it's alright, I can make due with what y'all have... good work. I really like kivy md...

**Comment by HeaTTheatR** [comment]
@Vampirebat https://github.com/kivymd/KivyMD/blob/master/kivymd/icon_definitions.py
