### ISSUE TITLE
MDTextFieldRound text not visible after unfocusing

### ISSUE THREAD

**Issue by kevin-schumann** [kivymd/KivyMD#785]
### MDTextFieldRound text not visible after unfocusing
Text is only visible while the text field is focused. 
The hint text is also not shown.

### Code and Logs

```python

from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
BoxLayout:
    padding: "50dp"

    MDTextFieldRound:
        helper_text: "There will always be a mistake"
        pos_hint: {"center_y": .5}
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()

```

**Comment by kevin-schumann** [comment]
This behaviour seems to be caused by the addition of the canvas.after instruction in the following commit. Removing it fixed this issue.

e43593072ed9be3ed16662b79c61598566664f28

What does this commit fix? I wasn't able to reproduce the bug as described in the commit message.

**Comment by HeaTTheatR** [comment]
@kevin-schumann `MDTextFieldRound` class has no `helper_text` attribute.

**Comment by kevin-schumann** [comment]
You are right! I meant the hint_text. I adjusted the code snippet.

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
BoxLayout:
    padding: "50dp"

    MDTextFieldRound:
        hint_text: "There will always be a mistake"
        pos_hint: {"center_y": .5}
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()


```

**Comment by HeaTTheatR** [comment]
@kevin-schumann Yes, I saw the problem.

**Comment by kevin-schumann** [comment]
@HeaTTheatR Could you explain what the commit I linked earlier tried to fix? As of now, I do not understand what it patches and ergo I'm not able to work on a pull request.
