### ISSUE TITLE
MD Toolbar and menus / Documentation

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#787]
### Description of the Bug

I think this is a matter of documentation. If you agree with the example below - assign this issue to me and when I get time I will PR a documentation change based on it.

The documentation on MDToolbar does not say anything about how to create a menu. The documentation on MDDropdownMenu says "The MDDropdownMenu does not work with the standard MDToolbar. You can use your own CustomToolbar and bind the menu window output to its elements.".

This is a critical issue since (as the kivymd and [MD](https://material.io/components/menus#dropdown-menu) examples show) there is no point in having an MD toolbar without menus.

It is also a shame because it is wrong - Menus work very well with MDToolbar as the following example shows (note I have recreated the example from the MDDropdownMenu page with the navigation button going to a menu even though I know that a navigation Drawer would make more sense here).

```python

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.snackbar import Snackbar

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "MDToolbar"
        left_action_items: [["menu", lambda x: app.callback(x)]]
        right_action_items: [["dots-vertical", lambda x: app.callback(x)]]

    MDLabel:
        text: "Content"
        halign: "center"
'''


class Test(MDApp):
    def build(self):
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)
        return Builder.load_string(KV)
    
    def callback(self, button):
        self.menu.caller = button
        self.menu.open()
        
    def menu_callback(self, menu, item):
        self.menu.dismiss()
        Snackbar(text=item.text).open()

Test().run()

```

Video just show that it works: 

https://user-images.githubusercontent.com/2239795/105475609-72286880-5c97-11eb-9780-467398d5ec45.mp4

### Versions

* OS:  all
* Python:  all
* Kivy: 2.0.0
* KivyMD: Master

**Comment by HeaTTheatR** [comment]
@runette Yes, I have not tested if the `MDMenu` with the `MDToolbar` works. This did not work before. Therefore, the documentation had relevant information about this. Now that there are new changes in the library, the `MDMenu` works with the `MDToolbar`. But I haven't tested it.

**Comment by runette** [comment]
@HeaTTheatR yep - as I say - I think this is only a documentation problem. If you like the example - I will attempt to PR the documentation change in the next couple of days.

**Comment by HeaTTheatR** [comment]
@runette Yes, I guess it's outdated documentation. If it's not difficult for you, you can make these changes to PR.

**Comment by runette** [comment]
Can.

Sometime this week
