### ISSUE TITLE
color hint (text_hint_color) for MDTextField not working (in the master branch of the library)

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivymd/KivyMD#803]
### Description of the Bug

I have tested 2 variants for my code:
First case - I have working DataTables without color hint for MDTextField
Second case - I haven't working DataTables, but have working color hint for MDTextField

How I can get working color hint for MDTextField and working DataTables?
Can you help me?

*** VARIANT 1 ***
-NavigationLayout - not working
+MDNavigationLayout - working
-Color - not working
+DataTables - working

pip install kivymd==0.104.1
pip install https://github.com/kivymd/KivyMD/archive/master.zip

1) Working! https://kivymd.readthedocs.io/en/latest/components/datatables/?highlight=AnchorLayout - code is working
2) Not working - color hint in MDTextField! Code is here: https://github.com/WISEPLAT/python-code/blob/master/mobile-test/file12.py

*** VARIANT 2 ***
pip install kivymd==0.104.1
pip install https://github.com/kivymd/KivyMD/archive/b70abb5.zip

After this:
+NavigationLayout - working
-MDNavigationLayout - not working
+Color - working
-DataTables - not working

1) Not Working! https://kivymd.readthedocs.io/en/latest/components/datatables/?highlight=AnchorLayout
2) Working - color hint in MDTextField! 
Only change in code MDNavigationLayout to NavigationLayout!
Code is here: https://github.com/WISEPLAT/python-code/blob/master/mobile-test/file12.py

### Versions

* OS: Windows 10
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD:

**Comment by HeaTTheatR** [comment]
```
    MDTextField:
        current_hint_text_color: 0, 1, 0, 1
        hint_text: "dd/mm/yyyy"
        pos_hint: {"center_x": .5, "center_y": .5}
```
