### ISSUE TITLE
my kivymd code worked well in windows but gives errors in linux

### ISSUE THREAD

**Issue by osama-ammar** [kivymd/KivyMD#804]
the program window openes for ~2 seconds then closed giving the below error. when running in linux...........but in windows , the same code works well 
my code is very long so ,can anyone suggests what the problem may be??

[INFO   ] [Logger      ] Record log in /home/osama/.kivy/logs/kivy_21-02-01_7.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-02-01 (installed at "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 20.0.4'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event7
[INFO   ] [MTD         ] Read event from </dev/input/event7>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
0.009
0.009
0.009
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "Radiosh_connect_worked.py", line 346, in <module>
     TestNavigationDrawer().run()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/base.py", line 387, in idle
     Clock.tick()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 311, in create_window
     super(WindowSDL, self).create_window()
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 1278, in create_window
     self.dispatch('on_pre_resize', *self.size)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 1460, in on_pre_resize
     self.dispatch('on_resize', width, height)
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "/media/osama/Learn/programming/kivy/git_test/radiosh/env37/lib/python3.7/site-packages/kivymd/uix/button.py", line 1993, in _update_pos_buttons
     self.set_pos_root_button(widget)
 TypeError: 'dict' object is not callable

**Comment by HeaTTheatR** [comment]
@osama-ammar 
Please describe your question in one message, attach a minimal code that may be run without additional manipulations, so developers can look at the working script and fix it. Also write what you expect from the script and what happened wrong. If needed, attach links or screenshots to explain us what you want to do.

**Comment by osama-ammar** [comment]
Thank you HeaTTheatR  , my code is very long , the problem is that the code is working well in windows and a kivy window appears waiting for user interactions ...........but when running in linux with the same environment (python 3.7 and kivy 2.0.0 and kivymd 0.104.2.dev0)....the program crashes and not working so could you suggest a solution to the above error

**Comment by HeaTTheatR** [comment]
@osama-ammar ...attach a minimal code that may be run without additional manipulations

**Comment by osama-ammar** [comment]
@HeaTTheatR ........   here is the main.py there are 2 other modules on which this code depends but they are working well and no problem with them......Regards

```python
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.properties import ObjectProperty
from kivymd.uix.picker import MDThemePicker
from kivy.uix.floatlayout import FloatLayout
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.picker import MDTimePicker
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.button import MDRoundFlatButton
from kivy.clock import Clock
from kivymd.uix.button import MDFlatButton
from kivymd.uix.dialog import MDDialog
from kivymd.uix.card import MDCard
from kivymd.uix.card import MDCardSwipe
import datetime
from kivymd.toast import toast
from kivymd.uix.tab import MDTabsBase

import sys



from Radiosh_pro import Decay as Decay_tab
from exposure_rate import Exposure
from DLP import DLP as DLP_tab


KV = '''

 

<ContentNavigationDrawer>:
  
  orientation: "vertical"
  padding: "9dp"
  spacing: "9dp"
  
  AnchorLayout:
    
    anchor_x: "center"
    size_hint_y: None
    height: avatar.height
    
    Image:
      
      id: avatar
      size_hint: None, None
      size: "100dp", "100dp"
      source: "mask.png"  

  MDLabel:
    
    text: "Radiosh Dosimetry"
    height: self.texture_size[1]
    font_style: "Button"
    size_hint_y: None
     
  ScrollView:
    
    MDList:
      
      OneLineListItem:
        text: "Decay"
        on_press:
          root.nav_drawer.set_state("close")
          root.screen_manager.current = "scr1"
          
      OneLineListItem:
        text: "DLP to Dose"
        on_press:
          root.nav_drawer.set_state("close")
          root.screen_manager.current = "scr 2"


      OneLineListItem:
        text: "Setting"
        on_press:
          root.nav_drawer.set_state("close")
          root.screen_manager.current = "scr 3"
          
      OneLineListItem:
        text: "Exposure (Dose rate)"
        on_press:
          root.nav_drawer.set_state("close")
          root.screen_manager.current = "scr 4"





Screen:
  name:'main screen'
  id:main
  
  MDToolbar:
    
    id: toolbar
    pos_hint: {"top": 1}
    size_hint: (1, .06)
    elevation: 3

    md_bg_color: app.theme_cls.accent_color
    title: "Radiosh"
    left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
    right_action_items: [["clock",lambda x: app.callback_2()]]

    



   
  MDNavigationLayout:
    
    x: toolbar.height
    
    ScreenManager:
      id: screen_manager

      Screen:
        name: "scr1"
        BoxLayout:  
          MDTabs:
            id: android_tabs
            pos_hint: {"top": .95}
            on_tab_switch: app.on_tab_switch(*args)            

          
      Screen:
        id:scr2
        name: "scr 2"
        BoxLayout:  
          MDTabs:
            id: dlp
            pos_hint: {"top": .95}
            on_tab_switch: app.on_tab_switch(*args) 

      Screen:
        id:scr3       
        name: "scr 3"
        MDLabel:
          text: "Screen 3"
          halign: "center"
          
        MDRaisedButton:
          text: "Open theme picker"
          on_release: app.show_theme_picker()
          pos_hint: {"center_x": 0.5, "center_y": 0.7}          




      Screen:
        id:scr4        
        name: "scr 4"
        BoxLayout:  
          MDTabs:
            id: exposure
            pos_hint: {"top": .95}
            on_tab_switch: app.on_tab_switch(*args) 




  MDNavigationDrawer:
    id: nav_drawer
    ContentNavigationDrawer:
      screen_manager: screen_manager
      nav_drawer: nav_drawer


''' 
   

class ContentNavigationDrawer(BoxLayout):
  pass

class TestNavigationDrawer(MDApp):
    data = {'+++': 'Python','language-php': 'PHP','language-cpp': 'C++'}

    
    def __init__(self,**kwargs):
        super(TestNavigationDrawer,self).__init__(**kwargs)
        

        
        
        self.x=Builder.load_string(KV)
        self.dialog = None



        
        
        self.theme_cls.theme_style = "Dark" # "Light"
        self.theme_cls.primary_palette = "BlueGray" # "Purple", "Red"


        
        
    def set_item_units(self, instance_menu, instance_menu_item):
        self.x.ids.units.text=instance_menu_item.text
        self.menu.dismiss()
 
    def set_item_isotopes(self, instance_menu, instance_menu_item):
        self.x.ids.radio_isotpes.text=instance_menu_item.text
        self.radio_isotopes_menu.dismiss()

    def show_alert_dialog(self):
            print (' a card')

            self.dialog = MDCardSwipe(size= [280,300],pos_hint= {"center_x": .5, "center_y": .5})
            self.dialog.open_card
            toast('Test Kivy Toast')            
            
            
    def show_time_picker(self):
            time_dialog = MDTimePicker()
            time_dialog.bind(time=self.get_time)
            time_dialog.open()


    def get_time(self, instance, time):
            print (time,type(time))
            self.x.ids.ref_time.text=str(time)
            
            time_now = (str(datetime.datetime.now().time()))
            hr,minu,sec = time_now.split(":")
            time_now=[float(hr)*60,float(minu),float(sec)]
            time_min= time_now[0]+time_now[1] 
            return time

            
      
    def now_time(self,*args):

        self.time_now = (str(datetime.datetime.now().time().strftime("%H:%M:%S")))
        hr,minu,sec = self.time_now.split(":")
        clear_time=str(int(hr))+':'+str(int(minu))+':'+str(int(sec))
        
        self.x.ids.ref_time.text=(clear_time)


    
    def speed_dial(self, instance):
        print(instance.icon)
        self.x.ids.speed_dial.icon=instance.icon
        print('hi    hi')






    def update_decay (self,*args):  
            try:   
                ref_Dose = float(self.x.ids.input_activity.text)
            except ValueError:   
                ref_Dose = float(0)
            
            time_now = (str(datetime.datetime.now().time()))
            hr,minu,sec = time_now.split(":")
            time_now=[float(hr)*60,float(minu),float(sec)/60]
            time_min= time_now[0]+time_now[1]+time_now[2] 

            ref_hr,ref_minu,ref_sec =self.x.ids.ref_time.text.split(":")
            time_ref=[float(ref_hr)*60,float(ref_minu),float(ref_sec)/60]
            time_ref= time_ref[0]+time_ref[1]+time_ref[2] 



            iso_dict ={"Tc 99m":.001918, "F 18":.009, "I 131":.0001, "I 123":.005, "Ga 68":.0106, "Ga 67":.0001,"Y 90":0.002,"O 15":0.3462,"N 13":0.093}
            decay_const=.009
            for i in iso_dict.keys():                
                if  self.x.ids.radio_isotpes.text==i:

                    decay_const=float(iso_dict[i])    
                    print (decay_const)

                
            activity_pre = ref_Dose * ( 2.71828**( -decay_const*(time_min-time_ref) ))
            
            print (decay_const)

                                        
            units_dict={"mCi":1,"Ci":0.001, "MBq":37, "Bq":3.7*10000000, "GBq":.037}

            for i in units_dict.keys():                
                if  self.x.ids.units.text==i:
                  pass        
                  
                  if time_min<time_ref : 
                      self.x.ids.current_dose.text=' Adjust Time '
                      print ('working1') 
                  else : 
                      self.root.ids.current_dose.text='%8.5f  %s'%(activity_pre,i)
 
                      print ('working2')   
                      
                      
                      
                      
                      
                      
    def on_start(self):
          for i in range(3):
              self.root.ids.android_tabs.add_widget(Decay_tab(text="insert")) 
              
          self.root.ids.exposure.add_widget(Exposure(text="Exposure"))    
          self.root.ids.dlp.add_widget(DLP_tab(text="DLP to Dose"))    

              
    def on_tab_switch(self, instance_tabs, instance_tab, instance_tab_label, tab_text):
          pass

          
    def show_theme_picker(self):
          theme_dialog = MDThemePicker()
          theme_dialog.open()       
      
    def build(self):

          return self.x




if __name__ == '__main__':
  TestNavigationDrawer().run()



```

**Comment by HeaTTheatR** [comment]
@osama-ammar ...attach a `minimal code` that may be run `without additional manipulations`...

**Comment by osama-ammar** [comment]
I already attached the code ......I couldn't understand what to do more

**Comment by HeaTTheatR** [comment]
@osama-ammar 
![Снимок экрана 2021-02-01 в 21 15 26](https://user-images.githubusercontent.com/16930280/106500347-c242ce80-64d2-11eb-9fdf-b62e1ceb4fd2.png)

**Comment by osama-ammar** [comment]
Dear @HeaTTheatR   actually , I couldn't understand what exactly you mean.....the attached code is the minimal code that may be run without additional manipulations.......so what can I do more????????

**Comment by HeaTTheatR** [comment]
@osama-ammar 
![Снимок экрана 2021-02-02 в 19 17 47](https://user-images.githubusercontent.com/16930280/106629200-a5b69d00-658b-11eb-9635-e5a7833d1745.png)

Secondly, your KV string is incorrect due to incorrectly spaced indents.
Thirdly, the minimal code, this is the code that demonstrates the essence of the problem, and your code has 300 (!) lines. Some Kivy and KivyMD modules are significantly shorter than your `minimal code`.

**Comment by osama-ammar** [comment]
Dear @HeaTTheatR   thanks alot , the problem is solved
