### ISSUE TITLE
Icon Not Showing with the latest kivy2.0.0

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#805]
kivymd Icons are not showing both on desktop and mobile with the latest of [kivy](https://files.pythonhosted.org/packages/12/96/091ddacafb84dd18555a32d860dbfaf9c806147aa30c6f3c8b93cb7bab97/Kivy-2.0.0.tar.gz) and also the master branch too and I also discovered it uses pygame as the Window Provider for now

OS: Pop_OS
python version: python3.7
kivymd version: master

**Comment by HeaTTheatR** [comment]
@kengoon It seems to me that this is a problem of dependencies that you installed incorrectly. One way or another, this is unlikely to be related to the KivyMD library.

**Comment by kengoon** [comment]
@HeaTTheatR ya it is not related to KivyMD, the problem is from Kivy itself. you can install the master branch of Kivy and check it out your self. Why I posted this here is because it only affects KivyMD and Kivy is not in the right position to find a quick fix

**Comment by podraco** [comment]
We need to see the logs, change your loggin to debug or below to see if there's anything missing. In the worst case, you would need to set it to trace

**Comment by kengoon** [comment]
Kivy Went back to sdl2 Window provider and all icons are now showing, it was a problem of pygame window provide. You can close this issue if you want
