### ISSUE TITLE
Can't set localization in KivyMD App (multiple language support in application)

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivymd/KivyMD#808]
### Description of the Bug

How can I do a localization for KivyMD App?
Is there any documentation with some examples?

I want to create app with 3 languages support (English, German and Russian)

P.S. It's basic for application to be supported multiple languages.

### Versions

* OS: Windows 10
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@shpaginoleg7755 https://github.com/tito/kivy-gettext-example
