### ISSUE TITLE
MDBottomNavigation text and icon color defaults to blue. 

### ISSUE THREAD

**Issue by gregynard** [kivymd/KivyMD#809]
I tried to change my theme to self.theme_cls.primary_palette = "Green" but the first icon and text appear to be still blue. Kindly see the image below. 
![image](https://user-images.githubusercontent.com/78597479/107031205-c598cb80-67ec-11eb-8350-612e9c7ff1f2.png)

**Comment by HeaTTheatR** [comment]
@gregynard Attach a minimal code that reproduces what you are describing.

**Comment by gregynard** [comment]
@HeaTTheatR  Sorry for bothering I found out that I place my builder load file on my constructor instead on build function. The below code fixes the problem. Again thank you for your swift support 


class Project(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def build(self):
        self.theme_cls.primary_palette = "Green"
        self.theme_cls.primary_hue = "500"
        self.theme_cls.theme_style = "Light"
        self.screen = Builder.load_file("test_env.kv")
        return self.screen
