### ISSUE TITLE
reload_viewer crashes when I type: pos_hint: {""}

### ISSUE THREAD

**Issue by xCuriousParanoiax** [kivymd/KivyMD#813]
### Description of the Bug

If I do:

```pos_hint: {""}```

The viwer crashes with the following error: 

AttributeError: 'set' object has no attribute 'items'

**Comment by HeaTTheatR** [comment]
@xCuriousParanoiax We cannot fix this because the error occurs on the Kivy side.

**Comment by podraco** [comment]
It's not really an issue, since `pos_hint` is an alias property that relies on its dict to work.

Also, it's `pos_hint` no `post_hint`

**Comment by HeaTTheatR** [comment]
Deprecated.
