### ISSUE TITLE
Doing "pip install kivymd" installs a version that does not contain the "hot_reload_viewer.py" file.

### ISSUE THREAD

**Issue by xCuriousParanoiax** [kivymd/KivyMD#815]
Doing ```pip install kivymd``` installs a version that does not contain the ```hot_reload_viewer.py``` file. You should add a note or something mentioning that in the docs.

**Comment by HeaTTheatR** [comment]
@xCuriousParanoiax `hot_reload_viewer.py` is available only in the master branch of the `KivyMD` library.
