### ISSUE TITLE
MDTextField helper does not appear when it is created from API

### ISSUE THREAD

**Issue by romybompart** [kivymd/KivyMD#824]
### Description of the Bug

Hello, 

  When I create the MDTextField from python the helper text is ignore as well as the helper_text_mode. 

### Code and Logs

```python
			for signal in self.unit.signals["tx"][message]: 
				self.root.ids.signals.add_widget(
						MDTextField (
								hint_text = signal.name,
								helper_text = "test",
							    helper_text_mode = "on_focus"
							)
					)
```

### Screenshots

![image](https://user-images.githubusercontent.com/8228572/107326552-3cde9180-6a71-11eb-93eb-ae2248aa0e93.png)

### Versions

* OS: Microsoft Windows [Version 10.0.19041.746]
* Python: 3.7.7
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
```python
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.textfield import MDTextField


class Example(MDApp):
    def build(self):
        screen = MDScreen()
        screen.add_widget(
            MDTextField(
                hint_text="hint_text",
                helper_text="helper_text",
                helper_text_mode="on_focus",
                pos_hint={"center_x": .5, "center_y": .5},
                size_hint_x=0.5,
            )
        )
        return screen


Example().run()
```

![Снимок экрана 2021-02-09 в 10 13 30](https://user-images.githubusercontent.com/16930280/107328256-7fc75600-6abf-11eb-994c-180a0f5404eb.png)

**Comment by romybompart** [comment]
Hi @HeaTTheatR 

   As you can see the helper_text is not what you have stated at the helper_text, the picture depicts a different value ("This filed is required". 

![image](https://user-images.githubusercontent.com/8228572/107329114-5255ba80-6a75-11eb-90f6-95ee2c29da23.png)


In this example you can se that the helper_text is the same as the kivy rule statement.

**Comment by HeaTTheatR** [comment]
Oh sorry:

```python
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.textfield import MDTextField


class Example(MDApp):
    def build(self):
        screen = MDScreen()
        field = MDTextField(
                hint_text="hint_text",
                helper_text_mode="on_focus",
                pos_hint={"center_x": .5, "center_y": .5},
                size_hint_x=0.5,
            )
        field.helper_text = "helper_text"
        screen.add_widget(field)
        return screen


Example().run()
```

**Comment by romybompart** [comment]
Don't worry, I just noticed after several checking. by default it will be this field is required. 

![image](https://user-images.githubusercontent.com/8228572/107330214-dfe5da00-6a76-11eb-8a3d-c877c1b315db.png)

Thank you for your time. 
Best Regards

**Comment by romybompart** [comment]
Hi @HeaTTheatR  , 

   The helper_text can be modified from python api after the MDTextField object creation. Thus 


```python
				text_field = MDTextField (
								hint_text = signal.name,
							    helper_text_mode = "on_focus",
							    text = str(self.unit.CanMsg[message]["signals"][signal.name])
							)
                                text_field.helper_text = "No description" if signal.comment is None else signal.comment
```

**Comment by HeaTTheatR** [comment]
@romybompart 
![Снимок экрана 2021-02-09 в 17 44 58](https://user-images.githubusercontent.com/16930280/107380101-9fca3a00-6afe-11eb-9ab1-568b6bfc5cd2.png)

**Comment by romybompart** [comment]
Hi @HeaTTheatR , ahh got it... 

  Nevertheless, helpder_text_mode needs to be set after the field instance is created too. 
  Do you know if this performance is related to the fact that helper_text_mode and helper_text are properties of the widget?

  I found this ok for me, It is matter of provide an example.

**Comment by podraco** [comment]
Must be an issue within `MDLable.__init__`

**Comment by podraco** [comment]
##### kivymd/uix/textfield.py
``` py
def __init__(self, **kwargs):
        self.set_objects_labels()
        super().__init__(**kwargs)
        # Sets default colors.
        self.line_color_normal = self.theme_cls.divider_color
        self.line_color_focus = self.theme_cls.primary_color
        self.error_color = self.theme_cls.error_color
        self._current_hint_text_color = self.theme_cls.disabled_hint_text_color
        self._current_line_color = self.theme_cls.primary_color

        self.bind(
            helper_text=self._set_msg,
            hint_text=self.on_hint_text,
            _hint_lbl_font_size=self._hint_lbl.setter("font_size"),
            helper_text_mode=self._set_message_mode,
            max_text_length=self._set_max_text_length,
        )
        self.theme_cls.bind(
            primary_color=self._update_primary_color,
            theme_style=self._update_theme_style,
            accent_color=self._update_accent_color,
        )
        self.has_had_text = False
        self._better_texture_size = None
        Clock.schedule_once(self.check_text)
        self._set_msg(self,self.helper_text) # << --  updates helper text text
```
