### ISSUE TITLE
Elevation does not follow the curve radius set on MDcard. 

### ISSUE THREAD

**Issue by gregynard** [kivymd/KivyMD#826]
I uninstall the kivymd branch master since I saw there are some changes made in the changelog and reinstall it again. But after running my program it seems the resolution is not the same as before and the elevation on my card does not follow the curve radius. kindly see below image and code for reference. I also notice the app is a little bit sluggish 

                             MDFloatLayout:
                                        MDCard:
                                            size_hint: 0.85, 0.8
                                            orientation: "vertical"
                                            pos_hint: {"center_x": 0.5, "y": 0.18}
                                            border_radius: 20
                                            radius: [15]
                                            MDLabel:
                                                text: "Test"
                                                size_hint_x: 0.93
                                                pos_hint: {"center_x":0.5, "center_y": 0.5}
                                                halign: "center"

                                            MDTextField:
                                                text:
                                                hint_text: "Test"
                                                size_hint_x: 0.93
                                                pos_hint: {"center_x":0.5, "center_y": 0.5}

                                            MDTextField:
                                                text:
                                                hint_text: "Test"
                                                size_hint_x: 0.93
                                                pos_hint: {"center_x":0.5, "center_y": 0.5}

                                            Widget:
                                                size_hint_y:None
                                                height: "100dp"

                                        MDFloatingActionButton:
                                            icon: "calculator-variant-outline"
                                            pos_hint: {"center_x": 0.5, "center_y": 0.17 }

![image](https://user-images.githubusercontent.com/78597479/107362823-3a814380-6b14-11eb-94f0-9dc10978f0d2.png)

**Comment by HeaTTheatR** [comment]
@gregynard https://github.com/kivymd/KivyMD/pull/819#issuecomment-774928951

**Comment by gregynard** [comment]
Thanks thanks!

**Comment by HeaTTheatR** [comment]
@gregynard This is already fixed here - https://github.com/kivymd/KivyMD/pull/822

**Comment by gregynard** [comment]
Thanks for your usual support.
