### ISSUE TITLE
Too much shadow on MDCard

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#829]
Whenever i set the radius of the vertices of MDCard the shadow seems not to blend with it any more

Check the image below and look at the vertices of the MDCard and when i increase the radius the shadow gets darker at the vertices

Before![Screenshot_20210209-162043.png](https://user-images.githubusercontent.com/42192162/107385321-12351d00-6af3-11eb-8dc3-9d8c688dfa85.png) 

Now![Screenshot_20210209-162034.png](https://user-images.githubusercontent.com/42192162/107385369-1e20df00-6af3-11eb-80e1-0559da9d1544.png)

**Comment by HeaTTheatR** [comment]
@kengoon https://github.com/kivymd/KivyMD/issues/826

**Comment by kengoon** [comment]
@HeaTTheatR I went through the issue link you sent and also check out the pull requests but i did not clearly understand. So my question now is, is there a simple fix for this

**Comment by HeaTTheatR** [comment]
@kengoon his has already been fixed. But the pull request has not yet been accepted due to some file conflict. We are waiting for the pull request author to fix it ...

**Comment by kengoon** [comment]
Ok, cool
