### ISSUE TITLE
Buildozer build issue

### ISSUE THREAD

**Issue by Arias800** [kivymd/KivyMD#83]
Hello,
When I tried to build app with buildozer I have this error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 340: ordinal not in range(128)` 
who's triggered by these lines of the setup.py:
```
VERSION_FILE = "kivymd/__init__.py"
ver_file_data = open(VERSION_FILE, "rt").read()
ver_regex = r"^__version__ = ['\"]([^'\"]*)['\"]"
ver_reg_search = re.search(ver_regex, ver_file_data, re.M)
```

**Comment by ArtemSBulgakov** [comment]
KivyMD supports only Python 3. Which version are you using?

**Comment by HeaTTheatR** [comment]
@Arias800 KivyMD supports only Python 3

**Comment by Arias800** [comment]
I use Python 3.7.1 ^^

**Comment by HeaTTheatR** [comment]
@Arias800 `requrements=python2`?

**Comment by Arias800** [comment]
No `requirements = python3`

**Comment by ArtemSBulgakov** [comment]
How did you install buildozer?

**Comment by Arias800** [comment]
I installed it as requested in the official documentation. But I use  the windows subsystem for linux (with ubuntu like distro) .

**Comment by HeaTTheatR** [comment]
@Arias800 `sudo python3 setup.py install`

**Comment by HeaTTheatR** [comment]
@Arias800 Show output...

**Comment by Arias800** [comment]
With the command above It's installed correctly  so it's maybe a Buildozer or python 4 android issue. If I change
 ```
VERSION_FILE = "kivymd/__init__.py"
ver_file_data = open(VERSION_FILE, "rt").read()
ver_regex = r"^__version__ = ['\"]([^'\"]*)['\"]"
ver_reg_search = re.search(ver_regex, ver_file_data, re.M)

if ver_reg_search:
    version = ver_reg_search.group(1)
else:
    raise ValueError("Unable to find version string in {}.".format(VERSION_FILE))
```
by `from kivymd.__init__ import __version__ as version` it work . That's weird
