### ISSUE TITLE
Widget under a custom MDCard not showing

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#834]
### Description of the Bug

Whenever I create a customized MDCard, widgets that I add under it  does not show when I run my code.
But it works when I just use MDCard directly on my code

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
<Card@MDCard>:
    orientation: "vertical"
    padding: "8dp"
    size_hint: None, None
    size: "280dp", "180dp"

    MDLabel:
        text: "Title"
        theme_text_color: "Secondary"
        size_hint_y: None
        height: self.texture_size[1]

    MDSeparator:
        height: "1dp"

    MDLabel:
        text: "Body"


Screen:
    Card:
        pos_hint: {"center_x":.5, "center_y":.5}

"""


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)


TestApp().run()

"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
i go this
![got](https://user-images.githubusercontent.com/42192162/107607136-ad83da80-6c38-11eb-9930-7297351348c7.png)

instead of this 
![expected](https://user-images.githubusercontent.com/42192162/107607204-da37f200-6c38-11eb-884b-8bf3005e0280.png)

### Versions

* OS: Pop_OS
* Python: 3.7/3.8
* Kivy: master
* KivyMD: master

**Comment by podraco** [comment]
seems that add_widget is acting funny.... 
somehow is clipping the canvas below the normal layer (where the specific color draws... )

![Captura de pantalla de 2021-02-11 02-20-42](https://user-images.githubusercontent.com/5509325/107614372-ce840580-6c0f-11eb-8a1d-26494f74810a.png)

``` python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
<TheCard@MDCard>:
    orientation: "vertical"
    padding: "8dp"
    size_hint: None, None
    size: "280dp", "180dp"
    md_bg_color:1,0,1,0.0

    MDLabel:
        text: "Title"
        theme_text_color: "Secondary"
        size_hint_y: None
        height: self.texture_size[1]
        canvas.before:
            Color:
                rgb:1,0,0
            Rectangle:
                pos:self.pos[0]-20,self.pos[1]-20
                size:self.size

    MDSeparator:
        height: "1dp"

    MDLabel:
        text: "Body"


Screen:
    TheCard:
        pos_hint: {"center": [0.5, 0.5]}

"""


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)


TestApp().run()

```
with the alpha of md_bg_color set to 1:
![Captura de pantalla de 2021-02-11 02-24-32](https://user-images.githubusercontent.com/5509325/107614622-4baf7a80-6c10-11eb-897a-473fcea8d9e5.png)

**Comment by podraco** [comment]
Fixed, i require approbation in the last pull request to pull the next
nevermind, just checked, thanks!
