### ISSUE TITLE
(Not exactly a feature request) The latest release seems outdated

### ISSUE THREAD

**Issue by jpan127** [kivymd/KivyMD#835]
### Description of the Feature
Hi, I just found this project and jumped into the one feature I really needed: `MDNavigationRail`.  I installed the package through pip and it looks to be the latest `104.1`.  It looks like the latest release doesn't even have the feature I want.
Looking through the history, the last release was 10 months ago. Have you guys considered releasing something soon, given this project seems to be fairly active.
I can go ahead and work off master, but that's not really ideal/stable.

**Comment by HeaTTheatR** [comment]
@jpan127 Thanks. We will make a new release when we fix a number of critical bugs in the library.
