### ISSUE TITLE
MDNavigationRailItem icon not loading from local image

### ISSUE THREAD

**Issue by jpan127** [kivymd/KivyMD#839]
### Description of the Bug

First off, is this possible to load an image into the icon? The documentation doesn't specify this, and all examples seem to point to an internal cache of icons.  When using any of the `md_icons` it works fine, when using a local image it doesn't.
I found `MDChip` also uses `icon` so I tried with that element, and it successfully loads the image.

### Code and Logs

There are no errors that I can tell.

```python

from kivy.app import App, Builder
from kivymd.app import MDApp

kv = """
#:kivy 1.0.9
#:import get_color_from_hex kivy.utils.get_color_from_hex

<MyTile@SmartTileWithStar>
    size_hint_y: None
    height: "240dp"

MDBoxLayout:
    orientation: "vertical"
    MDToolbar:
        title: "MDNavigationRail"
        md_bg_color: rail.md_bg_color
    MDBoxLayout:
        orientation: "horizontal"
        MDNavigationRail:
            id: rail
            color_normal: get_color_from_hex("#718089")
            color_active: get_color_from_hex("#f3ab44")

            MDNavigationRailItem:
                icon: "coffee-cup.png"
                text: "Python"
            MDChip:
                icon: "coffee-cup.png"
                text: "Python"
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()

```

#### Application:
![image](https://user-images.githubusercontent.com/19752007/107706107-a8dd1780-6c74-11eb-8f9e-b877ed6749da.png)

#### Image File:
![coffee-cup](https://user-images.githubusercontent.com/19752007/107706540-55b79480-6c75-11eb-9f43-fbbc08b11255.png)

### Versions

* OS: Windows 10
* Python: 3.9.0b3
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@jpan127 
> possible to load an image into the icon?

What do you have in mind?

**Comment by jpan127** [comment]
Hi, the library has a bunch of predefined icons, but I wanted to supply my own.  Is that possible with this element? I looks like it is with `MDChip` (see screenshot).

**Comment by HeaTTheatR** [comment]
@jpan127 https://kivymd.readthedocs.io/en/latest/components/chip/#use-custom-icon

**Comment by jpan127** [comment]
@HeaTTheatR Sorry, what? I said MDChip works, but the post is about `MDNavigationRailItem`.

**Comment by HeaTTheatR** [comment]
@jpan127 You cannot use custom icons for the MDNavigationRailItem class.

**Comment by jpan127** [comment]
I see, that is unfortunate.

Are there plans to support this? And if not, do you have suggestions on how I can add this feature?

**Comment by HeaTTheatR** [comment]
Deprecated - https://github.com/kivymd/KivyMD/commit/c683f53e8eb565dc6510814c5e4382b78ce1e216
