### ISSUE TITLE
Custom & text_color - MDRectangleFlatIconButton & MDRoundFlatIconButton

### ISSUE THREAD

**Issue by ikolim** [kivymd/KivyMD#84]
**Problem**
Unable to change the text colour for MDRectangleFlatIconButton and MDRoundFlatIconButton with the following attributes:

        MDRectangleFlatIconButton:
            theme_text_color: 'Custom'
            text_color: [1,0,0,1]
            text: "MDRectangleFlatIconButton"
            icon: "language-python"
            pos_hint: {'center_x': .5, 'center_y': .45}
            width: dp(230)

        MDRoundFlatIconButton:
            theme_text_color: 'Custom'
            text_color: [1,0,0,1]
            text: "MDRoundFlatIconButton"
            icon: "language-python"
            pos_hint: {'center_x': .5, 'center_y': .25}
            width: dp(200)

![kvMD-0 100 2-IconButton-textColor-Screenshot at 2019-08-03 17-01-10](https://user-images.githubusercontent.com/26026615/62417622-6cf1dc80-b611-11e9-904d-34bd8fc710d2.png)

**Solution**
I made the following changes in _button.py_ by
Replace:
```
            theme_text_color: 'Custom'
            text_color: root.theme_cls.primary_color
```
with:
```
            theme_text_color: root.theme_text_color   
            text_color: root.text_color                 
```

**Snippets: button.py - kv**
```
<MDRectangleFlatIconButton>
    ...
    theme_text_color: 'Custom'
    text_color: root.theme_cls.primary_color

    BoxLayout:
        ...

        MDIcon:
            ...

        MDLabel:
            ..
            theme_text_color: root.theme_text_color    
            text_color: root.text_color                 
            markup: root.markup
            
<MDRoundFlatIconButton>
    ...
    theme_text_color: 'Custom'
    text_color: root.theme_cls.primary_color

    BoxLayout:
        ...
        MDIcon:
            ...

        MDLabel:
            ...
            theme_text_color: root.theme_text_color     
            text_color: root.text_color                 
            markup: root.markup
```
![kvMD-myFix-Screenshot at 2019-08-03 17-28-53](https://user-images.githubusercontent.com/26026615/62417718-32d60a00-b614-11e9-8897-21acc2b36533.png)

**Comment by HeaTTheatR** [comment]
Will be fixed in version 0.101.0

**Comment by shashi278** [comment]
@ikolim or you can create a pull request resolving the same.

**Comment by ikolim** [comment]
A pull request was made on 6th August 2019.
