### ISSUE TITLE
Too much shadow/elevation when border radius is used with MDCard. 

### ISSUE THREAD

**Issue by gregynard** [kivymd/KivyMD#842]
I noticed that the MDcard has too much elevation/shadow when I used border-radius to curve the edges. Kindly see below code and image. If the card has no curved edges the elevation is normal. Thanks! 

MDCard:
        id: card
        orientation: "vertical"
        size_hint: .6, None
        height: self.minimum_height
        pos_hint: {"center_x": .5, "center_y": .5}
        border_radius: 20
        radius: [15]

        BoxLayout:
            id: box
            size_hint_y: None
            height: dp(150)

![image](https://user-images.githubusercontent.com/78597479/107784048-f72e0b80-6d85-11eb-8fbe-50fb31831b3f.png)

**Comment by HeaTTheatR** [comment]
@gregynard https://github.com/kivymd/KivyMD/pull/841#issuecomment-778147270

**Comment by gregynard** [comment]
Oki oki thanks!
