### ISSUE TITLE
Feature Request: MDDataTable - Allow updating of specific cells within the table by row id

### ISSUE THREAD

**Issue by caffeinatedMike** [kivymd/KivyMD#850]
**Purpose** : A datatable for an android app where specific columns of data are constantly updated for near-realtime stats. This would require being able to assign custom IDs to each row.

**Example 1** : A column that shows a timer counting up (hh\:mm:ss) that reflects how long the task (record) has been running for. 

**Example 2**: Three columns showing the number of info, warning, and error-level logging statements that can also be clicked (utilizing markup and a callback, relies on #849) to review log statements for that specific level of logging.

**Comment by podraco** [comment]
That seems a little  heavy to do,  since those call wouldn't allow the gc collect the widget in a common environment. Do you have any pseudocode you could share with us?

**Comment by ntaraujo** [comment]
I had this need and found `MDDataTable.table_data.data`, which is an ObservableList handling the row_data in a not intuitive way.
For anyone needing this, while the improvement doesn't happen, you can modify the content of single cells directly from there.
Ps.: I don't know if its safe. I saw some bugs on selecting the rows

**Comment by podraco** [comment]
i believe that mddatatables needs to be more mature for that to work in an intituive way..
