### ISSUE TITLE
ValueError: None is not allowed for IconLeftWidget.text_color

### ISSUE THREAD

**Issue by cyberpsyche** [kivymd/KivyMD#854]
### Description of the Bug

I upgrade the kivy to 2.0.0 in my new python3.8 environment on Mac OS machine and using the latest kivymd master code for compile installment from GitHub, when I execute a program coded based on kivymd and kivy former formal versions I got these error messages listed as follows:

>  Traceback (most recent call last):
>    File "/usr/local/lib/python3.8/site-packages/kivy/lang/builder.py", line 701, in _apply_rule
>      setattr(widget_set, key, value)
>    File "weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
>    File "properties.pyx", line 498, in kivy.properties.Property.__set__
>    File "properties.pyx", line 542, in kivy.properties.Property.set
>    File "properties.pyx", line 533, in kivy.properties.Property.set
>    File "properties.pyx", line 571, in kivy.properties.Property.check
>  ValueError: None is not allowed for IconLeftWidget.text_color
>  
>  During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "main.py", line 55, in <module>
>      StoryTeller().run()
>    File "/usr/local/lib/python3.8/site-packages/kivy/app.py", line 949, in run
>      self._run_prepare()
>    File "/usr/local/lib/python3.8/site-packages/kivy/app.py", line 944, in _run_prepare
>      self.dispatch('on_start')
>    File "_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/Users/sam/Projects/lightening/kivy_screen/storyteller_kivy2/modules/studio.py", line 1532, in on_start
>      ItemDrawer(icon=icon_name, text=icons_item[icon_name])
>    File "/usr/local/lib/python3.8/site-packages/kivymd-0.104.2.dev0-py3.8.egg/kivymd/uix/list.py", line 879, in __init__
>      super().__init__(**kwargs)
>    File "/usr/local/lib/python3.8/site-packages/kivymd-0.104.2.dev0-py3.8.egg/kivymd/theming.py", line 1125, in __init__
>      super().__init__(**kwargs)
>    File "/usr/local/lib/python3.8/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
>      super(ButtonBehavior, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
>      super(FloatLayout, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
>      super(Layout, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
>      self.apply_class_lang_rules(
>    File "/usr/local/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
>      Builder.apply(
>    File "/usr/local/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
>      self._apply_rule(
>    File "/usr/local/lib/python3.8/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
>      raise BuilderException(rule.ctx, rule.line,
>  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 81:
>  ...
>       79:        icon: root.icon
>       80:        theme_text_color: "Custom"
>  \>\>   81:        text_color: root.text_color
>       82:
>       83:<ItemVideo>:
>  ...
>  ValueError: None is not allowed for IconLeftWidget.text_color
>    File "/usr/local/lib/python3.8/site-packages/kivy/lang/builder.py", line 701, in _apply_rule
>      setattr(widget_set, key, value)
>    File "weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
>    File "properties.pyx", line 498, in kivy.properties.Property.__set__
>    File "properties.pyx", line 542, in kivy.properties.Property.set
>    File "properties.pyx", line 533, in kivy.properties.Property.set
>    File "properties.pyx", line 571, in kivy.properties.Property.check
> 

### Code and Logs

my kv language block is as follows:

```
KV = '''
# Menu item in the DrawerList list.
<ItemDrawer>:
    theme_text_color: "Custom"
    on_press: self.parent.set_color_item(self)
    on_release:
        root.parent.parent.parent.parent.set_state("close")
        root.parent.parent.parent.parent.parent.my_func(self.icon) 

    IconLeftWidget:
        id: icon
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color
'''
```

Is there any code upgrading clues for me ? Thanks a lot! 

### Versions

* OS:  MacOS
* Python: python 3.8
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@cyberpsyche Please describe your question in one message, `attach a minimal code that may be run without additional manipulations`, so developers can look at the working script and fix it. Also write what you expect from the script and what happened wrong. If needed, attach links or screenshots to explain us what you want to do.

**Comment by YarosMallorca** [comment]
@HeaTTheatR 
I have the same issue, please solve!
The code is basic, just the navigation drawer and the custom class <ItemDrawer>

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Please attach a minimal code that will reproduce this issue.

**Comment by YarosMallorca** [comment]
@HeaTTheatR Here is the basic code, run it in python 3.9, kivy 2.0, and kivyMD 0.104.2

```
from kivymd.app import MDApp
from kivy.lang.builder import Builder
from kivy.properties import ObjectProperty, StringProperty
from kivymd.uix.list import OneLineIconListItem
from kivymd.uix.boxlayout import MDBoxLayout

class ItemDrawer(OneLineIconListItem):
    icon = StringProperty()

class ContentNavigationDrawer(MDBoxLayout):
    screen_manager = ObjectProperty()
    nav_drawer = ObjectProperty()


kv_code = '''
<ItemDrawer>:
    theme_text_color: "Custom"
    on_release: self.parent.set_color_item(self)

    IconLeftWidget:
        id: icon
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color

<ItemConfirm>
    on_release: root.set_icon(check)

    CheckboxLeftWidget:
        id: check
        group: "check"

<ContentNavigationDrawer>:
    ScrollView:
        MDList:

            ItemDrawer:
                text: "Home"
                icon: "home"
               
                    
Screen:
    FloatLayout:
        MDToolbar:
            pos_hint: {"top": 1}
            elevation: 10
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
                        
    MDNavigationLayout:

        ScreenManager:
            id: screen_manager

            Screen:
                name: "home"
            
                
        MDNavigationDrawer:
            id: nav_drawer
            close_on_click: True

            ContentNavigationDrawer:
                id: "navdrawer"
                screen_manager: screen_manager
                nav_drawer: nav_drawer
'''



class BugReportApp(MDApp):
    def build(self):
        return Builder.load_string(kv_code)
    

BugReportApp().run()
```

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder ` ValueError: None is not allowed for IconLeftWidget.text_color`

**Comment by HeaTTheatR** [comment]
```
<ItemDrawer>:
    ...

    IconLeftWidget:
        ...
        text_color: 1, 0, 1, 1
```

**Comment by YarostheLaunchpadder** [comment]
First of all thank you, but there is another issue, unfortunately:
When I press it, the error is the following:
`AttributeError: 'MDList' object has no attribute 'set_color_item'`

I set the color as described in your comment

**Comment by YarosMallorca** [comment]
Thanks for your help!

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Try to use the master branch of the KivyMD library

**Comment by YarosMallorca** [comment]
Are there any important changes? @HeaTTheatR 
And another question, how to make it so the icon in the <ItemDrawer> is the same color as the primary_palette?

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder 
```
    IconLeftWidget:
        text_color: app.theme_cls.primary_color
```

**Comment by YarosMallorca** [comment]
Thank you so much! 
Have a nice day!
You're doing an amazing job, keep it up!
