### ISSUE TITLE
Latest Update has Broken MDTextfield

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#858]
### Description of the Bug

The latest updates to MDTextfield have stopped it working correctly if text is set in Python. The Hint text no longer animates. See example and gif below. This problem did not exist until about 11 days ago.

This is because the relevant function - that was `def on_text` has been changed to `def set_text` and so no longer automatically triggers when text is set after the Widget is created.

Someone raised a PR - #820 that was a fix - but you closed the PR. However, I am not sure that is the best fix. Far better just to use the functionality of Kivy and rename the function back to `on_text`. It can still be called from `def check_text` as it is currently.

### Code and Logs

```python
from kivy.lang import Builder
from kivy.properties import StringProperty
from kivymd.app import MDApp

KV = '''
BoxLayout:
    orientation: "vertical"
    BoxLayout:
        padding: "10dp"
        orientation: "horizontal"
    
        MDTextField:
            id: text_field_1
            hint_text: "Helper text"
            pos_hint: {"center_y": .5}
            text: app.text1
            
        MDTextField:
            id: text_field_2
            hint_text: "Helper text"
            pos_hint: {"center_y": .5}
            text: app.text2

    BoxLayout:
        orientation: "horizontal"
        Widget:
        MDRaisedButton:
            text: "Populate"
            on_release: app.populate()
        Widget:
    BoxLayout:
'''


class Test(MDApp):
    text1 = StringProperty()
    text2 = StringProperty()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def build(self):
        return self.screen

    def populate(self):
        self.text1 = "One"
        self.text2 = "Two"


Test().run()
```

### Screenshots

![Feb-15-2021 21-49-48](https://user-images.githubusercontent.com/2239795/107996900-710a0300-6fd9-11eb-9bc9-bd5b1cfa373b.gif)

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@runette This has already been fixed in the master branch of the library.

**Comment by runette** [comment]
No. It has not. I am using the Master Branch of the Library. It is causing this error. Have you tried the test program?

**Comment by HeaTTheatR** [comment]
@runette I always test my changes. And I didn't find any mistakes.

**Comment by HeaTTheatR** [comment]
@runette Although the test code above doesn't work ... My changes were about fixing the default text:

```python
MDTextFied(text="Text")
```

**Comment by runette** [comment]
> @runette I always test my changes. And I didn't find any mistakes.

I did not mean to suggest you do not test changes - I meant "Have you tried running the program I have included in the issue that can be used to show that the bug exists".

**Comment by HeaTTheatR** [comment]
> > @runette I always test my changes. And I didn't find any mistakes.
> 
> I did not mean to suggest you do not test changes - I meant "Have you tried running the program I have included in the issue that can be used to show that the bug exists".

https://github.com/kivymd/KivyMD/issues/858#issuecomment-779920717

**Comment by runette** [comment]
> @runette Although the test code above doesn't work ... My changes were about fixing the default text:
> 
> ```python
> MDTextFied(text="Text")
> ```

Good.

In the process, you have removed the ability to set the text using a binding to a StringProperty as shown in the example program - which is a very, very normal way of doing things. It worked 12 days ago. It does not work now. That is the issue that is stopping me from making a new build of my app.

**Comment by HeaTTheatR** [comment]
@runette I will try to fix it as soon as possible...
