### ISSUE TITLE
Max_height doesn't work

### ISSUE THREAD

**Issue by SkrodS** [kivymd/KivyMD#867]
### Description of the Bug

I'm trying to add max_height on a multiline MDTextField and it doesn't work. I'm doing all the gui in a .py file and not .kv file.
The rest of my code, that I do not include in this post, works!

The error I get is:  TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### Code and Logs

```python

#The following code is actually in a class which works. It's just the max_height that presents an issue.
self.content = MDTextField(pos_hint={'x':.01, 'top':.75}, multiline=True, max_height='200dp')  
self.add_widget(self.content)


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Versions

* OS: Ubuntu 20.04
* Python: 3.8.5
* Kivy: 2.0.0
* KivyMD: 0.104.0

**Comment by quitegreensky** [comment]
@SkrodS  i don't see any error

```python
from kivy.lang import Builder

from kivymd.app import MDApp

from kivymd.uix.textfield import MDTextField


KV = """
BoxLayout:
"""


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        self.screen.add_widget(
            MDTextField(
                pos_hint={"center_y": 0.5}, multiline=True, max_height="200dp"
            )
        )

    def build(self):
        return self.screen


Test().run()
```

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.

**Comment by podraco** [comment]
This issue will be closed February20,  2021 if there's no answer by the issue opener.

**Comment by SkrodS** [comment]
> Use KivyMD library from master branch.

Thank you! Using master branch worked.
