### ISSUE TITLE
New Version of HoverBehavior #855 breaks Tooltip in ScrollView

### ISSUE THREAD

**Issue by dafri92** [kivymd/KivyMD#869]
### Description of the Bug

The new hover behaviour in #855 breaks tooltips in ScrollView. Before commit d280f82 the tooltip worked as expected with the code below. After this commit it breaks. Please see the two attached screen recordings before and with commit d280f82.

Am I using the tooltip wrong and I got lucky before #855?

@runette 

### Code and Logs

```python
KV = '''
<IconTooltip@MDIcon+MDTooltip>

Screen:

    ScrollView:

        MDBoxLayout:
            adaptive_height: True

            IconTooltip:
                tooltip_text: 'this tooltip is not showing'
                size_hint: None, None
                size: self.texture_size
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Screen recording before #855, tooltip working as expected

https://user-images.githubusercontent.com/930308/108218636-27cec600-7135-11eb-89b3-da3f6edd2101.mov

### Screen recording after #855, tooltip no longer working

https://user-images.githubusercontent.com/930308/108218700-37e6a580-7135-11eb-9718-57349148ab54.mov

### Versions

* OS: macOS 11.2.1
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0 commit d280f82

**Comment by runette** [comment]
analyzing ...

**Comment by runette** [comment]
That appears to be a bug.

**Comment by runette** [comment]
Interesting problem. I have a solution. I want to test it a bit more but you should probably see it tomorrow latest.
