### ISSUE TITLE
Problem with MDTabs and text_size causing incorrect sizing in Tab Labels

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#874]
### Description of the Bug

This is a complicated one - so I will start with TL;DR:

> I have a problem with line 520 in `tabs.py` - it does not add anything that I can see and in a very specific circumstance it causes the Tab Label to be incorrectly sized.

Line 520 says this:
```
        if self.tab_bar.parent.allow_stretch else (self.width, None)
```

### Background

[The Fix for #534](https://github.com/kivymd/KivyMD/commit/3749028c9953238003f6d8473fd7e24d8670b52e) changed the Tab Label to be a subclass of MDLabel rather than Label (which is a good thing) and also added this code :

```
 on_tab_bar:
        self.text_size = (None, None) \
        if self.tab_bar.parent.allow_stretch else (self.width, None) 
```

I think this is wrong. The only reason for having `text_size` set is to control wrapping etc. For MDLabel, it makes sense. However, for MDTabs - as far as I can see it - there is no mode where you want the label text to wrap. So it makes no sense to set the `text_siz`e to anything. However, since MDLabel sets the `text_size` to `self.width` then it is necessary to over write`text_size` to `[None, None]` - but this should be done for all modes.

the logic that follows is to set the label width and label min_width from the texture size - which makes sense if `text-size` is not set. However, if `text_size` is set - then the texture size is set by the text_size - which we just set from `self.width` - so the whole process is circular!

### The problem

In normal operation - what I have described above does NOT cause any problems. However, it also does nothing useful which I have tested by running Kitchen sink and other apps without that line.

My main app - however- uses a non-standard font loaded in `theming`. For whatever reason - doing this means that the Label `self.width` is not set correctly until after the texture is created (there are notes to this effect in the kivy documentation). This means that line 520 sets an incorrect size - which then gets copied into the texture size.

This effect can be reproduced - but I have not put the code here since it is complicated and requires you to download some font files. Instead - I have shown the effect in the kitchen sink app. 

First with line 520

![Feb-18-2021 01-24-02](https://user-images.githubusercontent.com/2239795/108290369-27abe600-7188-11eb-8933-8b8292620479.gif)

Then without line 520

![Feb-18-2021 01-24-40](https://user-images.githubusercontent.com/2239795/108290474-68a3fa80-7188-11eb-8463-7855f060a8e3.gif)

### Versions

* OS: macos
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: latest master

**Comment by podraco** [comment]
I'm working on the tabs class.
please attach some example code. That can be run without modifications.

**Comment by podraco** [comment]
Please don't open multiple issues about the same class, just attach the problems you keep finding in only one issue.

**Comment by runette** [comment]
> Please don't open multiple issues about the same class, just attach the problems you keep finding in only one issue.

That seems a very strange way to think about it and not in accord with industry practice as I have experienced it over 40 years.  Bug reports should be single issues that can be fixed, tracked and closed and not long-running zombie issues that never get closed because they always get longer!

**Comment by runette** [comment]
> I'm working on the tabs class.
> please attach some example code. That can be run without modifications.

As stated in the issue - I cannot do the "without modifications" since to reproduce the bug you will have to download the font files. Or any font files (it does not depend on the exact font). I am happy to di that but don't come back with "without modification"!

**Comment by runette** [comment]
Change the `main.py` in kitchen sink to this : 

```
import ast
import os
import sys
from pathlib import Path

from kivy.core.window import Window
from kivy.core.text import LabelBase
from kivy.factory import Factory  # NOQA: F401
from kivy.lang import Builder
from kivy.loader import Loader
from libs.baseclass.dialog_change_theme import (
    KitchenSinkDialogChangeTheme,
    KitchenSinkUsageCode,
)
from libs.baseclass.list_items import (  # NOQA: F401
    KitchenSinkOneLineLeftIconItem,
)

from kivymd import images_path
from kivymd.app import MDApp

os.environ["KIVY_PROFILE_LANG"] = "1"

if getattr(sys, "frozen", False):  # bundle mode with PyInstaller
    os.environ["KITCHEN_SINK_ROOT"] = sys._MEIPASS
else:
    sys.path.append(os.path.abspath(__file__).split("demos")[0])
    os.environ["KITCHEN_SINK_ROOT"] = str(Path(__file__).parent)
    # os.environ["KITCHEN_SINK_ROOT"] = os.path.dirname(os.path.abspath(__file__))
os.environ["KITCHEN_SINK_ASSETS"] = os.path.join(
    os.environ["KITCHEN_SINK_ROOT"], f"assets{os.sep}"
)
Window.softinput_mode = "below_target"

font_styles = {
    "H1": ["Quicksand", 96, False, -1.5],
    "H2": ["Quicksand", 60, False, -0.5],
    "H3": ["Quicksand", 48, False, 0],
    "H4": ["Quicksand", 34, False, 0.25],
    "H5": ["Quicksand", 24, False, 0],
    "H6": ["Quicksand", 32, False, 0.15],
    "Subtitle1": ["Quicksand", 18, False, 0.15],
    "Subtitle2": ["Quicksand", 16, False, 0.1],
    "Body1": ["Quicksand", 16, False, 1.00],
    "Body2": ["Quicksand", 14, False, 1.00],
    "Button": ["Quicksand", 14, True, 1.25],
    "Caption": ["Quicksand", 12, False, 0.4],
    "Overline": ["Quicksand", 10, True, 1.5],
    "Icon": ["Icons", 24, False, 0],
}

fonts = [
    {
        "name": "Quicksand",
        "fn_regular": str(Path.cwd().joinpath("assets", "Quicksand", "Quicksand-Regular.ttf")),
        "fn_bold": str(Path.cwd().joinpath("assets", "Quicksand", "Quicksand-Bold.ttf")),
        "fn_italic": str(Path.cwd().joinpath("assets", "Quicksand", "Quicksand-Light.ttf")),
        "fn_bolditalic": str(Path.cwd().joinpath("assets", "Quicksand", "Quicksand-Medium.ttf"))
    },

]

for font in fonts:
    LabelBase.register(**font)


class KitchenSinkApp(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.theme_cls.primary_palette = "Teal"
        self.dialog_change_theme = None
        self.toolbar = None
        self.data_screens = {}
        Loader.loading_image = f"{images_path}transparent.png"
        self.theme_cls.font_styles = font_styles

    def build(self):
        Builder.load_file(
            os.path.join(
                os.environ["KITCHEN_SINK_ROOT"], "libs", "kv", "list_items.kv"
            )
        )
        return Builder.load_file(
            os.path.join(
                os.environ["KITCHEN_SINK_ROOT"], "libs", "kv", "start_screen.kv"
            )
        )

    def show_dialog_change_theme(self):
        if not self.dialog_change_theme:
            self.dialog_change_theme = KitchenSinkDialogChangeTheme()
            self.dialog_change_theme.set_list_colors_themes()
        self.dialog_change_theme.open()

    def on_start(self):
        """Creates a list of items with examples on start screen."""

        Builder.load_file(
            os.path.join(
                os.environ["KITCHEN_SINK_ROOT"],
                "libs",
                "kv",
                "dialog_change_theme.kv",
            )
        )

        with open(
            os.path.join(
                os.environ["KITCHEN_SINK_ROOT"], "screens_data.json")
        ) as read_file:
            self.data_screens = ast.literal_eval(read_file.read())
            data_screens = list(self.data_screens.keys())
            data_screens.sort()
        for name_item_example in data_screens:
            self.root.ids.backdrop_front_layer.data.append(
                {
                    "viewclass": "KitchenSinkOneLineLeftIconItem",
                    "text": name_item_example,
                    "icon": self.data_screens[name_item_example]["icon"],
                    "on_release": lambda x=name_item_example: self.set_example_screen(
                        x
                    ),
                }
            )

    def set_example_screen(self, name_screen):
        manager = self.root.ids.screen_manager
        if not manager.has_screen(
            self.data_screens[name_screen]["name_screen"]
        ):
            name_kv_file = self.data_screens[name_screen]["kv_string"]
            Builder.load_file(
                os.path.join(
                    os.environ["KITCHEN_SINK_ROOT"],
                    "libs",
                    "kv",
                    f"{name_kv_file}.kv",
                )
            )
            if "Import" in self.data_screens[name_screen]:
                exec(self.data_screens[name_screen]["Import"])
            screen_object = eval(self.data_screens[name_screen]["Factory"])
            self.data_screens[name_screen]["object"] = screen_object
            if "toolbar" in screen_object.ids:
                screen_object.ids.toolbar.title = name_screen
            manager.add_widget(screen_object)
        code_file = os.path.join(
            os.environ["KITCHEN_SINK_ROOT"],
            "assets",
            "usage",
            self.data_screens[name_screen]["source_code"],
        )
        with open(code_file, "r") as f:
            self.sample_code = f.read()
            self.screen_name = name_screen
            self.website = self.data_screens[name_screen]["more_info"]
        manager.current = self.data_screens[name_screen]["name_screen"]

    def back_to_home_screen(self):
        self.root.ids.screen_manager.current = "home"

    def switch_theme_style(self):
        self.theme_cls.theme_style = (
            "Light" if self.theme_cls.theme_style == "Dark" else "Dark"
        )
        self.root.ids.backdrop.ids._front_layer.md_bg_color = [0, 0, 0, 0]

    def show_code(self):
        if self.theme_cls.device_orientation == "landscape":
            code = KitchenSinkUsageCode(
                code=self.sample_code,
                title=self.screen_name,
                website=self.website,
            )
            code.open()


KitchenSinkApp().run()

```

and load the contents of this zip into the `assets` folder (it is a Google Fonts asset so it is openly licensed so ok to copy here)

[Quicksand.zip](https://github.com/kivymd/KivyMD/files/6001663/Quicksand.zip)

**Comment by podraco** [comment]
> > Please don't open multiple issues about the same class, just attach the problems you keep finding in only one issue.
> 
> That seems a very strange way to think about it and not in accord with industry practice as I have experienced it over 40 years. Bug reports should be single issues that can be fixed, tracked and closed and not long-running zombie issues that never get closed because they always get longer!

That's a great work practice. But only for big companies.
As you can see, this is a project where people often come and go. so unless you have a master issue that references to these small issues, the whole issue report can't track everything. And might or might not be drawn between reports.

**Comment by podraco** [comment]
A good work practice would be adding the Class at the start of the name to set where it belongs without having to enter the issue.
Something like:
MDTabs: Size issue
MDTabs:  padding issue
MDTabs: property not used
MDtabs: Material IO Update required.
and so on.
something short and consistent.

**Comment by podraco** [comment]
> > I'm working on the tabs class.
> > please attach some example code. That can be run without modifications.
> 
> As stated in the issue - I cannot do the "without modifications" since to reproduce the bug you will have to download the font files. Or any font files (it does not depend on the exact font). I am happy to di that but don't come back with "without modification"!

`Without modification` means that anyone who wants to analyze the issue can copy and paste the code to reproduce the error.

**Comment by runette** [comment]
> `Without modification` means that anyone who wants to analyze the issue can copy and paste the code to reproduce the error.

Yep - and as you can see you cannot reproduce this error by cutting and pasting the code - you also have to download the font file. I am admittedly being very precise about my use of language :)

**Comment by runette** [comment]
> A good work practice would be adding the Class at the start of the name to set where it belongs without having to enter the issue.
> Something like:
> MDTabs: Size issue
> MDTabs: padding issue
> MDTabs: property not used
> MDtabs: Material IO Update required.
> and so on.
> something short and consistent.

Good idea. If that is what you want then all is needed is for that to be documented. You might notice that - give or take some punctuation and syntax - that is what I did!

I admit that I spent more than enough years working for Google and a lot of my ideas are influenced by their "big company" thinking - although Google has never been organised enough about anything to have less than 5 ways of doing any one thing!

That said - I do not see how zombie issues, that never die, help any size of company. I can understand a grouping issue that basically says "these are the issues we plan to address in the next version". But I have never yet met a new version that implemented everything that was planned and you still want to be able to close the grouping issue on release but, if necessary, keep the subordinate issues open for later fixes.

**Comment by podraco** [comment]
What I'm talking about is order. An easy way to track every work that is going on and avoid zombie issues.

**Comment by podraco** [comment]
And after some test and fixes, I can say that, that line is one of the most important ones in the code. Since it can be used to update the widget width properly.

Here's a simple example.


https://user-images.githubusercontent.com/5509325/108427350-a3e30f80-7202-11eb-863a-d36f78ebe54d.mp4


Yet, for some reason the ripple behavior is broken...

**Comment by podraco** [comment]
https://user-images.githubusercontent.com/5509325/108446394-a86bf000-7223-11eb-93cb-8b0bb03cab05.mp4

This example uses the assets you gave.

**Comment by runette** [comment]
This issue has NOT been solved in the latest release.

It can be reproduced in the latest version of Kitchen SInk.

NOTE - to reproduce this problem, the MDTab must be set to allow_stretch=False
NOTE ALSO - in the current version of Kitchen sink - the allow_stretch attribute is applied to the wrong class - it must be applied to the MDTab class and not the MDTabBase class. If this is corrected - you get this

<img width="799" alt="Screenshot 2021-02-20 at 00 18 37" src="https://user-images.githubusercontent.com/2239795/108575500-5a81e580-7312-11eb-82e7-3d13e2764a71.png">
