### ISSUE TITLE
MDDatePicker code on website not working + on_save and on_close not working after fix 

### ISSUE THREAD

**Issue by grummble-ai** [kivymd/KivyMD#876]
The following code is taken from the website (https://kivymd.readthedocs.io/en/latest/components/pickers/index.html) and is currently not working (callback required):

`from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.picker import MDDatePicker

KV = '''
MDFloatLayout:

    MDToolbar:
        title: "MDDatePicker"
        pos_hint: {"top": 1}
        elevation: 10

    MDRaisedButton:
        text: "Open time picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_date_picker()
'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_save(self, instance, value, date_range):
        '''
        Events called when the "OK" dialog box button is clicked.

        :type instance: <kivymd.uix.picker.MDDatePicker object>;

        :param value: selected date;
        :type value: <class 'datetime.date'>;

        :param date_range: list of 'datetime.date' objects in the selected range;
        :type date_range: <class 'list'>;
        '''

        print(instance, value, date_range)

    def on_cancel(self, instance, value):
        '''Events called when the "CANCEL" dialog box button is clicked.'''

    def show_date_picker(self):
        date_dialog = MDDatePicker()
        date_dialog.bind(on_save=self.on_save, on_cancel=self.on_cancel)
        date_dialog.open()

Test().run()`

I have added the callback method 

`
    def get_date(self, date):
        '''
        :type date: <class 'datetime.date'>
        '''
`
and changed the datepicker to 

`
date_dialog = MDDatePicker(callback=self.get_date)
`
and now it opens just fine. 

The only issue left is that the on_save and on_close actions are not working. If I debug, it won't go into either method so I guess there's an issue with the binding method? 

Best,
Grummble

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.
