### ISSUE TITLE
MDTabs: allow_stretch not working

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#878]
### Description

With the latest update to MDTabs - `allow_stretch` is not working. This is because you have removed the code that implemented it.

### 

Run this test application:

```
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
        allow_stretch: True

<Tab>:

    MDLabel:
        text: "Content"
        

'''

class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''

class Test(MDApp):

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.tabs.add_widget(Tab(text="One"))
        self.root.ids.tabs.add_widget(Tab(text="Two"))


Test().run()
```

With the current version - you get this:

<img width="800" alt="Screenshot 2021-02-19 at 21 18 58" src="https://user-images.githubusercontent.com/2239795/108563120-dc651500-72f8-11eb-8727-40969636cdc5.png">

With the previous version - you get this :

https://user-images.githubusercontent.com/2239795/108563183-f43c9900-72f8-11eb-94ed-01c6c06c6ef1.mp4

* OS: macos
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: Master Latest

**Comment by podraco** [comment]
It is true, a bug, and yet wrong. The spec states that tabs can only be 150dp long, I'm working on it right now.

**Comment by podraco** [comment]
![Captura de pantalla de 2021-02-20 01-29-18](https://user-images.githubusercontent.com/5509325/108587763-19da9a00-731b-11eb-9dc7-1dce9afac7f3.png)

so far, it's fixed.
Now, it updates the text_size to None, None, and then updates it again to lock the wrapping. I'm testing different configurations.
Added the scrollable padding when the tab navigation is scrollable.
Blocked the scroll when the width from GridLayout is lesser than the scrollview one.

**Comment by podraco** [comment]
After all night testing and debugging i believe it will work now, ill open a Pr in the morning, cant read anymore XD

**Comment by podraco** [comment]
as a quick resume of the changes
allow stretch will allow the tabs to stretch from 90 to 150 width, while it's True, if it's false, then the new property is set (`fixed_tab_label_width`) which by default is set to `100dp`, 

The label is locked to 2 Lines, either is shorten or has an icon on top.
some KV code  has been removed, it wasnt used anymore, since it was changed in a event that happens when the widget is added on screen.

https://user-images.githubusercontent.com/5509325/108592134-f838dd00-7331-11eb-8501-413ad04d58fc.mp4

(in the video `allow_stretch` is set between `False` and `True`)

**Comment by runette** [comment]
You are talking about fundamental changes to the API for an existing component that is used by people in existing applications - many of which are probably commercial.

Can I please ask for a discussion - i.e. submit as a PR and not commit direct to the master code base and give people a chance to look at the changes and comment on them.

Just fundamentally changing the API and behaviour of components without any discussion and agreement on what the changes are, is a real problem if you are using this library for real life uses (even though it is currently marked as beta - I acknowledge that).

**Comment by HeaTTheatR** [comment]
@runette Are we fundamentally changing the API?

**Comment by runette** [comment]
If `allow_stretch` previously did 'x' and now does 'y' and that looks different and feels different to the app users - then yes. That is the definition of a change to the API. 

It is at least respectful of your users to provide a way of commenting on the change and recording that conversation.

**Comment by HeaTTheatR** [comment]
@runette If some API changes, we must warn the user. For example:

![Снимок экрана 2021-02-20 в 17 33 23](https://user-images.githubusercontent.com/16930280/108599359-c2cbd800-73a1-11eb-9ac2-5c198ecdf4a5.png)

**Comment by HeaTTheatR** [comment]
@runette @podraco I also don't like that the `allow_stretch` parameter wraps the label to the next line:

![Снимок экрана 2021-02-20 в 17 36 19](https://user-images.githubusercontent.com/16930280/108599448-3ec62000-73a2-11eb-89a2-23cb41ffeed6.png)

**Comment by runette** [comment]
> @runette If some API changes, we must warn the user. For example:
> 
> ![Снимок экрана 2021-02-20 в 17 33 23](https://user-images.githubusercontent.com/16930280/108599359-c2cbd800-73a1-11eb-9ac2-5c198ecdf4a5.png)

Agreed. But if it just changed by commit then it cannot be deprecated. If `allow_stretch` has already changed - then it is not deprecated, it has already changed.

**Comment by runette** [comment]
> It is true, a bug, and yet wrong. The spec states that tabs can only be 150dp long, I'm working on it right now.

Where do you get the figure of 150dp from? The only definition I can find is this :

<img width="794" alt="Screenshot 2021-02-20 at 15 19 19" src="https://user-images.githubusercontent.com/2239795/108600441-24367b80-738f-11eb-9697-f9c476c4a9a6.png">

**Comment by runette** [comment]
> allow stretch will allow the tabs to stretch from 90 to 150 width, while it's True, if it's false, then the new property is set (`fixed_tab_label_width`) which by default is set to `100dp`,

This does not seem to be in line with the material guidelines. What I understand is :

1. The minimum size should be 90dp
2. There is a maximum size (although I am not sure it actually is 150 as opposed to 360) after which the label should wrap or truncate
3. If the tabs are "Fixed Tabs" then the tabs should expand to cover the whole tab bar if possible - otherwise start scrolling
4. If "Scrollable Tab"  then the Tab should be set by the text length and scroll (except as per 2)

I do not know where a fixed tab size of 100dp comes from. I know that would break my app (although there is a question that will out in another response about windows/ mac).

I propose that we try to avoid hard coded limits except where the reason and the material.io justification is clear. KivyMD can't be idiot-proof - an MD app still requires the developer to apply MD in their design judiciously.

**Comment by podraco** [comment]
It is true, it's 360, I misread
100 dp is a place holder for the developer to set the value it requires. it's only used when the allow_stretch is false
with this, the value could be set to a X/root.width part for fixed tabs and update the contents.

**Comment by podraco** [comment]
now that that is proposed, what do we do about this?
![Captura de pantalla de 2021-02-20 16-40-43](https://user-images.githubusercontent.com/5509325/108610318-6913df80-739a-11eb-9f6d-dbb5a7818235.png)

Should we truncate the fixed tab behavior to 4 tabs in the carousel?

**Comment by podraco** [comment]
As well, should we consider applying this as part of the tabs class?

![Captura de pantalla de 2021-02-20 16-39-44](https://user-images.githubusercontent.com/5509325/108610356-b7c17980-739a-11eb-8415-429d7dc2695c.png)

**Comment by runette** [comment]
My opinion - "Clustered Fixed Tabs" - adding too much complication at this stage. Make it an enhancement and come back to it later.

**Comment by runette** [comment]
My opinion - Fixed Tab Placement :

Don't over complicated and try to *enforce* all guidelines. If the developer asks for Fixed Tabs (i.e. `allow_stretch` in the old version) - try 'the width of the tab bar divided by the number of tabs' approach and if that fails auto-fallback to Scrollable Tabs.

Leave specific guidelines about when to use Fixed or Scrollable Tabs to the app developer.

This is actually the behaviour we had before.

**Comment by podraco** [comment]
> My opinion - Fixed Tab Placement :
> 
> Don't over complicated and try to _enforce_ all guidelines. If the developer asks for Fixed Tabs (i.e. `allow_stretch` in the old version) - try 'the width of the tab bar divided by the number of tabs' approach and if that fails auto-fallback to Scrollable Tabs.
> 
> Leave specific guidelines about when to use Fixed or Scrollable Tabs to the app developer.
> 
> This is actually the behaviour we had before.

I'm getting mixed responses, Doesn't that contradicts the idea of the framework you mentioned before?
What do you say @HeaTTheatR, how should i proceed?

**Comment by podraco** [comment]
> My opinion - "Clustered Fixed Tabs" - adding too much complication at this stage. Make it an enhancement and come back to it later.

thats a good idea.

**Comment by runette** [comment]
> > My opinion - Fixed Tab Placement :
> > Don't over complicated and try to _enforce_ all guidelines. If the developer asks for Fixed Tabs (i.e. `allow_stretch` in the old version) - try 'the width of the tab bar divided by the number of tabs' approach and if that fails auto-fallback to Scrollable Tabs.
> > Leave specific guidelines about when to use Fixed or Scrollable Tabs to the app developer.
> > This is actually the behaviour we had before.
> 
> I'm getting mixed responses, Doesn't that contradicts the idea of the framework you mentioned before?
> What do you say @HeaTTheatR, how should i proceed?

Could you be more specific about which part of what I said you think is contradictory? 

But my general statement was "don't enforce / hard code anything unless clearly specified in material.io". That does not mean "do enforce what is specified in material.io". Sometimes - it is work without value. In this case -you could enforce the 4 tab guideline and cover all possible corner cases but why? If the app developer wants 5 fixed tabs - sure their app breaks the guidelines. That is their problem. They cannot build a good MD app just with kivyMD without also knowing Material Design themselves.

**Comment by podraco** [comment]
Wouldn't that place the bar too high?

**Comment by HeaTTheatR** [comment]
Use `tab_hint_x` instead of `allow_stretch`:

```
    MDTabs:
        tab_hint_x: True
```

This has already been fixed https://github.com/kivymd/KivyMD/pull/887
Although we still have a number of problems with the `MDTabs` class, this issue can be closed.
