### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by juanjavatus** [kivymd/KivyMD#88]
Hi,
How can I change MDIcon size? I have tried modifying font_size but has no effect.
Regards

**Comment by HeaTTheatR** [comment]
This cannot be done. And no need to do this.

**Comment by BillBridge** [comment]
Hi, I made the sizes in KivyMD more flexible through the kivy config file as follows:

1. At the very beginning of your application init the kivy config.

from kivy.config import Config

if mymode == 'COMPACT':
	HORIZ_MARGINS = 16
	TITELHEIGHT = 56
	SUBHEIGHT = 48
	HEADHEIGHT = 42
	ROWHEIGHT = 36
	ITEMHEIGHT = 24
	SPACING = 6
	PADDING = 9
	FONT_TITLE = 16
	FONT_SUBHEAD = 13
	FONT_BODY = 12
	FONT_ICON1 = 18
	FONT_ICON2 = 13
	FONT_CHIP = 10
else:
	HORIZ_MARGINS = 24
	TITELHEIGHT = 80
	SUBHEIGHT = 64
	HEADHEIGHT = 56
	ROWHEIGHT = 48
	ITEMHEIGHT = 32
	SPACING = 8
	PADDING = 12
	FONT_TITLE = 20
	FONT_SUBHEAD = 16
	FONT_BODY = 14
	FONT_ICON1 = 24
	FONT_ICON2 = 18
	FONT_CHIP = 13

Config.set('myconfig', 'horiz_margins', HORIZ_MARGINS)
Config.set('myconfig', 'titleheight', TITELHEIGHT)
Config.set('myconfig', 'subheight', SUBHEIGHT)
Config.set('myconfig', 'headheight', HEADHEIGHT)
Config.set('myconfig', 'rowheight', ROWHEIGHT)
Config.set('myconfig', 'itemheight', ITEMHEIGHT)
Config.set('myconfig', 'spacing', SPACING)
Config.set('myconfig', 'padding', PADDING)
Config.set('myconfig', 'font_title', FONT_TITLE)
Config.set('myconfig', 'font_subhead', FONT_SUBHEAD)
Config.set('myconfig', 'font_body', FONT_BODY)
Config.set('myconfig', 'font_icon1', FONT_ICON1)
Config.set('myconfig', 'font_icon2', FONT_ICON2)
Config.set('myconfig', 'font_chip', FONT_CHIP)

Config.write()

2. Then in __init__.py of kivymd get the configuration. Add the following lines.
from kivy.config import Config

HORIZ_MARGINS = Config.get('novaguide', 'horiz_margins')
TITLEHEIGHT = Config.get('novaguide', 'titleheight')
SUBHEIGHT = Config.get('novaguide', 'subheight')
HEADHEIGHT = Config.get('novaguide', 'headheight')
ROWHEIGHT = Config.get('novaguide', 'rowheight')
ITEMHEIGHT = Config.get('novaguide', 'itemheight')
SPACING = Config.get('novaguide', 'spacing')
PADDING = Config.get('novaguide', 'padding')
FONT_TITLE = Config.get('novaguide', 'font_title')
FONT_SUBHEAD = Config.get('novaguide', 'font_subhead')
FONT_BODY = Config.get('novaguide', 'font_body')
FONT_ICON1 = Config.get('novaguide', 'font_icon1')
FONT_ICON2 = Config.get('novaguide', 'font_icon2')
FONT_CHIP = Config.get('novaguide', 'font_chip')

3. Use the new definitions in the appropriate py/kv files.
import kivymd as kmd

mgrid = GridLayout(cols=1, orientation='vertical', padding=dp(1), spacing=dp(1),
                           row_default_height=dp(kmd.ITEMHEIGHT), size_hint=(1, None))

**Comment by juanjavatus** [comment]
Hi again,
Thanks BillBridge.
I have found a way to resize the icon. In case somebody has the need, here is some code:

from kivy.app import App
from kivy.lang import Builder
from kivy.properties import StringProperty
from kivymd.label import MDLabel

kv = '''
#:import md_icons kivymd.icon_definitions.md_icons
#:import FloatLayout kivy.uix.floatlayout
FloatLayout:
    size_hint: (None, None)
    size: 50,50
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    canvas:
        Color:
            rgba: (.6, .6, .6, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    Icon:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        halign: 'center'
        font_style: 'Icon'
        icon_name: 'bank'
        text: md_icons.get(self.icon_name)
        font_size: 24
'''

class Icon(MDLabel):
    icon_name = StringProperty()

    def on_touch_down(self, touch):
        if self.collide_point(*touch.opos):
            self.font_size = 48

    def on_touch_up(self, touch):
        if self.collide_point(*touch.opos):
            self.font_size = 24

class ResizeIconApp(App):

    def build(self):
        return Builder.load_string(kv)


if __name__ == '__main__':
    ResizeIconApp().run()

Regards
