### ISSUE TITLE
MDTabs: Unnecessary hard coded formating

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#880]
### Description of the Bug

There are three areas where the new MDTabs hard codes formatting and styles. This is bad practice.

1. The `font_style` is hardcoded to 'Button'. This should be an OptionProperty defaulted to 'Button'
2. The `font_size` is hardcoded to `sp(14)` - this should be taken from the definition for the font_style that is currently chosen. As a side note - it should be taken from the instance of the font_definition currently loaded into the app theme_cls to retain the correct theming behavior.
3. When the title is set by the `title` attribute, it is hardcoded to be upper case. This is just wrong. If the app programmer wants upper case - they can easily set it themselves. This should NOT be hard coded into the framework and is NOT specified in material.io.

**Comment by runette** [comment]
Actually - on line 758 not only is the title made upper case for a second time it is also hardcoded to be bold. material.io does not specify that the tab label should be bold.

**Comment by podraco** [comment]
Last time I read it, The material IO defines that the Tabs should use the Button style, and bold. Let me check it.

**Comment by podraco** [comment]
I was wrong I misunderstood the info, and applied the example spec definition to the tabs label.
What do you propose to be the current tab style?

**Comment by podraco** [comment]
Even tho, the tabs are buttons, should we add a theme style pointer, so the end developer could set the style manually?

**Comment by HeaTTheatR** [comment]
@podraco What do you mean by "button style"?

**Comment by runette** [comment]
I suggest, or propose, the following:

1 No formatting should be hardcoded - it should all be a matter of configuration
2 create a font_style property and default to "Button" font_style but allow the app dev to change it
3 derive the formatting from the font style. As I said above - this needs to be derived from the `font_style` property of the current `theme_cls` so that theme changes to the app are correctly reflected.

The changes needed are not complicated and I can PR a suggestion quite quickly - I am just aware that this class is under development and I don't want to do it unilaterally.

**Comment by podraco** [comment]
> @podraco What do you mean by "button style"?

label.font_style="Button", from the theme manager.

**Comment by podraco** [comment]
> I suggest, or propose, the following:
> 
> 1 No formatting should be hardcoded - it should all be a matter of configuration
> 2 create a font_style property and default to "Button" font_style but allow the app dev to change it
> 3 derive the formatting from the font style. As I said above - this needs to be derived from the `font_style` property of the current `theme_cls` so that theme changes to the app are correctly reflected.
> 
> The changes needed are not complicated and I can PR a suggestion quite quickly - I am just aware that this class is under development and I don't want to do it unilaterally.

Should we set it individually for every tab or only for the tablayout?

**Comment by runette** [comment]
> Should we set it individually for every tab or only for the tablayout?

By 'it' - I assume that you mean the font_style. I would think it would be best to follow normal kivy practice and have it configured on the instance of MDTabs.

**Comment by podraco** [comment]
then the use would be something like:

```yaml
<CTab>
    font_style: "Button"

RootWidget:
    MDTabs:
        id: tabs_manager
        CTab:
            [...]
        CTab:
            [...]
        CTab:
            [...]
```

Should we allow `"Custom"` as a valid style, Or block that option?

**Comment by runette** [comment]
> Should we allow `"Custom"` as a valid style, Or block that option?
as usual - just my opinion but since we are talking about font_style and font_styles are defined in a font_style object we should limit the selection to what is defined in the font_style object.

**Comment by podraco** [comment]
Then let me see how it works, since last time I knew it was changed to allow custom styles registered...
