### ISSUE TITLE
Text size abnormally large on Android with Font Size on Large in Phone Settings

### ISSUE THREAD

**Issue by YarosMallorca** [kivymd/KivyMD#884]
### Description of the Bug

The font size appears VERY BIG when compiled and ran on android where font size in settings is set to large. Is there a way to make kivymd / kivy ignore that?

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    MDLabel:
        text: "TEST"
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Bug: https://user-images.githubusercontent.com/69392733/107875481-77f12280-6ec0-11eb-89d7-cdb41f12221e.jpg

How it should be: https://drive.google.com/file/d/1-ESJocPnKqQifPS1dP7sp9BK5_TpQP4w/view?usp=sharing

### Versions

* OS: Android 10 & 11 Tested
* Python: 3.7.6
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Try testing on other versions of Android devices ...

**Comment by YarosMallorca** [comment]
Tried on multiple phones, same thing!

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Can you provide more specific versions of the device and screenshoots?

**Comment by YarosMallorca** [comment]
I think the screenshot is a Samsung device, not my phone (running android 6 or 7), also tested on a Samsung A50, same problem; Google Pixel 4 same thing!

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder I need screenshots.

**Comment by YarosMallorca** [comment]
![Screenshot_20210221-150154_365 Facts.jpg](https://user-images.githubusercontent.com/54041533/108627426-d89ad500-7455-11eb-9121-d92730c6ab86.jpg)

![Screenshot_20210221-150138_365 Facts.jpg](https://user-images.githubusercontent.com/54041533/108627432-dc2e5c00-7455-11eb-9df3-a8f21612ae2d.jpg)

![Screenshot_20210221-150133_365 Facts.jpg](https://user-images.githubusercontent.com/54041533/108627435-e0f31000-7455-11eb-89f3-efa681159aaa.jpg)

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder You did not understand me. We need screenshots not of one model, but of all on which you tested.

**Comment by YarosMallorca** [comment]
Okay, I will close this issue now because I tried on other phones / devices and only with two devices running lower versions of android this bug happened!
