### ISSUE TITLE
MDTabs - No Valid Icon was found.  No valid Title was found.  Icon   = ""    Title    = "" ->  kivymy.uix.tab.update_text() function 

### ISSUE THREAD

**Issue by spreadsomejelly** [kivymd/KivyMD#885]
### Description of the Bug
When using MDTabs -> getting _No Valid Icon was Found_ **ValueError** (line #758 in kivymy.uix.tab._update_text).  Tried setting title, icon, text independently, then together (several variations - to make sure I'm not losing my mind).  I tried using a separate KV file, and also putting a KV string inside the main.py file; however, no dice.  It seems as though the MDTabsBase class is instantiating without the text value, even though the parameter is set.  Thoughts?  

### Code and Logs

```python
import kivy # 96 dpi
#kivy.require('1.11.1')
from kivy.app import App
from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.floatlayout import MDFloatLayout

kv = """
MDBoxLayout:
	MDTabs:
		Tab:
			#text: 'Work'
			#title: 'Now'
			icon: 'chevron-up'
		Tab:
			#text: 'Please'
			#title: 'Goddamnit'
			icon: 'chevron-down'
"""
class Tab(MDFloatLayout, MDTabsBase):

	def __init__(self, **kwargs):
		super(Tab, self).__init__(**kwargs)

class TestApp(MDApp):
	
	def build(self):
		pass # when using the KV File
                #Builder.load_string(kv)
               
if __name__ == '__main__':
	TestApp().run()

---------------------------------------------------------------------------------
#(KV File - same instructions)
# ROOT
MDBoxLayout:
	MDTabs:
		Tab:
			#text: 'Work'
			#title: 'Now'
			icon: 'chevron-up'
		Tab:
			#text: 'Please'
			#title: 'Goddamnit'
			icon: 'chevron-down'
"""
```
### ERROR/Trace
[WARNING] stderr:   File "C:\Users\spreadsomejelly\.virtualenvs\banana_pudding_pops\lib\site-packages\kivymd\uix\tab.py", line 732, in __init__
[WARNING] stderr:     self._update_text()
[WARNING] stderr:   File "C:\Users\spreadsomejelly\.virtualenvs\banana_pudding_pops\lib\site-packages\kivymd\uix\tab.py", line 758, in _update_text
[WARNING] stderr:     f"{self}: [UID] = [{self.uid}]:\n\t"
[WARNING] stderr: ValueError: <kivy.factory.Tab object at 0x127A7970>: [UID] = [2336]:
[WARNING] stderr: 	No valid Icon was found.
[WARNING] stderr: 	No valid Title was found.
[WARNING] stderr: 	Icon	= ''
[WARNING] stderr: 	Title	= ''
[WARNING] stderr: 	

### Versions

* OS: Windows 7
* Python: 3.7.4
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by spreadsomejelly** [comment]
I think we are dealing with the "Truthiness of Python" on this issue.  Setting the tab.py **StringProperty** class params to the default empty string ("") instead of hardcoding an actual string or string space (i.e. " ") is getting caught by line #747 and then on.  With that said, if you change the MDTabsBase **StringProperty** **text** param inside kivymd.uix.tab.py to " ", you're golden.  I think the problem is that when you get so deep into multiple inheritance like we are with a framework like this, the brain starts spinning (and that's not just because I've been day drinking).  The next problem to solve is the size_hint issues causing too much iteration.  I love this framework, and I think it will become the preeminent Python GUI framework.  

P.S.  I didn't create a pull for this because I think the _update_text function needs to be slightly modified/refactored.

**Comment by podraco** [comment]
Ok, I'm working on it.

this is my proposal
https://github.com/podraco/KivyMD
what do you think?

**Comment by spreadsomejelly** [comment]
Beautiful!! I think that will work perfectly.  I'm dealing with another inheritance issue right now for another class, so my app won't properly load.  However, it passed the error I was describing earlier, so I believe you fixed it!  Great job man!  Thank you :)

**Comment by podraco** [comment]
Remember to open an issue if it's related to KivyMD we will analyze it as soon as possible.
If it's caused by a specific class use the following format, it will make things easier to keep track of the bugs.

`MDClassName - Issue Title`

**Comment by syleishere** [comment]
I am getting exact same error, anything happening on this?

    MDNavigationLayout:
        ScreenManager:
            id: manager
            Screen:
                name: 'Page_1'
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        id: toolbar
                        #pos_hint: {"x": 0, "top": 1}
                        #size_hint: 1, 0.4
                        elevation: 10
                        title: app.title
                        left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
                        #left_action_items: [['menu', lambda x: print(x)], ['bookmark', lambda x: print(x)]]
                        #right_action_items: [['magnify', lambda x: print(x)], ['bookmark', lambda x: print(x)]]
                    MDTabs:
                        #size_hint_y: 0.23
                        id: tabs
                        #on_tab_switch: app.on_tab_switch(*args)
                        Tab1:
                            id : tab1
                            text: "Play Me!"
                        Tab2:
                            id: tab2
                            text: "Play Baby!"
                        Tab3:
                            id: tab3
                            text: "Play Sexy!"
                        Tab4:
                            id: tab4
                            text: "Play Cutie"
                    Songlist:
                        id: songlist
                    Controls:
                        id: controls


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer



02-25 09:12:11.416 11606 11640 I python  :    File "/home/dan/python/apps/sunsaturn/helloworld/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/hello
world/kivymd/uix/tab.py", line 757, in _update_text
02-25 09:12:11.417 11606 11640 I python  :  ValueError: <kivy.factory.Tab1 object at 0xb6cac338>: [UID] = [768]:
02-25 09:12:11.417 11606 11640 I python  :      No valid Icon was found.
02-25 09:12:11.417 11606 11640 I python  :      No valid Title was found.
02-25 09:12:11.417 11606 11640 I python  :      Icon    = ''
02-25 09:12:11.417 11606 11640 I python  :      Title   = ''
02-25 09:12:11.417 11606 11640 I python  :
02-25 09:12:11.417 11606 11640 I python  : Python for android ended.

**Comment by HeaTTheatR** [comment]
@syleishere https://github.com/kivymd/KivyMD/pull/887

**Comment by Progvank** [comment]
I am a beginner, I didn't get any of that, I'm still having the same error
