### ISSUE TITLE
MDTab flashes while switching

### ISSUE THREAD

**Issue by sina76n** [kivymd/KivyMD#89]
Hi. I have issue with switching between MDTabsBase. the problem is while i try to switch between tabs, MDTabsBase icons mess and flashes for a moment. this happens in kitchen_sink example too. on windows and android both. Thanks for any help
[code.zip](https://github.com/HeaTTheatR/KivyMD/files/3508982/code.zip)

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Tabs
