### ISSUE TITLE
MDDatePicker Edit input button MDIconButton not working properly

### ISSUE THREAD

**Issue by ParthibanSoundram** [kivymd/KivyMD#890]
### Description of the Bug

Hi I just updated the latest KIVY MD version  0.104.2.dev0
with the reference of https://buildmedia.readthedocs.org/media/pdf/kivymd/latest/kivymd.pdf.
The date picker color-changing operations are working well. But while giving input using manual date enter that time not working. I am not able to type. How do I disable that "PENCIL" icon from the calendar display?

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder
from kivymd.uix.picker import MDDatePicker
from kivy.utils import get_color_from_hex


kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)
        picker = MDDatePicker(
                primary_color=get_color_from_hex("#de7227"),
                selector_color=get_color_from_hex("#39b195"),
                text_current_color=get_color_from_hex("#39b195"),
                text_button_color=get_color_from_hex("#39b195"),
                input_field_text_color=get_color_from_hex('#231f20')
            )
            picker.bind(on_save=self.on_save)
            picker.open()


if __name__ == '__main__':
    MainApp().run()
```

### Versions

* OS: WINDOWS 10
* Python: 3.6
* Kivy: 2.0
* KivyMD:  0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@ParthibanSoundram I do not understand the essence of your issue. Please provide additional information: more detailed description of the problem, screenshots, etc.
