### ISSUE TITLE
Can't display text in other languages

### ISSUE THREAD

**Issue by WISEPLAT** [kivymd/KivyMD#891]
### Description of the Bug

Hello! Can't display text in other languages, for example in China, Korean and Hindi.

How to set default font to display them correctly in KivyMD application?

For example in PyCharm editor with default font JetBrains Mono these text is displayed.

Please help, Thanks!

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .7}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        #menu_items = [{"text": f"Item {i}"} for i in range(5)]
        menu_items = [{"text": 'English'},
                      {"text": 'Русский'},
                      {"text": 'Deutsch'},
                      {"text": 'Français'},
                      {"text": '中文'},
                      {"text": '한국어'},
                      {"text": 'हिन्दी'}]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)

    def build(self):
        return self.screen


Test().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

![Image](https://i.paste.pics/809fa0bde8979ff250d369b08abce21d.png?trs=cf4a8ec8176d601ba21b2adb58577b1bcf857a5d4b0a9c03570c3b6e26c4ad23)

### Versions

* OS: Windows 10
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by podraco** [comment]
That either means that the font doesn't have the characters or the kivy backend can't load those characters.

**Comment by WISEPLAT** [comment]
> That either means that the font doesn't have the characters or the kivy backend can't load those characters.

Hi! How can I change the default font to display that characters? And which font I should use for this?

**Comment by podraco** [comment]
You can use word to see what fonts you would like to use.

Also, You can register new font sources with  the kivy label class and also, you can create new font themes with the font manager.

Read the kivy's Label docs to know how to register with their framework in more depth.

Or, if you don't want to get too deep into it, you can read the kivymd docs/tutorial on how to add a new font style https://kivymd.readthedocs.io/en/latest/themes/theming/#kivymd.theming.ThemeManager.font_styles

also, you will need to research how fonts works, since you will be using different characters than English (different codes than the normals)

**Comment by WISEPLAT** [comment]
> You can use word to see what fonts you would like to use.
> 
> Also, You can register new font sources with the kivy label class and also, you can create new font themes with the font manager.
> 
> Read the kivy's Label docs to know how to register with their framework in more depth.
> 
> Or, if you don't want to get too deep into it, you can read the kivymd docs/tutorial on how to add a new font style https://kivymd.readthedocs.io/en/latest/themes/theming/#kivymd.theming.ThemeManager.font_styles
> 
> also, you will need to research how fonts works, since you will be using different characters than English (different codes than the normals)

Thanks for the answer.
Can I change font theme on the fly? To append new font to new language?
(I want to create multilingual app)

**Comment by podraco** [comment]
I'm not sure, never had the necessity to, but you can try, if it launches an event update, it should update every label.

**Comment by WISEPLAT** [comment]
> I'm not sure, never had the necessity to, but you can try, if it launches an event update, it should update every label.

```python
KV = '''
Screen:

    BoxLayout:
        orientation: 'vertical'
                    
        MDLabel:
            text: "JetBrainsMono"
            font_style: "my_selected_font"       
        MDLabel:
            text: "English"
            font_style: "my_selected_font"
        MDLabel:
            text: "Русский"
            font_style: "my_selected_font"
        MDLabel:
            text: "Deutsch"
            font_style: "my_selected_font"
        MDLabel:
            text: "Français"
            font_style: "my_selected_font"
        MDLabel:
            text: "中文"
            font_style: "my_selected_font"
        MDLabel:
            text: "한국어"
            font_style: "my_selected_font"
        MDLabel:
            text: "हिन्दी"
            font_style: "my_selected_font"
        
        MDRaisedButton:
            text: "Click"
            on_release: app.change_lang()
    
'''

from kivy.core.text import LabelBase

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles


class MainApp(MDApp):
    def build(self):
        LabelBase.register(
            name="JetBrainsMono",
            fn_regular="JetBrainsMono-Regular.ttf")

        LabelBase.register(
            name="korea",
            fn_regular="korea.ttf")

        LabelBase.register(
            name="china",
            fn_regular="china.ttf")

        LabelBase.register(
            name="hindi",
            fn_regular="hindi.ttf")

        theme_font_styles.append('JetBrainsMono')
        theme_font_styles.append('korea')
        theme_font_styles.append('china')
        theme_font_styles.append('hindi')

        self.theme_cls.font_styles["my_selected_font"] = [
            "JetBrainsMono",
            16,
            False,
            0.15,
        ]

        

        return Builder.load_string(KV)
    
    def change_lang(self):
        print("clicked")
        self.theme_cls.font_styles["my_selected_font"] = [
            "china",
            16,
            False,
            0.15,
        ]
    
MainApp().run()
```
I have tried to run this code - but it doesn't change already displayed text.

**Comment by podraco** [comment]
Theres a small problem with the approach, because its a normal dic, not an observable property.
first of all, you need to set the memory to use the same memory as the font style, then when you update that external pointer, it will launch an event that will update every other label for example:

you kv should be something like:
```yaml
<CustomLabel>
    font_style: app.common_font_style

CustomLabel:
    [...]
    
CustomLabel:
    [...]
    
CustomLabel:
    [...]

```
then you should do something like
```python
class app(MDApp):
    [app definition]
    common_font_style = StringProperty("korea")
    index_=NumericProperty(0)
    Font_styles_list = ListProperty(["korea", "china", "hindi"])

    def change_lang(self):
        # this should update every label to the format you gave to the theme cls 
        print("clicked")
        self.index_ = self.index_+1
        self.common_font_style = self.Font_styles_list[index_]
    
```
or, you could update directly the theme manager definitions of the font_styles already defined.

Also, this part is no longer required. The theme_cls already updates it. it should be removed from the docs demo.
```
        theme_font_styles.append('JetBrainsMono')
        theme_font_styles.append('korea')
        theme_font_styles.append('china')
        theme_font_styles.append('hindi')
```

**Comment by WISEPLAT** [comment]
> Theres a small problem with the approach, because its a normal dic, not an observable property.
> first of all, you need to set the memory to use the same memory as the font style, then when you update that external pointer, it will launch an event that will update every other label for example:
> 
> you kv should be something like:
> 
> ```yaml
> <CustomLabel>
>     font_style: app.common_font_style
> 
> CustomLabel:
>     [...]
>     
> CustomLabel:
>     [...]
>     
> CustomLabel:
>     [...]
> ```
> 
> then you should do something like
> 
> ```python
> class app(MDApp):
>     [app definition]
>     common_font_style = StringProperty("korea")
>     index_=NumericProperty(0)
>     Font_styles_list = ListProperty(["korea", "china", "hindi"])
> 
>     def change_lang(self):
>         # this should update every label to the format you gave to the theme cls 
>         print("clicked")
>         self.index_ = self.index_+1
>         self.common_font_style = self.Font_styles_list[index_]
>     
> ```
> 
> or, you could update directly the theme manager definitions of the font_styles already defined.
> 
> Also, this part is no longer required. The theme_cls already updates it. it should be removed from the docs demo.
> 
> ```
>         theme_font_styles.append('JetBrainsMono')
>         theme_font_styles.append('korea')
>         theme_font_styles.append('china')
>         theme_font_styles.append('hindi')
> ```

It looks great, but can you help me to get a small piece of working code - that can be run and worked ok - as demo - I will really 
 appreciate it!
link to china.ttf https://disk.yandex.ru/d/8ifOtgBeeyT5Tg
link to korea.ttf https://disk.yandex.ru/d/fSoVxbpcecrVug
and link to hindi ttf https://disk.yandex.ru/d/KHR3qJQr1By4wg

It's very hard to get working example.

**Comment by WISEPLAT** [comment]
```python
from kivy.properties import StringProperty, NumericProperty, ListProperty

KV = '''
<CustomLabel>
    font_style: app.common_font_style
    
Screen:

    BoxLayout:
        orientation: 'vertical'

        CustomLabel:
            text: "JetBrainsMono"    
        CustomLabel:
            text: "English"
        CustomLabel:
            text: "Русский"
        CustomLabel:
            text: "Deutsch"
        CustomLabel:
            text: "Français"
        CustomLabel:
            text: "中文"
        CustomLabel:
            text: "한국어"
        CustomLabel:
            text: "हिन्दी"

        MDRaisedButton:
            text: "Click"
            on_release: app.change_lang()

'''

from kivy.core.text import LabelBase

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles


class MainApp(MDApp):
    common_font_style = StringProperty("korea")
    index_ = NumericProperty(0)
    Font_styles_list = ListProperty(["korea", "china", "hindi"])

    def build(self):
        LabelBase.register(
            name="JetBrainsMono",
            fn_regular="JetBrainsMono-Regular.ttf")

        LabelBase.register(
            name="my_selected_font",
            fn_regular="times-new-roman.ttf")

        LabelBase.register(
            name="times",
            fn_regular="times-new-roman.ttf")

        LabelBase.register(
            name="korea",
            fn_regular="korea.ttf")

        LabelBase.register(
            name="china",
            fn_regular="china.ttf")

        LabelBase.register(
            name="hindi",
            fn_regular="hindi.ttf")

        return Builder.load_string(KV)

    def change_lang(self):
        print("clicked")
        self.index_ = self.index_ + 1
        self.common_font_style = self.Font_styles_list[self.index_]


MainApp().run()
```
This code doesn't work(
I will really appreciate for a small piece of working demo)

**Comment by podraco** [comment]
I would suggest you to take a more careful read to the kivymd docs example.

Remember that you're registering new font files inside the label base, this means that you shall give every path to be able to use them. (in labelbase you're loading a font file).

The steps are simple:
1.- Register the new font to Label Base
2.- Register a new font style in the ThemeCLS or replace one that already exists.
3.- setup the label memory to be able to update the font style if it's needed. 

heres a working example:
```python
from kivy.properties import StringProperty, NumericProperty, ListProperty

KV = '''
<CustomLabel@MDLabel>
    font_style: app.common_font_style

Screen:

    BoxLayout:
        orientation: 'vertical'

        CustomLabel:
            text: self.font_name
        CustomLabel:
            text: "English"
        CustomLabel:
            text: "Русский"
        CustomLabel:
            text: "Deutsch"
        CustomLabel:
            text: "Français"
        CustomLabel:
            text: "中文"
        CustomLabel:
            text: "한국어"
        CustomLabel:
            text: "हिन्दी"

        MDRaisedButton:
            text: "Click"
            on_release: app.change_lang()

'''

from kivy.core.text import LabelBase

from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.font_definitions import theme_font_styles
from pathlib import Path

path=Path(__file__).parent/"fonts"
path=path.resolve()

LabelBase.register(
    name="JetBrainsMono",
    fn_regular=str(path/"JetBrainsMono-Regular.ttf"))

LabelBase.register(
    name="korea",
    fn_regular=str(path/"korea.ttf"))

LabelBase.register(
    name="china",
    fn_regular=str(path/"china.ttf"))

LabelBase.register(
    name="hindi",
    fn_regular=str(path/"hindi.ttf"))

class MainApp(MDApp):
    common_font_style = StringProperty("korea")
    index_ = NumericProperty(0)
    Font_styles_list = ListProperty(["korea", "china", "hindi"])

    def build(self):
        for i in self.Font_styles_list:
            self.theme_cls.font_styles[i]=[
                i,
                16,
                False,
                0.15
            ]
        return Builder.load_string(KV)

    def change_lang(self):
        print("clicked")
        self.index_ = self.index_ + 1
        if self.index_ >= len(self.Font_styles_list) :
            self.index_ = 0
        self.common_font_style = self.Font_styles_list[self.index_]


MainApp().run()

```

**Comment by HeaTTheatR** [comment]
This issue is not related to the KivyMD library. So I close it.

**Comment by WISEPLAT** [comment]
Thanks! This code are working great!!!!

If I have multilingual app - like this one - https://github.com/tito/kivy-gettext-example
How can I apply the font to all elements on the page by click on button?
