### ISSUE TITLE
Demos - binaries (apk)

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#892]
### Demos are not updating.

The demos are not updating in [kivymd/binaries](https://github.com/kivymd/storage/tree/binaries), for somedays.
Please fix it soon! 🙏

**Comment by VICTORVICKIE** [comment]
Yh in new Update Shrine demo is broken

**Comment by HeaTTheatR** [comment]
@Kulothungan16 Yes. This is expected. The entire demo application needs to be corrected according to the new API.

**Comment by kulothunganug** [comment]
I think reverting  [this](https://github.com/kivymd/KivyMD/commit/e80c6dfead1ce8e724082666f878657d4b845623) commit would fix this issue.

**Comment by kulothunganug** [comment]
Closing this as the author removed the demo applications and created new [one](https://github.com/kivymd/KitchenSink)
