### ISSUE TITLE
MDButtons - Doesnt update it's content to the label texture

### ISSUE THREAD

**Issue by podraco** [kivymd/KivyMD#894]
### Description of the Bug

The buttons aren't changing it's size to accommodate to the text size if the text property is updated. its wrapping the text insted.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:

    MDIconButton:
        icon: "language-python"
        pos_hint: {"center_x": .5, "center_y": .5}

    MDFlatButton:
        text: "this is a test :v"
        id: test2
        pos_hint: {"center_x": .3, "center_y": .2}
        on_release:
            self.text = self.text+"1"

    MDRaisedButton:
        text: "this is another test"
        id: test1
        pos_hint: {"center_x": .5, "center_y": .2}
        on_release:
            self.text = self.text+"1"
'''

class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)

Example().run()
```

### Screenshots
![python_REbXfHx7Ar](https://user-images.githubusercontent.com/5509325/109431165-b4e20c80-79ca-11eb-85a7-30257c4db7c9.png)
![python_pPHOM7FnEC](https://user-images.githubusercontent.com/5509325/109431166-b57aa300-79ca-11eb-9148-dee8de81a1b0.png)
![python_1U2x9OvjiA](https://user-images.githubusercontent.com/5509325/109431167-b6133980-79ca-11eb-96c5-edf3b03c14c8.png)
![python_o8ISkczv4p](https://user-images.githubusercontent.com/5509325/109431168-b6133980-79ca-11eb-9757-ce5f0e0c5627.png)
![python_YIGiHgotLJ](https://user-images.githubusercontent.com/5509325/109431169-b6133980-79ca-11eb-827a-1125bf8bc4ee.png)

### Versions

* OS:  Windows, Linux
* Python:  3.7
* Kivy: 2.0
* KivyMD:  Master

**Comment by HeaTTheatR** [comment]
@podraco This has already been fixed in my local repository.

**Comment by podraco** [comment]
Ok, i was looking through the code and came out with another kind of fix XD, I'll wait your pr then :9
