### ISSUE TITLE
MDButtons

### ISSUE THREAD

**Issue by podraco** [kivymd/KivyMD#898]
### Description of the Bug
when a button is defined as disabled, the saturation of the button doesn't match when a button is defined as normal and then disabled.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """

MDBoxLayout:
    spacing: "12dp"

    MDFlatButton:
        text: "Button 2"
        disabled: True

    MDFlatButton:
        text: "Button 2"
        on_release: self.disabled = True

"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
![python_7sHMr9qKZJ](https://user-images.githubusercontent.com/5509325/109939978-340b6500-7c97-11eb-8b13-4c6bf3b23aa5.png)

### Versions

* OS: windows
* Python:  3.8
* Kivy: 2.0
* KivyMD:  master

**Comment by shashi278** [comment]
@HeaTTheatR could you reproduce this error? Looking okay on my side :thinking: 
<img src="https://user-images.githubusercontent.com/37111736/110206221-781e8580-7ea2-11eb-99d0-26493d6ea9d0.png" height=400></img>

**Comment by HeaTTheatR** [comment]
@shashi278 I checked it is a bug.
