### ISSUE TITLE
MDDataTable | [ValueError] TableRecycleGridLayout.orientation is set to an invalid option 'vertical'

### ISSUE THREAD

**Issue by Hnenry** [kivymd/KivyMD#900]
The MDDataTable appears to be setting this value incorrectly. I get this error when accesing the example on the kitchenSink app:

 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 113:
 ...
     111:        height: self.minimum_height
     112:        width: self.minimum_width
 >>  113:        orientation: "vertical"
     114:        multiselect: True
     115:        touch_multiselect: True
 ...
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr'

**Comment by HeaTTheatR** [comment]
@Hnenry Use KivyMD library from master branch.
