### ISSUE TITLE
How to change the font form MDBottomNavigationItem

### ISSUE THREAD

**Issue by dosonwho** [kivymd/KivyMD#904]
### Description of the Bug
I can't change the font form MDBottomNavigationItem or  MDBottomNavigation

Your text
Dear:
I have a question, I don't know how to change font **(text: 'test_測試')**
I use chinease font.
Does anyone know?

Thank you for your reply

### Code and Logs

KV:
        MDBottomNavigation:
            on_kv_post: self.ids.tab_bar.spacing = 15 #設定間距
            panel_color: .2, .2, .2, 1

            MDBottomNavigationItem:

                name: 'screen 2'
                icon: 'language-cpp'
                text: 'test_測試'

### Versions

* OS: win10
* Python: 3.8
* Kivy: 2.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@dosonwho The API of the MDBottomNavigation class does not provide this capability ...

**Comment by dosonwho** [comment]
Thanks for your reply
