### ISSUE TITLE
Buildozer spec file

### ISSUE THREAD

**Issue by sina76n** [kivymd/KivyMD#91]
Hi. I've built my project but i can't actually add kivymd to buildozer requirements . I did what you said in documents and app is installed successfully but not run. can you please put the spec file example for kitchen_sink?

**Comment by ArtemSBulgakov** [comment]
See `buildozer logcat` for log
https://buildozer.readthedocs.io/en/latest/quickstart.html#run-my-application

**Comment by HeaTTheatR** [comment]
@sina76n 
![Снимок экрана 2019-08-18 в 16 37 07](https://user-images.githubusercontent.com/16930280/63225292-ce4fa900-c1d6-11e9-981c-b6a88825daa4.png)
![Снимок экрана 2019-08-18 в 16 39 13](https://user-images.githubusercontent.com/16930280/63225293-cee83f80-c1d6-11e9-9346-fe32a9268adb.png)
