### ISSUE TITLE
Android app is crashing when I am using file manager in it

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#910]
I am using kivymd latest version in my desktop and android app both and here I am using kivymd's file manager feature in my desktop and android app both so it is working fine for my desktop app but when I am using it in android then it crashes and giving me below error
![image](https://user-images.githubusercontent.com/33522186/110850534-cb7c4380-82a7-11eb-95f7-85a5bfcfb029.png)

so here is the case like when I open file storage of my android device
![Screenshot_20210312-015655](https://user-images.githubusercontent.com/33522186/110850913-3ded2380-82a8-11eb-9636-5c9b76fccfaf.png)
and click on the left side back icon then it crashes and give me above given issue so please fix it so the user can easily use it in 
android interface.
I have tried to fix it on my fork repo and it handles the issue so here is the link please fix the issue as soon as possible.
https://github.com/navjotcis/KivyMD/commit/cfd60abb85093ff6f827c80917462a84876b792a

**Comment by HeaTTheatR** [comment]
@navjotcis I see that you are not using the master branch.
