### ISSUE TITLE
App crash when datepicker open in my app on android device

### ISSUE THREAD

**Issue by jbc0708** [kivymd/KivyMD#913]
[Enviroment]
OS: Ubuntu 20.04 (64bit)
Python: 3.8.5
Kivy: 2.0.0
KivyMD: 0.104.2.dev0

[Issue]
datepicker example code in kivymd readdocs to my "main.py" file
and run app on my desktop successly.
so i convert main.py to android apk 
and install it to Galaxy Note 8 and execute app
it show toolbar,  MDButton.
when MDbutton click, it must show Datepicker widget like when shown on PC
but.. do not shown datepicker widget. just app crash..
how to i solved this problem?

**Comment by HeaTTheatR** [comment]
@jbc0708 To solve any problem, you need to look at the error log.

**Comment by jbc0708** [comment]
> @jbc0708 To solve any problem, you need to look at the error log.
ye.. i install adb and open terminal
typing command >  buildozer android debug deploy run logcat
and when i clicked button
terminal log show me this result
[result]
03-14 15:07:22.193  1320  1414 I python  : [INFO   ] [Base        ] Leaving application in progress...
03-14 15:07:22.193  1320  1414 I python  :  Traceback (most recent call last):
03-14 15:07:22.194  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/app/main.py", line 50, in <module>
03-14 15:07:22.195  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/app.py", line 855, in run
03-14 15:07:22.196  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/base.py", line 504, in runTouchApp
03-14 15:07:22.197  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/core/window/window_sdl2.py", line 747, in mainloop
03-14 15:07:22.198  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/core/window/window_sdl2.py", line 479, in _mainloop
03-14 15:07:22.199  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/base.py", line 342, in idle
03-14 15:07:22.199  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/base.py", line 327, in dispatch_input
03-14 15:07:22.200  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/base.py", line 293, in post_dispatch_input
03-14 15:07:22.201  1320  1414 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
03-14 15:07:22.202  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivymd/uix/behaviors/ripplebehavior.py", line 245, in on_touch_up
03-14 15:07:22.203  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivymd/uix/button.py", line 1083, in on_touch_up
03-14 15:07:22.204  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivymd/uix/button.py", line 969, in on_touch_up
03-14 15:07:22.205  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/uix/behaviors/button.py", line 179, in on_touch_up
03-14 15:07:22.206  1320  1414 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
03-14 15:07:22.206  1320  1414 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
03-14 15:07:22.207  1320  1414 I python  :    File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
03-14 15:07:22.208  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/date/kivy/lang/builder.py", line 64, in custom_callback
03-14 15:07:22.209  1320  1414 I python  :    File "<string>", line 12, in <module>
03-14 15:07:22.210  1320  1414 I python  :    File "/home/dukeout2/Project/Unse/.buildozer/android/app/main.py", line 45, in show_date_picker
03-14 15:07:22.211  1320  1414 I python  :  TypeError: __init__() missing 1 required positional argument: 'callback'
03-14 15:07:22.211  1320  1414 I python  : Python for android ended.

in my code:
def show_date_picker(self):
        date_dialog = MDDatePicker() <<  this is wrong code i guess..but.. it not happen app crash whe run app in DeskTop..
        date_dialog.bind(on_save=self.on_save, on_cancel=self.on_cancel)
        date_dialog.open()

**Comment by HeaTTheatR** [comment]
@jbc0708 Make sure that the build of the APK uses the master branch of the library and the code uses the API of the latest version of the library.

**Comment by jbc0708** [comment]
> @jbc0708 Make sure that the build of the APK uses the master branch of the library and the code uses the API of the latest version of the library.

i install kivymd version 0.104.2.dev0. Because i want to select year value..
before kivymd version(0.104.1) can't that..i wanted..
in buldozer.spec, requiremts = python3, kivy, kivymd==0.104.2.dev0  <<  it happen error when converting apk
so i type "requiremts = python3, kivy, kivymd" it used to kivymd(ver=0.104.1) in converting
it's really hard to use datepicker new version..

**Comment by HeaTTheatR** [comment]
@jbc0708 https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec#L29

**Comment by jbc0708** [comment]
> @jbc0708 https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec#L29

Finally i Solved.. Thank a lot
but it is still smal problem ..

when datepicker  opened.. 
1.not show arrow icon that change year value 
2. not show 2 arrow icon that change month value
3. not show pancil icon that change calendar widget to input widget or input widget to calendar widget

![Screenshot_20210314-164303_Date.jpg](https://user-images.githubusercontent.com/22402895/111061026-7e38e580-84e4-11eb-9ca9-3251b63cb00c.jpg)

i really great thanks to help me

**Comment by HeaTTheatR** [comment]
@jbc0708 
Remove `.buildozer` directory from your project and run built again.

**Comment by jbc0708** [comment]
> @jbc0708
> Remove `.buildozer` directory from your project and run built again.
ye.. i did it and I type buildozer android clean too..
but still have little problem..
however i great thank your help 
and I will close this issue
