### ISSUE TITLE
MDIcons are not visible in app

### ISSUE THREAD

**Issue by DAMIAN-Adol** [kivymd/KivyMD#918]
**Software Versions**
* Python: 3.8.5
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0 master

**Describe the bug**
I packed the app in an apk file, but after launching it I can't see the icons.

My **kivymd** folder was attached only to the main.py folder, but not as:
`requirements = https: //github.com/kivymd/KivyMD/archive/master.zip`

What am I doing wrong?

**Screenshots**
* **Desktop** / **Device**
![image](https://user-images.githubusercontent.com/57909540/111357441-51590f80-8657-11eb-9463-b2838ea21693.png)

**Comment by HeaTTheatR** [comment]
@DAMIAN-Adol https://github.com/kivymd/KivyMD/issues/257

**Comment by podraco** [comment]
Change your spec file requirements list to have all the following dependencies.

`requirements = kivy==2.0.0, kivymd==[the version you want to use], sdl2_ttf == 2.0.15`

#922

**Comment by tsmorton60** [comment]
I have the same issue of no icons with the development version of KivyMD. With the current stable version the icons show. I have repeatedly run,
buildozer android clean
and then
buildozer android debug

Here are my requirements,
requirements = python3, pillow, kivy==2.0.0, https://github.com/kivymd/KivyMD/archive/master.zip, sdl2_ttf == 2.0.15
Is this an issue with the development version?

**Comment by eriol** [comment]
@tsmorton60 it's working for me using:
```
requirements = python3==3.8.1,kivy==2.0.0,https://github.com/kivymd/KivyMD/archive/8f83652.zip,sdl2_ttf==2.0.15,toml==0.10.2,xdg==5.0.2,pillow==8.2.0
```
ignore `toml` and `xdg` dependencies, I need them in this specific project. 

Also we both are using `master` (since it changed on April): I always fix all the dependencies' version to not have surprises. Maybe there are some hints in the building logs?

**Comment by tsmorton60** [comment]
@eriol 
I changed my requirements file to match yours (where applicable), updated Ubuntu (20.04), did another buildozer android clean, and ran buildozer android debug. Still not one MDIcon shows. The build log says nothing remarkable I can find. It does say that sdl2 is included. Below are that last lines saying it was successful. I don't know where to look. 

[DEBUG]:   	
[DEBUG]:   	BUILD SUCCESSFUL in 3s
[DEBUG]:   	27 actionable tasks: 27 executed

[INFO]:    <- directory context /home/morton/Desktop/kivy-app/.buildozer/android/platform/python-for-android
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	dailybible: min API 21, includes recipes (freetype, hostpython3, jpeg, libffi, openssl, png, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, pillow, six, pyjnius, android, kivy, https://github.com/kivymd/kivymd/archive/master.zip, certifi), built for archs (armeabi-v7a)
[INFO]:    dailybible has compatible recipes, using this one
[INFO]:    # Copying android package to current directory
[INFO]:    # Android package filename not found in build output. Guessing...
[INFO]:    # Found android package file: /home/morton/Desktop/kivy-app/.buildozer/android/platform/build-armeabi-v7a/dists/dailybible__armeabi-v7a/build/outputs/apk/debug/dailybible__armeabi-v7a-debug.apk
[INFO]:    # Add version number to android package
[INFO]:    # Android package renamed to dailybible__armeabi-v7a-debug-0.6.8-.apk
[DEBUG]:   -> running cp /home/morton/Desktop/kivy-app/.buildozer/android/platform/build-armeabi-v7a/dists/dailybible__armeabi-v7a/build/outputs/apk/debug/dailybible__armeabi-v7a-debug.apk dailybible__armeabi-v7a-debug-0.6.8-.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Android packaging done!
# APK dailybible-0.6.8-armeabi-v7a-debug.apk available in the bin directory
morton@morton-VirtualBox:~/Desktop/kivy-app$

**Comment by eriol** [comment]
@tsmorton60 it seems all right. I published the project I was working on, it uses poetry so you can look at the exact versions I'm using: https://github.com/eriol/kioku

I hope this can help. I'm using Debian Bullseye (the almost new stable version of Debian). You may want to try to build my project and see if the icons show up. I don't remember if something is logged at runtime when icons are not found...
I can tell you that the only thing I did to have the icons on android was to add `sdl2_ttf==2.0.15` into `buildozer.spec`, clean and rebuild the app.
I don't remember now if I used both `buildozer android clean` and `buildozer clean`, but maybe yes.
