### ISSUE TITLE
MDButtons - question

### ISSUE THREAD

**Issue by geomancom** [kivymd/KivyMD#92]
how can i change the standard image in your button

**Comment by HeaTTheatR** [comment]
What image???

**Comment by geomancom** [comment]
the standard image that you depicted (android / python).

In the button settings, there is only the identifier of your pictures.

I want to upload my pictures

**Comment by HeaTTheatR** [comment]
I do not understand what you mean.

**Comment by geomancom** [comment]
![g837](https://user-images.githubusercontent.com/54456534/63626550-0b73cb00-c61d-11e9-8aa6-3a3f9f3cdd24.png)

**Comment by HeaTTheatR** [comment]
It's impossible. Is no such functionality.
