### ISSUE TITLE
default_tab not working - MDTabs

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#927]
### Description of the Bug

When using `default_tab` it doesn't work!

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.floatlayout import MDFloatLayout

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
        default_tab: 2

<Tab>

    MDLabel:
        text: root.text
        halign: 'center'
'''


class Tab(MDFloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.tabs.add_widget(Tab(text="One"))
        self.root.ids.tabs.add_widget(Tab(text="Two"))


Example().run()
```

### Versions

* OS: Zorin OS Lite 15
* Python: 3.6.9
* Kivy: 2.0.0
* KivyMD: master

**Comment by HeaTTheatR** [comment]
@Kulothungan16 
There is no implementation for this in the `tab.py` module...

![Снимок экрана 2021-03-21 в 17 17 55](https://user-images.githubusercontent.com/16930280/111908287-b357b180-8a69-11eb-9a5c-421762790c0c.png)

**Comment by HeaTTheatR** [comment]
@Kulothungan16 This parameter was not used at all and was removed in the master version of the library. To set the desired tab use the [switch_tab](https://kivymd.readthedocs.io/en/latest/components/tabs/#kivymd.uix.tab.tab.MDTabs.switch_tab) parameter.
