### ISSUE TITLE
MDTabs - not covering full width of the window

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#928]
### Description of the Bug

When using `MDTabs` it doesn't cover the full width of the window!

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.floatlayout import MDFloatLayout

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs

<Tab>

    MDLabel:
        text: root.text
        halign: 'center'
'''


class Tab(MDFloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.tabs.add_widget(Tab(text="One"))
        self.root.ids.tabs.add_widget(Tab(text="Two"))


Example().run()
```

you can also refer KitchenSinkDemo for this issue.

### Screenshot
![Screenshot 2021-03-21 19:38:55](https://user-images.githubusercontent.com/63696279/111907875-1e5eb380-8a7d-11eb-8efb-a914e9b1e50c.png)

### Versions

* OS: Zorin OS Lite 15
* Python: 3.6.9
* Kivy: 2.0.0
* KivyMD: master

**Comment by HeaTTheatR** [comment]
@Kulothungan16 I don't see any problem in the screenshot...

**Comment by kulothunganug** [comment]
![image](https://user-images.githubusercontent.com/63696279/111908724-456ab480-8a80-11eb-9f64-1f89bc546f45.png)

U can see that the two Tabs are fills the width of the screen (old kivymd)

**Comment by HeaTTheatR** [comment]
@Kulothungan16 And? What is the essence of your question?

**Comment by kulothunganug** [comment]
In most of the frameworks (old kivymd also) the tabs fills the width of the screen and it looks gud.
The one which is not filling the width of the screen will not be user friendly.

**Comment by HeaTTheatR** [comment]
@Kulothungan16 
```
    MDTabs:
        tab_hint_x: True
```
