### ISSUE TITLE
MDTextFieldRect animation enters strange states

### ISSUE THREAD

**Issue by lwwilker** [kivymd/KivyMD#929]
### Description of the Bug

I was using the MDTextFieldRect object in an application, and I was able to make the animation enter some states that don't look like they're supposed to happen.  In one instance I'm able to get two text fields in the same layout to have their highlight animation active at the same time and in another it looks like the animation remains active on the text field's parent layout.  I've attached some images.

To reproduce the issues just quickly click between the two text fields.  This reproduces all of the issues presented in the screenshots below.  An example is shown in the following video:
https://user-images.githubusercontent.com/47584126/111920348-6c16f400-8a5c-11eb-900f-5529a5ced8ec.mp4

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.button import MDRaisedButton


kv="""
FloatLayout:
	GridLayout:
		rows: 3
		cols: 1
		spacing: 5
		pos: self.parent.width - self.width - 10, 10
		size_hint: 0.22, 0.17
		size_hint_max_x: 200
		size_hint_max_y: 100

		MDTextFieldRect:
			id: username
			hint_text: 'Username'
			font_size: self.height * 0.468
			multiline: False
			write_tab: False
			size_hint: 1, 0.2
			normal_color: 1,1,1,0.85
			color_active: 1,1,1,1

		MDTextFieldRect:
			id: password
			hint_text: 'Password'
			font_size: self.height * 0.468
			password: True
			multiline: False
			write_tab: False
			size_hint: 1, 0.2
			normal_color: 1,1,1,0.85
			color_active: 1,1,1,1

		MDRaisedButton:
			text: "Login"
			font_size: self.height * 0.468
			size_hint: 1, 0.2
"""


class BugDemo(MDApp):

	def build(self):
		self.root = Builder.load_string(kv)


if __name__ == "__main__":
	BugDemo().run()

```

### Screenshots

![image](https://user-images.githubusercontent.com/47584126/111919607-d037b900-8a58-11eb-88cc-3d9638524cf2.png)
![image](https://user-images.githubusercontent.com/47584126/111919614-d9288a80-8a58-11eb-9cd4-0a62d008b6fb.png)
![image](https://user-images.githubusercontent.com/47584126/111919620-e5ace300-8a58-11eb-8596-01b8fb2066a7.png)

### Versions

* OS: Windows 10 (19042.868)
* Python: 3.7.9
* Kivyy:  2.0.0
* KivyMD: 0.104.1 (also happens on the master as of 3-21-21)

**Comment by HeaTTheatR** [comment]
The problem description does not show how to reproduce the behavior that the author describes.

**Comment by lwwilker** [comment]
I've updated the description

**Comment by HeaTTheatR** [comment]
@lwwilker Thanks, I will check this behavior later.

**Comment by sollarp** [comment]
I can't reproduce this behaviour by the given code. I suspect it is related to the OP system or Python version.
Works on:
kivymd:  0.104.2
Kivy:  2.0.0
Python 3.8.10
Ubuntu 20.04

https://user-images.githubusercontent.com/74240451/135612971-d6730287-21d7-4982-92b8-2ffed16d6025.mp4

**Comment by phifuh** [comment]
![image](https://user-images.githubusercontent.com/98083435/157903357-b254f60a-cc72-4e38-b512-fef3cd75f65f.png)

I noticed the same behaviour . If you click to fast from input to input, the line animation stops in the animation. 
Py 3.9
kivy 2.1
kivymd 1.0.0

if you focus a bugged element it re-plays the animation and is normal again

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
