### ISSUE TITLE
MDFloatingActionButtonSpeedDial button labels remain after double clicking the speed dial after it has been expanded

### ISSUE THREAD

**Issue by lwwilker** [kivymd/KivyMD#932]
### Description of the Bug

I was developing an application using the MDFloatingActionButtonSpeedDial, and I encountered a state of the widget where the labels for each button in the speed dial do not disappear when the speed dial is closed.  It occurs when the speed dial is expanded and then double-clicked.

To reproduce the issue, click the speed dial once, and then rapidly double click it:
https://user-images.githubusercontent.com/47584126/112215561-e0859a80-8bf6-11eb-933a-8306b5c5245f.mp4

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp


kv="""
FloatLayout:
	MDFloatingActionButtonSpeedDial:
		data: {"play": "Start", "stop": "Stop", "restart": "Restart", "power": "Shutdown"}
		root_button_anim: True
"""


class BugDemo(MDApp):

	def build(self):
		self.root = Builder.load_string(kv)


if __name__ == "__main__":
	BugDemo().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/47584126/112214462-9a7c0700-8bf5-11eb-98be-0ce39365977b.png)

### Versions

* OS: Windows 10 (19042.868)
* Python: 3.7.9
* Kivyy:  2.0.0
* KivyMD: 0.104.1 (also happens on the master as of 3-23-21)

**Comment by HeaTTheatR** [comment]
@lwwilker 
```
    data = {
        'name': 'icon',
        ...
    }
```

**Comment by HeaTTheatR** [comment]
@lwwilker 
```    data = {
        'name': 'icon',
        ...
    }```

**Comment by lwwilker** [comment]
Nothing in your response changed?...

**Comment by HeaTTheatR** [comment]
@lwwilker Be attentive and do not need to ask again...

**Comment by lwwilker** [comment]
I'm not following you.  Can you be more descriptive if the problem is something I'm doing wrong?

**Comment by HeaTTheatR** [comment]
@lwwilker 
```
data = {
        'name': 'icon',
        ...
    }
```

**Comment by lwwilker** [comment]
I've defined the 'data' attribute of the MDFloatingActionButtonSpeedDial class in the sample code I've provided.  What am I missing?  That's all I'm taking away from what you keep reposting...

**Comment by HeaTTheatR** [comment]
@lwwilker https://discord.com/channels/566880874789076992/618108815774056488/816265169880875018

**Comment by lwwilker** [comment]
Okay?

**Comment by lwwilker** [comment]
Why are issue comments being obliterated?

**Comment by HeaTTheatR** [comment]
@lwwilker So that people can quickly find an answer.

**Comment by HeaTTheatR** [comment]
@lwwilker And stop spamming! You have been given an exhaustive answer.
