### ISSUE TITLE
Rectangle Mode of MdTextField is behaving weirdly...

### ISSUE THREAD

**Issue by Prince2347X** [kivymd/KivyMD#933]
### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.textfield import MDTextField
from kivy.uix.screenmanager import Screen

class MyApp(MDApp):
    def build(self):
        self.theme_cls.primary_palette = "Purple"
        screen = Screen()
        text_field = MDTextField(hint_text="Code", mode="rectangle", pos_hint={"center_x": 0.4 + 0.1, "center_y": 0.9 - 0.4}, size_hint_x=0.1+0.4) #ignore the calculation in pos and size hint.. it's bcoz the key 'five' of my pc doesn't work
        screen.add_widget(text_field)
        return screen
    def on_start(self):
        self.fps_monitor_start()

if __name__ == '__main__':
    MyApp().run()
```

### Screenshots
This is the outcome....
![image](https://user-images.githubusercontent.com/68418241/112304549-a0d8b480-8cc3-11eb-93f0-fa97a88404b2.png)

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Prince2347X 
We do not support KivyMD 0.104.1. Use the master version of the KivyMD library:


https://user-images.githubusercontent.com/16930280/112306582-03748500-8cb1-11eb-91a3-abe247a9f528.mov
