### ISSUE TITLE
Changing theme_cls  to 'Dark' doesn't update the background color of MDDialog  

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#938]
Hello there, 
I've been working on an application which has to do with pdf's. Keeping that aside I have added a `MDSwitch` to change between Light and Dark theme style.
**KV** :
```
OneLineAvatarIconListItem:
	text: 'Dark theme'
	on_size:
		self.ids._right_container.width = lst_right_body.width
		self.ids._right_container.x = lst_right_body.width

	IconLeftWidget:
		icon: 'invert-colors'

	ListContainer:
		id: lst_right_body

		MDSwitch:
			id: dark_mode
			on_release: app.change_theme()

```
where the `ListContainer` is inheriting these
**PY** :
```
class ListContainer(IRightBodyTouch, MDBoxLayout):
    adaptive_width = True

``` 
**Preview** :
![PDFine 27-03-2021 17_29_37](https://user-images.githubusercontent.com/81470759/112720308-7f760380-8f23-11eb-8000-46ae7766eee1.png)

 But when the mode is changed to `'Dark'`  with the following function it doesn't change the background color of the `MDDialog` box

**KV (dark_mode callback)**

```
def change_theme(self):
  if self.root.ids.dark_mode.active:
      self.theme_cls.theme_style = "Dark"
      self.settings_config('theme_style', 'Dark') # this line changes the json file (config) to keep track of the preference later
  else:
      self.theme_cls.theme_style = "Light"
      self.settings_config('theme_style', 'Light')
```

In `'Light'` :

![PDFine 27-03-2021 17_29_25](https://user-images.githubusercontent.com/81470759/112720421-3a9e9c80-8f24-11eb-8f4f-ba18f32fe944.png)

In `'Dark'` :

![PDFine 27-03-2021 17_29_47](https://user-images.githubusercontent.com/81470759/112720436-48542200-8f24-11eb-8228-5020d5861196.png)

I even tried to print that `MDDialog` box's theme style when the `change_theme()` is called by
`
print(self.watermark_options_win.theme_cls.theme_style) # self.watermark_options_win is the instance of MDDialog
`
and get `'Dark'` printed

 If there is something wrong in my code or approach please forgive me for taking your time but if it is a real bug I will be pleased to help!

**Comment by HeaTTheatR** [comment]
@devMula 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.list import IRightBodyTouch

KV = '''
MDScreen:

    MyContainer:

    MDSwitch:
        on_active: app.theme_cls.theme_style = "Dark"
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class MyContainer(IRightBodyTouch, MDBoxLayout):
    pass


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```
![ezgif-3-c99967216b54](https://user-images.githubusercontent.com/16930280/112721524-4b93e180-8f15-11eb-9239-b927b0bcba2f.gif)

**Comment by ghost** [comment]
Thanks for you answer @HeaTTheatR but my question was related to `MDDialog` box, the theme style for the app changes pretty much as it should but, as you can see here the `MDDialog` box's background isn't changed :

https://user-images.githubusercontent.com/81470759/112726887-ac3b1280-8f45-11eb-9a76-db1fd66e7dac.mp4
