### ISSUE TITLE
3Button(Choose Year, Previous Month, Next Month) in DatePcker are not visible after Android Converting

### ISSUE THREAD

**Issue by jbc0708** [kivymd/KivyMD#947]
### Screenshots

Add images to explain us this bug. Paste urls here.
in Ubuntu 20.04
https://github.com/jbc0708/pyupbitReal/blob/master/1.png

in Android ( Android 9, Galaxy Note8)
https://github.com/jbc0708/pyupbitReal/blob/master/2.jpg
https://groups.google.com/group/kivy-users/attach/1cbd9451d997c/2.jpg?part=0.1&view=1

I know the buttons are still there.
But new users won't know how to choose the year and month.

Can i change 3 buttons's background Color?
or Could you please tell me the name of the 3 button variable?

### Versions

* OS: Ubuntu 20.04
* Python:  3.8.5
* Kivy: 2.0.0
* KivyMD:  0.104.2.dev0

**Comment by HeaTTheatR** [comment]
Version 0.104.2 is not supported.
