### ISSUE TITLE
MDCheckbox is activated when removing an item from the RecycleView

### ISSUE THREAD

**Issue by WhileForIf** [kivymd/KivyMD#953]
### Description of the Bug

I am using a list of dict, each item has an "act" key which can be True or False and determines the status of the MDCheckbox. I am trying to create a function that allows me to move an item in the list to the last place when the MDCheckbox is pressed and the value of act from False becomes True, and vice versa, if act becomes False then it becomes the first in the list. I have no problem activating the MDCheckboxes in the first half of the list, but when I press the ones below the middle of the list, the MDCheckboxes in the first half of the list are activated as if they were connected in some way (ATTENTION: they are only visually activated, in fact when printing the value of act it is always False). I leave a video with the demonstration and the function I am using. Before I used a function that acted directly on the main list but seeing the bug I tried to act on a copy of the list and then add all the elements but without results.

PS: I'm using RecycleView(scroll)

### This is the item class in kv

kv = """

```
<ListItemWithCheckbox>:
    on_press: app.root.scree.list_callback(root)

    IconLeftWidget:
        icon:root.icon

    RightCheckbox:
        active: root.act
        on_press: app.root.scree.last(root)

```
   """
### Item class in python 
```

class ListItemWithCheckbox(OneLineAvatarIconListItem):
    icon= StringProperty("")
    act = BooleanProperty(False)
    idlist=StringProperty("")
```

### The function called by 'on_press' in the MDCheckbox

  ```
def last(self,caller):
          attivo=False
          listaparallela=[]
          k=0
          for item in self.ids.scroll.data:
              if ("idlist", caller.idlist) in item.items():
                  if caller.act==True:
                      attivo=False
                  else:
                      attivo=True
              else:
                  listaparallela.append(item)
                  print(item)
          
          if attivo==True:
              listaparallela.append(
                  {
                          "viewclass":"ListItemWithCheckbox",
                          "text": caller.text, 
                          "icon": "table-chair", 
                          "idlist": caller.idlist,
                          "act" : True
                      })
          else:
              listaparallela.insert(0,{
                      "viewclass":"ListItemWithCheckbox",
                      "text": caller.text, 
                      "icon": "table-chair", 
                      "idlist": caller.idlist,
                      "act" : False
                  })
          for i in range(0,len(self.ids.scroll.data)):
              del self.ids.scroll.data[i-k]
              k+=1
          
          for item in listaparallela:
              self.ids.scroll.data.append(item)

```

### Video of the bug
 https://drive.google.com/file/d/17_P4srPQP2TouNolyfikoEFlAvf4fJnh/view?usp=sharing

```

**Comment by HeaTTheatR** [comment]
@WhileForIf Your question has nothing to do with the KivyMD library. Read the documentation for the RecycleView class.
