### ISSUE TITLE
MDFloatingActionButtonSpeedDial data = {'nam': 'icon'} KeyError: icon when hint_animation=True

### ISSUE THREAD

**Issue by hmae** [kivymd/KivyMD#954]
### Description of the Bug
when use MDFloatingActionButtonSpeedDial with hint_animation=True
clicking on Button to open items then when ever moving mouse .. error appear .
Error at [ kivymd\uix\button.py", line 1819 ]
  if self.data[instance.icon] == widget.text:
  KeyError: 'language-python'

it works fine for standard ver 0.104.1
i updated to latest ver to use new items like Live Editing Preview and some new widgets. 
thank you for hard work. i hope if i could help one day .. but still exploring the code .
### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """

MDFloatingActionButtonSpeedDial:
    data: app.data
    hint_animation: True
    callback: lambda x: print(x.icon)
"""

class Test(MDApp):
    data = {'python icon!':'language-python'}
    def build(self):
        root = Builder.load_string(kv)
        return root

Test().run()

```

### Screenshots
![Screenshot 2021-04-10 221204](https://user-images.githubusercontent.com/20520471/114283471-39a05b80-9a4a-11eb-98a9-f9fa946456fb.png)

### Versions

* OS: Windows 10 
* Python:  [INFO   ] [Python      ] v3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
* Kivy:  [INFO   ] [Kivy        ] v2.0.0
* KivyMD:  [INFO   ] [KivyMD      ] 0.104.2.dev0,

**Comment by VICTORVICKIE** [comment]
I have solved this issue in my local repository I'll PR soon @HeaTTheatR @hmae

**Comment by hmae** [comment]
it is solved after updating kivymd/uix/button.py file by this one >> 
https://github.com/VICTORVICKIE/KivyMD/blob/286522247bfc081363a442acb66d7850b8da8dd8/kivymd/uix/button.py


# just in case . 
Children Labels keep listening to Events even while closing stack [ `MDFloatingActionButtonSpeedDial.close_stack(self)` ]
if you can just click multiple times over the main button . Label Animation will start .
this will lead to keep animation working after closing the Stack 
![SpeedDialButton2](https://user-images.githubusercontent.com/20520471/114305149-415a1180-9ad7-11eb-835a-8d6b1acdf1a6.gif)

### was tested on Android >>
APK build by buildozer on ubuntu os.
python 3.8
original Kivymd ver 0.104.1
android 10
![drawable2](https://user-images.githubusercontent.com/20520471/114306983-027b8a00-9ade-11eb-8c45-beb6de359f22.png)

**Comment by VICTORVICKIE** [comment]
That is because the label button is actually behind the main button but with opacity 0 so these weird behaviour are expected, it would be great if you can fix this

**Comment by hmae** [comment]
> That is because the label button is actually behind the main button but with opacity 0 so these weird behaviour are expected, it would be great if you can fix this
### Solution for  weird behaviour when click the button multiple times
by just Cancel all previous animations of all widgets when execute `.open_stack`
added the following elif Statement
```python
def open_stack(self, instance):
        """Opens a button stack."""

        for widget in self.children:
            if isinstance(widget, MDFloatingLabel):
                Animation.cancel_all(widget)
            elif isinstance(widget, MDFloatingBottomButton):
                Animation.cancel_all(widget)
```
I am glad for your support to overcome this animation problem .

![Screenshot 2021-04-11 210937](https://user-images.githubusercontent.com/20520471/114318132-e4c51980-9b0b-11eb-8034-0207133b679b.png)


Shall this issue should be closed ?  @HeaTTheatR @VICTORVICKIE
