### ISSUE TITLE
 instead of maintaining as load_string I am maintaining its as .kv file seperately. In that case im calling builder method in my new screen .py file.?

### ISSUE THREAD

**Issue by kirthigakalyan** [kivymd/KivyMD#957]
@HeaTTheatR But instead of maintaining as load_string I am maintaining its as .kv file seperately. In that case im calling builder method in my new screen .py file.?

MyKv.kv:

<Create@MDBoxLayout>:
    id: crt_odr
    MDLabel:
        text: "Type"
        halign: "left"
    MDDropDownItem:
        id: menu_itms
        pos_hint:{'center_x':0.5, 'center_y':0.5}
        text: 'Select any one'
        on_release: app.menu_list.open()

MyKv.py:
Builder.load_file("MyKv.kv")

class MyKv(Screen):
      
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

      list_items = ["A", "B", "C"]
        menu_list =[{"text": drop_itm,
                     "viewclass": "OneLineListItem",
                     "on_release": lambda x=drop_itm: self.menu_callback(x)
                    } for drop_itm in list_items
                   ]
        self.menu_list = MDDropdownMenu(caller=self.ids.menu_itms,items=menu_list, position='center', width_mult=4)

    def menu_callback(self, itm):
        self.ids.menu_itms.set_item(itm)
        self.ids.menu_itms.dismiss()

Its showing same error : AttributeError: 'super' object has no attribute '__getattr__'

Please help.

_Originally posted by @kirthigakalyan in https://github.com/kivymd/KivyMD/issues/511#issuecomment-817515829_

**Comment by podraco** [comment]
hello, is this a bug report or a support request?

**Comment by Jemeni11** [comment]
I don't think the problem has anything to do with the builder method but I do not fully understand your problem. Maybe you should attach a screenshot instead?

**Comment by kirthigakalyan** [comment]
@podraco Its a query about builder methods in Kivy MD. Usually people are having a builder string to load the KV file. My query is why cant we use a separate KV file and create clasess for those in py file.

**Comment by Mayank-9018** [comment]
Read this : https://kivy.org/doc/stable/guide/lang.html.
You can create a separate .kv file and create classes for it in .py files.

**Comment by HeaTTheatR** [comment]
The problem is not related to the KivyMD library.
