### ISSUE TITLE
Snackbar.open() doesn't exists instead Snackbar.show() works fine

### ISSUE THREAD

**Issue by dibakarbose** [kivymd/KivyMD#958]
Documentation code in the following link has Snackbar.open() in the code, instead Snackbar.show() works.
(https://kivymd.readthedocs.io/en/latest/components/snackbar/)

Is the documentation not updated with the latest code ?

**Comment by HeaTTheatR** [comment]
@dibakarbose The `Snackbar` class does not have a `show` method.

**Comment by dibakarbose** [comment]
@HeaTTheatR Could you please tell me then how the code is working with .show(). I am attaching a screenshot below as well which will show Kivy and KivyMD version as well. Maybe I am missing something here with which you can help me out.

![image](https://user-images.githubusercontent.com/16408964/114578873-f1c44300-9c9a-11eb-862f-6c8a0b70d67c.png)

**Comment by HeaTTheatR** [comment]
@dibakarbose Use KivyMD library from master branch.

**Comment by dibakarbose** [comment]
Oh... I see.. I installed from PyPi actually.

Thanks for informing.. Will do that 👍
