### ISSUE TITLE
Facing issue with MDCardSwipe 

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#960]
Hello guys I have been using kivymd from last one year and I have seen day by day change in kivymd and I know you peoples are working very hard to implement more and more features in kivymd so I appreciate it and as I have been facing  some issues with swip delete feature so I am attaching demo file which will show you the issue what I am facing so here in the below given picture
![image](https://user-images.githubusercontent.com/33522186/114709297-ec5b0d00-9d1b-11eb-978c-ef2744a3637a.png)

when I am trying to swipe the screen from left to right it should only perform swipe operation but it is opening new screen but I am not able to prevent it because I want to display second screen on the press of any row so in simple I want the behaviour like when some one swipe the screen it should not perform press operation and when we will not swipe then we can perform click operation.
[sample_code.zip](https://github.com/kivymd/KivyMD/files/6310767/sample_code.zip)

**Comment by VICTORVICKIE** [comment]
For this you need to override the behaviour to see if they touch is moved and do accordingly i think

**Comment by navjotcis** [comment]
There is no function available to check the behavior and I have tried to customise it but it did not work

**Comment by VICTORVICKIE** [comment]
on_touch_down,on_touch_up,on_touch_move
They are available for all widgets and you need to find them on the parent classes i.e kivy

**Comment by navjotcis** [comment]
on_touch_down,on_touch_up,on_touch_move
all three of them are behaving same whenever I am trying to swipe it opens the new screen. it is not swiping row. I have attached the sample program above you can check that.

**Comment by navjotcis** [comment]
here this is the android apk which you can also check 

[Uploading apk.zip…]()

**Comment by hmae** [comment]
after reading the topic and testing your code .. 
i got this , changing or adding behaviors is pretty simple .. 
set variable -> `duration_long_touch` will help to give you time if you want to just press or swipe ..
what i did . giving me 2 choice .. 
1- if my touch is Too long .. it will change to sc 2
2- if not long ,, it just swipe ..
you can find docs here https://kivymd.readthedocs.io/en/0.104.1/behaviors/touch/
# Edited .. :
![image](https://user-images.githubusercontent.com/20520471/114775381-86997000-9d71-11eb-89b7-ac533420e4b0.png)

testing >>
![behaviorTesting](https://user-images.githubusercontent.com/20520471/114771940-7a131880-9d6d-11eb-814e-91a18055198e.gif)

there is a method called `on_swipe_complete` it is more simple than swipe then press to delete ..
it depends on how sensitive the items is .. but your choice .. 
docs > https://kivymd.readthedocs.io/en/latest/components/card/
![image](https://user-images.githubusercontent.com/20520471/114772662-5dc3ab80-9d6e-11eb-9fc8-646ada1af49f.png)

**Comment by navjotcis** [comment]
Thank you for good suggestion it will help me and others in future.

**Comment by podraco** [comment]
i'm closing this issue because this is a support request not a feature request nor a bug report.

**Comment by Neizvestnyj** [comment]
I suggest closing the issue, there are no errors/bugs
