### ISSUE TITLE
kivymd.color_definitions

### ISSUE THREAD

**Issue by pademo57** [kivymd/KivyMD#961]
### Description of the Bug

Getting import errors still:

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
File "C:\kivymd\venv\lib\site-packages\kivymd\uix\behaviors\backgroundcolorbehavior.py", line 14, in <module>
     from kivymd.color_definitions import palette, hue, text_colors
 ImportError: cannot import name 'palette' from 'kivymd.color_definitions' (C:\kivymd\venv\lib\site-packages\kivymd\color_definitions.py)

### Versions

* OS: Windows 10
* Python: 3.9
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@pademo57 We do not support version 0.104.1. Use the master version of the KivyMD library7

**Comment by pademo57** [comment]
Thanks but I've decided to go back to Flutter.

**Comment by podraco** [comment]
i wish you luck, if you ever want to come back and try again, DM me, i'm (almost) always available.
