### ISSUE TITLE
text input display on another page

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#965]
### Description of the Feature

Hello everyone
I have a question please... I'm making an app for my project using Kivymd, is there anyway I can view the text input from one screen (the one on the left) to another one (on the right), where one screen I put the information and  the other screen displays it after its saved. 
can someone help me with the code please. Thanks

![Capture2](https://user-images.githubusercontent.com/81992926/115162426-13da0e80-a069-11eb-8631-6f20f1cc3942.PNG)
![175034915_268783744964097_6378413840077581976_n](https://user-images.githubusercontent.com/81992926/115162431-18062c00-a069-11eb-8c01-623035a0dc74.png)

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by podraco** [comment]
# greetings

This is not a bug, but rather a support request, for this kind of questions use the appropiate discord channels.
you can find the server on the repo README.MD

this is not a kivymd related issue, rather a kivy framework issue.

yes it is possible.
you can use the ID of the label between screen or use the app method to share the data between screens.
