### ISSUE TITLE
clicking Expansion Panel in kitchen sink crashes the demo

### ISSUE THREAD

**Issue by ArjixWasTaken** [kivymd/KivyMD#969]
### Description of the Bug

Just as the title says, when I click to preview what the Expansion Panel is, it crashes the app

Error:
```
ImportError: cannot import name 'FakeRectangularElevationBehavior' from 'kivymd.uix.behaviors' (C:\Users\arjix\PycharmProjects\josh\venv\lib\site-packages\kivymd\uix\behaviors\__init__.py)
```

### Code and Logs

*no code, I was just running the demo app*

### Screenshots

![image](https://user-images.githubusercontent.com/53124886/115448884-e3d66b00-a222-11eb-948a-c3f8d6fb8ed7.png)
![image](https://user-images.githubusercontent.com/53124886/115449382-6c550b80-a223-11eb-9aab-bf3640b50103.png)

### Versions

* OS:                Windows 10
* Python:         3.8
* Kivy:              v2.0.0
* KivyMD:        v0.104.1

**Comment by ArjixWasTaken** [comment]
just realized that a lot of things are broken, not just this...

**Comment by podraco** [comment]
???

**Comment by podraco** [comment]
are you installing from master?
it seems that you used the stable version. we're not supporting that anymore.

**Comment by ArjixWasTaken** [comment]
oh

**Comment by podraco** [comment]
please, try following the instructions described on https://github.com/kivymd/KivyMD and https://github.com/kivymd/KivyMD/blob/master/README.md
have fun using kivyMD
