### ISSUE TITLE
MDBottomNavigation Text Size

### ISSUE THREAD

**Issue by obrien-james** [kivymd/KivyMD#97]
Hi,

Is it possible to set the size of the text for each of the MDBottomNavigationItem? Ideally I want be be able to adjust the size of the text when selected as its larger than the un-selected items. 

Also is it possible to control the spacing between them too? 

I have 4 bottom items on my app I'm writing, and when I just need to adjust these to make the items fit better. 

Thanks in advance. 

James

**Comment by ArtemSBulgakov** [comment]
It is impossible. Sizes hardcoded in the code.
https://github.com/HeaTTheatR/KivyMD/blob/7f7bc636e2733cdf1832709f4d981df4e3d22b1f/kivymd/uix/bottomnavigation.py#L294
https://github.com/HeaTTheatR/KivyMD/blob/7f7bc636e2733cdf1832709f4d981df4e3d22b1f/kivymd/uix/bottomnavigation.py#L356
https://github.com/HeaTTheatR/KivyMD/blob/7f7bc636e2733cdf1832709f4d981df4e3d22b1f/kivymd/uix/bottomnavigation.py#L359
https://github.com/HeaTTheatR/KivyMD/blob/7f7bc636e2733cdf1832709f4d981df4e3d22b1f/kivymd/uix/bottomnavigation.py#L388
https://github.com/HeaTTheatR/KivyMD/blob/7f7bc636e2733cdf1832709f4d981df4e3d22b1f/kivymd/uix/bottomnavigation.py#L392

**Comment by HeaTTheatR** [comment]
@obrien-james Show in the screenshot what you want to do.

**Comment by ArtemSBulgakov** [comment]
@obrien-james To control spacing between tabs
```
    MDBottomNavigation:
        on_kv_post: self.ids.tab_bar.spacing = 15
```

**Comment by obrien-james** [comment]
> @obrien-james To control spacing between tabs
> 
> ```
>     MDBottomNavigation:
>         on_kv_post: self.ids.tab_bar.spacing = 15
> ```

Thanks for this, I can increase the spacing between MDBottomNavigationItems, but not reduce them. 

Ive attached a screenshot cropped to the bottom menu, when the "Intervention" menu item is selected the text is right up to the edge of the screen.

![Screenshot 2019-08-30 at 13 56 16](https://user-images.githubusercontent.com/19244448/64022530-5e261900-cb2e-11e9-8019-4eaf0e31becf.png)

**Comment by ArtemSBulgakov** [comment]
@obrien-james All MDBottomNavigationItems have same width. In your case text "Intervention" is very big and takes all width.

**Comment by ArtemSBulgakov** [comment]
@obrien-james Update library. Now you can change font size
```
    MDBottomNavigation:
        # Default values:
        active_font_size: sp(14)
        inactive_font_size: sp(12)
        active_color: self.theme_cls.primary_color
        inactive_color: self.theme_cls.disabled_hint_text_color
```
 or disable increasing size
```
    MDBottomNavigation:
        active_font_size: self.inactive_font_size
```
