### ISSUE TITLE
MDDataTables showing an Error when press check all box

### ISSUE THREAD

**Issue by hmae** [kivymd/KivyMD#970]
### Description of the Bug

testing how heavy the app is when increasing page items number ...
beside at the end of gif .. it is showing an issue when press on All CheckBox ... there is an error occurred ..
any ideas ? 
### Code and Logs
 the following code presents how i create and add widgets...
```python
for fhash, flist in self.finalDuplicat.items():
    # Add Widget Configured in kv file
    self.app.thelist.add_widget(
        Header(
            text=str(fhash),
            secondary_text=str(sizehint(flist[0][0]))
            )
        )
    for i in flist:
        # Add Widget Configured in kv file
        self.app.thelist.add_widget(
            Item(
                text=str(os.path.dirname(i[-1])),
                secondary_text=str(os.path.basename(i[-1])),
                tertiary_text='- created {}  - modified {}'.format(time.ctime(i[2]), time.ctime(i[1]))
                )
            )
self.app.ui.ids.scrl.add_widget(self.app.thelist)
```

### MDDataTable testing GIF >>

![behaviorTesting](https://user-images.githubusercontent.com/20520471/115335357-53097c00-a19d-11eb-98aa-fbfbb61ccc98.gif)

#### Error when press on all CheckBox >>
![image](https://user-images.githubusercontent.com/20520471/115333067-4edb5f80-a199-11eb-9837-ac7abb57bd75.png)

### Versions

* OS: Windows 10
* Python: 3.8.6
* Kivy: 2.0.0
* KivyMD: 0.104.2-dev0

**Comment by HeaTTheatR** [comment]
@hmae Please attach a minimal example that reproduces this error.

**Comment by hmae** [comment]
@HeaTTheatR 
## The code i used to check it ..

```python
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.metrics import dp


class DemoApp(MDApp):
    def build(self):
        rootWidget = MDBoxLayout(orientation="vertical")
        rows = []

        for r in range(100):
            rows.append([f"a{r}", f"b{r}", f"c{r}"])

        Table = MDDataTable(
            check=True,
            use_pagination=True,
            sorted_order="ASC",
            size_hint=(1, 1),
            column_data=[
                ("column 1", dp(32)),
                ("column 2", dp(32)),
                ("column 3", dp(32)),
            ],
            row_data=rows,
        )
        rootWidget.add_widget(Table)
        return rootWidget


if __name__ == "__main__":
    obj = DemoApp()
    obj.run()
```

## here is the test GIF 
the problem mainly comes from rows that outside the window region 
if the row on the screen, nothing happened . but if there are many items that require scroll as in the GIF .. it will cause the issue ..

![mddatatableCheckAllCrash](https://user-images.githubusercontent.com/20520471/118328203-30515580-b506-11eb-8faf-6a2558abc67c.gif)
