### ISSUE TITLE
MDDatePicker Edit date bug

### ISSUE THREAD

**Issue by Aleksey2006** [kivymd/KivyMD#973]
Hello! Running the MD DatePicker example
In date editing mode, I delete everything and enter for example 20 month 1 and immediately the error RecursionError: maximum recursion depth exceeded in __instancecheck__
KivyMD from master

**Comment by Matishock1** [comment]
did you solve this error?

**Comment by HeaTTheatR** [comment]
@Matishock1 No.

**Comment by coder5459** [comment]
is there any way to remove the typing option so that a user does not accidentally stumble upon this bug?

**Comment by HeaTTheatR** [comment]
@coder5459 
`instance_date_picker.ids.edit_icon.disabled = Ttrue`
