### ISSUE TITLE
kivymd/MDNavigationDrawer issues;  ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by Gobline225** [kivymd/KivyMD#974]
### Description of the Bug
(sorry for my English level)
hi guys, im  learning to  create applications with kivy/kivymd, but i got many annoying issues with the MDNavigationDrawer mark up.
i just copied and pasted the first and easiest code provided by the [docs](https://kivymd.readthedocs.io/en/latest/components/navigation-drawer/index.html) about kivymd/MDNavigationDrawer in my editor which  directly gave me as output the folowing error :

```python
ReferenceError: weakly-referenced object no longer exists
```

the full log here
VVVVVVVVVVV
VVVVVVVVVVV
VVVVVVVVVVV
 
```python
[INFO   ] [Logger      ] Record log in /storage/emulated/0/A1/playground/.kivy/logs/kivy_21-04-20_0.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, Jun 15 2020, 02:19:10)
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'ARM'>
[INFO   ] [GL          ] OpenGL renderer <b'Mali-400 MP'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [Base        ] Unknown <android> provider
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/storage/emulated/0/A1/playground/nyyewfile.py", line 42, in <module>
     TestNavigationDrawer().run()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
   File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/weakmethod.py", line 56, in is_dead
     return self.proxy is not None and not bool(dir(self.proxy))
 ReferenceError: weakly-referenced object no longer exists
```

### Code 
here is the code i am talking about :
```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
 
from kivymd.app import MDApp
 
KV = '''
Screen:
 
    MDNavigationLayout:
 
        ScreenManager:
 
            Screen:
 
                BoxLayout:
                    orientation: 'vertical'
 
                    MDToolbar:
                        title: "Navigation Drawer"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
 
                    Widget:
 
 
        MDNavigationDrawer:
            id: nav_drawer
 
            ContentNavigationDrawer:
'''
 
 
class ContentNavigationDrawer(BoxLayout):
    pass
 
 
class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)
 
 
TestNavigationDrawer().run()
```
please help me I'm really tired of looking for solutions without ever finding anything

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by hmae** [comment]
this version is not supported ..
![image](https://user-images.githubusercontent.com/20520471/115975705-515a0280-a567-11eb-87e9-dde76d66c458.png)

### you have to update to latest version KivyMD: v0.104.2.dev0
instructions from here >> [install from master branch ](https://github.com/kivymd/KivyMD#how-to-install)
run ```pip install https://github.com/kivymd/KivyMD/archive/master.zip```

**Comment by Gobline225** [comment]
that is an log from my phone but i have the last version on my computer and it's still the same probleme

**Comment by Gobline225** [comment]
i m just confused. that is note the fact that my kivy version is old (this log come frome my phone; i got the last one on my computer)
, i just tried again the code on my computer in order to have the same issues like always(i had the same issue on my computer) to show you that the problem wasn't about the version, but contrary to what i expected, the windows appeared with no any issues. however, when i ran this code above there are 4 weeks ago  i had always the same error, the same log no matter the device (computer, phone). But i'd like say thank you to you because you still tried to help me solve my problem so thank you :100:

**Comment by hmae** [comment]
## **for Android devices** .. you have to build apk using ```Buildozer```
* Add the link to master branch in requirements in spec file to download dev version .
* screenshot preview instructions:
![image](https://user-images.githubusercontent.com/20520471/115976219-00004200-a56c-11eb-80f9-ed165a462baa.png)


## for desktop it works fine .. no problems .. you have just to check versions ..
instructions from here >> [install from master branch ](https://github.com/kivymd/KivyMD#how-to-install)
### **double** check your kivy and kivymd versions like following :
kivymd Version
![image](https://user-images.githubusercontent.com/20520471/115975935-40aa8c00-a569-11eb-95d1-0ad9a4ec77b2.png)
kivy Version
![image](https://user-images.githubusercontent.com/20520471/115975939-46a06d00-a569-11eb-9ef2-aea0c033363c.png)

## testing gif:
![behaviorTesting](https://user-images.githubusercontent.com/20520471/115975963-823b3700-a569-11eb-9c8d-ee817591ec53.gif)

**test environment:**
- [x] new fresh virtualenv
- [x] install kivymd from ```pip install https://github.com/kivymd/KivyMD/archive/master.zip```
- [x] execute the script in normal way ```python file.py```

@VICTORVICKIE @podraco

**Comment by hmae** [comment]
@Gobline225
i would like to help and solve your problem .. but to do that we have use the latest version .. to overcame all previous issues 🔧 .. 
after that .. we can say if the problem in current version or where 💯

**Comment by podraco** [comment]
@Gobline225  remember that kivyMD development/master version requires kivy >=2.0 as there were breaking changes on the kivy backend on the last version release.

if you need help with kivy MD feel free to join the official kivymd discord server or, the official kivy discord server for a quicker response.

**Comment by Gobline225** [comment]
Ok thank you, i will do

Le dim. 25 avr. 2021 03:04, Manuel Ortiz ***@***.***> a
écrit :
