### ISSUE TITLE
floating bubble with icon 

### ISSUE THREAD

**Issue by Gobline225** [kivymd/KivyMD#975]
### Description of the Feature

you could make a floating bubble which could float over all other application a bite like the one in Facebook messenger.

### Screenshots
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd291xDuYZrHsRLH7q8B0OwpkS7vQzgzb5_XyBdn4vwFxeBpY5gCXKF2GdVc1t88rAYy0&usqp=CAU

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
Not related to material design.
