### ISSUE TITLE
Need a way to disable divider - List

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#977]
### Description of the Feature

Need a way to disable the divider for all List widgets.
Now `BaseListItem` have
Divider mode. Available options are: ‘Full’, ‘Inset’ and default to ‘Full’.
but we also need a `None` option

**Comment by HeaTTheatR** [comment]
@Kulothungan16 
https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/list.py#L747

**Comment by kulothunganug** [comment]
please update the doc, users may get confused
https://kivymd.readthedocs.io/en/latest/components/list/#kivymd.uix.list.BaseListItem.divider
