### ISSUE TITLE
no module named 'kivymd.app' 'kivymd' is not a package

### ISSUE THREAD

**Issue by LivioAlvarenga** [kivymd/KivyMD#978]
### ModuleNotFoundError: No module named 'kivymd.app'; 'kivymd' is not a package

I used the code below in the VScode terminal, but didnt work.

pip install --force-reinstall https://github.com/kivymd/KivyMD/archive/master.zip

after I had this mensage

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source 
of the following dependency conflicts.
spyder 4.1.5 requires pyqt5<5.13; python_version >= "3", which is not installed.
spyder 4.1.5 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
conda 4.10.1 requires ruamel_yaml_conda>=0.11.14, which is not installed.

When trying to run the code below I have this message:

from kivymd.app import MDApp
ModuleNotFoundError: No module named 'kivymd.app'; 'kivymd' is not a package

Can you help me?

### Code and Logs

```python
from kivymd.app import MDApp

class DemoApp(MDApp):
    def build(self):
        return
    

if __name__ == '__main__':
    DemoApp().run()
```

### Screenshots

![Capturar](https://user-images.githubusercontent.com/68560929/117182785-29f80680-adad-11eb-8486-f50ef85677f6.PNG)
![Capturar1](https://user-images.githubusercontent.com/68560929/117182886-498f2f00-adad-11eb-808a-083d3521fe41.PNG)
![Capturar2](https://user-images.githubusercontent.com/68560929/117183077-82c79f00-adad-11eb-8020-60c1d33cf652.PNG)
![Capturar3](https://user-images.githubusercontent.com/68560929/117183553-0e413000-adae-11eb-830b-3150fd487b49.PNG)

### Versions

* OS: 
* Python: 3.8.5 64-bit base: conda
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0
* kivy_deps.gstreamer" 0.3.2
* kivy_deps.angle" 0.3.0
* kivy_deps.glew" 0.3.0
* kivy_deps.sdl2" 0.3.1

**Comment by HeaTTheatR** [comment]
@LivioAlvarenga Don't name your modules by the names of the packages you are using.
