### ISSUE TITLE
MDTextFieldRound color_active issue.

### ISSUE THREAD

**Issue by PositivPy** [kivymd/KivyMD#980]
### Description of the Bug

The `color_active` property of `MDTextFieldRound` has an opacity/transparency issue when used inside a `MDToolbar`. 

Using the private property `_color_active` fixes the problem.

### Code and Logs

Working code:

```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Toolbar"

        MDTextFieldRound:
           id: search_field
           icon_left: "magnify"
           hint_text: "Search..."
           size_hint: 0.5, None
           on_text: app.set_list_md_icons(self.text, True)
           pos_hint: {"center_y": .5,}

            _color_active: 1,1,1,1    <----- This fixes the issue
            normal_color: 1,1,1,1

    MDLabel:
        text: "Content"
        halign: "center"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Screenshots

Bug = `color_active: 1,1,1,1`
No-Bug = `_color_active: 1,1,1,1`

![bug-report-github](https://user-images.githubusercontent.com/60012794/117542087-a6d1ed00-b006-11eb-9f5c-b232ffde0a18.png)

### Versions

* OS: Unix
* Python: 3.8.5
* Kivy==2.0.0
* kivymd==0.104.1

**Comment by Guhan-SenSam** [comment]
Please use the latest version of kivymd version 0.104.2. Clone this repo and use that. The code works properly in 0.104.2
