### ISSUE TITLE
MDCard image size

### ISSUE THREAD

**Issue by PositivPy** [kivymd/KivyMD#982]
I am unable to change the background image size in the MDCard widget. Ideally, I'd like the image to resize automaticaly to the screen's size. 

![github-question](https://user-images.githubusercontent.com/60012794/117829926-b6e60880-b262-11eb-83e0-a7111c0fe48a.png)

**Comment by HeaTTheatR** [comment]
@Syker-uk https://kivymd.readthedocs.io/en/latest/api/kivymd/utils/fitimage/
