### ISSUE TITLE
MDFloatingActionButtonSpeedDial label_color does not work

### ISSUE THREAD

**Issue by mikejaegerberlin** [kivymd/KivyMD#983]
### Description of the Bug

The label_color of the stack buttons can be defined but has no influence on the actual label color. I assigned label_color with "app.primary_color" which should be dark blue. In my developing environment it has the default light blue color. When I am building it with buildozer the label_color stays just white.

This issue was not there when using kivymd 0.104.1

FYI: I assigned the text_color also with app.primary_color so that it can be seen for now. Actually the whole label should be dark blue with these settings but it is not.

kv-file definition
![image](https://user-images.githubusercontent.com/52066086/118305813-caa2a080-b4e8-11eb-8e76-fdbffbce56bc.png)

App in developing environment
![image](https://user-images.githubusercontent.com/52066086/118305936-f756b800-b4e8-11eb-82eb-2d4d9602b758.png)

App on Android phone
![image](https://user-images.githubusercontent.com/52066086/118306008-0f2e3c00-b4e9-11eb-8725-706df8954e61.png)

### Versions

* OS: Windows 10
* Python: 3.7.9 (developing), 3.7.5 (buildozer for android)
* Kivy: v2.0.0
* KivyMD: 0.104.2.dev0,

**Comment by HeaTTheatR** [comment]
@mikejaegerberlin https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/button.py#L1622

**Comment by mikejaegerberlin** [comment]
> @mikejaegerberlin https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/button.py#L1622
@HeaTTheatR 
I don't undertsand. You pointed me to "label_text_color". That is not the issue. That is working and I am using it. The "label_color" is the issue here and does not work ('label_color' itself does not occur in button.py). Or am I doing something fundametally wrong?

**Comment by HeaTTheatR** [comment]
@mikejaegerberlin `MDFloatingActionButtonSpeedDial` class has no `label_color` attribute.

**Comment by mikejaegerberlin** [comment]
Why? v0.104.1 had it?

**Comment by HeaTTheatR** [comment]
@mikejaegerberlin https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/button.py#L1622
