### ISSUE TITLE
MDTextField doesn't show the last letter for long texts

### ISSUE THREAD

**Issue by FilipeMarch** [kivymd/KivyMD#984]
### Description of the Bug

If you type a long text inside a MDTextField, it won't show the last letter typed. You just need to type any string bigger than the MDTextField itself.
You can reproduce the bug by running the following code and then typing "look at the last letter" on MDTextField

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
Screen:
    BoxLayout:
        orientation: 'vertical'
        Widget:
        MDTextField:
            hint_text: "Type a long text"
            mode: "rectangle"
            size_hint_x: 1/3
            pos_hint: {'center_x': 0.5}
            font_size: sp(30)
        Widget:
"""


class MainApp(MDApp):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/23220309/118319873-c15a0980-b4d1-11eb-90ef-1b0aac9597ab.png)

### Versions

* OS: Linux Mint 19.3 Cinnamon
* Python: 3.8.1
* Kivy: 2.0.0
* KivyMD: https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by louisdevie** [comment]
The text field view isn't updated correctly when entering text (and also when moving with home/end keys)

The cursor is outside the frame so the "m" here isn't visible :
![image](https://user-images.githubusercontent.com/56866204/119822020-7f7a8b80-bef3-11eb-81ad-4a1b811789ed.png)

The problem actually comes from kivy (the same thing happens with `kivy.uix.TextEntry`) :
![image](https://user-images.githubusercontent.com/56866204/119822253-bbadec00-bef3-11eb-9e4e-e1efc5faabd8.png)

Tested with
*Python: 3.8.1*
*Kivy: 2.0.0*
*KivyMD: 0.104.2.dev0 (2021-05-27)*

**Comment by HeaTTheatR** [comment]
@k39dev Thanks for your research! In this case, I can close this issue since it has nothing to do with the `KivyMD` library.
