### ISSUE TITLE
Cannot import name 'CheckboxLeftWidget' from 'kivymd.uix.list' 

### ISSUE THREAD

**Issue by JanickiJ** [kivymd/KivyMD#985]
I have an error during debuging kivymd app on android

I python  :  ImportError: cannot import name 'CheckboxLeftWidget' from 'kivymd.uix.list' (/data/user/0/org.test.ospapp/files/app/_python_bundle/site-packages/kivymd/uix/list.pyc)

 I python  : Python for android ended.

--buildozer.spec--
(list) Application requirements
comma separated e.g. requirements = sqlite3,kivy
requirements = python3,datetime,image,pillow,pyrebase,kivy==2.0.0, kivymd==0.104.1, sdl2_ttf == 2.0.15

**Comment by HeaTTheatR** [comment]
@JanickiJ We do not support the KivyMD library version, except for the master version of the library.

**Comment by JanickiJ** [comment]
> @JanickiJ We do not support the KivyMD library version, except for the master version of the library.
So is there any sollution to this problem?

**Comment by HeaTTheatR** [comment]
@JanickiJ https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec#L29

**Comment by JanickiJ** [comment]
@HeaTTheatR 
I changed requirements as you said and restarted buildozer
requirements = python3,kivy==2.0.0,https://github.com/kivymd/KivyMD/archive/master.zip,pygments,sdl2_ttf==2.0.15,pillow

But because of it new error occured 
ModuleNotFoundError: No module named 'chardet'
I added chardet to requirements, restarted buildozer and again the same situation, but now with idna
ModuleNotFoundError: No module named 'inda'
I added ida to requirements, but situation reapeated a few times 

Now my requirements look like this 
requirements = python3,kivy==2.0.0,https://github.com/kivymd/KivyMD/archive/master.zip,pygments,sdl2_ttf==2.0.15,pillow,requests,chardet,idna,pyasn1,urllib3,certifi,pyasn1_modules,pyparsing,httplib2,oauth2client

But new errors are still occuring
