### ISSUE TITLE
Add more functionality to lists

### ISSUE THREAD

**Issue by YarosMallorca** [kivymd/KivyMD#987]
### Description of the Feature

Make if possible to add a background to list items and also organize the with layouts inside every item.

### Versions

* OS: Windows 10
* Python: 3.7.6
* Kivy: 2.0
* KivyMD: Latest

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder Please provide a more detailed description of your proposal ...

**Comment by YarosMallorca** [comment]
Something like YouTube videos list where there is a title, images and more, also I want for the image to be as the item's background,  you understand? @HeaTTheatR

**Comment by HeaTTheatR** [comment]
@YarostheLaunchpadder No I do not understand.
