### ISSUE TITLE
Does KivyMD support Full Screen Dialog?

### ISSUE THREAD

**Issue by sprajagopal** [kivymd/KivyMD#989]
### Description of the Feature

I read through the documentation on MDDialog. The `type` doesn't have a `fullscreen` option. Reference: https://material.io/components/dialogs#usage

![image](https://user-images.githubusercontent.com/6297136/118844245-716fae00-b8e8-11eb-819a-a1b93244e2c7.png)

Is there a workaround to get this behaviour?

**Comment by HeaTTheatR** [comment]
@sprajagopal https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/dialog.py#L177

**Comment by sprajagopal** [comment]
Yeah I went through the source. So I should be using `BaseDialog` instead?

**Comment by HeaTTheatR** [comment]
@sprajagopal Yes.
